### ISSUE TITLE
CLI: --browser-cookies-file

### ISSUE THREAD

**Issue by GregMpour** [gildas-lormeau/SingleFile#1000]
**Describe the bug**
ENOENT: no such file or directory, open 'cookies.txt'

I have checked that I am in the right directory.

**To Reproduce**
docker run singlefile --browser-cookies-file="cookies.txt" "https://stackoverflow.com/" > example.html

**Expected behavior**
For the given page to save correctly as a .html.

**Environment**
 - OS: Win10 Home
 - Browser: Firefox, CLI
 - Version: 64

**Additional context**
Running everything in an Arch WSL2. Cookies.txt generated using https://github.com/lennonhill/cookies-txt.

**Comment by gildas-lormeau** [comment]
I will see if I can reproduce the issue. Meanwhile, could you try "./cookies.txt"?
