### ISSUE TITLE
Whether supporting css-in-js？

### ISSUE THREAD

**Issue by starandtina** [gildas-lormeau/SingleFile#1001]
Hi, thanks for your work, I really like SingleFile. For me, I wanna to save the internal web page into one single HTML file with SingleFile，and the web app was built with React + css-in-js，however, the styles which were injected into HTML using style tags couldn't take effect after saving the page，I just want to make sure that whether SingleFile support the styles dynamically injected into the page？If yes, is there anything I make it wrong？or how can i do it in the right way？Thanks in advance!

**Comment by gildas-lormeau** [comment]
It should work unless you're using Firefox and trying to save imported scoresheets in shadow roots. For example, I was able to save https://codepen.io/piggyslasher/pen/rqPjNj with SingleFile and the saved page is rendered properly.

**Comment by gildas-lormeau** [comment]
I'm closing this issue but feel free to add a comment or reopen it if necessary.
