### ISSUE TITLE
SingleFile error: Cannot read properties of undefined (reading 'getRedirectURL') (Google Drive)

### ISSUE THREAD

**Issue by ryan961** [gildas-lormeau/SingleFile#1002]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/32825698/179404853-0a62c2bb-3667-4fbd-8949-200668700175.png">

**Comment by ryan961** [comment]
Hi, did I open it the wrong way? I did not find the required configuration.🤔

**Comment by ryan961** [comment]
It was fixed after I installed the Google Drive app. Thank you for checking. 🤪

**Comment by gildas-lormeau** [comment]
Thank you, I was able to reproduce the bug. It was happening only once, the first time you enable this destination. That's why you think it's fixed. It should be totally fixed in the version 1.21.19.
