### ISSUE TITLE
WashingtonPost Pages Not Saving Completely

### ISSUE THREAD

**Issue by sj365** [gildas-lormeau/SingleFile#1003]
Hi Gildas-Lormeau,

WashingtonPost.com has started to use a lazy load method that makes it hard to save the page with all images and comments intact.  Singlefile is able to save the pages completely, but it may usually take 3-6 tries until it is done correctly even after scrolling the page myself prior to initiating the Singlefile save.  I used the following two pages to test Singlefile.

https://www.washingtonpost.com/technology/2022/07/16/racist-robots-ai/
https://www.washingtonpost.com/world/2022/07/18/heat-wave-uk-temperatures-40c-record/

I am a grad student who uses this extension for my web research and often have to save dozens of files over the course of 1 day.  Making multiple save attempts for the same file will increase the time and effort to save pages significantly. 
 
Is there something that could be done to ensure Singlefile is correctly saving the pages on the first try?  

I have tried using other extensions such as WebScapbook and SavePageWeb, but neither is capble of saving these pages with all images or without other errors.

In case it helps your research, I'm including the latest post sent to WSB and SPW since it contains videos of the issue in the 2 google drive links.

[WashingtonPost Articles Not Saving Correctly · Issue #285 · danny0838_webscrapbook (1).zip](https://github.com/gildas-lormeau/SingleFile/files/9152804/WashingtonPost.Articles.Not.Saving.Correctly.Issue.285.danny0838_webscrapbook.1.zip)

Thanks

SingleFile 1.21.19
Chrome is up to date
Version 103.0.5060.114 (Official Build) (64-bit)

Processor 11th Gen Intel(R) Core(TM) i9-11980HK @ 2.60GHz 3.30 GHz
Installed RAM 32.0 GB (31.7 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch Touch support with 10 touch points
Edition Windows 11 Home
Version 21H2
Installed on ‎1/‎31/‎2022
OS build 22000.795
Experience Windows Feature Experience Pack 1000.22000.795.0

**Comment by gildas-lormeau** [comment]
I confirm I can reproduce this issue. I'll to take a look at it but it's painful to reverse engineer this kind of feature in order to implement a generic solution. Meanwhile, you can however circumvent this issue by enabling the option `Images > zoom out the page`. Note that you can make sure that it's applied only on WashingtonPost by defining an auto-setting rule if you find this option  a bit annoying.

**Comment by sj365** [comment]
Gildas-lormeau,

This issue has been fixed for months.  Thanks for your updates to the program.  There is a new problem related to the Wpost that I will post in a few minutes.

**Comment by sj365** [comment]
Again this issue has been fixed for a while now.  The map saving issue may still be active in another thread,
