### ISSUE TITLE
WashingtonPost Maps Not Saved Correctly

### ISSUE THREAD

**Issue by sj365** [gildas-lormeau/SingleFile#1004]
Hi Gildas-Lormeau,

The map on this page https://www.washingtonpost.com/dc-md-va/2022/05/15/fairfax-streets-confederate-civil-war/    is not being saved correctly with SingleFile.  Please review the map image as seen on the Wpost page, vs the SingleFile saved .html file.

Thanks

WPost
![WPost map-2022-07-20_152517](https://user-images.githubusercontent.com/52141467/180067311-6f7ff3e5-a06a-46b1-b9db-22980541c6e6.png)

SingleFile
![SFile map-2022-07-20_152614](https://user-images.githubusercontent.com/52141467/180067401-15a657cd-c1ab-422c-8244-56889cd66b54.png)

SingleFile 1.21.19
Chrome is up to date
Version 103.0.5060.114 (Official Build) (64-bit)

Processor 11th Gen Intel(R) Core(TM) i9-11980HK @ 2.60GHz 3.30 GHz
Installed RAM 32.0 GB (31.7 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch Touch support with 10 touch points
Edition Windows 11 Home
Version 21H2
Installed on ‎1/‎31/‎2022
OS build 22000.795
Experience Windows Feature Experience Pack 1000.22000.795.0

**Comment by gildas-lormeau** [comment]
Sorry, for the late answer, I totally forgot this issue. This is actually a known issue. This map is displayed in a "tainted canvas". This is a security feature that blocks scripts on the page to read the bitmap. Unfortunately, this also applies to extensions (I don't know why).

**Comment by gildas-lormeau** [comment]
I'm closing this issue but feel free to add a comment or reopen it if necessary.

**Comment by J-A-M-E-5** [comment]
I have come across this issue with other pages, perhaps there is a solution here? https://stackoverflow.com/a/19896047
