### ISSUE TITLE
toolbar button less intrusive/ dark mode. maybe greyscale?

### ISSUE THREAD

**Issue by justsome12** [gildas-lormeau/SingleFile#1005]
How can I make the button greyscaled or anything else than this bright blue/yellow?

**Comment by gildas-lormeau** [comment]
You are referring to these buttons?

![image](https://user-images.githubusercontent.com/396787/180779546-3e5cfae6-a335-40c3-b3f1-e38c2a829179.png)

**Comment by justsome12** [comment]
> 

no the one in the firefox toolbar/menu
<img width="118" alt="2022-07-26_034725" src="https://user-images.githubusercontent.com/39725549/180904910-10f5f2d5-62dd-4ccb-a5a8-07b612b87272.png">

**Comment by gildas-lormeau** [comment]
Currently, there is no mechanism to change these icons. Actually, I also do like these colors.

**Comment by gildas-lormeau** [comment]
I'm closing this bug because I don't plan to implement a special mechanism to change the icon.
