### ISSUE TITLE
How to inject singlefile to iframes using javascript?

### ISSUE THREAD

**Issue by BoostUpStation** [gildas-lormeau/SingleFile#1010]
Downloading of iframes is working with singlefile extension.
But when i'm using singlefile using javascript by getting the content using singlefile.getPageData
Its not saving the iframe content.

And the html document inside of iframe content is not accessible by javascript methods like 'contentDocument', 'documentElement' etc. So that comes in corps.
But we can get the html content of an iframe by right click and then 'view frame source'

I looked at the config.js
There you told to inject 2 iframe scripts in the iframe, using content_scripts.
But how can we achieve that using js or js console.?
And as far as i know, content_scripts are used in extensions.

**Comment by gildas-lormeau** [comment]
You can use [HTMLIFrameElement#contentDocument](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentDocument) for this. See this example: https://plnkr.co/edit/EHLAEtdQsl3WHMot. However, it won't work with frames loaded from external domains or using the `srcdoc` attribute for security reasons.

**Comment by BoostUpStation** [comment]
Yes, as you said, its not working due to security reasons.
Can't we inject script to the document inside iframe using javascript, just like its done by singleFile extension?
I'm hoping like if it can be done using extension, it should be done using js console too.
Or any way to run singleFile extension from js console? Whenever we want. (this wasn't possible as i saw in the issues and discussion, but maybe now?)

**Comment by gildas-lormeau** [comment]
Well, it's possible to execute a script in the console of Chrome by selecting it, see the screenshot below. However, that would not be very practical to select each frame manually in order to inject the script.

![image](https://user-images.githubusercontent.com/396787/181643437-b6a47acb-b9e3-48e6-a087-0bf58b3a0008.png)

**Comment by gildas-lormeau** [comment]
Note that it should be possible to disable the security features when running Chrome, but it does not work for me, see https://crbug.com/857032.

**Comment by BoostUpStation** [comment]
In my browser also its not working,
Tried many extensions and arguments with chrome exe as well..

Whats good to me is, multiple tabs with auto save feature of singleFile.
Using that does the job pretty well.
Thanks for your support and hard work on this project, highly appreciated.

You may close this issue if you want :) if nothing more has to come from your side.

**Comment by gildas-lormeau** [comment]
Actually, you could use userscripts to achieve this depending on yor needs.

**Comment by gildas-lormeau** [comment]
I'm closing this issue but feel free to add a comment or reopen it if necessary.
