### ISSUE TITLE
Images are not being saved

### ISSUE THREAD

**Issue by soyasoya5** [gildas-lormeau/SingleFile#1012]
**Describe the bug**
Images are not saved

**To Reproduce**
1. Go to [this website](http://91fans.com.cn/post/carcommunityone/)
2. Save page with SingleFile
3. Check saved page, it has no images

**Expected behavior**
Saved page to contain images

**Environment**
 - Browser: Firefox

**Comment by gildas-lormeau** [comment]
I did the same test with the default settings of SingleFile but I was not able to reproduce the bug you described.

For the record, here is saved page zipped: [某汽车社区App 签名和加解密分析 - 奋飞安全 (7_29_2022 4_41_22 PM).zip](https://github.com/gildas-lormeau/SingleFile/files/9220883/App.-.7_29_2022.4_41_22.PM.zip)

**Comment by soyasoya5** [comment]
Thanks for confirming, I did some testing and it seems to be because of [HTTPS-only mode](https://support.mozilla.org/en-US/kb/https-only-prefs). I'm able to save the page after turning it off for the website.
