### ISSUE TITLE
YouTube hyperlink on web page does not work on saved file

### ISSUE THREAD

**Issue by dcard1** [gildas-lormeau/SingleFile#1013]
Using SingleFile to backup my content on social media site Quora.com.

SingleFile does a great job, bring images, formatting, and hyperlinks to Internet articles, etc. to a single file.

However, the hyperlink for Youtube video links does not work.  I only see an image of the video, but cannot click and play.  And if I just copy the link over the image, it is, indeed, an image.

Here is the actual Quora website page:

https://www.quora.com/When-transferring-power-to-the-power-grid-does-the-voltage-have-to-be-higher-than-the-grid-voltage-to-transfer-A-normal-house-in-America-has-240-volts-Does-the-voltage-have-to-be-higher-than-that-to-transfer/answer/Back-Track-28

thx in advance!

**Comment by gildas-lormeau** [comment]
Actually, there's no link because it's not a Youtube video.

**Comment by gildas-lormeau** [comment]
This bug is due to the fact that Quora forces users to click on the play button in order to load the YouTube video. When I click on the play button before saving it with SingleFile, then the link is present in the saved page.

**Comment by dcard1** [comment]
Thanks for a response!  Yes, I can click play and probably automate.  THXs for great application.
