### ISSUE TITLE
Template variables don't work for filename of saved files

### ISSUE THREAD

**Issue by AliM1988** [gildas-lormeau/SingleFile#1014]
Any Template variables specified for filename of saved files will be ignored.

For example I chose {page-title}.html but it becomes a random string like "c76855d1-5080-4a62-9407-280720e489e2.htm"

**Environment:**
 - OS:  Win7 , Win 8
 - Browser: Chrome
 - Version: 103.0.5060.134 (Official Build) (64-bit)

**Comment by gildas-lormeau** [comment]
This is a known issue, cf. https://github.com/gildas-lormeau/SingleFile#known-issues.

> If the file name of a saved page looks like "56833935-156b-4d8c-a00f-19599c6513d3.html", disable the option "Misc > save pages in background". Reinstalling the browser may also fix this issue. You can find more info about this bug [here](https://bugs.chromium.org/p/chromium/issues/detail?id=892133).
