### ISSUE TITLE
Tree menus don't work with enabled "Script" option

### ISSUE THREAD

**Issue by AliM1988** [gildas-lormeau/SingleFile#1015]
In pages like [this](https://lockxls.com/help.asp?hid=gs_addin) , tree menus don't work with enabled "Script" option within saved files. 

**Environment :**
 - OS: Win8
 - Browser: Chrome
 - Version: 103.0.5060.134 (Official Build) (64-bit)

**Comment by gildas-lormeau** [comment]
This is documented in the FAQ, see https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages.
