### ISSUE TITLE
Cant add new profile for settings

### ISSUE THREAD

**Issue by AliM1988** [gildas-lormeau/SingleFile#1017]
I have already 2 profiles, "Default settings" and another. When I add new profile, after enter name, new profile doesn't create.

**Environment :**
OS: Win8
Browser: Chrome
Version: 103.0.5060.134 (Official Build) (64-bit)

**Comment by gildas-lormeau** [comment]
I cannot reproduce this bug. Could you please open chrome-extension://hplobilfmnmpdildkekfnlfkmidnpooe/src/ui/pages/options.html#, press F12 to open the developer tools, click on "Console" tab at the top of the the developer tools window, and copy/paste here the error message you see? Alternatively, you can export your settings, zip the exported file and attach it here. Thus, I should be able to reproduce the bug.

**Comment by AliM1988** [comment]
It is the error appear after enter name for new profile:

> ui-options.js:362 Uncaught (in promise) 
{message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
message: "A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received"
[[Prototype]]: Object

**Comment by gildas-lormeau** [comment]
This error message does not really help me and seems unrelated to your bug. I think I need your settings to understand what's wrong.

**Comment by AliM1988** [comment]
[export.zip](https://github.com/gildas-lormeau/SingleFile/files/9262653/export.zip)
Please see attached file.

**Comment by gildas-lormeau** [comment]
Unfortunately, it's still impossible for me to reproduce the bug. Maybe there is some misunderstanding. What do you mean when you say "new profile doesn't create"?

**Comment by AliM1988** [comment]
I click + button and enter the name for new profile then click OK. So I check profiles, there is no new profile. Actually nothing done.

**Comment by AliM1988** [comment]
I think it is good implement periodic local backup of profiles (e.g. monthly) without overwrite on previous one.
So, the users access all backups. My profiles were reset several times.

**Comment by AliM1988** [comment]
I found it. When I disable synchronize options I can add new profile. If I enable it again, prevoius 2 profiles returns back and it doesn't let me add new profile. Since "synchronize option" there isn't on exported file, you can't reproduce the bug.

If you remember, adding Google account synchronizing was my feature request ([here](https://github.com/gildas-lormeau/SingleFile/issues/296)). Also, I reported that this feature has a bug ([here](https://github.com/gildas-lormeau/SingleFile/issues/766)).

**Comment by everythingness** [comment]
thanks AliM1988 this was driving me batty

**Comment by szenrom** [comment]
Same thing is happening in Firefox. After deselecting "synchronize options" I can add new profile. Otherwise the profile selection window is empty and clicking on any option changes current profile to default one.

OS: MacOS Monterey 12.6.7
Browser: Firefox 115.0.3 (64 bit)

**Comment by gildas-lormeau** [comment]
I identified the cause of this bug. I'm currently implementing a fix.
