### ISSUE TITLE
Saving page stops in Step 2/3

### ISSUE THREAD

**Issue by AliM1988** [gildas-lormeau/SingleFile#1018]
With default settings, saving this [url](https://www.proxoft.com/BinaryViewer.aspx) stops in Step 2/3.

**Environment :**
OS: Win8
Browser: Chrome
Version: 103.0.5060.134 (Official Build) (64-bit)

**Comment by gildas-lormeau** [comment]
I cannot reproduce this issue. This is probably related to a network issue. You should just wait. You can also reduce the value of ``Network > maximum download time (s)` in the options pages of SingleFile to wait less time.

**Comment by pawanpaudel93** [comment]
@gildas-lormeau Try saving for https://wagmi.sh/ and you will probably face same where it stops in step 2/3.

**Comment by gildas-lormeau** [comment]
Thank you @pawanpaudel93. I was able to reproduce and fix the issue. The fix will be available in the next version. I'm not sure this is the same bug as the one reported by @AliM1988 though.
