### ISSUE TITLE
SingleFile on Firefox does not process multiple tabs

### ISSUE THREAD

**Issue by HoudyDoody** [gildas-lormeau/SingleFile#1019]
1) 88 Tabs open, selected 2, right-click SingleFile icon, select "Save tabs," select "Save selected tabs," SingleFile icon displays green box with 3 dots. Nothing happens.
2) Same as above except clicked on SingleFile icon instead of "Save selected tabs." Same results 

(Note: documentation seems to read in one place to select "Save selected tabs," and in another place just to click on the icon. Also, I believe the documentation says the shortcut is CTRL + SHFT + Y, but that does not work. CTRL + ALT + S works. I think there was a conflict with another addon for CTRL + SHFT + Y, so I reassigned the shortcut).

I shut down and restarted Firefox then repeated the above two tests with the same results.
Singlefile works fine with one tab and just clicking on the icon or using CTRL + ALT + S.

OS: Win10 Home 64-bit
HP Laptop: Intel Core i7, 2.60 GHz, 16 GB 
Browser: Firefox 
Version: 103.0.1

I did change any other parameters.

**Comment by gildas-lormeau** [comment]
Thanks for the report. Unfortunately, I can't reproduce the bug you described. However, I did not do the test with 88 tabs already open. I only had 10 tabs. It shouldn't matter anyway.

I confirm that clicking the button should work as well as the shortcut for this use case.

I would recommend you to follow the procedure to fix unknown issues described here: https://github.com/gildas-lormeau/SingleFile#troubleshooting-unknown-issues.

Can you also tell me how dark the green color is (see below)? There are two different colors. The darker one (the one at the right) is displayed very briefly just after the saving starts.

![icons](https://user-images.githubusercontent.com/396787/183407826-6500f278-4afb-4ad7-a7ca-2b11512c254e.png)
