### ISSUE TITLE
SingleFile does not handle multiple tabs

### ISSUE THREAD

**Issue by HoudyDoody** [gildas-lormeau/SingleFile#1020]
1) 88 Tabs open, selected 2, right-click SingleFile icon, select "Save tabs," select "Save selected tabs," SingleFile icon displays green box with 3 dots. Nothing happens.
2) Same as above except clicked on SingleFile icon instead of "Save selected tabs." Same results 

(Note: documentation seems to read in one place to select "Save selected tabs," and in another place just to click on the icon. Also, I believe the documentation says the shortcut is CTRL + SHFT + Y, but that does not work. CTRL + ALT + S works. I think there was a conflict with another addon for CTRL + SHFT + Y, so I reassigned the shortcut).

I shut down and restarted Firefox then repeated the above two tests with the same results.
Singlefile works fine with one tab and just clicking on the icon or using CTRL + ALT + S.

OS: Win10 Home 64-bit
HP Laptop: Intel Core i7, 2.60 GHz, 16 GB 
Browser: Firefox 
Version: 103.0.1

I did not change any other parameters.

**Comment by gildas-lormeau** [comment]
This issue is a duplicate, please see my response here: https://github.com/gildas-lormeau/SingleFile/issues/1019.
