### ISSUE TITLE
Old config values backwards compatibility broken in custom runtimes

### ISSUE THREAD

**Issue by adomasven** [gildas-lormeau/SingleFile#1021]
Hi,

Zotero has recently upgraded the version of SingleFile that it runs and we noticed that scripts are no longer blocked. Upon further inspection we noticed that some of the config values have changed and while there is code in SingleFile for backwards compatibility, it doesn't seem to run when using the "custom environment" runtime, i.e. when calling `singlefile.getPageData(CUSTOM_CONFIG)`.

We'll update our code for new config values now, but this should be fixed so that future changes of config values don't break existing custom runtime configs.

**Comment by gildas-lormeau** [comment]
Hi,

I'm sorry for the inconvenience. I agree that it's a bug in [single-file-cli](https://github.com/gildas-lormeau/single-file-cli) (BTW, note that it's a separate project now). I wrote that kind of code for the extension, see below, but I forgot to implement it in the CLI. Note that I try to avoid bugs but all this work is still "best-effort".

https://github.com/gildas-lormeau/SingleFile/blob/master/src/core/bg/config.js#L193-L196

**Comment by adomasven** [comment]
Shouldn't the first argument to `singlefile.getPageData(CUSTOM_CONFIG)` get run through https://github.com/gildas-lormeau/SingleFile/blob/919d3dc/src/core/bg/config.js#L193-L196 though? I haven't checked the code-paths in SingleFile, but it from our testing it is not, hence the report here. Wouldn't that be a bug in this repo?

**Comment by gildas-lormeau** [comment]
I agree with you though. Ideally this code should be put in a "common" directory so that you don't have this problem in your context.

**Comment by gildas-lormeau** [comment]
I'm closing this issue. I'll try to remember that renaming properties means that I should increment at least the minor part of the version.
