### ISSUE TITLE
SingleFile in Safari does not save deferred images.

### ISSUE THREAD

**Issue by adomasven** [gildas-lormeau/SingleFile#1022]
Hi. At Zotero we had two branches of Zotero Connector extension code, separate for Safari and other browsers, that we have now rebased back onto a single branch. Safari didn't use to support SingleFile before, but now it does. We run SingleFile completely standalone on the page and only provide a shimmed fetch function that ignores CORS. In Chrome SingleFile loads and saves deferred images on https://enviragallery.com/demo/lazy-loading-demo/, but it does not In Safari. I've tried increasing the deferred load timeout and enabling `loadDeferredImagesDispatchScrollEvent`, but Safari still doesn't load deferred images.

**Comment by gildas-lormeau** [comment]
Hi, that's strange. Unfortunately, I don't have a Mac so I cannot test SingleFile in Safari. Did you try to set `loadDeferredImagesKeepZoomLevel` to `true`? By doing so, you are supposed to see the page dezooming to show it completely at the beginning of the process. Do you confirm that you see this behavior? Does it change anything?

**Comment by adomasven** [comment]
No, that doesn't seem to do anything in Safari from my observation and it doesn't fix deferred image saving. Could you point me to the codepoints that govern this and the description on how it's supposed to work? I'll try to troubleshoot it more thoroughly myself then and submit a PR.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback. I may be wrong but I have the impression that the problem is that SingleFile would not be able to override the `clientHeight` property of `documentElement`. This is done here: https://github.com/gildas-lormeau/single-file-core/blob/f919a47104948cf32ca199059ac17391f908faf0/processors/hooks/content/content-hooks-frames-web.js#L85. I think this can be verified by logging `clientHeight` just after this code is executed.

**Comment by adomasven** [comment]
We only inject `single-file-bootstrap.js` and `single-file.js` into Zotero Connector, so that code does not run in either plugin.

**Comment by gildas-lormeau** [comment]
Once built, this code is present in `single-file-hooks-frames.js`. So, you have to inject this script to make the feature work.

**Comment by adomasven** [comment]
Sure, but deferred images load without it in Chrome, how come? If we don't want to load frames, is it ok to inject the script in the top frame?

**Comment by gildas-lormeau** [comment]
Are you sure you're not injecting this script in Chrome? It can't work if this script is not injected. Note that MV3 would prevent you to do inject dynamically scripts. You have to declare it in the manifest file, see https://github.com/gildas-lormeau/SingleFile-Lite/blob/main/manifest.json#L27.

**Comment by adomasven** [comment]
Either way, I injected that script into Safari and got:

```
[Log] Pre override
[Log] 375
[Log] Post override
[Log] 4049
```
for the override line, so it works fine.

**Comment by gildas-lormeau** [comment]
The code in your previous comment is not directly related to deferred loading. It's a piece of code that tries to find the `currentSrc` of images.

If you see the logs, then it means the code is indeed injected?

**Comment by gildas-lormeau** [comment]
Regarding the logs, they look fine. Do you confirm that images were not loaded when you injected the script?

**Comment by adomasven** [comment]
Ok, I had the SingleFile extension enabled in Chrome, and if I disable it deferred image loading no longer works there either. Thanks for helping me through this confusion. So what do I need to inject into the main page beyond `single-file.js` and `single-file-bootstrap.js` to get deferred image saving to work? We don't need frame saving. Also you should probably update the Wiki with this information.

**Comment by adomasven** [comment]
> Regarding the logs, they look fine. Do you confirm that images were not loaded when you injected the script?

Yes, the images are not loaded.

**Comment by gildas-lormeau** [comment]
When you set `loadDeferredImagesKeepZoomLevel` to `true` and inject the script, do you see the page that is zoomed out?

**Comment by adomasven** [comment]
Yep, that works and actually saves all deferred images, but we cannot use it with this UX in Safari.

**Comment by gildas-lormeau** [comment]
I understand, it's still a step forward though and it allows me to understand the issue. I think the simplest way for you to debug this problem is to put a `debugger;` at the beginning of `loadDeferredImagesStart` and compare the execution of the code in Safari and Chrome.

**Comment by adomasven** [comment]
I'm not sure if I will be able to troubleshoot this successfully today, and I am going away for a week, so if there's no more comments on my part -- sorry! Thanks for the help so far. Could you confirm whether we need to inject `single-file-frames.js` for any other functionality aside from frame saving, like deferred image loading, or is `single-file-hooks-frames.js` enough?

**Comment by gildas-lormeau** [comment]
I did some debugging in Chrome. You have to know that loading deferred images is painful, so SingleFile uses multiple techniques to do so. It looks like the code below is the one that makes the feature work on this page. This code override the `Image` constructor in order to detect when the `src` is changed. If I remove this code and save the page with SingleFile, the images are not saved.
https://github.com/gildas-lormeau/single-file-core/blob/f919a47104948cf32ca199059ac17391f908faf0/processors/hooks/content/content-hooks-frames-web.js#L108-L139

You need to inject `single-file-frames.js` as a *content* script in order to get all the frames. If you don't save frames, you shouldn't need to inject it.

You need to inject `single-file-hooks-frames.js` as a *regular script* (i.e. "main" in MV3) in the page itself (and all the frames ideally) in order to save deferred images and fonts loaded with the `FontFace` API (this can be tested with www.theverge.com). The role of this script is to override native APIs when necessary.

I guess it works when with SingleFile installed because it injects the `single-file-hooks-frames.js` script for you and Zotero can interact with it. It probably means that you're unable to inject it in Zotero, for some reasons.

**Comment by adomasven** [comment]
Ok, I'm getting back to this. I'm now testing on Chrome with SingleFile extension disabled, since this turned out to not be just the Safari issue. I've injected both `single-file-frames.js` and `single-file-hooks-frames.js` via manifest.json with this config:

```JSON
{
	"matches": ["http://*/*", "https://*/*"],
	"run_at": "document_start",
	"all_frames": true,
	"js": [
		"lib/SingleFile/single-file-hooks-frames.js",
		"lib/SingleFile/single-file-frames.js"
	]
}
```

I see the scripts loaded via developer tools for the page, and I see `loadDeferredImagesStart` being executed. However, the monkey-patched `globalThis.Image` constructor is never called. Saving works with `loadDeferredImagesKeepZoomLevel = true`, but not without it.

If I step through `loadDeferredImagesStart` in the debugger, I see the document get zoomed out, but nothing actually loads during the debugger steps, and then it zooms back in.

Unfortunately, I cannot compare this to what happens when the SingleFile chrome extension is enabled, because that code is minified. Any other debugging steps that I may perform here?

**Comment by gildas-lormeau** [comment]
Following this discussion https://github.com/gildas-lormeau/SingleFile/pull/1027, were you able to build a non-minified version of the code?

**Comment by adomasven** [comment]
Ok, I figured it out. The issue is NOT doing what you've been telling me to do, hah. I wasn't injecting `single-file-hooks-frames.js` as a regular script. Additional stress in the docs about this file would be beneficial, explicitly stating that injecting this code in a privileged scope will make deferred image loading not work. Like in Safari we have a privileged extension JS scope/world and then the regular execution scope, similar to web extensions. In MV3 you can indeed specify the execution world in `manifest.json`, not sure about MV2. So in MV2, you need code like

```js
_injectSingleFileHooks: function() {
  const scriptElement = document.createElement("script");
  scriptElement.src = getExtensionURL("lib/SingleFile/single-file-hooks-frames.js");
  scriptElement.async = false;
  document.body.appendChild(scriptElement);
  scriptElement.remove();
}
```

to correctly manually inject the file. Injecting via web extension APIs is **wrong**.

Thanks a ton for help debugging this!

**Comment by gildas-lormeau** [comment]
Thank you for the feedback, I'm glad to hear you were able to find the cause of the issue :)
