### ISSUE TITLE
Not working on this page

### ISSUE THREAD

**Issue by AoiReiwa** [gildas-lormeau/SingleFile#1023]
Hello, This extension is not working on this page https://www.reuters.com/investigates/special-report/taiwan-china-wargames/

It only copys the text. Can you adjust it?

**Comment by gildas-lormeau** [comment]
Unfortunately, saving interactive elements does not work most of the time, see https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages for more info.

**Comment by gildas-lormeau** [comment]
@KeBugCheck Are the same person as here https://forums.zotero.org/discussion/comment/417028? If you are, please note that I do my best to fix the bugs that are brought to my attention. As far as I know, you have not reported any bugs to me. So, feel free to report them, or discuss them on the existing bug files. I answer to everybody.
