### ISSUE TITLE
Custom SingleFile use in a web extension works in Chrome, but stalls in Firefox

### ISSUE THREAD

**Issue by adomasven** [gildas-lormeau/SingleFile#1026]
We redesigned our use of SingleFile in the Zotero Connector to not rely on any web extension APIs for Safari support. This means, among other things, that we do not inject the `browser.` API shim for Chrome. While SingleFile works fine in Chrome, in Firefox it stalls out. I've discovered that this is due to SingleFile trying to set a deferred image loading timeout by sending the message to the background page via `browser.runtime.sendMessage({ method: "singlefile.lazyTimeout.setTimeout", type, delay })`. The check for this call fails in Chrome as `browser.` is undefined, but succeeds in Firefox.

There either needs to be some initial message communication in `singlefile.js`, checking, whether anything is handling `singlefile.` namespace messages in the background page, or a pref that explicitly disables use of any web extension APIs.

**Comment by adomasven** [comment]
Also as a side note, is there any benefit to setting the timeout in the background page? Are we potentially missing some functionality due to not handling that? We could technically implement messaging to the bg page even on Safari if running the timeout there has additional benefits, but this should also be explicitly documented in the wiki.

**Comment by gildas-lormeau** [comment]
This issue is weird because the check is stricter than what you wrote, see below.

https://github.com/gildas-lormeau/single-file-core/blob/e31da2d12122b68d14b0f4aae135d30e92297c1a/processors/lazy/content/content-lazy-loader.js#L185-L200

Can you give me more details about the error you're encountering? 

The timeout in the background page because the browser may decide to execute the callbacks later otherwise. This is for example the case when the tab being saved is not the active tab if I remember correctly..

**Comment by adomasven** [comment]
> This issue is weird because the check is stricter than what you wrote, see below. I expect `browser && browser.runtime && browser.runtime.sendMessage` to be `false` in your environment.

Yes, all of those are true in a Firefox Zotero Connector extension. SingleFile code is still running in an content script environment in our case for Firefox.

**Comment by gildas-lormeau** [comment]
I added an option named `loadDeferredImagesNativeTimeout` (`undefined` by default) in the last version. If you set it to `true`, then SingleFile should use `setTimeout` instead of sending a message to the background page.

**Comment by adomasven** [comment]
Yes, the option fixes the issue for Firefox. Thanks!
