### ISSUE TITLE
Picture on web not download when it is xx.googleusercontent.com/xxxx

### ISSUE THREAD

**Issue by issuex** [gildas-lormeau/SingleFile#1028]
**Describe the bug**
Picture on web not download when it is xx.googleusercontent.com/xxxx (picture not contain file extension)

**To Reproduce**
Sample steps to reproduce the behavior:
1. Go to https://www.zscaler.com/blogs/security-research/analysis-domain-fronting-technique-abuse-and-hiding-cdns
2. Save page with SingleFile
3. `https://lh5.googleusercontent.com/FpX8Zs9q6YVSkU9PNwIX-elhQIoAwpP47uUe0TpmmxM9QmZMaKfxTzPygq9BNPPHeoJ8rasQCFV7kxm6k-t7Es11cSyxEVK2aB07IRM9ufLpzZa2xRpQR19dfUQE60hGDUlr78qt` and etc. not download to `*.html`

**Expected behavior**
`lh5.googleusercontent.com/xxx` should be downloaded and able to open offline.

**Environment**
 - OS: Win10
 - Browser: Firefox
 - Version: 103

**Comment by gildas-lormeau** [comment]
I was not able to reproduce the issue with the default settings. Did you change any option in SingleFile?

**Comment by issuex** [comment]
I have tested again. and not found previous problem. Not sure why.
