### ISSUE TITLE
File name not using page title

### ISSUE THREAD

**Issue by MadDogDean** [gildas-lormeau/SingleFile#1031]
When saving file using Brave Browser, [Version 1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit)] on Win 11 x64, the correct file name is not saved.

Options indicate _File name > {page-title}.html_ but the file name suggested a a pseudo-random string (see attached screenshot)

![image](https://user-images.githubusercontent.com/23712335/187711897-0791bf84-cd8d-440c-963d-429862f093ac.png)

**Comment by gildas-lormeau** [comment]
This is an annoying bug in Chrome that Google does not want to fix. To circumvent it, you can disable the option "Misc > save pages in background". FYI? it's documented in the known issues here: https://github.com/gildas-lormeau/SingleFile#known-issues.

**Comment by MadDogDean** [comment]
Thanks for the update. I searched but didn't find the earlier issue.
Cheers, MadDogDean

**Comment by gildas-lormeau** [comment]
You're welcome. Actually, this link is the second one you can find in the document template when you create a bug report in SingleFile.
