### ISSUE TITLE
Bullet Points / presenter-bullets (How to save them)

### ISSUE THREAD

**Issue by MPSA1** [gildas-lormeau/SingleFile#1032]
Hello.
I have some websites with Bullet Points / presenter-bullets hidden. I have to click them to open them and it works/see only one at a time click. 
How I can save the entire webpage with these Bullet Points / presenter-bullets (information/text inside) to be open latter ?
At the normal configuration it does not save it.
What Can I do to make it save the Bullet Points / presenter-bullets ?
Thanks in advance.

**Comment by gildas-lormeau** [comment]
Sorry for the late answer, your websites probably depend on JavaScript to work properly. There is a question related to this issue in the FAQ here: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages. Unfortunately, the technical approach in SingleFile makes the support of JavaScript very limited.
