### ISSUE TITLE
Losing deffered images on chrome (but works perfect on firefox)

### ISSUE THREAD

**Issue by hyunki** [gildas-lormeau/SingleFile#1035]
Hi Thank you for the good extension!
I've been using this for scrap pages I like.
but I found that it is not working on chrome proplerly. (Access granted for file url)

It is working on firefox without any settings change but in chrome images are not loading.
Chrome extension settings are not touched except grant access to file url.

Tested site url: https://imgur.com/gallery/4yoGf

![image](https://user-images.githubusercontent.com/25163778/192662304-980d2e84-c52b-41ca-96a1-77440c8721dc.png)
671kb on chrome
37mb on firefox

chrome result
![image](https://user-images.githubusercontent.com/25163778/192662584-6570bd54-f861-4ce0-9957-4d413627705e.png)

**Comment by gildas-lormeau** [comment]
I did multiple tests on https://imgur.com/gallery/4yoGf with the stable version of Chrome (106.0.5249.62), and every time images are properly saved on my end. Maybe this issue would be due to a conflict with another extension?

**Comment by hyunki** [comment]
> I did multiple tests on https://imgur.com/gallery/4yoGf with the stable version of Chrome (106.0.5249.62), and every time images are properly saved on my end. Maybe this issue would be due to a conflict with another extension?

Thank you for the quick reply. Yes it seems like my problem.
I tested it with another computer and it works perfectly.
I'll test with new installation and let you know thanks

**Comment by hyunki** [comment]
> I did multiple tests on https://imgur.com/gallery/4yoGf with the stable version of Chrome (106.0.5249.62), and every time images are properly saved on my end. Maybe this issue would be due to a conflict with another extension?

I tested with new chrome installation without any extension.
same result. no single picture is saved.
I suspect "internet download manager" and "Adguard" but it wasn't.
I uninstalled both program but problem is reproduced.

![image](https://user-images.githubusercontent.com/25163778/192924120-481727d8-460f-45cd-b859-f6a766e7c32b.png)
good news is the more I click the 'save the page', the bigger the page size.
first attempt file size 566kb with no single image.
same on second attempt.
after 4~5 clicks, it worked.

**Comment by gildas-lormeau** [comment]
It might be related to a network issue. Did you try to increase the option "Images > save deferred images > maximum idle time (ms)"? If you see for example that you need to save the page 3 times to get the all the images, then multiplying the value by 3 should solve the issue.

**Comment by gildas-lormeau** [comment]
@hyunki Any news regarding this issue?

**Comment by hyunki** [comment]
> @hyunki Any news regarding this issue?

sorry I forgot to close this. Same problem for me... I guess browser need to be reinstalled.

**Comment by gildas-lormeau** [comment]
Did you try to increase the option "Images > save deferred images > maximum idle time (ms)"?

**Comment by hyunki** [comment]
Now 'SingleFile' works perfectly on 1500ms. I didn't touch anything. Chrome version 106.0.5249.119

FYI on that test day My Idle time was set on 4000ms.
But it wasn't work. Looooong scroll and same result.
![image](https://user-images.githubusercontent.com/25163778/197396515-0fdd0756-54a0-4668-8521-b76eabd32fda.png)

**Comment by hyunki** [comment]
![image](https://user-images.githubusercontent.com/25163778/197396656-f6e8efde-1775-4160-9288-6b2e91e1a9bc.png)
Chrome still can't catch images outside the scroll bar,
but singlefile can!
![image](https://user-images.githubusercontent.com/25163778/197396672-ae3d52a4-3246-48f9-8946-08ec1f352b4e.png)

**Comment by hyunki** [comment]
![image](https://user-images.githubusercontent.com/25163778/197396740-89fc61e0-ddb6-4a2f-aee1-9ce1154d5503.png)
and now, it saves all the image and is only 7mb.
It was 43mb on that day.

**Comment by gildas-lormeau** [comment]
Great :)
