### ISSUE TITLE
Save already saved html

### ISSUE THREAD

**Issue by Entretoize** [gildas-lormeau/SingleFile#104]
Hello,
I saved a website homepage with SingleFile, it worked perfectly, but I'm modifying it and want to save again and it just show a "ERR" message on the extension icon.
Is it supposed to work ?

Thanks

**Comment by gildas-lormeau** [comment]
Hi,

Yes it's supposed to work. Could you post the URL of the website?

**Comment by Entretoize** [comment]
For example:

https://ld-wp.template-help.com/wordpress_64774/



Le jeu. 29 nov. 2018 à 11:19, Gildas Lormeau <notifications@github.com> a
écrit :

**Comment by Entretoize** [comment]
I don't see anything in the console...

**Comment by gildas-lormeau** [comment]
Thanks for the URL. I'm not able to reproduce your issue and I am able to save the page with SingleFile on Chrome and Firefox without any problem. Your issue could be related to the other extensions you installed. Did you try to disable them, as suggested [here](https://github.com/gildas-lormeau/SingleFile#known-issues)?

**Comment by Entretoize** [comment]
Yes I just tried, also tried in private mode by enabling only SingleFile
and I still have the error. (I'm in chrome)


Cordialement, Grégory Defaisse


Le jeu. 29 nov. 2018 à 19:31, Gildas Lormeau <notifications@github.com> a
écrit :

**Comment by gildas-lormeau** [comment]
When the error occurs, could you please 
 - open chrome://extensions/, 
 - enable the developer mode with the toggle switch at the upper right of the page,
 - click on the link "Inspect views background page" displayed below the extension ID in the list of extensions below,
 - tell me if you see an error message?

Cordialement :)

**Comment by Entretoize** [comment]
Seems to work by adding "file:///*/" in permissions in the manifest...

**Comment by gildas-lormeau** [comment]
Or simply give the extension the right to access to the filesystem. There's a toggle switch for that in the details page of the extension.

**Comment by Entretoize** [comment]
OK, thanks, it would have been nice to have an alert telling me that, no ?

Le ven. 30 nov. 2018 à 09:47, Gildas Lormeau <notifications@github.com> a
écrit :

**Comment by gildas-lormeau** [comment]
Yes, I confirm it would be better :p. I also wished people would read the docs ;)
