### ISSUE TITLE
Zotero Connector for Safari: single-file-hooks-frames.js conflicts with Tampermonkey

### ISSUE THREAD

**Issue by adomasven** [gildas-lormeau/SingleFile#1040]
Our users reported that when using the Zotero Connector for Safari along with Tampermonkey links on Google Search do not work. After investigating I found that removing the injection of single-file-hooks-frames.js on pageload fixed the issue. Note that the Zotero Connector for Safari is an App Extension, not a Web Extension. Tampermonkey appears to be an App Extension too. I don't know if that is relevant though.

Let me know if I can help in debugging this.

**Comment by dstillman** [comment]
This [isn't caused by SingleFile](https://github.com/zotero/zotero-connectors/issues/404#issuecomment-1280516010) — @gildas-lormeau, please disregard.
