### ISSUE TITLE
Singlefile Error on Page Save

### ISSUE THREAD

**Issue by sj365** [gildas-lormeau/SingleFile#1041]
Im trying to save the following page from washingtonpost.com and Singlefile errors out and does not save the page.
Is there a way to create an error log and forward to you?

https://www.washingtonpost.com/politics/2022/10/11/kanye-west-tucker-carlson-fox-news/

https://drive.google.com/file/d/1XorA12oysGKTV6lvvz6i_ik3uLv8G_3i/view?usp=sharing
video of error

Processor   11th Gen Intel(R) Core(TM) i9-11980HK @ 2.60GHz   3.30 GHz
Installed RAM   32.0 GB (31.7 GB usable)
System type 64-bit operating system, x64-based processor
Edition Windows 11 Pro
Version 22H2
OS build    22621.674
Experience  Windows Feature Experience Pack 1000.22634.1000.0

Chrome is up to date
Version 106.0.5249.119 (Official Build) (64-bit)

**Comment by gildas-lormeau** [comment]
I think I was able to reproduce the issue and circumvent it. The fix will be available in the next version.
