### ISSUE TITLE
Save html pages as chrome saves when right click and "save as" .html

### ISSUE THREAD

**Issue by renovatio118** [gildas-lormeau/SingleFile#1043]
I've tried many different settings but i can't figure out how can i save all open tabs the way you save them one by one when right click on a page and clicking "save as" .html
This way it saves the html file and a folder with all photos inside. 
Is there a way to do this?

**Comment by piegamesde** [comment]
See also https://github.com/gildas-lormeau/SingleFileZ/issues/119
