### ISSUE TITLE
Not working well on this page

### ISSUE THREAD

**Issue by Yam78000** [gildas-lormeau/SingleFile#1045]
**Describe the bug**
Source code is displayed as web page content.

**To Reproduce**
1. Go to (https://formations.lechemindelanature.com/login/index.php)
2. Click on SingleFile icon to print the page
3. Open the output file
4. See error. I guess a CSS file is displayed 

**Expected behavior**
Print just the visible page part

**Screenshots**
Look at the zip in attachment. There are my SingleFile print + Firefox complete saving

**Environment**
 - OS: [Linux mint 20 64bit]
 - Browser: [Firefox]
 - Version: [102.0.1 (64 bits)]

**Additional context**
The single file printing is working with "Save Page WE" extension on Brave Browser [Version 1.41.96 Chromium: 103.0.5060.114 (Build officiel) (64 bits)])

Thanks in advance
Best regards

[Le Chemin de la Nature (print issue).zip](https://github.com/gildas-lormeau/SingleFile/files/9901832/Le.Chemin.de.la.Nature.print.issue.zip)

**Comment by gildas-lormeau** [comment]
Thank you for the detailed description of the bug. I confirm I was able to reproduce it and fix it. I just uploaded the version 1.21.25 of SingleFile containing the fix, it should be available for download on the Mozilla store in ~ 24-48h hopefully.

**Comment by gildas-lormeau** [comment]
The new version is now available for download.

**Comment by Yam78000** [comment]
Thank you, it works perfectly ! 
Better than "Save Page WE" plugin ;-)

**Comment by gildas-lormeau** [comment]
You're welcome and thanks for the kind words!
