### ISSUE TITLE
PLEASE ALLOW TO SAVE TO CONFIGURABLE FOLDER

### ISSUE THREAD

**Issue by dvassy** [gildas-lormeau/SingleFile#1050]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...

This module will not save to the Folder I want. The Firefox option to "always ask where to save" a download is ignored

**Describe the solution you'd like**

At a minimum: prompt for a target folder when saving, and the Firefox toggle that indicates to do so is ticked

**Describe alternatives you've considered (optional)**

Have a separately configurable folder for the saved files. This does not exclude the solution above

**Additional context (optional)**

**Comment by gildas-lormeau** [comment]
Please enable 'File name > open the "Save as" dialog to confirm the file name' in the options page of SingleFile.
