### ISSUE TITLE
Can a page like this be functional after saving it with SingleFile?

### ISSUE THREAD

**Issue by tchflws** [gildas-lormeau/SingleFile#1052]
https://oimo.io/works/bubbles/

looks like a fun demo but when saved it does not work at all - which was to be expected?

**Comment by gildas-lormeau** [comment]
See https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages.

You're lucky, disabling `HTML Content > save raw page` and `Network > blocked resources > scripts` in the options page of SingleFile seems to do the job.
