### ISSUE TITLE
Digest for filenames should not have to include the saved date in the content

### ISSUE THREAD

**Issue by DerSaidin** [gildas-lormeau/SingleFile#1058]
## Problem

When using `{digest-sha-256}` in the output filename, it is never the same because the content being hashed includes a header added by SingleFile with the saved date and time.

When I save the same page twice, a few seconds apart, I get:

```
$ diff -U0 2022-11-24T05_02_56.280Z_5e2798cd38b50f9cba55ff22d6324cf4aa597e6bc59ee56bde66ef8223c8ccc0.html  2022-11-24T05_03_08.506Z_3fd5f6d8c5c71850890633c9f9aa6f2c56fa6e14de8faa9ee96644095012794e.html
--- 2022-11-24T05_02_56.280Z_5e2798cd38b50f9cba55ff22d6324cf4aa597e6bc59ee56bde66ef8223c8ccc0.html	2022-11-23 21:03:00.087905016 -0800
+++ 2022-11-24T05_03_08.506Z_3fd5f6d8c5c71850890633c9f9aa6f2c56fa6e14de8faa9ee96644095012794e.html	2022-11-23 21:03:11.924158961 -0800
@@ -4 +4 @@
- saved date: Wed Nov 23 2022 21:02:56 GMT-0800 (Pacific Standard Time)
+ saved date: Wed Nov 23 2022 21:03:08 GMT-0800 (Pacific Standard Time)
```

This means I can't use `{digest-sha-256}` in filenames with the `skip duplicate files` option.

## Suggested Solution

Add a check box option under `HTML content` called `include saved date` (default to true).

Unchecking this option will cause the output to not have the `saved date: ...` line.

This should mean saving the same page repeatedly will get the same digest, and it is now possible to get the same output file path with `{digest-sha-256}` in the output filename (if the page content is the same and there is no date/time variables in the filename).

## Alternative Solution

Compute the digest of the file content without the SingleFile generated header, so the digest does not include the date.

The disadvantage(s) of this approach are:
* The digest in the filename will no longer match running `sha256sum` on the resulting file.
* The file will contain a date visited, but the file contents may be true for another more recent date. This raises more questions - should the date in the file be updated?

**Comment by gildas-lormeau** [comment]
Thank you, I agree with the issue you described and I also think the first proposition is the best one. I'll implement it.

**Comment by gildas-lormeau** [comment]
The new option has been added in the version 1.21.32 I just published.
