### ISSUE TITLE
Possible to combine/reference multiple pages ?

### ISSUE THREAD

**Issue by boweden** [gildas-lormeau/SingleFile#106]
Hi, thanks for this wonderful little gem.

I was wondering if it's possible to reference other pages from the same website by either:

1) downloading each page separately and referencing them with relative paths  (or)
2) downloading each page separately and "somehow" merging them together into a single file

For instance, this site has a walkthrough for a game split into multiple pages:
http://www.sierrahelp.com/Walkthroughs/FatesOfTwinionWalkthrough.html

I guess my question is if it's possible to download each page separately (FatesOfTwinionWalkthroughPt1.html, FatesOfTwinionWalkthroughPt2.html, etc...) and reference each part relatively, or simply combine them all somehow into a single file ?  Is something like this possible?

Thank you

**Comment by gildas-lormeau** [comment]
Hi, thanks for the kind words! Both suggestions are, in my view, feasible. However, they require some work and I am not sure I would be able to handle such a task. I'm also wondering if these features should not be implemented in another extension based on SingleFile code, but specialized in website crawling. This extension could also use the IndexedDB database to store pages.

**Comment by boweden** [comment]
Completely understand if it's currently outside the scope of the project :)

I can certainly get by with converting each page to PDF and later combining them all into a single file. Not the same as the original, but close enough :) 

Thank you again.

**Comment by AliM1988** [comment]
I make it for you, just download it!
[Walkthroughs.zip](https://github.com/gildas-lormeau/SingleFile/files/2683114/Walkthroughs.zip)

**Comment by boweden** [comment]
OMG! First, sincere apologies that I couldn't reply to you sooner.

Second, Wow.  Thank you so much for your persistence in finding a solution!  I didn't think it was that simple.  And I certainly couldn't have figured that out on my own (especially just Step 1)  Heh.  :) 

I think most, if not all, of my use cases where the number of html files involved are within reasonable limits. So the process of editing each html file is certainly feasible and should be no problem. :)

Thank you once again for this wonderful tool.  I don't think many people realize its full power and potential. ;)

**Comment by boweden** [comment]
By the way, just to summarize & clarify for any curious lurkers:

The process detailed by AliM1988 is the solution to my Request #1 mentioned in the first post.

"I was wondering if it's possible to reference other pages from the same website by either:

1. **downloading each page separately and referencing them with relative paths** (or)
2. downloading each page separately and "somehow" merging them together into a single file"

**Comment by boweden** [comment]
Sorry again for the bother. I tried your method on a slightly more complicated scenario where the Table of Contents is on a separate frame on the left:

https://www.falcom.co.jp/monarch/manual/index_e.html

I saved the individual pages separately, but combining them with the ToC frame on the side gives a blank page.  My question is, will your method work only if the side frame does not exist?

**Comment by gildas-lormeau** [comment]
@boweden It's maybe a bug in SingleFile. Let me check...

**Comment by boweden** [comment]
Ah, so it was a bug. I was wondering if it had anything to do with the procedure AliM1988 described.

Glad it helped identify the bug.  One less problem to deal with :)

**Comment by gildas-lormeau** [comment]
@boweden Yes, yet another bug fixed. Thanks :)

**Comment by AliM1988** [comment]
@boweden I'm Sorry for late response. I hope my post be useful. I have another general and easy solution to save multiple pages. You should the software that download whole website. I suggest Offline Explorer Enterprise. By the way, this is the list of tools that I googled:

- EasyWeb2Pic 
- EasyWebSave
- Maxprog Web Dumper 
- Offline Explorer Enterprise
- Portable Offline Browser 
- Teleport Pro 
- Web Copier
- Web Site eXtractor
- Website Downloader 
- WebZip 
- WWW2Image

**Comment by boweden** [comment]
Hi Ali,
Thanks for taking the trouble in searching for those programs.  I looked up some of them before, most of them are commercial products, and they are still not as robust and flexible as SingleFile.  So for now, I'm okay with saving multiple pages as PDF and merging them together into a single file. 

Who knows, maybe someday SingleFile (or some kind of fork of it) can reach that vision.  That will be the "final solution" to archiving the internet. ;) :+1:

**Comment by AliM1988** [comment]
Your'e Welcome.

**Comment by lumnikemel** [comment]
@boweden @AliM1988 
You didn't list HTTrack as a tool to download websites. It's a gold standard, and it's free.

**Comment by boweden** [comment]
@lumnikemel 
Thank you for this.  I didn't know about that one.  It does look very interesting.

I tested this program to download this game walkthrough page:  http://www.cytheraguides.com/archives/ferazel/

It creates hundreds of files, and sure it works, but a "single" file would be more elegant :)

But thank you nevertheless.

**Comment by doplu** [comment]
Hello,
For the merging html files together into one file html, imho you can use the windows freeware : TXTcollector https://bluefive.pairsite.com/txtcollector.htm

**Comment by doplu** [comment]
Maybe this extension will also help ?
https://chrome.google.com/webstore/detail/merge-windows/mmpokgfcmbkfdeibafoafkiijdbfblfg

**Comment by gildas-lormeau** [comment]
I'm closing this issue but I've opened the same on SingleFileZ, cf. https://github.com/gildas-lormeau/SingleFileZ/issues/20.

**Comment by Unknow0059** [comment]
It's a shame neither SingleFile nor SingleFileZ save hyperlinked pages nor rewrite hyperlinks to local file:// links. It doesn't seem that HTTRack can do that easily either, all while saving to a single HTML page.
I guess a separate script would have to be made for such purposes.

**Comment by gildas-lormeau** [comment]
@Unknow0059 It is possible. You can run for example this command and it should replace the links with the corresponding file:// URIs:
```
single-file https://www.my-site.com --crawl-links=true --crawl-max-depth=1 --crawl-replace-urls=true
```

**Comment by Unknow0059** [comment]
Oh, I see. Thanks! I'll just use that. Very handy! 😄

**Comment by gildas-lormeau** [comment]
You're welcome. Feel free to open an issue if it does not work as expected. It's a recent feature.
