### ISSUE TITLE
Images and in-line content on certain articles disappear during page interaction and scrolling

### ISSUE THREAD

**Issue by Roundlay** [gildas-lormeau/SingleFile#1060]
Bug description: 

- Images and in-line content on certain New Yorker articles are displayed incorrectly, or disappear during page interaction and scrolling.
    - For example:
        - [https://www.newyorker.com/magazine/2022/01/24/the-rise-of-ai-fighter-pilots](https://www.newyorker.com/magazine/2022/01/24/the-rise-of-ai-fighter-pilots)
        -  [https://www.newyorker.com/science/elements/shedding-light-on-untouchable-sea-creatures](https://www.newyorker.com/science/elements/shedding-light-on-untouchable-sea-creatures)
        - [https://www.newyorker.com/tech/annals-of-technology/can-computers-learn-common-sense](https://www.newyorker.com/tech/annals-of-technology/can-computers-learn-common-sense)
- The New Yorker logo appears to load correctly at first, but either disappears when the page has been fully loaded, or disappears after scrolling past the page's introductory artwork. (See videos.)
- If the pages are autoscrolled to an area below the page's introductory artwork immediately upon loading, the logo doesn't appear at all.
- The article's in-line images and embedded audio only load when `set content security policy` is unchecked, but loading these is still inconsistent. Otherwise, the in-line images and embedded content don't load at all. _This option seems to change how the logo issue occurs._

- I've tried enabling and disabling various SingleFile options that seem relevant to this issue, but none of them resolved it.
    - Enabled/disabled Zoom out the page
    - Enabled/disabled Save deferred images
    - Enabled/disabled Dispatch "scroll" event
    - Enabled/disabled Disabling blocked resources
    - Enabled/disabled Compress HTML content
    - Enabled/disabled Remove hidden elements
    - Enabled/disabled Set content security policy
        - Disabling this fixed the in-line loading issue, but the Logo issue remained. In-line content fails to load when this is enabled.
    - Enabled/disabled Save raw page
    - Enabled/disabled Remove unused styles
    - Enabled/disabled Compress CSS content
    - Enabled/disabled Move external styles to head

1. Go to [https://www.newyorker.com/magazine/2022/01/24/the-rise-of-ai-fighter-pilots](https://www.newyorker.com/magazine/2022/01/24/the-rise-of-ai-fighter-pilots)
2. Try saving the site using SingleFile.
3. Open the saved version of the site.
4. Wait for the local version to load and notice the missing assets appear and disappear.

Expected behaviour: site assets are loaded and respond to scroll events in the same way they respond at the source. That is, the New Yorker logo at the top of the screen shouldn't disappear when scrolling.

**Environment**
 - OS: Windows 11 Pro 21H2 22000.1219
 - Browser: Google Chrome
 - Version: Version 107.0.5304.107 (Official Build) (64-bit)

**Comment by gildas-lormeau** [comment]
Thank you, I couldn't reproduce the issue with the default settings. It looks like you unchecked "Network > blocked resources > scripts" which could lead to this kind of issue.

**Comment by Roundlay** [comment]
That did the trick! Thank you!
