### ISSUE TITLE
Infinite fetch when "deferred images" option is enabled

### ISSUE THREAD

**Issue by bryanph** [gildas-lormeau/SingleFile#1061]
**Describe the bug**
On this particular page SingleFile goes into an infinite fetch loop when "save deferred images" is enabled: https://www.neelnanda.io/blog/43-making-friends

**To Reproduce**
1. Enable "save deferred images"
2. Go to https://www.neelnanda.io/blog/43-making-friends
3. Click on "save page with singlefile"
4. See network tab, there is an infinite fetch happening

**Expected behavior**
It does not get stuck in "Deferred Images..." infinitely

Any particular situation in which something might this might happen?

**Environment**
 - OS: Win 11
 - Browser: Chrome
 - Version:  107.0.5304.107

**Additional context**
When disabling "save deferred images" it does work

**Comment by gildas-lormeau** [comment]
Thank you for the detailed report. I confirm I was able to reproduce the issue and fix it. The fix will be available in the next version.

**Comment by gildas-lormeau** [comment]
It's fixed in the version 1.21.31 that I've just published.
