### ISSUE TITLE
Ask both 'Infobar content' and the 'Save as' immediately and only then start the process from 'Frame contents'

### ISSUE THREAD

**Issue by Timo-Fi** [gildas-lormeau/SingleFile#1075]
Could it be so that when the SingleFile button is pressed, both the 'Infobar content' and the 'Save as pathname' dialogs would be immediately presented to the user, and only then would start the main process (that show the 'Frame contents' etc at the lower-left corner ).  With my lowly PC and sluggish connection, when creating SingleFiles from heavy pages, there is first a long pause (nothing seems to happen), then a very long pause while all the process steps are run, and only then the two dialogs are presented (so I need to wait for them). 

.

**Comment by gildas-lormeau** [comment]
Doesn't the icon of the extension change? If not, then there's nothing I can do. It just means that your PC is doing something else and won't let SingleFile display anything.

**Comment by Timo-Fi** [comment]
> Doesn't the icon of the extension change?

Icon changes properly, that is not related to my point. My feeling is that the following would be  a worthy improvement, I explain step by step:

1. I press the icon.
2. Now, **immediately**, the Save Path -dialog would be presented (and also the InfoBox contents -dialog would be presented in case it is set to be presented in the options).   
3. Only then would start the main process of collection the page contents.

Currently, on a hefty page, after pressing the icon it takes **plenty** of time before the dialogs appear.

**Comment by gildas-lormeau** [comment]
This is not technically possible to display the save as popup before the page is processed, unfortunately.
