### ISSUE TITLE
There is no dialog box to choose where to save the resulting html file ("Save as...")

### ISSUE THREAD

**Issue by iG8R** [gildas-lormeau/SingleFile#1080]
Hi.

**Describe the bug**
There is no dialog box to choose where to save the resulting html file ("Save as...") after SingleFile processed the page, it is saved into the Downloads folder by default. Other add-ons, e.g. SavePageWE, don't have this issue.

**To Reproduce**
1. Go to any webpage, where SingFile can work
2. Save page with SingleFile
3. See how the resulting file is saved into the Downloads folder without any dialog boxes where to save it.

**Expected behavior**
There should be a dialog box that asks where to save the resulting html file.

**Environment**
Microsoft Windows [Version 10.0.19043.1415]
Firefox 108.0.1 (64-bit)

**Comment by iG8R** [comment]
Sorry, just found out that the "open the "Save as" dialog to confirm the file name" was unchecked but I used SingleFile more than 3 years and everything worked well until today and the aforementioned option was checked.

**Comment by gildas-lormeau** [comment]
No problem, I'm glad you found the option. Maybe you changed the default behavior in Firefox. It might cause this kind of issue.
