### ISSUE TITLE
In Info Bar, make the URL a "clickable" link

### ISSUE THREAD

**Issue by MeNeDaUnAl** [gildas-lormeau/SingleFile#1082]
Hello, I usually insert the {url-href} of the page in the Info Bar, so to easily trace the origin of the saved page.
It would be very useful if it was a link, so I could directly click on it to access the actual online page, instead of highlighting it (not so easy) and copying to a new tab or opening it.
Keep up the good work, this is an indispensable addon.

**Comment by gildas-lormeau** [comment]
There's already a link, it's the icon at the right of the text. Is this button a problem?

**Comment by MeNeDaUnAl** [comment]
You have to forgive me, I swear I hadn't seen it: the button is there and works properly.
This has existed for a long time? I can't understand how I did not notice... Shame on me.
As justification I can only say that I use a quite long template 
**TITLE: {page-title} -- URL: {url-href} -- ({date-iso} -- {time-iso})**
and I don't look often at it until the end.

Perhaps it would be appropriate to make the icon more evident, for example with a color;
but it doesn't matter, once you know where to look... that's exactly what I wanted.
Many thanks for your prompt reply and for your patience...

**Comment by gildas-lormeau** [comment]
It exists for years, the close button at the left is more recent though. I didn't want to emphasize the button too much to favor the text (it's successful!), I'll think about it.

**Comment by MeNeDaUnAl** [comment]
That means that it's completely my fault: I have been stoned, I must admit it. :D
Alright, the important thing is that I found a solution. 
Thanks again and best wishes for the new year!

**Comment by gildas-lormeau** [comment]
You're welcome, I also wish you a good New Year's Eve :)
