### ISSUE TITLE
weibo.com's images can't be saved

### ISSUE THREAD

**Issue by zzt741** [gildas-lormeau/SingleFile#1096]
It seems like all pages on weibo.com can not save their images properly, after saving, these pages, when open them, all images are transparent, I have tried to change various options, but it not work. And in the old version of weibo.com, only a few images can be saved. Can you solve it?

**Environment**
 - OS: [Win10 64 bytes family Chinese version]
 - Browser: [Firefox 109.0 & Chrome 109.0]
 - Version: [1.21.33 & 1.21.34]

**Comment by gildas-lormeau** [comment]
That's because weibo "protects" its images, you have to enable `Network > pass "Referer" header after a cross-origin request error` in the options page of SingleFile.

**Comment by zzt741** [comment]
thanks!
