### ISSUE TITLE
Cannot archive Docker Blog

### ISSUE THREAD

**Issue by ygxxii** [gildas-lormeau/SingleFile#1101]
**To Reproduce**
1. Go to `https://www.docker.com/blog/*`, such as [https://www.docker.com/blog/docker-containerd-integration/](https://www.docker.com/blog/docker-containerd-integration/)
2. Click SingleFile icon to save the current page
3. See browser unresponsive script warning

**Environment**
 - OS: MacOS 13.1 (Intel)
 - Browser: Google Chrome 109.0.5414.119 (x86_64) & Firefox 109.0
 - Version: Singlefile 1.21.35

**Comment by gildas-lormeau** [comment]
Thank you for the report, I was able to reproduce an error but it did not lead to the browser being unresponsive. It's fixed in the last version I just published. Please let me know if it fixes your issue as well.

**Comment by ygxxii** [comment]
Issue solved! Awesome! Thanks you very very very much!!!
