### ISSUE TITLE
twitch.tv pages are missing images after recent Chrome update

### ISSUE THREAD

**Issue by datahoarderdude** [gildas-lormeau/SingleFile#1103]
## **Describe the bug**
On or around January 10th, 2023 SingleFile lost the ability to save every element of a twitch.tv page while running in Chrome on Windows 10. This seemed to coincide with the release of Chrome 109.0.5414.

Since then, twitch.tv pages are missing the static image that would be saved in the area where the video stream would normally be. **Please note that I am not attempting to save the video stream** (h.264, audio, etc). 

With past versions of Chrome, the SingleFile extension would grab a single frame from the video and embed it as a static image in the page. It was like taking a screenshot of the page which is exactly what I wanted.  **I am not trying to download moving video.**

Oddly enough this still works just fine under Firefox 109.0. I do not want to switch browsers unless I absolutely must.

## **To Reproduce**
1. Go to any stream on twitch.tv using Chrome v109.0.5414.120 on Windows 10 Pro 21H2
2. Run the SingleFile extension
3. Observe that the video area is replaced with a black, empty image

## **Expected behavior**
The video area on the page should be replaced with a static image that shows whatever was on the stream when the SingleFile extension downloaded the page. This was what the extension was doing up until recently (until ~January 10th 2023)..

## **Screenshots**
This is the result after running SingleFile in Chrome:
![image](https://user-images.githubusercontent.com/123902583/215354569-af0218af-ac43-4e97-906e-2363b6765b2f.png)

This is the result after running SingleFile in Firefox, on the same stream:
![image](https://user-images.githubusercontent.com/123902583/215354613-afff1bdd-a1e3-4143-923f-dad53f3131cb.png)

## **Environment**
 - OS: Win10 Pro 21H2
 - Browser: Chrome v109.0.5414.120 (this version does not work)
 - SingleFile for Chrome: v1.21.37
 - Browser: Firefox v109.0 (this version has no problems)
 - SingleFile for Firefox: v1.21.36

## **Additional context**
I have tried:
* Logging in / out of twitch
* Disabling hardware acceleration in Chrome
* Restart browser
* Clear browser cache
* Incognito Mode
* Separate PC running same OS, Chrome and extension versions

**Comment by gildas-lormeau** [comment]
Thank you very much for the detailed report, I was able to reproduce and fix the issue in the version `1.21.38` I've just uploaded on the store. I should be available for download in the coming hours hopefully.

**Comment by datahoarderdude** [comment]
Nice! Thank you, I really appreciate the fast response.

**Comment by gildas-lormeau** [comment]
you're welcome :)
