### ISSUE TITLE
File name doesn't match the page title when saving a page.

### ISSUE THREAD

**Issue by windvane** [gildas-lormeau/SingleFile#1106]
File name doesn't match the page title when saving a page.
SingleFile 1.21.38

**Comment by gildas-lormeau** [comment]
What do you mean?

**Comment by windvane** [comment]
See the image below.
![2023-01-31_215254](https://user-images.githubusercontent.com/12993295/215779997-e7f2dff1-6562-4b38-a2ca-f1a7ee1896c6.png)

**Comment by cj-neo** [comment]
Please turn it off in the options (other) "save pages in background"
than you will get the correct title name!

**Comment by windvane** [comment]
> Please, uncheck "save pages in background" in options (Misc) than you will get the correct title name!
> 
> Option: save pages in background Uncheck this option if you get invalid file names like "37bec68b-446a-46a5-8642-19a89c231b46.html" or interrupted downloads when saving pages. You can also uncheck this option if you want the "Save as" dialog to remember the last saved path. Unchecking this option prevent using sub-directories in filename templates.

Thank you.
