### ISSUE TITLE
How to save file to sub-folder by template ?

### ISSUE THREAD

**Issue by cj-neo** [gildas-lormeau/SingleFile#1108]
**Describe**
I know  in order to save the file  to any specified folder must be use single-file-companion or SingleFile Companion Lite.

But after using the above two software, I still can't save the file to the subfolder specified by the template.

Because the accumulated files so Much,I want to dynamically generate them according to the year and month's sub folder.
(e.g. "archives/{year-locale}/{month-locale}/{day-locale}/{page-title}.html").

error message:

When using single-file-companion:
show message: SingleFile error: [object Object] (Companion)

When using SingleFile Companion Lite:
Plug-in components crash directly

**Environment**
Using Chrome browser, also tested in incognito window

Can help me solve the problem? THX!

**Comment by gildas-lormeau** [comment]
Thank you for the report, I was able to reproduce the issue with SingleFile Companion Lite, I did not test and fix SingleFile Companion yet. The fix is available in the new version of SingleFile Companion Lite I just uploaded on GitHub.

**Comment by cj-neo** [comment]
> 感謝您的報告，我能夠使用 SingleFile Companion Lite 重現該問題，但我尚未測試和修復 SingleFile Companion。`1.0.5`我剛剛在 GitHub 上上傳的 SingleFile Companion Lite版本中提供了該修復程序。
> 
> 編輯：它`1.0.22`也在 SingleFile Companion 版本中得到修復。

Extremely grateful to you, Helped me a lot :P

**Comment by gildas-lormeau** [comment]
You're welcome, I'm glad to hear it :)
