### ISSUE TITLE
Incorrect UI (Firefox)

### ISSUE THREAD

**Issue by rstp14** [gildas-lormeau/SingleFile#111]
**Describe the bug**
Incorrect UI

**Screenshots**
![Screenshots](https://user-images.githubusercontent.com/8574197/50008406-1faef500-ffc5-11e8-9e8c-29b94a0b21de.png)
![Screenshots](https://user-images.githubusercontent.com/8574197/50008420-2e95a780-ffc5-11e8-9e37-5d5a780efde9.png)

**Environment**
 - OS: Windows 8.1 Pro
 - Browser: Firefox
 - Version: 64.0

**Comment by gildas-lormeau** [comment]
Thanks fore reporting the issue @rstp14. I noticed that too. Unfortunately, I cannot do anything to fix this apart from re-implementing dialog boxes from scratch. SingleFile is relying on standard confirm/alert/prompt dialog boxes. It is a Firefox bug but I thought it was a problem on Firefox 65 only... Maybe I'll need to re-implement them.

**Comment by gildas-lormeau** [comment]
It shouls be fixed now. I implemented a [(quick and dirty) workaround](https://github.com/gildas-lormeau/SingleFile/commit/fc55913916ec97dca81d5432b250ac7c318b4a68) by hiding the options page while the popup are displayed.

**Comment by rstp14** [comment]
Thank you, it works.
![Screenshots](https://user-images.githubusercontent.com/8574197/50041741-a36eed00-006a-11e9-9ab2-b4afe0ca76eb.png)

**Comment by gildas-lormeau** [comment]
Great!
