### ISSUE TITLE
SingleFile error: interrupted - on trying to save a github page

### ISSUE THREAD

**Issue by Andy2No** [gildas-lormeau/SingleFile#1111]
"Please ensure that you do not find an answer before reporting the issue:"

I see no open issues, only a closed one from a couple of years ago, saying the page was too complicated.  I assume a page on github is always quite simple.

**Describe the bug**

I get a "SingleFile error: interrupted" - on trying to save a github page

**To Reproduce**

1. Go to:
https://github.com/DhrBaksteen/ArduinoOPL2

2. Try to save it with SingleFile.

**Environment**
 - OS: Win 7 Pro SP1
 - Browser: Firefox 
 - Version: 102.7.0esr (64-bit), up to date.

**Additional context**

I updated SingleFile earlier today.  I hadn't previously had any problems saving pages from github using it before that.

**Comment by gildas-lormeau** [comment]
Thank you for the report. Unfortunately, I was not able to reproduce the issue. Did you change any setting in SingleFile?

**Comment by Andy2No** [comment]
> Thank you for the report. Unfortunately, I was not able to reproduce the issue. Did you change any setting in SingleFile?

Sorry.  I hadn't seen your reply.  I can't reproduce it today either.

I have *Fite name template* set to *{page-title}.html* with *open the **"Save As"** dialog to confirm the file name* ticked.  I don't think I've changed anything else.
