### ISSUE TITLE
Images not shown when saving dreamix-video-editing.github.io

### ISSUE THREAD

**Issue by Emasoft** [gildas-lormeau/SingleFile#1112]
Images not shown when saving [dreamix-video-editing.github.io](https://dreamix-video-editing.github.io/)

**Comment by gildas-lormeau** [comment]
These are videos actually, you can save them by disabling `Network > blocked resources > videos` in the options page of SingleFile.

**Comment by Emasoft** [comment]
Still not working. I also enabled scripts downloading, but nothing. Even the arrow buttons are not workings.

**Comment by gildas-lormeau** [comment]
I'm sorry but I cannot reproduce your issue.

**Comment by gildas-lormeau** [comment]
From my point of view, this issue is fixed. Feel free to give more details if necessary.
