### ISSUE TITLE
How to enable user defined Profile?

### ISSUE THREAD

**Issue by AliM1988** [gildas-lormeau/SingleFile#112]
**Describe the bug**
Thank you for implementation of my suggestion [here](https://github.com/gildas-lormeau/SingleFile/issues/97#issuecomment-440855865)

There is a bug. I can make as many as profile, but I can't enable them. Just "Default Setting" is enabled. When I select my own profile, SingleFile follow settings from "Default Setting" and after opening Option again, I see "Default Setting" is selected not previous profile that I selected!

**Environment**
 - OS: Win8
 - Browser: Chrome
 - Version: 70

Regard

**Comment by gildas-lormeau** [comment]
You have to open the context menu (on the webpage or SingleFile button) and, in the "Select profile" entry, choose the profile you want.

**Comment by AliM1988** [comment]
Hi
Thanks
