### ISSUE TITLE
I would like to download the whole Website inlcuding submenus and responsive design

### ISSUE THREAD

**Issue by ne0YT** [gildas-lormeau/SingleFile#1122]
**Is your feature request related to a problem? Please describe.**
I would like to have a working offline copy of a full (quite small) webpage.
So I would love to be abel to combine multiple subpages and areas and include responsive parts by moving around and clicking stuff on the page.

**Describe the solution you'd like**
I would love to have a second option to "record everything" and then "stop recording / save page) so I could move around and resize the webpage to then save every part of it so it can be responsive and have subpages saved to it.
that would be really great. Because it would allow me to maybe take old insecure webpages which don't have any serverside functionality and hos tthem somewhere just by serving the files. reducing serverload and also being able to browse something while beeing completely offline.

**Comment by gildas-lormeau** [comment]
Unfortunately, what you describe is very hard to achieve and thus of the scope of SingleFile. What you want is to save pages in WARC. See for example https://chrome.google.com/webstore/detail/warcreate/kenncghfghgolcbmckhiljgaabnpcaaa?hl=en&authuser=0.
