### ISSUE TITLE
Can't save local files with assets.

### ISSUE THREAD

**Issue by Antiwhore** [gildas-lormeau/SingleFile#1123]
This workaround is not working. My local file in turn references other local files and shitty Firefox won't let them load for "security reasons", so the page is loaded without styles and media files.

_Originally posted by @Antiwhore in https://github.com/gildas-lormeau/SingleFile/issues/7#issuecomment-1433146602_

**Comment by gildas-lormeau** [comment]
Please continue the discussion in the original thread, https://github.com/gildas-lormeau/SingleFile/issues/7#issuecomment-1433146602
