### ISSUE TITLE
Pass Iframe's HTML string to bypass CSP

### ISSUE THREAD

**Issue by dontfireme** [gildas-lormeau/SingleFile#1131]
I use SingleFile by injecting the script into websites (https://github.com/gildas-lormeau/SingleFile/blob/master/lib/single-file.js). SingleFile won't capture iframes if it can't access it (`iframe.contentDocument` will throw/return null). Would it be possible to bypass it somehow if I pass iframe's content manually? I can do that because I open Chrome via puppeteer, so from puppeteer I can grab any iframe's HTML. Is it possible somehow?

**Comment by gildas-lormeau** [comment]
The solution is to inject SingleFile scripts in the frames, the SingleFile will use the Message API to communicate with frames. That's how the CLI tool works.
