### ISSUE TITLE
htm or html files with attached _files folders

### ISSUE THREAD

**Issue by andreyjc** [gildas-lormeau/SingleFile#1132]
I have over 100 htm and html files with _files folders attached to them and want to convert them to single files. SingleFile will do it but change the layout and remove pictures, not duplicate the page. I tried changing various options and could not get it to work. I am using Firefox on Windows 10.

**Comment by xiaobai987292** [comment]
you can upload you html files to you web server then you can get these html url 
if you do not have any web server, you can use iis in stead

**Comment by andreyjc** [comment]
I handled it with Google chrome webhost add-on as prescribed. Thanks!
