### ISSUE TITLE
how get the SingleFile html result by tampermonkey script?

### ISSUE THREAD

**Issue by xiaobai987292** [gildas-lormeau/SingleFile#1133]
my script is like this 
```
// ==UserScript==
// @name         Convert title to kebab-case
// @namespace    https://github.com/gildas-lormeau/SingleFile
// @version      1.0
// @description  [SingleFile] Convert title to kebab-case
// @author       Gildas Lormeau
// @match        *://*/*
// @noframes
// @grant        GM_xmlhttpRequest
// @grant GM_setClipboard
// ==/UserScript==


(() => {

  let title;
  dispatchEvent(new CustomEvent("single-file-user-script-init"));

  addEventListener("single-file-on-after-capture-request", () => {
   var html_txt=document.documentElement.outerHTML;   
// here i want get the SingleFile reusult
  });

})();
```
i  want to save the SingleFile html to my server, but html_txt is the weburl original response.
how i get the SingleFile pagedata?

**Comment by gildas-lormeau** [comment]
I confirm what you want to achieve is not possible, on purpose, for security/privacy. The simplest way to fix this issue is to make your server compatible with WebDAV and configure the Destination in the options page.

**Comment by gildas-lormeau** [comment]
No, it's a deliberate choice I made because I want to make sure SingleFile does not introduce security issues.
