### ISSUE TITLE
Saving to WebDAV with a file name that is too long leads to an infinite loop

### ISSUE THREAD

**Issue by fengqi** [gildas-lormeau/SingleFile#1136]
In Linux, when a filename is greater than 255 Byte, it will report ENAMETOOLONG (36). Almost all webdav servers will return a 404 error.

In Singlefile, when a 404 error occurs, it tries to call MKCOL to create a directory, and then retries to put the file. However, it enters into a loop because the real reason for the 404 error is not that the directory does not exist.

https://github.com/gildas-lormeau/SingleFile/blob/master/src/core/bg/downloads.js#L227

**Environment**
 - OS: Ubuntu 20.4.5
 - Browser: Chrome 110.0.5481.177
 - Version: 1.21.39

**Additional context**
filename template: /{year-locale}/{month-locale}/{url-hostname} - {page-title}.html

**Comment by gildas-lormeau** [comment]
Thank you, I fixed the infinite loop issue. However, the error will still be thrown. 

You could use a template similar to this one to circumvent this problem:
`/{year-locale}/{month-locale}/{url-hostname}[64] - {page-title}[184].html`

**Comment by gildas-lormeau** [comment]
I'm closing the issue but feel free to reopen it if needed.

**Comment by fengqi** [comment]
Thank you for fixing it. dufs returns 403 It may be checking the length of the file name instead of triggering a system-level error.
