### ISSUE TITLE
Firefox protected pages

### ISSUE THREAD

**Issue by harryray33** [gildas-lormeau/SingleFile#1137]
Would it be possible to enable Singlefile to save Firefox protected pages, if it isn't. are you aware of any extension that can?

Thanks.

**Comment by gildas-lormeau** [comment]
You can do this by using a browser from another vendor, e.g. Chrome or Safari.

**Comment by harryray33** [comment]
At the moment, I have to use a scrolling screenshot programme to capture, for example, the about:addons page or about:support  in Firefox. It's not really satisfactory as it's saved as a .jpg rather than text.
I can't seem to find anything that will capture these pages.

**Comment by gildas-lormeau** [comment]
Indeed, I think it's impossible to capture the content of these internal pages with an extension unfortunately.
