### ISSUE TITLE
Translation of labels related to "Auto-settings rules"

### ISSUE THREAD

**Issue by gildas-lormeau** [gildas-lormeau/SingleFile#114]
Hi @yfdyh000, @Shitennouji, @rstp14, @xesarni, @KrasnayaPloshchad, @s8321414, @Vdragon @zerng07

I finished to implement the "Auto-settings rules" in the options page. This feature allows associating a settings profile with a complete or partial URL. Thus, you can set custom settings for specific URLs automatically. This feature allows to set separated profiles for the regular save and the auto-save, or to disable the auto-save. The new labels to translate are the following ones:

```
optionsAutoSettingsSubTitle: "Auto-settings rules"
optionsAutoSettingsUrl: "URL"
optionsAutoSettingsUrlPlaceholder: "Type a complete or partial URL (e.g. example.com)"
optionsAutoSettingsProfile: "Profile"
optionsAutoSettingsAutoSaveProfile: "Auto-save profile"
optionsAutoSettingsShowAllProfiles: "display all profiles"
optionsAutoSettingsShowAutoSaveProfile: "display 'Auto-save profile' column"
optionsUpdateRuleTooltip: "Update the rule"
optionsDeleteRuleTooltip: "Delete the rule"
optionsAddRuleTooltip: "Add the rule",
optionsValidateChangesTooltip: "Validate changes"
optionsDeleteRuleConfirm: "Confirm deletion of the selected rule"
profileDisabled: "Disabled"
```

Your help in translating these labels would be very welcome :)

If you want to contribute to the translation into zh-TW, you have to translate all the keys defined in the `messages.json` file. Some of them have already been translated (cf. https://github.com/gildas-lormeau/SingleFile/issues/108#issuecomment-447164565).

Status:

- [x] French translation
- [x] Polish translation
- [x] Russian translation
- [x] Japanese translation
- [x] Chinese (zh-CN) translation

**Comment by Shitennouji** [comment]
optionsAutoSettingsSubTitle": "自動設定のルール"
optionsAutoSettingsUrl": "URL"
optionsAutoSettingsUrlPlaceholder: "完全または部分的な URL を入力します (例 example.com)"
optionsAutoSettingsProfile: "プロファイル"
optionsAutoSettingsAutoSaveProfile: "プロファイルの自動保存"
optionsAutoSettingsShowAllProfiles: "すべてのプロファイルを表示します"
optionsAutoSettingsShowAutoSaveProfile: "「プロファイルの自動保存」列を表示する"
optionsUpdateRuleTooltip: "ルールを更新する"
optionsDeleteRuleTooltip: "ルールを削除する"
optionsAddRuleTooltip: "ルールを追加する"
optionsValidateChangesTooltip: "変更内容を検証します"
optionsDeleteRuleConfirm: "選択したルールの削除を確認する"
profileDisabled: "無効"

**Comment by gildas-lormeau** [comment]
Thank you very much @Shitennouji
