### ISSUE TITLE
Images from googleusercontent are not saved

### ISSUE THREAD

**Issue by shirooo39** [gildas-lormeau/SingleFile#1142]
For questions, please create or update a thread here: 
https://github.com/gildas-lormeau/SingleFile/discussions

Please ensure that you do not find an answer before reporting the issue:
 - in the FAQ: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md
 - in the list of known issues: https://github.com/gildas-lormeau/SingleFile#known-issues
 - in the help page embedded in the extension

**Describe the bug**
I'm trying to completely download everything from [NovelAI Prompt Guide - lunarmimi.net](https://lunarmimi.net/freebies/novelai-anime-girl-prompt-guide/) but a lot of the images are not saved.
The site author seems to be pulling the image from their Google Photos or Google Drive, which they should be publicly shared and can be saved.
I tried to save the page for 2x but same result.
this is exactly the same issue as [this one](https://github.com/gildas-lormeau/SingleFile/issues/1028), but there's no solution at all to that one.

**To Reproduce**
1. Go to [NovelAI Prompt Guide - lunarmimi.net](https://lunarmimi.net/freebies/novelai-anime-girl-prompt-guide/)
2. Click on the extension to save the page, as written on the Firefox Addon page
3. Wait for it to encode assets into base64
4. Once it's done, open the saved page.
5. Scroll down to the bottom of the site.
This site contains a lot of images but the 2nd time I tried, only some are saved and the rest are gone.

**Expected behavior**
I expect it to completely save everything that has been loaded and probably cached images too, into a single HTML file.

**Screenshots**
this is how the site look like when visited normally, there are tons of images and each sections can be scrolled down.
![image](https://user-images.githubusercontent.com/38461122/225353674-82f4912c-b6b4-4eff-aac1-ca15f7b285a0.png)

but this what I got... all of the images are not saved...
![image](https://user-images.githubusercontent.com/38461122/225353922-c48bb255-f5e8-4951-9eb8-d9e909d017ba.png)
(even the scrollbar doesn't seem to be showing, meaning that the addon doesn't know that there are scrollable sections on the page.

**Environment**
 - OS: Windows 11 Pro
 - Browser: Firefox x64 110.01
 - Version: version of what? the addon?

**Additional context**

**Comment by shirooo39** [comment]
![image](https://user-images.githubusercontent.com/38461122/225370887-a7ac8985-d0d2-47e0-88f1-0eb510f92ca9.png)
I just found out that the site is powered by WordPress and these "sections" I've been talking about was actually an embedded Google Sheet.

![image](https://user-images.githubusercontent.com/38461122/225371618-96085f3b-54be-42ac-aae5-62ece7f05571.png)
![image](https://user-images.githubusercontent.com/38461122/225371916-4e966bf3-b8cd-4b60-915f-9ea507942b26.png)
opening each frame to a new tab, the addon was able to save everything.

**Comment by gildas-lormeau** [comment]
I can save this page without scrolling but I need to increase significantly the option `Images > maximum idle time (ms)`. Setting it to `10000`fixed the issue o my end.

**Comment by gildas-lormeau** [comment]
I'm closing the issue. Feel free to reopen it if necessary.
