### ISSUE TITLE
Use SingleFile to save an exported HTML page from a different extension

### ISSUE THREAD

**Issue by neviln** [gildas-lormeau/SingleFile#1144]
**Is your feature request related to a problem? Please describe.**
I use an extension called "Tabs Outliner" that allows me to organize, suspend and keep track of all the Chrome tabs I constantly keep piling up. The extension allows me to export a list of all my chrome tabs (to use as a backup) in a new chrome window that displays all my windows/tabs using a collapsible tree layout. I can save the page as a .mhtml file via Chrome's standard "save page as", but the tree layout doesn't work properly in the saved file (I can't collapse or open any of the trees). Normally I wouldn't really care about being able to use the tree layout, but there are over 3000 tabs listed in many different groups (windows) so being able to collapse the trees would make it infinitely easier to browse through.

**Describe the solution you'd like**
The URL of the exported backup file is a .html page, but it's incorporated into the Tabs Outliner extension. For example, here's the URL of a recent export I made: 
_chrome-extension://eggkanocgddhmamlbiijnphhppkpkmkl/backup/backupview/view_tree.html?path=selectedFile&timestamp=1679800322365&fileSize=5837758&isLocal=true&isUserSelectedFile=true_

Is there any way to use SingleFile to save a URL like that? If not, is there any possibility of considering it as a feature request? Please and thank you

**Comment by gildas-lormeau** [comment]
Unfortunately, an extension cannot inject itself into the page of another extension. Because of this limitation, SingleFile can't save pages with `chrome-extension://...` as URL.

**Comment by neviln** [comment]
Since SingleFile can't inject itself into the page of another extension, is there any way to inject SingleFile into the local HTML page of that extension that is located in the chrome folder? 
Example:
/eggkanocgddhmamlbiijnphhppkpkmkl/backup/backupview/view_tree.html
