### ISSUE TITLE
特意注册个账号过来反馈一下小问题。

### ISSUE THREAD

**Issue by xiaozhinian520** [gildas-lormeau/SingleFile#1146]
https://www.520mojing.com/thread-43866-1-1.html
这个网站之前可以完整保存的，更新插件之后保存就居中显示一部分，难看的不行，作者可以看一下是不是兼容性出问题了吗？目前最新版本保存下来都是居中的，不是和网页一模一样。

**Comment by gildas-lormeau** [comment]
I confirm I can reproduce the issue but only with Chrome. I'll do some investigation...

**Comment by gildas-lormeau** [comment]
I was able to identify the cause of the issue and fix it. The fix will be available in the next version.

**Comment by gildas-lormeau** [comment]
The new version 1.21.41 is now available for download.

**Comment by xiaozhinian520** [comment]
非常感谢，谷歌浏览器试了一下完美运行，多谢。
