### ISSUE TITLE
Stuff missing from MkDocs site

### ISSUE THREAD

**Issue by NomarCub** [gildas-lormeau/SingleFile#1151]
I tried saving a site created with MkDocs and some images, unfoldable, collapsed menu options are missing. I tried saving it with another plugin, [Save Page WE](https://chrome.google.com/webstore/detail/save-page-we/dhhpefjklgkmgeafimnjhojgjamoafof), which has no such issues. Here's the site: https://blacksmithgu.github.io/obsidian-dataview/

I'm on Chrome on Windows 10.

The other plugin:
![image](https://user-images.githubusercontent.com/5298006/232042145-4843129c-34dd-4eb3-8222-af9e6745cf80.png)
[Dataview.zip](https://github.com/gildas-lormeau/SingleFile/files/11232785/Dataview.zip)

This plugin:
![image](https://user-images.githubusercontent.com/5298006/232042315-d72731df-4301-449d-90b8-265212b1310d.png)
[Dataview (4_14_2023 1_59_05 PM).zip](https://github.com/gildas-lormeau/SingleFile/files/11232791/Dataview.4_14_2023.1_59_05.PM.zip)

**Comment by gildas-lormeau** [comment]
Thank you for the detailed report. I was able to reproduce the issue and fix it. The fix will be available in the next version.

**Comment by gildas-lormeau** [comment]
The new version `1.21.41` is now available for download :)

**Comment by NomarCub** [comment]
The stuff under Metadata in the sidebar (Adding metadata, ...) still doesn't appear when I click on the arrowhead icon thing in the saved site (top left red circle).

**Comment by gildas-lormeau** [comment]
Please uncheck 'HTML Content > remove hidden elements'.
