### ISSUE TITLE
Save the whole page as a png

### ISSUE THREAD

**Issue by Grafenea** [gildas-lormeau/SingleFile#1152]
**Is your feature request related to a problem? Please describe.**
When I try to save a complete screenshot of a very large page, the firefox tool itself does not capture the entire page.

**Describe the solution you'd like**
Have in the extension the option to save the entire page as a png, with no size limit.

**Describe alternatives you've considered (optional)**
The use of another extension that manages to do this, however I would prefer that this feature existed in SingleFile, as keeping several extensions in the same browser makes it heavier for weaker computers.

**Additional context (optional)**
There is this extension (https://github.com/jakwings/firefox-screenshot), which has this function, however, this function could be implemented in SingleFile, as it has a similar objective of saving a page in a single file.

**Comment by gildas-lormeau** [comment]
Sorry for the very late reply. Fundamentally, I'm not against integrating this kind of functionality into the annotation editor. However, it's far too complex from a technical point of view. The problem is that browsers don't offer a simple API for this.

**Comment by Grafenea** [comment]
No need to apologize for taking so long to reply, everything has its time and there are times when we are busy, and we don't know everything either.

About unlimited screenshots, I ended up discovering that when it is too big, most image viewers have difficulties to render, if not simply crash completely.

I ended up finding this extension that does this ([https://github.com/jakwings/firefox-screenshot](https://github.com/jakwings/firefox-screenshot)), so don't need to worry about adding that feature, SingleFile is already very useful.

Thank you for your attention, hugs.

**Comment by gildas-lormeau** [comment]
This feature is now implemented, but with a twist. Instead of simply saving a screenshot, SingleFile will embed a screenshot in ZIP or self-extracting files, see `File format` option in SingleFile. Thus, the resulting file is compatible with PNG, ZIP and HTML optionally (i.e. for self-extracting files).
