### ISSUE TITLE
The file name of the saved file is garbled. Can it be set as the title of the page? 

### ISSUE THREAD

**Issue by LangfordHsu** [gildas-lormeau/SingleFile#1153]
The file name of the saved file is garbled. such as 1a2ce37d-4e9f-4f74-a7ad-9facf29ca5dd.htm or 888957be-9c66-4f4f-9232-e5d5382fcfb6.htm. **Please see the screenshot.**

![image](https://user-images.githubusercontent.com/33155648/232382661-c5a1e65b-24d2-45c5-8d3e-02a828710b75.png)

And I have tested it on Chinese and English web pages (It also includes Wikipedia), and also tested it in Chrome and Edge browsers, still the same result.

![image](https://user-images.githubusercontent.com/33155648/232383988-0c4183e5-73c0-41a5-be05-1cc740d4453c.png)

Just because of this functionality, I'd rather use another plugin now. Otherwise, I have to manually modify the file name, which is really inconvenient.

**Can it be set as the title of the page?**

Could you help me? Thank you very much.

**Comment by gildas-lormeau** [comment]
If the file name of a saved page looks like "56833935-156b-4d8c-a00f-19599c6513d3.html", disable the option "Misc > save pages in background". Reinstalling the browser may also fix this issue. You can find more info about this bug [here](https://bugs.chromium.org/p/chromium/issues/detail?id=892133).

See https://github.com/gildas-lormeau/SingleFile#known-issues
