### ISSUE TITLE
Info Bar disappears if trailing spaces are removed

### ISSUE THREAD

**Issue by ImportTaste** [gildas-lormeau/SingleFile#1154]
**Describe the bug**
If the document is edited and trailing spaces are removed, the info bar will fail to load.

**To Reproduce**
1. Open the file with a text editor
2. Remove the trailing space from the line **after** the ` Page saved with SingleFile ` line. The line starts with ` url:`
3. Open the page in the browser.

**Expected behavior**
Because many text editors remove trailing spaces by default, this caught me off-guard. I couldn't figure out why small changes that didn't seem to matter kept breaking it. After doing some diff checks, I finally figured out it was due to the SingleFile header missing those spaces.

**Comment by gildas-lormeau** [comment]
Thank you for the report, the issue is fixed and will be available in the next version.
