### ISSUE TITLE
save page via WebDriver with JavaScript

### ISSUE THREAD

**Issue by mlipok** [gildas-lormeau/SingleFile#1156]
**Is your feature request related to a problem? 
I need to save page to single file with javascript.
I use webdriver and need sometimes save page for testing cases.
I have installed extension and had exported/edited/imported config with `userScriptEnabled: true`

**Describe the solution you'd like**
I saw:
https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved

but as so far I do not see how to run saving the web content via JS.

For now I just need to use any JS code which will start saving the web conent when I use it in Browser Console.
I would not like to import any JS to document/frames , just want to use installed extension to start saving page via JavaScript.

Any body can help ?

**Describe alternatives you've considered (optional)**
none

**Additional context (optional)**
none

**Comment by gildas-lormeau** [comment]
Sorry for the very late reply. You should take a look at https://github.com/gildas-lormeau/single-file-cli and https://github.com/gildas-lormeau/single-file-cli/blob/master/back-ends/webdriver-chromium.js which is an implementation for WebDriver.
