### ISSUE TITLE
Problem saving images

### ISSUE THREAD

**Issue by deltafx22** [gildas-lormeau/SingleFile#1158]
**Describe the bug**

Saving the following [site](https://manhwa-es.com/manga/el-secreto-de-jae-kyung-espanol/capitulo-1/) after loading it does not save the images (1.html file inside the attached zip). But after several minutes I save the same page again (without reloading it), it saves the images correctly (2.html file).

The used configuration goes inside the zip, [Files.zip](https://github.com/gildas-lormeau/SingleFile/files/11370379/Files.zip)

**Environment**
 - OS: Win11
 - Browser: Chrome
 - Version: Latest

**Comment by gildas-lormeau** [comment]
Sorry for the late reply and thank you for the report. 

Like often, on this kind of websites, images are "protected". You have to enable the option `Network > pass "Referer" header after a cross-origin request error`in SingleFile to circumvent this.
