### ISSUE TITLE
Disable console warnings about web API usage

### ISSUE THREAD

**Issue by dstillman** [gildas-lormeau/SingleFile#1161]
In the Zotero Forums we got a [question](https://forums.zotero.org/discussion/104701/zotero-connector-singlefile-is-hooking-the-intersectionobserver-api-warning) about the "SingleFile is hooking the IntersectionObserver API to detect and load deferred images" warning that appears in the console on a lot of pages (e.g., every GitHub page).

This is the developer console, so people should expect a bit of noise, but I'm wondering about the reasoning behind having this enabled by default. Any report about a problem is going to include a URL, so for all but gated sites a SingleFile developer would be able to run a dev version on the URL with logging enabled and see which APIs were being used. And it's not clear to me that it's something an end user with the console open really needs to know about, since it doesn't imply an unusual state or something that needs to be fixed — it's just something that SingleFile needs to do on lots of sites. Or is there something inherently performance-degrading about these APIs that merits logging a warning to end users about?

(We could just comment this out in the Zotero Connector, but we try to abide by Mozilla's no-modified-third-party-libraries policy.)

**Comment by gildas-lormeau** [comment]
I added these logs to make sure that developers wouldn't be surprised to see unexpected behaviors when using APIs hooked by SingleFile. Now I realize that this problem does not exist in practice. So, I agree with removing the logs.

**Comment by gildas-lormeau** [comment]
This is fixed in the last version I published.

**Comment by dstillman** [comment]
Thanks!
