### ISSUE TITLE
Support all languages in Edge

### ISSUE THREAD

**Issue by Joker-jiajiahui** [gildas-lormeau/SingleFile#1162]
![image](https://user-images.githubusercontent.com/66585703/236611365-f2a797da-37cc-4110-94e6-debf326a09ba.png)

**Comment by gildas-lormeau** [comment]
Extensions like SingleFile rely on the language configured in the browser.

**Comment by gildas-lormeau** [comment]
Except in Edge... I'll try to fix this.

**Comment by gildas-lormeau** [comment]
This will be fixed in the version 1.21.45.
