### ISSUE TITLE
Keyboard shortcut for Safari

### ISSUE THREAD

**Issue by blackketter** [gildas-lormeau/SingleFile#1163]
The documented keyboard shortcut of "Ctrl+Shift+Y" doesn't seem to work in Safari on the Mac.  Any suggestions on how to set a keyboard shortcut?

p.s. Thanks for bringing this to Safari and the App Store!

**Comment by sapientsavant** [comment]
The shortcut is "command+shift+Y" in Safari on a Mac.

**Comment by gildas-lormeau** [comment]
I confirm Command+Shift+Y is the correct shortcut on macOS. Unfortunately, Safari does not seem to offer a way to change it.
