### ISSUE TITLE
Issue with SVG tags while scraping a HTML.

### ISSUE THREAD

**Issue by anilabhadatta** [gildas-lormeau/SingleFile#1164]
The texts are moving out of place while scraping a webpage.
Original HTML:
![image](https://user-images.githubusercontent.com/48487849/236909185-369ec3eb-c20d-4f87-b393-330a4486b686.png)

Scraped HTML:
![image](https://user-images.githubusercontent.com/48487849/236909307-02fd9c99-b960-46ce-8917-bafdbe001b23.png)

Left Original, Right Scraped
The br tags are inserted while scraping
![image](https://user-images.githubusercontent.com/48487849/236909703-b7ae09f8-5b6a-4dc0-a1f7-226bfd36fe30.png)

**Comment by anilabhadatta** [comment]
@gildas-lormeau Please take a look into this.

**Comment by gildas-lormeau** [comment]
I would need the URL of the page in order to understand what's wrong.

**Comment by anilabhadatta** [comment]
@gildas-lormeau This website requires a subscription to view the page. 
https://www.educative.io/module/page/Y6GKZ1igOAW0XJlmE/10370001/5565721689194496/4808500040695808
Maybe getting a 7 day trial may give you access

**Comment by gildas-lormeau** [comment]
Out of curiosity, does disabling `Images > save deferred images` in the options pages of SingleFile change anything?

**Comment by anilabhadatta** [comment]
@gildas-lormeau checked the issue is still there.
[Introduction - Fundamentals of Machine Learning for Software Engineers (5_17_2023 3_28_59 AM).zip](https://github.com/gildas-lormeau/SingleFile/files/11492412/Introduction.-.Fundamentals.of.Machine.Learning.for.Software.Engineers.5_17_2023.3_28_59.AM.zip)

**Comment by gildas-lormeau** [comment]
@anilabhadatta I fixed some issues related to CSS and SVG in the last version. Is this issue still reproducible?

**Comment by anilabhadatta** [comment]
@gildas-lormeau Working perfectly fine. Thank you so much, will implement your latest js file in my scraper.

**Comment by gildas-lormeau** [comment]
Great, I'm glad to hear it :). Thank you for your feedback, I think I can close this issue now.
