### ISSUE TITLE
Video not blocked when saving webpage using SingleFile Safari extension

### ISSUE THREAD

**Issue by alexey-zaharchenko** [gildas-lormeau/SingleFile#1167]
**Describe the bug**
When the video option is enabled for blocking resources in the Safari extension preferences, the resulting saved file should not contain any video content.

**To Reproduce**
1. Enable video blocking in the blocked resources settings of the extension.
2. Go to https://kizu.dev/anchor-positioning-experiments/?
3. Save page

**Expected behavior**
The resulting file should not contain any "src" attributes within the <video> tags, effectively blocking video content. Also file should be much smaller because of that

**Environment**
 - OS: MacOS 13.2.1 
 - Browser: Version 16.3 (18614.4.6.1.6)
 - Version: 1.21.41 from SingleFile for Safari

**Additional context**
It would be helpful to have an option to block video "src" attributes while still saving the posters of the <video> tags.

**Comment by gildas-lormeau** [comment]
I cannot reproduce your issue. On my end, posters are saved but videos are not.

I attached the saved page (with safari) in this zip file: [Future CSS_ Anchor Positioning (16_05_2023 22_37_09).html.zip](https://github.com/gildas-lormeau/SingleFile/files/11491859/Future.CSS_.Anchor.Positioning.16_05_2023.22_37_09.html.zip)

**Comment by alexey-zaharchenko** [comment]
Same for me now, strange. Sorry for falls alarm

**Comment by gildas-lormeau** [comment]
no problem ;)
