### ISSUE TITLE
[FR] Option to keep displaying infobar in annotation editor.

### ISSUE THREAD

**Issue by XMB-7** [gildas-lormeau/SingleFile#1169]
Personally, I'd like to enable the option of opening the annotation editor while viewing a page saved with SingleFile. 
Unfortunately, the info bar disappears when using the annotation editor and there seems to be no way to exit this mode without closing the saved webpage in order to view the info bar again. 
And without the info bar, I cannot jump to the source webpage, so hoping to add an option to keep displaying the info bar in the annotation editor or add a tool button to exit. Thanks.

![image](https://github.com/gildas-lormeau/SingleFile/assets/65625632/cf1a40e5-ecf8-447c-866c-61b038ffe107)

**Comment by gildas-lormeau** [comment]
Would a button to jump to the source webpage would be OK for you?

**Comment by XMB-7** [comment]
Thank you for considering my feature request.
Perhaps adding the infobar button directly to the end of the annotation toolbar would be a better solution, since the infobar contains not only the source link, but also the timestamp and the additional information added by users.

![Image_20230724_105937](https://github.com/gildas-lormeau/SingleFile/assets/65625632/0e2facb1-abe2-460f-910b-a974799a62a2)

**Comment by gildas-lormeau** [comment]
Thank you, I agree that the best solution would be to display the button somehow. Today, this is a limitation, not a feature. I'll try to see how I can circumvent this limitation.

**Comment by XMB-7** [comment]
If displaying the infobar button is somehow hard to achieve, a button that allows me to jump to the source webpage is satisfying enough.

**Comment by gildas-lormeau** [comment]
I was able to integrate the infobar in the editor. You will have to enable the option `Annotation editor > display the infobar`. The only minor issue is that you have to right-click on the link to open the original URL because all links are blocked in the editor.
The feature will be available in the next version.
