### ISSUE TITLE
unexpected change to time saved in file names

### ISSUE THREAD

**Issue by SteegHobland** [gildas-lormeau/SingleFile#1170]
Tonight I've noticed that the time put in file names has changed from UTC to my local time zone. I do not know why it's changed, nor why it was the way it was before.

Maybe it relates to updating Firefox, but the release notes on the most recent version didn't seem to mention anything about time and date that I could tell. I have some inkling that it may relate to how Firefox handles the privacy.resistFingerprinting preference, which I have set to true, as that's affected the time on websites, and maybe it used to affect extensions too, but I don't really know.

My file name template is `{page-title} ({date-locale} {time-locale}).html`, and as far as I know, that's what it was even before this unexpected change. It saves file with names like "Page Title (5_13_2023 10_33_02 PM).html", except the hour and day reflected universal time before, and local time, now.

How can I get things back to behaving how it used to? Should I change that string to something else? If so, can you tell me what to put in it?

**Comment by SteegHobland** [comment]
I've set my OS to use UTC as its time zone, in the meantime. I guess that's working okay, though I'd prefer my clock to read local time, and also the files save with UTC time, and the file names formatted as they were. But I don't know if there will be any way to get things to work exactly the way I want it.

**Comment by gildas-lormeau** [comment]
Does setting `privacy.resistFingerprinting` fix the issue?

**Comment by gildas-lormeau** [comment]
I'm closing the issue, feel free to reopen it if necessary.
