### ISSUE TITLE
[ BUG is not ] Timeless Excellence!

### ISSUE THREAD

**Issue by cvladan** [gildas-lormeau/SingleFile#1171]
I just felt the need to express my gratitude to the author. I used this extension more than 5-10 years ago and I am overjoyed to see that it is still being updated regularly. As I need it every 2-3 years, I was thrilled to see this old friend again, which I know is still working perfectly.

So, thanks to the author! And all this without charging individual users! Well done! It's incredible how useful the extension is for what it was designed to do, just as it was back then. 

Thank you so much!

**Comment by gildas-lormeau** [comment]
Thanks a lot for the message! It's really nice to meet one of the first users of SingleFile. I'm also glad to hear that you are still satisfied with it :). I didn't think when I created it that it would still be relevant 13 years later.
