### ISSUE TITLE
the settings seem to get reset every now and then. Recently, very frequently. 

### ISSUE THREAD

**Issue by thecheesemo** [gildas-lormeau/SingleFile#1173]
For questions, please create or update a thread here: 
https://github.com/gildas-lormeau/SingleFile/discussions

Please ensure that you do not find an answer before reporting the issue:
 - in the FAQ: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md
 - in the list of known issues: https://github.com/gildas-lormeau/SingleFile#known-issues
 - in the help page embedded in the extension

**Describe the bug**
the Settings for singlefile seem to reset to default and the only solution it to uninstall the extension, reinstall it and reload my settings from a backup. 

**To Reproduce**
I don't know how exactly you would reproduce this error. It seems to happen sometimes when launching firefox. Its happening much more recently lately. Before the recent increase it happened maybe twice in a year and a half. 
I notice it when Launching, the autosave will start saving every page I visit. Whereas with the settings I have defined, It will only save certain TLDs that I have added to my "news autosave" Profile

**Environment**
 - OS: Windows 10 Pro
 - Browser: Firefox 102.10.0esr
 - Version: SingleFile 1.21.42

**Additional context**
- I have not tried re building my firefox profile yet
- I have replaced the firefox icon with Resource Hacker

- I have other extensions/addons installed:
1. 600% Sound Volume
2. AdBlocker Ultimate
3. BookmarksHome
4. Facebook Container
5. Feedbro
6. Ghosterly - Privacy Ad Blocker
7. NoScript
8. Old Reddit Redirect
9. Remove Youtube Shorts
10. Save webP as PNG or JPEG
11. Ublock Origin
12. Video DownloadHelper
13. Zotero Connector

If this can't be fixed, its not a huge problem. I can disable the autosave function.

**Comment by gildas-lormeau** [comment]
I'm closing the issue, feel free to reopen it if necessary.
