### ISSUE TITLE
{url-href-digest-sha-1} doesn't work

### ISSUE THREAD

**Issue by defder-su** [gildas-lormeau/SingleFile#1175]
**Describe the bug**
SingleFile can't save page when filename contains {url-href-digest-sha-1}, producing ERR.

**To Reproduce**
1. Go to SingleFile -> Options
2. Set FileName Template to "SingleFile-{date-iso}/{time-iso}-{url-href-digest-sha-1} {page-title}.html"
3. Try to save any web page

**Expected behavior**
Page should be saved.

**Environment**
 - OS: macOS 10.15
 - Browser: Brave 1.51.118
 - Version: x86_64
 - SingleFile v.1.21.42

**Additional context**
1. It’s reproducible also with SingleFileZ.
2. It's reproducible also on Opera (Windows 8).
3. It's not reproducible on Brave 1.51.118 (Windows 10).

**Comment by Mzyxptlk** [comment]
Another problem that I suspect is related is that the `{digest-sha-256}` variable in filenames is no longer replaced when the page is saved. I use auto-saving with the following filename template:

`web-backups/{year-locale}-{month-locale}-{day-locale}/{url-href-flat} {digest-sha-256}.html`

Since May 23, this results in the following kind of filename:

`web-backups/2023-05-23/https__www.smbc-comics.com_comic_knowing {digest-sha-256}.html`

OS: Windows 10
Browser: Firefox 113.0.2
SingleFile: 1.21.42

**Comment by scruel** [comment]
https://github.com/gildas-lormeau/SingleFileZ/issues/154

**Comment by apsoyka** [comment]
Same problem here, neither the `{digest-sha-256}` template nor the `{digest-sha-512}` template are working correctly.

OS: Windows 11 Pro 22H2
Browser: Microsoft Edge 113.0.1774.57
SingleFile: 1.21.42

**Comment by gildas-lormeau** [comment]
Sorry for the late answer. I confirm I was able to reproduce the issue. This fix will be available in the next version.

**Comment by ronin712** [comment]
Should the SHA templates be fixed in version 1.0.26 in the Mac App Store?  When I use {digest-sha-256} in the infobar, it isn't replaced.

**Comment by ronin712** [comment]
Also, can this even work?  If you put the SHA in the infobar, it goes in the file, which means the file contents will no longer match the hash.  Am I misunderstanding something here?

**Comment by gildas-lormeau** [comment]
The HTML comment is ignored when computing the hash.

**Comment by gildas-lormeau** [comment]
I also confirm that it should work with the version published on the Apple store.

**Comment by ronin712** [comment]
Ok, so you can't just hash the file, you have to strip the comment first.  Got it.

**Comment by gildas-lormeau** [comment]
Yes :)

**Comment by ronin712** [comment]
{digest-sha-256} works in the file name, but does not work for me in the Infobar

**Comment by gildas-lormeau** [comment]
I just checked the code and I confirm it's not implemented. Sorry, it's an old feature and I did not remember it's not supported in the infobar.

**Comment by nettyso** [comment]
Oh no I'm guessing this is still true since I just ran into it and spent a while debugging in Firefox's extension debugger wondering why my breakpoints weren't running 😅  That's ok! Not too important!
