### ISSUE TITLE
Expose a synchronous JS api 

### ISSUE THREAD

**Issue by tahasabih** [gildas-lormeau/SingleFile#118]
**Is your feature request related to a problem? Please describe.**
I am trying to use this in conjunction with Selenium, and calling the extension is very flaky by using the key combinations.

**Describe the solution you'd like**
Exposing a js api which only returns when single page is done saving the page.

**Comment by gildas-lormeau** [comment]
Do you have an idea on how you would call this API from Selenium? Note that it would be necessarily asynchronous and based on callbacks/promises because a the code in SingleFile is heavily asynchronous.

**Comment by tahasabih** [comment]
Selenium allows us to run any js code through the webdriver. So if the api is exposed to the window we can just call that function and let SingleFile do it's job.

**Comment by gildas-lormeau** [comment]
Since SingleFile can embed (most) iframe contents into the saved page, I'm wondering if it wouldn't be risky from a privacy/security point of view. Can you enable/disable settings in the options page with Selenium? The idea would be to expose the API if and only if the user agrees and knows the risks. I have a mixed opinion, however, on the idea. I would really prefer this API to be private for the pages visited.

**Comment by gildas-lormeau** [comment]
Actually, can you please tell me if you're able to call `singlefile.core.saveTab()` with Selenium on chrome-extension://mpiodijhokgodhhofbcjdecpffjipkle/_generated_background_page.html with Chrome? It will generate an error, I just want to know if it works.

**Comment by tahasabih** [comment]
So in Selenium one only has the JS context of the current window (it basically runs whatever you send in the console of that tab).

**Comment by gildas-lormeau** [comment]
I don't think it's possible to implement something secure by exposing the API in the JS environment of visited pages. That's why I would prefer to expose the API in the background page. Can you please try to do the test I described in my last message to verify it would work?

**Comment by gildas-lormeau** [comment]
I'm closing the issue because I did not get any answer to my question. Feel free to re-open it if necessary.

**Comment by gildas-lormeau** [comment]
Hi @tahasabih, could you tell me if [this code](https://github.com/gildas-lormeau/SingleFile/tree/master/node-puppeteer) could solve your issue?

**Comment by gildas-lormeau** [comment]
Update: 

Link to the doc: https://github.com/gildas-lormeau/SingleFile/blob/master/cli/README.MD

**Comment by ahxxm** [comment]
tried cli and it works great!

I also want a simple web API for better integration potential(maybe async with rate limit, reuse chromium process, etc...) , thus it can be packed into a [docker service](https://gist.github.com/ahxxm/c6acb27f1a5f93428433426eddc91c8d) for other components
