### ISSUE TITLE
Zooming out breaks rendering

### ISSUE THREAD

**Issue by bansan85** [gildas-lormeau/SingleFile#1180]
**Describe the bug**
When option "zooming out" is checked, some content is rendered wrongly.

Bug exists in Chrome and Firefox.

**To Reproduce**
1. Go to https://developer.android.com/tools/sdkmanager
2. Check "Zooming out".
3. Download with SingleFile
4. Menu is not correctly rendered.

![image](https://github.com/gildas-lormeau/SingleFile/assets/9248729/31f2055c-4beb-4164-93c3-23fc0ab0e514)

**Expected behavior**

![image](https://github.com/gildas-lormeau/SingleFile/assets/9248729/9878544d-a2f4-4fcb-aed6-e0cdaf01f407)

**Environment**
 - OS: Win11 22H2
 - Browser: Chrome 114 /  Firefox 113
 - Version: 64

**Comment by gildas-lormeau** [comment]
Thank you for the detailed report. I confirm I can reproduce the issue. I'm not sure I'll be able to fix it though. At first glance, it doesn't seem obvious.

**Comment by gildas-lormeau** [comment]
I cannot really fix this issue, you must disable `Images > save deferred images > zoom out the page` to fix the distortion issues. This is the default value. You should enable this option only if you're sure it works for the page you're saving.
