### ISSUE TITLE
Styles and page title are lost when saving page on agwa.name/blog

### ISSUE THREAD

**Issue by ivan** [gildas-lormeau/SingleFile#1183]
**Describe the bug**

When saving any blog post on https://www.agwa.name/blog/ like https://www.agwa.name/blog/post/last_weeks_lets_encrypt_downtime, SingleFile does not retain the styles or the page title. The saved content appears unstyled.

**To Reproduce**
1. Install SingleFile 1.21.42 in Chrome
2. Visit https://www.agwa.name/blog/post/last_weeks_lets_encrypt_downtime
3. SingleFile the page with default options
4. Observe that the filename is "No title.html" and that the page's styles are not included

**Environment**
 - OS: Windows 10 22H2
 - Browser: Chrome
 - Version: 114.0.5735.134 or 116.0.5829.0

**Additional context**

The page is XHTML, but not error-free: https://validator.w3.org/check?uri=https%3A%2F%2Fwww.agwa.name%2Fblog%2Fpost%2Flast_weeks_lets_encrypt_downtime&charset=%28detect+automatically%29&doctype=Inline&group=0

**Comment by gildas-lormeau** [comment]
Thank you for the detailed bug report @ivan. In confirm I was able to reproduce it and fix it (in `single-file-core`). The fix will be available in the next version.

**Comment by gildas-lormeau** [comment]
Actually, I just noticed I only fixed the XHTML support. There is still a minor issue with the header and namespace support in CSS selectors. I need to investigate more on how to ignore them. I might release the new version meanwhile.

**Comment by gildas-lormeau** [comment]
I fixed the second issue as well.
