### ISSUE TITLE
{url-href} saving in folders and disabling save in background does same thing as {url-href-flat}

### ISSUE THREAD

**Issue by SonosMiro** [gildas-lormeau/SingleFile#1184]
Hello,

When using filename template {url-href}.html the webpage is saved in folders and not in the filename. I read about disabling save page in background and then it doesn't create folders but basically does the same thing as {url-href-flat} and replaces the / with _.

For me it's important to have the original url with / in the filename. That way I can easily look that page up using folder search.

I'm on Mac OSX & google chrome latest version.

Thanks

EDIT: I can change the name of the file to the url if I remove the : from https://.

**Comment by gildas-lormeau** [comment]
This is unfortunately a limitation of disabling the "save in background" option. I'm keeping the option open, however, as it might be possible to implement it in Chromium-based browsers.
