### ISSUE TITLE
IDK if it is a bug, or you just omitted something, but where can I set the location for saved websites? I try to find it in Firefox add-ons manager option and nada!

### ISSUE THREAD

**Issue by MrTatiTunes** [gildas-lormeau/SingleFile#1187]
For questions, please create or update a thread here: 
https://github.com/gildas-lormeau/SingleFile/discussions

Please ensure that you do not find an answer before reporting the issue:
 - in the FAQ: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md
 - in the list of known issues: https://github.com/gildas-lormeau/SingleFile#known-issues
 - in the help page embedded in the extension

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - OS: [e.g. Win10 Pro, Ubuntu 18.04.1, Android 7.1.2]
 - Browser: [e.g. Chrome, Firefox]
 - Version: [e.g. 64]

**Additional context**

**Comment by MrTatiTunes** [comment]
OK so how we manage the save location?

**Comment by gildas-lormeau** [comment]
Did you read the help page embedded in the extension?

**Comment by MrTatiTunes** [comment]
It is nice that you answered me in private, you did great job but still something is missing from your horizon, it does not answer my question, or… yes answers that we can not manage saving location. The location is the default save location set in browser config.
For my purpose, it is not enough.
I am researcher and I always use "save as" and have my NAS File-server locations for named and defined purposes.
So me, and I bet many of those who use your extension, would like to have this certain option not to move saves after saving them to default. Especially, moving or deleting files in NAS has completely different rules to the Windows systems.

**Comment by gildas-lormeau** [comment]
If you want to save pages in a custom folder, you can use https://github.com/gildas-lormeau/single-file-companion-lite.

**Comment by gildas-lormeau** [comment]
BTW, you can alternatively use a WebDAV server.
