### ISSUE TITLE
Pass referer header after error option not used with autosave

### ISSUE THREAD

**Issue by matso167** [gildas-lormeau/SingleFile#1191]
Pass referer header after error option not used with autosave

**To Reproduce**
1. enable "pass referer header after a cross-origin request error"
2. use autosave
3. request is not done again with referer header after server returns 403

**Expected behavior**
redo request with http referer if option is checked 

**Environment**
 - OS: Linux
 - Browser: Firefox

**Comment by gildas-lormeau** [comment]
Thank you for reporting the issue. I just did some tests and unfortunately it looks like Firefox does not support this option in background pages. I was not able to make it work.

**Comment by gildas-lormeau** [comment]
Actually I was wrong and I was able to identify and fix the issue. The fix will be available in the next version.
