### ISSUE TITLE
please add this for reducing memory use

### ISSUE THREAD

**Issue by Marco84** [gildas-lormeau/SingleFile#12]
First off thanks for this wonderful extension.

Please read this link and add these api and rules to your extension to make it use less memory, many extensions now use it and the result is that chrome uses much less memory:
Please also can you remove access of the extension to Your tabs and browsing activity and Your data on all websites for privacy reasons?

http://www.ghacks.net/2012/06/22/chrome-extensions-eventually-will-use-less-memory-than-before/

http://blog.chromium.org/2012/06/put-your-extensions-on-diet-with-event.html

http://developer.chrome.com/stable/extensions/event_pages.html

Thank you again for this wonderful extension

**Comment by gildas-lormeau** [comment]
This bug is fixed! The extension has been rewritten because it the "Core" extension was unpublished from the store. This gave me an opportunity to avoid using persisting global variables in the background scripts. Thank you!
