### ISSUE TITLE
is saved only as a blank page: https://translate.google.de/translate

### ISSUE THREAD

**Issue by DeVIL-I386** [gildas-lormeau/SingleFile#120]
If you translate something on the page (https://translate.google.de/translate)  it will only be saved as a blank page.

The frame with the translated page is not saved.
Instead, a blank white space appears.

**Comment by gildas-lormeau** [comment]
I cannot reproduce your issue. See [this file](https://github.com/gildas-lormeau/SingleFile/files/2706106/Google.Translate.2018-12-23.5_17_07.PM.zip) for an example of page successfully saved. I need more details to be able to reproduce and fix your issue.

**Comment by gildas-lormeau** [comment]
No problem. However saving this page did not cause any particular issue on my end. I did the test on the latest versions of Chrome and Firefox with the default settings applied. Here is [an example](https://github.com/gildas-lormeau/SingleFile/files/2706165/Google.Translate.2018-12-23.18_32_24.zip).

**Comment by DeVIL-I386** [comment]
909/5000
I use Vivaldi 2.2.1388.37 (Stable channel) (64-bit). I have just reset the settings of the extension. Although I'm sure I have not changed anything.
Still, it did not work. Also not in incognito mode.
I also had all other extensions disabled. Still, it did not work.
Then I restarted the browser. Although there was no browser update.
Now it works all of a sudden. The page can now be saved. Problem solved.
I always recommend it to people I help: Restart the device or the computer and see if the problem persists. I myself should have followed my advice.
It would certainly not be wrong to add this hint in your troubleshooting list: Restart your browser.
Thank you. And sorry for the time that has been lost for troubleshooting.
Is it possible to donate here?

**Comment by DeVIL-I386** [comment]
I use Vivaldi 2.2.1388.37 (Stable channel) (64-bit). 
I have just reset the settings of the extension. 
Although I'm sure I have not changed anything.

Still, it did not work. Also not in incognito mode.
I also had all other extensions disabled. Still, it did not work.

Then I restarted the browser. Although there was no browser update.
Now it works all of a sudden. The page can now be saved. Problem solved.

I always recommend it to people I help: Restart the device or the computer and see if the problem persists. I myself should have followed my advice.
It would certainly not be wrong to add this hint in your troubleshooting list: Restart your browser.

Thank you. And sorry for the time that has been lost for troubleshooting.
Is it possible to donate here?

**Comment by gildas-lormeau** [comment]
Thanks for the details. Maybe your issue was due to corrupted settings. There are some options that appeared/disappeared or have been renamed during the last months. It is possible that the code that is responsible for the upgrade of the concerned settings had a bug since it runs when you start the browser. I should have asked you to export your settings to investigate on this but I did not think about it because this feature is very recent. 

So, I'll add the ultimate step "Restart the browser" in the troubleshooting list since you prove it can "fix" issues. Thank you very much for your tests and the suggestion.

I did not setup anything to accept donations yet. I have to look at it more closely ;)

**Comment by gildas-lormeau** [comment]
You're welcome and thanks again for the info. I'll try to see what could have been gone wrong. As I expected it seems to coincide with the integration of "profiles".

**Comment by gildas-lormeau** [comment]
I'll have to do the tests but I think I fixed these issues meanwhile you were posting it.

**Comment by gildas-lormeau** [comment]
It looks like your bug is that `removeFrames` was set to `true` by default.
