### ISSUE TITLE
v1.21.45 freezes at saving step 2/3

### ISSUE THREAD

**Issue by cmorbach** [gildas-lormeau/SingleFile#1200]
**Describe the bug**
Chrome auto-updated to 1.21.45 yesterday. Saving an HTML dump of ine.com pages for my notebook stopped working.
I tried various settings.
Saving an empty/hello-world HTML page was working.

**To Reproduce**
1. Go to ine.com
2. Login
3. Go to some course
4. Saving freezes at step 2/3 no matter what setting

**Expected behavior**
The pages saves as before.

**Environment**
Chrome 108, Windows 8.1 (I know...but but I'm very busy and cannot afford a new PC)

**Additional context**
Loading 1.21.43 from GitHub and manually adding the add-on resolves the issue for me. (I hate automatic updates...)

When you think it's because of my old system - feel free to ignore my post. But I think there must have happened something between the two releases. Maybe it's helpful to read if other users complain about the issues as well.

**Comment by gildas-lormeau** [comment]
Can you please press F12, click on the "Console" tab, reproduce the issue, and paste here messages displayed in red?

**Comment by gildas-lormeau** [comment]
I think I was able to reproduce your issue, there is no particular error related to SingleFile in the console. The fix will be available in the version `1.21.47`.

**Comment by gildas-lormeau** [comment]
The version `1.21.47` has been published. This bug should be fixed now.

**Comment by cmorbach** [comment]
Sorry for the late reply - different time zones.

I can confirm, it's perfectly working now.

Thanks a lot!

**Comment by gildas-lormeau** [comment]
No problem ;) Thank you for the confirmation!
