### ISSUE TITLE
Hanging under Firefox in Ubuntu w multiple tab downloads

### ISSUE THREAD

**Issue by asteriskCat** [gildas-lormeau/SingleFile#1207]
See below

**Comment by asteriskCat** [comment]
Sometimes Firefox in Ubuntu 22.04 hangs with singlefile when trying to download multiple tabs.  This happens most often when a pic-in-pic video is playing (it's guaranteed in my experiments so far), but it happens randomly at other times.  When this happens, nothing I've tried will restore the multiple tab download for singlefile short of rebooting the machine, which of course is unacceptable.  I've tried closing firefox, pkilling firefox, searching for processes identified as containing `singlefile`, killall firefox, looking for high activity/memory processes (that's hopeless - way too many). The about:debugging window for singlefile shows no errors, warnings, logs, etc.  I've tried disabling, closing, opening and re-enabling the extension w no luck.  How can I gracefully restore the function w/o rebooting?

**Comment by gildas-lormeau** [comment]
Could you try to export your settings via the options page of SingleFile, edit the exported file in a text editor, divide by 2 the value `maxParallelWorkers` (more info here: https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options), import the modified settings and check if it helps?

**Comment by gildas-lormeau** [comment]
@asteriskCat Did you try to reduce the value of `maxParallelWorkers`?

**Comment by gildas-lormeau** [comment]
I'm closing te issue because I've no feedback. Feel free to post a comment, I'll be notified.
