### ISSUE TITLE
Graphics sometimes missed

### ISSUE THREAD

**Issue by notuntoward** [gildas-lormeau/SingleFile#1208]
This is a great plugin, but I'm finding that it misses graphics on many pages.  For example, in this [WA Post article](https://www.washingtonpost.com/climate-environment/2023/08/07/biden-white-house-climate-policy), the stored html file doesn't contain the horizontal bar graphs near the top of the article.

**Comment by gildas-lormeau** [comment]
I was not able to reproduce this issue. I did the test with the default settings in Firefox.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback :)
