### ISSUE TITLE
Infobar not shown.  Add a simple text option?

### ISSUE THREAD

**Issue by notuntoward** [gildas-lormeau/SingleFile#1209]
In the settings, I have the Infobar set like so:

<img width="284" alt="image" src="https://github.com/gildas-lormeau/SingleFile/assets/3851891/d3a20f47-4017-46e5-8eb7-459104e8f0e2">

But in all three places, nothing happens when I click on the 'I" (Brave, Chrome and Firefox).

I'm storing web pages as reference notes, so this metainfo is crucial, especially the URL.  Would it be possible to add a basic clickable link at the top that goes to the original source URL if you click it?

**Comment by gildas-lormeau** [comment]
You have to make sure you don't block JavaScript when opening saved pages.

**Comment by notuntoward** [comment]
Thanks for the reply.  As far as I can tell, this can't be solved with JavaScript settings.

I'm using SingleFile to store web pages in Obsidian, where I'm viewing them with the [HTML Reader](https://github.com/nuthrash/obsidian-html-plugin) plugin (which itself uses SingleFile somehow).  In that plugin's settings, I've turned off all restrictions, and this should unblock JavaScript, as much as possible in that app.


<img width="594" alt="image" src="https://github.com/gildas-lormeau/SingleFile/assets/3851891/434eabff-964f-4767-8616-59ba0787e77d">




With this setting, nothing happens in Obsidian when I click the 'I'.

Javascript is also allowed in the browsers I tried, for example, here is my Javascript setting in Brave:

<img width="501" alt="image" src="https://github.com/gildas-lormeau/SingleFile/assets/3851891/18a64561-022f-48cc-8d6a-1eb1a7eea451">

**Comment by gildas-lormeau** [comment]
Thank you for the additional info.

If you press F12 and open a saved page in the reader, do you see any error in the "console" tab after opening the page?

**Comment by gildas-lormeau** [comment]
Note that the original URL is stored as the [canonical URL](https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls) in the saved page. So, an alternative might be to request a feature in HTML Reader to take account of this standardized information and display a link to the original page.

**Comment by notuntoward** [comment]
I've asked for something similar to that, but the author of the HTML reader plugin doesn't see a way to transfer meta info to the  rest of Obsidian.  Something about the Obsidian design.  He said he'd think about it, thought it would take a month to reach a final conclusion.  I'm guessing that if it's not visible on the html, it won't be visible anywhere else.

Using this a bit more, I had another feature request.  I'll make a separate one.

**Comment by gildas-lormeau** [comment]
I have implemented a new infobar. It's visually the same and behaves identically but it does not depend on JavaScript to work properly. This should fix this issue. The new feature will be available in the next version.

**Comment by notuntoward** [comment]
Thanks for the new infobar.  I'll be an eager user of it.

**Comment by gildas-lormeau** [comment]
I forgot to mention that it will work in Chromium-based browsers only (with JS disabled). It won't work in Firefox until this bug is fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1712140.

**Comment by gildas-lormeau** [comment]
Meanwhile, if you want, you can test the example of saved page in the zip file.

[Example Domain (16_08_2023 23_09_16).html.zip](https://github.com/gildas-lormeau/SingleFile/files/12363643/Example.Domain.16_08_2023.23_09_16.html.zip)

**Comment by gildas-lormeau** [comment]
Note that if the page is working for you in Chrome but not Firefox, then it means it's a bug in HTML Reader.

**Comment by gildas-lormeau** [comment]
Thank you for the prompt feedback.

I confirm contents will be configurable with template variables. What do you mean by "with the markup tools, as configured"?

**Comment by gildas-lormeau** [comment]
I confirm i can reproduce your issue. However, I can confirm the new version will still be compatible with pages saved with previous versions and will work, of course, for pages saved with new version.

**Comment by gildas-lormeau** [comment]
I uploaded the new version `1.21.57` on the stores. It will be available for download once reviewed.

Feel free to reopen the issue if necessary.

**Comment by notuntoward** [comment]
I've updated to 1.21.57, but I'm still not seeing the annotation bar turned on when I revisit an already saved file.  When I reload a previously saved SingleFile from my computer, what I see is this:

<img width="585" alt="image" src="https://github.com/gildas-lormeau/SingleFile/assets/3851891/043cec86-4ff7-4975-8b49-1b54d1be0a98">


What I used to see, and what I believe my settings should still cause me to see, is this:

<img width="592" alt="image" src="https://github.com/gildas-lormeau/SingleFile/assets/3851891/ee666293-3411-419c-9c9c-b1faf296a732">

One other thing I notice now, is that whenever I visit a new page, the SingleFile icon has a circle around it:

<img width="569" alt="image" src="https://github.com/gildas-lormeau/SingleFile/assets/3851891/cdce4e24-b729-438e-a330-a56d02bd2d08">

If I click the icon, SingleFile does this:

<img width="272" alt="image" src="https://github.com/gildas-lormeau/SingleFile/assets/3851891/f115a11c-f6da-4b34-8cfe-26550b90833d">

But I haven't changed my settings.  

This does, though, bring up the annotation tools when I've reloaded an existing SingleFile file from my computer.

**Comment by notuntoward** [comment]
I added a comment to this issue but since I can't find the re-open icon, I
wasn't able to reopen it.

**Comment by gildas-lormeau** [comment]
I don't know what is the cause of the issues you're describing but they are not related to the current one. It looks like an it's an issue with Brave.

**Comment by notuntoward** [comment]
It's not specific to Brave, because I have the same problem on Chrome.  Could be a problem with the basic code that Chrome and Brave share, though.

But just to be sure we're talking about the same thing, I remember that you were able to reproduce the problem I reported, then one I reported about here, where the annotating icons don't immediately reappear when I load an html file that was previously stored by SingleFile.  

Did you see that that the annotating icons were missing before, and now, after 1.21.57, do you see the annotating icons immediately after loading a file written by SingleFile?

**Comment by notuntoward** [comment]
Thanks a lot!  That fixed it for Brave.

On Chrome, things worked when enabled this setting.

<img width="547" alt="image" src="https://github.com/gildas-lormeau/SingleFile/assets/3851891/d2e11e7c-ae1e-405c-9e3c-cd64eecb6b19">

**Comment by gildas-lormeau** [comment]
You're welcome! I confirm you need indeed to enable the file access (if you do not include the infobar) in Chromium-based browsers.
