### ISSUE TITLE
right-clicking the singlefile button or on the webpage to open the context menu is not work

### ISSUE THREAD

**Issue by qinggonghui** [gildas-lormeau/SingleFile#121]
**Describe the bug**

when i use the singlefile, i can't see the context menu of singlefile, no matter i right clicking on the webpage or on the singlefile button (i could see the context menu of firefox with right clicking).

i have checked the "add entry in the context menu of the webpage" and reset the browser

**Environment**
 - OS: win7 pro x64
 - Browser: firefox
 - Version: 52.90 esr x64

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. Hopefully, this bug was present only with old versions of Firefox. The fix will be deploy in the next version.

**Comment by qinggonghui** [comment]
Thank you so much. I'm looking forward :-)

**Comment by qinggonghui** [comment]
Have updated to the new version and the bugs have been solved. Your efficiency is amazing! Thank you again.

**Comment by gildas-lormeau** [comment]
You're welcome! It was an easy fix ;)
