### ISSUE TITLE
Can not see the contents and photos in saved page

### ISSUE THREAD

**Issue by ddseven345** [gildas-lormeau/SingleFile#1210]
**Describe the bug**
I saved a page from Google Docs one years ago.  I could see the contents and pictures in the past but now I could not. 

The file can be downloaded here:
https://1drv.ms/u/s!Ahvg-kle37mDnf1-XvWzTc816D6r0g?e=wtdYEI

**Environment**
 - OS: [e.g. Win10 Pro, 
 - Browser: [Firefox]
 - Version: [e.g. 64]

I did not have the problem on the others pages I save from Google Docs which I saved on the same day. 

Thanks

**Comment by gildas-lormeau** [comment]
Actually, the page contains some blurred contents but you have to scroll down to see it.

**Comment by ddseven345** [comment]
My bad. I can scroll down and saw the contents in Firefox. Did not see the scroll bar so I thought it did not work. Thanks for the reply.

**Comment by gildas-lormeau** [comment]
You're welcome :)
