### ISSUE TITLE
Save scroll position of iFrames with no scroll bars

### ISSUE THREAD

**Issue by loveencounterflow** [gildas-lormeau/SingleFile#1214]
I want to suggest that when a document containing non-scrollable iFrames (i.e. mainly those that have the `scrolling` attribute set to `no`, as in `<iframe scrolling='no'>`) is saved, the scroll positions of the content documents should also be preserved. This should not be difficult if a tiny bit of JS can be run for each iFrame:

```js
const iframe = document.querySelector( 'iframe' );
const x = contentDocument.documentElement.scrollLeft;
const y = contentDocument.documentElement.scrollTop;
// serialize x, y into the produced source; when saved document is opened, do
iframe.contentDocument.documentElement.scrollLeft = 123;
iframe.contentDocument.documentElement.scrollTop = 456;
// with the hard-wired coordinates to restore original view
```

One would imagine that putting the restoration part into a script section at the end of the framed document should work. I will try this out because it's a functionality that I need independently of this extension, so I might get back here to report on that.

BTW a great extension that neatly fills a difficult-to-fill gap of the web. 'Save a web page to the local file system' sounds so easy and web browsers have always offered to provide it, but the matter of fact is that it frequently fails to work to satisfaction. It should be easy but there are, apparently, too many corner cases.

**Comment by gildas-lormeau** [comment]
Thanks for the suggestion. I agree that it would be useful. However, it might be a bit complicated to implement because iframes can be sandboxed in web pages (this is often the case). This means that the scroll position has to be collected via `processors/content-frame-tree.js` in `single-file-core`. In addition, iframes are sandboxed in saved pages, so the iframe must be scrolled via the document inside.

**Comment by gildas-lormeau** [comment]
It's implemented, the feature will be available in the next version.
