### ISSUE TITLE
Page saved with wrong favicon

### ISSUE THREAD

**Issue by dougfunny1** [gildas-lormeau/SingleFile#1216]
**Describe the bug**
When saved, the page displays a different favicon than the one displayed on the original page.

**To Reproduce**
1. Go to www.habbo.com
2. Save page
3. See error

**Expected behavior**
The page is displayed with the original favicon.

**Environment**
 - OS: Win10 Pro
 - Browser: Chrome
 - Version: 1.21.56

**Additional context**
It looks like the page has 2 different favicons.
The first is the desktop version, displayed in the Chrome browser, stored at:
`<link rel="shortcut icon"`
The second is the mobile version, stored in other elements:
`<link rel="icon"`
`<link rel="apple-touch-icon"`
The extension removes the "shortcut icon" and "apple-touch-icon", leaving only the "icon".

**Comment by gildas-lormeau** [comment]
Thank you for the report. I was able to reproduce and fix the bug. The fix will be available in the next version.
