### ISSUE TITLE
In batch save URLs, have option to load pages in foreground

### ISSUE THREAD

**Issue by gnadlr** [gildas-lormeau/SingleFile#1218]
**Is your feature request related to a problem? Please describe.**

Some webpages does not fully load until it becomes the active tab (foreground). Therefore, they are not saved correctly when batch saving URLs.

**Describe the solution you'd like**

I'd like an option for the batch handler to open each URL in the foreground, with a configurable wait time before triggering download.

If you have any idea or possible workaround please let me know. I have ~10k links to scrape which is not really possible to download manually.

Thank you very much.

**Comment by gildas-lormeau** [comment]
I added an hidden option `processInForeground`, see https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options. This new option will be available in the next version.

**Comment by gildas-lormeau** [comment]
I uploaded the new version `1.21.57` on the stores. It will be available for download once reviewed.
