### ISSUE TITLE
{page-title} ({date-locale} {time-locale}).html - in RTL languages

### ISSUE THREAD

**Issue by Stamimail** [gildas-lormeau/SingleFile#1222]
There is a problem with 
{time-locale}

אבג (20.8.2023 12_34_56)

By my tests it's not good due to using the character "_"
Please use other character for {time-locale}

**Comment by gildas-lormeau** [comment]
I'm not sure this problem can be fixed. To generate the filename, SingleFile interprets the template and replaces all the character not supported by the filesystem (like `:`) with `_` by default in the generated filename. This can be configured via the hidden option `filenameReplacementCharacter` though, see here: https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options.

**Comment by Stamimail** [comment]
I guess if you remove `_` or replace it by other character it will be fixed.
What alternative do you want me to try?

**Comment by gildas-lormeau** [comment]
Does "-" work?

**Comment by Stamimail** [comment]
Yes.
Here is how it's look like.

אבג (21.8.2023 0-41-11)

**Comment by gildas-lormeau** [comment]
Thank you for the feedback. I think the best solution is to make configurable the replacement character via the options page in SingleFile. I cannot change the default value "_" to "-" because it's been more than 10 years that it is the default value.

**Comment by gildas-lormeau** [comment]
A new option `File name > replacement character` has been added in the options page to update easily the replacement character. This feature will be available in the next version `1.21.61`.
