### ISSUE TITLE
I found a page that singlefile fails to save, sometimes silently

### ISSUE THREAD

**Issue by kupietools** [gildas-lormeau/SingleFile#1230]
For questions, please create or update a thread here: 
https://github.com/gildas-lormeau/SingleFile/discussions

Please ensure that you do not find an answer before reporting the issue:
 - in the FAQ: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md
 - in the list of known issues: https://github.com/gildas-lormeau/SingleFile#known-issues
 - in the help page embedded in the extension

**Describe the bug**
Singlefile appears to fail late in the saving process for one particular website.  If "save in background" is on, it gives an error. If "save in background" is off, it fails silently and never saves the page. 

**To Reproduce**
1. Go to https://learnprompting.org/docs/prompt_hacking/offensive_measures/obfuscation
2. Use singlefile to try to save the page
3a. If "save in background" is turned on, the page save fails after clicking "save" in the save dialog with an orange error bar across the top: "singlefile error: interrupted" 
3b. If "save in background" is turned off, the page appears to save, there is no error
4. Go to your save folder — the page isn't there.

**Expected behavior**
The page is saved

**Screenshots**

**Environment**
 - OS: Mac OS X 10.14.6
 - Browser: Firefox
 - Version: 115.2.0esr (64-bit)

**Additional context**
I do have my browser set to ask me where to save for each download. I don't seem have any problem saving pages from any other site.

**Comment by kupietools** [comment]
How embarrassing... I discovered the problem. There's an emoji in the page title. Removing this from the save file name fixes the issue. Checking the "replace emojis with text" options fixes this issue. Perhaps add a warning somewhere to check that setting if there are save problems? Closing this issue.

**Comment by gildas-lormeau** [comment]
Actually, I didn't know emojis could cause problems in filenames. The option was added following a feature request. I suspect this might an issue be specific to Mac OS X though. Are you on HFS+ or APFS?

**Comment by kupietools** [comment]
APFS. Would not at all be surprised if it is Mac-specific, as it actually occurs after the OS-native 'save' dialog.
