### ISSUE TITLE
Implement the option `File name > file name conflict resolution` for all the possible destinations (WebDAV, GitHub, etc.)

### ISSUE THREAD

**Issue by AeliusSaionji** [gildas-lormeau/SingleFile#1235]
**Is your feature request related to a problem? Please describe.**

It appears that the autosave bookmark function does not run unless saving to the local filesystem.

**Describe the solution you'd like**

Include support for alternate destinations.

**Additional context (optional)**

I'm using the tab-stash addon, which stores your "tabs" as bookmarks. In an ideal world, SingleFile would save created bookmarks to a webdav location + update bookmark URI to point to webdav. Annotations should be able to overwrite the webdav file (if chosen in settings).

Thanks!

**Comment by gildas-lormeau** [comment]
Thank you for feature request. The main part of the issue is now implemented. It will will work with WebDAV and GitHub. The fix will be available in the next version of SingleFile.

The second part of the issue regarding the annotation editor is unrelated to this bug.

**Comment by gildas-lormeau** [comment]
It's fixed. The fix will be available in the next version. Only `prompt` is not supported (yet).

**Comment by gildas-lormeau** [comment]
`prompt` will also be supported.
