### ISSUE TITLE
Remove from page context menu

### ISSUE THREAD

**Issue by nollinvoyd** [gildas-lormeau/SingleFile#1237]
Firefox 117

Is this possible? I se that the page context menu is optional.  How about with css?

**Comment by gildas-lormeau** [comment]
I'm sorry but I don't understand the question. Are you referring to the context menu on the tab?

**Comment by nollinvoyd** [comment]
Yes, the context menu on the tab.

**Comment by gildas-lormeau** [comment]
Set the hidden option `tabMenuEnabled` to `false`, see here for more info: https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options

**Comment by nollinvoyd** [comment]
That dd it.  Thank you!
