### ISSUE TITLE
SingleFile error: Error 403 (WebDAV on Anybox)

### ISSUE THREAD

**Issue by rchrdyan** [gildas-lormeau/SingleFile#1238]
"SingleFile error: Error 403 (WebDAV)" on saving after updating to SingleFile 1.0.33.

**Environment**
 - OS: macOS Ventura 13.5.2
 - Browser: Safari
 - Version: 16.6 (18615.3.12.11.2)
<img width="1782" alt="CleanShot 2023-09-14 at 23 54 13@2x" src="https://github.com/gildas-lormeau/SingleFile/assets/91372532/9f9df321-cca7-4166-880f-13aa662f90e5">

**Comment by gildas-lormeau** [comment]
What are the values of `File name > template`and `File name > file name conflict resolution` in your settings?

**Comment by gildas-lormeau** [comment]
I'm just realizing `File name > file name conflict resolution` is hidden in Safari actually...

**Comment by gildas-lormeau** [comment]
What WebDAV server are you using?

**Comment by rchrdyan** [comment]
File name template value is {page-title} ({date-locale} {time-locale}).html
WebDAV server is http://localhost:6391/archive from Anybox.
Is there a way to see this hidden "file name conflict resolution" option?

**Comment by rchrdyan** [comment]
It worked just fine yesterday before the update.
I reported the issue to Anybox's developer as well.

**Comment by gildas-lormeau** [comment]
Thank you, I'll try to do some tests with AnyBox. Meanwhile, you can export your settings, edit the JSON file, replace `filenameConflictAction: "uniquify",` with `filenameConflictAction: "overwrite",`, save the file and import it in SingleFile. I would be interested to know if it helps.
I made changes in the imlementation of WebDAV to support the file name conflict action, this is probably my fault.

**Comment by rchrdyan** [comment]
That did not work. Same error.

**Comment by gildas-lormeau** [comment]
I was able to reproduce the bug with AnyBox. The bug is in AnyBox from my point of view, it should support the HTTP `HEAD` method but it returns a 403.

**Comment by rchrdyan** [comment]
It is very helpful. Thank you. I will communicate this with Anybox.

**Comment by gildas-lormeau** [comment]
FYI, I just did a test and tried to replace `HEAD`, with `PROPFIND` but that did not help. This means I cannot really circumvent this issue in SingleFile.

**Comment by gildas-lormeau** [comment]
BTW, the expected HTTP code in SingleFile on `HEAD` requests is a 404 when the file does not exist on the server.

**Comment by gildas-lormeau** [comment]
@rchrdyan I see a new version of Anybox has been published, is the bug fixed?

**Comment by rchrdyan** [comment]
No, not yet fixed in this version.

**Comment by francisfeng** [comment]
@rchrdyan @gildas-lormeau 

Hi there! Developer of Anybox here.

Thanks for reporting and locating the bug. The bug is fixed and the new version will be out in the next one or two days.

**Comment by gildas-lormeau** [comment]
That's great news, thank you @francisfeng

**Comment by francisfeng** [comment]
The new version (2.0.3) is out in Mac App Store.

@rchrdyan @gildas-lormeau

**Comment by rchrdyan** [comment]
> The new version (2.0.3) is out in Mac App Store.
Great work. Thanks.
I am closing this thread as resolved.
