### ISSUE TITLE
Chinanews.com becomes mojibake with Save raw page enabled

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [gildas-lormeau/SingleFile#124]
**Describe the bug**
While I try to save any page from www.chinanews.com I found all page becomes mojibake, but if I disabled Save raw page, I saw the problem disappeared.

**To Reproduce**
1. Go to www.chinanews.com
2. Click on SingleFile icon
3. See error

**Expected behavior**
The saved page doesn’t becomes mojibake

**Screenshots**
None

**Environment**
 - OS: Win10 Home
 - Browser: Firefox
 - Version: 64

**Additional context**

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. It should be fixed in version 1.9.18. Please confirm it works for you.

**Comment by KrasnayaPloshchad** [comment]
OK, it’s fixed.

**Comment by gildas-lormeau** [comment]
You're welcome...
