### ISSUE TITLE
Issue with saving Technotes from developer.apple.com

### ISSUE THREAD

**Issue by Avimanyu1** [gildas-lormeau/SingleFile#1241]
**Describe the bug**
[Page](https://developer.apple.com/documentation/technotes) when viewed doesn't display actual contents.

**To Reproduce**
1. Save page 
2. View in Safari
3. Page contents show an error

**Expected behavior**
Page should be the same as hosted

**Screenshots**

**Environment**
 - OS: macOS Sonoma
 - Browser: Safari 15
 - Version: 1.0.33

**Additional context**

**Comment by gildas-lormeau** [comment]
The only issue I see with this page is related to fonts. Let me know if you see any other problems, and if you have changed some options in SingleFile.

This can be circumvented by enabling the option `Network > pass "Referer" header after a cross-origin request error` in SingleFile but this option is not supported in Safari.
