### ISSUE TITLE
Washington Post Images Over-Enlarged

### ISSUE THREAD

**Issue by sj365** [gildas-lormeau/SingleFile#1249]
https://www.washingtonpost.com/politics/trump-adviser-larry-kudlow-hosted-publisher-of-white-nationalists-at-his-home/2018/08/21/f418a76c-a55e-11e8-8fac-12e98c13528d_story.html?noredirect=on

https://www.washingtonpost.com/technology/2023/02/28/hologram-circus-animals-roncalli/

https://www.washingtonpost.com/politics/2023/10/04/mccarthy-speaker-ouster-analysis/

WashingtonPost.com articles are being saved with the mini picture stubs at the bottom expanded out of proper proportion. This started happening with Singlefile around February 2023. This behavior is observed in all WashingtonPost articles checked. 

The options currently used are attached

Processor 11th Gen Intel(R) Core(TM) i9-11980HK @ 2.60GHz 3.30 GHz
Installed RAM 32.0 GB (31.7 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch Touch support with 10 touch points
Edition Windows 11 Pro
Version 22H2
OS Build 22621.2361

Chrome Singlefile - 1.22.2
Firefox Singlefile - 1.21.66

** This issue was previously posted and closed but has not been resolved.  The fix provided in the post was not effective- WashingtonPost Picture Distortion #1134**

You must disable Images > save deferred images > zoom out the page to fix the distortion issues. This is the default value. You should enable this option only if you're sure it works for the page you're saving.

savedfiles.zip
--------------
with deferred images and zoom checked-all images come in throughout page but bottom images are over enlarged (main issue)

correct wpost1 - screenshot of page showing correct image sizes for bottom images

1st-singlefile page save deferred images checked, zoom unchecked (missing bottom images and 3rd set of images on right side missing)

1st-singlefile settings screenshot

2nd- singlefile page save deferred images unchecked, zoom unchecked (missing bottom images and part of 1st set of images on right side missing, 2nd and 3rd sets of images on right side gone)

2nd-singlefile settings screenshot

current chrome singlefile-settings.json

firefox1 - with deferred images and zoom checked-all images come in throughout page but bottom images are over enlarged (main issue)

firefox1-singlefile settings screenshot

firefox2- with deferred images checked and zoom unchecked - all images come in throughout page but bottom images are over enlarged (main issue)

firefox2-singlefile settings screenshot

firefox3-with deferred images unchecked, zoom unchecked (missing bottom images and all of 1st set of images on right side missing, 2nd and 3rd sets of images on right side gone)

firefox3-singlefile settings screenshot

current ffx singlefile-settings.json

Tested on portableapps new chrome browser only Singlefile extension

Tested on installed chrome browser Version 117.0.5938.132 (Official Build) (64-bit) only singlefile extension active

Tested on Firefox 118.0.1 (64-bit) only Singlefile extension active

[savedfiles.zip](https://github.com/gildas-lormeau/SingleFile/files/12806930/savedfiles.zip)

**Comment by gildas-lormeau** [comment]
Thank you, I will do some tests to see what could be wrong. The problem for me is the paywall which is very annoying when testing bugs on this site.

**Comment by sj365** [comment]
Hi,

I think you need this for testing purposes only
https://gitlab.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by gildas-lormeau** [comment]
Thank you, the main issue is fixed, it's not related at all with "save deferred images" and "zoom out the page" options. The missing images when "zoom out the page" is unchecked is normal. This is due to the fact that the hack used to emulate a large screen could cause an infinite scroll on some websites. Thus, it keeps a safety margin leading to bottom contents not being loaded.

**Comment by gildas-lormeau** [comment]
I'm closing the issue because it's fixed.
