### ISSUE TITLE
[Tiny Feature Request] Would option "open saved pages in a new tab" now be applicable to self-extracting HTML?

### ISSUE THREAD

**Issue by thedewi** [gildas-lormeau/SingleFile#1255]
The "open saved pages in a new tab" option was always ignored for compressed formats, but now that we have self-extracting HTML format, would it make sense to widen that restriction?

The restriction is documented here -
https://github.com/gildas-lormeau/SingleFile/blob/4c8870b6f63e934c5f23b04f3bd90a9e917a430b/src/ui/pages/help.html#L118C63-L119C43

**Comment by gildas-lormeau** [comment]
Th technique used currently does not work with pages requiring JS. I think I have to find a workaround.

**Comment by gildas-lormeau** [comment]
I was able to implement the feature. It will be available in the next version.

**Comment by thedewi** [comment]
Thanks very much! That will make the workflow much smoother.
