### ISSUE TITLE
This page cant be saved with Singlefile

### ISSUE THREAD

**Issue by Theo1996** [gildas-lormeau/SingleFile#1258]
For questions, please create or update a thread here: 
https://github.com/gildas-lormeau/SingleFile/discussions

Please ensure that you do not find an answer before reporting the issue:
 - in the FAQ: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md
 - in the list of known issues: https://github.com/gildas-lormeau/SingleFile#known-issues
 - in the help page embedded in the extension

**Describe the bug**
After an update opened a tab detailing the changelog of some self extracting zip files today, no pages can be saved with singlefile. When I press the icon on wikipedia or any oher website it just shows a crossed red circle with the mouseover text reading "This page cant be saved with single file."

**To Reproduce**
1. Go to 'wikipeida'
2. Click on 'icon'
3. See error

**Expected behavior**
It should download the oage normally.

**Screenshots**

**Environment**
 - OS: win7 ultimate
 - Browser: firefox 78.9 esr
 - Version: add on version 1.22.3

**Additional context**
nothing

**Comment by gildas-lormeau** [comment]
Sorry for the inconvenience, I do not test SingleFile in Firefox 78. I was able to reproduce and fix this regression, the fix will be available in the next version.

**Comment by Theo1996** [comment]
thanks

**Comment by gildas-lormeau** [comment]
The new version is available for download.
