### ISSUE TITLE
New self-extracting ZIP formats don't produce readable results

### ISSUE THREAD

**Issue by redactedscribe** [gildas-lormeau/SingleFile#1259]
**Describe the bug**
Customised my default by duplicating it then changing the file format to self-extracting ZIP (universal). Saving with that profile produces an HTML which can be browsed using a archiver program, but when dragged into a browser only renders scrambled text. JavaScript is enabled as far as I know. Tried two browsers, Firefox and Brave. Same happens with non-universal self-extracting ZIP format.

**Screenshots**

![brave_2023-10-07_00-37-32](https://github.com/gildas-lormeau/SingleFile/assets/25013746/ced06cb4-98a6-40b1-937a-08de307d96b2)

**Environment**
 - OS: Windows 11
 - Browser: Firefox 118.0.1, Brave 1.58.137
 - Version: 64-bit

Thanks.

**Comment by gildas-lormeau** [comment]
It looks like a simple ZIP file, not a self-extracting file. Simple ZIP files cannot be displayed in the browser.

**Comment by redactedscribe** [comment]
> It looks like a simple ZIP file, not a self-extracting file. Simple ZIP files cannot be displayed in the browser.

I guess SingleFile isn't creating a self-extracting ZIP file for some reason. I tried several times using the first two formats and only once using the plain ZIP format.

**Comment by gildas-lormeau** [comment]
I was able to reproduce the issue. I can confirm it is a ZIP file, this can be verified by opening the source page via the context menu. You'll se binary contents.

**Comment by gildas-lormeau** [comment]
I can also confirm the cause of the issue. I opened the saved page in https://hexed.it/, selected and deleted all the bytes after `<script>var e,t`, and the resulting file can be unzipped without any warning.

**Comment by gildas-lormeau** [comment]
I deleted my previous answers because I was in the wrong thread. 

Actually, I don't know the cause of your issue. If you press F12, do you see an error in the console when opening a page?

**Comment by redactedscribe** [comment]
@gildas-lormeau In Firefox:

![firefox_2023-10-08_01-37-26](https://github.com/gildas-lormeau/SingleFile/assets/25013746/61400a06-9b3e-40b6-b4be-0299d858ff99)

**Comment by gildas-lormeau** [comment]
These errors are not related to SingleFile. Maybe another extension is conflicting with SingleFile?

**Comment by redactedscribe** [comment]
> Thank you. These errors are not related to SingleFile. Maybe another extension is conflicting with SingleFile?

When I tried it in Brave I used a Guest profile ("guest mode") and the result is the same - no extensions to conflict with. I just double-checked. Perhaps it's to do with [the version of 7-zip on my system](https://github.com/mcmilk/7-Zip-zstd)? I will have to reply tomorrow.

**Comment by gildas-lormeau** [comment]
The file included in your ZIP file is not a self extracting ZIP page. It's a simple ZIP file which I can uncompress with unzip without any particular issue.

**Comment by redactedscribe** [comment]
> The file included in your ZIP file is not a self extracting ZIP page. It's a simple ZIP file which I can uncompress with unzip without any particular issue.

This is what the extension is creating.

My steps are:

1. Duplicate default profile.
2. Set file format of new profile to self-extracting zip (universal).
3. Open example.com in a tab.
4. Right-click extension icon and "Save page with profile" using the new profile.
5. When the SingleFile tab opens with the wabpage, press "Save this page" button.
6. Result is the HTML file I included in my previous comment.

**Comment by redactedscribe** [comment]
Does the 1.22.5 release address this? Firefox received the update but the same bug is present. What could the source of the problem be?

**Comment by gildas-lormeau** [comment]
Sorry for the late answer. Actually I cannot reproduce your problem.

With the default settings, the  file format in the default profile is set to "HTML". Thus, on step 5, you should get an HTML file because you're saving the page with the default profile.

Is the file format in your default profile set to "ZIP"?

**Comment by redactedscribe** [comment]
> Sorry for the late answer. Actually I cannot reproduce your problem.

No problem.

> With the default settings, the file format in the default profile is set to "HTML". Thus, on step 5, you should get an HTML file because you're saving the page with the default profile.

Step 4 states that I am saving the page with the new profile via "Save page with profile".

My default is set to HTML. The duplicated profile is then changed to ZIP universal.

What could cause it to not work? You said a conflicting extension could be the problem.

**Comment by gildas-lormeau** [comment]
On step 4, you are saving the page with the new profile but you did not change the default profile. You must use `Select default profile` in the menu for this. That's why on step 5, the page is saved with the default profile, as HTML.

**Comment by redactedscribe** [comment]
I'm confused. I think we aren't understanding each other. Why would I need to change which profile is the default profile? My assumption is that the default profile's settings should have no effect when "Save page with profile" using a different profile. I will try changing the default profile to my duplicated profile.

Okay, so I think I understand you: Using 1.22.7, I first set SingleFile > Select the default profile > My ZIP universal profile, then I use Save page with profile > My ZIP universal profile to save the page. Now the expected result is achieved: The page saved is a .html, it renders in Firefox, and it's openable in 7-zip. But... this is completely unintuitive, and I hope this is an unintentional bug.

You should not _have_ to set the default profile to the same profile you want to use via "Save page with profile". "Save page with profile" should work no matter what the default profile is set to, otherwise it doesn't make sense to have the "Save page with profile" feature (because you could just set the default profile and then simply press "Save page with SingleFile", i.e. the extension's blue button).

**Comment by gildas-lormeau** [comment]
Since version 1.22, absolutely nothing has changed with regard to profile handling. The only new thing is 3 new formats in the options page. There must be some misunderstanding, but I can't figure it out.

**Comment by redactedscribe** [comment]
@gildas-lormeau Please explain this: When I want to save a page using a profile (called X) _which isn't the default profile_, why do I _have_ to first set SingleFile's default profile to be X _before_ I can save that page using "Save page with profile" to create a valid self-extracting ZIP?

Doing exactly this is the only way that I can create a HTML file which renders in Firefox and opens in an archiver program.

**Comment by gildas-lormeau** [comment]
You don't have to do that. Just select "Save with profile > X".

**Comment by redactedscribe** [comment]
@gildas-lormeau You are incorrect. I have performed the test now many times. What I am stating is precisely the case. I cannot communicate it any more clearly. Please try and see if the file format feature which you added is incorrectly requiring SingleFile's default profile to be the same as the selected "Save page with profile" for the file format to be self-extracting.

**Comment by redactedscribe** [comment]
In this zip which contains two HTMLs created by SingleFile, the first is the result of SingleFile's default profile being set to my normal default profile and then clicking "Save page with profile" > My ZIP universal profile. The second is the result after simply changing 

[example.com SingleFile examples.zip](https://github.com/gildas-lormeau/SingleFile/files/12916437/example.com.SingleFile.examples.zip)

**Comment by redactedscribe** [comment]
Here is also my exported settings: [singlefile-settings-2023-10-16T12_43_08.833Z.json](https://github.com/gildas-lormeau/SingleFile/files/12916702/singlefile-settings-2023-10-16T12_43_08.833Z.json)

**Comment by gildas-lormeau** [comment]
I'm sorry but I cannot reproduce your issue. I have reset my options. I have created a new profile named "universal zip file" and changed the file format in the new profile. If I go to https://www.example.com and save the page with the context by selecting `Save page with profile > universal zip fie`, the resulting file is named `Example Domain (...).u.zip.html`. It's a universal self-extracting file since the extension is `u.zip.html`, it also weights 54.3KB. If I click on the SingleFile button, the resulting file is named `Example Domain (...).html. It's not a universal self-extracting file (the extension is not `u.zip.html`, it weights 1.4KB.) because I use the default profile when I click on the button.

**Comment by redactedscribe** [comment]
I have done these tests numerous times and not once has a `*.u.zip.html` been created. Only `*.html`. I'm not sure what else I can say.

**Comment by gildas-lormeau** [comment]
Did you try to reset your options?

**Comment by redactedscribe** [comment]
I will try that now.

**Comment by redactedscribe** [comment]
That indeed produces a `*.u.zip.html`. The bug must be in my settings file. Maybe the profile's name has unexpected characters for example? I will try and find the problem.

**Comment by redactedscribe** [comment]
Here are two settings files. One works, the other does not. Doing a diff may reveal to you where the problem lies in my original configuration.

- `BROKEN.json` = my original configuration reduced to 1 profile ("Default settings") with file format changed to self-extracting ZIP universal. Does not produce `*.u.zip.html` files, only `*.html`.
- `WORKS.json` = Reset all options then set file format to self-extracting ZIP universal. Produces `*.u.zip.html` files.

[SingleFile broken vs working settings.zip](https://github.com/gildas-lormeau/SingleFile/files/12916940/SingleFile.broken.vs.working.settings.zip)

**Comment by redactedscribe** [comment]
Right. The `*.html` is because my file name template has .html in its file name... Let me investigate more.

**Comment by gildas-lormeau** [comment]
Thank you, I confirm the `{filename-extension}` template variable has indeed been added recently in order to avoid any confusion.

**Comment by redactedscribe** [comment]
[BROKEN - Default set to HTML, OTHER set to self-extracting ZIP (universal).json](https://github.com/gildas-lormeau/SingleFile/files/12917375/BROKEN.-.Default.set.to.HTML.OTHER.set.to.self-extracting.ZIP.universal.json)
[WORKS - Default and OTHER set to self-extracting ZIP (universal).json](https://github.com/gildas-lormeau/SingleFile/files/12917376/WORKS.-.Default.and.OTHER.set.to.self-extracting.ZIP.universal.json)

The diff between the files are these three lines:

![VSCodium_2023-10-16_16-49-34](https://github.com/gildas-lormeau/SingleFile/assets/25013746/2feb6d2f-c18e-4932-bf83-f9ca8d11ae73)

Please explore the JSONs files. What else in them could be causing the bug?

**Comment by redactedscribe** [comment]
Try resetting all settings then importing `BROKEN - Default set to HTML, OTHER set to self-extracting ZIP (universal).json`. Next visit http://example.com and "Save page with profile" > OTHER. Now open the saved web page in a browser. Is the resulting `*.u.zip.html` readable? Note: The profile has a custom path set for G:\ drive which may not exist on your system.

For me this produces scrambled text in the browser.

Since I cannot track down the bug, I guess I will just reset my options and re-create my profiles.

**Comment by redactedscribe** [comment]
Great news, thanks!

**Comment by redactedscribe** [comment]
Verified, it works with my old profile now.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback!
