### ISSUE TITLE
not saving correctly "Playstation"  website

### ISSUE THREAD

**Issue by karb10** [gildas-lormeau/SingleFile#1264]
**Describe the bug**
When save this Playstation [webpage](https://www.playstation.com/tr-tr/ps-plus/games/) , clickable buttons not working 

**Expected behavior**

**Screenshots**
![изображение](https://github.com/gildas-lormeau/SingleFile/assets/31970765/b15b57b5-cd96-488e-8659-73e6536c16af) 

**Environment**
 - OS: [. Win11 Pro, Firefox last version]

**Comment by gildas-lormeau** [comment]
This is a dynamic element handled by JavaScript. Unfortunately, some technical reasons make impossible for SingleFile to save scripts reliably, see https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages for more info.

**Comment by karb10** [comment]
> This is a dynamic element handled by JavaScript. Unfortunately, some technical reasons make impossible for SingleFile to save scripts reliably, see https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages for more info.

Changed this settings, fixed problem for full webpage save, but annotate saving not working javascript

However, you can save them by unchecking the option "Network > blocked resources > scripts", unchecking "HTML Content > remove hidden elements"
