### ISSUE TITLE
Extension do not work anymore because of new zip mode update. Revert to old for keep using it.

### ISSUE THREAD

**Issue by docop** [gildas-lormeau/SingleFile#1268]
Hi   While the app extension was quite nice, now it do not work anymore. Over ubuntu or mostly easily on windows with ff 93, 105, 115, 116
 version  1.21.64  / .66  do work.  all those 1.22.x not. Icon at top and print a white flag telling us the page canot be save. no matter a restart or refresh install: the extension updated kill it.

 *** for people who want to keep using it while searching for another extension :  manual download the revision on the ff extension page.
then install the .xpi  from the extension menu / mange.
 ** UnMht used to be the best and quick, but the removal part and annotation of singlefile was nice.

Perhaps doing a seperate extension name with the zip stuff can be good, if saving 10kb is important for some.

**Comment by gildas-lormeau** [comment]
This bug is fixed, see https://github.com/gildas-lormeau/SingleFile/issues/1258. You have to wait for the next version to be reviewed by Mozilla. It should be available for download in the coming days.

**Comment by gildas-lormeau** [comment]
The new version is available for download.
