### ISSUE TITLE
Add change history

### ISSUE THREAD

**Issue by AliM1988** [gildas-lormeau/SingleFile#127]
Hi 
Actually this is not a functional feature. I suggest to add a button near the "help" button named "change_log" to describe full change history. Many users want to know what features were added or what bugs were fixed. Maybe, they should check previous html that saved before and re-save them with new version.

Regard

**Comment by gildas-lormeau** [comment]
Hi,

Thanks for the proposal. Actually the change log is available on the Addons store of Firefox today. I'll try to implement it as you suggested.

**Comment by AliM1988** [comment]
Thanks.

**Comment by gildas-lormeau** [comment]
I re-open the issue since it's not implemented yet ;)

**Comment by AliM1988** [comment]
Are you implement it?

**Comment by gildas-lormeau** [comment]
No, you have to go to https://addons.mozilla.org/firefox/addon/single-file/versions/
