### ISSUE TITLE
SingleFIle on firefox-esr stopped working after last update

### ISSUE THREAD

**Issue by lhpitn** [gildas-lormeau/SingleFile#1270]
Hi,

on one of my ould debian boxes the single file extentions in firefox dosnt work anymore

its an old debian with firefox 91.13.0esr (64-bit) and there is no error message besides the red icon on top of the singlefile icon.

Ill try now to  upgrade my firefox and look if it fixes the problem, but maybe look into and if it is a problem with that version update the manifest so that it dosnt update on that old browser version...

thanks

**Comment by lhpitn** [comment]
Signle file Version
1.22.3

last update 6. october

**Comment by lhpitn** [comment]
yea, now after upgrading to 115.3.1esr (64-bit) everything works fine again, please look into it ;)

**Comment by gildas-lormeau** [comment]
This bug is fixed, see https://github.com/gildas-lormeau/SingleFile/issues/1258. You have to wait for the next version to be reviewed by Mozilla. It should be available for download in the coming days.

**Comment by gildas-lormeau** [comment]
The new version is available for download.
