### ISSUE TITLE
SingleFile Button not available in Extension Toolbar

### ISSUE THREAD

**Issue by fabianwenk** [gildas-lormeau/SingleFile#1272]
**Describe the bug**
I did just install SingleFile from AMO.
The SingleFile Button is not available in Extension Toolbar. It is also not available through "Customize Toolbar..." to be added. Restarting Firefox did also not help.

**Environment**
 - OS: macOS 13 (Ventura)
 - Browser: Firefox 118.0.2
 - Version: 1.22.5

**Comment by gildas-lormeau** [comment]
This is not something that SingleFile can control. If the icon is not visible even via the "puzzle" icon then it means that it's probably an issue with your profile data in Firefox.

**Comment by fabianwenk** [comment]
Somehow I have ignored the "puzzle" button until now. But yes, SingleFile was hiding in there. When clicking on the the "gear wheel" (settings) the menu shows up with a "Pin to Toolbar" option:
<img width="427" alt="Screenshot 2023-10-15 at 12 18 54" src="https://github.com/gildas-lormeau/SingleFile/assets/17186739/765c2276-2d27-4253-aa94-830f534fbb8f">
Which put into the Extension Toolbar:
<img width="211" alt="Screenshot 2023-10-15 at 12 19 50" src="https://github.com/gildas-lormeau/SingleFile/assets/17186739/ec1d30f8-998d-4b7a-a157-c8da46b2733d">
From there I could move it as usual through "Customize Toolbar..." also into the Bookmarks Toolbar.

Thank you very much for your help.

**Comment by gildas-lormeau** [comment]
You're welcome :)
