### ISSUE TITLE
Is not retrieving HTML5 Canvas images when the canvas tag is inside a shadow root element.

### ISSUE THREAD

**Issue by nmartins76** [gildas-lormeau/SingleFile#1276]
Tried with adobe express, https://www.adobe.com/express

Their website uses shadow elements all over the place, and when getting into the editor part, it uses canvas tag that will not display when running singlefile on it.

[Untitled - October 17, 2023 at 16.28.32 (10_17_2023 4_28_50 PM).zip](https://github.com/gildas-lormeau/SingleFile/files/13021914/Untitled.-.October.17.2023.at.16.28.32.10_17_2023.4_28_50.PM.zip)

**Comment by gildas-lormeau** [comment]
I confirm the issue with this test page: https://plnkr.co/edit/ZEiagCKFVZmfEcnC?open=lib%2Fscript.js&preview. However, the bug is specific to Chromium-based browsers, the canvas in the page is saved properly in Firefox and Safari. I will need to investigate more on this.

**Comment by gildas-lormeau** [comment]
Actually, the bug in Chrome is not related to the shadow root or the canvas, it's a problem related to iframes.

So, I cannot reproduce your issue. The image on this page https://run.plnkr.co/preview/clnw7iycr00052e6iqrahec7b/ can be saved properly in Firefox, Chrome, and Safari.

**Comment by gildas-lormeau** [comment]
I was actually able to identify

**Comment by nmartins76** [comment]
@gildas-lormeau Thank you for looking into that issue!

**Comment by gildas-lormeau** [comment]
@nmartins76 Is the shadow root attached to an element inside an iframe in your case?

**Comment by nmartins76** [comment]
@gildas-lormeau  I was checking that specific adobe example, and it doesn't looks like is sitting in an iframe

**Comment by gildas-lormeau** [comment]
@nmartins76 can you still reproduce this issue?

**Comment by nmartins76** [comment]
@gildas-lormeau yes, unfortunately, it still happens
 
 this is how the original looks
 
![image](https://github.com/gildas-lormeau/SingleFile/assets/63002511/dbc8f489-e53a-4f28-bac5-9bd2feef4ed7)

and how it comes from singlefile is attached to this comment
[Untitled - November 04, 2023 at 11.47.45 (11_4_2023 11_48_28 AM).zip](https://github.com/gildas-lormeau/SingleFile/files/13256553/Untitled.-.November.04.2023.at.11.47.45.11_4_2023.11_48_28.AM.zip)

**Comment by gildas-lormeau** [comment]
Thank you, I think this issue is due a known limitation, see https://github.com/gildas-lormeau/SingleFile#known-issues (2nd list item)
