### ISSUE TITLE
Cannot save https://github.com/polymorphicshade/NewPipe

### ISSUE THREAD

**Issue by iG8R** [gildas-lormeau/SingleFile#1282]
**Describe the bug**
SingleFile cannot save the page of https://github.com/polymorphicshade/NewPipe .

**To Reproduce**
1. Go to https://github.com/polymorphicshade/NewPipe
2. Try to save this page with SaveFile
3. The saving process hangs for an unknown period of time, but ultimately ends unsuccessfully, and the page becomes unresponsive.

**Expected behavior**
Saving this page properly.

**Environment**
 - OS: Microsoft Windows [Version 10.0.19045.2673] 64bit
 - Browser: Firefox 118.0.2 64bit
 - SingleFile 1.22.10

**Comment by gildas-lormeau** [comment]
It's a performance issue specific to Firefox. You can save the page but you have to be very patient.

**Comment by iG8R** [comment]
Hmm, I waited for about 10 minutes, but in the end nothing happened - as the page remained frozen, so it continued to stay in that state.
Did you manage to save this page?

**Comment by gildas-lormeau** [comment]
Yes I did, it took approximately 1 minute.

**Comment by iG8R** [comment]
I get it.
If I use the "self-extracting ZIP (universal)" file format - the behavior of SingleFile is like I described.
But, if I use the "HTML" file format - the page is saved immediately.

**Comment by gildas-lormeau** [comment]
I will try to find a workaround to fix the issue in Firefox, I wasn't realizing it was so slow.

**Comment by iG8R** [comment]
Thank you a lot.

**Comment by gildas-lormeau** [comment]
I was able to identify the cause of the issue and fix the perf issue. Now, it takes approximately 4 seconds to generate and download the ZIP file on this page. The fix will be available in the next version.
