### ISSUE TITLE
SingleFile error: TypeError: n.replaceAll is not a function

### ISSUE THREAD

**Issue by bsod-interia** [gildas-lormeau/SingleFile#1285]
SingleFile error: TypeError: n.replaceAll is not a function - подобное выдает уже около недели в расширении хрома

**Comment by gildas-lormeau** [comment]
Did you change the filename template is the settings?

**Comment by bsod-interia** [comment]
Нет. Ничего не трогал

**Comment by gildas-lormeau** [comment]
That's strange, does it happen an any page you try to save?

**Comment by bsod-interia** [comment]
да. совершенно верно, на любой ((

**Comment by gildas-lormeau** [comment]
Maybe your settings are somewhat corrupted, can you try to reset them by clicking on the button "Reset" in the options page and tell me if it helps?

---

Возможно, Ваши настройки несколько повреждены, попробуйте сбросить их, нажав кнопку "Сброс" на странице параметров, и сообщите мне, если это поможет?

**Comment by bsod-interia** [comment]
failed ((
не удалось ((

screenshot
скрин 

https://imgbox.com/jFRqz82c

**Comment by gildas-lormeau** [comment]
Does the version 1.22.15 solve the issue?

**Comment by bsod-interia** [comment]
эта версия установлена (
https://imgbox.com/yINWQYK3

**Comment by gildas-lormeau** [comment]
The extension is disabled in your screenshot, is this normal?

**Comment by gildas-lormeau** [comment]
Also, what browser and which version are you using?

**Comment by bsod-interia** [comment]
Если оно не работает, зачем его держать включеным? Естественно нормально! Вы будете держать нерабочее приложение включенным?
На скриншоте я вам показал версию

**Comment by gildas-lormeau** [comment]
I'm referring to the browser you're using. There are approx. You're the only user that is reporting this bug. I try to do my best. Sorry if this doesn't satisfy you.

**Comment by gildas-lormeau** [comment]
Je fais référence au navigateur que vous utilisez. Vous êtes le seul utilisateur à avoir signalé ce bogue. J'essaie de faire de mon mieux. Désolé si cela ne vous satisfait pas. Vous êtes en effet libre de faire ce que vous voulez, y compris de ne pas vous plaindre sur les pages de mon projet.

**Comment by bsod-interia** [comment]
Версия браузера 
Cent Browser
Версия 4.2.9.152 (Официальная сборка), (32 бит) (portable) (Chromium 80.0.3987.163)

Думаете из-за этого?  :(

**Comment by gildas-lormeau** [comment]
I confirm this is due to the version of Chrome. `replaceAll` has been added in Chrome 85, see https://caniuse.com/?search=replaceAll.

**Comment by bsod-interia** [comment]
Да. Давно бы обновил.
Но одно расширение, самое нужное у меня на оновленный браузер не установится, что очень печально.

Спасибо вам за уделенное время. 
Ваше приложение хорошее. 👍 
Желаю успехов

**Comment by gildas-lormeau** [comment]
Спасибо за поддержку, попробую обойтись без использования replaceAll, если это единственное, что мешает.

**Comment by gildas-lormeau** [comment]
Эта ошибка будет исправлена в следующей версии.
