### ISSUE TITLE
Annotate and save the page now opens 2 pages / tabs

### ISSUE THREAD

**Issue by 101Monkey** [gildas-lormeau/SingleFile#1286]
Recently, SingleFile started giving me an error each time I tried saving a page. After doing some tests, I’ve seen that it was linked to my default profile in Firefox. I resetted SingleFile settings, and that took care of that problem.

But since then, if I set SingleFile to open saved pages in a new tab, and then use “Annotate and save the page”, 2 new pages are opened: the saved page and the same page opened in the SingleFile editor. So 3 pages in all:

* the original page
* the saved page
* the page in the editor.

Before, when I used “Annotate and save the page”, it resulted in only 1 new page being opened in the editor (SingleFile was set to open saved pages in a new tab; I’ve been using that seting for a long time).

I did some test in a new profile where the only extension was SingleFile, and I got the same result. So this time, it’s not a problem with my Firefox profile or a corrupted settings file.

Did the last update changed SingleFile’s “Annotate and save the page” behavior, so that it now open 2 pages (the saved page, and the same page in the editor)? Or is it a bug?

**Comment by gildas-lormeau** [comment]
Thank you the detailed an clear report. I must confess I don't know (remember?) if it's a bug or a feature. This is probably the result of some refactoring related to SFZ integration and a new technique to display saved pages.

From a logical point of view, it's a feature. From a practical point of view, it's a bug. I'm going for practicality, as this feature seems unnecessary. I'll take a look at what caused this regression and fix it.

**Comment by gildas-lormeau** [comment]
I fixed the bug, the fix will be available in the next version.
