### ISSUE TITLE
Single File does not work - stuck on "Initializing Singlefile (2/2)

### ISSUE THREAD

**Issue by bostongarden** [gildas-lormeau/SingleFile#1287]
For questions, please create or update a thread here: 
https://github.com/gildas-lormeau/SingleFile/discussions

Please ensure that you do not find an answer before reporting the issue:
 - in the FAQ: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md
 - in the list of known issues: https://github.com/gildas-lormeau/SingleFile#known-issues
 - in the help page embedded in the extension

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - OS: [e.g. Win10 Pro, Ubuntu 18.04.1, Android 7.1.2]
 - Browser: [e.g. Chrome, Firefox]
 - Version: [e.g. 64]

**Additional context**

**Comment by bostongarden** [comment]
using 1.22.14 - auto update yesterday (10/30) - doesn't work now

**Comment by gildas-lormeau** [comment]
Please go to https://www.example.com, save the page, and press F12. to open the Console in the Dev Tools. Do you see any error message in the console?

**Comment by bostongarden** [comment]
It works fine on that page. Not sure why it misbehaved on the other page.

**Comment by gildas-lormeau** [comment]
What is the URL?

**Comment by bostongarden** [comment]
[image: Screen Shot 2023-11-01 at 5.30.58 AM.png]
Above is screen shot is from Firefox settings (about:preferences) showing
the problem - you an see three dots in the green box within the Singlefile
button. When I hover over that box it says "Initializing Singlefile (2/2)"
but I can't get that in the screenshot.

**Comment by gildas-lormeau** [comment]
The attached screenshot is not visible on GitHub unfortunately.

**Comment by bostongarden** [comment]
I can sent it to you by email if you like.

**Comment by gildas-lormeau** [comment]
@bostongarden Is this bug fixed?

**Comment by bostongarden** [comment]
Yes, thanks - it's fixed.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback, I'm closing this issue.
