### ISSUE TITLE
Provide some help/documentation for the expandable macros in "File Name -> template" field

### ISSUE THREAD

**Issue by cmvizitiu** [gildas-lormeau/SingleFile#129]
I can't figure out what {macro}s to use in the File Name -> template filed. E.g. I tried {host} for the host name but to no avail. Even worse, there seems to be no way to restore the defaults.

A tooltip with all possible macros should do (if the list's not too long) but an addition to Readme.md would do too. 

Changing the filed's HTML might be an idea also but will needlessly lengthen the area once expanded.

**Comment by gildas-lormeau** [comment]
It's documented in the help page which is accessible via the options page. Defaults can be restored by clicking the "Reset" button.

**Comment by cmvizitiu** [comment]
Given the way "Reset" was positioned I assumed it'll reset everything and that was not what I was looking for. As for the "help" page? My bad for missing it, sorry.

**Comment by gildas-lormeau** [comment]
Indeed the "Reset" button resets everything.
