### ISSUE TITLE
"Illegal characters" error when saving discussion threads from specific domains to any subdirectory

### ISSUE THREAD

**Issue by HJackal** [gildas-lormeau/SingleFile#1290]
A warning _SingleFile error: filename must not contain illegal characters_ appears and the add-on fails to save the webpage in question whenever I try to save individual discussion threads from the image board domains "komica1.org" and "komica2.net".

- It started to happen after the 1.22.17 update for Firefox add-on.
- Option "save pages in background" was checked all the time. "_" (underscore) was used as the replacement character (chosen by default).
- The error also occurred in private window or after restarting the browser.
- Resetting the add-on option (thus removing the subdirectory and the character "/" from the file name template) fixed the problem. The error occurred again when the path of any subdirectory was added to the template, even when the other settings were kept at the default values.
- The error did not occur when saving webpages from other domains. Webpages were saved under the specified subdirectory as intended.

**To Reproduce**

1. Add any subdirectory (new or existing) to the file name template
2. Open any individual thread hosted on komica1.org or komica2.net in a new tab (example: https://tomo.komica1.org/38/pixmicat.php?res=2719626)
3. Click on the "Save page with SingleFile" button located in the toolbar or extension list.
4. A banner with the text "SingleFile error: filename must not contain illegal characters" appears under the address bar. The webpage is not saved.

**Environment**

OS: Windows 10 Pro (64-bit)
Browser: Mozilla Firefox 119.0 (64-bit)
Add-on Version: 1.22.17

**Comment by gildas-lormeau** [comment]
Thank you for the report. I was to reproduce and fix the bug. The fix will be available in the next version.
