### ISSUE TITLE
Fails to save page with malformed attribute on nested <a> tag

### ISSUE THREAD

**Issue by mwdmwd** [gildas-lormeau/SingleFile#1299]
**Describe the bug**
When trying to save a page that contains an `<a>` nested in another `<a>`, where the inner one has an attribute with an invalid name, saving fails on [this setAttribute](https://github.com/gildas-lormeau/single-file-core/blob/f6221d9edf4175017e9d210108711427fc5e7211/core/index.js#L840) call in `replaceInvalidElements` during Step 1.

**To Reproduce**
1. Go to https://www.zycieodkuchni.pl/
2. Click on 'Save page with SingleFile'
3. See `SingleFile error: InvalidCharacterError: String contains an invalid character`

**Expected behavior**
The page is saved successfully

**Environment**
 - OS: Linux
 - Browser: Firefox 119.0.1

**Additional context**
Small reproducer:

```html
<a id=parent></a>
<a id=test href=http://example.com '>frog</a>

<script>
    document.getElementById("parent").appendChild(document.getElementById("test"));
</script>
```

**Comment by gildas-lormeau** [comment]
Thanks, I was able to reproduce the problem. It has to do with the fact that `Element#setAttribute()` is called with "'" as first parameter, which is invalid. Since this is a bit of a twisted case, I decided to ignore the exception.

**Comment by mwdmwd** [comment]
Thank you for the quick reply and fix! I'll close this issue since I see it's already fixed in `single-file-core` https://github.com/gildas-lormeau/single-file-core/commit/f4beae3ba5d2804fed319520df6ddcc56f52c278 and I can confirm that this solves the problem.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback!
