### ISSUE TITLE
The file name of a page saved with SingleFile looks like "56833935-156b-4d8c-a00f-19599c6513d3", why?

### ISSUE THREAD

**Issue by alphyoung** [gildas-lormeau/SingleFile#130]
When i click the button to save a page, the file name may looks like "56833935-156b-4d8c-a00f-19599c6513d3". How can I have file named by its page title? Thx.

**Comment by gildas-lormeau** [comment]
Do you use a download manager extension? I've seen this kind of issue in the past with the extension  "Free Download Manager Extension", cf. https://github.com/gildas-lormeau/SingleFile/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+file+name. In this case, unchecking "save pages in background" should fix the issue.

**Comment by alphyoung** [comment]
> Do you use a download manager extension? I've seen this kind of issue in the past with the extension "Free Download Manager Extension", cf. [#58 (comment)](https://github.com/gildas-lormeau/SingleFile/issues/58#issuecomment-412855461). In this case, unchecking "Misc > save pages in background" in the options page should fix the issue.

Thanks, it works.

**Comment by gildas-lormeau** [comment]
@alphyoung, in order to investigate a little bit more on this issue, can you confirm or infirm you have an extension similar to the one I cited that could be the source of the problem?

**Comment by gildas-lormeau** [comment]
I added a note about this issue in the "Known issues".

**Comment by bansan85** [comment]
Just for the record, I have the same problem since I installed DownThemall!. If I disable it, I don't have the problem anymore.
I confirm that unchecking "Misc > save pages in background" also works.

**Comment by gildas-lormeau** [comment]
@bansan85 Thank you for the feedback. It seems this issue is often related to download managers and I thank you for the feedback. On my end, I was able to reproduce it without installing any download manager. The only way I found to fix the issue (apart from unchecking "Misc > save pages in background") was to reinstall to Chrome. I hope Google will fix this bug someday...

**Comment by dnknn** [comment]
> In this case, unchecking "Misc > save pages in background" in the options page should fix the issue.

@gildas-lormeau  unchecking "Misc > save pages in background" cannot be solved 100% , e.g. When SingleFile auto-saving, it still doesn't work! 

![212_17073129](https://user-images.githubusercontent.com/10995302/108134994-36e05480-70f2-11eb-8314-562e2498a281.png)



- I was curious, so I checked the extensions one by one, and finally found the hidden culprit 🤦!

- When I disable [**Double-click Image Downloader**](https://chrome.google.com/webstore/detail/bkijmpolkanhdehnlnabfooghjdokakc) extension,  After that, everything is normal for SingleFile without any problems 😁

- I also reported there :  👇

### 🌐 https://gitlab.com/Marnes/doubleclick-image-downloader/-/issues/91

**Comment by gildas-lormeau** [comment]
Thank you @dnknn for your investigation on this issue! Unfortunately, this is a bug in Chrome and I don't think the author of the extension will find a way to circumvent it reliably.

**Comment by leaumar** [comment]
If your hunch is right, I've heard of this problem before, and I think my conclusion at the time was it's indeed hopeless. I think the API for download filename manipulation just isn't really designed for multiple manipulators.

**Comment by gildas-lormeau** [comment]
@leaumar Thank you for your feedback! Note that the bug is in the Chrome implementation, the same API works well in Firefox.

**Comment by leaumar** [comment]
That's because firefox still has not implemented download filename manipulation 😅
