### ISSUE TITLE
Saved files of the same page are different in size depending on whether the text on this page has been selected

### ISSUE THREAD

**Issue by iG8R** [gildas-lormeau/SingleFile#1301]
**Describe the bug**
When a web page has just been loaded and no manipulations have been made on it, after saving it, the resulting file is smaller in size than when text was selected on the page before saving.

**To Reproduce**
1. Go to any web page
2. Save it with "Save page with SingleFile"
3. Select any text on this page
4. Save it again with "Save page with SingleFile"
5. Compare the sizes of the saved pages

**Expected behavior**
The size of the saved page should be the same regardless of whether the text was selected previously or not.

**Screenshots**

[SingleFile-file-size-issue-Video_2023-11-15_20-26-34.webm](https://github.com/gildas-lormeau/SingleFile/assets/11407417/ffb123d0-c814-4c85-8e36-7c81c2dc1147)

**Environment**
 - OS: Microsoft Windows [Version 10.0.19045.2673] 64bit
 - Browser: Firefox 119.0.1 64bit

**Comment by gildas-lormeau** [comment]
Generally speaking, selecting the text should not change the size of the saved page. You can do some tests on https://www.example.com to verify this. However, I guess this website trigger some JavaScript code when you select the text which makes probably the page bigger. I don't see how this could be circumvented in SingleFile.

**Comment by iG8R** [comment]
The same result with www.example.com. Even the difference in size is almost the same - 6KB.
Does SingleFile use the browser cache to save the page and doesn't reload it?

[SingleFile-file-size-issue-example.com--Video_2023-11-16_18-54-51.webm](https://github.com/gildas-lormeau/SingleFile/assets/11407417/3c88fd30-9e66-4eb4-b454-cc56754774a3)

**Comment by gildas-lormeau** [comment]
I cannot reproduce your issue. I guess it's related to another extension you're using.

**Comment by iG8R** [comment]
As it turned out, it's due to user scripts. But, doesn't SingleFile download the page from scratch when it saves it?

**Comment by gildas-lormeau** [comment]
By default SingleFile saves the page as it is displayed. You can save the raw page (see "HTML content" section in the options page). However this might lead to data loss, compared to the displayed page.

**Comment by iG8R** [comment]
Then everything is clear why any manipulation with the page increases its size - this is because of the code that user scripts leave.

**Comment by iG8R** [comment]
Well, maybe not exactly a bug, because the code is left after the scripts that just deal with text processing - the script-translator ( https://greasyfork.org/en/scripts/36842-google-select-text-translator ) and the script that manipulates selected text - looking for its occurrences on the page itself, as well as on search engines on the Internet ( https://greasyfork.org/en/scripts/445274-searchjumper ).
And they leave the code precisely because they don't have to inject it every time the text is selected.

**Comment by gildas-lormeau** [comment]
I'm not going to debug these scripts to see if they can work without leaving traces in the DOM. On paper, it's possible though. Scripts, elements, texts, binary objects etc. can be stored in RAM without these resources being present in the DOM.

In any case, this is not a bug in SingleFile. Note that if you know how to code user scripts, you could probably solve this problem by cleaning up the DOM before saving the page, see https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved for more info.

**Comment by iG8R** [comment]
Thanks a lot for the advice!

**Comment by gildas-lormeau** [comment]
You're welcome!
