### ISSUE TITLE
save to Google Drive does not work

### ISSUE THREAD

**Issue by paponius** [gildas-lormeau/SingleFile#1306]
**Describe the bug**
save to Google Drive does not work
additionally, I can't select which google account I want to use

**To Reproduce**
save to google in options
save page
a page will for google login - expected
an error is shown: access blocked ... Error 400

**Expected behavior**
login instead of an error

**Screenshots**

**Environment**
 - OS: [e.g. Win10 Pro, Ubuntu 18.04.1, Android 7.1.2]
 - Browser: [e.g. Chrome, Firefox]
 - Version: [e.g. 64]

**Additional context**
would you like me to edit this to add more info, or is this known or easily reproducible error?

**Comment by gildas-lormeau** [comment]
Thank you for the report, the bug was a regression with Google Drive support in all browsers but Chrome. The fix will be available in the next version.
