### ISSUE TITLE
{url-hostname-root} and {url-hostname-domain} variables incomplete

### ISSUE THREAD

**Issue by Ugau943** [gildas-lormeau/SingleFile#1309]
Hello, thanks for this extension.

I've searched trough the doc and issues, but I thing there isn't anything (it's about a recent feature though https://github.com/gildas-lormeau/SingleFile/commit/a1aa6d83fb5df890c2ecf88735cc4e5433ca58a4 https://github.com/gildas-lormeau/SingleFile/issues/1279).

**Describe the bug**
When using the {url-hostname-root} or {url-hostname-domain} variable, the result may be incomplete (in my case, the first letter is missing). At least, it does it with https://jdownloader.org/, so perhaps it will show up in other cases (I haven't had this problem with other sites yet).

**To Reproduce**
1. Go to SingleFile Options page
2. 
    - Set "{url-hostname-root}.{filename-extension}" as _Template_ under _File name_ section 
    or
    - {url-hostname-root} as _Template of the infobar content_ under _Infobar_ section)
3. Go to "https://jdownloader.org/"
4. Save page with SingleFile
5. See that the filename is "downloader.org" (or the infobar shows "downloader.org") instead of **j**downloader.org

(same with {url-hostname-domain})

**Expected behavior**
{url-hostname-root} variable shouldn't truncate the "j" in the name.

**Environment**
Tested both with Firefox and Chrome.   
   
  
Thanks for your answers

**Comment by gildas-lormeau** [comment]
Thank for the detailed report. I confirm I was able to reproduce and fix the bug. The fix will be available in the next version.
