### ISSUE TITLE
Scripts work with the "HTML" format but not self-extracting files

### ISSUE THREAD

**Issue by suicidewhale** [gildas-lormeau/SingleFile#1313]
I'm having few issues with this extension.

**1.** I use this extension for a website which is some kind of forum. Some user comments are too long and automatically wrapped after ie 100 words and the rest of the comment is hidden in a word wrap link. When I save the page with singlefile, this link disappears. 

For example;

[this is an example topic from the site](https://eksisozluk1923.com/super-chat-enstantaneleri--37302?a=nice
)
You can see the first comment is:

> cinsi sapık iş arkadaşımın kız nickiyle ircye girip ettiği halt. şöyle ki;
> 
> start of jnd_astsby buffer: wed jul 06 20:01:26 2005
> 
> session ident: jnd_astsby (x@85.101.188.zurnanet-7623)
> <jnd_astsby> slm
> <sanal_zevk> selam
> <jnd_astsby> asl pls
> <jnd_astsby> asl pls
> <sanal_zevk> sen harbiden jandarma astsubaymisin

And there is a link below the comment called "**devamını okuyayım**" . If you save the page (whether you click on the link or not), the link disappears on the output. So from the output file, you can read only the first few lines from the comment, rest is hidden and not possible to be viewed since the link is absent.

BTW you can see content is still present when you view the source on output file.  So I believe this is just a problem about styling.

**2.** I also use this extension to save some pages on reddit and I use RES [Reddit Enhancement Suite] extension on chrome. As you know RES does some styling on reddit pages, however when you save the page, these stylings will not come into effect on the output file.

I tried to change some option settings but no success.

**Comment by gildas-lormeau** [comment]
I fixed the issue with self-extracting files. The fix will be available in the next versions of SingleFile and SingleFileZ.
