### ISSUE TITLE
auto close on batch doesn't work

### ISSUE THREAD

**Issue by mike-code** [gildas-lormeau/SingleFile#1314]
If you have "auto-close the tab after the page is saved" enabled, using "Batch save URLs..." option won't close the opened tabs after they are saved. 

Happens both on Firefox and Chrome.

**Comment by gildas-lormeau** [comment]
Actually, this option is ignored when saving in batch mode. However, I've just found a bug that could prevent some tabs to be closed. I've just fixed this bug. Could you please install manually the extension (see https://github.com/gildas-lormeau/SingleFile#install) and tell me if it fixes your issue?

**Comment by mike-code** [comment]
thx. auto closing on batch save works now. I tried on ~1400 urls and around ~20 of them didn't auto close (though they were saved). That's not a big issue though, more of a nitpick

**Comment by mike-code** [comment]
another issue I experienced is that if I put say 500 urls. The last ~30 or ~10 won't be opened. Like it stops opening near the end of the batch even though I see them on the list before pressing "save".

**Comment by gildas-lormeau** [comment]
Thank you for the feedback @mike-code. When you run this kind of test, do you notice an increase in RAM consumption? Also, is the RAM full or not?

**Comment by mike-code** [comment]
The ram consumption naturally increases due to number of opened tabs (Chrome) but  I don't see RAM getting even close to the max.

**Comment by gildas-lormeau** [comment]
I did some tests and I was able to reproduce the issues you described. Actually, these were regressions but I don't know when I introduced them. Hopefully, everything will work fine in the next version which should be available soon for download.
