### ISSUE TITLE
svg resources have incorrect mime-type

### ISSUE THREAD

**Issue by mike-code** [gildas-lormeau/SingleFile#1315]
I have an `<object>` element that has a `data` property with svg file href.

Example

```
<object id="my_svg" data="/image/foo.svg" type="image/svg+xml" onload="loadSvg()"></object>
```

As you can see there's an onload function that grabs the `data` href and creates an `<svg>` element.

The problem is that Single File will save this as 

```
<object d="my_svg" data="data:application/octet-stream;base64,........">
```

so it uses `data:application/octet-stream;base64` instead of `data:image/svg+xml;base64`.

This happens on Chrome and Firefox although on Firefox it works correctly 80% of the time while on Chrome it doesn't ever work.

**Comment by gildas-lormeau** [comment]
Thank you for the report. I confirm that the type attribute was ignored for `<object>` and `<embed>` tags. I've just added the implementation to support it (see https://github.com/gildas-lormeau/single-filez-core/commit/283b70cd25dc5dc79a9022631693d237ae4863af). The fix will be available in the next version.
