### ISSUE TITLE
A suggestion for Reset button

### ISSUE THREAD

**Issue by AliM1988** [gildas-lormeau/SingleFile#132]
Hi
I have a suggestion for Reset button in Options.
It's better Reset button just clear settings for selected profile not remove all profiles.
Regard

**Comment by gildas-lormeau** [comment]
Hi, can you give more details about how better it would be? I'm really mixed about that. I think there are pros and cons in the 2 cases and I am not convinced today to change the behavior of this button.

**Comment by AliM1988** [comment]
Hi, sorry for my late response.
For example, we have 4 profiles and I want to reset 3rd one to default settings. The RESET button can't help. Because it delete all user profiles and reset default profile. If you are not convinced, alternatively, RESET button can prompts user to reset current profile or all profiles. I think it can be better.
Regard

**Comment by gildas-lormeau** [comment]
No problem for the delay. Now, here is my use case: a user created 200+ profiles and want to delete them all. With the reset button acting like you described, will he be forced to click 200+ times on the "-" button and confirm the deletion of all profiles?

**Comment by AliM1988** [comment]
In the alternative suggestion, I mentioned RESET button prompts user to reset current profile or all profiles.

**Comment by gildas-lormeau** [comment]
Unfortunately, I cannot create (easily) a popup with custom buttons. The only popup types I can use are: 
* `prompt` to ask the user to type a string
* `confirm` to confirm an action: the button labels are "OK" and "Cancel" and cannot be changed
* `alert` to display a value

The popup you're suggesting would have 3 buttons but this type of popup does not exist natively in a browser. I need to be implemented from scratch and I consider it would be overkill to do so.

**Comment by AliM1988** [comment]
Hi. I See the v1.9.39. As you describe, RESET can just Reset & Delete all profiles and another option is Cancel. I have another suggestion: RESET button would reset current profile only. To delete all profiles you can add an extension on "-" button, add a drop-down near this button to delete all. I think it's better because the previous function of RESET button was delete all profiles not reset all profiles.

**Comment by gildas-lormeau** [comment]
Your proposal is fine but requires some additional development related to the "-" button. The other issue is that it fundamentally changes the behavior of the Reset button. Actually, this button exists now for more than 9 years in SingleFile and has always meant it would reset all the options. The idea is to help me debugging issues by making sure all options are deleted and back to their default values when troubleshooting a bug.

**Comment by gildas-lormeau** [comment]
Thanks for the suggestions. I'll try to see what can be done.

**Comment by gildas-lormeau** [comment]
This issue should be fixed in the new version 1.9.47.
