### ISSUE TITLE
Hang on IBM page

### ISSUE THREAD

**Issue by notuntoward** [gildas-lormeau/SingleFile#1324]
When I try to capture this page:

https://www.ibm.com/topics/boosting#:~:text=In%20boosting%2C%20a%20random%20sample,form%20one%2C%20strong%20prediction%20rule.

SingleFile hangs on Step 1 (screenshot).  After waiting a while either browser asks if I want to continue to wait or stop the process.

This is on either Brave or Firefox.

<img width="600" alt="image" src="https://github.com/gildas-lormeau/SingleFile/assets/3851891/bd709118-a87b-4c80-a3a7-f3555b19b3e2">

**Comment by gildas-lormeau** [comment]
Thank you, I was able to reproduce and find the cause of the issue. The fix will be available in the next version.
