### ISSUE TITLE
README mentions  "Annotate and save the page..." but this doesn't exist

### ISSUE THREAD

**Issue by notuntoward** [gildas-lormeau/SingleFile#1325]
The README mentions a context menu item called "Annotate and save the page..." but this doesn't exist (anymore?) on the SingleFile icon or when the cursor is on the web page itself.

**Comment by notuntoward** [comment]
It's set to "edit the page".  Same thing?

![image](https://github.com/gildas-lormeau/SingleFile/assets/3851891/b706f6c3-ac92-49a5-8637-3da028cd5dcc)

**Comment by notuntoward** [comment]
A bit off topic, but I remember from a while ago that you suggested using one for your repos to enable saving an already saved web page back to the location that it was loaded from.  But I can't find that repo now.  Is there an alternative?

**Comment by gildas-lormeau** [comment]
Yes, the "default mode" option has not effect on the menu entry removal.

Regarding the off topic issue, I guess this is the program you're looking for: https://github.com/gildas-lormeau/single-file-companion-lite.
