### ISSUE TITLE
Downloaded web pages lose interactivity.

### ISSUE THREAD

**Issue by JingofXin** [gildas-lormeau/SingleFile#1327]
I'm trying to download this page: https://distill.pub/2021/understanding-gnns/. But downloaded web pages lose their interactive content. Click the interact button below, it will not switch the page content. I followed the steps below, but they didn't work: save them by unchecking the option "Network > blocked resources > scripts", unchecking "HTML Content > remove hidden elements"
![image](https://github.com/gildas-lormeau/SingleFile/assets/31361630/63aa6942-8eb1-4541-9d4a-d50dc000eed8)

**Comment by gildas-lormeau** [comment]
If you followed these instructions https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages but it does not work then there's nothing I can do unfortunately.

**Comment by JingofXin** [comment]
> If you followed these instructions https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages but it does not work then there's nothing I can do unfortunately.

Or not. thank you.
