### ISSUE TITLE
Cant save annotated web page with javascript

### ISSUE THREAD

**Issue by karb10** [gildas-lormeau/SingleFile#1329]
Created new profile with Single File, enabled all possible settings for save full webpages

Firefox last version, Windows 11 last version. When annotate and save [this page,](https://www.playstation.com/tr-tr/ps-plus/games/) buttons not working

![изображение](https://github.com/gildas-lormeau/SingleFile/assets/31970765/e6014c17-2ded-45b1-a8d3-6f4e6047bc6c)

**Comment by gildas-lormeau** [comment]
If you followed these instructions https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages but it does not work then there's nothing I can do unfortunately.
