### ISSUE TITLE
File name limit(s) would be a good to have

### ISSUE THREAD

**Issue by cmvizitiu** [gildas-lormeau/SingleFile#133]
With the file name set to {page-title}, annoyingly often I bump into the 255 chars file name limit(s). I then try to edit/delete some chars from within the file name dialog... of course, there is no way to guess how long the title (and thus the file name) was if only because the "Save As" window was not meant for this so I have to make several attempts before I finally get the right number of chars. A simple "trim file name up to X chars" would do wonders. 

I can think of two implementations:

a) an extension of the {page-title} tag using and optional number (plus some defined separator) e.g. {page-title::255}  or a new tag e.g. {max-file-name::255}. Using only the "-" should do too if we agree that, by convention, if the last chars after a dash are numbers they should be interpreted as "max value for the field"

b) a "trim filename to [ xxx ] chars" config option would also solve the problem

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. Right now, I'm tempted to implement:
c) trim all filenames to 255 chars because other template variables could lead to the same issue and because I don't really want to add a new option for this. I consider there are already too much of them :p

**Comment by cmvizitiu** [comment]
... apparently not! 👎 Think we can close this for the moment.

**Comment by gildas-lormeau** [comment]
@cmvizitiu FYI, maybe the issue you were trying to describe is this one: https://github.com/gildas-lormeau/SingleFile/issues/142.
