### ISSUE TITLE
Save Selection not seem to save code snippets in pages 

### ISSUE THREAD

**Issue by gerroon** [gildas-lormeau/SingleFile#1332]
**Describe the bug**
It looks like it is not saving the code snippets in Medium article sample codes.
**To Reproduce**
Select the body and save selection https://phibr0.medium.com/how-to-create-your-own-obsidian-plugin-53f2d5d44046

**Expected behavior**
It would be nice if it actually saves the example codes in the pages. It is interesting that the page saving works, but not the selection saving.

**Environment**
 - OS: Win 11
 - Browser: Brave
 - Version: Chromium 119 6045

**Comment by gildas-lormeau** [comment]
Thank you, I was able to reproduce and fix the issue. The fix will be available in the next version.
