### ISSUE TITLE
"Save selection" is not working for some pages

### ISSUE THREAD

**Issue by chs33** [gildas-lormeau/SingleFile#1333]
For example, [this page](https://quant.stackexchange.com/questions/59477/option-strategy-collar)
after doing this
![image](https://github.com/gildas-lormeau/SingleFile/assets/16418270/2b3c272c-dcc8-4805-a6a4-add89b5276b0)

the plugin will be forever stuck at this state 
![image](https://github.com/gildas-lormeau/SingleFile/assets/16418270/213cf440-8c69-4880-9733-bbe303867f16)

OS: tried both Windows 7 and macos
Browser: Chrome 119.0.6045.200 (Official Build) (64-bit)

**Comment by gildas-lormeau** [comment]
I confirm I saved a selection, from your page, with Chrome. See the attached file.

[Option strategy Collar - Quantitative Finance Stack Exchange (06_12_2023 21_40_28).html.zip](https://github.com/gildas-lormeau/SingleFile/files/13591379/Option.strategy.Collar.-.Quantitative.Finance.Stack.Exchange.06_12_2023.21_40_28.html.zip)
