### ISSUE TITLE
Saved Infobar broken on Pale Moon browser

### ISSUE THREAD

**Issue by Gittyperson** [gildas-lormeau/SingleFile#1334]
SingleFile 1.21.56 and earlier versions do not cause this issue. After v.1.21.60, the included Infobar does not either work, or display correctly on latest Pale Moon browser:

The saved URL will not open, the Infobar will simply close instead. Also, the Close button is not displayed.

"include the infobar in the saved page" = enabled
Tested on SingleFile 1.22.36 (Firefox 120.0.1), Pale Moon 32.5.1, Windows 10

**Comment by gildas-lormeau** [comment]
The problem is that it's a bug in Pale Moon. The "new" infobar works in all browsers except Pale Moon. I made these changes to make the infobar compatible with Safari, so I cannot revert them.

**Comment by gildas-lormeau** [comment]
For the record, here is a simple example of infobar that works as expected in all browser except Pale Moon: https://plnkr.co/edit/dqGmg22rRiRnsgyd

Any workaround is welcome as long as it does not rely on JavaScript.

**Comment by gildas-lormeau** [comment]
Issue on the bug tracker of Pale Moon: https://repo.palemoon.org/MoonchildProductions/UXP/issues/2401

**Comment by Gittyperson** [comment]
Fixed in Pale Moon 33. Many thanks for your help in locating the issue.
