### ISSUE TITLE
"TypeError: e.findLast is not a function"

### ISSUE THREAD

**Issue by zanglebert** [gildas-lormeau/SingleFile#1336]
SingleFile version: 1.22.36

Using default settings, the extension stopped working during "Step 3/3", with error message "TypeError: e.findLast is not a function".

When reducing functionality to a minimum via settings (don't save deferred images, block all resources under "Network"), the error does *not* occur, but I can't pinpoint the exact setting that leads to the breakdown.

**Comment by gildas-lormeau** [comment]
What is the browser and the version of the browser you're using?

**Comment by gildas-lormeau** [comment]
This issue will be fixed in the next version.

**Comment by zanglebert** [comment]
> What is the browser and the version of the browser you're using?

_Firefox,_ and _very, very outdated_ (78.15.0esr).

Thank you for the fix, it's much appreciated!
