### ISSUE TITLE
Saved page is broken: https://ig.ft.com/generative-ai/

### ISSUE THREAD

**Issue by flyisland** [gildas-lormeau/SingleFile#1337]
**Describe the bug**
The saved page of https://ig.ft.com/generative-ai/ is broken.

**Environment**
 - OS: macOS Sonoma 14.1.2
 - Browser: Chrome, Version 119.0.6045.159 (Official Build) (arm64)
 - SingleFile: 1.22.37

**Additional context**
The original webpage utilizes advanced technology to create a dynamic scrolling experience that effectively presents the author's ideas. However, it appears that the saved version of the page is unable to replicate this dynamic behavior, resulting in an inaccurate representation of the author's intended message.

**Comment by gildas-lormeau** [comment]
Did you try to follow these tips? https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages

**Comment by flyisland** [comment]
@gildas-lormeau thanks for the info, I followed the FAQ to try it again but the saved page is still broken.

Since this is an expected result, I'll close this issue.

**Comment by gildas-lormeau** [comment]
@flyisland Thank you for your feedback. I'm sorry nothing worked.
