### ISSUE TITLE
In Batch save URL section, It should block user from entering invalid URLs

### ISSUE THREAD

**Issue by GaneshDabhade** [gildas-lormeau/SingleFile#1345]
Bug Description:
In the Batch Save URL--> "Add URLs" popup it allows the user to enter invalid URLs. 

**To Reproduce**
1. Go to the Batch Save URL and in an empty text box enter any invalid URL (Any string of random characters  e.g "github.com/")
2. Click on the "Add URL" button. 
Behavior: Here it do not allow to enter invalid URL. Which I think is the correct expected behaviour.
3. Now click on "Add URLs..." button, In the pop up displayed try to add same invalid URL ("github.com/")

**Bug:**
Here it is not blocking user from adding the invalid URL. Though it is an invalid URL but it still allows user to enter it.

![image](https://github.com/gildas-lormeau/SingleFile/assets/54856733/237c84d1-1ee4-4f4b-9b20-3a27478d9034)

**Expected behavior**
Behavour should be consistent in both the cases i.e "Add URL" and "Add URLs.."
If "Add URL" is not allowing any particular URL to be added then "Add URLs.." should also not allow that URL to be added.

**Environment**
 - OS: [e.g. Win10 Pro]
 - Browser: [e.g. Chrome, Firefox]
 - Version: [e.g. 64]

**Comment by gildas-lormeau** [comment]
Thank you, I changed the input type from `text` to [`url`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url). This will prevent the user from adding invalid URLs.
