### ISSUE TITLE
Warning message is missing when tried to add invalid URL

### ISSUE THREAD

**Issue by GaneshDabhade** [gildas-lormeau/SingleFile#1346]
**Describe the bug**
In the Batch Save URLs section, when a user enters any invalid URL and clicks on the "Add URL" button we don't add that particular URL however error/warning message is missing. So that the user will also get to know why the URL he is trying to enter is not added.

**To Reproduce**
1. Go to the Batch Save URLs section.
2. In the text box enter any invalid URL (any random string e.g "abcxyz").
3. Click on the "Add URL" button

**Bug:**
Here we are not adding the invalid URL but at the same time, we are not even showing an error/warning message.

**Expected behavior**
I think we should display some sort of informative error/warning message to the user about an invalid URL.

**Comment by gildas-lormeau** [comment]
Thank you, the patch corresponding to #1345 also fixes this bug.
