### ISSUE TITLE
Installed this add-on in Mozilla Firefox but no icon appeared

### ISSUE THREAD

**Issue by bakereliz** [gildas-lormeau/SingleFile#1354]
I am using latest versions of Windows and Firefox. Installed the add-on in Firefox but there is no icon in the toolbar extension area. Where is the icon? How am I supposed to use this?

Thanks.

**Comment by bakereliz** [comment]
Never mind. Figured out how to add it to toolbar.

**Comment by gildas-lormeau** [comment]
For the record, here is the link to the doc: https://support.mozilla.org/kb/extensions-button

**Comment by bakereliz** [comment]
Happy New Year!
Thank you so much for the link! I was able to figure out how to pin the extension to my toolbar and have used it already(!), but  I bookmarked your link for future reference. 
I do have a quick (hopefully) question, though. If a page includes links to other pages, do I have to follow the links and download those pages individually or is there a setting in SingleFile for a quick way to get them at the same time?
Thanks,Elizabeth


I don't know what the heck I'm doing, but I'm sure having a grand time doing it! 

    On Thursday, December 28, 2023 at 03:55:10 AM PST, Gildas ***@***.***> wrote:  
 
 


For the record, here is the link to the doc: https://support.mozilla.org/kb/extensions-button

**Comment by gildas-lormeau** [comment]
Hi Elizabeth,

Thank you, I wish you an happy new year's eve as well :)

> If a page includes links to other pages, do I have to follow the links and download those pages individually or is there a setting in SingleFile for a quick way to get them at the same time?

You can select the text (Ctrl-A or ⌘-A on macOS) on the page, right-click  and select "SingleFile > Save selected links". A page containing all the link URLs is displayed. Click on the "Save pages" button at the bottom of the page and SingleFile should save the linked pages.
