### ISSUE TITLE
Halting development of SingleFile?

### ISSUE THREAD

**Issue by gildas-lormeau** [gildas-lormeau/SingleFile#136]
I'm posting this message for people who follow the project. The [last review](https://addons.mozilla.org/en-US/firefox/addon/single-file/reviews/1270447/) from a guy named "Vlijmen Fileer" (@VlijmenFileer ?) on the AMO page almost convinced me I was losing my time with this extension.  I may also unpublish it from the stores. I'm simply fed up with this kind of disrespectful behavior.

**Comment by barrer** [comment]
> I'm posting this message for people who follow the project. The [last review](https://addons.mozilla.org/en-US/firefox/addon/single-file/reviews/1270447/) from a guy named "Vlijmen Fileer" (@VlijmenFileer ?) on the AMO page almost convinced me I was losing my time with this extension. I may also unpublish it from the stores. I'm simply fed up with this kind of disrespectful behavior.

When I open source project, I will ask: How do I use this program? Then develop the corresponding function. I will receive very good ideas from the user reviews, and ignore the opinions that I don't agree with. You can't guarantee that everyone likes you, but you can help those who like you.

SingleFile has 47,642 users in the Google Chrome app store, and you have helped 47,642 users, many of which may not be programmers. Thank you for your selfless dedication, thank you!

**Comment by barrer** [comment]
When time is not allowed, I think the best way is to keep the core function normal (keeping the html rendering very close to the original), other functions to see your schedule, family life is the first.

**Comment by gildas-lormeau** [comment]
@barrer Thank you very much for your advices and your encouragements. I hope to keep the motivation to offer a useful application to a majority of users. It has always been the driving force behind the development of SingleFile and, at the time, this user feedback was particularly demotivating. Anyway, I'm closing this issue as "WONTFIX: impossible to fix" and I'll try to deal with these kind things. Again, thank you too!

**Comment by thenewvu** [comment]
Thank you, @gildas-lormeau. Just want to say it out.

**Comment by thenewvu** [comment]
I think, as @barrer mentioned, you should better to focus only on what you need and what you love, you don't have to take all feedbacks, just give a chance for constribution, when there's enough needed, someone should step out and do it for himself/herself, I believe that is open-source was supposed to be.

**Comment by gildas-lormeau** [comment]
@thenewvu Thanks for the kind words and for your advice :)
