### ISSUE TITLE
Hey bro I want to contribute
What should I do?

### ISSUE THREAD

**Issue by NotJuba** [gildas-lormeau/SingleFile#1360]

**Comment by gildas-lormeau** [comment]
I don't expect contributions related to the style of the code as this is very subjective and not my priority today. Therefore, contributions are welcome if they are bug fixes or additional features. In this case, it's preferable that you let me know beforehand to avoid the surprise effect.

**Comment by NotJuba** [comment]
Hey please let me know which issue I can work on bro
