### ISSUE TITLE
Add Filename Template variables for action of save page / save selection

### ISSUE THREAD

**Issue by coldwinds** [gildas-lormeau/SingleFile#1365]
**Is your feature request related to a problem? Please describe.**
To distinguish between page and selection content, 
I would like to have two folder to store html files, 
one for result of save page, 
and one for result of save selection

**Describe the solution you'd like**
It would be nice to have certain {save_action} like Template variables with value of "page" and "selection".
So we can configure filename to let saved pages go to page folder, and saved selections go to selection folder

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. I added the support of the variable `{save-action}`. It will be available in the next version.
