### ISSUE TITLE
Let me disable this Keyboard Shortcut: Control + Shift + Y

### ISSUE THREAD

**Issue by xmatic** [gildas-lormeau/SingleFile#1367]
**Is your feature request related to a problem? Please describe.**
I like the extension, it does what it needs to do, and it does it well.

However, it seems to have a Keyboard Shortcut: Control + Shift + Y.

I'm using it as a Chrome Extension on Chrome Browser on Windows.

Is there any way to disassociate this Keyboard Shortcut? I often reach for Control + Shift + T (to reopen the last Chrome tab), and inadvertently press "Y" instead of "T" and waste 5 seconds of my life.

**Describe the solution you'd like**
Please include a checkbox that lets me disable this Keyboard Shortcut: Control + Shift + Y.

**Comment by gildas-lormeau** [comment]
You can change shortcuts here: chrome://extensions/shortcuts

**Comment by xmatic** [comment]
That worked. Fantastic tip. Thank you!
