### ISSUE TITLE
SinglePage failed to save pages from two distinct websites with message “too much recursion” and huge RAM usage

### ISSUE THREAD

**Issue by abolibibelot1980** [gildas-lormeau/SingleFile#1368]
**Describe the bug**
Starting today (I hadn't used Firefox much over the past few weeks), SinglePage failed to save pages from two distinct websites, with the same error message:
`SingleFile error: InternalError: too much recursion`
It happened on those two pages:
https://beincrypto.com/learn/eco-friendly-cryptocurrencies/
https://www.reddit.com/r/Monero/comments/m8sen0/is_monero_concerned_about_environmental_impact/
It happened even though all three steps were seemingly completed (in front of each step was a green thingy normally meaning that is was completed with success). The amount of RAM used increased tremendously during the page saving attempt, and that increase was only partially released after I closed the error warning and reloaded the page (difficult to measure properly as Firefox uses a whopping 16 processes at a time, but the global RAM usage went from about 12GB to about 13.5GB then went down to about 13GB, then after I shut down Firefox it went down to about 8GB). I restarted Firefox (from a profile which, it has to be noted, has 12 windows and several dozens tabs in some of them), it behaved exactly the same.
I could successfully save other pages from other websites with SingleFile during the same session under the same conditions. Those two pages do not seem overly large or complex. Save Page WE successefully saved both pages (with only a warning saying that a resource could not be saved, which happens nearly always with that extension), and didn't seem to cause a RAM usage spike.

**Environment**
 - OS: Windows 7
 - Browser: Firefox 115.6.0esr

**Comment by gildas-lormeau** [comment]
Unfortunately, I cannot reproduce this issue. I did the tests with Firefox ESR on macOS. I suspect you've installed another extension that injects content into the page. This might explain why I can't reproduce the issue.

**Comment by Davidebyzero** [comment]
I've been having trouble with this too. Some pages it happens with for me:
https://www.kusc.org/playlist - This playlist format just recently changed. I used to be able to save it just fine with SingleFile, and now I can't.
https://www.speedrun.com/kwirk/guides/vahlm - A seemingly simple page, but it exhibits this problem as well.

I tried disabling all of my extensions except for SingleFile and it still happened.

OP's [beincrypto.com](https://beincrypto.com/learn/eco-friendly-cryptocurrencies/) link also exhibits the issue for me, but I cannot reproduce it with the problem with their [reddit link](https://www.reddit.com/r/Monero/comments/m8sen0/is_monero_concerned_about_environmental_impact/), which saves fine for me with SingleFile.

**Comment by gildas-lormeau** [comment]
@abolibibelot1980, @Davidebyzero, @noto10
Did you enable `Stylesheets > compress CSS content` option in SingleFile?

**Comment by gildas-lormeau** [comment]
I was able to reproduce and fix this issue when `Stylesheets > compress CSS content` is enabled. The fix will be available in the next version.

**Comment by Davidebyzero** [comment]
> I was able to reproduce and fix this issue when `Stylesheets > compress CSS content` is enabled. The fix will be available in the next version. Meanwhile, you can disable the option if this is the cause of your issue.

Wow, thank you very much! Now all of the pages that I couldn't save before, I can, using that workaround for now.
