### ISSUE TITLE
Does not save certain images on some pages? WEBPs?

### ISSUE THREAD

**Issue by orionanomaly** [gildas-lormeau/SingleFile#1371]
1. Thank you SO MUCH for building this Gildas I have followed your work for years.  I archive and work with a lot of web-related pages and it seems no one builds anything useful in this space except you!

2. I have noticed this page below does NOT save the images.  I do not know why. (I have to check others I often save a page and never check the output so this is concerning).

I was wondering if it is because they are WEBP but not sure if that would be an issue.  

https://corporatefinanceinstitute.com/resources/fixed-income/yield-curve/

The page saves correctly, but the images (the graphs) are missing.

3.  Unrelated, but using an HTML to PDF add-on I am able to save the images.  

*I tried this on Chrome AND Firefox and get the same behavior for that page above.

**Comment by Super-cz** [comment]
在保存ChatGPT4.0对话页面时我也遇到了相同问题，当在交流过程中输入图片给GPT或者让它输出一些图片，页面保存正常但图像或图表丢失

**Comment by gildas-lormeau** [comment]
Actually, the images are present in the saved page but hidden via CSS. You can circumvent this issue by enabling the option `Images > remove images for alternative screen resolutions` or by running the script below in the Dev Tools (F12) before saving the page.

```js
document.querySelectorAll("img").forEach(element => element.removeAttribute("srcset"))
```
