### ISSUE TITLE
Duplicate style element is added when re-saving existing snapshot

### ISSUE THREAD

**Issue by correctmost** [gildas-lormeau/SingleFile#1377]
**Describe the bug**
SingleFile's internal `.single-file-*` CSS rules get duplicated each time a snapshot is reopened and saved.

**To Reproduce**
1. Start with a new Firefox profile
2. Install SingleFile
3. In the extension options, check the `Annotation editor` > `open pages saved with SingleFile in the annotation editor` box
4. Go to https://www.google.com/robots.txt
5. Right-click and choose `SingleFile` > `Annotate and save the page...`
6. In the annotation editor, click the Save button to save a snapshot
7. In a new tab, open the saved snapshot to enter the annotation editor once again
8. Click the Save button to save a second snapshot
--> Notice the snapshot has increased in size by ~2KB
--> The difference is a duplicated style element with SingleFile's CSS rules

**Expected behavior**
Is it possible to avoid the duplicated styles to make it easier to diff snapshots? Thanks!

**Environment**
 - OS: Arch Linux
 - Browser: Firefox 122.0
 - SingleFile 1.22.40

**Comment by gildas-lormeau** [comment]
Thank you for the detailed report. I reproduced and fixed the issue. The fix will be available in the next version.
