### ISSUE TITLE
Batch URL Save with Mighty Networks websites: Can't get pages to fully render despite `processInForeground` and other options enabled

### ISSUE THREAD

**Issue by lowercaseprosocial** [gildas-lormeau/SingleFile#1378]
For questions, please create or update a thread here: 
https://github.com/gildas-lormeau/SingleFile/discussions

Please ensure that you do not find an answer before reporting the issue:
- [X] in the FAQ: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md
- [X] in the list of known issues: https://github.com/gildas-lormeau/SingleFile#known-issues
- [X] in the help page embedded in the extension

**Describe the bug**
I'm trying to save a number of pages of a website run on 'Mighty Networks', along with a script to unhide extra elements. I can get pages to save fine if I load a tab manually and then run SingleFile, but if I try to use the 'Batch save URLs' option to save a page . 

What I've tried:
- Testing on both Chrome and Firefox.
- Enabling `processInForeground`, as suggested in https://github.com/gildas-lormeau/SingleFile/issues/1218
- Enabling other options like 'dispatch scroll event', 'zoom out the page', etc. . In case it helps I've exported sample settings to https://gist.github.com/lowercaseprosocial/93a66c1293021670575e62180cac7009  
- Not using my userscript - this doesn't seem related to the issue and am not including the script for now. I will note that the script I use is rather slow (makes use of async timeouts and such) and when running batch save URLs the premature saving happens before the userscript has a chance to run. My script does seem to run fine WITHOUT Batch saving though, even in cases where it takes several minutes to run before invoking an event to continue with SingleFile, per the instructions in https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved

**To Reproduce**
1. Try using my settings mentioned above.
2. Go to singlefile's Batch save URLs, try adding the following urls to test.
```
https://community.mightynetworks.com/posts/host-a-magical-livestream-48599150
https://community.mightynetworks.com/events/host-a-magical-livestream?instance_index=20240111T170000Z
https://community.mightynetworks.com/posts/from-great-to-magical-newsletters-have-come-to-mighty
```
3. Try running the batch save.
4. Observe that you may have either have most of the URLs save such that there's no actual content in the saved file and are only around 289kb in size, rendering just a header bar. Compare to running singlefile on a url (not in batch) that has been opened, which usually saves into a larger file with more of the actual contents. 

**Expected behavior**
Batch URL save should output the same as individual save.

**Screenshots**
The left side shows what the saved result with batch URLs ends up looking like. The right side is the expected result.
![image](https://github.com/gildas-lormeau/SingleFile/assets/93850858/5a90a0fb-91eb-4c51-95cb-58c3de55f0ea)

**Environment**
 - OS:Fedora 39
 - Browser: Chrome or Firefox 
  - Version:  Chrome 121.0.6167.85, Firefox 122, SingleFile 1.22.40

**Additional context**

**Comment by gildas-lormeau** [comment]
I confirm I was able to reproduce the issue. In fact, detecting the complete loading of a page is not a trivial matter. For this reason, I've just added a hidden option called `delayBeforeProcessing` (associated with a profile) which allows you to set a number of seconds before processing the page. This option will be available in the next version.

**Comment by gildas-lormeau** [comment]
Note that the userscript below should also work

```js

dispatchEvent(new CustomEvent("single-file-user-script-init"));

addEventListener("single-file-on-before-capture-request", async event => {
    event.preventDefault();
    debugger;
    try {
        await new Promise(resolve => setTimeout(resolve, 5000));
    } finally {
        dispatchEvent(new CustomEvent("single-file-on-before-capture-response"));
    }
});
```
