### ISSUE TITLE
options don't work

### ISSUE THREAD

**Issue by M4pbGH** [gildas-lormeau/SingleFile#138]
**Describe the bug**
1. profile '+' does not open a dialog to specify a name for another profile
2. clicking Export and Import buttons shows no reaction
3. changing checkboxes or filename template show changes made but there is no SAVE button, and closing the options dialog box resets changes to default
==> no configuration changes possible

**To Reproduce**
1. open Singlefile Options
2. Click '+' to add a new profile, or Export, or Import
3. nothing happens
4. No error issued

**Expected behavior**
Options should work as described.

**Screenshots**

**Environment**
 - OS: Win10 Enterprise, 64-bit, latest version, all updates
 - Browser: Vivaldi (Chrome engine from current Google Chrome browser)
 - Version: 2.2.1388.37 (Stable channel) (64-Bit)

**Additional context**
For Vivaldi I installed Singlefile from Chrome Webstore.
For Firefox I installed Singlefile from Mozille AddOns portal. Here Singlefile settings changes work as expected.
==> issue with Chromium?

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. It is weird, especially the fact that saving does not work. Currently, I am not able to reproduce this issue. On my end, popups work as expected. Here is my environment:
- OS: Win10 Pro, 64-bit, latest version, all updates
- Browser: Vivaldi version: 2.2.1388.37

Here is a screenshot (in french) showing the popup.

![screenshot](https://user-images.githubusercontent.com/396787/51684247-eb7b1b00-1feb-11e9-9b38-96f812fcb689.png)

To help me identifying the cause of your issue, could you please install the extension from the Chrome store, open `chrome-extension://mpiodijhokgodhhofbcjdecpffjipkle/extension/ui/pages/options.html` in a tab, then press F12 to open the developer console, and do any change in the options. Do you see any message in the developer console? Are your changes saved if you press F5 ore refresh the tab?

**Comment by wizzard0** [comment]
I can confirm this, sometimes options dialog is not even shown (using Chromium). To @M4pbGH - it helps to restart the browser, ahem, 2 times :)

**Comment by gildas-lormeau** [comment]
That's really weird... Out of curiosity, do you change the user-agent of your browser?

**Comment by gildas-lormeau** [comment]
I added next to the title of the options page an icon allowing you to open the options page in a separated tab. Are you able to reproduce this issue when the options page is displayed in a tab?
