### ISSUE TITLE
can not save google api page

### ISSUE THREAD

**Issue by nt475vd** [gildas-lormeau/SingleFile#1382]
在这样的网页不能保存页面
https://developers.google.com/apps-script/reference/drive
报告错误：
SingleFile 錯誤: InternalError: too much recursion

**Comment by gildas-lormeau** [comment]
translation:
You can't save a page at a page like this
https://developers.google.com/apps-script/reference/drive
Report an error:
SingleFile error: InternalError: too much recursion

---
I cannot reproduce this bug with the default settings in Chrome or Firefox.

我无法使用 Chrome 浏览器或火狐浏览器的默认设置重现这个错误。

**Comment by gildas-lormeau** [comment]
Did you change any settings?

----

您是否更改了任何设置？

**Comment by gildas-lormeau** [comment]
Feel free to comment if you have more info about the issue.
