### ISSUE TITLE
Reddit pages are 60 MB - 90 MB

### ISSUE THREAD

**Issue by gitressa** [gildas-lormeau/SingleFile#1387]
**Describe the bug**
Thanks for a great add-on, it's really nice to have.

**To Reproduce**
1. Go to a Reddit page
1. Save the page
1. See that it is 50-90 MB

**Expected behavior**
I would expect it to be 2-3 MB.

**Environment**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 1.22.40

**Comment by gildas-lormeau** [comment]
Unfortunately, for some reasons I cannot explain, the developers decided to inline and duplicate all the stylesheets in the new version of Reddit and it inevitably leads to this kind of result. For example, https://www.reddit.com/r/webdev/ contains more than 600 stylesheets. For the moment I don't see how I can get around this problem, apart from saving pages while logged in on Reddit.

**Comment by gitressa** [comment]
Thanks for a fast answer. It also happens when you are logged in.

**Comment by iG8R** [comment]
Same issue here... it is incomprehensible how 1 page can be ~90MB...

**Comment by gildas-lormeau** [comment]
This issue is fixed in the last version of SingleFile. I attached a ZIP file containing the recommended settings for Reddit which you can import via the options page in SingleFile.

[singlefile-settings-reddit.json.zip](https://github.com/user-attachments/files/16936929/singlefile-settings-reddit.json.zip)

**Comment by gitressa** [comment]
Thanks! I don't see the `Stylesheets > group duplicate stylesheets together` option, but Reddit pages are now only ~1 MB, so something has been updated, and the issue has been fixed.

**Comment by iG8R** [comment]
@gildas-lormeau 
Could you please also publish the Firefox addon on the releases page when a new one is released, because https://addons.mozilla.org/en-US/firefox/addon/single-file/ is not updated in a timely manner.

**Comment by gildas-lormeau** [comment]
The publish is in progress. Mozilla takes usually approx. 1 week to review the code.

**Comment by iG8R** [comment]
That's why I asked you to publish the addon on the release page, because you don't have to wait for Mozilla to review the code.

**Comment by gildas-lormeau** [comment]
Sorry for the misunderstanding, it looks like I was a bit tired. Actually, I cannot get an xpi file until Mozilla has reviewed the code. You can install the extension manually though. See here: https://github.com/gildas-lormeau/SingleFile?tab=readme-ov-file#install

**Comment by iG8R** [comment]
Thanks a lot for the suggestion, too bad you can't get the xpi file. I used to do what you suggested, but it's so inconvenient that I have to reinstall the addon after every restart of Firefox.

**Comment by gildas-lormeau** [comment]
Regarding the persistence of the extension, maybe one of these suggestions would work, I did not test them:
- https://stackoverflow.com/questions/64702424/how-to-persist-the-firefox-temporay-addon-on-browser-restart
- https://stackoverflow.com/questions/47363481/install-a-personal-firefox-web-extension-permanently

**Comment by gildas-lormeau** [comment]
The new version has been published.

**Comment by iG8R** [comment]
Thank you very much!

**Comment by gitressa** [comment]
Just adding a tip that `Stylesheets > group duplicate stylesheets together` seems to have been disabled, and Reddit pages were again big. (Or maybe I reinstalled the add-on?) Anyway, after enabling, they are again small. Thanks!

**Comment by gildas-lormeau** [comment]
@gitressa That's stange, this should not happen. Is the "sync" option enabled in your settings?

**Comment by gitressa** [comment]
No, "synchronize options" is not enabled ... but it says "Check this option to synchronize your options and make them available in all instances of the browser you are logged into, on different devices." and I am only on a single device ...

Or does it do more than that text describes?

**Comment by gildas-lormeau** [comment]
As far as I know, this is the only case in which the settings could be reset. It's still pretty strange... Please do not hesitate to contact me if you find that the option `Stylesheets > group duplicate stylesheets together` deactivates itself again.

**Comment by gitressa** [comment]
Thanks, I'll keep an eye on it. Thanks for a great add-on!
