### ISSUE TITLE
keep the infobar content in html head with zip file format

### ISSUE THREAD

**Issue by leeyaunlong** [gildas-lormeau/SingleFile#1390]
I use some three party tool to index singlefile files and extract the meta info ( saved with infobar ).
When I use the zip file format html to save the file size , the zip format html removed the infobar text content from html first lines.
So the those tool cannot extract the meta info or index meta.
Can you still keep the infobar info in html head lines as html format version?

**Comment by gildas-lormeau** [comment]
I agree that would be useful, I'll try to add the HTML comment in the saved page when using th self-extracting format.
