### ISSUE TITLE
Anchor/Pin Note Cards

### ISSUE THREAD

**Issue by Matthew-Mind** [gildas-lormeau/SingleFile#1399]
When I annotate a page with notes, then save and close the page, upon reopening the page file the note cards are not where I put them.  They are nearby, often covering something I want to be visible, and it may not be clear what on the page they are referring to.

I noticed the anchor icon on note cards, but could not identify any effect from clicking it.

Is there any way to anchor/pin a note card in place, or anchor it to an element on the page without covering the element?
Is there any way to indicate what on the page a note is referring to?

**Comment by gildas-lormeau** [comment]
I cannot reproduce the issue. I saved a page on example.com and added a note exactly on top of the "E" and it works as expected. The note is at the same position when I open the saved page. See the attached file. Moving the note allows you to know to which element it is anchored.

By default, notes are attached to elements. If you click on the anchor button, the position of the note will be relative to the document.

[example.zip](https://github.com/gildas-lormeau/SingleFile/files/14605660/example.zip)

**Comment by Matthew-Mind** [comment]
Apologies. The only failure is my failure to understand. That is resolved.

**Comment by gildas-lormeau** [comment]
No problem, thank you for the feedback.
