### ISSUE TITLE
save referrer and day/url+hash/tab id in JSON in the document

### ISSUE THREAD

**Issue by wizzard0** [gildas-lormeau/SingleFile#140]
**Is your feature request related to a problem? Please describe.**
I have terrible memory and often using SingleFile to find out *how* did I found about a particular article or topic. Auto-save + full-text search does wonders, and I'd like to take it one step further by tracking how exactly which tab was opened. 

**Describe the solution you'd like**
The simplest way seems to just save document.referrer and tab ID, similar to how URL/hash/date is currently saved. And, for easier access from code, also write date in UTC, and embed this as a JSON somewhere :)

**Describe alternatives you've considered (optional)**
I already save tab id as part of a filename, but it's less convenient.

Also, I was pleasantly surprised that SingleFile can auto-create subfolders (i.e. history/day/time-host-tab)

Again, *awesome* extension. Many thanks!

**Comment by gildas-lormeau** [comment]
Thanks for the suggestion @wizzard0. Actually, there are 2 suggestions in your post:
- adding the referrer
- serialize this info in JSON "somewhere"
It would be great if you could split your request into 2 separated posts.

Regarding the first point. As you may know, the infobar content can be customized thanks to templates. Today, I think this issue could be fixed just by adding a new template variable. Would it be sufficient for you?

**Comment by gildas-lormeau** [comment]
Did you enable "Allow access to file URLs" here chrome://extensions/?id=mpiodijhokgodhhofbcjdecpffjipkle?

**Comment by wizzard0** [comment]
Oh, now I see. I thought the infobar was embedded in the saved HTML. Also, when opening the saved tab with autosave it's re-saved again. Not a problem, but weird :)

**Comment by wizzard0** [comment]
The dialog is not shown, though (1.9.44)

**Comment by gildas-lormeau** [comment]
@wizzard0 So... If you set the for the infobar template option to `referrer: {url-referrer}`, does it fix your issue? You'll find this info in the first comment of the page (in the source code) or in the infobar when displaying the saved page into a browser with SingleFile installed. It's not JSON though.

**Comment by gildas-lormeau** [comment]
@wizzard0 I'm closing this issue. From my point of view, it's fixed. Feel free to re-open it if you think it's not.
