### ISSUE TITLE
Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by HippyCraig** [gildas-lormeau/SingleFile#1408]
Sometime when I try to use SingleFile as soon as the file downloads Windows Security blocks it and I get an error 

Trojan:Script/Wacatac.B!ml

now other pages on the same site dont do that but some started to reciently.  There HTML files so I dont know why its getting picked up that way, I thought that virus was only related to EXE. and other excutable file types.

**Comment by HippyCraig** [comment]
sometimes when I go back to it and try again it works half the time.   I checked my settings and it looks to be on by default

If I disable teh first one will it ignore the second hightlighted option?  Will that effect how its rendered?

![image](https://github.com/gildas-lormeau/SingleFile/assets/17074456/54633279-a418-4aed-8d8c-24eaefc82007)

**Comment by HippyCraig** [comment]
I may have read that wrong, is the box being checked mean it skips scripts?   
Isnt checked by default isnt it?   If so then and my comment just above is true then I havent changed it so it must be blocking them and I still get that warning from time to time

**Comment by gildas-lormeau** [comment]
The checkbox is checked by default, i.e. scripts are blocked. 

I don't use Windows very often and I've never seen this issue in the past. The best way to help me would be to give me an example of URL illustrating the problem.

**Comment by HippyCraig** [comment]
We can probably close this as I havent seen it but one or times after I posted it, its been good since.

**Comment by gildas-lormeau** [comment]
That's fine for me, it's most likely a false alarm anyway. I've never heard that pages saved with SingleFile could pose a security problem.

**Comment by HippyCraig** [comment]
Thanks for take the time to look I appreciate it
