### ISSUE TITLE
Referrer variable in templates

### ISSUE THREAD

**Issue by wizzard0** [gildas-lormeau/SingleFile#141]
**Is your feature request related to a problem? Please describe.**
As described in #140, to track how did I arrived on a particular page, when saving history

**Describe the solution you'd like**
Add a variable {url-referrer} accessible from templates like the current {url-href}

**Comment by gildas-lormeau** [comment]
You should be able to use this variable in the version 1.9.42.

**Comment by wizzard0** [comment]
Works, great! Doesn't work with websites blocking referrer, though, could be improved if extension could catch the event where I start navigation (or just use the last active tab URL) when the referrer is not available, but it's more of a cherry on the cake :)
