### ISSUE TITLE
add an option to exclude fonts when saving page

### ISSUE THREAD

**Issue by armstrongli** [gildas-lormeau/SingleFile#1411]
**Is your feature request related to a problem? Please describe.**
the saved file size is over 2.5MB when saving a tekton logs of a taskrun in tekton pipeline. the fonts takes over 90% of content in the saved file.

**Describe the solution you'd like**
add an option to exclude all fonts from the saved file.

**Describe alternatives you've considered (optional)**
add an context menu bar on the right click with `Save page with SingleFile(exclude fonts)`.

**Additional context (optional)**
![image](https://github.com/gildas-lormeau/SingleFile/assets/8025018/4a8b2617-dbdd-416b-b7fb-b29dfb5f89d3)

**Comment by armstrongli** [comment]
maybe releated to this issue: https://github.com/gildas-lormeau/SingleFile/issues/1088

**Comment by gildas-lormeau** [comment]
The option already exists, see `Network > blocked resources > fonts`. You can also create a profile in the options page in order to add en entry in the context menu.
