### ISSUE TITLE
Cannot safe HTML file

### ISSUE THREAD

**Issue by direlle** [gildas-lormeau/SingleFile#1413]
**To Reproduce**
1. Go to 'https://skillnet.countywexfordchamber.ie/'
2. Click on 'SinfleFile icon' to safe the HTML file
3. See error 'SingleFile error: TypeError: URL constructor: https://skillnet. wexfordchamber.ie/wp content/uploads/2018/03/chamber.png is not a valid URL.'

**Environment**
 - OS: [Windows 10]
 - Browser: [Firefox 121]
 - Version: SingleFile 1.22.43

**Comment by gildas-lormeau** [comment]
Thank you for the report. I can confirm I was able to reproduce and fix the issue. The fix will be available in the next version.
