### ISSUE TITLE
Unix error 36 during operation remove on file ….html.part (File name too long)

### ISSUE THREAD

**Issue by fox0** [gildas-lormeau/SingleFile#142]
**Describe the bug**
Add-on creates files with long names that the browser cannot save to disk.

**To Reproduce**
1. Go to 'http://old.reactor.cc/post/3802575'
2. Click on 'save page'
3. See error 'download fail'

**Expected behavior**
Page has been saved to file.

**Screenshots**
![download list](https://user-images.githubusercontent.com/15684995/51798365-5a05e600-2243-11e9-91fa-ce4b282b0dcd.png)

**Environment**
 - OS:Ubuntu 18.04.1
 - Browser: Firefox
 - Version: 64.0

**Comment by fox0** [comment]
Template filename: {page-title} ({date-iso} {time-locale}).html

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. I was able to reproduce it, and I just deployed the version 1.9.44 which should fix it.

**Comment by fox0** [comment]
All is ok. Thank you very much!

**Comment by gildas-lormeau** [comment]
You're welcome :)
