### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Explosion-Scratch** [gildas-lormeau/SingleFile#1421]
There have been 540 commits since the last version was released back in November 2022

**Comment by gildas-lormeau** [comment]
You mean a tagged version on Docker Hub?

**Comment by gildas-lormeau** [comment]
I've released a new version, see https://github.com/gildas-lormeau/SingleFile/releases/tag/v2.0.17

To tell the truth, I don't know why this matters, as the CLI tool is separate and the extension is updated on the stores regularly. However, I think that the current state of the code (which works well) deserves a new release :)

**Comment by Explosion-Scratch** [comment]
Oh, I didn't know that the extension was updated independently from releases lol

**Comment by gildas-lormeau** [comment]
No problem ;)
