### ISSUE TITLE
Saving as zip results in broken document (numbers [0-255] separated by commas)

### ISSUE THREAD

**Issue by gunchev** [gildas-lormeau/SingleFile#1422]
**Describe the bug**
Saving self extracting zip (universal or not) file from FireFox and Chromium results in something that displays a comma separated list of numbers from 0 to 255 (so most likely byte values).
In addition the "zip" file is larger than the HTML variant. I suspect these should be the byte values, not text, but didn't test that theory.

**To Reproduce**
- Save any page ( google, wikipedia, https://www.archimetric.com/what-is-deployment-diagram/ ).
- Open the saved file.

**Expected behavior**
Readable copy of the web page.

**Screenshots**

**Environment**
 - OS: Fedora 39
 - Browser: Chromium, Firefox
 - Version: 1.22.45
- Configuration: [singlefile-settings-2024-04-01T15_16_08.842Z.json](https://github.com/gildas-lormeau/SingleFile/files/14825092/singlefile-settings-2024-04-01T15_16_08.842Z.json)

**Comment by gildas-lormeau** [comment]
Thank you, I confirm I was able to reproduce and fix the bug. The fix will be available in the next version.
