### ISSUE TITLE
Save to include videos/gifs

### ISSUE THREAD

**Issue by megamorphg** [gildas-lormeau/SingleFile#1423]
**Is your feature request related to a problem? Please describe.**
I would like to save a [page](https://www.bachatasteps.com/?options=level) that contains many dance clips in gif format.
When saving the page it does not include all the images or any videos. At best, there are just some static images.
I've enabled all options under Images section including setting the maximum idle time to 10s.

**Describe the solution you'd like**
Way to pre-load all the videos that are visible and save as a single file.

**Describe alternatives you've considered (optional)**
I'm open to any other alternatives! Would just like to be able to access the site offline.

**Comment by gildas-lormeau** [comment]
You're welcome! Run the code instead to autoplay all the videos. Note that you can convert it as a [bookmarklet](https://en.wikipedia.org/wiki/Bookmarklet) for more convenience.

```js
document.querySelectorAll(".video-overlay").forEach(overlayElement => overlayElement.remove()); document.querySelectorAll("video").forEach(videoElement => videoElement.autoplay = true);
```
