### ISSUE TITLE
File name issue (V 1.22.46 for Google Chrome )

### ISSUE THREAD

**Issue by keltt929** [gildas-lormeau/SingleFile#1431]
**Describe the bug**
After updading to 1.22.46 (Chrome), the file name become very strange in every web page I visited.
For example: 65c6494a-eae1-4108-9982-d6a026ee0fb9.htm

It works well in 1.22.45 (Firefox).

**To Reproduce**
1. Go to "https://edition.cnn.com/"
2. Perfoming SingleFile to save page. The file name is "de85571b-8607-4ab6-95c3-7a646c42730c.htm".  
3. Press CTRL+S to save page. The file name is "Breaking News, Latest News and Videos _ CNN.html".

**Expected behavior**
When I using SingleFile to save web page, the default file name should be same as or similar as the file name I save the page by using CTRL+S. But I always get a file name with strange numbers and letters.  

**Screenshots**
![SingleFile_Issue (Pic 1)](https://github.com/gildas-lormeau/SingleFile/assets/92744099/d46d7cac-9b2d-4ea3-ab87-b2cfe206c658)

![SingleFile_Issue (Pic 2)](https://github.com/gildas-lormeau/SingleFile/assets/92744099/94234d1a-a55f-4bbf-aba2-1ad1e4f6107d)

**Environment**
 - OS: Win10 Pro (22H2)
 - Browser: Chrome
 - Version: 1.22.64

**Comment by gildas-lormeau** [comment]
This is a bug in Chrome, see the second issue for Chromium-based browsers here: https://github.com/gildas-lormeau/SingleFile?tab=readme-ov-file#known-issues
