### ISSUE TITLE
Manifest v3 support

### ISSUE THREAD

**Issue by grematt** [gildas-lormeau/SingleFile#1434]
What is the timeline for migration to manifest v3? Are there plans to migrate?

**Comment by gildas-lormeau** [comment]
For the record, the repository for SingleFile MV3 can be found here: https://github.com/gildas-lormeau/SingleFile-MV3. I will publish it on the stores of Edge and Chrome when I will have no other choice. This should happen in June 2024, see https://developer.chrome.com/blog/resuming-the-transition-to-mv3.
