### ISSUE TITLE
Add option to remove menu entry in tab bar

### ISSUE THREAD

**Issue by fiso64** [gildas-lormeau/SingleFile#1444]
**Is your feature request related to a problem? Please describe.**
With the extension enabled, when I right click any tab in the tab bar, there is a menu entry for SingleFile. I would like to have an option to remove this entry. The option `add entry in the context menu of the webpage` disables the context menu entry when right clicking anywhere on a page, but not when right clicking a tab.

**Describe the solution you'd like**
An option in the settings `add entry in the context menu of the tab bar` which can be unchecked to disable that.

**Comment by gildas-lormeau** [comment]
The option exists but is hidden because it's specific to Firefox, you have to set `tabMenuEnabled` to `false`. See here for more information on how to change this value: https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options.
