### ISSUE TITLE
SingleFile and SingleFileZ both have problem when saving a webpage tool based on Bootstrap.

### ISSUE THREAD

**Issue by 265785** [gildas-lormeau/SingleFile#1446]
**Describe the bug**
I want to save this webpage tool for offline use. Its format is based on Bootstrap:
https://wxlzmt.github.io/pages/simple/calc.html

Because I want to run the functions in the offline webpage, I unchecked all the blocked resources. However, the calculating function of this page don't work in the saved webpage. 

![0001](https://github.com/gildas-lormeau/SingleFile/assets/56037874/b72ef6d3-48ad-4300-bf9f-426ee87ce9cb)

![0002](https://github.com/gildas-lormeau/SingleFile/assets/56037874/affec06e-6227-42f4-afdb-e8ad07f20674)

Then I unchecked all the checkboxes that have word "remove" and saved the page, Though the function works, the webpage format becomes abnormal.  

![0002](https://github.com/gildas-lormeau/SingleFile/assets/56037874/5616aab4-8bca-4fec-95ba-67ab54d51906)

![0004](https://github.com/gildas-lormeau/SingleFile/assets/56037874/83ffc090-fe0a-41a4-b09d-f0f13ee90d70)

**To Reproduce**
1. Reset SingleFile or SingleFileZ's Settings
2. Go to https://wxlzmt.github.io/pages/simple/calc.html
3. Change SingleFile or SingleFileZ's Settings like "Describe the bug"
4. Save this webpage by SingleFile or SingleFileZ.
5. Open the saved file.
6. See error

**Expected behavior**

To reserve the webpage's original format and functions, only uncheck all the blocked resources is enough. This will do help to many pages based on Bootstrap. Thank you!

**Environment**

 - OS: Win11 Pro
 - Browser: Edge
 - Version:  124.0.2478.67

**Additional context**

1. The webpage's function is simple, Its' only function is to divide two numbers into two coprime integers, and find the value of multiplying the two coprime integers by 1-any number. It can be used offline. 

2. The translation of this page in English is shown below: 

![0005](https://github.com/gildas-lormeau/SingleFile/assets/56037874/65cb39c2-d0bc-4806-96c3-6786deef317f)

3. The webpages are saved in InPrivate mode, No other extension block the saving process.

**Comment by gildas-lormeau** [comment]
Can you please try to enable the option `HTML content > save raw page`?

**Comment by 265785** [comment]
I tried. But he situation become worse. 
![image](https://github.com/gildas-lormeau/SingleFile/assets/56037874/26a43cae-4198-4aa7-9ba5-2354b350a8b6)

**Comment by gildas-lormeau** [comment]
It looks to work for me with `HTML content > save raw page` (and the other options you mentioned) but the page displays two alerts and the form is not filled with the default values. However, it is functional.

**Comment by 265785** [comment]
Your program is really great. I tried several other pages with offline scripts, most of them can be saved correctly with scripts inside, In the case of only unchecking the `Network > block xxx` with the default settings.
I wonder why this page cannot be saved normally, but I feel it is really a good example for you to improve your program. 
> Note: I tried your option again (Though it is relatively troublesome). The saved webpage's script can work, but the initial value is lost.

**Comment by gildas-lormeau** [comment]
Thanks, the problem was that SingleFile was overwriting the values of some fields when “save raw page” was enabled. I've fixed the bug, the fix will be available in the next version.
