### ISSUE TITLE
MAFF to HTML with SingleFile: testers needed

### ISSUE THREAD

**Issue by gildas-lormeau** [gildas-lormeau/SingleFile#145]
SingleFile can now convert MAFF files to HTML from the command line. You can find more info here: https://github.com/gildas-lormeau/SingleFile/tree/master/maff2html.

Your comments/issues are welcome!

**Comment by KrasnayaPloshchad** [comment]
@danny0838

**Comment by gildas-lormeau** [comment]
I'm closing the issue because:
 - it seems it's the wrong canal of communication
 - some tests have already been done and no issues have been reported

Any feedback is welcome though. Feel free to re-open the issue if needed.
