### ISSUE TITLE
Images (full-sized) not fully captured on eBay listing

### ISSUE THREAD

**Issue by deprid** [gildas-lormeau/SingleFile#1454]
When there's multiple images shown in a listing, only the first one is captured in original size. Also, you can't click on the rest of images to zoom/view in full size.

For example:
https://www.ebay.com/itm/144373457498

**Comment by gildas-lormeau** [comment]
Unfortunately,  I confirm it's not possible to save the interactive parts of this page. It's one of the limitation of SingleFile.
