### ISSUE TITLE
Saving with Zip format (including SingleFileZ) fails to save some elements

### ISSUE THREAD

**Issue by onoter** [gildas-lormeau/SingleFile#1459]
**Describe the bug**
Saving a certain webpage as zip format (or save it using SingleFileZ) will not save a png picture on the top. 
However, saving the same page with HTML format will correctly save the png picture. 

**To Reproduce**
1. Save this [page](https://zzfy.hncourt.gov.cn/public/detail.php?id=29159) with default settings (HTML format). 
2. The page is correctly saved.
3. Set `Options -> File format -> format` to `self-extracting ZIP (universal)`
4. Save that page again. And you'll see the picture missing. 

**Screenshots**

1. &nbsp;
![_2024-05-19_220005](https://github.com/gildas-lormeau/SingleFile/assets/125631778/eee21cde-8bf1-4e13-802b-f7e29297d950)

2. **The picture is missing when saved as zip:**
   
   ![missing](https://github.com/gildas-lormeau/SingleFile/assets/125631778/6517c883-86d1-4bc8-81dd-233246ee2b01)

**Comment by gildas-lormeau** [comment]
Thank you for the detailed report. I was able to reproduce and fix the bug. The fix will be available in the next version.
