### ISSUE TITLE
保存网页后，本地html文件无法正常显示网页内容

### ISSUE THREAD

**Issue by reswing** [gildas-lormeau/SingleFile#1467]
For questions, please create or update a thread here: 
https://github.com/gildas-lormeau/SingleFile/discussions

Please ensure that you do not find an answer before reporting the issue:
我按照faq中的设置修改了，也无法正常显示网页内容

**Describe the bug**
1、此网址保存下来后，无法正常显示。地址：https://weibo.com/1684197391
2、我按照下图的建议修改设置后，仍然保存后无法正常显示网页内容
<img width="1046" alt="image" src="https://github.com/gildas-lormeau/SingleFile/assets/69662722/70d0431e-ae9a-4997-a5fb-d763b84023c3">

**To Reproduce**
点击singlefile图标，保存网页即可重现问题

**Expected behavior**
希望保存下来的文件能正常显示原网页内容

**Screenshots**
保存下来的文件如下图效果，无法正常显示
<img width="1492" alt="image" src="https://github.com/gildas-lormeau/SingleFile/assets/69662722/7378d649-0175-4149-b427-288303b995d8">

**Environment**
 - OS:macOS 14.5
 - Browser: Chrome
 - Version:1.22.49

**Comment by gildas-lormeau** [comment]
此问题与 JavaScript 无关。要解决这个问题，请重置 SingleFile 中的设置并启用 `网络 > 跨域请求失败时添加来源地址头信息（Referer）`

---

This issue is not related to JavaScript. To fix it, reset the settings in SingleFile and enable `Network > pass "Referer" header after a cross-origin request error`.

**Comment by reswing** [comment]
> 此问题与 JavaScript 无关。要解决这个问题，请重置 SingleFile 中的设置并启用 `网络 > 跨域请求失败时添加来源地址头信息（Referer）`
> 
> This issue is not related to JavaScript. To fix it, reset the settings in SingleFile and enable `Network > pass "Referer" header after a cross-origin request error`.

确实图片的显示和这个设置有关，但是没有完全解决问题。如果我将页面一直下滑，加载比较久之前的内容然后保存，保存下来的文件，显示内容只有一部分。

**Comment by gildas-lormeau** [comment]
> 确实图片的显示和这个设置有关，但是没有完全解决问题。如果我将页面一直下滑，加载比较久之前的内容然后保存，保存下来的文件，显示内容只有一部分。

尝试启用选项 `图片 > 保存延迟加载的图片 > 缩小页面`。这可能会有所帮助。
