### ISSUE TITLE
I'm bit confused about help page

### ISSUE THREAD

**Issue by directentis1** [gildas-lormeau/SingleFile#1476]
For questions, please create or update a thread here: 
https://github.com/gildas-lormeau/SingleFile/discussions

Please ensure that you do not find an answer before reporting the issue:
 - in the FAQ: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md
 - in the list of known issues: https://github.com/gildas-lormeau/SingleFile#known-issues
 - in the help page embedded in the extension

**Describe the bug**
According to this: https://github.com/gildas-lormeau/SingleFile/blob/29ae30b8c7c6e8c15ebf5938097fc67cccd77ff3/src/ui/pages/help.html#L993

It must be 
`%if-not-equals<value|expected|trueValue|falseValue>`: returns the `trueValue` if value does not equal expected or the `falseValue` otherwise (e.g. "`%if-not-equals<{page-title}|Untitled|{page-title}|{page-heading}>`" to return the _**page title**_ if the page title does not equal "Untitled" or the _**page heading**_ otherwise). 

Similar to:
%if-not-contains<value|expected|trueValue|falseValue>: returns the trueValue if value does not contain expected or the falseValue otherwise (e.g. "%if-not-contains<{page-title}|Untitled|{page-title}|{page-heading}>" to return the _**page title**_ if the page title does not contain "Untitled" or the _**page heading**_ otherwise). 

**To Reproduce**
SingleFile help docs, section 6. #template-functions

**Expected behavior**
As above.

**Screenshots**

**Environment**
Unrelated

**Comment by gildas-lormeau** [comment]
Thank you! I should have reread more closely what Copilot had proposed. This will be fixed in the next version.
