### ISSUE TITLE
Why can't I click this button,i want debug the crx!

### ISSUE THREAD

**Issue by wjsw1781** [gildas-lormeau/SingleFile#1477]
Why can't I click this button I want to debug to see how this plugin fetches html How to replace img with base64 How to get the contents of an iframe but can't debug I want to learn the key logic above

我是中国人 ,我有个问题,为什么这个按钮无法点击  我想要调试查看这个插件是如何对html进行获取的 如何替换img为base64 如何获取iframe的内容的  但是无法调试  我想要学习上面这些关键逻辑!
![image](https://github.com/gildas-lormeau/SingleFile/assets/28215744/f3a15025-5c10-4887-9503-da9893d37e1a)

**Comment by gildas-lormeau** [comment]
I'm sorry but I don't know what this button is because I don't speak Chinese. However, you can press F12 to open the Dev Tools.

**Comment by gildas-lormeau** [comment]
I'm closing the issue, feel free to comment it though.
