### ISSUE TITLE
ebay capture doesn't save all images

### ISSUE THREAD

**Issue by moto-ctrl** [gildas-lormeau/SingleFile#1478]
**Is your feature request related to a problem? Please describe.**
As in the subject, saving page on ebay doesn't save multiple product images so they could be later enlarged

**Describe the solution you'd like**
Similarly as opening auction in the browser, moving across images describing given product should enlarge images and allow to zoom in (ideally)

**Describe alternatives you've considered (optional)**
Separate download of images that can be opened from a directory?

**Additional context (optional)**
The problem is with any auction with multiple images. e.g. https://www.ebay.co.uk/itm/265898030237

**Comment by gildas-lormeau** [comment]
I can confirm that even if you run the script, it doesn't work. Unfortunately, this is one of SingleFile's limitations.
