### ISSUE TITLE
有些网址无法下载图片

### ISSUE THREAD

**Issue by lbcake** [gildas-lormeau/SingleFile#1481]
For questions, please create or update a thread here: 
https://github.com/gildas-lormeau/SingleFile/discussions

Please ensure that you do not find an answer before reporting the issue:
 - in the FAQ: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md
 - in the list of known issues: https://github.com/gildas-lormeau/SingleFile#known-issues
 - in the help page embedded in the extension

**Describe the bug**
网页没有加载显示的图片，通过singlefile下载时，图片也无法显示

**To Reproduce**
1、访问 https://www.52pojie.cn/thread-1060379-1-1.html
2、直接点击singlefile插件，开始下载文件
3、点开下载完成的html文件，会发现里面未加载的图片无法显示，和常见问题里面描述不一致，能否优化下呢

**Expected behavior**
网页没有加载显示的图片，通过singlefile下载后，希望那些没有加载完成的图片也可以显示在html本地文件中

**Screenshots**

没有下载成功图片
![image](https://github.com/gildas-lormeau/SingleFile/assets/26319880/61b76659-0f30-4e86-9eaf-56ec7f4437b0)

**Environment**
 - OS: [Win10]
 - Browser: [ Chrome  128.0.6535.2 ]
 - Version: [64]

**Comment by gildas-lormeau** [comment]
这是因为图像受到 "保护"。请启用  `网络 > 跨域请求失败时添加来源地址头信息（Referer）`。

**Comment by Essayage** [comment]
> 这是因为图像受到 "保护"。请启用 `网络 > 跨域请求失败时添加来源地址头信息（Referer）`。

下面这评论与此讨论主题无关，就是想在此借楼吐槽感谢一下开发者。
webclipper、飞书剪藏、印象笔记剪藏以及其他保存网页的插件都用了，最后用你这一个才成功准确的保存了整个网页，太niubi
![OIP-C](https://github.com/gildas-lormeau/SingleFile/assets/59192319/d1d4162e-52aa-45f5-9b3e-309fde57b903)
