### ISSUE TITLE
ScienceDirect snapshots are missing styles

### ISSUE THREAD

**Issue by adomasven** [gildas-lormeau/SingleFile#1484]
Hi Gildas,

We are getting [reports](https://forums.zotero.org/discussion/113676/zotero-7-beta-problems-with-the-snapshots-imported-from-sciencedirect) from our users that saving ScienceDirect pages (e.g. https://www.sciencedirect.com/science/article/abs/pii/S030193222100152X) produces a broken snapshot. I can reproduce it with the default SingleFile extension. It is reproducible on Firefox and Chrome, with Zotero Connector disabled. Zotero uses the option to not capture frames on the page, but that doesn't seem to have an impact when toggled in SingleFile options.

**Comment by gildas-lormeau** [comment]
Thank you. I was able to reproduce and fix the issue in SingleFile. The fix will be available in the next version. 

You will have to adapt the code on your end. The `fetch` function passed as parameter here https://github.com/zotero/zotero-connectors/blob/d3b870f525137c79a567398b668b87ee19d60fb7/src/common/singlefile.js#L60 should try to fetch the resource via a script injected into the page. This script has to fetch the resource outside the extension world. This allows keeping the `referrer` HTTP header value unchanged.

**Comment by gildas-lormeau** [comment]
Actually passing  the option `referrerPolicy: "strict-origin-when-cross-origin"` to `fetch` might be sufficient...

**Comment by adomasven** [comment]
I've updated SF in the Connector to the latest version which uses `referrerPolicy: "strict-origin-when-cross-origin"`, but it did not help neither in Firefox, nor in Chrome. Are you sure it works without sending the correct referrer?

**Comment by gildas-lormeau** [comment]
Yes, I'm sure it works but for that I have to call `fetch` outside the content script, in the page itself. You should just have to adapt this code https://github.com/gildas-lormeau/SingleFile/blob/dc9d100fbce9e4870d24aa04f718f15c138ca652/src/lib/single-file/fetch/content/content-fetch.js#L96-L138. This code interacts with the following code in `single-file-core` https://github.com/gildas-lormeau/single-file-core/blob/main/processors/hooks/content/content-hooks-frames-web.js#L136-L148.
