### ISSUE TITLE
Saving to zip-based format hangs indefinitely on some pages in Firefox

### ISSUE THREAD

**Issue by LunarTulip** [gildas-lormeau/SingleFile#1492]
I've been trying to save some image-heavy fiction with SingleFile, recently. However, for two of the relevant fiction-works' pages, it's been consistently getting stuck rather than saving successfully. It attempts to save, reaches "Save progress: 100%" according to the extension hovertext (and undims the page), but doesn't reach the point of finishing the save process by putting the file in my filesystem, instead just hanging at 100% save progress forever.

(I have replicated this through multiple browser restarts, in a private window, et cetera.)

To reproduce the bug: First, from SingleFile's default settings, set save format to `self-extracting ZIP (universal)`, `self-extracting ZIP`, or `ZIP`. Then go to one of these two pages:

- https://glowfic.com/posts/8238?view=flat
- https://glowfic.com/posts/7426?view=flat

...and attempt to save with SingleFile. Observe the page never being saved, and instead just getting stuck at "Save progress: 100%". Also, try canceling and retrying once it's been stuck for a while, and observe this leading to the process getting stuck even earlier on the retry, at "Initializing SingleFile (2/2)". Whereas the expected behavior would be for the page to be saved successfully in the normal manner for pages saved with SingleFile.

I've been having this problem on Arch Linux, in Firefox 127.0.2. It didn't arise when I did the same thing in Chromium 126.0.6478.126. It also didn't arise when I saved older versions of those same pages in Firefox on my old Windows 10 machine, about two months ago. (Although sadly I no longer have physical access to that machine and thus I can't test whether it *still* works there.)

**Comment by gildas-lormeau** [comment]
Thank you. I confirm I can reproduce the bug with the 2nd URL. I improved a little bit the implementation but it's not sufficient to fix it. I need to dig a little deeper...

**Comment by gildas-lormeau** [comment]
I was able to fix the bug. Note however that it might take a long time (e.g. more than 1 minute) to process very large pages.
