### ISSUE TITLE
Enable "Save as..." on Firefox

### ISSUE THREAD

**Issue by sampablokuper** [gildas-lormeau/SingleFile#150]
**Is your feature request related to a problem? Please describe.**
Currently, SingleFile on Firefox always saves the page to the Downloads folder.

**Describe the solution you'd like**
Ideally, SingleFile would be able to ask the user which directory they would like to save the page to.

Thanks!

*P.S. Possibly related to #3.*

**Comment by gildas-lormeau** [comment]
You can enable the "Save as" dialog by checking in the options page: File name > Open the save as dialog to confirm the filename.
