### ISSUE TITLE
some code blocks missing

### ISSUE THREAD

**Issue by hxlhxl** [gildas-lormeau/SingleFile#1502]
**Describe the bug**
code blocks missing

**To Reproduce**
1. Go to 'https://mdxjs.com/docs/using-mdx/'
2. Click on 'Save file with singlefile'
3. Open downloaded html
4. Code block is missing

**Expected behavior**
full content should be downloaded

**Screenshots**
![image](https://github.com/user-attachments/assets/6f3b3899-fccc-4fad-b201-6687516f5c4f)

**Environment**
 - OS: Linux debian 5.10.0-23-amd64
 - Browser: Google Chrome Version 113.0.5672.92 (Official Build) (64-bit)
 - Version: SingleFile Version 1.22.51

**Comment by gildas-lormeau** [comment]
Thank you. I confirm I can reproduce the bug. However, if I open the page I saved with Chrome in Firefox or Safari, the blocks are visible. So, it seems to be a tricky issue...

**Comment by gildas-lormeau** [comment]
Taking a closer look at the problem, it seems that the author has decided to deploy some "experimental" code in production. The problem stems from the following declaration `mask-image: paint(squircle);`. `mask-image` is not supported in Safari and Firefox. `paint()` is also only supported in Chrome, cf. https://developer.mozilla.org/en-US/docs/Web/CSS/image/paint, and could be qualified as experimental. I'll have to look into this, but for this to work properly, the page would have to include a piece of JavaScript code to make calls to `CSS.paintWorklet.addModule()`.

**Comment by gildas-lormeau** [comment]
It took a bit of work, but I was able to implement Worklet support. The fix will be available in the next version.
