### ISSUE TITLE
Deferred images on medium.com don't load in background tabs

### ISSUE THREAD

**Issue by user471** [gildas-lormeau/SingleFile#151]
**Describe the bug**
Sometime images doesn't load.

**To Reproduce**
I cannot reproduce it, but I think when I open something like 20 tabs and use "Save all tabs"
**Expected behavior**
Of example this page https://medium.com/refactoring-ui/7-practical-tips-for-cheating-at-design-40c736799886
the second image in html file looks like this 
https://i.imgur.com/REYyLhb.png

**Environment**
 - OS: Win8
 - Browser: Firefox
 - Version: 64

**Comment by gildas-lormeau** [comment]
That's because these images are lazy loaded and SingleFile capture the page before they are fully loaded. Did you try to increase the value of "Images > maximum idle time" in the options page?

**Comment by gildas-lormeau** [comment]
Could you also tell me if unchecking the "compress HTML content" option fixes the issue?

**Comment by gildas-lormeau** [comment]
Anyway, I think I may improve things though when saving "a lot of" tabs. Stay tuned...

**Comment by user471** [comment]
@gildas-lormeau thanks, I will try to increase the idle time and see if it helps. 
Could the extension focus the current tab which it's saving so lazy images start loading and wait when they will be loaded?

**Comment by gildas-lormeau** [comment]
I was able to identify exactly why Medium was not loading images and how to make it load images before saving the page. Thus, the fix does not impact the user experience by changing the focused tab.

**Comment by user471** [comment]
@gildas-lormeau It's still doesn't work sometime. 
I opened https://medium.com/refactoring-ui/7-practical-tips-for-cheating-at-design-40c736799886 in background tab then click Save all tabs, but images wasn't load
version 1.9.89

**Comment by gildas-lormeau** [comment]
@user471 Thanks for the feedback. I'll do more tests to see what's wrong. Please make sure the `maximum idle time` is high enough for medium. I noticed their lazy-loading mechanism is very very slow.

**Comment by user471** [comment]
I set `maximum idle time` for 10000 but it didn't help. When I open medium pages in the browser the images are loaded pretty quick.

**Comment by gildas-lormeau** [comment]
@user471 It should be fixed now. Please tell me if it works for you too. I needed to set a delay of 5000ms to get the complete page though.
