### ISSUE TITLE
Controls that support custom file names and then save them 

### ISSUE THREAD

**Issue by cdxiaodong** [gildas-lormeau/SingleFile#1512]
Controls that support custom file names and then save them

**Comment by gildas-lormeau** [comment]
Can you give me more details or cite an example?

**Comment by gildas-lormeau** [comment]
I guess you're referring to the option `File name > open the "Save as" dialog to confirm the file name` in the options page of SingleFile. Feel free to comment the issue if I'm wrong.

**Comment by cdxiaodong** [comment]
thanks，i got help yet
