### ISSUE TITLE
Unable to print infobar

### ISSUE THREAD

**Issue by rxnwin** [gildas-lormeau/SingleFile#1516]
Thank you for the kind words! The link to the original URL is displayed in the infobar at the top right of the saved page when displaying it in a browser. If you're using a Chromium-based browser, make sure `Allow access to file URLs` is enabled here `chrome://extensions/?id=mpiodijhokgodhhofbcjdecpffjipkle` in order to display the infobar.

_Originally posted by @gildas-lormeau in https://github.com/gildas-lormeau/SingleFile/discussions/685#discussioncomment-2415147_

It is elegant to use the infobar to display the original url, but the infobar  is always folded when the saved file is printed as pdf. Can we set the infobar to expand by default, or display information at the top like Save Page WE?

**Comment by gildas-lormeau** [comment]
I added an option `Infobar > keep infobar open`. The feature will be available in the next version.
