### ISSUE TITLE
How to export images in html file into folder ?

### ISSUE THREAD

**Issue by wankio** [gildas-lormeau/SingleFile#153]
This firefox extension worked pretty good but how i can export single html file into folder with images inside ? 
Thank

**Comment by gildas-lormeau** [comment]
I guess you would have to use an extension that allows you to download images into a folder. I don't know if it exists but I confirm this is technically doable. From my point of view, I consider this feature out of scope for SingleFile. If you cannot find such extension, I may develop one since it wouldn't be very hard to do so.

**Comment by wankio** [comment]
yeah, it would be great, download images in fully loaded webpage into folder, folder name set by page title and date_time. mht2html

**Comment by JohnnyWoong** [comment]
maybe can add option for single file or split html,css,js and images

**Comment by gildas-lormeau** [comment]
@JohnnyWoong Do you think that could be really interesting for users to save apart the CSS and JS files?

**Comment by JohnnyWoong** [comment]
I think that will be a great app for developers

**Comment by gildas-lormeau** [comment]
Why shouldn't they use the native "save as" feature which does exactly this (i.e. saving in a separate folder all the external resources)?

**Comment by JohnnyWoong** [comment]
This way save page ofter miss something

**Comment by gildas-lormeau** [comment]
The native "save as" may be indeed less reliable... The problem is that you're basically asking me to re-implement the "save as" feature because Google don't fix their bugs.  If I implemented it, I think I could not integrate this feature in SingleFile, because of its name. I'm pretty sure people would never expect it to save a page in several files...

**Comment by JohnnyWoong** [comment]
Yeap,you are right (｀・ω・´)

**Comment by KrasnayaPloshchad** [comment]
You can try Web ScrapBook to save page, then you will get a HTZ file, or MAFF file if you configured, then you extract it via 7-zip and similar app, and you will get it.

**Comment by JohnnyWoong** [comment]
> You can try Web ScrapBook to save page, then you will get a HTZ file, or MAFF file if you configured, then you extract it via 7-zip and similar app, and you will get it.

ok, i will try that,thx : )

**Comment by wankio** [comment]
mht2html can extract it. Singlefile is really great for archive page without redownload any files (it may have chance to failed,missing,corrupted if redownload files)

**Comment by gildas-lormeau** [comment]
@JohnnyWoong Did you try this extension? https://chrome.google.com/webstore/detail/save-all-resources/abpdnfjocnmdomablahdcfnoggeeiedb

**Comment by JohnnyWoong** [comment]
> @JohnnyWoong Did you try this extension? https://chrome.google.com/webstore/detail/save-all-resources/abpdnfjocnmdomablahdcfnoggeeiedb

thx,i will try that

**Comment by gildas-lormeau** [comment]
@JohnnyWoong Did you try the extension? It looks like it's exactly what you need. Therefore, I would close this issue.

**Comment by JohnnyWoong** [comment]
Yep,i already try that,that is what i want,thx :)

**Comment by gildas-lormeau** [comment]
Great!

**Comment by gildas-lormeau** [comment]
@JohnnyWoong This may interest you: https://addons.mozilla.org/en-US/firefox/addon/singlefilez/

This fork of SingleFile creates HTML files that are also ZIP files which contain the page resources.

**Comment by JohnnyWoong** [comment]
Thanks for info, but i am a chrome user 👍

**Comment by gildas-lormeau** [comment]
@JohnnyWoong Too bad, you don't know what you're missing ;)

**Comment by gildas-lormeau** [comment]
@wankio @JohnnyWoong This may interest you: https://chrome.google.com/webstore/detail/singlefilez/offkdfbbigofcgdokjemgjpdockaafjg

**Comment by JohnnyWoong** [comment]
wow, thx :)

Gildas Lormeau <notifications@github.com> 于2019年5月29日周三 上午5:02写道：
