### ISSUE TITLE
[Bug] Auto-settings - Can't exit edit mode without making a change

### ISSUE THREAD

**Issue by TFWol** [gildas-lormeau/SingleFile#1530]
**Describe the bug**

When editing an existing URL under auto-settings and you decide you don't want to change it, you won't be able to cancel the edit.

**To Reproduce**
1. Go to addon settings page (doesn't matter if normal or full screen version)
2. Under auto-settings, next to an existing entry, click the pencil icon to enter edit mode
3. Note the appearance of the Check symbol which would allow you to validate your settings
4. Click inside the URL field
5. Look at the check symbol, it is greyed out and you can't click it to exit edit mode. You also won't be able to edit any other entry's settings.

You are basically forced to make a change, save it, remove your change, then save it again.

**Expected behavior**
Keep the check symbol from being greyed out or a mechanism to cancel a change.

**Environment**
 - OS: Win10 Pro
 - Browser: Firefox 
 - Version: 128

**Comment by gildas-lormeau** [comment]
Thank you! I agree that this feature is missing and that it's frustrating to be confronted with this problem as a user. I don't know why I forgot it. I guess it was to do as little as possible :p. I'll add a Cancel button and make the `Esc` key work too, ideally.

**Comment by gildas-lormeau** [comment]
The "cancel" button and the "Escape" shortcut are now implemented. The feature will be available in the next version.
