### ISSUE TITLE
`np-coburg.de`: slideshow images not saved

### ISSUE THREAD

**Issue by mara004** [gildas-lormeau/SingleFile#1533]
**Describe the bug**

When saving pages from `np-coburg.de`, image slideshows are broken. Only the first image is included, any others are lost.

I have read the FAQs ["Why aren't images saved on [some sites]?"](https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-arent-images-saved-on-sites-like-sspaicom-or-weibocom) and ["Why don't interactive elements [...] work properly in saved pages?"](https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages), but checking the mentioned options does not help. In fact, this makes all images disappear, even the first.

**To Reproduce**
1. Go to any article with slideshow from `np-coburg.de`, e.g. https://www.np-coburg.de/inhalt.lage-im-ueberblick-brand-im-kuehlsystem-von-akw-saporischschja-geloescht.1088cf39-0e92-41d1-bd9d-3d1d9856340c.html
2. Save with SingleFile by clicking its icon
4. View the output. It will shows only image 1; slideshow controls and subsequent images are missing (in this case, images 2 to 4).

**Expected behavior**
All images should be included; slideshow should work.

**Screenshots**
Online page | Saved page
--- | ---
![image](https://github.com/user-attachments/assets/a008d10b-85b5-4371-bbd8-707bc5463e41) |![image](https://github.com/user-attachments/assets/fecebe65-6aec-4740-bc99-1bea6d6c4d91)
... | (not navigatable)

**Environment**
 - OS: Fedora 37
 - Browser: Firefox 120.0.1
 - SingleFile Version: 1.22.55

**Additional context**
`archive.org` and `archive.ph` also fail to save the slideshows:
https://archive.ph/2kbOf
https://web.archive.org/web/20240812175851/https://www.np-coburg.de/inhalt.lage-im-ueberblick-brand-im-kuehlsystem-von-akw-saporischschja-geloescht.1088cf39-0e92-41d1-bd9d-3d1d9856340c.html

**Comment by gildas-lormeau** [comment]
I did a test and I confirm SingleFile cannot save the images because they are retrieved dynamically after the page is loaded. You can circumvent the issue by disabling the option `HTML Content > set content security policy` (and following the advises in the FAQ). However, the images won't be visible when viewing the page offline, or if they disappear from the website one day. I attached an example of saved page.

[Ukraine-Krieg_ Putin will endlich Ruhe an neuer Front von Kursk - Politik - Neue Presse Coburg (8_12_2024 8_19_00 PM).html.zip](https://github.com/user-attachments/files/16591547/Ukraine-Krieg_.Putin.will.endlich.Ruhe.an.neuer.Front.von.Kursk.-.Politik.-.Neue.Presse.Coburg.8_12_2024.8_19_00.PM.html.zip)

**Comment by mara004** [comment]
I see, thanks for the quick reply.

Unfortunately that's not too much use to me, as what I wish to do is archive standalone, offline snapshots (of some of the paid articles, actually).
So I guess I'll have to download the additional images manually and store them in an accompanying directory (duh).

Thanks for this nice tool anyway; it works well on many other websites that don't do this dynamic loading.

**Comment by gildas-lormeau** [comment]
I'm glad to hear it works sometimes ;) 

On paper, the WARC format is more suited to your needs. This format is designed to store all network exchanges. FYI, you can find a list of tools to handle WARc files here: https://wiki.archiveteam.org/index.php/The_WARC_Ecosystem#Tools.

**Comment by mara004** [comment]
Thanks for the link, I shall give WARC a try. Do you have a recommendation which of these tools I should use?
However, seeing as the archive sites failed too, I'm not sure whether I'll truly have more luck with WARC?
Also, if I end up with some command-line tool, how will this play with the paywall?

**Comment by gildas-lormeau** [comment]
It would be difficult for me to give you more information, as I haven't had the time or opportunity to test the tools.
