### ISSUE TITLE
Saving in the background doesn't work with S3 Destination

### ISSUE THREAD

**Issue by davidzajac1** [gildas-lormeau/SingleFile#1534]
**Describe the bug**
HTML downloads in the background when the Destination is set to "save to filesystem" without having to press the SingleFile button, but when destination is set to "upload to Amazon S3" saving in the background fails with the error below from the Console. Saving to S3 does still work when manually triggered by clicking the SingleFile extension icon.

```
Rob_Dyrdek:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

chrome-browser-polyfill.js:1 Uncaught (in promise) Error: Extension context invalidated.
    at Object.sendMessage (chrome-browser-polyfill.js:1:2358)
    at A (single-file-extension-bootstrap.js:1:4576)
    at b (single-file-extension-bootstrap.js:1:3229)
    at single-file-extension-bootstrap.js:1:1672
    at E (single-file-extension-bootstrap.js:1:1777)
    at single-file-extension-bootstrap.js:1:1742
```

**To Reproduce**
1. Set Destination to "upload to Amazon S3"
2. Make sure "auto-save after page load or on page unload" under the "Auto-save" section is checked
3. Make sure "save pages in background" and "display stats in the console after processing" are checked under the "Misc." section
4. Navigate to any website and observe that the contents is Not saved in the background

**Expected behavior**
The page should be saved in the background and uploaded to the S3 bucket without error.

**Screenshots**
![image](https://github.com/user-attachments/assets/ba1245cb-9c12-4b97-993d-8787cf340962)

**Environment**
 - OS: Macbook M1 Pro - Sonoma 14.5
 - Browser: Chrome 127.0.6533.100

**Additional context**
This is not an authentication issue with S3! When I click "Save page with profile" the page saves properly and is uploaded to my S3 bucket seconds later.

I could probably fix this myself and make a PR if someone can comment with some context on where the issue with this might be.

**Comment by gildas-lormeau** [comment]
Thank you, I've found an error in the code but I did not test the fix yet. Feel free to test it by installing manually code on `master`.

**Comment by davidzajac1** [comment]
> Thank you, I've found an error in the code but I did not test the fix yet. Feel free to test it by installing manually the code on the `master` branch.

This is great thanks @gildas-lormeau for the quick response!

**Comment by gildas-lormeau** [comment]
I was able to reproduce the issue and fix it. The will be available in the next version (on all platforms).

**Comment by davidzajac1** [comment]
@gildas-lormeau I can't believe how quick you got to that thanks os much!

**Comment by gildas-lormeau** [comment]
You're welcome, it was an easy fix ;)
