### ISSUE TITLE
Constantly receive Err when trying to download page

### ISSUE THREAD

**Issue by FluidNets-DamianS** [gildas-lormeau/SingleFile#154]
**Describe the bug**
Receiver a red Err message when clicking on the icon to download page.

**To Reproduce**
1. Go to 'https://help.myglue.com/hc/en-us/articles/360000095552'
2. Click on 'Save Page with SingleFile' (icon)
3. See error

**Expected behavior**
The page to download.

**Screenshots**
![image](https://user-images.githubusercontent.com/10325877/52610033-67c78800-2e4d-11e9-89a1-ae6c81e74c29.png)

**Environment**
 - OS: Win10 Pro x64
 - Browser: Chrome
 - Version: 72.0.3626.96

**Additional context**
The last time I used SingleFile ~4mos ago it worked fine.

**Comment by firzen** [comment]
me too

**Comment by KageDev** [comment]
Same. Yesterday it worked and today it stopped ;(

Win10 Pro x64
Google Chrome 72.0.3626.96

**Comment by gildas-lormeau** [comment]
I'm really sorry for the inconvenience guys. It's fixed version 1.9.57.

**Comment by gildas-lormeau** [comment]
By the way, thank you all for having reported the issue!

**Comment by KageDev** [comment]
No, thank YOU for making such a great tool =)
