### ISSUE TITLE
Infobar appears in the saved page only if 'include the infobar in the saved page' is unchecked

### ISSUE THREAD

**Issue by aquarime** [gildas-lormeau/SingleFile#1541]
Hi,

SingleFile 1.22.59 / Firefox 115.14.0 ESR

Just noticed that the Infobar button appears on saved pages only if the option _include the infobar in the saved page_ is **_unchecked_**.
_include the infobar in the saved page_  states: _Check this option to display the ℹ button at the top right of the page when viewing a saved page in a browser where SingleFile is not installed._

Hence, enabled or not, the Infobar button should always appear on viewing a saved page in a browser where SingleFile _IS_ included IF _display an infobar when viewing a saved page IS checked_, which is the case when this issue is encountered. I have not tested on a browser where SingleFile is NOT installed.

**Comment by gildas-lormeau** [comment]
I did all the possible tests but I was not able to reproduce the issue. Did you change any other setting?

**Comment by aquarime** [comment]
Now this is odd.
I don't change Singlefile's settings, I've always had them as now and Infobar would display on saved pages.
I then noticed when saving a page with SingleFile 1.22.59 that, without having changed any of its settings, the Infobar would not display.
I don't save many pages so I presume the issue appeared with 1.22.59

I had an irrational try with setting the 'include the infobar in the saved page' to false and ... Infobar appeared , which surprised me given 'display an infobar when viewing a saved page IS checked' should be the only concerned pref in my scenario (saved page viewed on a browser which runs the extension).

To summarize:

include the infobar in the saved page = CHECKED = `"includeInfobar": true` -> issue
include the infobar in the saved page = UNCHECKED = `"includeInfobar": false` -> No issue

Maybe a conflict with another extension? Really odd. I'll have a look at possible interferences ...

This is my SingleFile's settings from .json:
If I change _include the infobar in the saved page_ to UNCHECKED, hence "includeInfobar": false in the settings.json, no issue, Infobar button is correctly displayed.

`START -------------------------------------------------------------------------`

{
  "profiles": {
    "__Default_Settings__": {
      "removeHiddenElements": true,
      "removeUnusedStyles": true,
      "removeUnusedFonts": true,
      "removeFrames": false,
      "blockScripts": true,
      "blockVideos": true,
      "blockAudios": true,
      "blockFonts": false,
      "blockStylesheets": false,
      "blockImages": false,
      "acceptHeaders": {
        "document": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "script": "*/*",
        "audio": "audio/webm,audio/ogg,audio/wav,audio/*;q=0.9,application/ogg;q=0.7,video/*;q=0.6,*/*;q=0.5",
        "video": "video/webm,video/ogg,video/*;q=0.9,application/ogg;q=0.7,audio/*;q=0.6,*/*;q=0.5",
        "font": "application/font-woff2;q=1.0,application/font-woff;q=0.9,*/*;q=0.8",
        "stylesheet": "text/css,*/*;q=0.1",
        "image": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8"
      },
      "saveRawPage": false,
      "insertMetaCSP": true,
      "saveToClipboard": false,
      "addProof": false,
      "woleetKey": "",
      "saveToGDrive": false,
      "saveToDropbox": false,
      "saveWithWebDAV": false,
      "webDAVURL": "",
      "webDAVUser": "",
      "webDAVPassword": "",
      "saveToGitHub": false,
      "githubToken": "",
      "githubUser": "",
      "githubRepository": "SingleFile-Archives",
      "githubBranch": "main",
      "saveWithCompanion": false,
      "sharePage": false,
      "compressHTML": true,
      "insertTextBody": false,
      "insertEmbeddedImage": false,
      "insertEmbeddedScreenshotImage": false,
      "compressCSS": false,
      "moveStylesInHead": false,
      "loadDeferredImages": true,
      "loadDeferredImagesMaxIdleTime": 1500,
      "loadDeferredImagesKeepZoomLevel": false,
      "loadDeferredImagesDispatchScrollEvent": false,
      "loadDeferredImagesBeforeFrames": false,
      "contextMenuEnabled": true,
      "filenameTemplate": "%if-empty<{page-title}|No title>.html",
      "filenameMaxLength": "192",
      "filenameMaxLengthUnit": "bytes",
      "filenameReplacementCharacter": "_",
      "replaceEmojisInFilename": false,
      "saveFilenameTemplateData": false,
      "shadowEnabled": true,
      "maxResourceSizeEnabled": false,
      "maxResourceSize": 10,
      "networkTimeout": 0,
      "confirmFilename": false,
      "filenameConflictAction": "uniquify",
      "displayInfobar": true,
      "displayStats": false,
      "backgroundSave": true,
      "autoSaveDelay": 1,
      "autoSaveLoad": false,
      "autoSaveUnload": false,
      "autoSaveDiscard": false,
      "autoSaveRemove": false,
      "autoSaveLoadOrUnload": true,
      "autoSaveRepeat": false,
      "autoSaveRepeatDelay": 10,
      "autoSaveExternalSave": false,
      "removeAlternativeFonts": true,
      "removeAlternativeImages": true,
      "removeAlternativeMedias": true,
      "saveCreatedBookmarks": false,
      "passReferrerOnError": false,
      "replaceBookmarkURL": true,
      "allowedBookmarkFolders": [
        ""
      ],
      "ignoredBookmarkFolders": [
        ""
      ],
      "compressContent": false,
      "createRootDirectory": false,
      "preventAppendedData": false,
      "selfExtractingArchive": false,
      "extractDataFromPage": false,
      "password": "",
      "groupDuplicateImages": true,
      "infobarTemplate": "",
      "blockMixedContent": false,
      "saveOriginalURLs": false,
      "includeInfobar": true,
      "openInfobar": false,
      "removeSavedDate": false,
      "confirmInfobarContent": false,
      "autoClose": false,
      "openEditor": false,
      "openSavedPage": false,
      "autoOpenEditor": false,
      "defaultEditorMode": "normal",
      "applySystemTheme": true,
      "warnUnsavedPage": true,
      "displayInfobarInEditor": false,
      "saveToRestFormApi": false,
      "saveToRestFormApiUrl": "",
      "saveToRestFormApiToken": "",
      "saveToRestFormApiFileFieldName": "",
      "saveToRestFormApiUrlFieldName": "",
      "saveToS3": false,
      "S3Domain": "s3.amazonaws.com",
      "S3Region": "",
      "S3Bucket": "",
      "S3AccessKey": "",
      "S3SecretKey": "",
      "sync": false,
      "loadDeferredImagesBlockCookies": false,
      "loadDeferredImagesBlockStorage": false,
      "filenameReplacedCharacters": [
        "~",
        "+",
        "\\\\",
        "?",
        "%",
        "*",
        ":",
        "|",
        "\"",
        "<",
        ">",
        "\u0000-\u001f",
        ""
      ],
      "tabMenuEnabled": false,
      "browserActionMenuEnabled": true,
      "logsEnabled": true,
      "progressBarEnabled": true,
      "maxSizeDuplicateImages": 524288,
      "forceWebAuthFlow": false,
      "resolveFragmentIdentifierURLs": false,
      "userScriptEnabled": false,
      "saveFavicon": true,
      "includeBOM": false,
      "insertMetaNoIndex": false,
      "insertSingleFileComment": true,
      "_migratedTemplateFormat": true,
      "delayBeforeProcessing": 0,
      "blockAlternativeImages": true
    }
  },
  "rules": [
    {
      "url": "file:",
      "profile": "__Default_Settings__",
      "autoSaveProfile": "__Disabled_Settings__"
    }
  ],
  "maxParallelWorkers": 2,
  "processInForeground": false
}

`END --------------------------------------------------------`

**Comment by gildas-lormeau** [comment]
Did you you see the "Edit" section in y previous message?

**Comment by aquarime** [comment]
> Did you you see the "Edit" section in y previous message?

Mea culpa, I read too quickly and not till the end which states indeed:

> Edit: Sorry, I did not do my tests in Firefox ESR. This might be the reason I was not able to reproduce it. If I'm not wrong the version 1.22.61 (publish in progress) should fix the issue. I recently fixed a regression indirectly related to the infobar and which was specific to "old" browsers.

I'll wait for planned SingleFile 1.22.61 and let you know.
Sorry for having missed the end of your comment leading to useless explanations.

**Comment by aquarime** [comment]
Fixed with SingleFile 1.22.61
Thanks

**Comment by gildas-lormeau** [comment]
Thank you for the feedback!
