### ISSUE TITLE
Ability to save images / fonts on disk instead of base64

### ISSUE THREAD

**Issue by You-Honey** [gildas-lormeau/SingleFile#1544]
Would it be possible to have a feature that allows me to save all assets to disk instead of converting them to base64?

Love the product btw!

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. Actually, it would no longer be SingleFile but the standard "save as" feature. Have you tried saving the pages in ZIP format (see Options > File format)? That might suit your needs.

**Comment by You-Honey** [comment]
@gildas-lormeau Sorry to bother you but could you help me out what variable handles the zip feature? As I'm using the plugin programmatically.

https://github.com/gildas-lormeau/SingleFile/blob/master/src/core/bg/config.js
