### ISSUE TITLE
'Maximum length of filename option' not working when saving to WebDAV server

### ISSUE THREAD

**Issue by foxdodo** [gildas-lormeau/SingleFile#1547]
When scraping Twitter, SingleFile copy the entire tweet into the filename, causing an error when storing it in the EXT4 file system.
Attempted to enable the `Maximum length of filename `option and set it to 50 bytes, but it still returned a 405 error.
Enable the `Save as dialog to confirm filename` option to observe the file length, find that it hasn't been reduced to the specified length.
When using the desktop version of the SingleFile extension, I can solve the problem by enabling `Save as dialog to confirm filename` option. However, the Safari extension for iOS doesn't have the option to `Open 'Save As' dialog to rename` the file.
Apart from first saving the file locally, then renaming it and uploading it to WebDAV, are there any other work around?

**Comment by gildas-lormeau** [comment]
In fact, this was deliberate on my part, as I considered this limit to be especially valid for the filesystem. But it wasn't a good idea, because there's always a limit . From now on, the filename will always be truncated if necessary. The fix will be available in the next version.
