### ISSUE TITLE
Special characters in the password cause the configuration file export to be incomplete.

### ISSUE THREAD

**Issue by kimoch111** [gildas-lormeau/SingleFile#1548]
The presence of a "#" in the password "Save to WebDAV Server" results in an incomplete exported profile

**Comment by gildas-lormeau** [comment]
I think I was not able to reproduce the issue. Could you please provide more details?

**Comment by kimoch111** [comment]
Edge Version: 128.0.2739.54
SingleFile Version: 1.22.61

Reinstall the extension
![image](https://github.com/user-attachments/assets/4ced6080-678e-4ca0-bb12-2de5b6c37280)

Default configuration directly sets webdav configuration
![image](https://github.com/user-attachments/assets/e2ce83cc-e041-440b-96bb-88c853a073e5)

Looking at the exported configuration, it is found that the output content is incomplete, and it is interrupted at the "#" of the password.
![image](https://github.com/user-attachments/assets/1ea454c9-411a-4a6c-9931-f0312e933a94)

Have tested, in Edge browser using installing extensions from the chrome store, same error, same error in Chrome, on firefox it's correct!

**Comment by gildas-lormeau** [comment]
Thank you for the additional info, I was able to reproduce and fix the issue. The fix will be available in the next version.
