### ISSUE TITLE
weibo.com's images can't be saved in version 1.22.62

### ISSUE THREAD

**Issue by childlikx** [gildas-lormeau/SingleFile#1549]
I have read this issue  #1096 .

Whether or not the `"Referer" header after a cross-origin request error` option is enabled, the image cannot be saved normally.

The issue only occurs in the chrome store version 1.22.62, the edge store version 1.22.61 works fine.

Environment

OS: [Win10 64 bytes]
Browser: [Edge 128.0.2739.42]
Version: [Chrome store 1.22.62]

**Comment by gildas-lormeau** [comment]
Thank you very much! It was actually a severe regression. I've rolled back the changes in the version 1.22.63.

**Comment by childlikx** [comment]
> Thank you very much! It was actually a severe regression. I've rolled back the changes in the version 1.22.63.

The same issue occurred in the latest version 1.22.76, I wonder if it is because of this modification #1640, but it seems that the problem in that issue has not been fixed either.

**Comment by gildas-lormeau** [comment]
@childlikx Thank you, I think I was able to reproduce and fix the issue (on both sites). The fix will be available in. the next version.
