### ISSUE TITLE
Youtube does not load completely (SingleFile 1.9.59)

### ISSUE THREAD

**Issue by DeVIL-I386** [gildas-lormeau/SingleFile#155]
Firefox 65.0.1 64-bit
Windows 10 Home Version 1803

Youtube does not load completely as long as the extension is active. Videos can also not be switched to fullscreen. If you deactivate SingleFile, Youtube works as usual again.
The Firefox console says:
SingleFile is hooking the requestAnimationFrame function to load deferred images.

![screenshot_2019-02-14 youtube](https://user-images.githubusercontent.com/1786308/52753548-633ed300-2ff7-11e9-9373-f916ffe5dcb8.png)

Cookies and browser cache have already been deleted. Browser has already been restarted.

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. Please force the update of the extension. The version 1.9.60 published 4 hours ago fixes it.
