### ISSUE TITLE
SingleFile Downloaded Self-Extracting ZIP File Displays Blank Page When Opened

### ISSUE THREAD

**Issue by undefined-me** [gildas-lormeau/SingleFile#1557]
Hi,
I'm experiencing an issue with the self-extracting ZIP format generated by SingleFile. When I download and open the file, the resulting HTML page displays as blank.  
The file is from this URL: 
https://zh.wikipedia.org/wiki/2024%E5%B9%B4%E5%A4%8F%E5%AD%A3%E5%B8%95%E6%8B%89%E6%9E%97%E5%8C%B9%E5%85%8B%E9%81%8B%E5%8B%95%E6%9C%83 
![image](https://github.com/user-attachments/assets/e7bc2be5-3f27-4de3-b920-cb921aa9c985)

**To Reproduce**
1. I used SingleFile to save a webpage in self-extracting ZIP format.
2. I used a browser with SingleFile installed to open the self-extracting ZIP format webpage.
3. The page displays as blank.

**Environment**
 - OS: Win10 22H2
 - Browser: Chrome, Edge
 - Version: 64

**Additional context**
I have enabled the option 'Allow access to file URLs.'

**Comment by gildas-lormeau** [comment]
Thank you, I was able to reproduce the issue. It's actually a regression due to the migration to the Manifest V3. I fixed it. The fix will be available in the next version.
