### ISSUE TITLE
Win7/FF65 + SingleFile = Links on Youtube can't be clicked anymore

### ISSUE THREAD

**Issue by Revisor** [gildas-lormeau/SingleFile#156]
**Describe the bug**
After upgrading to Firefox 65, I found the following bugs:
1. Links on Youtube can't be clicked: I can see the URL in the status bar when hovering over them, but nothing happens after clicking, the page doesn't change.
2. Content on Youtube doesn't load: When visiting a Youtube video, only the video appears. The title, rating, description, comments and recommended videos stay blank.
3. Invisible overlay on Slack: No text can be selected and no links clicked on Slack.

**To Reproduce**
1. Go to www.youtube.com
2. Click on any video thumbnail
3. Nothing happens

**Expected behavior**
The clicked video should load.

**Environment**
 - OS: Win7 64-bit
 - Browser: Firefox
 - Version: 65.0.1 64-bit

**Additional context**
I tried disabling all add-ons and enabling them one by one, until I found that it was SingleFile that caused the problems. After this I confirmed that it's not caused by a combination of add-ons by disabling all and enabling only SingleFile.

Thank you for the useful add-on, it has helped me a lot.

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue and sorry for the inconvenience. This was a bug in the version 1.9.59. Please update to version 1.9.60. You can force the pdate via the combo button a the top right of the page here: about:addons.

**Comment by gildas-lormeau** [comment]
Duplicate of https://github.com/gildas-lormeau/SingleFile/issues/155

**Comment by Revisor** [comment]
Ah, I see. Thank you for the quick response. After updating it indeed works.

I'm sorry for the duplicate bug report, I should have looked in the closed issues.

**Comment by gildas-lormeau** [comment]
You're welcome.

Don't worry for the duplicate. I shouldn't have broken Youtube in the first place :p.
