### ISSUE TITLE
Option "HTML > remove unused attributes"

### ISSUE THREAD

**Issue by ghost** [gildas-lormeau/SingleFile#1565]
**Describe the bug**
1. There is an option in SingleFile to compress the HTML content, the option is activated by default to remove unnecessary content without changing the appearance of the document, reducing the file size:

![image](https://github.com/user-attachments/assets/11381dfc-0bd5-4baa-a66d-74da07fe62b4)

2. However, the option does not work on certain pages, keeping several unnecessary attributes in the source code elements, such as:

![image2](https://github.com/user-attachments/assets/4bf0941f-238f-454d-a458-8eef4bd1acbb)

3. It seems that in general, custom attributes are not removed, leaving the file unnecessarily larger.

**To Reproduce**
1. Go to https://gemini.google.com/share/1c4c3bc8cb01
2. Save the page with SingleFile
4. See the source code with several unnecessary attributes on the elements, just increasing the file size

**Expected behavior**
The page has unnecessary attributes removed, and the file size is smaller.

**Environment**
 - OS: Win10 Pro
 - Browser: Chrome
 - Version: 128

**Comment by gildas-lormeau** [comment]
The elements you've highlighted are attributes, not tags. This is why they are not removed. Removing unused attributes is not implemented in SingleFile. I also think it's a bit difficult to implement.
