### ISSUE TITLE
BUG: when saving openai article SingleFile does not preserve the content of the embedded tabs

### ISSUE THREAD

**Issue by Emasoft** [gildas-lormeau/SingleFile#1568]
**Describe the bug**
When saving the following web article SingleFile does not preserve the content of the embedded tabs (or the tab buttons responsivness):
https://openai.com/index/learning-to-reason-with-llms/

**To Reproduce**
1. Go to 'https://openai.com/index/learning-to-reason-with-llms/'
2. Export using SingleFile Safari iOS extension
3. Search and preview the generated html file saved into the Downloads folder (using File app on iCloud Drive)
4. Scroll down to the tabs
5. Click on 'Coding' tab (or any other)
6. See that the content of the tab is not updated
7. Try also opening the file with Textual, GoCo or other text editors with embedded browsers (same result)

**Expected behavior**
When opening the saved .html file in the (with preview or with any browser) the tabs should change the text content displayed when clicked.

**Environment**
 - OS: iPadOS 17.6.1 (21G93)
 - Browser: Safari iOS

**Comment by gildas-lormeau** [comment]
This is a known issue, it's documented in the FAQ here: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages.
