### ISSUE TITLE
место, где пасутс�….html (invalid encoding)

### ISSUE THREAD

**Issue by fox0** [gildas-lormeau/SingleFile#157]
Hi again.

**Describe the bug**
The filename is truncated incorrectly If page-title is unicode.

**To Reproduce**
Template filename: {page-title} ({date-iso} {time-locale}).html

1. Go to https://tabun.everypony.ru/blog/toymerchandise/186413.html
2. Click on 'save page'
3. See wrong filename.

**Environment**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 65

**Comment by fox0** [comment]
Maybe this will be useful when searching for a bug:
`new Blob(['11ф']).slice(0, 3)`

**Comment by fox0** [comment]
https://github.com/gildas-lormeau/SingleFile/blob/master/lib/single-file/single-file-core.js#L450
https://github.com/gildas-lormeau/SingleFile/blob/master/lib/single-file/util/doc-util.js#L95

**Comment by gildas-lormeau** [comment]
Thanks @fox0 for you detailed description. I reproduced and fixed the issue. It will be available soon in the next version.

**Comment by gildas-lormeau** [comment]
I deployed the version 1.9.67 which should fix this issue.

**Comment by fox0** [comment]
Everything is working. Thank.
