### ISSUE TITLE
Unicode-range matching bug

### ISSUE THREAD

**Issue by BloodlineL** [gildas-lormeau/SingleFile#1571]
![unicode-range](https://github.com/user-attachments/assets/a628cfe7-9f89-4c95-a7e3-529a5b51aa9e)
unicode-range: U+0025-00FF;  true
unicode-range: U+4??; true 
unicode-range: U+26; false
Single code point always return false.

**Comment by gildas-lormeau** [comment]
Thank you very much, I've corrected the bug. The correction will be available in the next version.
