### ISSUE TITLE
Feature: Include 32px icon for the Add-ons Manager

### ISSUE THREAD

**Issue by Nmrawe** [gildas-lormeau/SingleFile#1577]
**Is your feature request related to a problem? Please describe.**
SingleFile comes with various sizes of its icon, but it is missing the 32px variant used by Firefox in the Add-ons Manager. It is getting downloaded from https://addons.mozilla.org instead. Unfortunately, Firefox launched in the offiline environment will not display this icon.

**Describe the solution you'd like**
Include the 32px icon.

**Comment by gildas-lormeau** [comment]
Thank you for the info, I added the icon. The fix will be available in the next version.
