### ISSUE TITLE
Some images were wrongly converted with save raw page enabled

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [gildas-lormeau/SingleFile#158]
**Describe the bug**
If I enabled Save raw page for www.wikimedia.org, many of image failed to load, only Wikipedia globe available.

**To Reproduce**
1. Go to www.wikimedia.org
2. Enable Save raw page at about:addons
3. Click on SingleFile button

**Expected behavior**
All images are saved as well

**Screenshots**
No, but a attachment available.

**Environment**
 - OS: Win10
 - Browser: Firefox 65

**Additional context**

[Wikimedia.zip](https://github.com/gildas-lormeau/SingleFile/files/2895074/Wikimedia.zip)

**Comment by gildas-lormeau** [comment]
Thanks again @KrasnayaPloshchad for your issue report. I reproduced and fixed the problem. The fix will be available in the next version.

**Comment by gildas-lormeau** [comment]
I deployed the version 1.9.67 which should fix this issue.

**Comment by KrasnayaPloshchad** [comment]
OK, fixed.
