### ISSUE TITLE
User Script integration: script cannot access "detail" property of event (Permission Denied) in Firefox

### ISSUE THREAD

**Issue by surlyhacker** [gildas-lormeau/SingleFile#1588]
**Describe the bug**
I am trying to use a user script (via Violentmonkey) in Firefox to get/set options for SingleFile in the provided events/handlers and I get a 'Permission denied to access property "options" ' in the console.

**To Reproduce**
1. Follow directions to enable user script integration [here](https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved)
2. Create a user script that responds to the `single-file-on-before-capture-request` event
3. In the event handler, try to access the event's `detail.options` object
4. See error in console 'Permission denied to access property "options" ' 

**Expected behavior**
That I can get/set options for SingleFile programmatically via this event handler 

**Environment**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 131

**Additional context**
The page I linked above says "You can also get and set the options via the detail property of the single-file-on-before-capture-request and single-file-on-before-capture-response events."

I am using the default @inject-into user script metadata setting, but have tried all possible values for this.

Here is the relevant code from the user script:
```
dispatchEvent(new CustomEvent("single-file-user-script-init"));

  addEventListener("single-file-on-before-capture-request", (foo) => {
    console.dir(foo.detail);
    console.log("template: "+foo.detail.options.filenameTemplate);
    console.dir(foo.detail.options.filenameTemplate);

  });
```

**Comment by gildas-lormeau** [comment]
Thank you, I confirm I was able to reproduce the issue. This is due to a security restriction in Firefox. 

In order to circumvent it, I added the support of JSON values instead of objects by passing the option `{ detail: "jsonDetail" }` when dispatching the `single-file-user-script-init` event. See the code below for example. This new feature will be available in the next version.

```
dispatchEvent(new CustomEvent("single-file-user-script-init", { detail: "jsonDetail" }));

addEventListener("single-file-on-before-capture-request", (event) => {
  event.preventDefault();
  const { options } = JSON.parse(event.detail);
  options.filenameTemplate = "test.html";
  dispatchEvent(new CustomEvent("single-file-on-before-capture-response", { detail: JSON.stringify({ options }) }));
});
```
