### ISSUE TITLE
Failure to Save Text Box Contents - Firefox Plugin

### ISSUE THREAD

**Issue by Maghsad** [gildas-lormeau/SingleFile#1589]
**Describe the bug**
Formerly, the Firefox SingleFile extension successfully saved all filled contents in forms, including text boxes, regardless of their size and content. Recently, it does not.

**To Reproduce**
1. Go to any page with a text box such as https://form.jotform.com/242823393058258
2. Fill the text box, e.g., section "Describe Your Feedback:*"
3. Save as SignleFile using the most recent version of Firefox and SingleFile extension
4. You will find the filled text box content is empty

**Expected behavior**
Formerly, Firefox SingleFile extension successfully saved the filled contents in all forms, including text boxes, regardless their size and content

**Environment**
 - OS: macOS 12.7.6
 - Browser: Firefox
 - Version: 131.0 (aarch64)

**Screenshots**

<img width="1537" alt="SingleFile" src="https://github.com/user-attachments/assets/2a4c8d5a-a938-41c9-a300-f4a5a4172f78">

**Comment by gildas-lormeau** [comment]
Thank you, I confirm there was a bug. I was able to reproduce and fix it. The fix will be available in the next version.
