### ISSUE TITLE
Download objects on URLS

### ISSUE THREAD

**Issue by lumnikemel** [gildas-lormeau/SingleFile#159]
Hi. First off, thank you for this fantastic extension. It took me a long time to stumble on it as a replacement to Scrapbook (for Chrome-based browsers).

I have SingleFile downloading every page I visit in a hierarchy of folders based on date-time. I do this, because I tend to flit through technical content, and invariably find myself needing to go back to it at some point. I use a separate program to index all the content locally.

It's missing one feature that I really need. This is not the same as Issue #7 "Why not file:/// URLs?".

Can we get SingleFile to download files like JPG, PDF, PNG, ZIP, etc, when it is the file in the URL? For instance:

- https://ak9.picdn.net/shutterstock/videos/9758339/thumb/1.jpg
This downloads find, but when opened, it's a blank page. It looks like there might be the image encoded in the source, but it doesn't display in either Chrome or Firefox. It's still in HTML format, and I would be fine if this at least displayed. I would prefer SingleFile to download the image as it's extension would dictate (ie, the above image would download as a jpeg, following the naming convention set in SingleFile).

- http://www.orimi.com/pdf-test.pdf
Again, SingleFile doesn't error out, but the PDF clearly isn't in the downloaded page. In this one, I would like to have SingleFile download the PDF.

In both cases above, PDF and JPG, SingleFile would need to allow me to view the file, and still download it. For instance, still allow me to view PDFs using the browser's pdf.js, and, in my case, download it in the background.

**Comment by gildas-lormeau** [comment]
Hi, thanks for reporting the issue. This should be fixed for images and pdf files in the version 1.9.68 I just deployed. Zip files are not displayed by the browser, they are downloaded instead. So I did not fix anything regarding this file format.

**Comment by lumnikemel** [comment]
Cool. So I updated to the new version. It now does download the images and PDF as HTML, so it meets my first need of being able to download automatically as I browse.

Is it possible to download the images and PDF as their native file-type? So, I would actually get the jpeg or pdf in my downloads folder? Maybe this could be set as an option?

**Comment by gildas-lormeau** [comment]
Well, it means I need to re-implement this feature because your new needs make obsolete the old ones. I also need to find a rule to generalize this feature to audio, video as well I guess.

**Comment by lumnikemel** [comment]
I'd be willing to help with the code if you can point me in the right direction of what I need to look at learning. I don't do web-dev for a living, but I have to read code, and I write selenium and python scripts.

**Comment by gildas-lormeau** [comment]
Honestly, today I don't know where this could be integrated. I need to think about it more...

**Comment by gildas-lormeau** [comment]
@lumnikemel I released a fork of SingleFile that produces HTML files which are also ZIP files. Maybe this could help you, cf. https://github.com/gildas-lormeau/SingleFileZ.
