### ISSUE TITLE
SingleFile shows error "SingleFile error: interrupted" when the actual problem is the lack of disk space

### ISSUE THREAD

**Issue by mpatas** [gildas-lormeau/SingleFile#1590]
**Describe the bug**
SingleFile shows error "SingleFile error: interrupted" when the actual problem is the lack of disk space. That error message is rather misleading in such a case, as "interrupted" seems to suggest that something actively interrupted the process.

**To Reproduce**
1. Make sure some disk is full.
2. Try to save some page using SingleFile in that disk.
3. See error "SingleFile error: interrupted".

**Expected behavior**
The error message could be, for example, "SingleFile error: disk full" or "SingleFile error: error while saving (possibly no space in disk)", or at least "SingleFile error: unspecified error while saving".

**Comment by gildas-lormeau** [comment]
Thank you for the feature request. Unfortunately, this is technically impossible. Extensions (and regular web pages) cannot be aware of the underlying cause of this kind of errors, maybe for privacy reasons.
