### ISSUE TITLE
Option in browser extension to maintain relative links between multiple downloaded pages

### ISSUE THREAD

**Issue by antonymilne** [gildas-lormeau/SingleFile#1591]
**Additional context (optional)**

Let me put this section upfront since I think the rest will make more sense that way!

I am a maintainer of [Vizro](https://github.com/mckinsey/vizro), an open source framework for dashboards based on [Dash](https://github.com/plotly/dash). [Here's an example dashboard](https://vizro-demo-visual-vocabulary.hf.space/) to see the sort of thing you get using Vizro/Dash.

A recurring user request, both [on Vizro](https://github.com/mckinsey/vizro/issues/587) and [on Dash](https://github.com/plotly/dash/issues/1056), is to be able to download a static HTML version of the dashboard. On Dash (much older than Vizro) this is a very long standing request that comes up year after year but has had only very partial solutions.

I only just discovered SingleFile and found that it actually solves 95% of the problem straight away, which is AMAZING 🎉 So first of all a huge thank you for this amazing tool!

**Is your feature request related to a problem? Please describe.**

Vizro and Dash dashboards are typically multipage. We link between these pages with relative links, e.g. 
```
<a href="/correlation/bubble">...</a>
```

When I download a page these links become absolute, e.g.
```
<a href="https://vizro-demo-visual-vocabulary.hf.space/correlation/bubble">...</a>
```

**Describe the solution you'd like**

I'd like to be able to download a whole dashboard with multiple pages and maintain the relative links between pages. I can already batch save URLs, and the extension options give a huge amount of control and flexibility but unfortunately not this.

I see that similar things have been discussed before but it was quite a long time ago, and I imagine things might have changed since then e.g. https://github.com/gildas-lormeau/SingleFile/issues/106

No doubt there are lots of different options and complexities and edge-cases here to figure out exactly what the option should be and when it should do the link replacement. For me, a solution that would get 99% of the way there would just be a box that you could tick when you do a batch download from the browser that says "do not replace relative links between these pages".

If this were possible then it would be a hugely helpful for Dash and Vizro 🙏 

**Describe alternatives you've considered (optional)**

Something similar to this appears to be possible using `crawl-replace-url` and the CLI - see e.g. 
https://github.com/gildas-lormeau/SingleFile/issues/576
https://github.com/gildas-lormeau/SingleFile/issues/532

Unfortunately this is not feasible for us since:
* it's very difficult to get an executable approved in an enterprise setting compared to installing a browser extension
* it's less user friendly for someone non-technical who just wants to download a dashboard. For Vizro and Dash, many users of the download functionality would just not have technical expertise to install and use CLI

These options are useful for crawling a website. That would be useful for Vizro and Dash so that you could somehow just instruct SingleFile _from the browser_ to "save whole dashboard" with a single dashboard page open, and it would only follow relative links and save those. This would avoid going through the batch URL save route so would be even simpler and more user-friendly. My guess from reading previous issues is that it's more complex to implement, maybe beyond the scope of the browser extension, and doing the batch URL is good enough for our needs, so I thought I'd start with that suggestion anyway. If it turns out there's a more natural way to solve this that means users don't need to copy and paste the URL of every page of the dashboard into the batch download window then even better of course! I don't think we need all the power of the CLI exposed in the browser extension here, but if somehow it were possible to enable this functionality it would be awesome 🙏

**Comment by gildas-lormeau** [comment]
Thank you for the feature request. This should be more or less possible by setting the hidden option `resolveLinks` to `false` (see https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options) and setting the filename template value to `{url-pathname}`. However, this will not save pages with the `.html` extension. This could be solved with a userscript which would rewrite all the links to add the extension though, before saving the page.

**Comment by antonymilne** [comment]
Thank you very much for the hints! I didn't realise there were all those hidden options and the possibility of user scripts - that's super cool and makes it very flexible and powerful.

Is it possible in the user script to access the file format extension? I looked through what's available in the `detail` property since it feels like it should be there but didn't see it anywhere?

So it looks like the full flow for a dashboard user would be:
1. Install SingleFile and user scripts extension
2. Turn on developer mode
3. Export settings, modify json to set `resolveLinks` and `userScriptEnabled`, import modified settings
4. Set filename template to `{url-pathname}`
5. Import a user script to rewrite the links
6. Run batch save on every URL of the dashboard

This is already a huge step forward compared to the current solution 💯 But I'm wondering how far we can push it. I'd basically like to make it as much "point and click" as possible for a non-technical dashboard user. The ideal flow would be something like this:
1. Install SingleFile
2. Dashboard itself has a button that would supply all the URLs on the dashboard that should be saved and the options
3. User clicks this button and SingleFile saves all the supplied URLs according to the provided options

Do you have any ideas for how we could make the journey here somewhere closer to this ideal? e.g. I see that I could provide a SingleFile options file for the user to import rather than them having to do it manually which simplifies the process a bit, but I fear it's still too many manual steps for most people.

(Apologies if this is very naive or way outside the scope of SingleFile - I'm a Python developer and know very little about Chrome extensions! This morning was the first time I ever ran a user script, and the vast majority of our users would be the same... So if there are other tools you think would be more suitable here then please do say!)

**Comment by ilker-binzet** [comment]
> Thank you very much for the hints! I didn't realise there were all those hidden options and the possibility of user scripts - that's super cool and makes it very flexible and powerful.
> 
> Is it possible in the user script to access the file format extension? I looked through what's available in the `detail` property since it feels like it should be there but didn't see it anywhere?
> 
> So it looks like the full flow for a dashboard user would be:
> 
> 1. Install SingleFile and user scripts extension
> 2. Turn on developer mode
> 3. Export settings, modify json to set `resolveLinks` and `userScriptEnabled`, import modified settings
> 4. Set filename template to `{url-pathname}`
> 5. Import a user script to rewrite the links
> 6. Run batch save on every URL of the dashboard
> 
> This is already a huge step forward compared to the current solution 💯 But I'm wondering how far we can push it. I'd basically like to make it as much "point and click" as possible for a non-technical dashboard user. The ideal flow would be something like this:
> 
> 1. Install SingleFile
> 2. Dashboard itself has a button that would supply all the URLs on the dashboard that should be saved and the options
> 3. User clicks this button and SingleFile saves all the supplied URLs according to the provided options
> 
> Do you have any ideas for how we could make the journey here somewhere closer to this ideal? e.g. I see that I could provide a SingleFile options file for the user to import rather than them having to do it manually which simplifies the process a bit, but I fear it's still too many manual steps for most people.
> 
> (Apologies if this is very naive or way outside the scope of SingleFile - I'm a Python developer and know very little about Chrome extensions! This morning was the first time I ever ran a user script, and the vast majority of our users would be the same... So if there are other tools you think would be more suitable here then please do say!)

Hi there! Can you share your SingleFile Settings file?

**Comment by antonymilne** [comment]
Hi @ilker-binzet, here's the relevant settings that I used. I'm curious why you're interested in this - are you also trying to export a Dash/Vizro dashboard?
```
      "filenameTemplate": "{url-pathname}",
      "userScriptEnabled": true,
      "resolveLinks": false,
```

@gildas-lormeau just wondering whether you had any more thoughts on the above? 🙏

**Comment by ilker-binzet** [comment]
> Hi @ilker-binzet, here's the relevant settings that I used. I'm curious why you're interested in this - are you also trying to export a Dash/Vizro dashboard?
> 
> ```
>       "filenameTemplate": "{url-pathname}",
>       "userScriptEnabled": true,
>       "resolveLinks": false,
> ```
> 
> @gildas-lormeau just wondering whether you had any more thoughts on the above? 🙏

Yes, I'm interested in exporting the Dash dashboard. Thanks for the settings you provided! These settings include using the pathname of the page URL as the filename, enabling user scripts and disabling link resolutions. Do you have any other advice or tips on this?

**Comment by gildas-lormeau** [comment]
@antonymilne Sorry for the late response. To avoid security problems, I prefer to avoid letting a web page drive SingleFile. So, I think the most realistic solution would be to fork SingleFile and adapt it for your use case. That way, you could integrate the userscript into the extension and activate the required options.

**Comment by antonymilne** [comment]
@ilker-binzet 
> Yes, I'm interested in exporting the Dash dashboard. Thanks for the settings you provided! Actually, These settings include using the pathname of the page URL as the filename, enabling user scripts and disabling link resolutions. Do you have any other advice or tips on this?

No other tips yet I'm afraid, but I'll let you know by posting on the Vizro/Dash issues if that changes! 

@gildas-lormeau 
> @antonymilne Sorry for the late response. To avoid security problems, I prefer to avoid letting a web page drive SingleFile. So, I think the most realistic solution would be to fork SingleFile and adapt it for your use case. That way, you could integrate the userscript into the extension and activate the required options.

No worries, thank you very much for your advice and for all your amazing work on this 🙏

**Comment by gildas-lormeau** [comment]
@antonymilne Note that I can help you to fork SingleFile if necessary since the changes are quite easy to apply.

**Comment by antonymilne** [comment]
Amazing, thank you very much @gildas-lormeau! 🙏 I am just pausing work on this for now but will definitely let you know if I need help with it in future.
