### ISSUE TITLE
Support for Partial Page Save

### ISSUE THREAD

**Issue by pandayummy** [gildas-lormeau/SingleFile#1592]
Can you absorb this project into yours?

https://github.com/mika-cn/maoxian-web-clipper

Select part of the page and save it as single html file.

![mx-wc-focus-mode](https://github.com/user-attachments/assets/2a63faf6-94ed-490d-88e2-b5a5e0cdcea8)

**Comment by gildas-lormeau** [comment]
You can select `SingleFile > Save selection` in the context menu of the page for this. You can also use the annotation editor for a more advanced usage.

**Comment by pandayummy** [comment]
WOW, never noticed that function in context menu!
Thank you!
