### ISSUE TITLE
Text missing from boxes from sed.js.org

### ISSUE THREAD

**Issue by fekir** [gildas-lormeau/SingleFile#1598]
**Describe the bug**

Try to save locally https://sed.js.org/?snippet=k7kgq5, the saved page does not contain the text contained in the text boxes

**To Reproduce**
1. Go to https://sed.js.org/?snippet=k7kgq5 (or to https://sed.js.org directly)
2. Click on the firefox extension for downloading the page
3. Open the downloaded file in Firefox
4. See the difference

**Expected behavior**

The text in the text boxes should not be missing.

**Screenshots**
original page

![image](https://github.com/user-attachments/assets/865dc0aa-d6a4-447e-a6d1-7adcd484d41c)

downloaded page

![image](https://github.com/user-attachments/assets/f18e90dc-892f-40d4-a58d-1d679a51e056)

**Environment**
 - OS: Debian Bookworm
 - Browser: Firefox
 - Version: 128.3.1esr

**Additional context**

**Comment by gildas-lormeau** [comment]
Thank you for the full report. Actually, this issue is fixed in the version 1.22.72 which should be available for download on the Mozilla store in the coming days (review in progress).
