### ISSUE TITLE
WARC support

### ISSUE THREAD

**Issue by samatjain** [gildas-lormeau/SingleFile#160]
Any plans to support WARC (Web ARChive) as an output format over MAFF?

Refs:

 * https://en.wikipedia.org/wiki/Web_ARChive
 * https://www.archiveteam.org/index.php?title=The_WARC_Ecosystem
 * https://iipc.github.io/warc-specifications/

**Comment by gildas-lormeau** [comment]
Today, it's not planned. The biggest issue with WARC is that Chrome or Firefox don't offer a way to integrate a WARC viewer seamlessly. It means for example that double-clicking on a warc file in your file explorer wouldn't open the browser to view the page. Opening the file or drag'n dropping the file wouldn't work any better, you would see the browser downloading the file instead. So, the user experience would be quite bad from my point of view.

**Comment by gildas-lormeau** [comment]
I close this bug as "won't fix" because browsers don't offer a way to handle WARC files reading.
