### ISSUE TITLE
Include the readability metadata into the saved file

### ISSUE THREAD

**Issue by jarofromel** [gildas-lormeau/SingleFile#1604]
**Is your feature request related to a problem? Please describe.**

There is no stable set of metadata in the files saved with SingleFile.

**Describe the solution you'd like**

Include the metadata which Mozilla Readability library tries to provide.

**Describe alternatives you've considered (optional)**

I query and normalize `<meta elements` by myself or I run readability library elsewhere and I combine its results with SingleFile html.

**Additional context (optional)**

Mozilla Readability library is applied when the button `Format the page for better readability` is applied. It would be nice to include the metadata which the readability library tries to normalize into the saved file as well.
By metadata I mean the [following fields](https://github.com/mozilla/readability?tab=readme-ov-file#parse) coming from the readability:
* `length`: length of an article, in characters;
* `excerpt`: article description, or short excerpt from the content;
* `byline`: author metadata;
* `dir`: content direction;
* `siteName`: name of the site;
* `lang`: content language;
* `publishedTime`: published time;

These metadata are already included in the SingleFile output but dispersed over the different `<meta elements` (below). Readability tries to normalize these and provides them in the stable way. It is also more complete -> sometimes I find that some metadata are not in the `<meta elements` of the SingleFile output but it is available in the readability metadata (cross-checked in the browser) ->  the reason is likely that the readability uses other ways to get metadata than `<meta elements` (ld-json).
```
<meta name=....
<meta property=og:....
<meta name=twitter:.... 
<meta property=article:......
```

(My) usecase: I read, then save some interesting pages with SingleFile in the readable form, then I do monthly report where I query the metadata (author, sitename, excerpt).

I am not sure what would be the optimal way of inclusion. Maybe new `<meta name=readability.{field} content={...} >`.

By the way, thanks a lot for an excellent addon it makes my digital life easier.

**Comment by jarofromel** [comment]
This seems to me as a better way of including metadata to SingleFile output (than meta elements).
```
<script id="readability-metadata" type="application/json">
{
    "length": 250,
    "excerpt": "article description, or short excerpt from the content",
    "byline": "Johny Doe",
    "dir": null,
    "siteName": "Doe",
    "lang": "en",
    "publishedTime": "2022-01-06T10:00:03.134Z"
}
</script>
```

**Comment by gildas-lormeau** [comment]
Thank you very much for the suggestion. I agree it's a good idea so I have implemented it. This feature will be available in the next version.

**Comment by jarofromel** [comment]
You are fast :). I just started with simple pull request but your solution is of course better. I will check it to learn something new.
Thanks a lot for accepting the suggestion and your time to implemented it.

```
// add to lib/single-file-extension-editor.s
// ---------- readability metadata trial 
      const { content, textContent, ... metajson} =  article
      const metajsonElement = document.createElement("script");
      metajsonElement.type = "application/json";
      metajsonElement.textContent = JSON.stringify(metajson)
      document.head.appendChild(metajsonElement)
//-----------
```

**Comment by gildas-lormeau** [comment]
Thanks for the feedback, my solution is very similar to yours, rest assured. ;)
