### ISSUE TITLE
Text color changed

### ISSUE THREAD

**Issue by BloodlineL** [gildas-lormeau/SingleFile#1607]
Original color: 
![001](https://github.com/user-attachments/assets/a6af1c46-b428-4559-aef0-aee03b19dd9e)
![004](https://github.com/user-attachments/assets/d576c94a-44e6-4c5f-9d02-236020a1a202)
Colors in saved file: 
![003](https://github.com/user-attachments/assets/cc40c3c2-82b6-4ddd-9aba-5b55a76e9646)
![002](https://github.com/user-attachments/assets/30d347d9-1b9a-42b9-8748-6560d001a984)
The URL where the problem occurs is <https://adoyle.me/blog/why-zip-file-checksum-changed.html>

**Comment by gildas-lormeau** [comment]
Thank you for the detailed report, I was able to reproduce and fix the issue. The fix will be available in the next version. You can circumvent the issue meanwhile by disabling the option `Stylesheets > remove unused styles` in SingleFile.
