### ISSUE TITLE
add redirect to infobar?

### ISSUE THREAD

**Issue by jacobmgreer** [gildas-lormeau/SingleFile#1608]
**Is your feature request related to a problem? Please describe.**
When batch saving URLs, some URLs will redirect to another url.

**Describe the solution you'd like**
It would be nice to pass the originally requested URL to the infobar. This would help reconcile which URLs are being redirected.

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. The original URL will be available via the template variable `{url-original}` in the next version.
