### ISSUE TITLE
Filename template data (tag <script data-single-file-options>) is missing in the files where readability was used

### ISSUE THREAD

**Issue by jarofromel** [gildas-lormeau/SingleFile#1609]
**Describe the bug**

The tag `<script type=application/json data-single-file-options>`  which keeps the filename template data is missing in the files which were saved with the readablity option in spite of the active option `File name/ save the filename template data into the page`.

**To Reproduce**
1. Make active the option `File name/ save the filename template data into the page`
2. Open a page in the SingleFile annotation editor
3. Apply the 'Format the page for better readability"
4. Save the file
5. Inspect the file. The tag `<script type=application/json data-single-file-options>` is missing.

**Expected behavior**

The tag `<script type=application/json data-single-file-options>` exists in the file.

**Environment**
 - OS: Linux, Ubuntu 20.04 
 - Browser: Firefox 132, Firefox Developer Edition
 - Version: 1.22.72

**Additional context**
The described tag is missing. Also I'like to ask (if you don't mind) why this tag is placed into the body of html file instead of the head - that's just my curiosity because I am not a Front-Dev.

**Comment by gildas-lormeau** [comment]
Thank you for the report. I've just fixed the issue. The fix will be available in the next version. Regarding the position of the tag in the page, I must confess I don't know why I included it in the body instead of the head tag. Even if it's valid, I agree that inserting it in the head would perhaps be preferable.
