### ISSUE TITLE
writing notes BEFORE or AFTER saving a page 

### ISSUE THREAD

**Issue by gbbzzz** [gildas-lormeau/SingleFile#161]
Ok ...
Nice addon for saving a web page into a single file ... for later usage.

Hopefully, an *.html file will always be ready to be opened, even several years later, not as with ".mht format and for instance the addon "SAVE PAGE WE".

But is there a way to "NOTE" (ie : highlight somme text + write a note) BEFORE or/and AFTER saving ?

I would be really grateful for any solution ...

**Comment by gildas-lormeau** [comment]
Today, you can customize the data appearing the infobar which is displayed when viewing an archive. For this, check the option "user interface > open a prompt dialog to edit the infobar content". Whis this option enabled, SingleFile opens a prompt dialog just before saving the page allowing you to insert notes related to the saved page.

**Comment by gildas-lormeau** [comment]
I know this feature is rather limited. I also think it would be nice to have a feature allowing users to annotate the document with notes.

**Comment by gildas-lormeau** [comment]
Out of curiosity, do you think the notations should follow the web annotation specs defined by the W3C? cf. https://w3c.github.io/web-annotation/serialization-html-note/index-respec.html

**Comment by gildas-lormeau** [comment]
This feature will be available in the version 1.12.0 soon.
