### ISSUE TITLE
[FR] Use full-width symbols to replace invalid file name characters

### ISSUE THREAD

**Issue by adan89lion** [gildas-lormeau/SingleFile#1614]
**Is your feature request related to a problem? Please describe.**

Most filesystems do not allow special characters such as `/`, `?`, `*`, `:`, etc... As a result, files downloaded using SingleFile often end up with numerous underscores (`_`). While manual renaming is possible, it would be very time-consuming.

**Describe the solution you'd like**

Virtually all full-width special characters are support by most filesystems. SingleFile can convert illegal characters into their full-width counterparts as an option under `Options` → `File name`.

For example:
Replace `:` with `：`; `?` with `？`, instead of the predefined `_`.

It's more elegant, and easier for file management.

**Comment by gildas-lormeau** [comment]
Thank you very much for the suggestion! I totally agree with you. This will be implemented in the next version.

**Comment by vertis** [comment]
This has just broken everyone else's naming conventions between versions. It doesn't make sense to me that the slugified version of the URL would have full width characters

**Comment by gildas-lormeau** [comment]
@vertis you can revert these changes or choose your own characters in the version 1.2.74 by editing the value of the hidden option `filenameReplacementCharacters`, see https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options.

**Comment by Codereamp** [comment]
Just to mention an issue that this solution may pose to ones using console windows in Windows. I mentioned Consolas in [the discussion](https://github.com/gildas-lormeau/SingleFile/discussions/1632), but all other mono spaced fonts available for console windows also don't render them in Windows 10. At the screen the question marks in squares is colons replaced with full-width colons

<img src="https://github.com/user-attachments/assets/9360a937-1893-42d6-bfbd-5c2d76a3694a" width="600">

**Comment by redactedscribe** [comment]
<img width="1013" height="80" alt="Image" src="https://github.com/user-attachments/assets/8d8da32b-da7e-4ce8-9341-bb361e062dc5" />

I only just found out that this change had been made and my first thought was that this was a bug and came here to report it. The screenshot above showing the replacement character option makes no mention of common invalid filename characters being automatically replaced by faux equivalent characters -- which it should. E.g. "Common invalid characters will be replaced by full-width equivalent characters. For any others, the following character will be used to replace them."

I personally do not like these characters at all (ugly rendering, cannot be typed, terminal issues) and would prefer to use `_` (underscore) for all invalid characters as had been done by the extension up until this change. I can modify the [hidden option](https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options) `filenameReplacementCharacters` to overcome this, but if any others are added by the extension at a later date, I will have to be aware of those changes and edit the JSON each time.

I think this option feature should be split into two: The current option as it was (replace all invalids by the specified character), and add a sub-option which enables the automatic replacement of common invalid characters with full-width equivalents. Basically a simple toggle to enable this new behaviour or not.

**Comment by gildas-lormeau** [comment]
If it reassures you, it is highly unlikely that `filenameReplacementCharacters` will change in the future. The problem is that the options page must allow these characters to be edited.

**Comment by user-1-2-3-4-5** [comment]
To prevent the full-width characters from being used, does making the following change restore the original behaviour?

from the exported file:

      "filenameReplacementCharacters": [
        "～",
        "＋",
        "？",
        "％",
        "＊",
        "：",
        "｜",
        "＂",
        "＜",
        "＞",
        "＼"
      ],

modified to:

      "filenameReplacementCharacters": [
        "_"
      ],

---

I want a Unix-, terminal-friendly filename template.

**Comment by user-1-2-3-4-5** [comment]
I removed these problematic characters from existing filenames with Perl rename `prename` on Linux — `cd` into your Singlefile webpages folder and run:

    prename --dry-run --verbose 's/～/-/g' *

Remove the `--dry-run` flag after you've inspected the output. The sample substitution replaces `～` with `-`, and characters can also by removed entirely be leaving the second blank:

    prename --dry-run --verbose 's/＜//g' *
