### ISSUE TITLE
Sub folders in file name do not work in Safari

### ISSUE THREAD

**Issue by th** [gildas-lormeau/SingleFile#1619]
**Describe the bug**

I have set file name in SingleFile Safari Extension's settings dialog to SingleFile/%if-empty<{page-title}|No title> ({date-locale} {time-locale}).{filename-extension}

The Single File folder exists in Safari's Downloads folder.

Unfortunately the slash is replaced by "undefined" and the file is saved in the Downloads folder itself, not the SingleFile subdirectory.

**To Reproduce**
1. Set file name to SingleFile/%if-empty<{page-title}|No title> ({date-locale} {time-locale}).{filename-extension}
2. Browse to www.github.com
3. Activate the Safari extension
4. There is a file Downloads/SingleFileundefinedGitHub (14.11.2024 10：23：34).html

**Expected behavior**
A file Downloads/SingleFile/GitHub (14.11.2024 10：23：34).html

**Screenshots**

**Environment**
 - OS: Mac OS X Sequoia 15.1
 - Browser: Safari
 - Version: 18.1

**Additional context**

**Comment by gildas-lormeau** [comment]
I confirm this is unfortunately a limitation of Safari. This issue is related to the fact that the [`downloads`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads) API is not available in Safari.
