### ISSUE TITLE
Page can't be saved - add explanation

### ISSUE THREAD

**Issue by jumapico** [gildas-lormeau/SingleFile#162]
The following page can't be saved: https://support.mozilla.org/en-US/kb/moving-thunderbird-data-to-a-new-computer

The icon of SingleFile show as `disabled` but no explanation is found about the cause that the page can't be saved.

Maybe is a good feature the indication of why SingleFile can't save the page.
Also, i hope for pages in support.mozilla.org can be saved in the future.

P.D.: Thanks for your work! SingleFile is very useful.

**Comment by gildas-lormeau** [comment]
You're right, this needs to be improved. For your information, Firefox does not allow extensions to run extensions on this domain. I think there are 2 fixes to implement:
 - add an error message in the tooltip
 - allow this domain to be saved on Chrome

**Comment by gildas-lormeau** [comment]
I added a new icon state to try fixing this issue. Now a "🛇" will be displayed when you cannot save page. The tooltip also says the page cannot be saved. Finally, I also updated the "Know issues" in the README.MD file. That's the best I can do without requesting additional permissions.

**Comment by jumapico** [comment]
That was fast!
Thanks for the improvement and also thanks for your work in this great add-on.

**Comment by gildas-lormeau** [comment]
You're welcome!
