### ISSUE TITLE
Annotation editor doesn't appear when reloading a saved file

### ISSUE THREAD

**Issue by notuntoward** [gildas-lormeau/SingleFile#1621]
I have `open pages saved with SingleFile in the annotation editor` checked but when I open a saved html file that I've annotated, the annotation editor is not displayed.  Up until just recently, annotation editor opening worked every time -- I used it a lot to re-annotate saved web pages.

**To Reproduce**

1. Activate these singlefile settings:
![image](https://github.com/user-attachments/assets/9086fc08-a256-4c21-82d2-fb42a8b3b67a)

2. In Brave, visit any page, say [this page](https://www.washingtonpost.com/science/2024/11/14/chatgpt-ai-poetry-study-creative/?carta-url=https%3A%2F%2Fs2.washingtonpost.com%2Fcar-ln-tr%2F3fa3bf8%2F67362b19b922210df756df4d%2F598abab5ae7e8a68162503f0%2F25%2F57%2F67362b19b922210df756df4d).

3. Highlight some text and save the annotated page using the annotation toolbar

3. Go to Windows Explorer and click on the saved .html file

**Expected behavior**
I'd expect to see the annotation toolbar upon opening the saved .html.

**Environment**
Brave Version 1.73.89 Chromium: 131.0.6778.69 (Official Build) (arm64) and Windows 11
Here are my complete settings: [singlefile-settings-2024-11-14T20_00_28.600Z.json.txt](https://github.com/user-attachments/files/17757129/singlefile-settings-2024-11-14T20_00_28.600Z.json.txt)

**Comment by gildas-lormeau** [comment]
You have to enable the option `Allow access to file URLs` in the extension page.

**Comment by notuntoward** [comment]
Thanks!  Not sure how I changed that...
