### ISSUE TITLE
Annotate any html file with SingleFile annotation editor

### ISSUE THREAD

**Issue by notuntoward** [gildas-lormeau/SingleFile#1622]
**Is your feature request related to a problem? Please describe.**

Zotero is a convenient way to save and organize web page .html files, and to associate them with their metadata and any comments.  I would like to be able to annotate zotero's html snapshots with the SingleFile annotation editor -- zotero files and any other html files.

**Describe the solution you'd like**
When I right click on the SingleFile browser icon, I'd like to see an "annotate file" menu item.  If the current tab already contains an local html file, then it would bring up the annotation editor.  Otherwise, it would load the file first and then bring up the annotation editor.

**Describe alternatives you've considered (optional)**
- Just zotero's own internal html file annotator
   - but these annotations aren't stored in the html file itself, but in a separate database
     - So, my colleagues can't see my annotations unless they start using zotero.
     - But they all have web browsers
- Saving web pages as pdfs, where annotations are portable
  - I can annotate them in SingleFile and then save as pdf
  - or save and annotate web page pdfs in other ways
  - But this isn't ideal
     - it's many extra steps:
       - zotero already automatically saves web page html files, and puts them in the correct location
       - it does this all in one click
    - converting to pdf sometimes scrambles complex web pages

**Additional context (optional)**
At one point I think there was a SingleFile restriction preventing it from saving to anywhere but a downloads folder. SingleFile had a workaround that involved running a separate filesaver process, I think.  

Maybe this process could handle not-download-folder part of the html file annotating I'm requesting?  But ideally SingleFile wouldn't wouldn't need to do this -- I never managed to get that process to work on a Windows 11 computer.

Finally at the moment, I can't get the annotator to open on files written by SingleFile either: #1621

**Comment by gildas-lormeau** [comment]
For your information, Zotero uses SingleFile under the hood to save snapshots. Doesn't it provide an annotation editor?

**Comment by notuntoward** [comment]
Yes, it does annotate but the problem is that the annotations aren't visible outside of zotero.  

If I mark up an html file and send it to somebody, that somebody can't see the markups without installing Zotero.  Same thing if I view it obsidian, where I do most of my writing.

PDFs are handled the same way in zotero, which is why I mark them up using an external pdf annotator.

**Comment by gildas-lormeau** [comment]
You should be able to save files in any directory on your disk by installing SingleFile Companion Lite, see https://github.com/gildas-lormeau/single-file-companion-lite.

**Comment by notuntoward** [comment]
What I'm missing is not saving files but opening them.  

The SingleFile annotator pops up in my browser whenever I open a .html that was created by SingleFile.  If I open a file created by Zotero, the annotator doesn't pop up.  This means that I can't annotate Zotero's .html using SingleFile.

**Comment by gildas-lormeau** [comment]
I cannot reproduce this issue actually. I installed Zotero on my machine, I saved https://example.com/, I opened the saved file in Firefox, and I can annotate the saved page with SingleFile without any particular issue. FYI, SingleFile verifies the presence of the comment node `<!-- Page saved with SingleFile ... -->` in the saved page to determine if the annotation editor can open it. Do you confirm you see this comment at the top of the HTML source of a saved page?

**Comment by notuntoward** [comment]
You're right!  I've been reconfiguring my zotero setup lately, and now I can't reproduce this either.  Was I looking at the wrong .html files?  

Thanks for your thoroughness, and for this great tool. I apologize for wasting your time.

**Comment by gildas-lormeau** [comment]
No problem, thank you for your feedback!
