### ISSUE TITLE
How do I revert back to the old file naming scheme

### ISSUE THREAD

**Issue by rauzaen** [gildas-lormeau/SingleFile#1624]
Earlier file title - Max Films 2024_ Sunkissed Land (1983) - watch and download [1813MB] at max.io (11_18_2024 3_04_36 PM)
Newer file title - Max Films 2024： Sunkissed Land (1983) - watch and download [1813MB] at max.io (11_18_2024 3：04：36 PM)

How to do go back to old naming scheme as default for future files as the newer one messes up the organization from my previously saved files.

**Comment by gildas-lormeau** [comment]
You can replace `：` with `_` in the hidden option `filenameReplacementCharacters`, see https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options.

**Comment by rauzaen** [comment]
I tried making changes in the JSON but still can't get them to import.

**Comment by gildas-lormeau** [comment]
@rauzaen What browser are you using?

**Comment by rauzaen** [comment]
Opera Browser v95.0.4635.84 on W8.1 using SingleFile v1.22.73
I also tried importing a previously saved settings file but it made no difference.

**Comment by rauzaen** [comment]
I think the older version replaced all special characters with `_` but the newer version does not. And while this make sense, I just simply prefer the old naming scheme for consistency purposes.
