### ISSUE TITLE
Changed naming scheme should be described in the Help page

### ISSUE THREAD

**Issue by jarofromel** [gildas-lormeau/SingleFile#1625]
**Describe the bug**
My filename scheme is `{datetime-iso}--%if-empty<{url-last-segment}|no-title>.{filename-extension}`. I noticed last version of SF produces this `2024-11-20T15：43：56.919Z` while previous version produced  `2024-11-20T15_43_56.919Z`.  Help page does not mention the new format.

**Additional context**

Based on the #1624 I guess the intention is to have `colon` as the divider in the time part. But the Help page still mentions old format with `underscore`. 
As a side note to keep the old behavior I use this (maybe someone finds it useful).
`%replace<{datetime-iso}|:|_>--%if-empty<{url-last-segment}|no-title>.{filename-extension}`

**Comment by jarofromel** [comment]
Also the file with the new naming scheme was written to my desktop (Firefox 132.02, Ubuntu 20.04) as `2024-11-20T15：43：56.919Z`. So instead of the `colon` (`:`, 0x3A) the `full width colon` (`：`,  0xFF1A) is used.
I am not sure if it is intended behavior because in the replace function above I use just normal colon `:` and it works.

**Comment by gildas-lormeau** [comment]
Thank you for the reminder! I will update the documentation, the workaround you proposed is OK. It works because the template is applied before invalid characters are replaced. For the record, you'll be able to replace `"："` with `"_"` of the `"filenameReplacementCharacters"` array in the version 1.2.74 that I've just submitted.

**Comment by vertis** [comment]
I appreciate everything you do (for free!!) but this is a very annoying breaking change. How many of the other characters that were previously _ are now some other unicode version in:

```
      "filenameReplacementCharacters": [
        "～",
        "＋",
        "？",
        "％",
        "＊",
        "_", // already fixed
        "｜",
        "＂",
        "＜",
        "＞",
        "＼"
      ],
```

I want my naming to be consistent to what it was previously.

**Comment by vertis** [comment]
NM, I think it's just all of them and I've now set them back to what they were before.

**Comment by rauzaen** [comment]
Sorry but can someone help me out. I want to change all the newer characters to `_` like how it was before the update.

**Comment by gildas-lormeau** [comment]
@rauzaen Replace:
```
"filenameReplacementCharacters": ["～", "＋", "？", "％", "＊", "：", "｜", "＂", "＜", "＞", "＼"],
```
with:
```
"filenameReplacementCharacters": ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
```

**Comment by rauzaen** [comment]
Thanks. Got it working.
