### ISSUE TITLE
lookup fields get reset while SingeFile runs

### ISSUE THREAD

**Issue by Subnum12** [gildas-lormeau/SingleFile#1627]
**Describe the bug**
lookup fields get reset while SingeFile runs.

**To Reproduce**
1. Go to https://www.ebay.de/itm/134581579769
2. modify tax to 19% 
![grafik](https://github.com/user-attachments/assets/c946b2d3-46f3-439d-9957-dbe8eb4527b3)
3. run SingeFile 
4. before SingeFile starts, lookup will be reset to 0% tax
![grafik](https://github.com/user-attachments/assets/f14bd85f-bec1-44a3-8a7a-4576c42a2641)

**Expected behavior**
the page should not be modified by SingeFile 

**Environment**
 - OS: Win10 Pro
 - Browser: Firefox 132.0.
 - Version: 64
 - SingeFile version 1.22.73

**Comment by Subnum12** [comment]
reproduce not possible anymore

**Comment by gildas-lormeau** [comment]
In fact, I studied the bug quite closely. it still exists (I can reproduce in Chrome) and is an unfortunate side effect of the option `Images > save deferred images`. To get around it, you can:
 - disable the option `Images > save deferred images` or,
 - activate the or option `Images > save deferred images > zoom out the page`,
 - scroll to the bottom of the page and save it
