### ISSUE TITLE
Content is not visible in saved https://store.google.com/magazine/compare_cameras?hl=en-US&pli=1

### ISSUE THREAD

**Issue by jrmuizel** [gildas-lormeau/SingleFile#1636]
**Describe the bug**
After saving https://store.google.com/magazine/compare_cameras?hl=en-US&pli=1 the resulting file seems to have a lot of the content but it isn't visible. The page appears to be using webcomponents/shadow DOM so that could be related to the cause. The content doesn't show up in either Chrome or Firefox when saved with both Chrome and Firefox

**To Reproduce**
1. https://store.google.com/magazine/compare_cameras?hl=en-US&pli=1
2. Save the page
3. Load the result

**Expected behavior**
The content should be there.

**Screenshots**
<img width="1417" alt="Screenshot 2024-12-02 at 10 29 11 AM" src="https://github.com/user-attachments/assets/9455940c-e910-4d67-8a2e-f191b1fa2b26">

**Environment**
 - OS: macOS
 - Browser: Chrome and Firefox

**Comment by gildas-lormeau** [comment]
Thank you, I confirm I can reproduce the issue and that it is probably related to the Shadow DOM. 

FYI, you can circumvent  this issue today by choosing the "self-extracting ZIP (universal)" file format. I'll have to find out why, for the moment it's quite mysterious...

**Comment by gildas-lormeau** [comment]
In the end, the issue wasn't so hard to find, I must have been a bit tired last time. The fix will be available in the next version. For the record, it was related to the usage of the [":defined"](https://developer.mozilla.org/en-US/docs/Web/CSS/:defined) pseudo class.
