### ISSUE TITLE
SingleFile blocks website

### ISSUE THREAD

**Issue by nomennescio32** [gildas-lormeau/SingleFile#164]
Windows (any)/Firefox 65.0.2 (64-bit).
Go to abnamro.nl/ and check "Login" or "Inloggen", depends on the language the screen comes up with.
Now a login screen should appear. But only so with SingleFile disabled.

I tried about everything possible to change this behaviour and changed options as far as I understand their meaning and would like to know an insider's view on this.

**Comment by gildas-lormeau** [comment]
Thank you very much for reporting the issue. It is fixed in the version 1.9.75.
