### ISSUE TITLE
SingleFile replaces vertical bar | in page title with double quotes when saving file

### ISSUE THREAD

**Issue by kennethb22** [gildas-lormeau/SingleFile#1644]
**Describe the bug**

When saving a page with a vertical bar |, SingleFile replaces the | with a double quote character. It does this regardless of what the "Replacement Character" in Options -> File Name is set to. 

**To Reproduce**
1. In SingleFile Settings, under File Name, set the template to {page-title}
2. Go to the following link: https://thelampmagazine.com/issues/issue-26/the-one-hundred-pages-strategy
3. Save the page using SingleFile
4. The file is named "The Lamp " The One Hundred Pages Strategy"

**Expected behavior**
The file should be named "The Lamp _ The One Hundred Pages Strategy" if the "Replacement Character" in Options -> File Name is set to the default of _.

**Screenshots**

![image](https://github.com/user-attachments/assets/e9a73785-03ac-4c02-9c0d-b14dabc46b26)
![image](https://github.com/user-attachments/assets/b1b91857-d7a5-4aef-a140-ddb0abbc9e3e)

**Environment**
 - OS: [MacOS Sonoma 14.6.1, iOS 18.1.1, iPadOS, 18.1.1]
 - Browser: [Safari, Brave, Firefox]
 - Version: [17.6, 1.73.101 Chromium: 131.0.6778.139, 133.0.3]

**Additional context**

Problem appears to occur with any page that has a vertical bar in the page title. See also: https://www.nytimes.com/2024/12/02/opinion/ignorance-knowledge-critical-thinking.html

**Comment by gildas-lormeau** [comment]
This issue is related with #1641 and #1624. What browser are you using?

**Comment by kennethb22** [comment]
SingleFile version 1.22.75 on Firefox, 1.22.76 on Brave, 1.22.76 on Safari.

**Comment by gildas-lormeau** [comment]
This bug is supposed to be fixed in the version 1.22.76. If possible, export your configuration, edit it in a text editor and tpost here the value of `filenameReplacedCharacters` and `filenameReplacementCharacters`.

**Comment by kennethb22** [comment]
```
  "filenameReplacedCharacters": [
        "~",
        "+",
        "\\\\",
        "?",
        "%",
        "*",
        ":",
        "|",
        "\"",
        "<",
        ">",
        "\u0000-\u001f",
        ""
      ],

      "filenameReplacementCharacter": "_",      
      
```

**Comment by gildas-lormeau** [comment]
Thank you, I just uploaded a new version which should fix the issue. Meanwhile, you can fix this problem manually by setting the `filenameReplacedCharacters` value to:
```
"filenameReplacedCharacters": [
        "~",
        "+",
        "?",
        "%",
        "*",
        ":",
        "|",
        "\"",
        "<",
        ">",
        "\\\\",
        "\u0000-\u001f",
        ""
      ]
```
