### ISSUE TITLE
Auto-Saving & Silent Save

### ISSUE THREAD

**Issue by vostapchenko** [gildas-lormeau/SingleFile#165]
Hello! Can you add 2 features to the "SingleFile" extension?
1. Auto-Saving the active tab after a certain period of time, for example, 5-10 seconds. Сonstantly, not only after loading.

2. Saving to the selected folder without displaying a window to confirm the saving. Those silent saving, without notice and the need for additional action by the user.

Thanks in advance!

**Comment by gildas-lormeau** [comment]
Hi,

Thanks for the suggestions.

1. I was not sure it would be needed and was waiting for someone to propose this feature. I will implement it soon. The delay will be configurable in the options page.

2. This can be done only through filename templates. You can prepend folder names in the filename template, e.g. `/auto-save/{page-title} ({date-iso} {time-locale}).html`. Unfortunately, I cannot use some kind of "Select folder" popup to let users choose a directory once for all. It's technically impossible.

**Comment by vostapchenko** [comment]
1. Yes, it is really necessary! For example, if Ajax is used to change the page, then the actual reload does not occur, and SingleFile does not save the modified page...
2. I asked about something else. Now, when autosaving, every time I see a standard Windows window with a preference, select the directory to save. I also need to save the file without any extra questions at the time of saving. Using e.g. templates / auto-save / {page-title} ({date-iso} {time-locale}). html is a good and clear option. But I could not get rid of additional questions at the time of saving the file...
PS Sorry for my English. My native language is Russian . Thank!

**Comment by gildas-lormeau** [comment]
@vostapchenko What browser are you using? Firefox or Chrome?

**Comment by vostapchenko** [comment]
I am using Google Chrome ver.72.0.3626.119

**Comment by vostapchenko** [comment]
This my setting and Window in autosave mode:
![settings](https://user-images.githubusercontent.com/48206543/53734713-d40a3a00-3e95-11e9-842f-75df9e1b2d12.PNG)
![winwindowsave](https://user-images.githubusercontent.com/48206543/53734727-da98b180-3e95-11e9-8d8d-c6838ad9e5c6.PNG)

**Comment by gildas-lormeau** [comment]
@vostapchenko Thnaks for the info. That's weird. Do you confirm the option 'сохранять страницы в фоновом режиме' is checked?

**Comment by vostapchenko** [comment]
Yes, is chec
![1](https://user-images.githubusercontent.com/48206543/53756034-2fa1eb00-3ec9-11e9-91a3-3337d76876c6.PNG)
ked

**Comment by gildas-lormeau** [comment]
@vostapchenko Thanks, can you also check if the option "Advanced settings > Downloads > Ask where to save each file before downloading" is disabled in chrome://settings?

**Comment by vostapchenko** [comment]
Wow! Thank you very much! I did not even think that this setting could affect.
Waiting for autosave with a timer :)

**Comment by gildas-lormeau** [comment]
You're welcome. I'll try to implement the timer very soon!

**Comment by gildas-lormeau** [comment]
@vostapchenko The version 1.9.77 has a new option to auto-save periodically pages.
