### ISSUE TITLE
Lost image after saving

### ISSUE THREAD

**Issue by frostblazergit** [gildas-lormeau/SingleFile#166]
**Describe the bug**
After saving, the image is lost. Try this URL:  
https://www.oracle.com/webfolder/technetwork/tutorials/obe/java/gc01/index.html
Click on "**Expand All Topics**" and save

**To Reproduce**
1. Go to 'https://www.oracle.com/webfolder/technetwork/tutorials/obe/java/gc01/index.html'
2. Click on 'Expand All Topics'
3. Save Page
4. Image loss

**Environment**
 - OS: macOS 10.14.1
 - Browser: Chrome 72.0.3626.119
 - Version: SingleFile 1.9.75

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. This will be fixed when I will deploy the new version on stores.

**Comment by gildas-lormeau** [comment]
Its fixed in the version 1.9.76.

**Comment by frostblazergit** [comment]
@gildas-lormeau 
SingleFile 1.9.77  
Working as expected is great! Thank you! 😉

**Comment by gildas-lormeau** [comment]
Great!
