### ISSUE TITLE
Tracking Pixel (collector.githubapp.com), why?

### ISSUE THREAD

**Issue by womotroll** [gildas-lormeau/SingleFile#169]
Hi,
after installing Pi-Hole on an extra Server (Raspberry pi) singlefile no longer works.
Pi-hole has blacklistet collector.githubapp.com,  for reasons of data protection. 
Whitelisting this tracking pixel site doesn't help!
For what reasons do you use this tracking pixel???

Eberhard

**Comment by gildas-lormeau** [comment]
Hi, I do not use any tracking pixel at all. What page are you trying to save?

**Comment by gildas-lormeau** [comment]
@womotroll I really need more details about this issue. It's really weird and it does not reassure.

**Comment by womotroll** [comment]
Hi,
i really don't know what's going on. In the morning, just before i open this issue, i noticed the 
query at the pi-hole server about collector..., everytime a tried to save a page.
Now, i reconfigured my PC , so the pi-hole server  will not be contacted, but the error ist still there.
Can't save any page, z.B.: 
-  https://www.kuketz-blog.de/android-ohne-google-take-back-control-teil1/
-  https://www.eike-klima-energie.eu/2019/03/05/vom-menschen-verursachte-erderwaermung-uneinigkeit-innerhalb-der-weltweiten-klimaforschung/
and so on.
I'm using win 7 , Browser: Waterfox V56.2.7.1 (64bit), Singlefile V1.9.77(updated today)
I'm using your program for a long time, and i'm very happy about it.
Another test on Ubuntu as Virtual guest with the same URLs, Waterfox (same Version), 
but Singlefile V1.9.60 works!!!
Anything i can do?
Sorry, Eberhard

**Comment by gildas-lormeau** [comment]
I'm reopening the issue because it's not fixed. Do you know which version of SingleFile introduced your issue? The version 1.9.61?

**Comment by womotroll** [comment]
Please wait, Singlefile has just now be updated to V1.9.79 and it is working again!!!
Sorry for the problems that I have caused.
 
Eberhard

**Comment by gildas-lormeau** [comment]
Ok, feel free to re-open the issue if needed.
