### ISSUE TITLE
page-title}.html

### ISSUE THREAD

**Issue by p1512654** [gildas-lormeau/SingleFile#170]
The problem with the {page-title} .html template in version 1.9.77 doesn’t save the page, sometimes it doesn’t save when you set it up, but when you restart Firefox, you’ll always save the page. In the version of SingleFile 1.9.75 there is no problem. Please correct. I really like the extension and I would like to continue using it.
I used a translator for this message.
I have Windows 7 64 bits SP1 Firefox 62 64 bits

**Comment by gildas-lormeau** [comment]
Hi @p1512654, 

Thanks for reporting the issue here ;). Can you give me an example of page you cannot save?

**Comment by gildas-lormeau** [comment]
The strange thing is that I did not change any code related to the filename since the version 1.9.75...

**Comment by p1512654** [comment]
https://b.radikal.ru/b24/1903/35/b14bbfebd5f3.jpg The problem in version 1.9.78 remains

**Comment by p1512654** [comment]
https://github.com/gildas-lormeau/SingleFile/issues/170 - does not allow to save

**Comment by gildas-lormeau** [comment]
That's weird, I cannot reproduce the issue. Did you try to reset your options? For example, the correct value for the filename template id `{page-title}.html ` (with a leading `{`)

**Comment by gildas-lormeau** [comment]
@p1512654 Good news, I can reproduce the issue. It happens when "remove frames" is enabled. I'll deploy a new version very soon.

**Comment by p1512654** [comment]
Yes you are right thank you

**Comment by gildas-lormeau** [comment]
@p1512654 I just published the version 1.9.79 which should fix this regression. I'm sorry for the inconvenience. Please confirm it's okay on your end.

**Comment by p1512654** [comment]
Yes, everything is fine in version 1.9.79 thank you very much

**Comment by gildas-lormeau** [comment]
You're welcome! Thank you also for your efforts ;)
