### ISSUE TITLE
Not save in PrivateMode (Chrome)

### ISSUE THREAD

**Issue by vostapchenko** [gildas-lormeau/SingleFile#172]
**Describe the bug**
I activated SingleFile to work in PrivateMode (Chrome). I see the active icon in the toolbar. I see the icon blinking in an attempt to save the page, I see the message “OK” on the icon, but the files in the specified directory are not saved. This is only in privatemode! In normal mode, save successfully.
For the experiment, I installed the same parameters of the save directory both in Chrome itself and in SingleFile - without a result...

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. Do you see a "network error" in the download bar with a cryptic filename?

**Comment by vostapchenko** [comment]
Yes, I can see a "network error" in Downolad Files.
![prscr](https://user-images.githubusercontent.com/48206543/53948399-c55f9500-40d8-11e9-8ee3-6240088bfcb3.png)

**Comment by gildas-lormeau** [comment]
That's interesting. It's a regression and it's the first time I can reproduce this kind of bug consistently. I'm looking at what's wrong.

**Comment by vostapchenko** [comment]
Many thanks for the tip! After disable the option "Misc.> Save pages in background", pages began to be saved in PrivateMode. But only when manually saving (for example, click on the SingleFile icon). In the mode of cyclic automatic saving (New Functional), “A” flashes on the icon, but does not save (in PrivateMode)

**Comment by gildas-lormeau** [comment]
@vostapchenko That's normal. When the auto-save is active, pages are always saved in background. That's required from a technical point of view. I think I have fixed your bug, I'll publish a new version very soon.

**Comment by gildas-lormeau** [comment]
@vostapchenko I just deployed the version 1.9.80 which should fix the issue. Please confirm it's okay for you.

**Comment by gildas-lormeau** [comment]
I tested the fix on 2 different machines. From my point of view, this issue is fixed so I'm closing it. Feel to re-open it if needed.
