### ISSUE TITLE
No file saved if 'prompt for a name' is selected

### ISSUE THREAD

**Issue by rosmauk** [gildas-lormeau/SingleFile#173]
After version 1.9.79 no dialog box is initiated to allow file name selection and no file is saved, when the File name option 'prompt for a name' is selected.
Changing the File name option to 'create a unique name' and tick the 'open the "Save as" dialog to confirm the file name' works around the problem.

**Environment**
 - OS: Linuxmint 19.1
 - Browser: Firefox
 - Version: 65.0.1

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. I need to do more tests but it looks like Firefox does not support this option at all actually. Were you seeing a different behavior in the past?

**Comment by rosmauk** [comment]
Thanks for your reply. Before and including version 1.9.79 saving a page caused a combination of 3 possible dialog boxes to appear when the conflict resolution was set to 'prompt for a name'. The possible dialogs are SingleFile_Dialog, Firefox_Dialog and FileBrowser_Dialog. Initially all the options had been reset.

The Firefox_Dialog appeared every time, the SingleFile_Dialog only appears if the 'open the "Save as" dialog to confirm the file name' option is ticked and the FileBrowser_Dialog only appears when the Firefox Downloads Preference is set to 'Always ask you where to save files'. The page files were always saved in the location edited in the FileBrowser_Dialog or in the default Firefox download preference location.

From version 1.9.80 and above none of the 3 dialog boxes ever appeared, regardless of the other changes listed above, and no page files were produced (although the screen was greyed out and the Frame contents, Deferred images, Step 1/3 etc were being processed).

I do not think you actually need to include the 'prompt for a name' option in the 'file name conflict resolution' menu or the SingleFile_Dialog box. If you use either 'create a unique name' or 'overwrite the existing file' this automatically downloads the page file to the Firefox default location (usually ~/Downloads) regardless of the Firefox downloads preference setting. If the 'open the "Save as" dialog to confirm the file name' box is ticked then the FileBrowser_Dialog appears giving you the option to edit the name and saved to location.

As an observation only with default options, all the page files all have unique names even with the 'overwrite the existing file' option because {time-locale} in the template increments in one second intervals.

I hope the above helps. Thanks for all your efforts with this addon, it is very useful.



![SingleFile_Dialog](https://user-images.githubusercontent.com/48361170/54074029-abaf8080-4285-11e9-9e07-0c4c3a7831fb.png)
![Firefox_Dialog](https://user-images.githubusercontent.com/48361170/54074031-b8cc6f80-4285-11e9-8392-a89ed206b9b0.png)
![FileBrowser_Dialog](https://user-images.githubusercontent.com/48361170/54074033-bcf88d00-4285-11e9-973b-91993e695572.png)

**Comment by gildas-lormeau** [comment]
@rosmauk Thank you very much for your feedback. I agree with you but I won't remove the option because it works on Chrome actually. The version 1.9.86 should fix the issue. The option "prompt for a name" still does not work on Firefox but it will download the file. Please let me know if this behavior is okay for you.

**Comment by rosmauk** [comment]
Apologies for the delay in replying. I understand others using Chrome may want to retain this option. The behaviour of the latest version works satisfactorily for my purposes. Thanks for your work in fixing this, the saved pages are perfect for my purposes.

(I found by accident that unticking 'save pages in background' and ticking 'open the "Save as" dialog to confirm the file name' you can still get the SingleFile_Dialog in Firefox if you want it.)

**Comment by gildas-lormeau** [comment]
@rosmauk No problem for the delay and thanks for your feedback. I'm closing the issue, feel free to re-open it if needed.
