### ISSUE TITLE
How to use SingleFile extension with puppeteer headless browser?

### ISSUE THREAD

**Issue by manibharathytu** [gildas-lormeau/SingleFile#178]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered (optional)**

**Additional context (optional)**

**Comment by gildas-lormeau** [comment]
If you use the [CLI](https://github.com/gildas-lormeau/SingleFile/tree/master/cli) tool, you'll use Puppeteer by default. The code for Puppeteer is [here](https://github.com/gildas-lormeau/SingleFile/blob/master/cli/back-ends/puppeteer.js). Do you need more info?

**Comment by Ansarimi** [comment]
I am having the same requirement. I am trying to create puppetter as service like http://pptraas.com, but when i save the html, i need to save in single file. Can we achieve this by leveraging this code base?

**Comment by gildas-lormeau** [comment]
@Ansarimi Yes that's possible. I encourage you to take a look at the files contained in the "cli" directory. It will give you some insights on how to achieve this, I guess. Note that the code is under AGPL. It means that you must open-source your code if you want to use SingleFile in a commercial service/product.

**Comment by manibharathytu** [comment]
@gildas-lormeau  Thanks. I used the CLI code from my node app and got it working. Would be easier if it comes as npm package. Any idea on publishing an npm package?

**Comment by gildas-lormeau** [comment]
@manibharathytu It's not published yet for 2 main reasons:
 - this is the repository of an extension, not a npm package. I would need to create a separate repository for npm
 - this is still a work in progress and I may change/improve things in the future

**Comment by gildas-lormeau** [comment]
@Ansarimi were you able to find the info you wanted to know?

**Comment by gildas-lormeau** [comment]
I'm closing this issue, feel free to re-open it if needed.
