### ISSUE TITLE
Privacy policy: missing 'not'

### ISSUE THREAD

**Issue by jakseb** [gildas-lormeau/SingleFile#179]
In the privacy policy ([privacy.md](https://github.com/gildas-lormeau/SingleFile/blob/57cec4fd63b1561493e3cb4c5f32997eee07e452/privacy.md)) you can see the following:

> SingleFile **does send** any data to our servers or any third parties. All your data is stored locally on your device.

Shouldn't it be 'does NOT send'?

**Comment by gildas-lormeau** [comment]
Yes, you're right! :p

**Comment by gildas-lormeau** [comment]
Thank you very much!
