### ISSUE TITLE
Display logs at the bottom left even if "overlay a shadow on the page during processing" option is disabled

### ISSUE THREAD

**Issue by Orriky** [gildas-lormeau/SingleFile#183]
Hi,

I removed the flag from "overlay a shadow on the page during processing" and the result was bad.
Please, verify this option because it seems that it doesn't work

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. It should be fixed in the verision 1.10.17 I just deployed. Please let me know if that's fine for you.

**Comment by Orriky** [comment]
Thanks,
it works well. 
Is it possible showing the popup notification at the bottom left of the page without applying shadow all over the page?

**Comment by gildas-lormeau** [comment]
Why not...

**Comment by Orriky** [comment]
Do you plan to save even embedded video/audio?

**Comment by gildas-lormeau** [comment]
You already have options for this. See the options "remove video sources" and "remove audio sources" in the "Other resources" part of the options page.

**Comment by gildas-lormeau** [comment]
The fix will be available in the next version of SingleFile.
