### ISSUE TITLE
buttonBlockedBadge uses unicode character which is not supported on macOS

### ISSUE THREAD

**Issue by mstange** [gildas-lormeau/SingleFile#184]
**Describe the bug**
On some pages, a tofu glyph shows up as a badge on the SingleFile toolbar button icon.

The string is defined here, for English:

https://github.com/gildas-lormeau/SingleFile/blob/7d322c861c845568fba85f5050a53901f5dc0d0b/_locales/en/messages.json#L71

<img width="710" alt="Screen Shot 2019-04-05 at 2 31 28 PM" src="https://user-images.githubusercontent.com/961291/55649019-d3740480-57af-11e9-9189-b826e5308ec4.png">

On my machine, no font has [this glyph](https://emojipedia.org/prohibited-sign/). Firefox sometimes hangs its UI for 1.5 seconds searching all fonts for the glyph, see this profile: https://perfht.ml/2TYmu4r

I suggest using the [No Entry sign emoji](https://emojipedia.org/no-entry-sign/) instead, which is supported on macOS.

**Environment**
 - OS: macOS 10.12.6
 - Browser: Firefox
 - Version: 68

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. I used the no entry sign emoji you suggested instead. I just published the version 1.10.18 which includes this change. Please let me know if that's okay for you on macOS now.

**Comment by mstange** [comment]
Thanks, that was fast! I just updated to the new version and it's fixed. I can see the glyph now and there is no more UI hang when it first appears.

**Comment by gildas-lormeau** [comment]
It was an easy fix. Because I think the issue was quite annoying, I preferred to fix it asap. Thank you again!
