### ISSUE TITLE
Can't save any page, show me an “error” word.

### ISSUE THREAD

**Issue by nomosaic** [gildas-lormeau/SingleFile#188]
I'm using win7 & waterfox 56.2.8. When I clicked the icon and it started to load pages, after that there‘s a word “error” on the icon.
Now, I can't save any webpage.
singlefile version 1.10.28
![错误](https://user-images.githubusercontent.com/14254798/56071775-12631500-5dc3-11e9-9e8f-550e38683290.jpg)

**Comment by gildas-lormeau** [comment]
@nomosaic  I cannot reproduce your issue with Waterfox 56.2.8 (on Win 10 Pro). On my end, pages are saved without any particular issue. 

When this error happens, could you please press F12 and tell me if you see an error (i.e. messages in red) in the console? (cf. "Console" tab). 

If you can't see any error, please 
 - go to about:debugging#addons, 
 - click the checkbox "Enable add-on debugging" at the top left,
 - find SingleFile in the list of installed extension and click the "Debug" link, 
 - it will open a new window and a confirmation dialog box, click on "OK" in the confirmation dialog box, 
 - in the new opened window, please tell me if you see errors in the "Console" tab.

**Comment by nomosaic** [comment]
@gildas-lormeau 
![20190413214647](https://user-images.githubusercontent.com/14254798/56080613-d4530900-5e35-11e9-9820-dd4227709210.jpg)
![20190413214725](https://user-images.githubusercontent.com/14254798/56080614-d4eb9f80-5e35-11e9-9a00-2c17ae10e9a5.jpg)

**Comment by gildas-lormeau** [comment]
The "file name conflict resolution" option does not work if set to "prompt for a name" in Firefox and Waterfox,. I updated the "known issue" in the documentation accordingly. However, since the version 1.10.29, it won't trigger anymore the error you reported. I there is a conflict, a unique filename will be generated.

**Comment by nomosaic** [comment]
Thank you for your effort. The problem's been fixed

**Comment by gildas-lormeau** [comment]
Great :)
