### ISSUE TITLE
[question] does it upload any data to a third party for conversion or other purposes?

### ISSUE THREAD

**Issue by AdKiller** [gildas-lormeau/SingleFile#189]
Can you please confirm if this addon uploads any data for conversion or any other purpose?

**Comment by gildas-lormeau** [comment]
I confirm it does *not* upload any data for conversion. All the work is done in your browser. However, when you save a page with SingleFile, it can download resources (images, CSS, frame contents, fonts etc.) that are not displayed or not cached but present in the page.

FYI, I wrote a short privacy policy here: https://github.com/gildas-lormeau/SingleFile/blob/master/privacy.md

**Comment by gildas-lormeau** [comment]
I'm closing this issue because I added a FAQ in the project, see https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md.
