### ISSUE TITLE
Progress stops at 99%

### ISSUE THREAD

**Issue by timscott** [gildas-lormeau/SingleFile#19]
I see that someone else reported this, and it was fixed.  But I just got the extension, and I have this problem on some pages.  Like this one:

http://www.rollingstone.com/movies

**Comment by wxn666** [comment]
I have also encountered the same issue numerous times. This could be caused by the servers not delivering some files.  Please consider adding a feature allowing saving a page, with a warning, even if the progress does not reach 100%.

**Comment by wxn666** [comment]
I would like to add that I have tried saving a webpage many times and on different days but every time the progress stopped at 99%. I finally used another extension on firefox to save it.
