### ISSUE TITLE
CLI version does not emit the trailing </body></html> tags

### ISSUE THREAD

**Issue by jamestoothman** [gildas-lormeau/SingleFile#193]
**Describe the bug**
CLI version does not emit the trailing </body></html> tags.

**To Reproduce**

1. use this sample HTML input (or any small HTML file):
!DOCTYPE html>
<html>
<head>
<title>HTML Page to Reproduce SingleFile Bug</title>
</head>
<body>
<h1>The following is sample content:</h1>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</body>
</html>

2. run latest SingleFile from the cli; command-line options I passed in to single-file:
'--back-end=webdriver-chromium --browser-width=1920 --browser-height=1080 --remove-scripts=false --save-raw-page=true'

3. Observe that the output HTML has an extra blank line at the end of the output file, but is missing the </body> and </html> tags.

**Expected behavior**
SingleFile should emit the closing </body> and </html> tags if they were present in the source HTML.

**Environment**
 - OS: [macOS Mojave 10.14.4]
 - Browser: [Chromium]
 - Version: [Version 70.0.3519.0 (Developer Build) (64-bit)]

**Additional context**
*exact* same behavior/issue occurs on a FreeBSD server running SingleFile CLI, where I also tried it with the same input data.

**Comment by jamestoothman** [comment]
This issue seems to have removed the HTML from my post ... the tags that are being truncated are the closing BODY and HTML tags;  I will attach an image:

![image](https://user-images.githubusercontent.com/9202187/56686375-d6bd2a80-66a1-11e9-8996-8e8155250890.png)

**Comment by gildas-lormeau** [comment]
This is a feature. The HTML5 specification allows these tags to be [omitted](https://www.w3.org/TR/html5/syntax.html#optional-tags). Any parser that can't parse this content is not really compliant with HTML5. However, you can disable this feature by passing the option `--compress-html=false`.

**Comment by jamestoothman** [comment]
Thanks much for the immediate reply!

**Comment by gildas-lormeau** [comment]
you're welcome ;)
