### ISSUE TITLE
Many missing photos in saved file

### ISSUE THREAD

**Issue by captaindavepdx** [gildas-lormeau/SingleFile#195]
**Describe the bug**
A significant number of photos are missing in the saved 'html' file.

**To Reproduce**
1. Go to 'https://twitter.com/mcuban'
2. Click on the "Single-File" extension. 
3. Open the saved 'html' file.
4. See the missing images.

**Expected behavior**
Download all the images on the website into the saved 'html' file.

**Screenshots**
https://pasteboard.co/IbQMnwS.png

**Environment**
 - OS: macOS Sierra
 - Browser: Chrome
 - Version: 74

**Additional context**
Certain Twitter webpages download perfectly.
Tried saving 'mcuban' twitter website using Chrome, Firefox, Command Line Interface.
All the download methods experienced the same problem.

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. If you try to save the page (without scrolling into the page) again, do the missing images appear in the second saved page?

**Comment by captaindavepdx** [comment]
Of course, thanks for building such an awesome tool! 

Tested the page without scrolling. The images are still missing in Chrome, Firefox.

Tested the updated version without scrolling. The images are still missing on Chrome, and it appears the missing images have been removed from the twitter feed in Firefox - still missing, but not visible.

Also, scrolled websites are a crucial feature, personally. If possible, it'd be great to be able to execute javascript in the headless version too! =]

**Comment by gildas-lormeau** [comment]
If you set a higher value for the "maximum idle time (ms)" option like 3000 or 5000, do you see any difference?

**Comment by captaindavepdx** [comment]
That did the trick - even on scroll, thanks! 

Set "maximum idle time" to 6000.

**Comment by gildas-lormeau** [comment]
Great! :)

**Comment by mfioretti** [comment]
> If you set a higher value for the "maximum idle time (ms)" option like 3000 or 5000, do you see any difference?

Hello,

today I installed the current version of SingleFile on firefox 68.0.1 and it seems to work really great (thanks!!!) except for the problem described here: I too have noticed missing images (different ones, when saving the same page twice for testing). Searching for a fix I found this issue and so tried to "set a higher value for the "maximum idle time (ms)" but.. I do not see or recognize where to set that option. My fault surely, but please point me to the right place/file, thanks

**Comment by gildas-lormeau** [comment]
@mfioretti Is your interface in another language than English?

**Comment by mfioretti** [comment]
> @mfioretti Is your interface in another language than English?

No, it is in English, but I have found the problem: I was looking in the wrong place in the preference panel, ie under "auto save" instead of "images". Don't ask me why... :-(

Now, with a maximum idle time of 10 seconds all the images in the test pages I have tried are saved. If this works in the same way with firefox in headless mode, I've really found what I needed!

only thing I notice is that the saved page a) does NOT adapt to the width of the browser window, has a fixed size and b) the browser does not show scrollbars on the side or on the bottom.

a) is I guess unavoidable, and no big deal. but would like to know the exact reason

b) is a big usability problem, any idea how to fix it?

Thanks

**Comment by gildas-lormeau** [comment]
I'm glad to know you found the option. Note that you can run SingleFile from the command line too.

a & b) Do you see these issues with any website you want to save?

**Comment by mfioretti** [comment]
>  a & b) Do you see these issues with any website you want to save?

I've tried with www.repubblica.it and www.ilfattoquotidiano.it (home pages of two italian newspapers): the first two websites that came to my mind, no other reason.

**Comment by gildas-lormeau** [comment]
On my end, I don't have any particular issue with the 3 websites you cited. Did you change any option?

**Comment by mfioretti** [comment]
> On my end, I don't have any particular issue with the 3 websites you cited. Did you change any option?

after logging in again, it does seem that the problem is something weird in my window manager, not in the saved HTML file

**Comment by gildas-lormeau** [comment]
Ok, thanks for the feedback!
