### ISSUE TITLE
Cannot use "--browser-height" to trigger the loading of deferred images on Twitter

### ISSUE THREAD

**Issue by captaindavepdx** [gildas-lormeau/SingleFile#197]
**Describe the bug**
The height of the html file is 7835, regardless of the "--browser-height" option.

**To Reproduce**
1. Go to "Command Line Interface" (Mac)
2. Run SingleFile with a custom "--browser-height=300" option
3. Open the "html" file using "Google Chrome" 
4. Open "Console" in the "Developer Tools"
"View > Developer > Developer Tools > Console" or "Command + Option + i"
5. Run "document.body.height" command in the "Console"
6. See "7835"
7. Repeat using a different height, for example, "--browser-height=30000"
6. See "7835," regardless of the "--browser-height" option 

**Expected behavior**
The height of the "html" file to change based on the "--browser-height" option.

**Html files**
"--browser-height=300"
[https://drive.google.com/open?id=1kMiLF2kO12eDUqOuUObvKCQaKfk1cftD](url)

"--browser-height=3000"
[https://drive.google.com/open?id=1oGQdtRWkrbG0-5ttNEBPf7avxrMFbXo8](url)

"--browser-height=30000"
[https://drive.google.com/open?id=1k0UgqcH90HxmkUg5KL8eSzIE0WCLC6gs](url)

**Environment**
 - OS: [macOS Sierra - 10.12.6 ]
 - Browser: [Google Chrome]
 - Version: [e.g. 74]

**Additional context**
I've added the "--browser-executable-path" option to each test. Also, I noticed the number of images missing in the "html" file was different based on the "--browser-height" option.
- "--browser-executable-path" (only) missing 5 images.
- "--browser-height=300" missing 5 images.
- "--browser-height=3000" missing 3 images.
- "--browser-height=30000" missing 0 images.

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. Could you please run these 2 tests and tell me if the height of the displayed window changes?

`./single-file https://example.com/ --browser-height=50 --browser-debug=true`

`single-file https://example.com/ --browser-height=500 --browser-debug=true`

**Comment by captaindavepdx** [comment]
The height does change in both tests.

./single-file https://example.com/ --browser-height=50 --browser-debug=true
<img width="1269" alt="50" src="https://user-images.githubusercontent.com/30560737/56865964-e762ee80-6988-11e9-9f81-0e02e858f10e.png">

./single-file https://example.com/ --browser-height=500 --browser-debug=true
<img width="1268" alt="500" src="https://user-images.githubusercontent.com/30560737/56865990-2a24c680-6989-11e9-92e7-3ff844c6cb7f.png">

**Comment by gildas-lormeau** [comment]
So it seems the option works as expected. Could you do this additional test please? Run `single-file https://github.com/gildas-lormeau/SingleFile --browser-height=10000 --browser-debug=true` and try to scroll with the mouse wheel in the tab when the page is loaded. If the height of the browser is 10,000px then you should not be able to scroll. Can you confirm you can't scroll?

**Comment by captaindavepdx** [comment]
@gildas-lormeau Correct, I cannot scroll.

**Comment by gildas-lormeau** [comment]
It looks like the real issue is that you cannot retrieve a page with all the contents if it has a bigger size than 8,000px. It's maybe intentional from twitter. If that's the case,I recommend you to inject a script that would do the autoscroll after the page is loaded.

**Comment by captaindavepdx** [comment]
Cool, I'll try that and update afterward.

**Comment by captaindavepdx** [comment]
@gildas-lormeau I may have found part of the problem. 

When I run my script, it displays an error message, "TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded" It's intended to scroll until it reaches the bottom of the page, which can take longer than 30000ms.

To test it, I adjusted my script to stop scrolling at 30000px. And it completed successfully! The html file was 36652px, and 9.2 mb. 

However, it was missing many photos - like when the "--browser-height" option was set below 8k in our previous tests.

To test that, I set the "--browser-height" option to 8000, and reran my new script. But it was only 7907px, and 2.2 mb - which appeared similar to the html files from before.



 



My script works perfectly when it's ran by my script editor, or in the Chrome console. Not sure, what the problem is.

**scroll.js**
https://pastebin.com/xUKaiibk

**Comment by gildas-lormeau** [comment]
The timeout can be increased. I have to verify if there's a switch for that. Stay tuned. Please let me know if you think the issue is fixed from your point of view.

**Comment by captaindavepdx** [comment]
Sounds good, looking forward to testing it!

**Comment by gildas-lormeau** [comment]
I don't think you need to post an issue for the mssing images right now. I fixed the timeout issue, I guess, could you please update your code and tell me what you get?

**Comment by captaindavepdx** [comment]
This is great, now command line interface downloads the full length of the website!

**Comment by gildas-lormeau** [comment]
Great :)
