### ISSUE TITLE
Issue when saving a page with the CLI tool if injected scripts use JS redirect(s).

### ISSUE THREAD

**Issue by captaindavepdx** [gildas-lormeau/SingleFile#198]
**Describe the bug**
I have a script that redirects the browser, which causes Single-File to crash, or fail to redirect.

**To Reproduce**
1. Go to Command Line Interface, add a script that redirects the browser, run it.
2. See "Cannot find context with specified id" or incorrect html completed.

**Redirect script:** 
[https://pastebin.com/rH4PfgyF](url)

**Expected behavior**
The website loads, then the browser redirects to a new website, and then saves html.

**Screenshots**
<img width="1280" alt="Screen Shot 2019-04-28 at 8 59 14 PM" src="https://user-images.githubusercontent.com/30560737/56875935-b8846100-69f8-11e9-9c4a-b3dd46c6b092.png">

**Environment**
 - OS: [MacOS]
 - Browser: [Google Chrome]
 - Version: [74]

**Additional context**
The script executes ok in "Debug" mode, but still crashes in Command Line Interface.
[Potential problem](https://github.com/GoogleChrome/puppeteer/issues/1325#issuecomment-473455922)
[Potential example](https://github.com/GoogleChrome/puppeteer/issues/3684)
[Potential solution](https://github.com/GoogleChrome/puppeteer/issues/3471)

**Comment by gildas-lormeau** [comment]
There are 2 issues with your code. The first one is the fact that you did not assign a function to window.onload. The correct code is the one below (I use lambdas instead of function):

```
if (window.location.href == "https://www.apple.com/") {
    window.onload = () => {
        setInterval(() => {
            window.location.assign("https://www.microsoft.com/");
        }, 1000);
    }
}
```

However this code cannot really work or I don't know what you expect since you're constantly (every second) redirect the user to https://www.microsoft.com/. Thus, SingleFile doesn't have the time to process the page.

**Comment by gildas-lormeau** [comment]
I did 2 more tests with the 2 following scripts:

````
if (window.location.href == "https://www.apple.com/") {
    window.onload = () => {
        setTimeout(() => {
            window.location.assign("https://www.microsoft.com/");
        }, 1000);
    }
}
````
This one does not work.


````
if (window.location.href == "https://www.apple.com/") {
    window.onload = () => {
        // setTimeout(() => {
            window.location.assign("https://www.microsoft.com/");
        // }, 1000);
    }
}
````
This one somewhat works but the URL in the comment generated by SingleFile is incorrect.

**Comment by captaindavepdx** [comment]
@gildas-lormeau That was supposed to be setTimeout - whoops!

**Comment by captaindavepdx** [comment]
My actual script is much longer, that example is just to show the problem.

**Comment by gildas-lormeau** [comment]
Yes, I understand. I need to to more tests to see if this issue can be fixed.

**Comment by captaindavepdx** [comment]
Awesome, thanks @gildas-lormeau!

**Comment by gildas-lormeau** [comment]
@captaindavepdx I did some tests and right now, I'm unable to fix this issue. Why do you do a redirect in the injected script?

**Comment by captaindavepdx** [comment]
@gildas-lormeau I'm trying to log in to Twitter, which redirects after login. 

Certain web pages require login, such as twitter.com/mcuban/media.

I found a few posts about redirects in Puppeteer's GitHub, but I didn't understand their solution. 

Was it unhelpful, or unrelated?

**Comment by gildas-lormeau** [comment]
For twitter, the script below works on my end. The redirect is probably an HTTP redirect (I did not check) which does not cause any particular issue. What script do you run to log in to Twitter?

````
addEventListener("load", () => {
	document.querySelector(".email-input").value = "login";
	document.querySelector("input[type=password]").value  = "password";
	document.querySelector(".LoginForm ").submit();
}, false);
````

**Comment by captaindavepdx** [comment]
//Login to Twitter
function twitter() {
    var twitterUsername = "dave.r.littlefield@gmail.com";
    var twitterPassword = "my247cow";
    var twitterCheck = document.getElementsByClassName("js-username-field email-input js-initial-focus").length;
    if (twitterCheck > 0) {
        setTimeout(function() {
            document.querySelector(".js-initial-focus").value = twitterUsername;
            //document.getElementsByClassName("js-username-field email-input js-initial-focus")[0].value = twitterUsername;
        }, 1000);
        setTimeout(function() {
            document.querySelector(".js-password-field").value = twitterPassword;
            //document.getElementsByClassName("js-password-field")[0].value = twitterPassword;
        }, 1000);
        setTimeout(function() {
            try {
                window.location.href = "https://twitter.com/mcuban";
                document.querySelector(".EdgeButtom--medium").click();
                //document.getElementsByClassName("submit EdgeButton EdgeButton--primary EdgeButtom--medium")[0].click();
            } catch (error) {
                console.log(error);
            }
        }, 3000);
    }
    loggedIn = true;
}

**Comment by captaindavepdx** [comment]
```
//Login to Twitter
function twitter() {
    var twitterUsername = "email";
    var twitterPassword = "password";
    var twitterCheck = document.getElementsByClassName("js-username-field email-input js-initial-focus").length;
    if (twitterCheck > 0) {
        setTimeout(function() {
            document.querySelector(".js-initial-focus").value = twitterUsername;
            //document.getElementsByClassName("js-username-field email-input js-initial-focus")[0].value = twitterUsername;
        }, 1000);
        setTimeout(function() {
            document.querySelector(".js-password-field").value = twitterPassword;
            //document.getElementsByClassName("js-password-field")[0].value = twitterPassword;
        }, 1000);
        setTimeout(function() {
            try {
                window.location.href = "https://twitter.com/mcuban";
                document.querySelector(".EdgeButtom--medium").click();
                //document.getElementsByClassName("submit EdgeButton EdgeButton--primary EdgeButtom--medium")[0].click();
            } catch (error) {
                console.log(error);
            }
        }, 3000);
    }
    loggedIn = true;
}
```

**Comment by gildas-lormeau** [comment]
Try this instead, it works for me.

command: 
`single-file https://twitter.com/mcuban/following following-mcuban.html --browser-scripts=./test.js`

script:
 ```
addEventListener("load", () => {
	document.querySelector(".js-username-field").value = "login";
	document.querySelector(".js-password-field").value  = "password";
	document.querySelector(".signin").submit();
});
```

**Comment by captaindavepdx** [comment]
That successfully logged in, awesome!

It kept firing repeatedly, so I added the if-then statement. And I saw you added it too.

I used, similar idea:
```
if (window.location.href.match("login")) {

}
```

Great work! I wonder why this worked, but the main login screen didn't.

**Comment by gildas-lormeau** [comment]
Great! :)

I edited a little bit the code to use "DOMContentLoaded" event. I recommend you to do the same. It is triggered when the DOM is ready and before resources begin to be downloaded. The "load" event is triggered after the resources are downloaded.

**Comment by captaindavepdx** [comment]
Good Catch! =]

The auto scroll script I had worked great by itself, cli and debug, but now it doesn't work right? Should I make a new issue?

**Comment by gildas-lormeau** [comment]
You can run the auto scroll code just after `document.querySelector(".signin").submit();` and so on.

**Comment by captaindavepdx** [comment]
K, I'll try that, and a few other things. Good idea!

**Comment by gildas-lormeau** [comment]
I updated the code.

**Comment by captaindavepdx** [comment]
Cool, do I need to add a second if-then, to prevent it from firing repeatedly?

**Comment by gildas-lormeau** [comment]
In this example, if there are no redirects after being logged in then you don't need a second if-else.

**Comment by captaindavepdx** [comment]
Doesn't it redirect from login, to following? Not sure how it's different, or why it works, but in debug mode it pulls up the login screen.

**Comment by captaindavepdx** [comment]
Is this normal? It calls getURL from a file in the SingleFile directory?

<img width="1280" alt="Screen Shot 2019-04-29 at 3 22 44 PM" src="https://user-images.githubusercontent.com/30560737/56930747-aa831e80-6a92-11e9-9095-9b00cc2e2695.png">

**Comment by captaindavepdx** [comment]
Should I start a new post?

**Comment by gildas-lormeau** [comment]
You can if you want but you're not forced to. I confirm the issue and I know how to fix it because it's a regression in fact. It will just need some time to fix it. It has only an impact if you don't pass the option "--load-deferred-images=false".

**Comment by captaindavepdx** [comment]
I've added that to the command line ever since you said to do that from before. I'm wondering if the if-then statement we used is related. I'm doing some tests on it, I'll post an update afterward:

**Comment by gildas-lormeau** [comment]
Ok. I fixed the previous issue you were referring to, it was easier than expected. You just have to update the code.

**Comment by captaindavepdx** [comment]
Cool, updating

**Comment by captaindavepdx** [comment]
@gildas-lormeau Ok, installed, do I need to do anything differently?

**Comment by gildas-lormeau** [comment]
Work on your script and if you're sure there's an issue related to SingleFile (ant not related to JavaScript only), post it.

**Comment by captaindavepdx** [comment]
K

**Comment by captaindavepdx** [comment]
Is there a way to see the console.log of each headless run?
