### ISSUE TITLE
Cannot save lazy loaded images on WeChat public blogs

### ISSUE THREAD

**Issue by wizyoung** [gildas-lormeau/SingleFile#199]
**Describe the bug**
The lazy loaded images on WeChat public blogs cannot be saved. Even if I set the "maximum idle time" to a long interval like 5000ms.

**To Reproduce**
1. Go to 'https://mp.weixin.qq.com/s/reNCLvOyJHkJZimnMpbIig##'
2. Save page.
3. Inspect saved file.

**Screenshots**
Original page: 
![](https://i.imgur.com/7q0mdKu.png)

Saved page: 
![](https://i.imgur.com/hXhyB5R.png)

**Environment**
 - OS: macOS 10.14.4 (18E226)
 - Browser: Chrome
 - Version: 74.0.3729.108

**Comment by captaindavepdx** [comment]
I had a similar problem using Command Line Interface - various number of missing photos.

**I was able to temporarily fix it by setting a very large browser height, and then saving the website.**
- Command Line Interface: Add the "--browser-height=8000" option to your command line.
- Extension (Mac): Click "View" menu, click "Developer Tools" menu item, click "Toggle Device Toolbar," Click "Responsiveness Menu," click "Edit" menu Item, set "Width" input to your screen width, set "Height" input to "8000," and click "SingleFile" save website extension.
- Extension (Windows): I assume it's the same as Mac, but I don't have a Windows computer to test it.

![screenshot](https://user-images.githubusercontent.com/30560737/56879112-1ff7dc00-6a0c-11e9-9bad-bc1e587f973f.png)

**Complete html file of your website, created using the methods above:** 
[https://drive.google.com/open?id=1UBjvLIyC6EM2s54_9WwuEXrHMl8ak_Nb](url)

**Comment by gildas-lormeau** [comment]
@wizyoung Thanks for reporting the issue. I cannot reproduce it. On my end the saved page is perfectly saved with Chrome or Firefox (on Windows) without doing anything special. Note that I'm doing tests from France on a ADSL line (i.e. with a high latency I guess) and did not change the "maximum idle time" value. I need to do more tests maybe... The "?" in the middle of the image placeholder in your screenshot is a bit intriguing. Can you post here a zip containing your saved page? Do not hesitate to post more info if you have any.

**Comment by wizyoung** [comment]
@gildas-lormeau 
The zipped file is here
[ZipFile1](https://github.com/gildas-lormeau/SingleFile/files/3127375/e829f117-8401-46d3-ade2-7d2a908e2399.html.zip)

And here is another test link of wechat blogs which I also failed to save the images:
[Link](https://mp.weixin.qq.com/s?__biz=MzI5MDUyMDIxNA==&mid=2247487503&idx=1&sn=e98437efda298a9d8fe1a386c5a96601&chksm=ec1ffdf6db6874e03e1e05d438ebd0d295364d01ca8b2741bdad8ffa5d328032ad24ae76a289&token=1931231045&lang=zh_CN&scene=21#wechat_redirect)
[ZipFile2](https://github.com/gildas-lormeau/SingleFile/files/3127384/0e4153c0-2c93-4b4e-8365-3d401844073b.html.zip)

Hope that can help

**Comment by wizyoung** [comment]
@captaindavepdx Hi, thanks for your help. But your trick does not work on my computer. And when I open your posted html file, the images are still missing. That's quite interesting.

**Comment by gildas-lormeau** [comment]
@wizyoung I opened the two pages you attached and I confirm they're okay. On my machine the images are present and displayed in these 2 pages. Maybe do you have other extensions which are conflicting with embedded images? Couls you try to open these pages with other extensions disabled? By the way, you seem to have a known issue with filenames. I recommend you to uncheck Misc > save pages in background in the options page to fix this, or to re-install Chrome.

**Comment by captaindavepdx** [comment]
@wizyoung Interesting, indeed! I also opened the two pages you attached, and they both worked fine.

Last night I was able to reproduce the issue using the Chrome SingleFile extension, but this morning it  works as expected.

**Comment by wizyoung** [comment]
@captaindavepdx @gildas-lormeau Seems the problem lies in my browser. I disabled all the extensions but in vein. I open my attached files on other Windows computers and the images display normally. But interestingly, saved pages on websites except the wechat blogs are normal in my browser. I will do more experiments these days.

**Comment by wizyoung** [comment]
I copy the html file to my iPhone (iPhone X, iOS 12.2) and open it with Documents app by Readdle and DevonThink and the images fail to load.

**Comment by gildas-lormeau** [comment]
@wizyoung Thanks for the info. Honestly, this "?" is really weird. It remembers me the icon displayed by IE, back in the days, when a resource was not found or not supported. Did you already see this icon on a regular web page? I don't know "Documents app by Readdle" and "DevonThink" and I don't have any iPhone so I cannot tell you if this issue is related. maybe they don't support [data URIs](https://en.wikipedia.org/wiki/Data_URI_scheme) (this is how images are embedded).

**Comment by wizyoung** [comment]
Actually I didn't see the "?" icon on a regular web page.  I have tested the above html files on my friend's macbook and again the images failed to load. I guess Apple products don't support the standard you mentioned. So I will close this issue. Thanks for your help.

**Comment by captaindavepdx** [comment]
@wizyoung I am using a MacBook, and the html file worked fine - I just had to open them manually in Chrome.

**Comment by wizyoung** [comment]
@captaindavepdx Have you tried using Safari?

**Comment by captaindavepdx** [comment]
Not yet, only Chrome, but I've mostly used the command line interface.

**Comment by gildas-lormeau** [comment]
That's weird... I don't remember that Safari has issues with data URIs.

**Comment by wizyoung** [comment]
Update from 2020 :-). Today I tried the extension on Microsoft edge mac version and had some interesting findings. Please see the table below.
For the lazily loaded images on mp.weixin.qq.com: 
![result](https://user-images.githubusercontent.com/13296106/74081955-a2c7c000-4a8f-11ea-92de-4143e6e6a39d.jpg)
I did the test on my two macbooks and the results are the same.
1. Apparently there are some problems with the safari, maybe the data URIs not supported?
2. It seems there are also some problems with the chrome? Maybe some functional implementations are different on macOS platform? 

Hope the information helps

**Comment by gildas-lormeau** [comment]
Thank you for the update. I'm surprised images are still not displayed correctly in Safari. At the top right of https://mp.weixin.qq.com/s/reNCLvOyJHkJZimnMpbIig##, there is a QR code image. Is it broken too when the other images are broken? In other words, are some images still saved?

I don't understand why when you use Chrome to save the page instead of Edge, you get different results. Are you sure "save deferred images" was enabled in Chrome when doing the tests?
