### ISSUE TITLE
Recommended URL for AMO Listing

### ISSUE THREAD

**Issue by Grossdm** [gildas-lormeau/SingleFile#202]
Greetings,

I noticed that the AMO URL listed both here on GitHub and in your YouTube video comments is both language and platform specific.

I have often not had AMO redirect me to the appropriate URL for my language and/or platform. However, if I start with an AMO URL that has no language or platform info, it always redirects correctly.

I recommend that you list your AMO URL as this: `https://addons.mozilla.org/addon/single-file`.

Thank you for your development!

**Comment by gildas-lormeau** [comment]
Thanks for the info, I didn't know I could use such links. It's fixed :)

**Comment by Grossdm** [comment]
You are quite welcome!
