### ISSUE TITLE
Singlefile extension is not getting added with Chrome74

### ISSUE THREAD

**Issue by saritapol13** [gildas-lormeau/SingleFile#203]
**Describe the bug**
Singlefile extension is not getting added with Chrome74

**To Reproduce**
1. Go to 'Chrome web store and install the extension'

**Expected behavior**
Extension should be installed

**Actual**
Getting error: "Package is invalid. Details: 'Could not load background script 'index.js'.'"

**Environment**
 - OS:  Win10
 - Browser: Chrome
 - Version: 74

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. I'm really sorry about that. I just published a new version which fixes the issue.
