### ISSUE TITLE
Option to limit the simultaneous processed pages

### ISSUE THREAD

**Issue by user471** [gildas-lormeau/SingleFile#204]
Is there currently any limit for how many pages is processed simultaneously?

**Comment by gildas-lormeau** [comment]
No, that's an interesting idea though. I'm wondering what the default value should be. I guess it should be determined by the number of cores of the CPU. Did you do some performance tests on your end?

**Comment by user471** [comment]
I did not, but I think It shouldn't be more than the number of the cores.

**Comment by gildas-lormeau** [comment]
@user471 I implemented a pool of worker which is set by default to the number of logical cores of the CPU. You can change this number by exporting your settings, changing the `maxParallelWorkers` value in the JSON file and importing it.

**Comment by gildas-lormeau** [comment]
It's fixed. What I described in the previous post is implemented in the version 1.10.51 I just published.
