### ISSUE TITLE
The "error" displayed on the icon is coming again, can't save any page successfully.

### ISSUE THREAD

**Issue by nomosaic** [gildas-lormeau/SingleFile#208]
This bug is the same as last time.
V1.10.48 is OK, the newest version 1.10.55 has the problem.

![调试页面：singlefile](https://user-images.githubusercontent.com/14254798/57355248-27537e00-71a0-11e9-8213-9764a4f3d967.jpg)
![singlefile 调试页面](https://user-images.githubusercontent.com/14254798/57355455-a779e380-71a0-11e9-8a37-b4a42f777099.jpg)

Win7 Waterfox 56.2.9 x64

**Comment by gildas-lormeau** [comment]
Thank you. This issue should be fixed in the latest version. Note that for the option "file name conflict resolution", the value "create a unique name" which is not the default value is not supported on Firefox.

**Comment by gildas-lormeau** [comment]
Tests on my end show the fix seems okay. I'm closing this issue. Feel free to re-open it if necessary.
