### ISSUE TITLE
This website saving was stuck in the 1st step.

### ISSUE THREAD

**Issue by nomosaic** [gildas-lormeau/SingleFile#209]
e.g. This one
http://www.gov.cn/zhengce/content/2016-07/05/content_5088351.htm
![singlefile 无法保存某网页 错误信息](https://user-images.githubusercontent.com/14254798/57431492-8fb86300-7265-11e9-849a-9f73d38a4978.jpg)
![singlefile 无法保存某网页1](https://user-images.githubusercontent.com/14254798/57431493-8fb86300-7265-11e9-91af-137761819427.jpg)

**Comment by gildas-lormeau** [comment]
Thanks for the issue report. I was able to reproduce and fix the bug. It's fixed in the version 1.10.57 I just published.
