### ISSUE TITLE
Local file useage

### ISSUE THREAD

**Issue by vojtechruz** [gildas-lormeau/SingleFile#21]
Hello,
why is it not possible to process locally stored html files? Do you plan to add this feature? It would be ideal use case as a lot of other programs allow html export of content, but images and styles are as separate files and not contained in one file. Thank you.

**Comment by sunk818** [comment]
This is a duplicate of https://github.com/gildas-lormeau/SingleFile/issues/7

**Comment by ampheta** [comment]
OK
