### ISSUE TITLE
Save pages in background "checked" doesn't remember the last saved path

### ISSUE THREAD

**Issue by iG8R** [gildas-lormeau/SingleFile#211]
**Describe the bug**
While "Save pages in background" option is checked the last saved path in "Save as" dialog doesn't preserved although the description indicates contrary - "Uncheck this option if you get invalid file names like "37bec68b-446a-46a5-8642-19a89c231b46.html" or interrupted downloads when saving pages. You can also check this option if you want the "Save as" dialog to remember the last saved path. Unchecking this option prevent using sub-directories in filename templates."
On the other hand if this option is unchecked some sites cannot be saved with SingleFile (Save as dialog doesn't appear), e.g. all pages from github.com.

**To Reproduce**
0. Check "Save pages in background" option
1. Go to any site
2. Try to save some pages into different folders
3. Every time you will be suggested to save these pages only into Downloads (default) folder.

**Environment**
 - OS: Win10 Pro
 - Browser: WaterFox
 - Version: 56.2.9 (64-bit)

**Comment by gildas-lormeau** [comment]
Thanks for the issue report. I just published the version 1.10.60 which should fix it.

**Comment by iG8R** [comment]
Thank you!

**Comment by gildas-lormeau** [comment]
You're welcome.
