### ISSUE TITLE
Can't execute scripts in command line interface

### ISSUE THREAD

**Issue by captaindavepdx** [gildas-lormeau/SingleFile#212]
**Describe the bug**
An error states that single-file can't find the module for the js file - js file is saved in the "cli" folder

<img width="569" alt="Screen Shot 2019-05-10 at 7 23 07 PM" src="https://user-images.githubusercontent.com/30560737/57563943-303b7f80-7359-11e9-905e-2934ee1ee1ae.png">

**To Reproduce**
1. Go to command line interface
2. Run single-file using a added js file
3. See error.

**Expected behavior**
Single-file crashes before it launches

**Environment**
 - OS: macOS 10.14
 - Browser: Google Chrome
 - Version: 75

**Additional context**
I uninstalled, and reinstalled, but single-file still crashes

**Comment by gildas-lormeau** [comment]
Does it work when you preprend to the path "./"? i.e. "./login-linkedin.js" instead of "login-linkedin.js"?

**Comment by captaindavepdx** [comment]
Yes, whoops! Thanks, @gildas-lormeau

**Comment by gildas-lormeau** [comment]
You're welcome. I'll improve path resolving soon, I hope.
