### ISSUE TITLE
Stuck on step 3/3 - Save progress 100%

### ISSUE THREAD

**Issue by xpressos** [gildas-lormeau/SingleFile#214]
Having some issues downloading certain vbulletin forum pages, most download without any issues.

I tried many settings combinations.

Depending on settings, the download will either complete step 3/3 or get stuck on step 3/3. Hovering over the info shows: Save progress 100%

Either way I'm never able to obtain the actual download.

Currently using latest: 1.10.62

F12 Console attached:

![13-05-2019 17-45-18](https://user-images.githubusercontent.com/22617577/57639783-910cc700-75a8-11e9-82f8-c5d3b4538b5a.jpg)

Any ideas on how to get the download to complete?

**Comment by gildas-lormeau** [comment]
@xpressos Unfortunately, I cannot reproduce the issue you described. Could you please give me an example of URL that fails to download.

**Comment by gildas-lormeau** [comment]
Can you also tell me if you change any template (filename template, infobar template) in the settings?

**Comment by gildas-lormeau** [comment]
@xpressos I think I was able to fix the issue you described. This would be related to the presence of ")" in the query parameters. Please let me know if the version 1.10.63 I just published fixes it.

**Comment by xpressos** [comment]
@gildas-lormeau - The update 1.10.63 resolved the problem! Thanks very much - do you have a donations page?

BTW. Have considered implementing keyboard shortcuts to save all tabs / single tab? would be a nice feature for SingleFile.

**Comment by gildas-lormeau** [comment]
You're welcome. I do not have a donation page (yet). The business model I try to apply to SingleFile is B2B-oriented, i.e. selling licenses for commercial products with closed sources.

I'm not against implementing different keyboard shortcuts. I'll open an issue for that.

**Comment by gildas-lormeau** [comment]
@xpressos FYI, you can now save all the tabs by pressing Ctrl+Shift+U (since the version1.10.66)

**Comment by xpressos** [comment]
Great addition to SingleFile. Thanks very much!

**Comment by gildas-lormeau** [comment]
You're welcome! :)
