### ISSUE TITLE
Embed the demo as a series of gifs instead of a youtube link

### ISSUE THREAD

**Issue by kkarakk** [gildas-lormeau/SingleFile#216]
**Is your feature request related to a problem? Please describe.**
youtube is a hassle to open/get information from

**Describe the solution you'd like**
embed gifs in the description page of the functionality

**Comment by gildas-lormeau** [comment]
@kkarakk Thanks for the suggestion. I'm going to do it.

**Comment by gildas-lormeau** [comment]
That's done!
