### ISSUE TITLE
how to stop/interrupt the saving progress?

### ISSUE THREAD

**Issue by scruel** [gildas-lormeau/SingleFile#218]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
If user press the 'Esc' key then stop the saving progress.

**Describe alternatives you've considered (optional)**

**Additional context (optional)**

**Comment by gildas-lormeau** [comment]
Thanks for the suggestion. Out of curiosity, why do you need to stop a save in progress?

**Comment by scruel** [comment]
Sometimes click icon for mistake, but the following issues are more like the reasons for this function:
1. 'Save pages in background' function need select the saving folder every time(not the saving folder that I have chosen before).
2. Without 'overlay shadow', sometimes my action may cause to save the wrong page (like click the JS based button)
3. Even enable 'save JS' function, it won't work will in some pages(e.g. https://item.jd.com/2854388.html).
![image](https://user-images.githubusercontent.com/16933298/58207256-eff2de80-7d14-11e9-9343-cfff09fe0742.png)

Also, If need, I may open issues for the problems I mentioned.

**Comment by scruel** [comment]
Sometimes click icon for mistake, but the following issues are more like the reasons for this function:
1. 'Save pages in background' function need choose the saving folder every time(seems will open the default folder, but not the folder that I have chosen for saving before).
2. Without 'overlay shadow', sometimes my action may cause to save the wrong page (like click the JS based button)
3. Even enable 'save JS' function, it couldn't work well in some pages(e.g. https://item.jd.com/2854388.html).
![image](https://user-images.githubusercontent.com/16933298/58207566-845d4100-7d15-11e9-977e-5189373a6d7d.png)

Also, If need, I may open issues for the problems I mentioned.

**Comment by gildas-lormeau** [comment]
I understand your need. I'll try to implement it. Here are how to fix your issues 1 and 3:

 1. Not necessarily, please make sure 'open the "Save as" dialog to confirm the file name' is disabled. This issue may also be related to the configuration of the browser. What browser are you using?
 3. This is normal, I cannot guarantee scripts will be correctly saved. In 2019, this is almost impossible to save a page with all its scripts correctly. I think I'm going to remove this option and always remove scripts like in MHTML.

**Comment by scruel** [comment]
I've tried the solution 1, but it not works on Google Chrome(74.0.3729.169)
For solution 3, keep this function. It's acceptable for some pages' JS works fine while some are not. I haven't opened issues about this before cause I realized that there are so many compatibility issues, so it is not possible to handle it well.

**Comment by gildas-lormeau** [comment]
Regarding the first issue, is the option "Ask where to save each file before downloading" disabled in the "Downloads" section of chrome://settings?

**Comment by scruel** [comment]
> I've tried the solution 1, but it not works on Google Chrome(74.0.3729.169)
> For solution 3, keep this function. It's acceptable for some pages' JS works fine while some are not, JS do playing a role as hidden/display switcher on some websites. I haven't opened issues about this before cause I realized that there are so many compatibility issues, so it is not possible to handle it well.

**Comment by scruel** [comment]
JS do playing a role as hidden/display switcher on some websites.

**Comment by scruel** [comment]
> Regarding the first issue, is the option "Ask where to save each file before downloading" disabled in the "Downloads" section of chrome://settings?

Nope, I've enabled it.

**Comment by gildas-lormeau** [comment]
> 
> 
> > Regarding the first issue, is the option "Ask where to save each file before downloading" disabled in the "Downloads" section of chrome://settings?
> 
> Nope, I've enabled it.

Okay, unfortunately SingleFile cannot overwrite this setting.

In understand your need regarding JS. Enabling the "Misc > Save raw page" option may also help to avoid issues in this case but iframes and deferred images won't be saved.

**Comment by gildas-lormeau** [comment]
Since the version 1.11.0 I just published, you can interrupt the saving progress by clicking on the SingleFile button when processing a page, so I'm closing this issue. Feel free to re-open it if necessary.
