### ISSUE TITLE
Auto upload to other services

### ISSUE THREAD

**Issue by ImSingee** [gildas-lormeau/SingleFile#220]
**Is your feature request related to a problem? Please describe.**
I want to have an auto web archive workflow. For now, I just use SingleFile to download the html file and upload it to my Google drive.

**Describe the solution you'd like**
Offer a function to auto upload the generated file to Google drive.

**Describe alternatives you've considered (optional)**
Or just a completely customize action after generating the file. Maybe just write js code or offer some hooks like the extension below.

**Additional context (optional)**
Maybe you can see [this](https://mika-cn.github.io/maoxian-web-clipper/advanced-zh-CN.html) for some ways to implement my request.

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion, I'll try to see how it could be achieved.

**Comment by gildas-lormeau** [comment]
A new option "Misc > save to Google Drive" allows you to save the generated file on Google Drive. This feature will be available in the new version 1.13.0 which will be published very soon. Meanwhile, you can install the extension manually if you want to test it.

**Comment by gildas-lormeau** [comment]
The version 1.13.0 is available for download on the store of Firefox. It will be available on Chrome in the coming days, once reviewed.
