### ISSUE TITLE
A suggestion to avoid clicking by mistake

### ISSUE THREAD

**Issue by qinggonghui** [gildas-lormeau/SingleFile#224]
As there is a freezing time when clicking the SingleFile buttion on the add-ons bar of the browser, I suggest if it could give a notice windows to say "SingleFile try to save the page, go on？" and let the user choose Yes or Cancel. 

This is used to avoid clicking by mistake if there are too much button on the add-ons bar. 

At the meantime, I think， to avoid too much user validation(click the Yes), it could user a timer to turn off the function "notice windows" in let's say 30mins after the last time when clicking the SingleFile button.

Thinks to your devotion to SingleFile :)

**Comment by gildas-lormeau** [comment]
Thanks for the suggestion. If this issue https://github.com/gildas-lormeau/SingleFile/issues/218 was fixed, wouldn't it somewhat solve your issue?

**Comment by qinggonghui** [comment]
Yes，this is another way to solve the problem when the "mistake" happened. And what I suggest is to avoid this "mistake".

Anyway, the effect should be the same.

**Comment by gildas-lormeau** [comment]
@qinggonghui Thank you, I'll try to implement one of the  suggestions soon. It's not an easy task to it may take a while.

**Comment by qinggonghui** [comment]
We just want the SingleFile become better. And it already works well, helps me a lot.

So take your time please. Thank you again :)

**Comment by gildas-lormeau** [comment]
Since the version 1.11.0 I just published, you can interrupt the saving progress by clicking on the SingleFile button when processing a page, so I'm closing this issue. Feel free to re-open it if necessary.
