### ISSUE TITLE
slow opening of saved files with some addons

### ISSUE THREAD

**Issue by rezad1393** [gildas-lormeau/SingleFile#225]
**Describe the bug**
when I save a page with this addon and then open it if firefox , it freexes (or severly slows) firefox for some seconds. but this only happens with some addons enabled.
I disabled addons to see which one cause it and found 4 which enabling any one would cause this behavior.

I noticed that having these addon enabled only wont produce the result but only disabling them fixes the issue.
these are those addons.
" https://addons.mozilla.org/en-US/firefox/addon/requestcontrol/
https://addons.mozilla.org/en-US/firefox/addon/privacy-pass/
https://addons.mozilla.org/en-US/firefox/addon/ipvfoo-pmarks/
https://addons.mozilla.org/en-US/firefox/addon/smartproxy/"

I also noticed with the help of this addon (https://addons.mozilla.org/en-US/firefox/addon/website-information/) that singlefile pages seem to tell firefox that they have bogus domains (I am not sure but the addon shows that)
 like this
![111](https://user-images.githubusercontent.com/7523164/58860429-5a1a6480-86c1-11e9-9648-1cc37e6212b1.png)

I have reported this issue to smartproxy addon page (https://github.com/salarcode/SmartProxy/issues/89) and I am also reporting it here to see what causes this.

opening the pages saved by singlefile in chromium doesnt cause this issue but in chrom I have less addons installed but have the smartproxy one install too.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - OS: archlinux
 - Browser: firefox 6.70.1
 - Version: latest

**Additional context**

**Comment by gildas-lormeau** [comment]
Thank you for the detailed info about the issue.  I managed to reproduce it in a way. On my side, the page is displayed instantly, the browser does not freeze, but the "i" icon at the top right takes longer to display. I did some tests and identified that this API call is responsible for this problem: `browser.webRequest.onBeforeRequest.addListener(() => { }, { urls: ["<all_urls>"] }, ["blocking"]);`. From my point of view, it may be a bug in Firefox, especially because this API does not seem to work with file: URIs. Indeed, I tried to cancel requests by returning `{ cancel: true }` in the listener and, when opening HTML pages from the filesystem, this had no effect while that should completely block the display. 

In order to be sure it's a Firefox bug, could you do the following test please? In Chromium, if you enable "Allow access to file URLs" in the details page of all the extensions you have listed, do you experience the same problems?

**Comment by rezad1393** [comment]
try a more complicated page and not with a empty new firefox profile but with your everyday profile.
I think those addons I named (which I should uMatrix to them too) are working with domains and your addon adds bogus (internal data maybe? I am not a developer ,just a user) and they get messed up with the domain lengths in the page.

I have tried before with only smartproxy enabled and the issue is not there (At least not felt so maybe very smaller lag?) but I will try again today to see if I can use smartproxy (the addon from that list that I actually need) to work with my  other adddons by the old and tested way on disabling addons and testing. :)

btw this doesnt  have to do with you addon actually installed. it is just the pages save with you addon.

and for testing try to save a big page with many images so that you are sure you see the issue completely.

**Comment by rezad1393** [comment]
https://github.com/salarcode/SmartProxy/issues/89#issuecomment-499437135

**Comment by gildas-lormeau** [comment]
Thanks @rezad1393 for the additional info. FYI, here is an example of extension that, when installed, will kill your Firefox when opening a page from the filesystem which contains a lot of data URIs. This does not happen with Chrome so I'm going to open an issue on the bug tracker of Firefox.

[bug-webrequest-file.zip](https://github.com/gildas-lormeau/SingleFile/files/3261513/bug-webrequest-file.zip)

**Comment by rezad1393** [comment]
so this is firefox bug?
on the smartproxy issue tracker the author say the page saved by your addon create 255 connections in the first have second, and that they are fake request.
I have put the link to that comment two post up.

**Comment by gildas-lormeau** [comment]
They are not "fake requests", these are data URIs requests. BTW, you could circumvent this issue by using SingleFileZ, I guess, cf. https://github.com/gildas-lormeau/SingleFileZ.

**Comment by gildas-lormeau** [comment]
FYI, I created this issue in the bug tracker of Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1557300

**Comment by gildas-lormeau** [comment]
@rezad1393 Maybe SingleFileZ (https://github.com/gildas-lormeau/SingleFileZ) could help to circumvent this issue because it uses blob URI instead of data URI.
