### ISSUE TITLE
"Save selection" does not work when the "save raw page" option is enabled

### ISSUE THREAD

**Issue by alekssmitt** [gildas-lormeau/SingleFile#226]
Hello!
First of all, I want to say that you are absolutely right in pointing out to me that I should bring all the questions here. And here I am!

**Describe the bug**
Save Selection --> pointing out the cursor --> result: blank file

**To Reproduce**
1. Go to any site
2. Click the "Save selection" button on the “Single File” extension menu.
3. Move the mouse to highlight the desired content.
4. right-click to save

**Environment**
 - OS: Win7 Pro
 - Browser: Chrome, Firefox
 - Version: x64

**Additional context**
Here is one of the saved files that does not open in Chrome, nor in IE. Please look at that.
[[Solved] Thumbnail Previews Do Not Show on Windows Explorer.zip](https://github.com/gildas-lormeau/SingleFile/files/3268488/Solved.Thumbnail.Previews.Do.Not.Show.on.Windows.Explorer.zip)

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue here :)

You have to use the left click to validate the selection. Right-click cancels it. However it should not produce a blank file... And on my end, it does not. Did you change any option?

**Comment by gildas-lormeau** [comment]
I don't have any particular issue when opening the file you attached, can you give me more details about this issue? Do you see any error in the console (open with F12)?

**Comment by alekssmitt** [comment]
This is not the file I attached, here it is:
![Untitled 2](https://user-images.githubusercontent.com/36442471/59147646-01bbcd80-8a07-11e9-864e-ecdd38945ca4.jpg)

**Comment by gildas-lormeau** [comment]
You're right, I deleted my comment. However, I need to know the exact steps to produce this empty page because when I go to https://www.linglom.com/it-support/solved-thumbnail-previews-do-not-show-on-windows-explorer/, select the main part and save it, the saved page is okay on my end, cf. this screenshot below.

![image](https://user-images.githubusercontent.com/396787/59147731-78ed6380-89ff-11e9-91ae-5db4deb01dd4.png)

**Comment by alekssmitt** [comment]
> Did you change any option?

Yes, I changed a lot of options, I think "save raw page" the one that do it.

**Comment by gildas-lormeau** [comment]
Okay, thanks. I should maybe disable the "Save selection" entry when this option is enabled. They are incompatible each other.

**Comment by alekssmitt** [comment]
> Can I ask you why you enable this option?
I noticed that the file structure, when I turn on this option, looks more like regular HTML. I mean, ideally there should be no JS.

**Comment by gildas-lormeau** [comment]
The default options already allow to remove all the JS from the page (cf. "remove scripts" option which is enabled by default). If it does not, then it's a bug. Note that maybe you should uncheck "compress HTML" option though to get something that looks more like regular HTML. This option allows to remove optional tags, quotes and white-spaces.

**Comment by alekssmitt** [comment]
I read the documentation, and of course  "remove scripts" option is on, nevertheless js is still there.
I don't mind js as soon as the resulting file can be readable in readers such as allreader or calibre and it can be post-edited, or merged in one epub for example.

**Comment by gildas-lormeau** [comment]
Well, maybe you found a bug then. Can you show me an example of page where the JS is still there while the option is enabled?

**Comment by alekssmitt** [comment]
Apparently, you are right! These are JSON-LD scripts. However, I just tried to save the page without the option “save the raw page” and got a page with missing elements (which is important for me), then turned it on again and got everything as it have to be. I think it would be better to leave it as it was.

**Comment by gildas-lormeau** [comment]
> However, I just tried to save the page without the option “save the raw page” and got a page with missing elements (which is important for me), then turned it on again and got everything as it have to be

Then, this would be another bug. Please report me how to reproduce it.

**Comment by alekssmitt** [comment]
OK, If you don't mind I'll open new issue.

**Comment by gildas-lormeau** [comment]
Yes, please open a new one.

**Comment by gildas-lormeau** [comment]
This issue has been fixed in the latest version I just published. Since you're using Chrome, you'll have to wait approximately 7 days before this update is available.
