### ISSUE TITLE
Script performs unexpectedly 

### ISSUE THREAD

**Issue by captaindavepdx** [gildas-lormeau/SingleFile#228]
**Describe the bug**
Script fires a half dozen or so times per second, retry counter not resetting. 

**To Reproduce**
1. Attach this script to SingleFile.
2. Set `--browser-headless=false`.
3. Download dynamic website, airbnb.com.
4. Open console in developer tools.
5. See `console.log` fire rapidly, and `retryAttempt` does not reset to 0.
```
var lastScrollY = 0;

function scroll(retryAttempt) {
    if (retryAttempt < 10) {
        setTimeout(function () {
            window.scrollBy(0, 1000);
            if (window.scrollY != lastScrollY) {
                lastScrollY = window.scrollY;
                window.scrollBy(0, 1000);
                scroll(0);
                console.log(retryAttempt);
            } else if (window.scrollY == lastScrollY) {
                scroll(retryAttempt + 1);
                console.log(retryAttempt);
            }
        }, 1000);
    }
}

scroll(0);
```

**Expected behavior**
The screen to scroll down, and console to print retryAttempt, once per second, until 10 retries.

**Screenshots**
<img width="1280" alt="Screen Shot 2019-06-11 at 3 12 39 PM" src="https://user-images.githubusercontent.com/30560737/59310509-70916480-8c5b-11e9-8852-b565dd43ecf8.png">

**Environment**
 - MacOS: Mojave
 - Browser: Chrome
 - Version: 75

**Additional context**
The script worked as expected outside of SingleFile - Chrome, Safari.
Tried another script intended to limit the rate it was fired- same result.

```
var running = false;
var lastScrollY = 0;

function scroll(retryAttempt) {

    if (running == false && retryAttempt < 10) {
        running = true;

        window.scrollBy(0, 1000);
        
        if (window.scrollY != lastScrollY) {
            lastScrollY = window.scrollY;
            window.scrollBy(0, 1000);
            console.log(retryAttempt);
            setTimeout(function() {
                running = false;
                scroll(0);
            }, 1000);
        } else {
            console.log(retryAttempt);
            setTimeout(function() {
                running = false;
                scroll(retryAttempt + 1)
            }, 1000);
        }
    }
}

scroll(0);
```

**Comment by gildas-lormeau** [comment]
Isn't your issue due to the fact that the script is injected in all frames and that you must ensure`window == top` is true (cf. https://github.com/gildas-lormeau/SingleFile/issues/201#issuecomment-487900629)?

**Comment by captaindavepdx** [comment]
Haha, i forgot about that - it's been a while. And yes, that did the trick. Thanks @gildas-lormeau!
