### ISSUE TITLE
Some images are not displayed in the SingleFile-saved webpage when "duplicate images merging" option has been checked.

### ISSUE THREAD

**Issue by nomosaic** [gildas-lormeau/SingleFile#229]
Waterfox 56.2.10.1 x64
e.g. This MS page
![重复图像合并](https://user-images.githubusercontent.com/14254798/59442437-ccf7ae00-8e2c-11e9-820c-4e82aab8e846.jpg)
https://support.office.com/zh-cn/article/%E7%94%A8%E5%9C%86%E7%8E%AF%E5%9B%BE%E8%A1%A8%E7%A4%BA%E6%95%B0%E6%8D%AE-0ac0efde-34e2-4dc6-9b7f-ac93d1783353

**Comment by gildas-lormeau** [comment]
The page is correctly saved. Images will be displayed in Firefox or Chrome fine. I don't know why Waterfox refuses to display them. From my point of view, it's a bug in Waterfox.

**Comment by nomosaic** [comment]
> 
> 
> The page is correctly saved. Images will be displayed if you open the saved page in Firefox or Chrome. I don't know why Waterfox refuses to display them. From my point of view, it's a bug in Waterfox.

Image source code in saved page:
<img src="data:image/svg+xml,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; width=&quot;400&quot; height=&quot;293&quot;><rect fill-opacity=&quot;0&quot;/></svg>" alt="带格式的圆环图" ms.cmpgrp="content" ms.pgarea="Body" ms.interactiontype="500" style="background-blend-mode:normal!important;background-clip:content-box!important;background-position:50% 50%!important;background-color:rgba(0,0,0,0)!important;background-image:var(--sf-img-25)!important;background-size:100% 100%!important;background-origin:content-box!important;background-repeat:no-repeat!important">

There is a hint about the reason maybe?
https://stackoverflow.com/questions/31418480/img-with-svg-data-uri-wont-display-in-firefox

**Comment by gildas-lormeau** [comment]
I tried to use base64 to encode data URIs but, unfortunately, it does not help to circumvent this issue, cf. 
[用圆环图表示数据 - Office 支持 (2019-06-16 2_13_32 AM).zip](https://github.com/gildas-lormeau/SingleFile/files/3293678/-.Office.2019-06-16.2_13_32.AM.zip).

**Comment by gildas-lormeau** [comment]
@nomosaic BTW, did you try to use SingleFileZ? It has an implementation that circumvents this kind of issue (e.g. related to grouped images).

**Comment by gildas-lormeau** [comment]
I'm closing this issue because it has been added in the list of known issues here: https://github.com/gildas-lormeau/SingleFile#known-issues
