### ISSUE TITLE
Would it be possible to have a Webdriver only solution ?

### ISSUE THREAD

**Issue by mohanraj-r** [gildas-lormeau/SingleFile#230]
**Is your feature request related to a problem? Please describe.**
I would like to use SingleFile with just Webdriver as the entry point and the only external dependency besides singleFile.

**Describe the solution you'd like**
Ability to inject singleFile js file(s) into the current page using webdriver (with [JavascriptExecutor](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/JavascriptExecutor.html)) and trigger saving page to given path.

**Describe alternatives you've considered (optional)**
* If the browser (chrome) was configured to start with the singlefile extension - which I guess could be configured to autosave the page on open. But this gives less control than being able to drive page capture whenever required when interacting with the page using webdriver. 
* Guess the cli can also be used to drive a similar workflow - but it requires node - and hence more dependencies and moving parts. Also it can't work with authenticated pages unlike a webdriver solution which could authenticate by filling in credentials.

**Comment by gildas-lormeau** [comment]
As you noted it's possible and this is indeed what does the CLI tool. The implementations are here
 - Chromium: https://github.com/gildas-lormeau/SingleFile/blob/master/cli/back-ends/webdriver-chromium.js
 - Firefox: https://github.com/gildas-lormeau/SingleFile/blob/master/cli/back-ends/webdriver-gecko.js

You have to port this code in Java and it should (almost) work.

**Comment by gildas-lormeau** [comment]
@mohanraj-r Any comment?

**Comment by mohanraj-r** [comment]
Thanks @gildas-lormeau I will look into porting it into Java when possible and will ping you with any questions if needed.

**Comment by gildas-lormeau** [comment]
Great :)
