### ISSUE TITLE
Problem saving page

### ISSUE THREAD

**Issue by zdk5567** [gildas-lormeau/SingleFile#234]
The save is in step 1, after several minutes trying to save it, the tab closes due to lack of memory.

The following page I try to save: [https://noticias.coches.com/consejos/intercooler-que-es-y-como-funciona/160303](url)

System: windows 10 pro x64
Web browser: Chrome x64 and firefox x64, both in the latest version
And it has been tested with ublock origin enabled and disabled

**Comment by gildas-lormeau** [comment]
Thanks for issue report. This issue was due to style sheets included in themselves. That's why the process was stuck. It's fixed in the version 1.11.1 I just published.
