### ISSUE TITLE
Subresource Integrity - fails to embed javascript file when script tag includes integrity check.

### ISSUE THREAD

**Issue by belzecue** [gildas-lormeau/SingleFile#237]
Fails to embed javascript file when script tag includes integrity check.  Simply omits it.

e.g.

<script type="text/javascript" src="aes.js" integrity="sha256-io/4XEop79kCBTcCfNvUjOxzT+szFctt9ul41O8U/ag=" crossorigin="anonymous"></script>

See https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by gildas-lormeau** [comment]
It's strange, the code exists to do so (cf. https://github.com/gildas-lormeau/SingleFile/blob/master/lib/single-file/single-file-core.js#L1089). I'll do some tests..

**Comment by gildas-lormeau** [comment]
I did a quick test and I confirm I was not able to reproduce your issue. Do you know an example of page where SingleFile does no remove the integrity attribute?

**Comment by belzecue** [comment]
Thanks for looking into it.

I can't post the problem file because it's on my private site, which I don't want to announce.  But I can show you the two <head> sections and how they differ...

ORIGINAL
-------------

<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>JavaScrypt Encryption</title>
<meta content="utf-8" http-equiv="encoding">
<script type="text/javascript" src="aes.js" integrity="sha256-io/4XEop79kCBTcCfNvUjOxzT+szFctt9ul41O8U/ag=" crossorigin="anonymous"></script>
</head>


SINGLE FILE RESULT:
-----------------------------

<!DOCTYPE html> <html lang=en><meta charset=utf-8>
<title>JavaScrypt Encryption</title>
<meta content=utf-8 http-equiv=encoding>
<link type=image/x-icon rel="shortcut icon" href="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="></head>


Note there is no beginner <head> tag in the Single File output, and the script tag has been entirely omitted.

**Comment by gildas-lormeau** [comment]
I forgot to mention I disabled the option "other resources > remove scripts" before doing the test. Otherwise, all script tags containing JavaScript are removed from the saved page.

The HTML SingleFile produces is optimized for generating small files. However, the HTML is valid. If you prefer, you can disable "HTML Content > compress HTML content"

**Comment by belzecue** [comment]
Ah yes, my apologies.  This was my error.  I disabled 'remove scripts' and now my page functions perfectly after being Single File'd.  I will study the options carefully.

**Comment by gildas-lormeau** [comment]
No problem ;)
