### ISSUE TITLE
date of page in name of save file

### ISSUE THREAD

**Issue by mrjok** [gildas-lormeau/SingleFile#238]
Windows 10, Firefox 60.7.2 ESR, SingleFile 1.11.5

How I can add date of create web page in name of save file?

**Comment by gildas-lormeau** [comment]
You mean the publish date? Unfortunately, there are no standards to store store it with a meta tag, cf. https://stackoverflow.com/questions/4575967/is-there-a-standardized-meta-tag-for-the-date-of-a-website

**Comment by gildas-lormeau** [comment]
I'm closing this issue. Feel free to re-open it if necessary.
