### ISSUE TITLE
SingleFile fails to produce a self-contained file

### ISSUE THREAD

**Issue by curtcox** [gildas-lormeau/SingleFile#24]
I am trying to use SingleFile to produce a single page version of "Cocoa Core Competencies" located here:

https://developer.apple.com/library/ios/documentation/general/conceptual/devpedia-cocoacore/Accessibility.html

The produced HTML file still contains lots of embedded URLs to developer.apple.com. Most of them need to be embedded ahead-of-time for the page to work properly offline.

**Comment by gengkev** [comment]
It's not going to save every single link that it can find, if that's what you're expecting...? That would require quite a lot of recursion! SingleFile only saves the page that you're currently on.
