### ISSUE TITLE
option to remove from sidebar and tab context menu

### ISSUE THREAD

**Issue by artyfox** [gildas-lormeau/SingleFile#240]
In Firefox, under options>user interface there is the option to remove the "Single File" entry from the page context menu, but not from the sidebar or tab context menu.

Would be awesome if you could add this option. Thanks! 🦊

**Comment by gildas-lormeau** [comment]
Currently, you can remove the entry in the tab menu with a hidden setting. Export your settings, open the saved file, replace `"tabMenuEnabled": true` with ``"tabMenuEnabled": false`, save the file, and import it. Unfortunately, it's impossible for me to provide a setting to hide SingleFile from the sidebar.

**Comment by artyfox** [comment]
Hey, thanks for the import settings tip! It worked. 

It would be nice if the "sidebar_action" entry could be externalized from the manifest. Hopefully FF will  make it work like context menus, where you request permission to the sidebar, and the rest is controllable via js.

Thanks for your continued development of this cool add-on! 🦊

**Comment by gildas-lormeau** [comment]
I'm closing this issue since there is no technical solution available to remove SingleFile from the sidebar.
