### ISSUE TITLE
Tag </ html> is missing in the saved file on purpose ?

### ISSUE THREAD

**Issue by alekssmitt** [gildas-lormeau/SingleFile#241]
Tag </ html> is missing in any saved file.

**To Reproduce**
the structure can be seen with any HTML editor

**Environment**
 - OS:  Win7 Pro
 - Browser: Chrome
 - Version: 64

**Comment by gildas-lormeau** [comment]
Yes, it's on purpose. SingleFile removes from the HTML the [optional tags](https://www.w3.org/TR/html5/syntax.html#optional-tags), quotes etc. You can disable this behavior by unchecking "HTML > compress HTML".

**Comment by alekssmitt** [comment]
Thanks for explicit answer.

**Comment by gildas-lormeau** [comment]
you're welcome!
