### ISSUE TITLE
Print "function" does not work after conversion

### ISSUE THREAD

**Issue by MrCatalina** [gildas-lormeau/SingleFile#242]
**Describe the bug**
This code no longer functions after single file.  It should print the content of the page.

button onclick="myFunction()">Print this document</button

I had to delete the outside arrows to display.

I am using a webpage as a document using dreamweaver.  This works until I make it a single file.  Please feel free to contact me.

**Comment by gildas-lormeau** [comment]
That's because SingleFile removes all scripts from the page. I'll try to implement an option, I guess, that allows to keep the inline scripts.

**Comment by gildas-lormeau** [comment]
@MrCatalina Actually, I did not read carefully your issue. I thought the value of onclick was "print()" or "window.print()". If the value is a call to a function from a script (e.g. "myFunction()"), then unchecking "remove scripts" (and optionally checking "save raw page") might fix this issue.
