### ISSUE TITLE
Option to always show infobar

### ISSUE THREAD

**Issue by user471** [gildas-lormeau/SingleFile#243]
For example it's not possible to install singlefile on mobile chrome, so it would be helpful if infobar could be visible without extension.

**Comment by gildas-lormeau** [comment]
Thanks for the suggestion. I'll try to implement it.

**Comment by gildas-lormeau** [comment]
A new option will be available in the next version in order to include the infobar into the saved page.

**Comment by gildas-lormeau** [comment]
The new option is available in the version 1.11.28 I've just published.

**Comment by user471** [comment]
@gildas-lormeau Thanks. Option for cli saving would also be helpful.

**Comment by gildas-lormeau** [comment]
@user471 Yes, I agree. I'll implement it soon

**Comment by gildas-lormeau** [comment]
@user471 The option is now available, it is `--include-infobar=true`.
