### ISSUE TITLE
Ability to save web page with css modifications from DevTools

### ISSUE THREAD

**Issue by KroniK907** [gildas-lormeau/SingleFile#244]
Currently, if you have made any CSS or JS changes to a web page through the Developer Tools built into Chrome or Firefox, these changes will not be saved. 

It would be nice to have the option to save the web page as it is currently shown, with all the modifications to CSS, JS etc, as this provides a nice way to make some tweaks and changes and then share those change ideas with a project manager or developer etc in an easy to view format.

Thanks!

**Comment by gildas-lormeau** [comment]
I did some tests and I would be little bit more nuanced. In Chrome and Firefox, you can add styles on elements and they will be saved. In Firefox, you can also add rules (via the "+" button) and they will be saved. Unfortunately, as far as I know, it's not technically possible for SingleFile to retrieve the content of CSS or JS files modified through the debugger.

**Comment by KroniK907** [comment]
Interesting. I would have assumed that it saves the changes to the cached
CSS file for the tab and you would be able to retrieve it. But I'm not a
chrome expert so maybe it's all done in memory or something.

In any case, thanks for looking into it.

**Comment by gildas-lormeau** [comment]
This feature is implemented in the version 1.11.29 I've just published. It will work correctly only in Chrome. Firefox does not implement (yet) the Dev Tools API required for this feature.
