### ISSUE TITLE
Skipping Step 3 of 3 when saving page as HTML

### ISSUE THREAD

**Issue by j311tech** [gildas-lormeau/SingleFile#245]
I've had this issue periodically and then it disappears.

It is happenning in Chrome & Firefox and on all computers that I use..

When I'm saving pages as HTML, I usually get deferred images, step 1/3, step 2/3 and then step 3/3 before the HTML file is created. Now, it never does step 3/3.

**Comment by gildas-lormeau** [comment]
With simple pages, this step can be very fast and it does not have the time to be displayed in the log window. However, be reassured, this step is indeed executed :) For example, I always see it if I try to save https://www.phonandroid.com/test-bose-700.html.

**Comment by gildas-lormeau** [comment]
I'm closing this issue. Feel free to re-open it if necessary.

**Comment by j311tech** [comment]
Gildas, 

Thank you for the quick response and explanation.
I originally used Mozilla Archive Format and similar add-ons, until Firefox disabled them and went to Web Extensions. I started using another extension until I found out about SingleFile, which is much easier to use and requires less technical knowledge in the use of it's options. It's a terrific product.

**Comment by j311tech** [comment]
Gildas, 

Thank you for the quick response and explanation.
I originally used Mozilla Archive Format and similar add-ons, until Firefox disabled them and went to Web Extensions. I started using another extension until I found out about SingleFile, which is much easier to use and requires less technical knowledge in the use of it's options. It's a terrific product.

**Comment by gildas-lormeau** [comment]
Thank you also for the feedback and the kind words! I am also reassured to hear that SingleFile remains technically accessible :). 
By the way, do you know SingleFileZ (https://github.com/gildas-lormeau/SingleFileZ), it's a fork of SingleFile I wrote recently and which may remind you of the MAFF format.
