### ISSUE TITLE
Save selection bug

### ISSUE THREAD

**Issue by harryks** [gildas-lormeau/SingleFile#248]
**Describe the bug**

Hello.
Sorry for the Google translation.

All versions SingleFile after 1.10.74 and SingleFileZ after 0.1.14 (i.e., after June 6) incorrectly save the selection on the `forum.ru-board.com` and `4pda.ru` forums.

On `forum.ru-board.com` when selecting and copying one post to a file, this post and the footer (and the response form, if I am authorized) are saved.

On 4pda.ru still worse. Starting from the selected post, every second post is saved to a file until the end of the page.

That is, if I select the fourth post from the bottom, then the fourth and second posts will be saved to the file, counting from the bottom. If I select the fifth post from the bottom, then the fifth, third and first posts will be saved to the file, counting from the bottom. And + footer.

**To Reproduce**
1. Go to links https://forum.ru-board.com/topic.cgi?forum=5&topic=50187&start=500#15
or
https://4pda.ru/forum/index.php?showtopic=200241&view=findpost&p=5682001
2. Select any one post
3. Save selection
4. Open saved file

**Expected behavior**
Expected to save only one post.

**Screenshots**
Files, links ans screenshots attached.

**Environment**
 - OS: Win8.1 Pro
 - Browser: Firefox
 - Version: 52, 60, 68
[SingleFile_bug.zip](https://github.com/gildas-lormeau/SingleFile/files/3449228/SingleFile_bug.zip)

**Comment by gildas-lormeau** [comment]
Thank you very much for having reported this issue. It will be fixed in the 1.11.13 I'm going to publish.

**Comment by gildas-lormeau** [comment]
I'm not sure I really fixed the issue though. Please let me know if that works for you.

**Comment by gildas-lormeau** [comment]
This issue should now be saved in the version 1.11.14 I just published.

**Comment by gildas-lormeau** [comment]
I read the thread https://forum.ru-board.com. Out of curiosity, what means "буржуями" :p?

**Comment by harryks** [comment]
In this context, it means English speaking :-)
Version 1.11.14 saves correctly. Thanks.
But on the forum 4pda.ru wrong encoding.
![4pda - wrong encoding](https://user-images.githubusercontent.com/42656194/62210933-ff8e4380-b3a5-11e9-9056-4835060342b2.png)

**Comment by gildas-lormeau** [comment]
Thanks for the feedback. The encoding issue is not related to this "Save selection" issue though. I'm checking right now what's wrong.

**Comment by gildas-lormeau** [comment]
@harryks The encoding issue should be fixed in the version 1.11.15 I just published.

**Comment by harryks** [comment]
version 1.11.15 - Ok

Thanks, very quickly done
I wish you success in your work. And good luck

**Comment by gildas-lormeau** [comment]
You're welcome and thank you for the kind words :)
