### ISSUE TITLE
SingleFile 1.11.18 - saving page fails

### ISSUE THREAD

**Issue by smaragdus** [gildas-lormeau/SingleFile#249]
Hello,

Until today I have never had problems with **SingleFile** but version **1.11.18** does not work for me neither in **Chromium** nor in **Firefox**. Saving pages gets stuck at `Step 1/3`, screen:

![SingleFile 1 11 18 - 2019-08-03 - 002](https://user-images.githubusercontent.com/9025757/62405212-0d111c80-b5a4-11e9-9025-3874381bfb7a.png)

In the tool bar I see `ERR` in stead of `OK`.

Restarting the browsers did not help.

In Firefox uninstalling and reinstalling the extension did not help but downgrading from version **1.11.18** to version **1.11.14** solved the problem- **SingleFile** worked as expected.

In Chromium **SingleFile** worked in Incognito mode but I got files with such names:

- `b2087d88-f9b9-40d1-b894-3d46018dd125`
- `c20026f0-d7b4-4490-bc3e-9399e7d33993`

Disabling `save pages in background` fixed the file names problem. Later I re-enabled this option and I again got such file names.

I do not know whether the problem is in my browsers or in  **SingleFile** version **1.11.18**- until now I have never had problems saving pages and I always got the right names.

The browsers I use with **SingleFile** are the following:

- [Cent Browser](https://www.centbrowser.com/) version **4.0.9.112**
- [Iceweasel](https://sourceforge.net/projects/libportable/) version **67.0** (not the latest one)

My system - Windows 8 x64.

Since version **1.11.14** works just fine in **Iceweasel** (custom build of **Firefox**) but version **1.11.18** doesn't I presume that some changes might have broken something in the latest version of **SingleFile**.

**Comment by gildas-lormeau** [comment]
Thanks for having reported the issue. I think this issue is fixed in the version 1.11.19 I published some hours ago. Please confirm if it is fixed on your side. Otherwise, please provide a URL showing the issue.

The issue with filenames seems to be related to Chrome updates. To fix it, you have unfortunately to reinstall it. Google does not seem to want to fix this annoying bug.

**Comment by smaragdus** [comment]
@gildas-lormeau 

Thank you very much for the quick response and the quick fix.

I checked **SingleFile** version **1.11.19** with both **Cent Browser** and **Iceweasel** and it worked fine with both of them (because the extension hadn't updated automatically I uninstalled and reinstalled it). However in **Chromium**-based **Cent Browser** I was still getting file names of this pattern:

- `0be48820-ba6e-425b-9607-49dea3cb6e8b`
- `cc5fb477-8f8c-4a03-8772-82806681d1dd`

so as a workaround I disabled `save pages in background` option as explained in **Known Issues**.

> The issue with filenames seems to be related to Chrome updates. To fix it, you have unfortunately to reinstall it.

In fact I am using the portable version of **Cent Browser** so there is no installation but extraction a SFX archives. I do not find any meaning to overwrite the same files. Perhaps I am wrong?

I will close this issue as it is fixed (disabling `save pages in background` option allows me to get the right file names).

I would like to take this opportunity to thank you for **SingleFile** extension- it  is one of my favourite ones. I have compared it with several similar extensions and for me **SingleFile** is the best- it offers more options, it produces smallest files, excellent work, thank you!

Have a great week-end!

**Comment by gildas-lormeau** [comment]
You're right @smaragdus, it does not make any sense to "re-install" a portable version of a browser. Did you try to use another profile to see if it helps? This bug tends to annoy me because it's quite myterious and Google does not seem to care about it.

Thank you very much for the kind words! I'm glad to see users happy with SingleFile :)

**Comment by smaragdus** [comment]
@gildas-lormeau 

For me now there are great extensions but not great browsers. I was a long time Firefox users but the changes Mozilla made to their browser made me hate it. I do not like Chromium either- I try to de-Google it as much as possible using custom clones but it is steadily going down too- with the advent of Chromium Manifest V3 and the limitation of ad-blocking extensions I may dump it for good. So currently I am switching back and forth between Chromium and Firefox. In short- I love some open source extensions (including your SingleFile) but I hate the browsers. For me it is outrageous that Google simply does not care about fixing some very old bugs, all it cares about is taking customization away from the users and severely dumbing down the already dumbed down Chromium.

Last night before opening this issue I did some tests with SingleFile and as far as I remember when using a new profile I was getting file names for web pages just right. I may do more tests in the future (I am going out now) and if I discover anything valuable to share I will post it here.

Best regards
