### ISSUE TITLE
Does not work in Incognito Mode

### ISSUE THREAD

**Issue by franzalex** [gildas-lormeau/SingleFile#25]
Congratulations for the wonderful extension. I instantly fell in love with it and that rarely happens for me. One thing I have observed, which is hampering my use of the extension is that it does not work in Incognito Mode.

After doing all the background processing and popping up the save dialog, the associated item in the download bar says **Failed - No file** (as shown in the screenshots below) and nothing gets saved. The only workaround (if it can be called as such) I have found is to open the page in normal mode (_something I didn't want to do initially_) and then save from there.

![image](https://cloud.githubusercontent.com/assets/7560066/3681870/55a172d2-12c1-11e4-8edd-9d7f9e546b52.png)  
![image](https://cloud.githubusercontent.com/assets/7560066/3681888/8d71a920-12c1-11e4-89a8-26e77bd769ea.png)
### Additional Details
- Google Chrome Version 36.0.1985.125 m  
- Microsoft Windows 7 Home Premium Service Pack 1 (32-bit)

**Comment by Dany0** [comment]
I second this one. I suppose this might be a chrome privileges issue.

**Comment by gengkev** [comment]
You can copy the page linked to by "Click here to save the page" and open that in a regular window, but then right click -> Save Page As doesn't seem to work...

**Comment by saveriomiroddi** [comment]
Bump! This really hurts my workflow as well, as I use the Incognito mode for almost all the web usage.

**Comment by gildas-lormeau** [comment]
This issue is fixed in SingleFile version 1.0.15.
