### ISSUE TITLE
AutoSave Broken

### ISSUE THREAD

**Issue by lumnikemel** [gildas-lormeau/SingleFile#252]
**Describe the bug**
Auto-save is no longer working. It worked yesterday. The [A] appears, but it simply doesn't automatically save. I've tried a ton of things to get it working. I've tried on Chromium and Vivaldi. This does NOT affect SingleFileZ. I noticed SingleFile was updated sometime today, so that probably broke it.

**Comment by gildas-lormeau** [comment]
Sorry, I forgot to publish the version that fixes this issue. It should work with the version 1.11.25.

**Comment by lumnikemel** [comment]
How do I get that version? i just restarted browser, but extension did not update. Still on x.24.

**Comment by lumnikemel** [comment]
Thanks. Works now.

**Comment by gildas-lormeau** [comment]
Great :)
