### ISSUE TITLE
Saved webpage shows infobar even if infobar disabled

### ISSUE THREAD

**Issue by H48** [gildas-lormeau/SingleFile#254]
**Describe the bug**
When I open a page saved with SingleFile the Infobar is shown despite both "display an infobar when viewing a saved page" and "include the infobar in the saved page" being disabled.

**To Reproduce**
1. Disable 'display an infobar when viewing a saved page' in SingleFile's options
2. Disable 'include the infobar in the saved page' in SingleFile's options
3. Go to https://github.com/jmacd/xdelta/blob/wiki/CommandLineSyntax.md
4. Click on the SingleFile icon in the toolbar to save the page
5. Open the saved page
6. The (i) in the top right-hand corner is shown and upon clicking shows the save time and link to the source webpage

**Expected behavior**
The (i) should not be shown in the saved page.

**Environment**
 - OS: Win10 Home v1903
 - Browser: Firefox
 - Version: 68.0.2 64-bit

**Comment by gildas-lormeau** [comment]
Thank you @H48 for having reported this issue. I was able to reproduce it and it should be fixed in the version 1.11.30 I've just published. Please let me know if it works on your side.

**Comment by H48** [comment]
@gildas-lormeau 
Thank you very much, confirm fixed in both SingleFile and SingleFileZ (although only on my other computer, will check on the original bugreport computer on Monday).

**Comment by gildas-lormeau** [comment]
@H48 You're welcome and sorry for the inconvenience. Have a nice weekend!

**Comment by H48** [comment]
Confirmed fixed on original PC as well. Thanks!

**Comment by gildas-lormeau** [comment]
Great news! I'm closing the issue :)
