### ISSUE TITLE
the empty checkmark ' "Save as" dialog to confirm the file name' isn't being respected and other bugs

### ISSUE THREAD

**Issue by eixan** [gildas-lormeau/SingleFile#256]
**Describe the bug**
Bug: When I tell the extension to save every selected tab it asks me for the file name of each tab
Bug 2: Suspecting that other extensions could be the culprit I disabled all of them only to find that the extension was further broken by only saving two out of the 40 tabs I selected. The autosave tab feature would ask me for the file name for every tab that a window contained though.

**To Reproduce**

**Expected behavior**

**Screenshots**
https://files.catbox.moe/78p7pb.png

All the extensions that I had enabled initially.

**Environment**
 - OS:  Windows 10 pro  OS build:18362.295 _Version_:1903
 - Browser: Chrome
 - Version:  76.0.3809.100  

**Additional context**

**Comment by gildas-lormeau** [comment]
Is "Ask where to save each file before downloading" enabled in chrome://settings/downloads?

**Comment by eixan** [comment]
yes...

**Comment by gildas-lormeau** [comment]
I'll add this issue in the list of "know issues". Thank you!
