### ISSUE TITLE
SingleFile not working with Firefox Quantum 'Reader View' feature

### ISSUE THREAD

**Issue by theunbob** [gildas-lormeau/SingleFile#257]
**Describe the bug**
When viewing a page with 'reader view' - clicking the SF icon (on Firefox toolbar) results in this message: "This page cannot be saved with SingleFile". Is this a SF bug or something else?

I did see the comment "I thought extensions could not run in the reader view." in Issue #76 - but I observed that other extensions work just fine while viewing a page with 'reader view'.

![Screenshot (2)](https://user-images.githubusercontent.com/25568254/63376771-75e9ea00-c343-11e9-84c2-5b58ba01c9da.png)

**Environment**
 Firefox Quantum 68.0.1 (64-bit); Windows 10 Home 1903 (OS Build 18362.295)

**Comment by gildas-lormeau** [comment]
I should have given more details. Actually, some extensions may work but any extension that needs to execute [content scripts](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/Content_scripts) (this is the case of SingleFile) wan't work in the reader view. Here is the issue on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1371786.

**Comment by theunbob** [comment]
Thanks for clarification. Voted on Bugzilla!

**Comment by gildas-lormeau** [comment]
@theunbob Thank you!

**Comment by gildas-lormeau** [comment]
@theunbob You might be interested by this userscript https://gist.github.com/gildas-lormeau/963f363bce2a7bdb53b46ec74e11bf5c which could fix your issue. To use it, enable the hidden option userScriptEnabled by exporting the settings from the options page, editing the JSON file, replacing `userScriptEnabled: false` with `userScriptEnabled: true`, and importing the modified file in SingleFile.

Then, you can import the userscript in an extension like TamperMonkey. You should see the page going into a reader mode just before being saved.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because I can't fix it in SingleFile and I proposed a workaround. Feel free to re-open it if necessary.

**Comment by gildas-lormeau** [comment]
@theunbob The new version 1.17.0, currently being reviewed by Mozilla and which should be available soon for download provides a new button "Format the page for better readability" in the annotation editor. By clicking on this button, the page will be formatted in the same way as the reader view.
