### ISSUE TITLE
SingleFile do not keep settings 

### ISSUE THREAD

**Issue by davidovic123** [gildas-lormeau/SingleFile#259]
SingleFile don't keep our settings after cleaning the browser. At the restart, all the settings are reinitialized. Then our settings are lost. 
For example, the form of the file name after the save page which return to the previous situation.

![SilngleFile settings](https://user-images.githubusercontent.com/54600718/63805195-ca2b3600-c910-11e9-9cce-ee20435b74a7.jpg)

**Comment by gildas-lormeau** [comment]
What do you mean by "cleaning the browser"?

**Comment by davidovic123** [comment]
"cleaning the browser" is when we clean history, navigation, cache, junk files,, etc using programs such as ccleaner, ashampoo winoptimizer, anti-viruses cleaning...
I'm not sure that's the direct reason of losing settings but I guess that it is.
The fact is the settings turn to the previous situation after my browser cleaning and after opening my new session in the laptop.
The fact is this = our settings in SingleFile options are lost, we don't find them and keep them unchanged all over opening the new sessions.
Thx

**Comment by gildas-lormeau** [comment]
Thanks for the details. SingleFile uses the standard way to store user-settings (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local). I'm a bit surprised the settings are reset by the cleaning tools you cited. Do you know an example of extension that stores user settings that does not suffer from this issue?

**Comment by gildas-lormeau** [comment]
I'm fixing closing issue because I consider I use the recommended API to store the settings. I don't plan to avoid cleaning tools to reset SingleFile settings, I guess it's a feature.

**Comment by gildas-lormeau** [comment]
@davidovic123 The version 1.13.14 which will be available very soon for download has a new option "synchronize options". Enabling it should fix your issue.
