### ISSUE TITLE
SingleFile breaks Transifex webpage

### ISSUE THREAD

**Issue by jakseb** [gildas-lormeau/SingleFile#260]
https://www.transifex.com/toofishes/archlinux-pacman/viewstrings/ does not work if SingleFile is enabled.

**To Reproduce**

1. Go to the mentioned URL. You need to be logged in.
The page looks like this:
 
![screenshot: initial view](https://user-images.githubusercontent.com/23054974/63976202-157c4a80-cab1-11e9-89f0-70b38f07a79e.png)

2. Click the 'Choose a language' field. Select, for example, Arabic.
3. Nothing happens.

**Expected behavior**

With SingleFile disabled, a list of resources is shown:

![screenshot: language selected](https://user-images.githubusercontent.com/23054974/63974413-190dd280-caad-11e9-9319-a8cf4f34cd3a.png)

**Environment**

 - OS: Arch Linux
 - Browser: Firefox 68.0.2 (64-bit)

**Additional context**

Relevant messages from the console:
```
TypeError: console.warn is not a function    content-hooks-frames-web.js:230:12
TypeError: Editor.router is undefined        64dcd18966c2.js:110:1
The Web Console logging API (console.log, console.info, console.warn,
console.error) has been disabled by a script on this page.
```

**Comment by gildas-lormeau** [comment]
Thank you for the bug report and the pull request.

If you can test the master branch, please confirm me the fix works for you too.

**Comment by gildas-lormeau** [comment]
The last commit ensures that if the web page overloads the method `console.warn` (but not the `console` object), the warning will still be displayed without crashing.

**Comment by gildas-lormeau** [comment]
I published the fix in the version 1.11.34 because it was an important issue. Please let me know if you have any remark.

**Comment by jakseb** [comment]
I confirm that your fix works. And, indeed, it is better than mine.

**Comment by gildas-lormeau** [comment]
Great! I'm sorry I did not merge your pull request. That's mainly my fault because the code is not documented and you could not guess what the "right fix" was.

**Comment by jakseb** [comment]
I noticed that the fix would not work if the script messing with `console` were placed in `<head>`. [Test page][githack] ([source][gist]). Your scripts run later. Therefore it might be a good idea to somehow make them execute earlier or at least swallow exceptions from calls to `warn()`, just in case.

[gist]: https://gist.github.com/jakseb/daced16e31c27eb922c5142c0dce8f21
[githack]: https://gistcdn.githack.com/jakseb/daced16e31c27eb922c5142c0dce8f21/raw/8be779413ebdd2f1e55956cfe08c234c7a8fee5e/console.html

**Comment by gildas-lormeau** [comment]
So, I went back and forth and I finally decided to implement somewhat your suggestion. Inlining script contents would fix this issue (https://github.com/gildas-lormeau/SingleFile/commit/9889578964051da701e5d5d138be7c6f29939aee which has been rollbacked) but these scripts would not be executed if the CSP of the page disallows it. Thank you for the test page, it was really useful ;)
