### ISSUE TITLE
Transifex conflict

### ISSUE THREAD

**Issue by solokot** [gildas-lormeau/SingleFile#263]
**Describe the bug**
The extension interferes with the work of the Transifex website (https://www.transifex.com): the form for choosing the language for translation is blocked. Disabling the extension solves the problem.

**To Reproduce**
1. Open https://www.transifex.com
2. Log in on the site, open (any) translation project, in which you are already a member of the translation team, select the resource for the translation ...
3. ... and can not select a language for translation in the form
4. After disable extension Transifex works fine

**Screenshots**
![screenrecord](https://user-images.githubusercontent.com/25316928/64060638-718dbe80-cbd8-11e9-875a-9130e3407392.gif)

**Environment**
 - OS: Windows 7 x64
 - Browser: Waterfox 58, Chrome 69

**Additional context**
The problem is the same for Chrome and Firefox.

**Comment by gildas-lormeau** [comment]
Please make sure SingleFile is up to date. This bug was fixed yesterday, cf. https://github.com/gildas-lormeau/SingleFile/issues/260.
