### ISSUE TITLE
out of 117 tabs only 104 are actually saved

### ISSUE THREAD

**Issue by eixan** [gildas-lormeau/SingleFile#264]
**Describe the bug**

When I opened the bookmark containing the same 117 tabs shown in the video below in my normal profile  it only saved like 20 tabs,they are all from /r/ecchi post's.

**To Reproduce**
Steps to reproduce the behavior: https://drive.google.com/file/d/1SbMteCu75mhOAjCd5Px_SjBbYPk1pMui/view?usp=sharing

**Expected behavior**

**Screenshots**

**Environment**
 - OS: Windows 10 Pro Version:1903 OS Build:18362.295
 - Browser: Chrome 64 bit Version 76.0.3809.132  
 - Version: [e.g. 64]

**Additional context**

**Comment by gildas-lormeau** [comment]
I'll try to do some tests with a high number of tabs. Are you sure all the tabs were finished being processed?

**Comment by gildas-lormeau** [comment]
I did 2 separate tests by using this site https://trackthis.link/. It allows to open 100 tabs with different web sites. I removed from the 100 tabs the ones that could not be fully loaded. Then, I saved all the tabs, and it worked fine. You can enable the setting `User interface > auto-close the tab after the page is saved` to identify easily tabs that would cause issues.

**Comment by eixan** [comment]
That setting exposed the fact that I did not realize  there were tabs off screen. You see chrome used to make the tabs much smaller  to squeeze all the tabs into one window. About the size of a tab that's 'pinned. So I figured I was all seeing all the tabs.
