### ISSUE TITLE
Doesn't save files properly after the last update

### ISSUE THREAD

**Issue by alekssmitt** [gildas-lormeau/SingleFile#265]
Files saved on the hard drive doesn't re-save along with their stylesheets, and all the pictures are gone missing

In the nutshell - before the last update all was all right, after - all gone haywire.

Please restore previous version.

**Environment**
 - OS: Win7 Pro
 - Browser: Chrome
 - Version: 64

**Comment by gildas-lormeau** [comment]
@alekssmitt I cannot reproduce the bug you're describing. Did you try to follow the procedure to [debug unknown issues](https://github.com/gildas-lormeau/SingleFile#troubleshooting-unknown-issues)?

**Comment by alekssmitt** [comment]
[https://my.cloudme.com/alekssmitt/An%20Inexpensive%20X-ray%20Machine](url)
Try it yourself.

**Comment by alekssmitt** [comment]
copy + paste the link in a new window, download it, it is the ordinary saved article, try to re-save it

**Comment by gildas-lormeau** [comment]
Can you confirm you're using the last version of SingleFile? I fixed an issue yesterday that is maybe related to this one.

**Comment by alekssmitt** [comment]
Yes, I checked it, before making zip. And version is 1.11.35

**Comment by alekssmitt** [comment]
And I think that maybe this is something with relative links in HTML

**Comment by alekssmitt** [comment]
That's what I mean:
  <img src = "fig225.jpg" alt="figure 225">

**Comment by gildas-lormeau** [comment]
I'm really sorry. I did not read the issue description carefully and I did not notice it was happening with pages on filesystem only (or almost). FYI, this regression was occurring if a resource did not have any "content type", which is the case when it is read from the filesystem. It should be fixed in the version 1.11.36 I've just published.

**Comment by alekssmitt** [comment]
Yes, you did it, v.1.11.36 work like a charm!
