### ISSUE TITLE
SingleFile as an API

### ISSUE THREAD

**Issue by gitgiggity** [gildas-lormeau/SingleFile#267]
I want to add SingleFile as a library to an extension that I am currently building (to do with Native Messaging).
My extension needs to save complete web pages as part of its function, and SingleFile parsing capability is perfect for this.

1) From Content Scripts (current tab) in my extension, what function should I call to silently capture a complete page into a variable?

2) I don't require the UI/Feedback parts, I only want to capture the page silently (my own extension already provides feedback in the sidebar), so, what folders/files from your project do I need to include in my extension, as a minimum?

I looked at the documentation, FAQ, and even the closed questions/issues for any information/examples towards a SingleFile API. If I've missed anything please direct me to the correct place.

**Comment by gildas-lormeau** [comment]
The API is still a work in progress. That's why it's not documented yet. However I'm quite satisfied with the interface currently existing.

To use the library part of SingleFile, you have to include as content scripts (files in `lib/*/content` folder) and background scripts (files in `lib/*/bg` folder) these scripts:
 * everything in the `/extension/lib` folder
 * everything in the `/lib` folder

Then, you have to execute the code below as a content script when you want to capture the page.

`const pageData = await singlefile.lib.getPageData(options, { fetch: singlefile.extension.lib.fetch.content.resources.fetch });`

The options object should contain the options to pass to SingleFile. I highly recommend you to use the default settings defined in `/extension/core/bg/config.js` (see below). Note that some of these options are related to the UI and won't have any effect (e.g. `includeInfobar`, `confirmInfobarContent`, `shadowEnabled` etc.)

https://github.com/gildas-lormeau/SingleFile/blob/fdd9e5768669400c2d226c9bde89c6f9d364663e/extension/core/bg/config.js#L34-L79

The `pageData` object has a property `content` containing the content of the page and a property `filename` containing the generated filename (if the option `filenameTemplate` is defined).

If you want to process pages in the background script, it will be a little bit more complicated but it's feasible (that's how the auto-save works).

**Comment by gitgiggity** [comment]
First of all, thank you for your detailed reply.

I placed your project in a _lib/libraryname_ sub folder, as I usually do with other libraries such as bootstrap and jquery, but I remained puzzled for hours as to why yours wasn't working, until I discovered that many file paths have been hardcoded in your project.
I guessing that this is one of those "work in progress" you were talking about.

I used a regex search pattern `"/((lib|extension|common)/[^"]*)"` and a replace pattern `"/lib/singlefile/$1"` to normalize all the paths in the js files.

There was also a problem with `async inject(tabId, options)` (_extension\lib\core\bg\scripts.js_) where it complained that `options` was undefined, so I manually added the options your provided to the start of that function too.

When I call `singlefile.extension.lib.core.bg.scripts.inject`, it returns and seems to be working.
When I call `singlefile.extension.getPageData`, it never returns.

Please advise,

Much appreciated.

**Comment by gildas-lormeau** [comment]
To make things simpler, I created a simple project showing you how to use the code necessary for using SingleFile as a library. Basically, I followed the steps I described in my first response. The "interesting" files are in '/extension/core'. Please let me know if you need more info or have any question.

[singlefile - lite.zip](https://github.com/gildas-lormeau/SingleFile/files/3569701/singlefile.-.lite.zip)

**Comment by gitgiggity** [comment]
Excellent!

The extension/library you have attached works flawlessly. I think it is because you removed/detached some UI dependencies. Using the same file layout, I could not get the official one to work. _I would like to use/adapt the official one in order to keep up with updates._

As for the `options` parameter being undefined, I finally discovered that the `inject` function takes two parameters (`tabId, options`), where I had been supplying only `options`, but JavaScript offered no hint whatsoever, _sigh!_

I am a C# programmer, accustomed to strongly typed functions and variables. JavaScript really confuses me, which is why I'm writing my extension with Bridge.NET

I really appreciate you having walked me through all the steps.
Thank you for all your help.

**Comment by gildas-lormeau** [comment]
Note that I just updated the zip (approx 10 min ago). Regarding the issue with `(tabId, options)` parameters, it's my fault, I wrote `(options)` initially.

You *should* be able to get the same project than mine by following the steps described in my first answer. Please retry and let me know if works for you.

**Comment by gitgiggity** [comment]
I decided to make a batch file ([SingleFileExtract.zip](https://github.com/gildas-lormeau/SingleFile/files/3572480/SingleFileExtract.zip)) to mirror SingleFile files from a list of all SingleFile-Lite files.
The result is perfectly functional.

The [regex process](https://github.com/gildas-lormeau/SingleFile/issues/267#issuecomment-527322331) is still necessary in order to place the library under `lib/singlefile/...`

Yours is the best extension for extracting a complete webpage, and I'm happy to be able to incorporate it as a library in my project.

Thank you very much for all your help, @gildas-lormeau.

**Comment by gitgiggity** [comment]
I think I found a bug, complaining that `method` variable doesn't have a specific function.
It maybe due to my own messages being captures by your listener, whereby `method` appears to be undefined.

```
extension\lib\fetch\bg\fetch-resources.js
Line: 33
```
Easily fixed:
- by changing this:
- `if (message.method.startsWith("fetch")) {`
- to this:
- `if (message.method && message.method.startsWith("fetch")) {`

**Comment by gildas-lormeau** [comment]
Indeed, my code can conflict yours in this case, I'll fix that. Thanks.

**Comment by gildas-lormeau** [comment]
I applied your fix. I forgot to thank you for the batch file. I hope it will be useful for anyone that would want to integrate SingleFile in an extension. I'm also glad you're happy with SingleFile :).

**Comment by gildas-lormeau** [comment]
I added a new option `basePath` that allows you to avoid to replace hard-coded paths in your script. Now, you just have to set it via the options object. For example:
```
const options = {
  // ....
  basePath: "lib/singlefile"
};
```

**Comment by gildas-lormeau** [comment]
I'm closing this issue because I created a page in the wiki which explains how to integrate the API into an extension here https://github.com/gildas-lormeau/SingleFile/wiki/How-to-integrate-the-API-of-SingleFile-into-an-extension. This is a work in progress.

**Comment by heavenkiller2018** [comment]
oh, i need this too!

**Comment by gildas-lormeau** [comment]
@heavenkiller2018 Did you look at this document https://github.com/gildas-lormeau/SingleFile/wiki/How-to-integrate-the-API-of-SingleFile-into-an-extension which explains how to do so?
