### ISSUE TITLE
Capture Scroll down transitions

### ISSUE THREAD

**Issue by lucasverra** [gildas-lormeau/SingleFile#268]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when using SingleFile and animations/transitions are not captured

**Describe the solution you'd like**
SingleFile to capture scrolling transitions

**Additional context (optional)**
ex site 

https://libra.org/en-US/ vs `SigleFile copy hosted on netlify` => https://affectionate-curran-7dd332.netlify.com/

**Comment by gildas-lormeau** [comment]
Unfortunately, this is not technically possible with SingleFile. This issue is related to the fact that this page is relying on JavaScript to animate contents and that SingleFile removes all the scripts by default. SingleFile removes the scripts because saving them, most of the time, won't give the expected result. I tried to save the page you linked with the options "Misc > save raw page" enabled and "Other resources > remove scripts" disabled but it does not help to keep the animations.

**Comment by lucasverra** [comment]
OK, and besides SFile what would be your recommendation in order to capture the full UX (animatations) of that landing page ?

**Comment by gildas-lormeau** [comment]
I'm unsure you will find a tool that will be able to capture animations on this website. Your best option, I guess, would be to save the page in the WARC format (https://warcreate.com/). I did not test it though.

**Comment by lucasverra** [comment]
ok, i guess i can close this Frequest. Thanks for the support ! ✌🏼

**Comment by gildas-lormeau** [comment]
You're welcome. Note that enabling "Misc > save raw page" and disabling "Other resources > remove scripts" may work sometimes. For example, it works for saving animations on https://onewave.io/. I would need to debug libra.org to understand what's wrong on this particular website...

**Comment by lucasverra** [comment]
Let me know, i find that libra/wordpress well rounded in UX terms. Animations yes, but lean and subtle.

**Comment by lucasverra** [comment]
> Unfortunately, this is not technically possible with SingleFile. This issue is related to the fact that this page is relying on JavaScript to animate contents and that SingleFile removes all the scripts by default. SingleFile removes the scripts because saving them, most of the time, won't give the expected result. I tried to save the page you linked with the options "Misc > save raw page" enabled and "Other resources > remove scripts" disabled but it does not help to keep the animations.

hello there , im not finding options/misc anywhere (latest FF) 🤔
Customize take me to FF customization page for bar icons ..

<img width="446" alt="image" src="https://user-images.githubusercontent.com/11323803/67787690-478a3880-fa71-11e9-9479-ced1bc91016e.png">

**Comment by gildas-lormeau** [comment]
I did some additional debugging and I'm still concluding SingleFile cannot save JavaScript animations on this website. It's too bad they don't use CSS animations or transitions that have been specified approximately 10 years ago...
