### ISSUE TITLE
 wrapper that can be invoked from bash shell or python console

### ISSUE THREAD

**Issue by stjordanis** [gildas-lormeau/SingleFile#270]
This is the best web scraper, thank you so much; It would be useful to so many if ported it to python.
Could you make an interface so we can use it in python (or bash shell) by using selenium for instance?
Thank you
The function arguments will include the web link and download location,  selenium will read the cookies from the system and Singlefile wrapper will do the rest. 
Maybe this could be useful :
  https://github.com/n8henrie/pycookiecheat
I could also help with python, btw

**Comment by gildas-lormeau** [comment]
Well, I don't know Python. However, if you know a little bit JavaScript, I think that all you have to do is to convert https://github.com/gildas-lormeau/SingleFile/blob/master/cli/back-ends/webdriver-chromium.js or https://github.com/gildas-lormeau/SingleFile/blob/master/cli/back-ends/webdriver-gecko.js into the equivalent Python script.

**Comment by stjordanis** [comment]
Thank you for your prompt reply, I will try all your suggestions

**Comment by gildas-lormeau** [comment]
You're welcome :)
