### ISSUE TITLE
Clicking the "+" icon should copy over the settings from currently selected profile into the new one

### ISSUE THREAD

**Issue by artyfox** [gildas-lormeau/SingleFile#272]
Is it possible to implement a quick select menu for saving under different option sets?

For example, I'd like to be able to right-click the toolbar icon and be able to save with "scripts enabled" or "scripts disabled" (two profiles).

This would make your extension super convenient! 🦊

**Comment by gildas-lormeau** [comment]
If I'm not wrong, SingleFile implements already what you suggest.

**Comment by artyfox** [comment]
Ah, you're right! Sorry, I didn't see that! 

I have a quick suggestion though. When you click the "+" icon to create a new profile, it should copy over the settings from currently selected profile into the new one.

For example, I have the ["tabMenuEnabled": false hidden setting](https://github.com/gildas-lormeau/SingleFile/issues/240). It would be nice if to have that automatically be applied to a derivative profile. 

Thanks! 🦊

**Comment by gildas-lormeau** [comment]
It should be possible. I updated of the issue accordingly.

**Comment by gildas-lormeau** [comment]
This feature will be available in the upcoming version of SingleFile.

**Comment by gildas-lormeau** [comment]
Available in the version 1.11.39.
