### ISSUE TITLE
Add a "Last used location (Instead of Downloads)" option

### ISSUE THREAD

**Issue by imtoao** [gildas-lormeau/SingleFile#273]
**Is your feature request related to a problem? Please describe.**
I never store files on "Downloads" folder as it just creates a mess. In addition, I always use a meaningful name for each file I save so I can quickly/easily locate later on. The problem with the add-on is that it always defaults to "Downloads" folder (Not the last used folder). Thus, for each file going to the same folder, I need to navigate all folder levels again which can be iincredibly annoying when saving many files (Which I usually do for documentation purposes). Using the multi-file save is of no use in this case because it would assign meaningless automatic names. That said, it would be nice to add the same feature for both single-file and multi-file operations.

**Describe the solution you'd like**
Please include one additional option called: 
    Save the file on the "last used folder" instead of "Downloads"

**Describe alternatives you've considered (optional)**
If not too much trouble, it would be nice to also have a "Always save files on (Browse)" option.

Thanks in advance.

Regards

**Comment by gildas-lormeau** [comment]
This option already exists but is not called like you suggested. It's documented in the [known issues](https://github.com/gildas-lormeau/SingleFile#known-issues).
```
The last saved path cannot be remembered by default. To circumvent this limitation, disable the option "Misc > Save pages in background"
```

**Comment by imtoao** [comment]
Thanks for the quick response!
I checked the open issues but did not check that. I've just tested it and it works!
Thank again!
Regards

**Comment by gildas-lormeau** [comment]
You're welcome
