### ISSUE TITLE
Bug in SingleFile Chrome extension !!!

### ISSUE THREAD

**Issue by on1no** [gildas-lormeau/SingleFile#274]
Hi
And Sorry For My Bad English

The SingleFile Firefox extension Working Great And file name saved correctly with date And Time
**BUT**
The SingleFile Chrome extensionn when saving file names it saved with random numbers Letters No Date and No Time

Please See The Youtube Link its will explain everything
https://youtu.be/Ic0PkH5n9ug

**Comment by gildas-lormeau** [comment]
It's a bug in Chrome and unfortunately, I don't really know how to fix it. You can circumvent it by disabling the option "Misc > Save pages in background" as indicated in the [known issues](https://github.com/gildas-lormeau/SingleFile#known-issues). Reinstalling Chrome may also fix this issue.

**Comment by on1no** [comment]
its working 👍 (disabling the option "Misc > Save pages in background) did the trick  👍 👍

thank you thank you so much 😎😎

**Comment by gildas-lormeau** [comment]
You're welcome :)
