### ISSUE TITLE
SingleFile CLI get a 404 error

### ISSUE THREAD

**Issue by bansan85** [gildas-lormeau/SingleFile#275]
**Describe the bug**
Single-file CLI have a 404 error with a valid URL.

**To Reproduce**
1. Get SingleFile f38ec8c97b07fa328b91d00c3db6e38ca6aef4ab
2. run ```single-file.bat --browser-executable-path="C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "https://developer.apple.com/library/archive/releasenotes/iPhone/NSFetchedResultsChangeMoveReportedAsNSFetchedResultsChangeUpdate/index.html" here.html```

I have a web page like [this one](https://developer.apple.com/library/archive/releasenotes/iPhone/NSFetchedResultsChangeMoveReportedAsNSFetchedResultsChangeUpdate/indexXXXXXXXX.html)

SingleFile works with other web site.

**Expected behavior**
When I open https://developer.apple.com/library/archive/releasenotes/iPhone/NSFetchedResultsChangeMoveReportedAsNSFetchedResultsChangeUpdate/index.html with Chrome, I can successfully get the page with SingleFile 1.11.42

**Environment**
 - OS: Win10 Pro 1903
 - Browser: Chrome
 - Version: Version 76.0.3809.132 (Build officiel) (64 bits)

**Comment by gildas-lormeau** [comment]
This is due to the value of the user-agent. I guess Apple don't like headless browsers. 

To fix your issue, pass the option `--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36` when launching SingleFile.

**Comment by bansan85** [comment]
Huge thanks. It's working :) . The ```--user-agent``` should be added to the ```--help```.

**Comment by gildas-lormeau** [comment]
Indeed... It's documented now.
