### ISSUE TITLE
Pop up Message partially hidden

### ISSUE THREAD

**Issue by paponius** [gildas-lormeau/SingleFile#277]
**Describe the bug**
Pop up Message on Option page is partially hidden. This is confusing, it looks like something went wrong.

**To Reproduce**
Press Reset button on Option page,
only bottom of message window is visible. Without scrolling up, it looks like an empty bar with Cancel button.

**Expected behavior**
Message will be centered and visible after pressing Reset button.

**Screenshots**
![creenshot](https://user-images.githubusercontent.com/14345371/65059847-00d7f780-d977-11e9-9db2-4d0a36370fce.png)

**Environment**

    OS: Win10 Pro
    Browser: Firefox
    Version: 64

**Comment by gildas-lormeau** [comment]
Thank you again for having reported this issue. I decided to align the popup to the bottom in this case. The popups displayed when creating/updating/deleting profiles are now aligned to the top. The fix is available in the version 1.11.45 I've just published.
