### ISSUE TITLE
Capture multiple tabs in deterministic order

### ISSUE THREAD

**Issue by cy7yz2rj** [gildas-lormeau/SingleFile#278]
**Is your feature request related to a problem? Please describe.**
When capturing multiple tabs, SingleFile appears to process them in parallel, such that when sorting by filesystem mtime the ordering of the html files doesn't mirror the ordering of tabs on the browser window.

**Describe the solution you'd like**
Please consider adding an option to save multiple tabs sequentially, only beginning the capture of the next tab when the previous has completed. Make it disabled by default with a warning that toggling it on may lead to slower total capture time.

**Describe alternatives you've considered (optional)**
Using *{tab-id}* as file name prefix works for alphanum sorting but not for mtime sorting.

**Comment by gildas-lormeau** [comment]
I guess the feature you want is already available by forcing the number of parallel workers to 1. Go to the options page, export the settings, open the json file in a text editor, replace `"maxParallelWorkers": n` (n being the number of core on your CPU) with `"maxParallelWorkers": 1` and import the modified file in SingleFile. Please let me know if this fulfill your needs.

**Comment by cy7yz2rj** [comment]
I didn't know about that option, didn't think of looking in the json file for hidden settings. Anyhow, it does not work, unfortunately.

The order is less "random" with a single thread than with the default but even with as low as ~10 tabs it's very easy to get unordered downloads. Tested on a fresh profile of Firefox ESR, SingleFile 1.11.48 from AMO.

**Comment by gildas-lormeau** [comment]
I think what you want is `{tab-index}` which exists but I forgot to document it. You can set `maxParallelWorkers` to its initial value. I'll try to make sure tabs will be ordered by their index by default so you won't need to use `{tab-index}`.

**Comment by gildas-lormeau** [comment]
I published the version 1.11.50. You can set `maxParallelWorkers` to 1 or use the variable `{tab-index}` to fix this issue.

**Comment by cy7yz2rj** [comment]
Fix confirmed, thanks for all your work with this extension!
