### ISSUE TITLE
Is there a shortcut for “save selected content”？

### ISSUE THREAD

**Issue by shuaiyy** [gildas-lormeau/SingleFile#280]
the current shortcut i could found : 
![](http://bilibili.shuaiyy.cn/bilibili/20190927181046.png)
add a shortcut for “save selected content” will be very helpful, thx.

**Comment by gildas-lormeau** [comment]
No there is not. I think I'll use the default shortcut and implement a "smart save" that will save the page or the selected content if any.

**Comment by shuaiyy** [comment]
thanks for reply,  "smart save" is what i need and i love it !!!

**Comment by gildas-lormeau** [comment]
This feature is implemented in the version 1.11.56 I published. Note for Firefox users: the extension is not published yet (cf. https://github.com/mozilla/addons-server/issues/12503).
