### ISSUE TITLE
Java feature issue

### ISSUE THREAD

**Issue by AliM1988** [gildas-lormeau/SingleFile#281]
**Describe the bug**
Some sites have some java code to group information with hide/unhide them (like as bullet, + sign, ...). SingleFile has problem with some of them even you disable option "remove scripts".

**To Reproduce**
1. Go to 'https://www.balena.io/etcher/'
2. Disable option "remove scripts" in SingleFile
3. Save page and then open saved page
4. You see + signs don't work and the information can't be unhide.

**Expected behavior**
It's expected to unhide text when users click on + sign (in saved page)

**Environment**
 - OS: Win8,
 - Browser: Chrome
 - Version: 75.0.3770.100 (Official Build) (64-bit)

**Comment by gildas-lormeau** [comment]
Unfortunately, it's impossible for SingleFile to guarantee scripts will work. That's why the option is checked by default. The website you're referring to is a good example to illustrate this issue.
