### ISSUE TITLE
Trouble with frames

### ISSUE THREAD

**Issue by gitgiggity** [gildas-lormeau/SingleFile#284]
[This link](https://pubs.vmware.com/workstation-9/index.jsp?topic=%2Fcom.vmware.ws.using.doc%2FGUID-AB5C80FE-9B8A-4899-8186-3DB8201B1758.html) results in a blank page when saved.

I saw a lot of frameset references in the source of that page. And [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frameset) says that frameset is being discontinued.

I'm not sure this is an issue unique to SingleFile, yet if the page is able to render, perhaps it should be able to save too.

**Comment by gildas-lormeau** [comment]
Thank you for having reported this bug. I was able to reproduce it and fix it. I will publish a new version with the fix soon.

**Comment by gildas-lormeau** [comment]
It's fixed in the version 1.11.59.
