### ISSUE TITLE
Possible basePath side effect

### ISSUE THREAD

**Issue by gitgiggity** [gildas-lormeau/SingleFile#285]
For every page loading, browser console shows:

`Security Error: Content at https://example.com/ may not load or link to moz-extension://00000000-0000-0000-0000-000000000000/lib/hooks/content/content-hooks-web.js.`
`Security Error: Content at https://example.com/ may not load or link to moz-extension://00000000-0000-0000-0000-000000000000/lib/hooks/content/content-hooks-frames-web.js.`

Note that it doesn't have the correct `lib/singlefile` prefix that I've supplied to basePath (e.g. `lib/singlefile/lib/hooks/content/content-hooks-web.js`)

It doesn't seem to hinder any performance, but I thought that since it's a Security Error, then it may be worthy of note.

**Comment by gildas-lormeau** [comment]
Indeed, the files ending with "-web.js" cannot be moved. This issue cannot be fixed because these scripts must be injected as soon as possible otherwise they won't work properly. Unfortunately, it's impossible to read the option synchronously. I will remove the documentation about `basePath` because it's broken.

**Comment by gildas-lormeau** [comment]
I think you'll like the new directory structure.

**Comment by gitgiggity** [comment]
Yikes!
Well, I'll continue to use basePath because it remains necessary in order to organize the libraries that my project depends on.

**Comment by gitgiggity** [comment]
The new directory structore looks interesting, but I don't know how to use it, LOL.
I referenced the same files as before, but all I get is `AbortError: The operation was aborted`
I even double checked against the new manifest.json

**Comment by gildas-lormeau** [comment]
That's a weird error! I did not test the manifest.json in the wiki yet because it's just a matter of renaming paths. I'll do some tests...

**Comment by gildas-lormeau** [comment]
I did some tests and it works fine for me. Here is the extension in the zip file.

[singlefile - lite.zip](https://github.com/gildas-lormeau/SingleFile/files/3686294/singlefile.-.lite.zip)

**Comment by gitgiggity** [comment]
I just `tried singlefile - lite`

Browser Console shows:
```
undefined is not a valid URL. background.js:321
    onBeforeRequest moz-extension://b26b80eb-3597-45af-8c73-22d0bea3a637/background-scripts
/background.js:321
    apply self-hosted:4417
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:588
    fire resource://gre/modules/ExtensionChild.jsm:1171
    receiveMessage resource://gre/modules/ExtensionChild.jsm:1175
    _callHandlers resource://gre/modules/MessageChannel.jsm:914
    _callHandlers resource://gre/modules/MessageChannel.jsm:913
    promise resource://gre/modules/MessageChannel.jsm:992
    _handleMessage resource://gre/modules/MessageChannel.jsm:989
    _handleMessage self-hosted:1005
    receiveMessage resource://gre/modules/MessageChannel.jsm:225
    forEach self-hosted:266
    receiveMessage resource://gre/modules/MessageChannel.jsm:218
<unavailable>
```

**Comment by gildas-lormeau** [comment]
There is no `background.js` file in the project. Please check what is the extension having as ID "b26b80eb-3597-45af-8c73-22d0bea3a637". This info can be found in the page used to install manually extensions.

**Comment by gitgiggity** [comment]
That ID belongs to HTTPS Everywhere.
I did like before, and disabled all other extensions.
Then I only got `<unavailable>` in the Browser Console.

**Comment by gildas-lormeau** [comment]
Are you looking at the console in the tab, not the one attached to the background script?

**Comment by gitgiggity** [comment]
Both consoles, Browser console, and Inspect/Debug console, show the same `<unavailable>`.

**Comment by gildas-lormeau** [comment]
If I install the extension I attached and I go to example.com, here is below what I see

![image](https://user-images.githubusercontent.com/396787/66160286-1a8d6600-e62a-11e9-8222-604881719544.png)

**Comment by gitgiggity** [comment]
First of all, thank you for your patience.
I was looking in the `Ctrl+J` console.
After seeing you screenshot, I suddenly remembered the `F12` console (very embarrassed).
It's working exactly as in your screenshot.

Now, when I move `extension` into `lib/single-file/extension`, then I get that `AbortError: The operation was aborted.` that I originally told you about.

I honestly thing `basePath` was a tidy and superior solution, instead of having some files under `lib/single-file`, and other files under `extension`, which is just messy.

**Comment by gitgiggity** [comment]
Okay, I've gone back to my very very earlier solution of RegEx search and replace.

I think it's the only _neat_ solution that will work, until those hard coded paths are revised into something like a global list variable.

Thank you for all your help.

**Comment by gildas-lormeau** [comment]
No problem for the issue related to the debugger.

I'm sorry but I don't want to introduce a build step and it's, as far as I know, the *only way* to solve the base folder issue. I did my best to make things simple. I consider that copying 2 folders to import SingleFile in any extension is not too constraining. I also want that `/lib` does not contain any code dependent on APIs of Web Extension.

**Comment by gitgiggity** [comment]
I really appreciate your work and how you've patiently walked me through the steps of integrating your _new_ API.

My desire to have the Libraries/APIs in my project situated under their own individual sub-folders, is perhaps aesthetical. It's a habit I've developed through my programming years, especially while dealing with MVVM where separation is considered a virtue.

RegEx search and replace will suffice for now, so long as it satisfies the aforementioned aesthetics ;-)

**Comment by gildas-lormeau** [comment]
You're welcome. By the way, if your regexp (that you could run in a build script on all files) is similar to replacing all occurrences of `extension/lib` with `lib/single-file/extension/lib`, you should be pretty safe. I just did the test and it worked fine, cf. the attached file. I don't think I will change the structure of the project soon ;).

[singlefile - lite.zip](https://github.com/gildas-lormeau/SingleFile/files/3688453/singlefile.-.lite.zip)
