### ISSUE TITLE
Image with better quality

### ISSUE THREAD

**Issue by alk1895** [gildas-lormeau/SingleFile#286]
When the "remove images for alternative screen resolutions" option is checked, keep the image with better quality.

This is not a problem at the moment, just a suggestion that would be great if I had it.

Thanks for the great extension.

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. I find it's an interesting feature. I think I'll add a [hidden option](https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options) that will you allow to save images with better quality once enabled.

**Comment by gildas-lormeau** [comment]
I'm unsure the idea I had in mind is a good one actually. I was thinking about using the info in the `media` attribute of the `<source>` tag to determine levels of quality. You can find more info about this feature here: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images. 
However, this property is also used to adapt images to the orientation of the device. This is for example the case here https://mdn.github.io/learning-area/html/multimedia-and-embedding/responsive-images/responsive.html. You can resize the width of the browser to see how images adapt themselves to the width of the device. Let's say a user saves this page in Firefox for Android in portrait mode and set to "high" the "image quality" option, should SingleFile save the image intended to be displayed on desktop (i.e. in landscape mode)?

**Comment by gildas-lormeau** [comment]
I'm closing the issue because I think it's more complicated than expected to implement properly. Feel free to comment or re-open the issue if you think I missed something.

**Comment by neviln** [comment]
I know this was an old topic, but I was really hoping to find some kind of solution or workaround. I'm in the process of selling my current house to move into a different house and was trying to save some real estate listings I found.
For whatever reason, the pages kept saving with the lowest resolution image out of the  5 options available linked in **srcset** . 

I spent several hours tinkering with settings in SingleFile; using Chrome DevTools in hopes to trick the browser into using one of the higher res images; and trying other various suggestions I found on forums, but ultimately, the 70+ SingFile saves all kept using the lowest quality images. 

This is a sample of one of the img tags on the real estate listing page:
```
<img class="img-responsive center-block lazyloaded" width="753" height="500" data-src="https://rew.ca/01.jpeg?auto=format&crop=top%2C%20left&fit=fill&fill=blur&ixlib=react-9.7.0&h=500&w=753" data-srcset="https://rew.ca/01.jpeg?auto=format&crop=top%2C%20left&fit=fill&fill=blur&ixlib=react-9.7.0&w=753&h=500&dpr=1&q=75 1x,
https://rew.ca/assets/01.jpeg?auto=format&crop=top%2C%20left&fit=fill&fill=blur&ixlib=react-9.7.0&w=753&h=500&dpr=2&q=50 2x,
https://rew.ca/assets/01.jpeg?auto=format&crop=top%2C%20left&fit=fill&fill=blur&ixlib=react-9.7.0&w=753&h=500&dpr=3&q=35 3x,
https://rew.ca/assets/01.jpeg?auto=format&crop=top%2C%20left&fit=fill&fill=blur&ixlib=react-9.7.0&w=753&h=500&dpr=4&q=23 4x,
https://rew.ca/assets/01.jpeg?auto=format&crop=top%2C%20left&fit=fill&fill=blur&ixlib=react-9.7.0&w=753&h=500&dpr=5&q=20 5x" srcset="https://rew.ca/assets/01.jpeg?auto=format&crop=top%2C%20left&fit=fill&fill=blur&ixlib=react-9.7.0&w=753&h=500&dpr=1&q=75 1x,
https://rew.ca/assets/01.jpeg?auto=format&crop=top%2C%20left&fit=fill&fill=blur&ixlib=react-9.7.0&w=753&h=500&dpr=2&q=50 2x,
https://rew.ca/assets/01.jpeg?auto=format&crop=top%2C%20left&fit=fill&fill=blur&ixlib=react-9.7.0&w=753&h=500&dpr=3&q=35 3x,
https://rew.ca/assets/01.jpeg?auto=format&crop=top%2C%20left&fit=fill&fill=blur&ixlib=react-9.7.0&w=753&h=500&dpr=4&q=23 4x,
https://rew.ca/assets/01.jpeg?auto=format&crop=top%2C%20left&fit=fill&fill=blur&ixlib=react-9.7.0&w=753&h=500&dpr=5&q=20 5x" src="https://rew.ca/assets/01.jpeg?auto=format&crop=top%2C%20left&fit=fill&fill=blur&ixlib=react-9.7.0&h=500&w=753">
```

Is there any kind of workaround for this....via SingleFile settings; or changing a setting in Chrome DevTools; or manually inserting some CSS into the page, like the viewport meta tag:
`<meta name="viewport" content="width=1920, initial-scale=3">`
or a media:
`@media only screen and (min-width: 1920px)`

Any help would be greatly appreciated. And thank you so much for such an amazing extension. Aside from uBlock, SingleFile is my most used Chrome extension.
