### ISSUE TITLE
"save selected" missing in macOS 10.15

### ISSUE THREAD

**Issue by MagisDing** [gildas-lormeau/SingleFile#287]
I am not sure if this is a bug or not, I found "Save Selected" missing after upgrading to macOS Catalina. The feature was very handy, I could use SingleFile as a perfect replacement for Evernote web clipper.
(https://cl.ly/7b7a6d38ba7e)
Can we specify the auto-save path other than [`~/Downloads`?]

OS: macOS 10.15
Browser: Firefox 69.0.2
SingleFile: 1.29

**Comment by gildas-lormeau** [comment]
Did you enable the "save raw page" option? This may explain why the entry is not present.

You could choose another folder to save pages but that would impact all your downloads. You can however save pages in a sub-directory of the "Downloads" folder by prepending its name into the filename template (cf. help page for more info).

**Comment by gildas-lormeau** [comment]
@MagisDing So, do you confirm you enabled the option?...

**Comment by gildas-lormeau** [comment]
I'm closing the issue because you did not answer to my question. Feel free to re-open it if disabling the option "save raw page" does not fix the issue or if you think it's necessary.
