### ISSUE TITLE
Picture disappears after running SingleFile (v1.11.61) created HTML file.

### ISSUE THREAD

**Issue by streetwolf** [gildas-lormeau/SingleFile#288]
The attached HTML file, within the zip file, created by SingleFile  displays the accompanying picture for a second or two then disappears.

I'm running Fx Nightly on Windows 10 64 bit.

[These 15 retailers need a Merry Christmas (2019-10-09 1_01_01 PM).zip](https://github.com/gildas-lormeau/SingleFile/files/3708586/These.15.retailers.need.a.Merry.Christmas.2019-10-09.1_01_01.PM.zip)

This is the original site I used SingleFile on:

https://www.msn.com/en-us/money/companies/these-15-retailers-need-a-merry-christmas/ss-AAIrVAF?fullscreen=true#image=12

**Comment by gildas-lormeau** [comment]
On my end the image in the HTML file you attached is displayed correctly. However, I noticed the image disappears if the width of the window is less than 1785px. It's related to the way the page has been designed and the fact that it depends on JavaScript to position and resize the image. I can't really fixed that unfortunately.

**Comment by gildas-lormeau** [comment]
So, the only way to see the image is to make sure the resolution of the screen is the same when viewing the page. It's due to the way this page has been designed. I'm closing this issue because it cannot be fixed in SingleFile.
