### ISSUE TITLE
The resulting file is too large.

### ISSUE THREAD

**Issue by alekssmitt** [gildas-lormeau/SingleFile#289]
There is nothing in the file but text. It is saved in txt format with a size of not more than 5 KB, but SingleFile saves it with a size of 500 KB.

100 times bigger, it's a lot!

**Environment**
 - OS:  Win7 Pro
 - Browser:  Chrome
 - Version:  x64

[The definite article with abstract uncountable nouns.zip](https://github.com/gildas-lormeau/SingleFile/files/3712918/The.definite.article.with.abstract.uncountable.nouns.zip)

**Comment by gildas-lormeau** [comment]
Indeed, there are some images that aren't displayed but saved. I'll try to see what I can do to remove them.

**Comment by gildas-lormeau** [comment]
I fixed the issue. I need to do some more tests to make sure the fix does not introduce any regression before publishing it though. I hope I will publish in the next 24 hours.

Note that SingleFile will produce a file almost 5X bigger (!) than the size you would have expected, i.e. the size of the content saved as a text file (5,432 bytes). There are some HTML tags and style sheets to save... 

I attached a zip file containing the saved selection you used as example to illustrate the issue.

[The definite article with abstract uncountable nouns - last version.zip](https://github.com/gildas-lormeau/SingleFile/files/3769795/The.definite.article.with.abstract.uncountable.nouns.-.last.version.zip)

**Comment by alekssmitt** [comment]
> I need to do more tests to make sure the fix does not introduce any regression before publishing it though.

I don't know if this has affected the minor issue below:
![Untitled 1](https://user-images.githubusercontent.com/36442471/67554980-1cbe7e00-f719-11e9-8cc5-6210cb689dee.jpg)
It allows neither deleting nor changing settings

**Comment by alekssmitt** [comment]
In this case, the only hope that they will fix it in the next update.

**Comment by gildas-lormeau** [comment]
Actually, the best way to solve this issue is to report it. I searched for a similar bug on https://bugs.chromium.org/p/chromium/issues/list but I wasn't able to find any similar issue. Please let me know if you want to report it. Otherwise, I'll do it for you.

**Comment by gildas-lormeau** [comment]
I published the fix of the issue you initially reported in the version 1.12.14.

**Comment by gildas-lormeau** [comment]
@alekssmitt  FYI, I filed the issue related to the black rectangle on bugs.chromium.org, cf. https://bugs.chromium.org/p/chromium/issues/detail?id=1018351.

**Comment by alekssmitt** [comment]
> Actually, the best way to solve this issue is to report it.

I totally agree. Somehow it did not occur to me in the first place.

**Comment by alekssmitt** [comment]
And thanks for your work! The resulting files are decreased dramatically.

**Comment by gildas-lormeau** [comment]
You're welcome, I'm glad to hear it :).
