### ISSUE TITLE
Override ALT+Click With SingleFile

### ISSUE THREAD

**Issue by alivefromupstairs** [gildas-lormeau/SingleFile#295]
**The Problem:**
Mass `Save page with SingleFile` requires a lot of right-clicking and going through nested menus.

**The Solution:**
Alt+mouseup saves files already, and it would be good to have an option to use SingleFile to do the saving.
Be mindful of taking over when the intent is to select text without triggering anchor tags, however.

**Comment by gildas-lormeau** [comment]
I don't understand the issue. Isn't mass `Save page with SingleFile` solved with `Save selected tabs`, `Save unpinned tabs` and `Save all tabs`?
What "Alt+Mouseup" is supposed to do? On my end it does nothing at all in Firefox and Chrome. And, how is this related to mass saving?

**Comment by alivefromupstairs** [comment]
> I don't understand the issue. Isn't mass `Save page with SingleFile` solved with `Save selected tabs`, `Save unpinned tabs` and `Save all tabs`?

Oh, I see.

> What "Alt+Mouseup" is supposed to do? On my end it seems this shortcut does nothing at all in Firefox and Chrome. And, how is this related to mass saving?

I tested it on Windows/Chrome and Arch Linux/Chromium and it works as Ctrl+S. `save unpinned tabs` should do it, though. Closing.
 
How does `selected tabs` work?

**Comment by gildas-lormeau** [comment]
By the way, note that there are 2 shortcuts in SingleFile, Ctrl+Shift+Y to save the page or the selected content and Ctrl+Shift+U to save all tabs.

To save selected tabs you can use Ctrl and click on the tabs you want to save. You can also use Shift and click on the first tab and the last tab of a group of tab to save.
