### ISSUE TITLE
Resetting the options fixed issue, but how to determine what the problem actually was?

### ISSUE THREAD

**Issue by ItsExtra** [gildas-lormeau/SingleFile#297]
Thank your for this very handy tool! 

It wasn't working as expected so I followed the troubleshooting instructions. Resetting the options worked. Yay!

However I still don't know _what_ the problem actually was. 

Before resetting, I exported my options so I have them available to compare.

I imagine there is a way to compare the default settings to the ones I was using to see what the difference is. Hopefully, other than manually putting them beside each other and comparing line by line? Is there a tool that can automagically tell the differences in the files? Then I can change the options one at a time to see where the problem lies. (Unless there is an even more efficient method?)

(I'm not a programmer so if you are thinking of something which is very obvious to you, it may not be obvious to me.)

**Comment by gildas-lormeau** [comment]
You can simply attach the exported options to this issue and tell me which URL you saved. It will be easy for me to identify which options you changed.

**Comment by ItsExtra** [comment]
I appreciate the offer but is there a way to do it myself? Id rather not subject someone to such a tedious task...


Oct. 27, 2019, 21:00 by notifications@github.com:

**Comment by gildas-lormeau** [comment]
Yes, there's a way to do it yourself by using, for example, vscode as I explained in my previous answer.

**Comment by ItsExtra** [comment]
I see I'm sorry. 

Lesson learned: dont use the email interface for gh. 

I will try when at my computer.

Thanks!

**Comment by gildas-lormeau** [comment]
Sorry, I guess that's because I edited the message shortly after I posted it in order to add info about vscode.

**Comment by ItsExtra** [comment]
@gildas-lormeau that makes sense! Whatever the etiology I think the point stands about not using the email. :)

So I got vscode and did as you suggested (which is a useful thing to know how to do in any case). However there were so many differences. I started trying one by one enabling/disabling but I got overwhelmed and confused trying to keep track of it all. So I thought that maybe instead of trying to work the program out by the scientific method, I would ask if you have any insight, since you designed it and all. 

So this page, for example, is very strange because when the file loads the whole content flashes quickly, but then disappears. So I do think it's in there someplace. But not displaying. 

Here is a url: 
https://www.aliexpress.com/item/32820090157.html?spm=a2g0o.tm31131.8569345810.1.2d592234gWeTWj&&scm=1007.25281.150765.0&scm_id=1007.25281.150765.0&scm-url=1007.25281.150765.0&pvid=2f7aad5f-f191-4bf7-93ca-a0bb91953e65

Here is the default setting output, which work properly:
![working](https://user-images.githubusercontent.com/54250414/68065125-5e07ec80-fd1c-11e9-95d0-a20258962883.png)

Here is what I get instead:
![not working](https://user-images.githubusercontent.com/54250414/68065138-8bed3100-fd1c-11e9-9ae4-9d23e3fc3e7c.png)

Here are the settings I tried with // on the end of the lines that are changed from the default.

```
    "__Default_Settings 2__": {
      "removeHiddenElements": true,
      "removeUnusedStyles": true,
      "removeUnusedFonts": true,
      "removeFrames": true,  //
      "removeImports": false,  //
      "removeScripts": false,  //
      "compressHTML": true,
      "compressCSS": true,
      "loadDeferredImages": false,  //
      "loadDeferredImagesMaxIdleTime": 1500,
      "loadDeferredImagesBlockCookies": false,
      "loadDeferredImagesBlockStorage": false,
      "filenameTemplate": "{page-title} ({date-iso} {time-locale}).html",
      "infobarTemplate": "{url-href} archived by SingleFile {datetime-utc}",  //
      "includeInfobar": true,  //
      "confirmInfobarContent": false,
      "autoClose": false,
      "confirmFilename": false,
      "filenameConflictAction": "prompt",  //
      "filenameMaxLength": 192,
      "filenameReplacedCharacters": [
        "~",
        "\\\\",
        "?",
        "%",
        "*",
        ":",
        "|",
        "\"",
        "<",
        ">",
        "\u0000-\u001f",
        ""
      ],
      "filenameReplacementCharacter": "_",
      "contextMenuEnabled": true,
      "tabMenuEnabled": true,
      "browserActionMenuEnabled": true,
      "shadowEnabled": true,
      "logsEnabled": true,
      "progressBarEnabled": true,
      "maxResourceSizeEnabled": false,
      "maxResourceSize": 10,
      "removeAudioSrc": false,
      "removeVideoSrc": false,
      "displayInfobar": true,
      "displayStats": false,
      "backgroundSave": true,
      "autoSaveDelay": 1,
      "autoSaveLoad": false,
      "autoSaveUnload": false,
      "autoSaveLoadOrUnload": true,
      "autoSaveRepeat": false,
      "autoSaveRepeatDelay": 10,
      "removeAlternativeFonts": true,
      "removeAlternativeMedias": false,  //
      "removeAlternativeImages": false,  //
      "groupDuplicateImages": false,  //
      "saveRawPage": false,
      "saveToClipboard": false,
      "resolveFragmentIdentifierURLs": false,
      "userScriptEnabled": false,
      "openEditor": false
```

**Comment by gildas-lormeau** [comment]
Thank you. I'll do some tests but I'm pretty sure the issue is related to the fact that "remove scripts" is disabled. Indeed SingleFile can't embed scripts reliably. Sometimes it will work and some other times it won't and unfortunately this cannot be fixed. That's why the option is enabled by default.

**Comment by ItsExtra** [comment]
that's it!

thank you so much

**Comment by gildas-lormeau** [comment]
You're welcome :)

**Comment by sergeevabc** [comment]
How do I reset SingleFile options? Currently the extension does not work at all and its options are empty.

![](https://i5.imageban.ru/out/2020/01/03/18b25660fd5b9421f898d96350780419.png)

**Comment by gildas-lormeau** [comment]
@sergeevabc I cannot reproduce your issue with the latest stable version of Firefox. Since this version of SingleFile is more than one week old and nobody complained about it, I guess this might be specific to your install. Can you please click on the "arrow" icon next to the "+" (below "Details" in the screenshot), press F12 in the newly created tab to open the developer tools, click on the "Console" tab in the developer tools, and paste here the error message you see in the console?

**Comment by gildas-lormeau** [comment]
@sergeevabc After pasting the error message, you can try to run `await browser.runtime.sendMessage({ method: "config.resetProfiles" });` in the console. It should reset all your settings in SingleFile.

**Comment by sergeevabc** [comment]
@gildas-lormeau, did as you told me. 
```
Error: An unexpected error occurred ExtensionUtils.jsm
await browser.runtime.sendMessage({ method: "config.resetProfiles" });
Error: An unexpected error occurred ExtensionUtils.jsm
```

**Comment by gildas-lormeau** [comment]
@sergeevabc Thank you. It looks like this error does not come from SingleFile but Firefox. On my end, there is unfortunately nothing I can do to help you. I would recommend you to post an issue here: https://bugzilla.mozilla.org. If you already created a new profile in Firefox then I guess a fresh install of Firefox might fix the issue.

**Comment by sergeevabc** [comment]
@gildas-lormeau, I tried previous [versions][1] of Singlefile and found out that 1.13.12 is the last that works.

[1]: https://addons.mozilla.org/en-US/firefox/addon/single-file/versions/

**Comment by gildas-lormeau** [comment]
@sergeevabc Thank you for the info. The feature that was added in the version 1.13.13 is the synchronization of the options with your Firefox account. By default, it's disabled so it should not cause any issue though. Did you enable this setting in the past? Is there any particular setting related to your eventual Firefox (online) account that I should be aware of?

**Comment by sergeevabc** [comment]
@gildas-lormeau, I’ve nailed down the issue. It has something to do with the length of profile’s path.
Steps to reproduce:
1. Download [Firefox Portable][1] 71.
2. Unpack to ```C:\abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz```
3. Launch FirefoxPortable.exe, install [Singlefile][2], try to save some webpage or tune options.

[1]: https://portableapps.com/apps/internet/firefox_portable
[2]: https://addons.mozilla.org/en-US/firefox/addon/single-file/

**Comment by gildas-lormeau** [comment]
@sergeevabc I'm sorry, I should have mentioned this issue. Actually, I opened it some months ago. I guess this is the same one even though I'm surprised resetting the profile did not fix it. The good news is that Mozilla is working on it, see https://bugzilla.mozilla.org/show_bug.cgi?id=1536796.
