### ISSUE TITLE
Implement an option to extract an element as a single widget with full css

### ISSUE THREAD

**Issue by neocris** [gildas-lormeau/SingleFile#298]
give the possibility to extract an element with every styles that apply to it contained on the element itself (likely the output of something like window.getComputedStyle() scoped for the element), so global styles would be locally inlined to just get that element properly styled as viewed on the site

**Comment by neocris** [comment]
fuck, only now i've seen there is a ctx sub-menu with a 'save selection' option that allows to do this. i had only experiment with the toolbar button so far that saves a local copy of the whole doc. this improves my already well impression of this utility even more

**Comment by gildas-lormeau** [comment]
No problem ;)
