### ISSUE TITLE
+ sign is not replaced in filenames

### ISSUE THREAD

**Issue by kalum88** [gildas-lormeau/SingleFile#300]
The "Known issues" section says:
The following characters are replaced with _ in filenames: ~, \, ?, %, *, :, |, ", <, >

In this list the + sign is missing so the page will not be saved if filename contains the + sign within page-title. 

Example:
https://dennikn.sk/1639847/o-117-dni-sa-rozhodne-danko-vyhlasil-volby-na-29-februara-2020-co-nas-teraz-caka/

Page-Title
O 117 dní sa rozhodne. Danko vyhlásil voľby na 29. februára 2020 (+ čo nás teraz čaká)

Workaround:
temporarily remove page-title from filename. 

**Environment**
 - OS: [Win10, Android 9]
 - Browser: [Firefox]
 - Version: [1.12.19]

**Comment by gildas-lormeau** [comment]
Thanks for having reported this issue. I did the same test with Firefox on Windows 10. On my end, I cannot reproduce the issue. I was able to download the file and the filename of the saved page contains the "+". Moreover, the "+" is not a reserved character on Windows, cf. https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN. Can you please export your settings, edit the exported file in a text editor and replace

    "filenameReplacedCharacters": [
        "~",

with 

    "filenameReplacedCharacters": [
        "~",
        "+",

Then import the file in SingleFile and tell me please if this change fixes your issue.

**Comment by kalum88** [comment]
Thank you for your quick answer. You are right on Windows 10 it works. The problem is just on my Android phone with Firefox. In a File Explorer I can save a file with the filename containing the + sign but the addon not saves the file.

So I tried to export my settings, added the + sign to the list, imported modified settings and I could successfully save the file I mentioned in the example.

Many thanks for your help and this great addon.

**Comment by gildas-lormeau** [comment]
Thank you very much for your tests, I'll add the "+" in the list anyway.

**Comment by gildas-lormeau** [comment]
The version 1.12.20 I just published fixes this issue.

**Comment by kalum88** [comment]
Thank you. I did a reset off my settings, uninstalled the addon and installed the new version. Then successfully saved the site on Android.

**Comment by gildas-lormeau** [comment]
That's great news! :) Thank you for the feedback.
