### ISSUE TITLE
Uncertain future of SingleFile on Firefox

### ISSUE THREAD

**Issue by gildas-lormeau** [gildas-lormeau/SingleFile#311]
I was contacted by a person at Mozilla that proposed me to see if SingleFile could be eligible to the ["Recommended Extensions" program](https://blog.mozilla.org/firefox/firefox-recommended-extensions/). That's why SingleFile is currently being manually reviewed by Mozilla and that I did my best to fix all the issues. 

The consequence is that today, it's not clear at all for me if I'll be able to publish future versions of SingleFile on the store of Mozilla. The problem is related to third-party code I forked and I adapted in order to run in SingleFile. The concerned files are here: https://github.com/gildas-lormeau/SingleFile/tree/master/lib/single-file/vendor. It looks like I am not allowed to include code I forked (i.e. modified) and that any extension doing so can be banned from the store. You can find more info about this requirement here: https://extensionworkshop.com/documentation/publish/third-party-library-usage/. So, not only SingleFile won't probably be recommended but it may be banned from the store soon too.

For now, it looks like I'm still allowed to sign extensions and distribute them myself so I include to this issue the last version of SingleFile. It fixes some bugs related to the latest features introduced in the version 1.13.x (pending saves, annotation editor) and some translations have been updated.

I'm sincerely sorry for the inconvenience.

Here is the link to install the version 1.13.23 (unzip the file and open the xpi file in Firefox to install it). Use it at your own risk as usual. It has been signed by Mozilla but will not exist on the store:

[singlefile_save_a_page_as_a_single_html_file-1.13.23-an+fx.xpi.zip](https://github.com/gildas-lormeau/SingleFile/files/3877433/singlefile_save_a_page_as_a_single_html_file-1.13.23-an%2Bfx.xpi.zip)

**Comment by gildas-lormeau** [comment]
Because the version on tje store of Mozilla is obsolete and things are not going better, I removed SingleFile from it. From now on, the only way to use SingleFile on Firefox is to install it from the link I provided in the previous post. Again, I'm sorry for that.

**Comment by gildas-lormeau** [comment]
I've been told that I'm not allowed to distribute updates of SingleFile at all for Firefox right now. I'll remove the link to the latest version soon.

**Comment by paponius** [comment]
Sorry to hear that. Is there something we can do? Like write someone?
This looks to me like the reviewer does not actually understand how various licenses works.
All files in your .../vendor folder are MIT licensed.
MIT license allows to do anything with the code, except to claim it as someone's own and removing the MIT notice. It also explicitly allows modifications.

Firefox guideline at ...third-party-library-usage web page does allow use of third party.
They only require to be provided a link to the source code.
Maybe this is what's at issue? Maybe you gave them links to original source code?
They should get links to your modified source code and that should satisfy them.

If they require a link to the original library which is further unmodified, which they should not,
there might be an easy solution.
Create your own library "my utility collection". concat all files from your vendor folder into one file, add your own MIT license to the header.
Now it's your library and not third-party anymore. It's legal with MIT and Firefox can't ask for links as it's not third-party but part of your source code.
And if that will not satisfy them, create the utility as another project. It will be your own third-party library and you can provide links to its unmodified version.

css-minifier.js file itself has a long history already.
Started as cssmin utility by Isaac Schlueter, then become a part of a YUI Compressor, after that cssmin.js and later UglifyCSS. Each ported by another author for another project.
Including it as a part of your library would be just another step in its history.

Hope this will get resolved.

**Comment by gildas-lormeau** [comment]
Thank you for your advice. I might use this technique if necessary but I'm not sure Mozilla will approve it, they know what I'm doing anyway. I provided the links to the original projects in the README and the source code. The problem is that Mozilla cannot compare checksums. I told them that I forked the code and I was now the mantainer of these forks. That does not really suffice. Mozilla recommends to me use the original library if I can and to submit PRs to the author for the changes I would apply. In the case of SingleFile, I often applied changes that are specific to SingleFile or the fact that it runs in a web extension. I also ported or "modernized" some code in order to be less prone to bugs and easier to maintain.

Now, all you have to do is to wait. I'll get more details in the coming days from Mozilla regarding this issue and the future of SingleFile in Firefox. Note that I changed the title because, in the worst case, I wouldn't be allowed to distribute a signed version of SingleFile for Firefox. I think there are still some chances it will be recommended though.

**Comment by gildas-lormeau** [comment]
@paponius I added the new author, I'm going to upload it on the store of Mozilla.

**Comment by gildas-lormeau** [comment]
For the info, Mozilla made impossible for me to publish self-hosted extension w/o being reviewed first... Officially, I cannot update SingleFile anymore for Firefox.

**Comment by gildas-lormeau** [comment]
It looks like the extension is finally recommended \o/. This issue can now be closed.

**Comment by cy7yz2rj** [comment]
Great news!

Hijacking this issue to note that on AMO the extension is licensed under GPLv3 when it should be AGPLv3.

**Comment by gildas-lormeau** [comment]
Thanks for the info @cy7yz2rj, I'll update it :)

**Comment by Shitennouji** [comment]
I confirmed that the update version "1.13.28" was registered on AMO (addons.mozilla.org) on ​​November 26, 2019.
I was worried, so it was really good.
Gildas, is cheers for good work.

**Comment by gildas-lormeau** [comment]
@Shitennouji Thanks! :)
