### ISSUE TITLE
Uncertain future of SingleFile on Chrome

### ISSUE THREAD

**Issue by gildas-lormeau** [gildas-lormeau/SingleFile#312]
Google will force extension developers to adapt the code of their extensions in order to be compliant with the [Manifest V3](https://docs.google.com/document/d/1nPu6Wy4LWR66EFLeYInl3NzzhHzc-qnk4w4PX-0XMw8). No dates have been given, but extensions based on the Manifest V2, like SingleFile, won't be installable anymore in Chrome in the future.

The manifest V3 has a great impact on the code of SingleFile. It means that I will have to rewrite a large portion of code located in the "/extension" folder. I'm also unsure about the features that I would be able to implement. These features would probably disappear if I adapt the extension:
 - Save multiple tabs in one click and the "pending saves" view
 - Auto-save
 - Annotation editor

Today, I cannot say if SingleFile will be ported to the Manifest V3 because it's hard for me to estimate the amount of work needed and I don't know if I will be able to maintain two separate versions of SingleFile.

**Comment by Mika3578** [comment]
I hope I can continue to use this extension which for me is the best way to archive a html web page

**Comment by gildas-lormeau** [comment]
I also hope I'll be able to find a solution to this issue. Hopefully, there is still time before the extension becomes obsolete. Also, porting the basic functionality should not be a problem. For the moment I am waiting for the APIs offered by Manifest V3 to be stable before beginning to see how to adapt the code.

**Comment by damoclark** [comment]
hi @gildas-lormeau 

I can imagine how frustrating this change is, given how much work goes into writing browser addons.  

Firefox add-on authors went through considerable pain a couple of years ago with the removal of XUL/XPCOM and Add-on SDK support in favour of their new Webextensions API with Firefox Quantum.  It was especially painful for those who had well designed integrations with the Firefox UI such as DownThemAll, Tab Mix Plus, and others, that Webextensions no longer support.  

Do you know how much Google's Manifest V3 diverges from Webextensions API?  Mozilla modeled much of Webextensions on Googles API, and then extended it.

Hopefully polyfills will emerge that will help in maintaining cross-browser support of your extension.  You have done a great job on it. 

Damo.

**Comment by nakinigit** [comment]
I resist the google ecosystem, as unavoidable as it seems sometimes. I love your extension for firefox, it is quite valuable.

**Comment by KrasnayaPloshchad** [comment]
@ damoclark DownThemAll is already rewritten as Webextensions, and available for both Firefox, Chrome and Opera

**Comment by gildas-lormeau** [comment]
@damoclark Sorry, I did not see your question. Manifest V3 is not ready yet so it's not easy to tell you how much it will diverge from the WebExtension specification. The change with the biggest impact is the replacement of background scripts with service workers. It removes the DOM API, so the auto-save cannot work anymore as is. The library part of SingleFile should not be heavily impacted though since it has been designed to run outside extensions (e.g. when running on CLI). It means that I should be able to write a "SingleFile Lite" version. Right now, I'm waiting that Google finishes the implementation and fixes current bugs of the Manifest V3 API. So, wait & see...

**Comment by damoclark** [comment]
> @damoclark DownThemAll is already rewritten as Webextensions, and available for both Firefox, Chrome and Opera

Indeed it has been rewritten, but with reduced functionality as explained on its [AMO page](https://addons.mozilla.org/en-US/firefox/addon/downthemall/). 

> Please note: Version 4 of DownThemAll! is.a complete rewrite as a WebExtension, as the old add-on system was abandoned and disabled in Firefox. This was mozilla's decision, and there is nothing we can do about it. We are therefore limited to the tools the WebExtensions model provides to us, which sadly makes it impossible to provide some of the advanced features of DownThemAll! Version 3.

**Comment by gildas-lormeau** [comment]
For the record, more details about the technical issues related to the manifest v3 can be found in this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1051597

**Comment by gildas-lormeau** [comment]
I think this issue has no purposes. I'm closing it.

**Comment by yooper** [comment]
@gildas-lormeau, any thoughts or timelines on when this extension will be manifest 3 compliant? And do you need help in porting it to be m3 compliant?

**Comment by gildas-lormeau** [comment]
@yooper It's already ported actually, see https://github.com/gildas-lormeau/SingleFile-MV3. I'm just waiting as much as I can.

**Comment by yooper** [comment]
Your awesome! Thank you.
