### ISSUE TITLE
Option not to save MathJax fonts

### ISSUE THREAD

**Issue by rychphd** [gildas-lormeau/SingleFile#313]
When I save for example https://mathoverflow.net/questions/344949

The file is larger by about 50KB than the one saved with ScrapBook because of a font encoded in base 64 after

`@font-face{font-family:MathJax_Size1;src:url(data:application/octet-stream;base64,d09GRk9UVE8AABagAAsAAAAAID ...`

I don't seem to need that font embedded like that, probably because it's in the browser cash already: both files render back identically in Firefox.

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. Unfortunately, I cannot reproduce it. If I save the page you gave as example, I see that the font "MathJax_Size1" is not embedded in the saved page. I attached to this issue the saved page with the default settings. If you open it in a text editor and search for "MathJax_Size1" for you find any result. Did you change any option?

[reference request - Is there a systematic theory for Gibbs measures (better if on Hilbert spaces)_ - MathOverflow (2019-11-22 2_49_30 PM).zip](https://github.com/gildas-lormeau/SingleFile/files/3879777/reference.request.-.Is.there.a.systematic.theory.for.Gibbs.measures.better.if.on.Hilbert.spaces._.-.MathOverflow.2019-11-22.2_49_30.PM.zip)

**Comment by gildas-lormeau** [comment]
@rychphd Do you confirm or infirm the issue?

**Comment by rychphd** [comment]
Maybe it's because I use MathML? Could you try to set, loaded in Firefox, via right click menu on a MathJax formula: Math Settings -> Math Rendere -> MathML?

**Comment by gildas-lormeau** [comment]
I was able to reproduce the issue. I made fixed the issue without needing to add another option. The fix will be available in the version 1.13.28.
