### ISSUE TITLE
Save all tabs not working

### ISSUE THREAD

**Issue by Maxulinimus** [gildas-lormeau/SingleFile#315]
Hi

Great extension.

This feature worked a couple of weeks ago but is not working now. Only a couple of tabs gets saved then it stops. I'm trying on the same webpage that used to work.

**Comment by gildas-lormeau** [comment]
I'm sincerely sorry for that. It's a regression in the latest version of Chrome, see #314. I hope I'll be able to deliver the bugfix I coded this week-end in less than 10 days...

**Comment by gildas-lormeau** [comment]
@Maxulinimus The version 1.13.28 which fixes this issue is now available for download on the store of Chrome.
