### ISSUE TITLE
Firefox: the add-on does not work after restart FF

### ISSUE THREAD

**Issue by hdid** [gildas-lormeau/SingleFile#316]
Each time i start firefox i have to disable/re-enable add-on to works otherwise it does not appear anywhere!

**Expected behavior**
No need to disable/enable every time!

**Environment**
 - OS: Win7 Pro
 - Browser: Firefox
 - Version: 70

**Comment by gildas-lormeau** [comment]
That's weird, what do you mean by "it does not appear anywhere"? You don't see the icon in the toolbar and it does not appear in the extensions page?

**Comment by hdid** [comment]
I mean, I can not see the icon but it is available among the extensions.

**Comment by hdid** [comment]
I mean, I can not see it's icon but the addon is available among the extensions.

**Comment by gildas-lormeau** [comment]
Thank you. Was it working correctly in the past on your machine with this version of Firefox?

**Comment by hdid** [comment]
Rarely, first days maybe but since i remember i had this problem (even after FF updates, the issue remained).

**Comment by gildas-lormeau** [comment]
What version of Firefox do you use? I tried the version 32 but I forgot it does not support web extensions like SingleFile.

**Comment by hdid** [comment]
Sorry, edited (v70.0)

**Comment by gildas-lormeau** [comment]
I think it's a bug in Firefox. Did you try to create a (temporary) new profile in Firefox to see if the bug is still present?

**Comment by hdid** [comment]
Yes seems it is a FF bug.

**Comment by gildas-lormeau** [comment]
Were you able to fix the issue?

**Comment by hdid** [comment]
Yes the issue was resolved.
Indeed; I'm using FF portable. The old portable edition had an additional "default" folder in "Data\profile" path. So i downloaded new PAF version. It had not "default" folder then i moved all contents from old "default" folder to the new path pure "Data\profile".
After FF start, SingleFile icon appears and works with no problem.

**Comment by gildas-lormeau** [comment]
Great! I'm glad to hear it :)
