### ISSUE TITLE
Save icon fonts from CSS files

### ISSUE THREAD

**Issue by zungmou** [gildas-lormeau/SingleFile#317]
It seems that SingleFile does not save any images from CSS files, but many websites use CSS backgrounds to render images. Can SingleFile parse the CSS file and download the image specified by the address of the css background field?

**Comment by gildas-lormeau** [comment]
SingleFile does save images from CSS files. What makes you think it does not?

**Comment by gildas-lormeau** [comment]
You can verify it by saving this page for example: https://developer.mozilla.org/en-US/docs/Web/CSS/background-image.

The image at the right is displayed as a background image in CSS.

**Comment by zungmou** [comment]
Sorry, I found that the image in the issue did not come from a CSS file, but from some special font. I looked at the DOM structure of the original web page and found that there was no CSS background setting, but an unusual character was set, and then a special font was used to implement the image.

Because SingleFile does not save unused fonts by default, the saved html file cannot display images. After I try to save the font, the images can be displayed normally.

Thanks for your reply, this issue can be closed.

**Comment by gildas-lormeau** [comment]
Thank you for the detailed answer. If this is possible for you, please share the URL of the concerned page because SingleFile should have embedded the font.

**Comment by zungmou** [comment]
https://nim-lang.org/

See the 'Learn Nim today' section of the page, the icon of the header will not saved by SingFile's default setting.

**Comment by gildas-lormeau** [comment]
I can reproduce the issue. Thank you.

**Comment by gildas-lormeau** [comment]
So, the issue was due to the fact that the font family name of the font is "Font Awesome\ 5 Free". The presence of "\" was causing this issue in Firefox.

**Comment by zungmou** [comment]
Perfect solution! Thank you for your hard work!

**Comment by gildas-lormeau** [comment]
You're welcome. Thank you also for having reported this issue, it was quite subtle.
