### ISSUE TITLE
Put to choose which folder save the page

### ISSUE THREAD

**Issue by cpusam** [gildas-lormeau/SingleFile#319]
Please, in desktop, just put some option to choose and/or rename the file, like if you downloaded a single file. It's horrible to have to predicts where the files are saved. (Even I supposed be in $HOME/Downloads)

**Comment by gildas-lormeau** [comment]
If I'm not wrong, this option already exists. It's "File name > open the "Save as" dialog to confirm the file name". Is it what you want?

**Comment by cpusam** [comment]
But is not from the extension, the Ctrl+s is the common option, but it creates a folder with the files like images. The single file extension not can do this?

**Comment by gildas-lormeau** [comment]
I just learned today it's possible in Chrome but not Firefox, cf. https://twitter.com/check_ca/status/1205507296824119296
