### ISSUE TITLE
SaveLocation

### ISSUE THREAD

**Issue by nakinigit** [gildas-lormeau/SingleFile#321]
Things have changed, probably due to firefoxes endless updates. despite the fact that in firefox settings downloads are 'always prompt' where to save, this app ignores that setting and saves to "C:\Temp". I am prompted where to save for all other downloads.

**To Reproduce**
1. Go to save page with single file
2. Click on na
3. Scroll down to na
4. See error none

**Expected behavior**
not prompted for save location

**Screenshots**

**Environment**
 - OS: [e.g. Win10 Pro, Ubuntu 18.04.1, Android 7.1.2]
 - Browser: [e.g. Chrome, Firefox]
 - Version: [e.g. 64]

**Additional context**

**Comment by gildas-lormeau** [comment]
Did you try to enable the option `File name > open the "Save as" dialog to confirm the filename`?

**Comment by nakinigit** [comment]
Thanks, Is that a new setting? Never noticed it before. I see you also added some other useful features.

**Comment by gildas-lormeau** [comment]
It's an old setting but I can understand you did not notice it because there are a lot (maybe too much) of options.
