### ISSUE TITLE
Autosave Settings out-of-sync and not auto-saving

### ISSUE THREAD

**Issue by damoclark** [gildas-lormeau/SingleFile#325]
**Describe the bug**
From version 1.14.2 onwards of singlefile, auto-save no longer functions.

**To Reproduce**
1. Add * as url for auto-settings rules so all urls will be auto saved
2. Turn on autosave for all tabs
3. Browse to a page
4. The 'A' appears on the singlefile toolbar icon
5. But no auto-save takes place

**Expected behavior**
With version 1.13.32, and after completing the above steps, pages navigated to will auto-save

**Environment**
 - OS: macOS 10.13
 - Browser: Firefox
 - Version: 71
 - singlefile version: 1.14.4

I've updated this issue request with more accurate information after further testing.

**Comment by gildas-lormeau** [comment]
Thank you for having reported the issue. I just deployed a fix. Once the extension reviewed, it will be available for download.
