### ISSUE TITLE
Allow Userscripts to initiate saves

### ISSUE THREAD

**Issue by damoclark** [gildas-lormeau/SingleFile#327]
**Is your feature request related to a problem? Please describe.**

The problem is that I want to save only some pages, depending on the contents or events in the page that I presently interact with through userscripts.

While singlefile supports 'auto-save' and includes co-ordination with userscripts, it is an all or nothing proposition.  You either save all (according to url matching rules in the profile) or none, unless manually triggered.  

**Describe the solution you'd like**
I would like my userscripts to be able to signal to singlefile when to save the page, if at all.  The userscript may wait for certain elements to load, or for me to complete an action within the page and then send an event to singlefile to initiate the page save.  This could be implemented alongside existing userscript integration that performs actions before and after saves.  

So when my userscript wants singlefile to save, it does something like the following:

```javascript
addEventListener("single-file-on-after-capture-request", () => {
    // Capture of page complete
    document.title = title;
  });
// Tell singlefile to capture this page now
dispatchEvent(new CustomEvent("single-file-initate-capture"));
```

**Describe alternatives you've considered (optional)**
If I use auto-save, and register async event handlers, I can simply not send the `response` event back to singlefile to prevent saving.  But it disables any manual function of singlefile for that page.  There are also race condition issues with the current userscript integration (see #326).

Would you consider this feature for an upcoming release @gildas-lormeau ?

Many thanks.

Damo.

**Comment by gildas-lormeau** [comment]
Thanks for your detailed description of this feature request. I would not prefer, if possible, to expose an API allowing an event to signal when to capture the page because this event could also be used by a script in the host page, for "malicious uses". I think I would prefer to implement an event that allows you to signal when you want to cancel the capture of the page. Would it work for you?

**Comment by damoclark** [comment]
I understand your concern.  It was a potential issue I considered as well. 

Unfortunately preventing a capture only solves half my use case problem. My userscripts know when to initiate the capture.  This relates to the race condition I reported in #326 .

But I see this as a broader challenge for extension developers.  Especially when extensions may want to interoperate with one another.

Without making things too complicated, I wonder whether a simple cryptographic approach could be used?

Singlefile settings could include a shared key, or perhaps a RSA key pair.  The counterpart could be pasted within the privileged scope of userscripts source so that it is inaccessible to the DOM and scripts in the host page.  This key could be used to sign or encrypt a nonce passed as data with the event so singlefile can validate the event has come from a trusted source.  

Perhaps something along the lines of:

[node-forge RSA](https://www.npmjs.com/package/node-forge#rsa)

or even a simple shared secret:

[node-forge AES](https://www.npmjs.com/package/node-forge#aes)

Such an approach could be used by other webextensions that may wish to integrate with singlefile into the future.  A simple implementation that starts with userscripts might be a low-risk experiment of such a concept.

What do you think @gildas-lormeau ?

D.

**Comment by gildas-lormeau** [comment]
I think that your suggestion is interesting. I would propose to add a new hidden option named, for example, `userScriptEventPrefix`. This would store the secret value that you define and would be used a prefix for events triggered by the userscript. The default value would be `single-file`. You would be able to override it and set it for example to `single-file-my-super-secret-event-prefix`. Then, in the userscript, you would have to trigger events with a name like `single-file-my-super-secret-event-prefix-on-before-capture-request`.

**Comment by damoclark** [comment]
There are some gaps in my knowledge of the visibility of events to scripts from different origins within the DOM.  So what I am raising here may be a non-issue.

My suggestions for using cryptographic tools was on the understanding that scripts in the host page could 'listen' or otherwise detect events fired from userscripts in the DOM.  If my understanding is correct, then obscuring the event names will not be an effective approach because a malicious script could look for any events fired with your proposed suffix `on-before-capture-request`.

But I am I not at all confident that this is a problem.  @gildas-lormeau do you know whether in host pages can listen for any event through the DOM?

If not, then what you propose, I think, is a great solution.  Simple and effective. :+1: 

D.

**Comment by gildas-lormeau** [comment]
@damoclark Sorry for the late response. From my point of view, cryptographic tools won't save us because the private key would be public, i.e. on GitHub or in the source code of the extension itself. The solution I'm proposing should be more secure because, as far as I know, it's impossible for a script to listen to the custom event name without knowing the prefix. The only solution would be to use brute force.

**Comment by damoclark** [comment]
> The solution I'm proposing should be more secure because, as far as I know, it's impossible for a script to listen to the custom event name without knowing the prefix. The only solution would be to use brute force.

On this basis, then using the prefix approach sounds great to me.  From your suggestion:

> I would propose to add a new hidden option named, for example, userScriptEventPrefix. This would store the secret value that you define and would be used as a prefix for the name of the events triggered by the userscript. The default value would be single-file. 

Perhaps not provide a default, in case people don't make up their own - bad actors don't have a default to test for.  Perhaps if the `userScriptEventPrefix` is provided in the options, it must have a value set by the user to be in effect.

> You would be able to override it and set it for example to single-file-my-super-secret-event-prefix. Then, in the userscript, you would have to trigger events with a name like single-file-my-super-secret-event-prefix-on-before-capture-request.

Sounds good.  I'd also suggest sending a response event back to the userscript from singlefile once the save is completed also.  This allows the userscript to potentially carry on with other tasks, knowing that the save is complete.  It also allows the userscript to be sure that Singlefile received the capture-request event.

Would this be something you could implement quickly and easily?  I'm happy to test pre-releases if that would help.

Thanks @gildas-lormeau 
D.

**Comment by MPeti1** [comment]
@gildas-lormeau could we know why was this closed? I think it's fine if you say you don't want it because of x and y, and I think it might be better to let those know who are searching for such a feature that it's not planned anymore.

**Comment by gildas-lormeau** [comment]
@MPeti1 I closed this issue because the real issue was https://github.com/gildas-lormeau/SingleFile/issues/326. Usually, when I decide I won't implement a feature, I close it in order to stay organized.
