### ISSUE TITLE
Link to original page

### ISSUE THREAD

**Issue by nakinigit** [gildas-lormeau/SingleFile#328]
**Is your feature request related to a problem? Please describe.**
I don't think so

**Describe the solution you'd like**
You have added the ability to annotate before saving, but I don't think that is an option after saving. Often times, potential edits are not realized until subsequent review of the saved pages. Unless I have overlooked many of the options you have added, maybe a link to the original page included? I could re-save so that annotations may be applied.

**Describe alternatives you've considered (optional)**

**Additional context (optional)**

**Comment by gildas-lormeau** [comment]
I'm not sure I'm following you. Do you want to be able to to edit again a save page or get a link to the original URL?

**Comment by gildas-lormeau** [comment]
Here are 3 additional remarks:
 - the link to the original URL can be found via the infobar
 - if you check "UI > open pages saved with SingleFile in the annotation editor", the editor will auto-open itself when displaying a daved page
 - for security reasons, it's technically impossible to provide a link to the page saved *on the filesystem*.

**Comment by nakinigit** [comment]
Thanks for the reply. I am puzzled by the infobar. A box pops up when I save a page, but where is the infobar?

**Comment by gildas-lormeau** [comment]
It's a transparent icon with a "i" as symbol which is displayed at the top right of the saved page. If you're using Chrome, make sure "Allow access to file URLs" is enabled in the extension page.

**Comment by gildas-lormeau** [comment]
I'm closing the issue because I guess it's fixed actually. Feel free to re-open it if necessary.
