### ISSUE TITLE
allow option to replace characters that are invalid on Windows or Unix 

### ISSUE THREAD

**Issue by Konfekt** [gildas-lormeau/SingleFile#329]
To share files between Windows and Linux or MacOS, please add an (default?) option to replace all characters that are invalid on Windows or Unix, that is `\<>":|?*` (Windows and `/` ( Unix). It does not cause much inconvenience, but might save headaches down the road. (Save Page WE has such an option.)

Thank you for this great extension!

**Comment by gildas-lormeau** [comment]
You can edit the list of the replaced characters by editing the `filenameReplacedCharacters` and `filenameReplacementCharacter` options as documented here: https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options.

**Comment by Konfekt** [comment]
Yes, thank you, please excuse my oversight, indeed these characters are now replaced.

**Comment by gildas-lormeau** [comment]
No problem ;)
