### ISSUE TITLE
Open and save mutiple links

### ISSUE THREAD

**Issue by linsui** [gildas-lormeau/SingleFile#333]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to download some pages in a table of contents. Now I use another extension [Open Selected Links](https://addons.mozilla.org/en-US/firefox/addon/open-selected-links/) to open them and use SingleFile to save all the tabs. I can't open too much links at the same time or the website may block me.

**Describe the solution you'd like**
Would it be possible to select some links and then SingleFile can open and save them one by one? Thanks!

**Comment by gildas-lormeau** [comment]
"Open Selected Links" does not seem to work at all on my end. Could you describe me how you select multiple links with it?

**Comment by linsui** [comment]
![2020-01-07 09_57_01-Window](https://user-images.githubusercontent.com/36977733/71862222-0b1e2d00-30f1-11ea-9946-69b79027a264.png)

![2020-01-07 10_05_55-Window](https://user-images.githubusercontent.com/36977733/71862582-466d2b80-30f2-11ea-8cdf-764d3fa4a2e1.png)

Select some links and open them with "Open Selected Links". All of the 7 links will open. Then I can save them with SingleFile. But if I try to open 70 links in the same time maybe my browser will freeze or I'll be block by the website.

**Comment by gildas-lormeau** [comment]
Thank you. I'll try to see what I can do. Today SingleFile is not able to limit the number of tabs used to save pages and I think I will need some time to think on how to implement it.

**Comment by gildas-lormeau** [comment]
The feature is implemented in SingleFile and SingleFileZ. It will be available in the next version I'll publish very soon.

**Comment by linsui** [comment]
Thanks!

**Comment by gildas-lormeau** [comment]
You're welcome. The new version of SingleFile is now being reviewed by Mozilla. It should be available for download in the coming hours or days on the store of Mozilla. By the way, I also added a button "Add URLs" in the pending view to save easily a list of URls.
