### ISSUE TITLE
Exclude elements injected by other WebExtensions

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [gildas-lormeau/SingleFile#336]
**Describe the bug**
Several extensions as [Scroll To Top](https://addons.mozilla.org/firefox/addon/scroll-to-top/) and [Ghostery](https://addons.mozilla.org/firefox/addon/ghostery/) can inject elements on webpage, which should not be saved in HTML file, however I can see the element on the saved file. 

**To Reproduce**
1. Install Scroll To Top
2. Go to https://www.amirifont.org/
3. Click on SingleFile button
4. Scroll down to below
5. See error in source codes, with an element that has ID `pratikabuSTTDiv`

**Expected behavior**
SingleFile should detect which extensions inject the element, and exclude it during page saving.

**Screenshots**

**Environment**
 - OS: Win10
 - Browser: Firefox 72
 - Version: 1.15.1

**Additional context**

**Comment by gildas-lormeau** [comment]
Unfortunately, it's not really possible to write a generic code to handle the automatic removal of these elements. I think the only way to do this would be to hard-code in SingleFile a list of IDs or class names, for example, to remove them.

**Comment by KrasnayaPloshchad** [comment]
I know what’s wrong with me. Scroll To Top has an option Auto Hide (5 sec) to hide the arrow icon, however if I click SingleFile button after the arrow is hidden, the arrow is activated, and the arrow appearing on the saved page, but if I save again with Save Page WE, the element doesn’t appear. So there is an issue that could cause this conflict.

**Comment by gildas-lormeau** [comment]
Thank you @KrasnayaPloshchad  for the additional details. SingleFile implements a fetaure allowing you to save images on a page that are not displayed yet. This feature that "Save Page WE" does not really implement (it has an "auto-scroll" feature instead which is disabled by default) makes the icon to appear again when saving the page. Please disable "images > save deferred images" if you are not interested in this feature and want the same behavior than "Save Page WE".

**Comment by gildas-lormeau** [comment]
This problem might be fixed by using a userscript (see https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved). @KrasnayaPloshchad, would you be interested?

**Comment by gildas-lormeau** [comment]
@KrasnayaPloshchad Actually my question was: Would you like that I provide you a userscript to fix this issue?

**Comment by KrasnayaPloshchad** [comment]
Yes.

**Comment by gildas-lormeau** [comment]
Here is the user script to hide the Scroll To Top icon before processing the page and show it again after the page is processed.
```
// ==UserScript==
// @name         [SingleFile] Hide Scroll To Top icon
// @namespace    http://tampermonkey.net/
// @version      0.1
// @author       Gildas
// @match        *://*/*
// @grant        none
// ==/UserScript==

(function () {
    'use strict';

    let scrollToTopElement;

    dispatchEvent(new CustomEvent("single-file-user-script-init"));
    addEventListener("single-file-on-before-capture-request", () => {
        scrollToTopElement = document.getElementById("pratikabuSTTDiv");
        if (scrollToTopElement) {
            scrollToTopElement.parentElement.replaceChild(document.createElement("singlefile-stt"), scrollToTopElement);
        }
    });

    addEventListener("single-file-on-after-capture-request", () => {
        if (scrollToTopElement) {
            const scrollToTopPlaceholder = document.querySelector("singlefile-stt");
            if (scrollToTopPlaceholder) {
                scrollToTopPlaceholder.parentElement.replaceChild(scrollToTopElement, scrollToTopPlaceholder);
            }
            scrollToTopElement = null;
        }
    });

})();
```

**Comment by gildas-lormeau** [comment]
I'm closing this issue because it cannot be fixed in a generic way and I provided a workaround for Scroll To Top. Feel free to reopen it if necessary.
