### ISSUE TITLE
'Save favicon' checkbox

### ISSUE THREAD

**Issue by bugrepo** [gildas-lormeau/SingleFile#339]
Please add 'Save favicon' checkbox. Thank you.

**Comment by gildas-lormeau** [comment]
By default the favicon should be saved otherwise it's a bug. Would you like to save pages without embedding the favicon or did you save a page where the favicon is missing?

**Comment by bugrepo** [comment]
Yes, it is saved. I ask to make a checkbox to be able to save without favicon.

**Comment by gildas-lormeau** [comment]
Thank you for the clarification. I don't think I will make this option available in the user interface. However, it will be possible to set it via the hidden options, cf. https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options. Stay tuned!

**Comment by bugrepo** [comment]
OK. Hidden options rule! :)

I asked that feature because when I save some small html page, favicon can be more than a half of html size and this makes me said :(

**Comment by gildas-lormeau** [comment]
It's implemented. The hidden option `saveFavicon` will be available in the next version I'll publish.

**Comment by gildas-lormeau** [comment]
The feature is now availaible in the version 1.15.4 that I just published on the store of Mozilla. For Chrome and MS Edge, you'll have to wait approximately one week before it's available for download.
