### ISSUE TITLE
[Feature request] Ability to embed other files

### ISSUE THREAD

**Issue by BiatuAutMiahn** [gildas-lormeau/SingleFile#34]
Hello, I think it would be a useful feature to be able to embed other files such as small zips. And an option to include/exclude files, along with max file size.

**Comment by KrasnayaPloshchad** [comment]
Nice, this will making addon more powerful as [Save Page WE](https://addons.mozilla.org/firefox/addon/save-page-we/).

**Comment by gildas-lormeau** [comment]
Hi, could you give me more details about your how the the embedding feature should be presented to the user?

**Comment by gildas-lormeau** [comment]
I don't understand your response. You can also already change the filename of the saved page with SingleFile.
