### ISSUE TITLE
CLI not working UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by alivefromupstairs** [gildas-lormeau/SingleFile#340]
[![asciicast](https://asciinema.org/a/InXUnUZmAJAlaIfoMrBSSb8RK.svg)](https://asciinema.org/a/InXUnUZmAJAlaIfoMrBSSb8RK)

**Environment**
 - OS: Linux manjaro 5.3.18-1-MANJARO
 - Browser: [ungoogled chromium](https://github.com/Eloston/ungoogled-chromium/)
 - Version: 79.0.3945.88

**Comment by gildas-lormeau** [comment]
Did you try to pass the path of the chrome executable with the --browser-executable-path switch?

**Comment by alivefromupstairs** [comment]
That did it. another question is how to download multiple pages in the same command? Does it not impact performance to have `single-file` execute one url at a time, or does it attach itself to an ongoing browser instance somehow?

**Comment by gildas-lormeau** [comment]
The CLI for SingleFile is a simple script. It cannot help you to download multiple pages in the same command. I would recommend you to run `n` commands in parallel, `n` being the number of logical cores of your CPU. I hope I'll find the time to code something better that would allow you to use only one browser instance and multiple tabs (for example) to capture URLs in parallel.
