### ISSUE TITLE
Parallel Downloads in CLI

### ISSUE THREAD

**Issue by aliveupstairs** [gildas-lormeau/SingleFile#341]
https://github.com/gildas-lormeau/SingleFile/issues/340#issuecomment-575209332
>  I hope I'll find the time to code something better that would allow you to use only one browser instance and multiple tabs (for example) to capture URLs in parallel.

**Comment by gildas-lormeau** [comment]
I added some new options. The option `--urls-file` allows you to pass the path of a text file containing a list of URLs to crawl in parallel. the option `--max-parallel-workers` allows you to set the number of captures running in parallel.

**Comment by aliveupstairs** [comment]
What about this invocation?
```
$ single-file 'url1' 'url2'
```
I'm not requesting it, just making sure I don't miss a simpler, more intuitive way that does not include creating a file for a couple of urls.

**Comment by aliveupstairs** [comment]
also, what's the default value of `--max-parallel-workers`?

**Comment by gildas-lormeau** [comment]
The default value of `--max-parallel-workers` is 8. For 2 URLs, I consider the user should call the CLI tool twice.
