### ISSUE TITLE
Any chance to have this addon on palemoon

### ISSUE THREAD

**Issue by Janaue** [gildas-lormeau/SingleFile#342]
Any chance to have this addon on palemoon or old firefox using XUL addons?

**Comment by gildas-lormeau** [comment]
Unfortunately, I'm afraid the chances are thin. It would require a non-negligible amount of work for almost no gain. The problem is that XUL is not future anymore for almost 10 years.

**Comment by Janaue** [comment]
> 
> 
> Unfortunately, I'm afraid the chances are thin. It would require a non-negligible amount of work for almost no gain. The problem is that XUL is not the future anymore for almost 10 years. The other problem is that I never wrote any XUL addon. I would need to learn it and it's hard to be motivated.

okay, I thought there was and old XUl version, then you moved on to the webext, so I was wiling to test the old one.
