### ISSUE TITLE
pull request: new Chinese translation

### ISSUE THREAD

**Issue by frostblazergit** [gildas-lormeau/SingleFile#343]
I found that the detailed prompt information ICON (I) has been replaced by the information in the "help.html" file, and the "description" in the "i18n" language configuration file is no longer used.

I very much agree with this change!

Because of the lag in translation, the latest English help documentation is often easy to understand.

Attached is the new and improved translation, which can be directly replaced and then you can use the git comparison function to see the changed lines.

The annotate feature is very useful, thank you so much for making such a great extension!
[i18n-zh.zip](https://github.com/gildas-lormeau/SingleFile/files/4085408/i18n-zh.zip)

**Comment by gildas-lormeau** [comment]
Thank you very much too for your help! I'll update the extension very soon :)
