### ISSUE TITLE
Markdown export?

### ISSUE THREAD

**Issue by Agrotsa** [gildas-lormeau/SingleFile#345]
Would it be possible to save the pages in MD format besides HTML? In MD you can edit a document on programs that go from nice and fancy editors like Typora or [Vnote](https://github.com/tamlok/vnote) to anything that can handle plain text, like the simplest plain text editor (I have edited short MD files on the SMS app on an old Nokia. It was an "emergency", of course I dont plan to do it again if I can avoid it. xD).

HTML saving is perfect to keep exact copies of a page; I use it very frecuently to keep exact backups of purchases and bank operations. SingleFileZ has become a perfect substitute to the defunct MAFF archives. But most of the pages we save arent usually important documents that need to be saved intact; I think that most of the time we save blog/press articles, forum threads, guides, tutorials... In short, documents that we most likely shall end editing and resuming to delete the "superfluous" parts of the page and paragraphs or phrases we aren't interested in; and here's where Markdown arises as the perfect format.

So, I hope I've explained my propsed use case well. If you see it reasonable and feasible, please add this second option to let the user choose acording to his precise needs.

Theres this [browser extension that saves webpages to MD](https://github.com/enrico-kaack/markdown-clipper) without issues. It's way less complete in options than SingleFile, and doesn't save media files, but, despite its "spartan-ism", may be it could suggest some ideas, hints or have re-usable code?

**Comment by gildas-lormeau** [comment]
Thank you for the detailed feature request. Unfortunately, I think it won't be possible. The main feature of SingleFile (and SingleFileZ) is to save pages in HTML. It has been designed for this use case and saving in another format would require a lot of work. Another important feature of SingleFile is to save the page faithfully, ideally like a screenshot. Saving in Markdown is the opposite. Only the relevant content must be saved. 

However, it's possible to run a userscript before the page is saved and I wrote a userscript based on readability (https://github.com/mozilla/readability) to save the page like displayed in the reader view. The procedure to enable userscripts in SingleFile is described here: https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved. The userscript based on readability is here: https://gist.github.com/gildas-lormeau/963f363bce2a7bdb53b46ec74e11bf5c.

Out of curiosity, what option in SingleFile would you like to see in markdown-clipper (the extension you linked)?

**Comment by gildas-lormeau** [comment]
I'm closing this issue because I proposed a solution and asked you more details but I did not get any feedback from you. Feel free to comment or reopen it if necessary.

**Comment by Agrotsa** [comment]
Excuse for responding so late. I saw your mail when I hadn't much time to respond and thought that I'd do it the day after, but then I forgot completely.

> Out of curiosity, what option(s) of SingleFile would you like to see in markdown-clipper (the extension you linked)?

The possibility to have all the content, text and media, in one single compressed file or at least a MD file and a directory with all the media inside, like Typora or Markor (Android) do, so I dont depend on an Internet connection to have the complete document whenever I want to see it but I have it all in my device and also can share with others easily, like one can do with  SingleFileZ, but, as you mentioned, keeping only the relevant content, which is the main advantage for my needs of saving a webpage in MD, that you can edit it very easily and keep only what you consider relevant.
I use your extension and also Markdown Clipper mostly for web clipping ,although I also use SFZ to save receipts, tickets, bank operations and other important stuff that I do want to save identically to the original web; but 90% of my usage is as web clipper. Having my clips locally is more handy and also improves privacy because if everytime I want to see a note with media atached, said media has to be fetched from the net every time, and the same for people I may have shared with, that makes a sort of fingetprint.
But you are right. This is a feature request to make to the developers of Markdown Clipper, not you. 

I tried the script thing you liked, but I'm afraid that I'm a regular user with a very scarce knowledge about scripting, and haven't been able to go beyond the part 1 of your guide. The 2nd part, «Dispatch the custom event single-file-user-script-init in the user script.» I dont even know what does mean xD. I supose that I must copy the command in the line below that instruction somewhere in the user script or something like that, but I don't know where should I place the downloaded script.
In sum, the idea of being able to save only the relevant content that you see when use the reader view sounds great to me, but I can't say if works as a solution because I've been too ignorant to make it function xD. Maybe a simpler, maybe even a GUI, way to use user scripts would make that option more accesible for "script-illiterate" users.

**Comment by gildas-lormeau** [comment]
Thank you for your response. I understand that you want actually an extension to save into markdown and that is able to save images. The problem for me is that it is very difficult, if not impossible, to write or integrate the code to remove all the superficial content of the page. This is the biggest challenge when writing such extension because this code has to work on all websites. Honestly, my hope is that this bug will be fixed someday: https://bugzilla.mozilla.org/show_bug.cgi?id=1371786.

If you feel brave, here is how to use the UserScript:

1. Enable the hidden option `userScriptEnabled` by exporting the settings from the options page, editing the JSON file, replacing `userScriptEnabled: false` with `userScriptEnabled: true`, and importing the modified file in SingleFile.

2. Install the extension TamperMonkey (or GreaseMonkey)

3. Add the following script, as is, in TamperMonkey and make sure it's enabled (there's a toggle for that): https://gist.github.com/gildas-lormeau/963f363bce2a7bdb53b46ec74e11bf5c

Then, when you save a page, you should see it turn into a page as it is displayed in the player view, just before SingleFile saves it.

**Comment by Agrotsa** [comment]
> The problem for me is that it is very difficult, if not impossible, to write or integrate the code to remove all the superficial content of the page.

Oh, no worries. SingleFileZ does a great jod in what it's intended to do. I suppose that I just was asking  for something not very realistic.
Common users just tend to think that software development is way easier than it is in reality, and believe that adding suport to different formats is an easy task. We are used to open our word processor and have a plethora of formats to save: ODT, DOCX, RTF, PDF, etc. So, I thought that adding the possibility to save in MD would be an easy task and SFZ could be an "all-purpose" web clipper, both useful to save exact copies of pages and to save clips or take material for notes, recipes, writings, etc.
It was my mistake. From my common user ingenuous perspective I thought that these type of extensions maybe just made a sort of "Select all + Copy + Paste" like, say, a word processor, like when you select content from a web page, copy it, create or open a document in Libreoffice, paste, and there you have what you had copied; well, maybe the typography and layout is not exact, but basically you have all what you wanted.
Oviously, seems that browser extensions dont work that straight way and things are much more complicated. I wasn't too aware of that, so it was a silly request from my side :-s
I'll keep using MD clippers for web clipping and SFZ for exact copies.

**Comment by Agrotsa** [comment]
> If you feel brave, here is how to use the UserScript:

Have tried with GreaseMonkey (I dont feel comfortable installing closed source stuff like TamperMonkey, especially to handle such a delicate thing like the web browser). I created a new script and copied and pasted yours, but t doesn't work. Maybe that method isn't the correct one to install scripts, but since the URL doesnt end in "user.js", GM doesn't recognize is as a script and cant install it the normal way. The case is that it doesn't open a reader view before saving, just saves as always,
In any case, I have "discovered" something that I didn't know it was there (to my shame xD): the "Save selection" entry in SFZ right clic menu (how could I miss it? 🤦‍♂️).

With that wonderful option that inexplicably I had been missing all these months using your extension I can save only what I want in a page, even recognizes multiple selections in different paragraphs. Cool! I still cant edit the resulting document, but since I can save just what I wan, it isnt really very necessary to edit; I might want to rephrase some sentences and such, but those are just details. So, I'm now 93% happy with SFZ. Heheh.

Many thanks for your work and your kind user support :D

**Comment by gildas-lormeau** [comment]
You're welcome!

I'll do a test with GreaseMonkey to see what's wrong.

I'm glad you're 93% happy! Let me try to increase that number :) I'm unsure you know it but SingleFile (not SFZ though) has an annotation editor that allows you to remove unwanted contents from the page too. It is possible to use the editor with the selected content by enabling the option "User interface > annotate the page before saving".

**Comment by gildas-lormeau** [comment]
@Agrotsa The new version 1.17.0, currently being reviewed by Mozilla and which should be available soon for download provides a new button "Format the page for better readability" in the annotation editor. By clicking on this button, the page will be formatted in the same way as the reader view.

**Comment by Agrotsa** [comment]
> I'm unsure you know it but SingleFile (not SFZ though) has an annotation editor that allows you to remove unwanted contents from the page (cf. the "scissors" icon in the toolbar).

No, I didnt know. I in fact have just known that SF and SFZ are not the same thing but with compressed savings for SFZ. So they both have more differences besides saving in one single and compressed files... Well, I guess I'll have to throw a look on SingleFile when I have the time, although as I said, since I have known that SFZ can save only what the user selects and not the entire page I'm very satisfied with the results. I'll try SF nevertheless, if it has more features than SFZ maybe it could fit even better my necessities.
Thanks for the recommendation.

**Comment by gildas-lormeau** [comment]
> Although why having two extensions, one with compression but less featured, and other more feature rich but without compressed savings? I dont see the reason, I suppose that I'm missing it, sorry. :-|

You can find a response in the [FAQ](https://github.com/gildas-lormeau/SingleFileZ/blob/master/faq.md). It's also highly probable that SFZ won't work at all with the Manifest V3.
