### ISSUE TITLE
Auto save when opening Chrome

### ISSUE THREAD

**Issue by SigTill** [gildas-lormeau/SingleFile#346]
I want to start chrome - on specific webpage and automatically save the page as html without user interaction, for instance by running:
"start chrome www.google.com singlefileautosave=yes c:\temp\outputfile.html" in the command line.

Tried to figure out if this is doable already, but seems not?

**Comment by gildas-lormeau** [comment]
Unfortunately, that's indeed not possible. However, note that if you enable "autosave all tabs" (or "autosave selected tabs"), it will stay enabled even when you restart Chrome. It means the user interaction is required only the first time you use SingleFile.

**Comment by gildas-lormeau** [comment]
I'm closing this issue. You can still comment it though. You can also reopen it if you think it is necessary.
