### ISSUE TITLE
SUGGESTION functional current page URL at the top of a saved page

### ISSUE THREAD

**Issue by githubzoidal** [gildas-lormeau/SingleFile#347]
I'd like to have a functional current page URL at the top of a saved page. This could already be a feature but I haven't been able to find it in the Options on Firefox 72.02. If it's already baked in, please point the way.

**Comment by gildas-lormeau** [comment]
You can find a link to the original URL into the infobar. When viewing a saved page, if you click on the "i" icon which is displayed at the top right of the page, it opens the infobar. It displays the saved date and an icon to open the original URL.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because I gave additional details on how to get the original URL. Feel free to reopen it if necessary.
