### ISSUE TITLE
Issues with these websites

### ISSUE THREAD

**Issue by abolibibelot1980** [gildas-lormeau/SingleFile#348]
**Describe the bug**
On a few websites, saving a page with SinglePage either makes Firefox hang with no result, or the website suddently displays an error message.

**To Reproduce**
1. On this website, if I try to save any page with SinglePage, it hangs with a high CPU usage until I cancel the process. Works normally with the SavePage extension.
https://www.vavideo.de/suche?q=Queen+-+Rock+the+World
2) If I try to save this article I immediately get a red warning saying “Uh-oh! We don't know what happened here.” (See screenshot below.) Tried twice, same result. Works normally with SavePage.
https://www.fastcompany.com/90457393/snickers-save-the-world-joke-is-the-most-cynical-super-bowl-ad-yet

**Expected behavior**
The pages should be saved as on other websites.

**Screenshots**
![image](https://user-images.githubusercontent.com/44624604/73434752-a2b91900-4347-11ea-909b-d219cbdb912a.png)

**Environment**
 - OS: Windows 7 Pro
 - Browser: Firefox 72 x64
 - CPU Intel i7 6700K / Asus Maximus Hero VIII / 16GB RAM / no graphic card

**Additional context**
Except for the file naming pattern, SinglePage is currently configured with the default settings, including what I believe is referred as "save deferred images" (by the way there's a grammar error in the french translation : "sauver les images chargées de manière différées" => it should be "de manière différée").

I already issued a bug report a few months ago ([here](https://github.com/gildas-lormeau/SingleFile/issues/283)), and only saw the replies just now ; I will try to disable the "save deferred images" for those problematic websites. But the extension should somehow "be aware" that something went wrong and propose to temporarily disable this feature as a workaround (if it is indeed known to be the main cause of such issues).

EDIT : I tested the second link with the aforementioned option disabled, and it seems to work normally.

**Comment by gildas-lormeau** [comment]
Thank you, I'll do the tests again. However, you should not need to disable the option "save deferred images" (thank for the typo, I'll fix it). You should just have to reset your options and keep enabled the setting. Technically speaking, the [hidden options](https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options) `loadDeferredImagesBlockCookies` and `loadDeferredImagesBlockStorage` must  be set to false. This is the default value since the previous issue you mentioned.

**Comment by gildas-lormeau** [comment]
The first issue is due to the compression of CSS. I'm going to investigate further on this. Meanwhile, you can disable the option "compress CSS content" to fix it.

**Comment by gildas-lormeau** [comment]
The option "compress CSS content" will be disabled by default in the version 1.15.5 I'm going to publish. Once the extension updated, please reset your options.
