### ISSUE TITLE
Have a configurable maximum filename length

### ISSUE THREAD

**Issue by bigtonylewis** [gildas-lormeau/SingleFile#349]
**Is your feature request related to a problem? Please describe.**
Due to the way I backup data (rclone encryption to cloud) it base64-encodes file names, and anything longer than about 140 characters is rejected by the cloud destination.  SingleFile has a max filename length of 192 characters, and so some saved pages can't be backed up unless I manually rename them

**Describe the solution you'd like**
The ability to set the max filename length, but ensuring some fields are preserved (e.g. date).  That is, truncate {page-title} and not the date/time fields so that the overall length is less than a configurable length.

To make it maximally configurable, the template could maybe be
`    {page-title}[120] ({date-iso} {time-locale}.html`
or
`    {page-title,120} ({date-iso} {time-locale}.html`
indicating that the page-title is truncated to 120, should the user decide that is what they want.

**Describe alternatives you've considered (optional)**
I can rename files manually when they error, but as the backups are automatic on a headless machine, I might miss some.

This was discussed in #133 but closed as the issue was with OS limits.  This issue comes not from the OS

**Comment by gildas-lormeau** [comment]
There is actually the hidden option `filenameMaxLength` to set the maximum length. You can find more info about how to set it here: https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options. However, I find your suggestion very interesting, I'll try to implement it.

**Comment by gildas-lormeau** [comment]
The feature is now implemented in SingleFile and SingleFileZ. I choose the first syntax you proposed, e.g. `{page-title}[120]`. It will be available in the next version I'll publish very soon.

**Comment by bigtonylewis** [comment]
Superb, thank you.  I really appreciate it

**Comment by gildas-lormeau** [comment]
You're welcome!
