### ISSUE TITLE
[Feature Request] DataURI Deduplication

### ISSUE THREAD

**Issue by BiatuAutMiahn** [gildas-lormeau/SingleFile#35]
Hello again, The DataURI's should be able to be reduced via CSS/javascript rules, and I beleive this would greatly improve the size of the file, memory usage, and speed of capture.

**Comment by gildas-lormeau** [comment]
That's an interesting idea. I think it may be hard to implement though, especially since the getMachedRules API has been removed from the DOM.

**Comment by gildas-lormeau** [comment]
I'll be honest, I'm not fond of this idea. I would like saved pages not to be dependent from JS at all.

**Comment by gildas-lormeau** [comment]
Finally, I was able to implement the feature you proposed :)
