### ISSUE TITLE
[Question] Force Ask where to save each file before downloading

### ISSUE THREAD

**Issue by aliveupstairs** [gildas-lormeau/SingleFile#353]
Is it possible to have a default `download location` but `ask each time` just for `SingleFile`?

Browser: `chromium`

**Comment by Mika3578** [comment]
Same question, how to choose a different destination folder "to save as".

**Comment by gildas-lormeau** [comment]
You can display the "Save as" dialog just for SingleFile by enabling the option `File name > open the "Save as" dialog to confirm the file name` (and make sure `Misc > save pages in background` is enabled). You can also choose the folder name where to save the pages but it has to be a subfolder of your "Downloads" folder. To do this, add the folder name + `/` to the value defined by the option `File name > template`. For example, if you want to save your files in the subfolder `SingleFile`, you can replace the filename template `{page-title} ({date-iso} {time-locale}).html` with `SingleFile/{page-title} ({date-iso} {time-locale}).html`.

**Comment by aliveupstairs** [comment]
> it has to be a subfolder of your "Downloads" folder

Symlinking the directory I want inside the `Downloads` directory worked.
