### ISSUE TITLE
When saving a bookmarked page, give the bookmark the file manager address?

### ISSUE THREAD

**Issue by user0022** [gildas-lormeau/SingleFile#354]
Hello! Thanks for your addon which seems great (and your big and fast work, and your clear explanations in answers, at least to my impression).
In addition to the option "save the page of a newly created bookmark", would it possible/good to give the file manager address instead of the internet address? So when opening the bookmark, saved page would open.

Pros (?):
- Easier/faster access to pages (by opening Bookmarks, instead of opening the file manager).
- Opens a page faster from computer than from internet?
- Advantages of Bookmarks management versus file manager's usually (mine at least):
 -Would give favicons to saved pages, as they appear in Bookmarks, but not in the file manager.
 -Placing/sorting/grouping files where you want in the list (by drag'n'drop), in an order which is kept in the default sorting if I'm not wrong. And adding separators too.
 -Other: tags, easy duplication, notes (in Keyword)...
- If the user bookmarked + saved a page, it seems logical that he'd be interested in accessing this saved page immediatly from his bookmark.
- Few coding?

Cons (?):
- One might want to know which bookmark has its page saved, and which not, but they'd be all the same. (-> Maybe adding a mark to the favicons, or placing the SingleFile bookmarks in a separate Bookmarks folder?)
- Now the pages in the file manager must (?) stay unorganised in the same folder, instead of possiblility to sort them in sub-folders.
- Loss of the prime goal of Bookmarks, to simply remember an empty internet address (-> but maybe both could be kept, with choice in bookmarking way).
- Out of scope?

This could also be done by making Bookmarks crawl addresses in a file manager folder, or else.
One can notice that this use would make SingleFile ressemble to the ancient or new [ScrapBook](https://addons.mozilla.org/fr/firefox/search/?q=scrapbook&type=extension) extension, which would be maybe good, but maybe "out of scope".

_
I'm just a non-technician user in Firefox (*ubuntu), and if my English is too bad sorry I can write in French as I'm French-speaking too Mr Lormeau.

**Comment by gildas-lormeau** [comment]
Thank you for the very detailed suggestion. I'd really like to implement this feature (as an option to fix the pros/cons issue). Unfortunately, as I recall, that is technically impossible. The problem is that SingleFile doesn't know the full path to the saved file. It just knows the path relative to the "Downloads" folder. However, I have to do some more tests because I'm not 100% sure.

**Comment by gildas-lormeau** [comment]
Good news, I was wrong! It looks like I should be able to get the full path of the saved file. Stay tuned ;)

**Comment by gildas-lormeau** [comment]
I added the option "link the new bookmark to the saved page" below "save the page of a newly created bookmark". The option is disabled by default. When enabled, SingleFile will replace the URL of the page in the bookmark with the URI of the saved page on the disk.  The feature will be available in the next version I should upload soon. (/cc @anthonyclarka2)

**Comment by gildas-lormeau** [comment]
I just uploaded the version 1.17.0 on the store which implements this new option. It should be available for download soon.

**Comment by user0022** [comment]
Thank you, and it's already in SingleFileZ it's been fast!
Hope other users will find it useful. :)

**Comment by gildas-lormeau** [comment]
Indeed, the code SingleFileZ is most of time published some minutes after I upload it. I have no doubt you won't be the only one to find this feature useful ;).
