### ISSUE TITLE
Improve the saving from the cache.

### ISSUE THREAD

**Issue by user0022** [gildas-lormeau/SingleFile#355]
Hello! Thanks again for your addon in my 2nd request.
I'm not the only one <s>staring at</s> certainly who've noticed that pages can be saved from the cache (not sure if "cache" is technically always the right location). That means that when pages have been loaded, you can cut your connexion (or click in Firefox on: File > Work Offline), and then save your page(s).
I would think that this possibility has often logically an interest for some users, because why do they want to save a page? If it's because their internet connexion is weak, or their data amount limited or expensive, I think that not to download a second time every page they save is something they agree with.
(I would see also a possible ecological benefit.)

Improving would mean?
- Maybe to indicate somewhere that it is possible, because possibly some users would be interested, but not knowing it can be done.
- Maybe add it as an option in the menu: "Save from cache / offline".
- Try to solve a problem which appears in this saving way, that deferred images aren't saved, even with the option "save deferred images" kept checked. So maybe make a mix with just "first from cache", or maybe force loading all content in pages before taking it from cache? I don't know.
- Save as faithfully as from internet (?). Personnally I usually save from cache, and sometimes there are lacks/flaws in the page, flaws which maybe wouldn't have occurred if it wouldn't have been done this way, but I'm not sure (nevertheless I still prefer saving this way). So maybe if the suggestion of this issue is accepted, I'll verify when/if it happens, and report it!
- Maybe save from cache as default behavior, but save from network if a problem is detected.

(Little remark: I could have thought that SingleFile already took the page from the cache as I had read [here](https://github.com/gildas-lormeau/SingleFile/issues/320) that "SingleFile needs the page to be displayed in a tab to save it faithfully", but the "System Monitor software shows well that when saving online with SingleFile, the corresponding amount of data of the page is imported from network.)

**Comment by gildas-lormeau** [comment]
SingleFile does use the cache from the browser when it's possible and use the network otherwise. For example SingleFile should still work if you open a page in a tab, disconnect yourself from internet, and save the page after you have been disconnected. I did the test and it worked well on my end. 

SingleFile needs the page to be displayed in a tab in order to execute JavaScript. The data you see in the system monitor can be related to the loading of deferred images.

**Comment by gildas-lormeau** [comment]
More precisely, today SingleFile already sets the option `cache` to [`"force-cache"`](https://developer.mozilla.org/en-US/docs/Web/API/Request/cache) when retrieving the page resources.

**Comment by user0022** [comment]
Ok thank you for fast answer! Well I made a test again and it's true it seems to work like you say.

In fact, at first time to check if SingleFile saved the page from network, I had loaded a small page, simply an issue page like this present one here, and then saw a bump in System Monitor to around 30 Ko/s. Then I saved it with SingleFile while online and saw the same bump, so I deduced it had been re-loaded from the network. But apparently in "basic behavior" there comes regular bumps that have the same size! So that would be where my mistake came from.
Here I just made a second test with a bigger page, so first loading made a bump to 160 Ko/s, and then saving dind'nt made this bump, only a 30 Ko/s one , which must just be a "regular one".
So the mystery is solved.
(Each time I had scrolled the page to the bottom to load possible deferred images so it souldn't come from this.)

So I'm happy to learn that it works this way, as I didn't like the idea to load a second time from network to save.

**Comment by gildas-lormeau** [comment]
I share your point of view regarding how SingleFile should use the cache. By the way, I forgot to mention that SingleFile can try to download all the fonts formats (woff, ttf, etc.) in order which one should be kept. That might explain the 30KB/s bump you see. 

I'm closing this issue because I can't do more actually. Maybe I'll add a hidden option to let the user choose the policy he prefers.
