### ISSUE TITLE
Saved pages on local drive have issues saving on Chrome/Brave, but not on Firefox

### ISSUE THREAD

**Issue by electricmessiah** [gildas-lormeau/SingleFile#359]
I have an archive of old saved pages that I've been converting to single files with this addon. Using Chrome/Brave, it will display "This page cannot be saved with SingleFile," but on Firefox it saves the page with no issues. The URL for these files are obviously this, but just showing for clarity.

URL: file:///E:/Web/Archive/Astronomy/Science%20Center...Where%20Science%20Becomes%20an%20Adventure.htm

**Comment by gildas-lormeau** [comment]
Please make sure "Allow access to file URLs" is enabled in the page of the extension chrome://extensions/?id=mpiodijhokgodhhofbcjdecpffjipkle.

**Comment by gildas-lormeau** [comment]
@electricmessiah Is the option enabled?

**Comment by gildas-lormeau** [comment]
I'm closing this issue because I did not get any response from you. Feel free to reopen it if necessary.
