### ISSUE TITLE
Add rel=canonical tag metadata to all archived snapshots

### ISSUE THREAD

**Issue by gwern** [gildas-lormeau/SingleFile#360]
SingleFile currently specifies the original URL informally, but it should use the standardized search-engine-supported `rel=canonical` HTML `<link>` feature to specify the original URL.

Right now, SingleFile stores the original URL inline as a comment, eg

```
<!DOCTYPE html> <html class=js lang=de-DE><!--
 Page saved with SingleFile 
 url: https://tarnkappe.info/crimenetwork-biz-offline-fuer-immer/ 
 saved date: Sat Feb 15 2020 08:13:40 GMT-0500 (Eastern Standard Time)
--><meta charset=utf-8>
<meta name=theme-color content=#2b86a6>
```

This is not standardized or understood by any tools, and is partially redundant with the [canonical link element](https://en.wikipedia.org/wiki/Canonical_link_element) standardized 8 years ago & supported by search engines for 11 years.

Adding the canonical links helps machine parsing of the files and avoids SEO penalties or confusion if one hosts SingleFile mirrors, and is politer to the original authors.

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. In fact, I know well this tag since I'm the founder of seo4ajax. What should happen if the canonical URL is already defined and different from the URL of the page being saved? For example, it can happen if the URL contains a query parameter?

**Comment by gwern** [comment]
[The RFC](https://tools.ietf.org/html/rfc6596) does not require the canonical to be unique, perfect, or even different from the current URL, as it's intended to be a hint and processed heuristically downstream (it suggests that there be only one per page but doesn't require it); so as far as the standard is concerned, SingleFile could go either way.

Given that SingleFile is targeted at archiving purposes, the 'original' rel=canonical, if any, may be long gone and invalid, while a SingleFile-added rel must have been valid at the time of creation; so my preference would be to document the actual origin by adding the rel=canonical with the current URL being saved regardless of whether a rel=canonical is already present. (It would be nice to add only if different.)

But the difference is probably minor enough that it depends on which way is easiest to implement. I would rather have either than have neither due to bikeshedding.

**Comment by gildas-lormeau** [comment]
From my point of view, a canonical should be unique. The RFC you linked also says:
`
Avoid designating the target (canonical) as:
[...]
      *  An IRI that also specifies a canonical link relation to an IRI
         other than itself.
[...]
`

The problem, from my point point of view, is that by replacing the existing canonical, you might lose a very valuable information: the URL that is/was indexed on search engines and (maybe) social networks.

**Comment by gwern** [comment]
> The RFC you linked also says:

As I already said, it suggests but does not require it. If it required it, it would say so, using the standard RFC terms like 'MUST" or 'REQUIRED', which exist for that purpose. (Nor is that recommendation possible to implement without crawling and parsing the other IRI, and even if one did that, the other IRI could change at any time, invalidating it.)

> by replacing the existing canonical, you might also lose a very valuable information

Is that more or less valuable information than the status quo of throwing away the original URL in every case for every page ever saved with SingleFile in any way?

**Comment by gildas-lormeau** [comment]
The original URL is not thrown away, it's always stored in the comment after the `<html>` tag and there's no option to remove it. The canonical URL is also kept in the saved page.

I'm not against adding some markup to store the original URL. However, I doubt the canonical URL is meant for this. The RFC says "The canonical link relation specifies the preferred IRI from resources with duplicative content". In SingleFile, this URL is not the "preferred" URL. It's the URL of the page that has been saved. 

Maybe the `WebPage` object from schema.org would be more appropriate?

**Comment by gwern** [comment]
> The original URL is not thrown away, it's always stored in the comment after the <html> tag and there's no option to remove it.

It is thrown away in the sense that it is hidden in a nonstandard comment used only by SingleFile.

> The canonical URL is also kept in the saved page.

Assuming there is one.

> Maybe the WebPage object from schema.org would be more appropriate?

I've never heard of that being used by anyone, and I don't see any relevant fields reading through it and double-checking for keywords like 'copy' or 'mirror' except possibly the `BasedOn` which implies more of a derivative work ("A resource from which this work is derived or from which it is a modification or adaption.") in the copyright sense than a mirror/copy/archive/duplicate. Duplicate pages (mirrors and copies) are what rel=canonical are typically used for, as WP and most guides to rel=canonical use describe it, and what SingleFile creates: a duplicate.

I will note that no one in the [comparable ArchiveBox issue](https://github.com/pirate/ArchiveBox/issues/92) has the slightest doubt that this is an appropriate use of rel=canonical, and in fact, some people are quite angry that it is *not* used.

**Comment by gildas-lormeau** [comment]
The relevant field is `url` and I'm not afraid of using a standard that nobody else uses.

I consider that if SingleFile should follow the RFC then it should keep the canonical URL that was already defined in the page, but that's not what you want. The ArchiveBox issue you mentioned is related to SEO issues (`create duplicate search results`), The need of author is not to store the original URL. I am pretty sure they would agree with me if someone asks what to do in case of conflict, i.e. keep the canonical URL that was already defined.

**Comment by gwern** [comment]
> The relevant field is url

No, it's not: it says "URL of the item." Period. Nothing about 'URL of the original item' or 'URL of the canonical version'. If I make a SingleFile archive of `foo.com` and I upload it to `gwern.net/foo.com.html`, the latter is the `url`. Not the former. So it does not serve this purpose and you would break the Schema standard if you tried that instead of rel=canonical.

> I consider that if SingleFile should follow the RFC then it should keep the canonical URL that was already defined in the page, but that's not what you want

As I clearly said already, I am largely indifferent to whether the original is replace or augmented, and I regard the debate as bikeshedding as the RFC does not require any particular behavior.

> The ArchiveBox issue you mentioned is related to SEO issues 

And my point was that no one else thinks that it is an abuse of rel=canonical or reads the RFC the way you do, and that using it this way serves useful purposes and is valid.

> I am pretty sure they would agree with me if someone asks what to do in case of conflict, i.e. keep the canonical URL that was already defined.

Then do that!

**Comment by gildas-lormeau** [comment]
Okay, I will all the canonical link *if not already present*.

**Comment by gwern** [comment]
Pulled and checked some examples. Looks good, thanks.

**Comment by gildas-lormeau** [comment]
You're welcome.
