### ISSUE TITLE
[CLI][Feature Request] Log Failed URLs

### ISSUE THREAD

**Issue by aliveupstairs** [gildas-lormeau/SingleFile#362]
![image](https://user-images.githubusercontent.com/46059092/74669206-f8465000-51a6-11ea-9611-dd2757f23c22.png)

`$ single-file --urls-file myurls.txt` outputs some errors, one of which says `Navigation timeout of 60000 ms exceeded`. It would be great if a log file contains failed URLs to retry downloading later: `myurls.txt.log`.

**Comment by gildas-lormeau** [comment]
Thanks for the suggestion, I'll try to implement something (a news switch, probably) to address this issue.

**Comment by gildas-lormeau** [comment]
I added the switch `--error-file` to pass the name of the file storing the errors. If you do not pass it, errors will be displayed in the (error) console.
