### ISSUE TITLE
Fonts not saved

### ISSUE THREAD

**Issue by davwheat** [gildas-lormeau/SingleFile#368]
**Describe the bug**
When saving a page, the fonts used on that page are not embedded into the document.

**To Reproduce**
1. Go to https://gg-help.web.app/kb/roaming-in-eu
2. Save the page
3. Observe the incorrect font

**Expected behavior**
I hoped that my site's font would be embedded into the HTML file (base64 encoded?).

**Screenshots**

Real:
![image](https://user-images.githubusercontent.com/7406822/75494264-be99f400-59b3-11ea-8e39-4ab85cb71fb8.png)

Saved:
![image](https://user-images.githubusercontent.com/7406822/75494252-b5a92280-59b3-11ea-9d6e-35845434167b.png)

**Environment**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 80

**Comment by gildas-lormeau** [comment]
Thanks for having reported the issue. I'll see what's wrong. This is due to the option "remove unused fonts".

**Comment by gildas-lormeau** [comment]
The bug is fixed in the latest version I just published. After having been reviewed by Google, it should be available for download on the store of Google in approximately 7 days.
