### ISSUE TITLE
add options:saved pages  with  "UTF-8"    or  "UTF-8 with BOM"

### ISSUE THREAD

**Issue by newsdos** [gildas-lormeau/SingleFile#369]

**Comment by gildas-lormeau** [comment]
Out of curiosity, why do you need a BOM?

**Comment by gildas-lormeau** [comment]
@newsdos I can add the option but I would like to know why I would add it.

**Comment by gildas-lormeau** [comment]
It's implemented and will be available as a [hidden option](https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options) (`includeBOM`) in the next version. You'll have to replace `includeBOM: false` with `includeBOM: true` in the exported settings to enable it.
