### ISSUE TITLE
Cannot save slides from bookshelf.vitalsource.com

### ISSUE THREAD

**Issue by FaVorith** [gildas-lormeau/SingleFile#372]
Hi,

For a private backup, I saved some slides from bookshelf.vitalsource.com. This worked fine on 24th of February 2020, but since a few days, instead of the slides, only "whitespace" is being saved. I followed the troubleshooting steps, but this did not solve the problem.

I then fell back to the version that was released prior to 24th of February 2020 and everything is working again. I think something was broken during one of the last updates.

Regards,
Fabian

**Comment by gildas-lormeau** [comment]
What browser are you using?

**Comment by FaVorith** [comment]
Hi,

Firefox 73.0.1 64 bit.

As an additional detail: The first two operations during saving the website seem to behave normally, but when it says "Step 1/3" "2/3" "3/3", it finishes all of these way too fast (probably because there are no pictures which could be encoded into base64).

Regards,
Fabian

**Comment by gildas-lormeau** [comment]
Thank you. Is the version of SingleFile up to date? I introduced a regression recently. The version 1.17.10 published today fixed it.

**Comment by FaVorith** [comment]
Hi,

Oh, sorry, I had assumed that FF is downloading updates near real-time. I just installed the latest version released today and it seems to work properly again.

Thank you so much for your quick support and the great tool!

Regards,
Fabian

**Comment by gildas-lormeau** [comment]
You're welcome and sorry for the inconvenience. It seems indeed Firefox takes its time :)
