### ISSUE TITLE
Chrome Title

### ISSUE THREAD

**Issue by sj365** [gildas-lormeau/SingleFile#373]
Hello,

Thanks for fixing SF trouble with Twitter pages.  I was just about to put a report in.  Currently, SingleFile Chrome is saving pages with random letters/numbers instead of the Title or url.  This is not happening with pages saved with Singlefile in Firefox.

Currently using Chrome 80 and Firefox 73.01.

[sf title error.zip](https://github.com/gildas-lormeau/SingleFile/files/4289906/sf.title.error.zip)

**Comment by gildas-lormeau** [comment]
Unfortunately, it's a known issue in Chrome. See here: https://github.com/gildas-lormeau/SingleFile#known-issues.
