### ISSUE TITLE
Solved:SingleFile is causing Firefox to slow down

### ISSUE THREAD

**Issue by nonsenseoleg** [gildas-lormeau/SingleFile#376]
**Describe the bug**
SingleFile is causing Firefox to slow down .laggy mouse and site surfing i need to disable it to continue.

**To Reproduce**
i can not say how to reproduce sometimes happening.but 6-7 times in a day.
i think there is a conflict with outlook.office365.com site.

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/61837910/75993269-44fd8b00-5f0a-11ea-9a52-a3052421a370.png)

![Screenshot_4](https://user-images.githubusercontent.com/61837910/75993486-93128e80-5f0a-11ea-9181-3f210ed2f768.png)

**Environment**
 - OS: [Win10 Pro, ]
 - Browser: [Firefox]
 - Version: [ 73.0.1

**Additional context**
pc setup ryzen 7 16 gb rx580

**Comment by gildas-lormeau** [comment]
Thank you for the info. When this happens, could you stop the script, open the console by pressing F12, click on the "Console" tab and tell me if you see any error message (in red)?

**Comment by nonsenseoleg** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/61837910/76000959-792a7900-5f15-11ea-9512-8774759946ee.png)

actually at that time there wasnt warning but was laggy.

**Comment by nonsenseoleg** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/61837910/76001664-7da36180-5f16-11ea-9385-59b7f274d7c0.png)

**Comment by gildas-lormeau** [comment]
Thank you, it's hard to see what is going wrong unfortunately.

**Comment by nonsenseoleg** [comment]
i can give one more clue . its starts laggy when preview a mail attachment.after that until i disable its  laggy all time.i think its all about office365 site.

**Comment by gildas-lormeau** [comment]
I think I will provide you 2 or 3 different custom build of SingleFile that you would have to install manually. That would help me to narrow down this issue. Could you do me this kind of service?

**Comment by nonsenseoleg** [comment]
its ok .i m waiting

**Comment by gildas-lormeau** [comment]
Thank you. I need to prepare them. I'll ping you here when they're ready. Stay tuned!

**Comment by gildas-lormeau** [comment]
@nonsenseoleg Below are some custom builds to test:

[singlefile-extension-firefox-1.zip](https://github.com/gildas-lormeau/SingleFile/files/4303398/singlefile-extension-firefox-1.zip)
[singlefile-extension-firefox-2.zip](https://github.com/gildas-lormeau/SingleFile/files/4303400/singlefile-extension-firefox-2.zip)
[singlefile-extension-firefox-3.zip](https://github.com/gildas-lormeau/SingleFile/files/4303401/singlefile-extension-firefox-3.zip)
[singlefile-extension-firefox-4.zip](https://github.com/gildas-lormeau/SingleFile/files/4303402/singlefile-extension-firefox-4.zip)
[singlefile-extension-firefox-5.zip](https://github.com/gildas-lormeau/SingleFile/files/4303403/singlefile-extension-firefox-5.zip)

Could you install them manually (cf. https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/) one after another and tell me if any of them fixes the issue?

**Comment by nonsenseoleg** [comment]
i tested first example almost 3-4 hours and didnt saw any problem.i didnt know after every restart i need to also install.so today when i install again.but the second sample.i dont have any problem also but i can say definitly second one is faster than first one.i will continue to use and report

**Comment by gildas-lormeau** [comment]
Thank you for the feedback. I plan to integrate the changes of the first zip into SingleFile in the future. The changes of the second zip are already integrated in the latest version of SingleFile I published yesterday. I'm still interested in knowing if the 3 other zips improve things on your end though.

**Comment by nonsenseoleg** [comment]
hi again i can confirm that after using almost 5 days of second zip file that i dont have any problem.i will try to use the others and inform.

**Comment by gildas-lormeau** [comment]
@nonsenseoleg Thank you for the feedback. Note that the other versions might not work at all. Indeed, the goal was of these versions was to test if SingleFile  was slowing down Firefox without actively using SingleFile. So, instead of testing these versions, I think it might be simpler for you to test the stable version from the store (since it integrates the changes made in the second zip file) and tell me if the issue persists.

**Comment by gildas-lormeau** [comment]
Thanks @nonsenseoleg. Feel free of course to re-open the issue if necessary :)
