### ISSUE TITLE
'Disable context menus' option not integrated properly

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [gildas-lormeau/SingleFile#377]
When users disable context menus, they're still shown in tabs' context menu. This interferes with my preferred context menu sorting since i want a particular extension that i use constantly to be the last in the queue. Kindly add an option to disable context menus globally. Thanks.

**Comment by gildas-lormeau** [comment]
There s a [hidden option](https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options) for that, please export your settings, replace in the exported file `tabMenuEnabled: true` with `tabMenuEnabled: false` and import the modified file.

**Comment by Vulgaris-Viridis** [comment]
Alright that works too.. Thanks!

**Comment by gildas-lormeau** [comment]
You're welcome.
