### ISSUE TITLE
Add an option to ignore webp images

### ISSUE THREAD

**Issue by newsdos** [gildas-lormeau/SingleFile#378]
saved HTML page in FF 74  ,but not view picture in FF 55.

why saved html page with webscrapbook can .

**Comment by gildas-lormeau** [comment]
Can you please provide an example illustrating the issue? It's probably related to the options "Images > group duplicate images". Please disable it if you to open your pages in a obsolete browser.

**Comment by newsdos** [comment]
thank your replay
 &nbsp;
  disable it .but no picture.
 &nbsp;
 website:
 &nbsp;
 
https://mp.weixin.qq.com/s?__biz=MzAxMjE4OTcxNg==&amp;mid=2651047006&amp;idx=1&amp;sn=0e4b115cbe0f464b801982734a37ca7f&amp;chksm=8042cd25b7354433eac47f2eff51f40a2cec72dc3c5fd5dca8a4d1a4f8593679396bf90cf94d&amp;scene=21#wechat_redirect
 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Gildas"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年3月15日(星期天) 晚上6:31
 收件人:&nbsp;"gildas-lormeau/SingleFile"<SingleFile@noreply.github.com&gt;;
 抄送:&nbsp;"云雾雨"<403107301@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [gildas-lormeau/SingleFile] View (#378)

 

 

 
Can you please provide an example illustrating the issue? It's probably related to the options "Images &gt; group duplicate images". Please disable it if you to open your pages in a obsolete browser.

**Comment by gildas-lormeau** [comment]
Th reason is that these images are saved in webp and Firefox 55 don't support them. I'll see if I can add an option. I know Safari refuses to display them too.

**Comment by newsdos** [comment]
Although the software makes the saved files smaller, it takes more time.

The version before 1.17.4 is not bad.

**Comment by gildas-lormeau** [comment]
What do you mean by "The version before 1.17.4 is not bad". Are there issues with the following versions?

**Comment by XX-J** [comment]
> The reason is that these images are displayed and saved in webp and Firefox 55 doesn't support this format. The support of webp images has been added in Firefox 65...

<details><summary> My FireFox v53.0.3 (pcxFireFox) is support webp images. See screenshot:</summary>

![2020 05 12-1](https://user-images.githubusercontent.com/17948007/81802115-2b864a00-951e-11ea-8eb5-7b9882d0b1e7.png)
</details>

**Comment by fregante** [comment]
Why would you use Firefox 55? It's already 2.5 years old and not supported by Mozilla themselves. Sounds like a non-issue here.

**Comment by gildas-lormeau** [comment]
@XX-J Thank you, I did not know that...

@XX-J, @fregante  This issue is opened because of Safari in fact.

**Comment by gildas-lormeau** [comment]
@XX-J That's weird though since [this post](https://hacks.mozilla.org/2019/01/firefox-65-webp-flexbox-inspector-new-tooling/) confirms it was not supported on Firefox 64-

**Comment by gildas-lormeau** [comment]
I'm closing this issue as "wontfix" since the latest version of Safari (14) will finally support WebP, see https://caniuse.com/#feat=webp.

**Comment by KotBoyun** [comment]
Hello! Gildas-lormeau, thanks for the extension. This is the best there is with such features! I will raise, if possible, the old topic. There is still one browser that does not support webp images - Internet Explorer 11. It is used to quickly preview HTML files in TotalCommader. I save the page in a Chrome browser, then to quickly scroll through local HTML files I use Total Commander. Those pages that contain webp;base64 images do not show. It also doesn't work in Windows explorer window view panel (ALT+P). Please consider installing this option. I see it this way. Check the box (save webp as jpeg). If I didn't write it clearly, I'll add screenshots. Is it possible to do?
