### ISSUE TITLE
SF can`t save the page...

### ISSUE THREAD

**Issue by kramola-RU** [gildas-lormeau/SingleFile#379]
Gildas, hi !

Why SF can`t save this page:
https://www.windowslatest.com/2020/02/16/windows-10-v2004-hardware-accelerated-gpu-scheduling/

![132](https://user-images.githubusercontent.com/51376332/76904832-c8778e80-68b1-11ea-8a27-fb0428e3870c.jpg)

SF 1.17.21
Firefox 70.01 x32
Win 10 2004 x64

**Comment by gildas-lormeau** [comment]
Hi, I don't know... I was able to save it without any particular issue. 

Could you press F12 and post a screenshot of the console? Could you also go to about:debugging#/runtime/this-firefox, scroll down to the SingleFile entry, click on the button "Inspect" and post a screenshot of the console in the Inpect window?

**Comment by kramola-RU** [comment]
**F12**
![F12](https://user-images.githubusercontent.com/51376332/76953396-afa5c200-691f-11ea-88ab-09594b95ecf6.jpg)


**Inspect**
![Inspect](https://user-images.githubusercontent.com/51376332/76953420-b7fdfd00-691f-11ea-9e58-9f6baa1c8cb4.jpg)

**Comment by gildas-lormeau** [comment]
Thank you. It looks like it's due to the "out of memory" issue. I did not test the 32bit version of Firefox and I need to do some further investigations. On my machine, I see that Firefox eats more than 3 GB of RAM when processing this page with SingleFile. It's very unusual.

**Comment by gildas-lormeau** [comment]
I was able to find the cause of the issue. This was due to the removal of CSS comments. I replaced the implementation with a better one, I hope, and now the RAM usage seems reasonable. It should be available for download on the store, once reviewed, in the coming days.

**Comment by gildas-lormeau** [comment]
Th version is already published. I guess we can thank the Covid-19 :p

**Comment by kramola-RU** [comment]
You are the best ! (forever)

**Comment by kramola-RU** [comment]
**1.17.22** -- works fine.
Thank you very much !

**Comment by gildas-lormeau** [comment]
I'm glad to hear that. Thanks also for your issue which helped to optimize SingleFile ;)
