### ISSUE TITLE
get original resources

### ISSUE THREAD

**Issue by Red-Flame** [gildas-lormeau/SingleFile#380]
This project is great,but how to get original resources from SingleFile "*.html" file? For a complete project,maybe it's important.Thanks!

**Comment by gildas-lormeau** [comment]
Thank you. I would recommend you to use [SingleFileZ](https://github.com/gildas-lormeau/SingleFileZ) instead. It embeds an `index.json` file giving you the URLs to the original resources.

**Comment by gildas-lormeau** [comment]
The new option "HTML Content > save original URLs of embedded resources" in the version 1.19.22+ allows to save the URLs of the original resources as CSS comments/HTML attributes (see the help page for more info).
