### ISSUE TITLE
single-file docker cli timeout / hangs

### ISSUE THREAD

**Issue by etherai** [gildas-lormeau/SingleFile#384]
Thank you for building / open sourcing this great tool!

The following invocation hangs indefinitely: 

```
docker run single-file "https://codeburst.io/protocol-buffers-part-2-the-untold-parts-of-using-any-6a328560048d" > out.html

URL: https://codeburst.io/protocol-buffers-part-2-the-untold-parts-of-using-any-6a328560048d
Stack: TimeoutError: Navigation timeout of 100000 ms exceeded
```

I am able to produce an output of the above url with the Chrome Extension.
 
**Expected behavior**
Contents of page should be written to `out.html`

**Environment**
 - OS: Docker-for-Mac
 - cli docker container built from `cli/dockerfile` from master

**Comment by etherai** [comment]
I was able to get better results by setting `--browser-wait-until domcontentloaded`

**Comment by gildas-lormeau** [comment]
I confirm I can reproduce the issue without even using docker. It looks like it's a bug in Puppeteer, using `load` also works. This event is triggered a bit later than `domcontentloaded`.

**Comment by gildas-lormeau** [comment]
I think I will implement a way to automate the fallback.

**Comment by gildas-lormeau** [comment]
I added the option `--browser-wait-until-fallback` which is `true` by default. When it's `true`, SingleFile will automatically retry to save the page with the next value of `browser-wait-until`. That's the best I can do to circumvent this issue.
