### ISSUE TITLE
Hanging at step 3 on franceinter.fr

### ISSUE THREAD

**Issue by abolibibelot1980** [gildas-lormeau/SingleFile#385]
**Describe the bug**
Saving a page hangs at step 3 on franceinter.fr. It worked earlier today on this website (I successfully saved three pages), but then it started hanging indefinitely and it became impossible to save a page on this website, even after re-starting Firefox, even after disabling Ublock and AdBlockPlus and allowing all scripts in NoScript. I tried enabling delayed image saving, and disabling the "background task" option. SavePage WE works on this website.

**To Reproduce**
Go to 'https://www.franceinter.fr/emissions/les-histoires-du-monde/les-histoires-du-monde-30-mars-2020' or 'https://www.franceinter.fr/personnes/anthony-bellanger' or seemingly any other page from franceinter.fr, attempt to save the page.

**Expected behavior**
It should finish saving the page and display the usual confirmation window.

**Environment**
 - Windows 7 Pro SP1
 - Firefox 74 x64 with active add-ons : AdBlockPlus, Download Helper, NoScript, SavePage WE, Download Star, MyJDownloader, SingleFile, uBlock Origin, DownThemAll

**Comment by gildas-lormeau** [comment]
Thank you for having reported the issue. I was able to reproduce it and fix it. The fix will be available in the next version which is currently being reviewed.

**Comment by gildas-lormeau** [comment]
I re-open the issue meanwhile.

**Comment by gildas-lormeau** [comment]
And I close it again, the new version has just been published.

**Comment by gildas-lormeau** [comment]
And I close it again, the new version has just been published.
