### ISSUE TITLE
"Save Page As" / Desination pick, instead of instantsave to default download folder

### ISSUE THREAD

**Issue by Fr6jDJF** [gildas-lormeau/SingleFile#386]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when files loose their category on export, while you have the chance to instant sort it right (the general heap in a download map).
I found no option for it in the add-on config, just a checkbox for "download in background", but that won't let me choose some destination on it's prompt, since no file explorer.

**Describe the solution you'd like**
"Save as" option to save direct to categorized destination in Downloads/Dest. folder, this instead of sorting thing later out(what likely requires time consuming insight to documents when sorting with poor named pages for example)

**Describe alternatives you've considered (optional)**
FF74 "Save Page As" function to save in to desired folder.

**Comment by gildas-lormeau** [comment]
If "Misc. > save pages in background" is checked (it's the default value), then checking "User interface > open the "Save as" dialog to confirm the file name" should fix the issue. Otherwise, make sure "Always ask you where to save files" is checked in about:preferences.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because I did not get any feedback and I consider as already fixed. Feel free to reopen it if you think I'm wrong.

**Comment by mlep** [comment]
Followup: it works.
Note: ``open the "Save as" dialog to confirm the file name`` is under the ``FileName`` item in SingleFile 1.18.66 preferences.
