### ISSUE TITLE
Load SingleFile inside Puppeteer

### ISSUE THREAD

**Issue by yhafri** [gildas-lormeau/SingleFile#387]
@gildas-lormeau do you think it's possible to load `SingleFile` when  `Puppeteer` is started and call `Singlefile` to produce _HTML_?

A call is already available to load extensions [load-extension](https://peter.sh/experiments/chromium-command-line-switches/#load-extension), but not really sure if `SingleFile` will be compatible.

Feedback are welcome.
Keep up the good work...

**Comment by gildas-lormeau** [comment]
Isn't what the [CLI](https://github.com/gildas-lormeau/SingleFile/tree/master/cli) does?

**Comment by yhafri** [comment]
Amazing @gildas-lormeau 
I will give it a go and report back. Thanks a lot.

**Comment by yhafri** [comment]
On MacOS using `node v10.6.0` and `yarn 1.21.1`.

```
git clone https://github.com/gildas-lormeau/SingleFile.git
cd SingleFile/cli
npm install
chmod +x single-file
./single-file "https://twitter.com/BorisJohnson/" 
(node:16167) UnhandledPromiseRejectionWarning: Error: Browser is not downloaded. Run "npm install" or "yarn install"
    at ChromeLauncher.launch (/Users/octo/SingleFile-master/cli/node_modules/puppeteer-core/lib/Launcher.js:236:15)
(node:16167) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16167) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Am i missing something @gildas-lormeau ?

**Comment by yhafri** [comment]
This solved my issue `--browser-executable-path `

**Comment by gildas-lormeau** [comment]
Glad to hear it :)

**Comment by gildas-lormeau** [comment]
@yhafri It would be great if you could one day acknowledge your mistake and perhaps apologize for **violating the SingleFile license** in your service. The changes you made to your fork clearly demonstrate your intention to hide your intent. By the way, despite your efforts to hide this, there are still traces of your work here: https://github.com/elastic/elasticsearch/issues/57924.
