### ISSUE TITLE
24 Hour Time

### ISSUE THREAD

**Issue by defrilitus** [gildas-lormeau/SingleFile#390]
Could you consider adding an option to use 24h time in the saved page's title?
The American 12h format is extremely annoying! Thanks in advance!

**Comment by gildas-lormeau** [comment]
I know, I'm french ;)

Go to the options page and replace the value of the option "File name > template" with the following one:
`{page-title} ({date-iso} {time-iso}).html`

**Comment by gildas-lormeau** [comment]
I'm closing this issue because the solution I proposed should fix it. Feel free to reopen it if necessary.

**Comment by defrilitus** [comment]
@gildas-lormeau Works perfectly. Thank you. Apologies for only having realised now that this option is included in the add-on's documentation.

**Comment by gildas-lormeau** [comment]
No problem ;)

**Comment by lkintact** [comment]
@gildas-lormeau Hello, I was looking for a way to get local time in the 24h notation in saved pages' filenames and found this issue.

Not quite sure if it's a bug, but `{time-iso}` that you advised to use [above](https://github.com/gildas-lormeau/SingleFile/issues/390#issuecomment-611745300) returns UTC time, i.e. without a time offset.

I realize what I wanted can be done with `{hours-locale} {minutes-locale} {seconds-locale}`, but thought I should report anyway.

OS: Windows 10 Home 1803,
Browser: Firefox 84.0.1 (32-bit),
SingleFile 1.18.60.

**Comment by gildas-lormeau** [comment]
@lkintact Thank you for the feedback. Do you think adding new variables named for example `{time-locale-h24}` and `{time-locale-h12}` would be okay?

**Comment by lkintact** [comment]
FWIW, I think it would be okay. Also, perhaps `{datetime-locale}` and `{hours-locale}` should as well be split into `{datetime-locale-h24}` + `{datetime-locale-h12}` and `{hours-locale-h24}` + `{hours-locale-h12}` respectively.

**Comment by lkintact** [comment]
@gildas-lormeau Sorry, I somehow mistook "locale" for "local" in the template variable names, and since it's the locale that sets the time format (24h/12h), my idea doesn't make sense. Perhaps, for the same reason the names `{time-locale-h24}` and `{time-locale-h12}` will be a bit confusing?

**Comment by gildas-lormeau** [comment]
@lkintact I agree it can be a bit confusing
