### ISSUE TITLE
"Installation aborted because the add-on appears to be corrupt."

### ISSUE THREAD

**Issue by baloe** [gildas-lormeau/SingleFile#391]
**Describe the bug**
Add on won't install.

**To Reproduce**
1. Go to https://addons.mozilla.org/en-US/firefox/addon/single-file/?src=search,
2. click on "Add to Firefox",
3. See error message "Installation aborted because the add-on appears to be corrupt."

**Environment**
 - OS: Win10 
 - Browser: Firefox 75.0 64bit

**Comment by gildas-lormeau** [comment]
I cannot reproduce this issue and there is nothing I can do on my end to fix it. This post might help you to find the cause of the issue: https://discourse.mozilla.org/t/firefox-containers-addon-disappeared-after-update/57336.

**Comment by baloe** [comment]
Thank you for the hint, @gildas-lormeau, this is not a bug in the Add-On.
Setting the OS clock to the correct time solved the issue.

**Comment by gildas-lormeau** [comment]
Glad to hear it :)
