### ISSUE TITLE
CLI not working UnhandledPromiseRejectionWarning. Error: Browser is not downloaded.

### ISSUE THREAD

**Issue by coderxyz** [gildas-lormeau/SingleFile#392]
Environment: Windows 10 Pro 1909
Browser: Google Chrome 
Version: 81.0.4044.92

Steps followed 

`cd /path/to/SingleFile-master`
`cd cli`
`single-file.bat` 

I got this error 

`(node:16004) UnhandledPromiseRejectionWarning: Error: Browser is not downloaded. Run "npm install" or "yarn install"
    at ChromeLauncher.launch (C:\SingleFile-master\cli\node_modules\puppeteer-core\lib\Launcher.js:236:15)
    at async Object.exports.initialize (C:\SingleFile-master\cli\back-ends\puppeteer.js:36:12)
(node:16004) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16004) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

After searching for the solution, you mentioned to pass the path of the chrome executable with the --browser-executable-path 

How should I do this? 

Is it a bug or am I doing something wrong

**Comment by gildas-lormeau** [comment]
You should determine where Chrome is installed on your PC and pass the complete path to chrome.exe via the option `--browser-executable-path`. For example, on my machine with Canary on Win 10, I pass the following value:
`--browser-executable-path=C:\\Users\\Gildas\\AppData\\Local\\Google\\Chrome SxS\\Application\\chrome.exe`

Alternatively, you can add the path to the chrome.exe file into your `PATH` environment variable.

**Comment by coderxyz** [comment]
I added the complete path of chrome.exe to --browser-executable-path but now I am getting this error

`(node:4384) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn C:Program Files (x86)GoogleChromeApplicationchrome.exe ENOENT`

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

**Comment by gildas-lormeau** [comment]
Please try to replace "\" occurrences with "/" in the value, e.g. `--browser-executable-path="C:/Users/Gildas/AppData/Local/Google/Chrome SxS/Application/chrome.exe"`

**Comment by coderxyz** [comment]
The file is getting saved in the `cli` directory itself. Is it possible to change the directory to another drive. Because i have a plan to download 100's of url's

**Comment by gildas-lormeau** [comment]
For this, go first into the directory where you want to save files and use the complete path to launch single-file. For example, to save pages on `d:\saved-pages`:

    d:
    cd saved-pages
    c:\SingleFile-master\cli\single-file https://www.example.com/ --browser-executable-path=...

**Comment by gildas-lormeau** [comment]
For your information, I added a "Troubleshooting" part in the README file.
