### ISSUE TITLE
SingleFile's behaviour on infinite scroll pages

### ISSUE THREAD

**Issue by einemarc** [gildas-lormeau/SingleFile#393]
This issue is neither really a bug report nor a feature request, rather a question or something inbetween. I have noticed that SingleFile seems to produce unpredictable and sometimes subpar results when saving web pages which make use of infinite scroll*. I am wondering if such pages are already take into consideration of SingleFile's functioning. Do they even present a special situation for SingleFile? If so, would it be possible to improve SingleFile in this regard or provide a setting for the handling of such pages?

Check the following examples:
- [Example 1](https://correctiv.org/aktuelles/klimawandel/2020/04/08/nach-der-coronakrise-ist-mitten-in-der-klimakrise/): Previews of more articles load at the end, the URL changes as if already viewing the respective other article; when saved with SingleFile, the resulting file size differs with different tries and is sometimes very large, 30 MB or more; SingleFile on Firefox aborts the saving process at step 2).
- [Example 2](https://www.seriouseats.com/recipes/2020/03/sicilian-style-spaghetti-alla-carrettiera-fresh-tomato-and-garlic-sauce.html): At the end of the article (a recipe) another full article (a background article to the recipe) loads and the URL changes respectively; SingleFile can not save just the first actual article, but always saves the other article too, but is only able to save the images when already visited manually (which is as expected).
- [Example 3](https://infinite-scroll.com/demo/full-page/): More and more pages are loaded when scrolling and the URL changes respectively; when loading the page and not scrolling at all, SingleFile still somehow is able to save parts of page 2.

I use SingleFile with Chromium 81 running on macOS 10.15.4.

I'd be happy if you could shed some light on this issue.

\* I feel I should explain what I mean. I am refering to web pages where content is automatically added/loaded at the end of the page and the URL in the browser's address bar automatically changes without a usual page load. It is often used in online stores for displaying items which would normally be several pages (where you would usually manually go to the next page with e. g. the next 20 items), but more and more also for news websites, blogs and so on, where at the end of an article another article appears and when scrolling further the URL changes to that of the other article. (I had to do a quick search on what this feature is actually called. It seems it can be achieved by either using JavaScript or the pushState of the HTML5 history API. I don't know much more. Most results I found and could comprehend – I am not a web developer, if not already obvious – covered this feature from the point of view of SEO and how to deal with it.)

**Comment by gildas-lormeau** [comment]
All these issues are due to the option "Images > save deferred images". 

Some websites use a mechanism to load content (mostly images) on the fly when the user scrolls down the page. This mechanism is called "lazy loading". This means that if you try to save such a page without scrolling it, some content will not be saved. That's the problem the option "Images > save deferred images" is trying to fix.

When the option "Images > save deferred images" is enabled, SingleFile will, among other things, zoom out the page very briefly (you won't notice it) in order to force lazily loaded contents to load.

Here, for example, is what your third example looks like when SingleFile zooms it out.
![image](https://user-images.githubusercontent.com/396787/79129192-0d092380-7da5-11ea-8dc0-1f48f96bf2dc.png)

I think the problem is it should maybe zoom out a little less the page.

**Comment by einemarc** [comment]
Thank you, that makes perfect sense. I had another idea of what this option does and foolishly never tried it with the option unchecked.

By the way, thank you for developing and maintaining SingleFile. There is no comparable alternative to store and archive web pages in full in a single file. I use it mainly for academic work and it has become indispensable in my daily workflow.

**Comment by gildas-lormeau** [comment]
You're welcome :). I might suggest that you create a new profile in the options page (see the "+" button at the top right of the page) called for example "No deferred images", disable the option "Images > save deferred images" in this profile and every time you see a problematic page of this type, associate it with this new profile via the entry "SingleFile > Select the profile of the current domain" in the context menu.

**Comment by gildas-lormeau** [comment]
I made the changes to zoom out a little bit less. This fixes the issue for the 2 last examples. For the first site, I did not find yet how to avoid the URL update. The version with the fix (1.17.35) should be available for download on the store of Chrome in approximately 7-10 days.

**Comment by einemarc** [comment]
Good idea with the profile. Thanks for the change as well, will try the version asap.
