### ISSUE TITLE
Packaging with PKG [ENHANCEMENT]

### ISSUE THREAD

**Issue by lzaiko** [gildas-lormeau/SingleFile#394]
Hi @gildas-lormeau 
I'm playing with **singlefile cli** and I want to package it as a standalone executable using [PKG](https://github.com/zeit/pkg).
The idea is to put it in my `/usr/bin` and use it as a normal linux command.
I'm new to Node and hope you can advice.

Thank you.
Lou.

**Comment by gildas-lormeau** [comment]
I did not know PKG. That seems indeed interesting, have you tried to follow their instructions?

**Comment by fregante** [comment]
@gildas-lormeau if you publish single-file to npm you can change your [instructions](https://github.com/gildas-lormeau/SingleFile/blob/master/cli/README.MD) to just:

```sh
npm install single-file -g
```

**Comment by pirate** [comment]
I believe this @gildas-lormeau fixed this, so `npm install -g https://github.com/gildas-lormeau/SingleFile.git; single-file --help` should work now.

**Comment by gildas-lormeau** [comment]
Indeed, I'm just hesitating about suggesting the `-g` flag because I find it's a bit opaque for regular users that don't know Node.js. If I suggest it in the documentation, I need to document how to uninstall the global module I guess :p.

**Comment by gildas-lormeau** [comment]
Update: SingleFile is now available on dockerhub, see https://hub.docker.com/r/capsulecode/singlefile (and https://hub.docker.com/r/capsulecode/singlefilez for SingleFileZ).

**Comment by ashutoshsaboo** [comment]
Hi @gildas-lormeau , is there any plan to publish this on npm? Or are there any challenges in doing that? Given you already support npm install via your github package, so might as well publish the same on npm? 

My use-case was to use SingleFile in cloud for orchestrating some workflows. https://pipedream.com/ can read all npm registry packages only unfortunately at the moment. I was hoping if you could help with the same? 

Also, I'd presume publishing on npm could also help with more discoverability for SingleFile in general. :)

**Comment by gildas-lormeau** [comment]
@ashutoshsaboo I might publish it on NPM. I'm still a bit hesitant since it's not really a node module but an application/extension.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because I think the tags on Docker Hub and Git that I added recently solve it. Feel free to reopen it though if you think Docker/Git is not sufficient.
