### ISSUE TITLE
Delete Selection

### ISSUE THREAD

**Issue by Saadish** [gildas-lormeau/SingleFile#396]
**Is your feature request related to a problem? Please describe.**
Sometimes i want to save a page, except a special section.

**Describe the solution you'd like**
Be possible to delete a selection by press Delete on the keyboard.

**Comment by gildas-lormeau** [comment]
This can be done via the annotation editor. You can open it by selecting "Annotate and save the page..." in the context menu.

**Comment by Saadi1988** [comment]
Thank you. SingleFile ext is great.

In "Annotate and save the page..." for adding notes to pages, when i switch language from EN to PERSIAN (Right-To-Left language) then if the SingleFile ext makes the paragraph direction RTL and right align automatic, my works will be better. Can you build this?  Thanks.

**Comment by gildas-lormeau** [comment]
Well, I need to see if that's technically possible. How do you change the language of the browser?

**Comment by Saadish** [comment]
> 
> 
> Well, I need to see if that's technically possible. How do you change the language of the browser? Should the text written in English also written from right to left? Are you referring to the user interface elements only? I'm unsure I understand your feature request actually.

How do you change the language of the browser? Alt+Shift
Should the text written in English also written from right to left? Some Times
Are you referring to the user interface elements only? Yes

Some Windows applications do this considering the keyboard input switch. but they can't do for mixed-used languages in one paragraph. and sets the paragraph direction on first used language.

**Comment by gildas-lormeau** [comment]
Thank you, its more clear now. What are the cases where English text should be written from right to left?

**Comment by Saadish** [comment]
When in a sentence started with RTL language and the English word(s) begin or end with for example "." character.
for example ".NET" will be shown "NET." between Persian words in the RTL paragraph.

**Comment by gildas-lormeau** [comment]
Okay, what elements of SingleFile are concerned by this specific issue?

**Comment by Saadish** [comment]
Noting rectangles.
(I hope you understand what you mean)

**Comment by gildas-lormeau** [comment]
Okay, I'll check how to implement this.

**Comment by gildas-lormeau** [comment]
Can you do this test and tell me if the behavior is okay?

With the DOM inspector, add the style "direction: rtl;" on the `textarea` element from a note, and type some text in the note. See the screenshot below.

![image](https://user-images.githubusercontent.com/396787/79803391-322c0200-8362-11ea-9299-e97e1f6656db.png)

**Comment by gildas-lormeau** [comment]
If you can, please try to add the attribute `dir="rtl"` on the `textarea` element instead and tell me if the direction automatically changes when you're using Alt+Shift?

![image](https://user-images.githubusercontent.com/396787/79804517-7ae4ba80-8364-11ea-93f5-3658219e1841.png)

**Comment by Saadish** [comment]
on the edit-section, the DOM inspector doesn't work. and by editing HTML codes, `dir=auto` on the `textarea ` it works. However not for mixed text. just for every line. it is enough.

**Comment by JokerShades** [comment]
> 
> 
> This can be done via the annotation editor (cf. the button with the scissors icon). You can open it by selecting "Annotate and save the page..." in the context menu or enabling the option "User interface > annotate the page before saving"

Hi, I have many pages I would like to save, is it possible to automatically annotate them to remove some section before saving

Thanks

**Comment by gildas-lormeau** [comment]
@Saadish Thank you! I will add the attribute `dir=auto`. The fix will be available in the next version.

@JokerShades That seems complicated to implement. I think a userscript could solve the issue though. Can you give me more details about your need?

**Comment by Saadish** [comment]
> @Saadish Thank you! I will add the attribute `dir=auto`. The fix will be available in the next version.
> 

Thank you very much.

**Comment by JokerShades** [comment]
> @JokerShades That seems complicated to implement. I think a userscript could solve the issue though. Can you give me more details about your need?

For example, I have these two pages
https://www.cgspectrum.com/blog/skybound-concept-artist-april-prime
https://www.cgspectrum.com/blog/become-a-game-designer-5-tips

Is there a way to automatically remove the headers and footer before saving them instead of manually annotating them? Some kind of filter like with adblocks plugins

**Comment by gildas-lormeau** [comment]
@JokerShades To automate this, you could install an extension like GreaseMonkey and add the userscript below. You have also to enable the hidden option `userScriptEnabled` by exporting the settings from the options page of SingleFile, editing the JSON file, replacing `userScriptEnabled: false` with `userScriptEnabled: true`, and importing the modified file in SingleFile. 

Note that the script is specific to www.cgspectrum.com.
```
// ==UserScript==
// @name         [SingleFile] Select main content on cgspectrum.com
// @version      1.0
// @description  [SingleFile] Select main content on cgspectrum.com
// @match        *://www.cgspectrum.com/*
// @noframes
// @grant        none
// ==/UserScript==

dispatchEvent(new CustomEvent("single-file-user-script-init"));

addEventListener("single-file-on-before-capture-request", () => {
	document.querySelector(".header-container-wrapper").remove();
	document.querySelector(".footer-container-wrapper").remove();
});
```

**Comment by gildas-lormeau** [comment]
@Saadish The version containing the fix was published today.

**Comment by JokerShades** [comment]
> 
> 
> @JokerShades To automate this, you could install an extension like GreaseMonkey and add the userscript below. You have also to enable the hidden option `userScriptEnabled` by exporting the settings from the options page of SingleFile, editing the JSON file, replacing `userScriptEnabled: false` with `userScriptEnabled: true`, and importing the modified file in SingleFile.
> 
> Then, when saving a page of [www.cgspectrum.com](http://www.cgspectrum.com), the header and the footer will be automatically removed. Note that the script is specific to [www.cgspectrum.com](http://www.cgspectrum.com).
> 
> ```
> // ==UserScript==
> // @name         [SingleFile] Select main content on cgspectrum.com
> // @version      1.0
> // @description  [SingleFile] Select main content on cgspectrum.com
> // @match        *://www.cgspectrum.com/*
> // @noframes
> // @grant        none
> // ==/UserScript==
> 
> dispatchEvent(new CustomEvent("single-file-user-script-init"));
> 
> addEventListener("single-file-on-before-capture-request", () => {
>   document.querySelector(".header-container-wrapper").remove();
>   document.querySelector(".footer-container-wrapper").remove();
> });
> ```

It works
Thanks for this

**Comment by gildas-lormeau** [comment]
You're welcome. I'm closing this issue since it is fixed now.
