### ISSUE TITLE
Pull requests. Updated the translation of Traditional Chinese (Taiwan, Hong Kong).

### ISSUE THREAD

**Issue by frostblazergit** [gildas-lormeau/SingleFile#397]
**Additional context (optional)**
path `zh_TW/messages.json`

[messages.json.zip](https://github.com/gildas-lormeau/SingleFile/files/4507316/messages.json.zip)

**Comment by gildas-lormeau** [comment]
@frostblazergit Thank you very much!

Meanwhile, I added 2 options. It would be great if you could translate them. The 2 options are:
 - "max length (bytes)" in the filename section
 - "apply the system theme when formatting a page in the annotation editor" in the misc. section

**Comment by frostblazergit** [comment]
@gildas-lormeau 
After the function is updated in the chrome store, I will translate it according to the specific function. Will reply to this issue when the time comes.

**Comment by gildas-lormeau** [comment]
Okay @frostblazergit, thank you.
