### ISSUE TITLE
File name template not working on Brave Browser

### ISSUE THREAD

**Issue by renochew** [gildas-lormeau/SingleFile#398]
Hi,

First of all, thank you for creating this excellent extension. 

I recently moved to Brave browser, I notice that the auto generated file name is not respecting the template, it usually look like this "93f37818-43f7-4204-b45f-30b33c60065e.html".

Its working fine in other browser though.

Thank you.

**Comment by gildas-lormeau** [comment]
It's a [known issue](https://github.com/gildas-lormeau/SingleFile#known-issues), please disable "Misc > save pages in background.
