### ISSUE TITLE
rename file from list urls

### ISSUE THREAD

**Issue by zulmianah** [gildas-lormeau/SingleFile#399]
hello,
how to rename url from list-urls.txt with single-file?
thx,

**Comment by gildas-lormeau** [comment]
You have to use the `--filename-template option`.

**Comment by gildas-lormeau** [comment]
FYI, you can find more information about the syntax of the template in the help page of the extension.

**Comment by zulmianah** [comment]
thank you sir

**Comment by gildas-lormeau** [comment]
You're welcome!
