### ISSUE TITLE
May be a way to reduce the final file size

### ISSUE THREAD

**Issue by alekssmitt** [gildas-lormeau/SingleFile#403]
I found large unused snippets in <style> tags in files.
It looks like:

> <style>@font-face{font-family:'Roboto';font-style:italic;font-weight:400;src:local('Roboto Italic'),local('Roboto-Italic'),url(data:font/woff2;base64,d09GMgABAAAAACkwABIAAAAAXOQAACjNAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGmobllYcNgZgAIcMCFIJgzwRDAqBhQj3BAuCEAASgRQBNgIkA4QcBCAFgwoHIAyCRBuXUxXs2CDgPICQqM8DZyMs2Dgg0Fj3RwaCjQOQTN8K/v+SwMkAhW
> -------------------------------------------------------------------------------------------------------------------------------------------------------
> 6WYMdj3iqlhMGL5bpWouX7G8szrnjPwy10Sd789mTRLGnyoijkSWbed7Wtjtx7VtPjxLeYX/g1/hnie8KbQha/taWLhW8H3rEzplr8tpUIJ3ET/0fdS0yWsjTylGdcn5EMg539fYm6Fr8d4CSe5/+20ZdJLZJbTRYAAAA=) 

As You see chanks beginning with 'url' can be removed, they are useless:

<style>@font-face{font-family:'Roboto';font-style:italic;font-weight:400;src:local('Roboto Italic'),local('Roboto-Italic'),url----------------------------------------------------------------------------------------

**Comment by gildas-lormeau** [comment]
As far I know, it's useful for anyone that does not have Roboto installed on their system, i.e. the vast majority of users.

**Comment by alekssmitt** [comment]
After I deleted them, the file became 10 times lighter without visible changes. Moreover, when I deleted all the styles, the file became 150 times lighter with visible changes. However, I think deleting unused styles is a way to reduce file size.

**Comment by alekssmitt** [comment]
To be more precisely - how to kill all unused fonts in  chosen selection, if one only needed an article not a whole page?

**Comment by gildas-lormeau** [comment]
That's already implemented in SingleFile. SingleFile should always remove unused fonts in the options in the "Fonts" section are enabled. Can you describe how to reproduce the issue?

**Comment by alekssmitt** [comment]
It is very simple. Open the saved file and, according to a simple try & cut rule, delete all the styles one by one, return the ones that were really used.

**Comment by alekssmitt** [comment]
Here the example:
[SingleFile File.zip](https://github.com/gildas-lormeau/SingleFile/files/4540101/SingleFile.File.zip)
[corrected manually.zip](https://github.com/gildas-lormeau/SingleFile/files/4540105/corrected.manually.zip)
2 identical files

**Comment by gildas-lormeau** [comment]
Are you sure you did not change any option? When I go to https://czkaltan.ru/bolezni-serdtsa/prichiny-tahikardii-posle-edy.html and save the same part, the saved page weights 158KB.

[Причины тахикардии после еды - Кардио доктор (2020-04-27 4_20_52 PM).zip](https://github.com/gildas-lormeau/SingleFile/files/4540176/-.2020-04-27.4_20_52.PM.zip)

**Comment by alekssmitt** [comment]
How did you do this??

**Comment by alekssmitt** [comment]
Yes, now I see that there is a little mess in my extension options

**Comment by gildas-lormeau** [comment]
Moreover, in the 2 files you attached the 8 `@font-face` rules are strictly the same.

**Comment by alekssmitt** [comment]
Yes,
Some time ago, I tried to save files containing java applets in different ways, and since this did not help, I left it with one unchecked option ...
forgot about it, and it came to this mess.
I'm sorry.

**Comment by gildas-lormeau** [comment]
No problem!
