### ISSUE TITLE
Local resources are not included

### ISSUE THREAD

**Issue by daniel-starke** [gildas-lormeau/SingleFile#405]
**Describe the bug**
Trying to save a local HTML file with references local resources like images works but those images are only included with absolute path.

**To Reproduce**
Try with any HTML file stored locally, which includes local resources (by relative links).

**Expected behavior**
All resources are properly included, whether local or not.

**Environment**
 - OS: Windows 7 Professional SP1
 - Browser: Firefox
 - Version: 75.0

**Comment by gildas-lormeau** [comment]
Thank you for reporting the issue.

Are you sure it works for images with relative paths? I've done some tests and it seems that it is impossible to save a locally stored image, whether the path is relative or absolute.

**Comment by daniel-starke** [comment]
What I meant was that you can reproduce the issue e.g. by using a local HTML file with relative image paths. I did not try absolute paths. So both does not work, most likely. Maybe a security issue.

**Comment by gildas-lormeau** [comment]
If I'm not wrong it used to work in the past with previous versions of Firefox. I also think Mozilla made a change related to the security that breaks this use-case. I don't know if it's a bug or a feature.

**Comment by gildas-lormeau** [comment]
I did the same test with Firefox ESR (68) and it works as expected. This tend to confirm something has changed in Firefox meanwhile.

**Comment by gildas-lormeau** [comment]
I opened this issue on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1644488

The regression appeared in the version 74.

**Comment by daniel-starke** [comment]
Thank you.

**Comment by gildas-lormeau** [comment]
This bug has been closed by Mozilla as wontfix.

**Comment by gildas-lormeau** [comment]
I added this issue in the "Known issues" here: https://github.com/gildas-lormeau/SingleFile/blob/master/README.MD#known-issues. I'm closing it because that's the best I can do, unfortunately.
