### ISSUE TITLE
SingleFile issue within Convertri

### ISSUE THREAD

**Issue by ClarenceDS** [gildas-lormeau/SingleFile#408]
**Describe the bug**
There is an issue when SingleFile is installed and someone goes to pages such as anything hosted with convertri - https://www.convertri.com/ 
Convertri is a landing page builder and many people use it for marketing and stuff. It would be bad if people don't see the content on the web page itself.

I tested it using incognito with the extension enabled and with the extension disabled Check these sites below that have issues when singlefile is enabled 
https://www.convertri.com/ 
https://dropmock.convertri.com/txtvideo-main 
https://bonus.dropmock.com/wolfwallstreet 

Here are screenshots to show you the issue that I'm experiencing. I've compared the enabled vs the disabled single file chrome extension in incognito window.
FYI - SingleFile is the only extension that I've installed in the incognito window. 

**To Reproduce**
1. SingleFile should be enabled then go to 
https://www.convertri.com/ 
https://dropmock.convertri.com/txtvideo-main 
https://bonus.dropmock.com/wolfwallstreet 

2. See error - images are not showing

**Expected behavior**
Images should appear in the webpages - see screenshot below of what should it look like with the SingleFile disabled

**Screenshots**
https://imgur.com/a/2dY2swr

**Environment**
 - OS: Win10 Pro, MacOSX
 - Browser: Chrome
 - Version: Version 81.0.4044.129

**Comment by gildas-lormeau** [comment]
Thank you very much for having reported this issue. I was able to reproduce it and fix it. The fix is available in the version 1.17.40 I just uploaded on stores. It should be available for download within 7 days on Chrome, after the extension has been reviewed. This delay will be shorter for Firefox.

**Comment by ClarenceDS** [comment]
Thank you @gildas-lormeau !
