### ISSUE TITLE
[Request] - Embed Custom CSS

### ISSUE THREAD

**Issue by SystemLogoff** [gildas-lormeau/SingleFile#410]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to be able to embed CSS (unique to a domain as though the extension configuration if possible), so I can override how a page is displayed when saved. It would be handy if I'm grabbing the page to make it readable on other devices.

**Describe alternatives you've considered (optional)**
The userscript options could work, but would be a little clunky.

**Additional context (optional)**
![image](https://user-images.githubusercontent.com/13181256/81482157-39705e00-91f2-11ea-870f-95ec4a980473.png)
Just a text field under here that would be embedded as <style>$field</style> in the page would be great.

**Comment by gildas-lormeau** [comment]
I'm really hesitant to implement this feature for two reasons:
 - users will be forced to create multiple profiles and define multiple auto-settings rules if they want to inject a stylesheet unique to the domain. It looks complicated.
 - the integration with userscripts has been designed for this kind of specific needs. It also seems less complicated from my point of view. What do you find clunky actually?

**Comment by SystemLogoff** [comment]
It was just a nice to have request, mostly because my needs focused on a limited number of domains. If the issue would be too messy to a standard user's workflow then I do not mind using the userscript method.

**Comment by gildas-lormeau** [comment]
I can provide you the userscript to inject the CSS content if it can help you.

**Comment by gildas-lormeau** [comment]
I'm closing this issue. Feel free to comment it or reopen it if necessary though.
