### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bansan85** [gildas-lormeau/SingleFile#414]
**Describe the bug**

With Chrome and Firefox, I can't capture a specific page.

**To Reproduce**
1. Go to http://xvmdetr.cluster020.hosting.ovh.net/tmp/NF%20EN%201991-1-3-NA--A1%5bT-NO%5d%5bL-FR%5d%5b11-07%5d%5bPDF%5d.htm
2. Click on Capture
3. Be stuck at Stage 1/3

Console says :

```
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at removeCssComments (<anonymous>:6785:28)
    at Function.resolveLinkStylesheetURLs (<anonymous>:6352:29)
    at async getStylesheetContent (<anonymous>:5694:16)
    at async processElement (<anonymous>:5669:29)
    at async <anonymous>:5653
    at async Promise.all (index 1)
    at async Processor.resolveStylesheetURLs (<anonymous>:5638:4)
    at async <anonymous>:5030
    at async Promise.all (index 0)
savePage @ VM50:8022
async function (async)
savePage @ VM50:8013
onMessage @ VM50:7979
(anonymous) @ VM50:7968
(anonymous) @ chrome-browser-polyfill.js:262
```

**Expected behavior**

Be able to capture the page.

**Environment**
 - OS: Win10 Pro 1909 18363.815
 - Browser: Chrome Version 81.0.4044.138 (Build officiel) (32 bits)
 - Version : 1.17.42

**Comment by gildas-lormeau** [comment]
Thank for having reported this issue. I was able to reproduce it and fix it. The fix will be available in the version 1.17.43.

**Comment by bansan85** [comment]
Awesome. Thank for you fast correction. The commit fix it.

**Comment by bansan85** [comment]
I have to delete the URL. Is it fine or do you want to download it at a future test ?

**Comment by gildas-lormeau** [comment]
That's OK :)

**Comment by bansan85** [comment]
:) I think it's important to tell you how useful your work is. I use your plugin every day and it helps me so much to archive web page.

**Comment by gildas-lormeau** [comment]
I'm really glad to hear this :)
