### ISSUE TITLE
On Brave Browser, Google Drive option does nothing

### ISSUE THREAD

**Issue by arcane12** [gildas-lormeau/SingleFile#417]
When I turn on "save to Google Drive" using the Brave browser, there is no popup to give SingleFile permissions to use Google Drive. (I'm not logged into a Google account in the browser).

I've seen ways that let you give access by generating a key code. Maybe there's a way to do this?

**Comment by gildas-lormeau** [comment]
I guess this issue can be circumvented by exporting your settings, open the exported file in a text editor, replace `forceWebAuthFlow: false` with `forceWebAuthFlow: true` and import the settings.

**Comment by arcane12** [comment]
That let me log in. Then it shows the message "Authorization has been granted successfully. Please switch to your application." It still doesn't save the page though, and asks me every time to login. Is there a setting to put the auth key?

**Comment by gildas-lormeau** [comment]
You have to close the authorization tab actually.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because the procedure I gave you should work I did not get any feedback. Feel free to reopen it if necessary.
