### ISSUE TITLE
Add options to remove resources (images, stylesheets, fonts, frames) or keep only their URL

### ISSUE THREAD

**Issue by zeus6999** [gildas-lormeau/SingleFile#418]
Hi
how is it possible that images are not converted into base64?
I wish it remains original link

best regards

**Comment by gildas-lormeau** [comment]
Hi,

That's not possible. The purpose of SingleFile is to save all the displayed contents.

**Comment by brandonkal** [comment]
@gildas-lormeau
Along those same lines, I'd like to be able to remove elements.

I have the extension [Saka Key](https://github.com/lusakasa/saka-key) that always injects a hidden div element into all pages, but there is no need to include this in the saved file.

I would like to see the option to specify a CSS selector that gets removed in the output.
Like so:
```js
document.querySelectorAll('#saka-gui-root').forEach(el => el.remove())
```
