### ISSUE TITLE
page-title custom format

### ISSUE THREAD

**Issue by gmolveau** [gildas-lormeau/SingleFile#419]
Hi :)
Thank's for making this extension, I use it A LOT (in parallel with monolith), it's really cool !
Is-it possible to apply a custom format for the template variable `{page-title}` ?
I'd like to remove the spaces from the title and replace them with `-` or `_`.
Merci :)

**Comment by gildas-lormeau** [comment]
Hi,
I think the simplest way to do this would be to declare the white space as an invalid character. You can do this by exporting the settings of SingleFile, open the file with a text editor, and add `" "`` in the array of characters `filenameReplacedCharacters` and importing the modified file in SingleFile. Note that you can also define what replacement character to use with the setting `filenameReplacementCharacter`.

**Comment by gmolveau** [comment]
Awesome, thank's a lot and thank's for your time :)

**Comment by gildas-lormeau** [comment]
You're welcome!

Kenavo ;)

**Comment by gmolveau** [comment]
Salut Gildas, désolé de déterrer cette issue, je remarque qu'il n'y a plus le champ `filenameReplacedCharacters`. J'aimais bien l'utiliser pour avoir en sortie de SingleFile des noms de fichiers "linux friendly" (sans espace ni accent). Quelle solution existe-t-il désormais pour ce problème ? Merci :)

**Comment by gildas-lormeau** [comment]
Salut Grégoire, il n'y a pas de soucis pour le déterrage ;)

C'est bizarre, je viens de vérifier et je confime que la propriété est bien présente quand j'exporte la configuration. 

Note qu'elle est par contre désomais couplée avec `filenameReplacementCharacters` qui permet d'indiquer les remplacements à effectuer pour chacun des caractères.

Au pire, tu peux faire une remise à zéro des options pour corriger le problème. Sinon, pour éviter une remise à zéro, tu peux ajouter à la main la propriété ci dessous.

```
"filenameReplacedCharacters": [
        "~",
        "+",
        "?",
        "%",
        "*",
        ":",
        "|",
        "\"",
        "<",
        ">",
        "\\\\",
        "\u0000-\u001f"
      ]
```

**Comment by gmolveau** [comment]
Je pense que j'ai trouvé mon soucis. En fait j'ai l'impression que lorsque j'essaye d'importer mon export de 2023 via la GUI, singlefile le charge bien mais en fait il n'est pas rééllement pris en compte.
Je vais essayer de faire un reset, d'exporter et de modifier.

**Comment by gmolveau** [comment]
J'ai refait [une config](https://github.com/user-attachments/files/17956033/greg_singlefile-settings-2024-11-29T07_53_33.321Z.json), et j'ai l'impression que c'est le `{page-title}` qui ne passe pas bien au travers des `filenameReplacedCharacters`.

**Comment by gildas-lormeau** [comment]
En effet, il manque le remplacement du caractère " " par "-" dans `filenameReplacementCharacters`. Voici la configuration mise à jour ci-dessous.

```
{
  "profiles": {
    "__Default_Settings__": {
      ...
      "filenameReplacedCharacters": [
        "~",
        "+",
        "?",
        "%",
        "*",
        ":",
        "|",
        "\"",
        "<",
        ">",
        "\\\\",
        " ",
        "\u0000-\u001f",
        ""
      ],
      "filenameReplacementCharacters": [
        "～",
        "＋",
        "？",
        "％",
        "＊",
        "：",
        "｜",
        "＂",
        "＜",
        "＞",
        "＼",
        "-"
      ],
      ...
    }
  },
  ...
}
```

**Comment by gmolveau** [comment]
Ah ok c'est donc ça ! et est-il possible de faire en sorte que ca soit le `filenameReplacementCharacter` qui soit utilisé tout le temps ? (sans devoir le mettre en face de chaque `filenameReplacedCharacters`)
