### ISSUE TITLE
suddenly stopped saving to download folder (or anywhere else)

### ISSUE THREAD

**Issue by DrGary83** [gildas-lormeau/SingleFile#42]
I've been using singlefile for over a year.  Great extension!  I run Windows 7, Chrome browser.
Just today, for the first time, the file is processed, the banner presents, I click Download, and nothing gets downloaded.  The banner goes away as usual.  Searching the whole machine can't find the target files.
(I can't uncheck "process in background" as it is greyed out and checked.)
Apologies if I'm overlooking something silly.
Thanks!

**Comment by MarkWoulfe** [comment]
Having this exact same issue with Chrome on Mac (High Sierra 10.13), maybe an update to chrome has broken the ability to download?

**Comment by chumbolito** [comment]
Same here. It just stopped working. I still get the banner prompt to save the file, but nothing gets downloaded?

**Comment by adcoulter** [comment]
Not a fix, but I have noticed that (on a mac, at least) if you hold cmd while clicking 'Click here to save the page' it works still.

**Comment by adcoulter** [comment]
Right clicking + 'Save Link As..' also works, so likely just a problem triggering the download within the tab.

**Comment by DrGary83** [comment]
Thanks!!  
I really thought I'd tried those things on my Win 7 system running chrome..
Both <ctrl>-<ck> and <R-ck>, <save link as> do work.  It's not perfect but it will do.
I use this extension several times a day!

**Comment by KangarooCreativeTeam** [comment]
I CONFIRM the following workaround is good for me on Chrome v65, LINUX

1. Press Ctrl + Left Click on the "Click here to save the page" link in the yellow prompt bar.
2. OR Right Click on that link and choose "Save link as".

O_O

**Comment by marador86** [comment]
Samsung Tab A suddenly stopped showing downloaded photos in Gallery. After going insane trawling through various "fixes" and getting nowhere, FINALLY found (on this forum) the solution. So simple. STOP USING DEFAULT GALLERY APP. DOWNLOAD QUICK PIC, AND ENABLE SHOW HIDDEN FILES IN MENU. HEY PRESTO, DOWNLOAD FILE APPEARS IN ALBUMS!! 😁😁😁😁😁Thanks so much for the tip.
see: [ShowBox](https://showbox.software/) [Lucky Patcher](https://luckypatcher.pro/) [Kodi](https://kodi.software/)
