### ISSUE TITLE
PDF download / Call external program after save

### ISSUE THREAD

**Issue by Ukridge** [gildas-lormeau/SingleFile#420]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
First of all, thank you for your truly amazing job.
I would like to offer to implement these 2 features:
1) Allow to save PDF (as PDF), if it possible
2) Add an ability to call some software on local machine to postprocess saved files (for example for put them in external database).

**Comment by gildas-lormeau** [comment]
1) I did not try to save as a PDF a page processed first with SingleFile, does it make any difference compared to the PDF produced if you save the same page without using SingleFile?
2) It's impossible from a technical point of view for an extension to open an external program.

**Comment by Ukridge** [comment]
Thank you for your reply. 
1) Sorry, I meant the PDF opened in embedded pdf viewer. For example, I can open http://www.africau.edu/images/default/sample.pdf directly in browser. And all I want is to download this file an do some postprocessing (with the callback provided by SingleFile). But I cannot save this file with SingleFile (it shows the stop sign on SingleFile icon).
2) Thanks for explanation. I belive that there's a way of calling external application (at least at Firefox) but, as I googled today, it's very application-specific, so it's obviously should not be implemented in your extension.

**Comment by gildas-lormeau** [comment]
Sorry for my late response. I totally forgot to answer you. 

1. Browsers don't allow extensions to run in the pdf viewer, the reader view, internal pages, etc. Thus, I would need to write a PDF reader to integrate SingleFile.
2. Indeed, since SingleFile runs on multiple platforms, I prefer to keep the code as universal as possible.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because saving in PDF is not in the scope of SingleFile currently, and calling external programs is not possible in browsers. Feel free to reopen it or comment it if necessary.
