### ISSUE TITLE
Scrolling option in CLI

### ISSUE THREAD

**Issue by amiiigh** [gildas-lormeau/SingleFile#422]
Hi, 

Thanks for your amazing repo.

How can I use this feature in cli?

![image](https://user-images.githubusercontent.com/6973168/82830178-04673b00-9e83-11ea-8599-b2aa47e0820c.png)

Which one is better, using --browser-height with a very large number or scrolling the page?

Thanks again

**Comment by amiiigh** [comment]
I guess --load-deferred-images does the same thing in cli. Is that right?>

**Comment by gildas-lormeau** [comment]
Yes, that switch which is enabled by default should give you the same result. However it is also possible to inject a script with --browser-scripts that would scroll into the page by using the events exposed to [user-scripts](https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved).

**Comment by gildas-lormeau** [comment]
If you really want to autoscroll, create a file named `autoscroll.js`, paste the content below into the file, save the file into the `cli` folder and run SingleFile with the switch `--browser-scripts=./autoscroll.js`

```
const SCROLL_STEP_PX = 500;
const SCROLL_STEP_DELAY = 200;

dispatchEvent(new CustomEvent("single-file-user-script-init"));

addEventListener("single-file-on-before-capture-request", event => {
	autoscroll();
	event.preventDefault();
});

function autoscroll() {
	const previousScrollY = scrollY;
	scrollBy(0, SCROLL_STEP_PX);
	if (previousScrollY < scrollY) {
		setTimeout(autoscroll, SCROLL_STEP_DELAY);
	} else {
		dispatchEvent(new CustomEvent("single-file-on-before-capture-response"));
	}
}
```
