### ISSUE TITLE
Filename conflict with "Nimbus Screenshot and Screen Recorder"

### ISSUE THREAD

**Issue by DarthSaber** [gildas-lormeau/SingleFile#423]
As a historian, the "SingleFile" Chrome extension is an invaluable tool which enables me to save a web page exactly as displayed. 

However, as long as the "Nimbus Screenshot and Screen Recorder" Chrome extension is enabled, SingleFile will generate a unique file name composed of letters and numbers for every file it saves, regardless of what parameters are set in its "Extension Options". Once Nimbus is disabled however, then SingleFile will save pages with the correct naming system as specified.

Every web page provides information but does not control what apps or extensions are able to scan their data, rather this depends on the abilities programmed into the app or extension that allow it to do so.

Thus SingleFile should save pages properly according to the parameters set regardless of whether or not Nimbus or any other file saving app is installed and enabled. As a historian, both SingleFile and Nimbus are invaluable aids in my research work and I need SingleFile to operate properly.

**To Reproduce**
1. Download Chrome and update it to the latest release.
2. Download and install both the "Nimbus Screenshot and Screen Recorder" and SingleFile extensions and ensure that they are enabled for use.
3. Open any web page and use SingleFile to save the file.
4. The error will be almost immediately apparent.

**Expected behavior**
The file will be saved with a randomly generated name, regardless of the parameters set.

**Screenshots**

**Environment**
![5-25-2020 Google Chrome Extensions](https://user-images.githubusercontent.com/65920975/82840158-3bdfe280-9e97-11ea-9add-610ea5b9c495.png)

![5-25-2020 BBC Homepage](https://user-images.githubusercontent.com/65920975/82840390-ff60b680-9e97-11ea-88f5-033491c1485d.png)

![5-25-2020 Randomly generated file name](https://user-images.githubusercontent.com/65920975/82840400-10112c80-9e98-11ea-8f68-d9f0ec691a10.png)

 - OS: Windows 10 Professional
 - Browser: Google Chrome 
 - Version 83.0.4103.61 (Official Build) (64-bit)

**Additional context**

**Comment by gildas-lormeau** [comment]
Thank you for having reported the issue. Unfortunately, there is nothing I can do on my end to fix this conflict. This is a bug in Chrome that is documented in the [known issues](https://github.com/gildas-lormeau/SingleFile#known-issues).

**Comment by gildas-lormeau** [comment]
@DarthSaber any news following my suggestion?

**Comment by gildas-lormeau** [comment]
I'm closing the issue because it's a known issue and I indicated how to circumvent it. Note that Google closed this bug as "WONTFIX".
