### ISSUE TITLE
Imgur albums incomplete

### ISSUE THREAD

**Issue by peasantdave** [gildas-lormeau/SingleFile#424]
**Describe the bug**
Trying to save Imgur albums with the descriptions for all the images. I scroll down in the album and make sure to click any expansions like "Load 16 more images".  After saving with SingleFile it seems that only the images around what is on the screen at the current time are saved. I've tried changing Images > "maximum idle time (ms)" to 6000, trying Incognito, and also resetting all settings but still not able to see all images in the album. 

**To Reproduce**
1. Go to 'https://imgur.com/gallery/m1Qxl3b'
2. Scroll down to "Load 16 more images" to load everything.
3. Click on 'SingleFile extension to save page
4. Open saved file and see that it is not complete. 

**Expected behavior**
Should save the album as it is seen on the screen with all images and their descriptions. 

**Screenshots**
Live page: https://i.imgur.com/Wcy6DL6.jpg
SingleFile version: https://i.imgur.com/DOSWFcx.png
Both: https://imgur.com/a/zIRjJ4S

**Environment**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 83.0.4103.61

**Comment by gildas-lormeau** [comment]
This issue was discussed here: https://github.com/gildas-lormeau/SingleFileZ/issues/29. This issue can't be fixed in Chrome because imgur.com is relying on some kind of poorly implemented lazy-loading. However, I was able to save this page in Firefox.

**Comment by peasantdave** [comment]
Thanks for the tip about Firefox and sorry for the duplicate issue. I search for past issues on SingleFile but did not know SingleFileZ existed until now. Keep up the great work!

**Comment by gildas-lormeau** [comment]
No worry for the duplicate, I was not meaning you should have found it ;).
