### ISSUE TITLE
Vivaldi 3 extension context-menu not working.

### ISSUE THREAD

**Issue by Leidenfrosty** [gildas-lormeau/SingleFile#425]
**Describe the bug**
When right-clicking on the extension in Vivaldi 3, the context-menu does not show up.

**To Reproduce**
1. Right-click on the extension.
2. See error.

**Expected behavior**
Context-menu showing up. I would like to toggle auto-save.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/42622027/82928299-5773e780-9f82-11ea-9fb7-efae49145961.png)

**Environment**
 - OS: [Ubuntu 20.04. LTS]
 - Browser: [Vivaldi]
 - Version: [3.0.1874.38]

**Additional context**
I don't even need the context-menu, I just want a way to enable autosave.

**Comment by gildas-lormeau** [comment]
I did the test and confirm the issue. The context-menu on the icon is not displayed in Vivaldi. To open the context menu of SingleFile, you have to display it from the page itself.
