### ISSUE TITLE
How do I access the custom user script?

### ISSUE THREAD

**Issue by Seminko** [gildas-lormeau/SingleFile#426]
I updated the JSON, imported the options, all good. Where do I write the custom javascript to be performed before saving a page?

**Comment by gildas-lormeau** [comment]
Did you install an extension to run user scripts like GreaseMonkey, TamperMonkey etc.?

**Comment by Seminko** [comment]
Did some searching on user scripts. First of all, I didn't even know what they were. I thought you had some user-script.js ¨file that can be updated and "uploaded" to the extension :).

Maybe it wouldn't be a bad idea to update the link (https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved) to explain further.

Will try later today after work. Thanks

**Comment by Seminko** [comment]
In the end, I went a completely different route.

**Comment by gildas-lormeau** [comment]
Ok... What did you do, out of curiosity?

**Comment by Seminko** [comment]
Actually wrote my own extension that downloads what I need it to download and made it so that it shares the folder name structure with SingleFile so that both the HTML file and the files my extension downloads end up in the same place. ;)

**Comment by gildas-lormeau** [comment]
I see. I think you made the good choice, I'm unsure user scripts would be powerful enough for your use case. Thank you for the feedback :)

**Comment by Seminko** [comment]
Likewise, thanks for your awesome extension! I will help my old man a lot :)
