### ISSUE TITLE
SVG inlined appears to be in source but displays as a white rectangle

### ISSUE THREAD

**Issue by paul-hammant** [gildas-lormeau/SingleFile#429]
**Describe the bug**

SVGs appear to save, but render incorrectly in resulting single-file.  Note the SVGs in question are onDocumentLoad() modified with JQuery to add colors.

**To Reproduce**

1. Go to https://www.branchbyabstraction.com  
2. Save page as SingleFile
3. Open result in FF or Chrome

**Expected behavior**

The SVGs that are inlined in the page are as they appear in the original and not white.

**Screenshots**

![](https://user-images.githubusercontent.com/82182/83763652-dd71eb80-a670-11ea-808d-fd01e5fcb7fa.png)

**Environment**
 - OS: Mac 10.14.6
 - Browser: Chrome
 - Version: 83.0.4103.61

**Additional context**

None

**Comment by gildas-lormeau** [comment]
Thank you for the issue. It's really weird. Right now, I have absolutely no idea why the SVG images are not displayed.

**Comment by gildas-lormeau** [comment]
The issue was due to a bug in the code that produces the HTML content. The `<source>` tag of the SVG images was incorrectly considered as a `<source>` tag in HTML. This leaded the `</source>` tag to be removed and make the resulting SVG invalid. The fix will be available in the version 1.17.47.
