### ISSUE TITLE
Processed page cannot be saved.

### ISSUE THREAD

**Issue by smwikipedia** [gildas-lormeau/SingleFile#43]
Reproduce steps:
1. Choose "process page" from the right-click menu;
2. Click save prompt bar as below:
![save page](https://user-images.githubusercontent.com/999318/37873650-8501af66-3053-11e8-8868-a521384c6aef.png)

Result: The prompt bar disappeared and nothing get saved.

If I right click the prompt bar and choose "open in a new tab". I can see the page (probably the processed one) with strange URL like this:

`blob:chrome-extension://mpiodijhokgodhhofbcjdecpffjipkle/7d2e641e-2306-43bf-9edb-9a552e3b31e1`

I am using:

Chorme 65.0.3325.181 64bit version
Windows 10 version 1607.

**Comment by smwikipedia** [comment]
Same issue as https://github.com/gildas-lormeau/SingleFile/issues/42

**Comment by rytch0** [comment]
Same problem.  Right clicking only invokes the standard Chrome html save.

**Comment by KangarooCreativeTeam** [comment]
I CONFIRM the above-mentioned workaround is good for me on Chrome v65, LINUX

1. Press Ctrl + Left Click on the "Click here to save the page" link in the yellow prompt bar.
2. OR Right Click on that link and choose "Save link as".

O_O

**Comment by hents3** [comment]
Same issue with Google Chrome 65.0.3325.181 (64-bit).

**Comment by vrapp** [comment]
Was the same with Chrome 65.0.3325.181 (64-bit), but after updating Chrome to  66.0.3359.139 (64-bit) works as expected.
