### ISSUE TITLE
Saved Page Info Bar Data

### ISSUE THREAD

**Issue by sj365** [gildas-lormeau/SingleFile#430]
**Is your feature request related to a problem? Please describe.**

If I have asked you this before, my apologies.  I am interested in the possibility of you modifiying the SingleFile saved page Info icon to make it more easily readable and accessible.

**Describe the solution you'd like**

Ideally, the Info bar should be accessible and viewable regardless if it is opened in a browser that doesnt have the Singlefile extension installed.  Currently this is not the case.

**Describe alternatives you've considered (optional)**

An example of this would be how Save Page WE infobar is accessible and viewable on any browser that can open an .html file.  The info bar is also neatly presented across the width of the page and not squished together like the Singlefile icon bar.

**Additional context (optional)**

The overall request is to improve Singlefile saved pages value as a web archive technology application.  Currently, Singlefile infobar archive info can be seen only if the appliation is installed in the browser.  Any person reviewing the saved page in a browser without the application installed would not see it and would have difficulty verifying the actual original website location and date/time saved information, which then cant be used directly as references for school reports, library type archiving purposes, etc.  Mozilla Archive Format also had a full width Info Bar that was excellent.

**Comment by gildas-lormeau** [comment]
Doesn't the option "HTML content > include the infobar in the saved page" fixes this issue?

**Comment by sj365** [comment]
Hi,
the option "HTML content > include the infobar in the saved page" does not
fix this issue.  Please see the attached screenshots.  It is not just the
aesthetic; the Singlefile .html file infobar will not show if the browser
is not running Singlefile extension.

Thanks

**Comment by gildas-lormeau** [comment]
There is no screenshot attached. However, I can confirm that the option "HTML content > include the infobar in the saved page" works as expected and allows to have the infobar displayed even if SingleFile is not installed.

**Comment by gildas-lormeau** [comment]
@sj365 Any news?

**Comment by sj365** [comment]
Hi,

I just tried in another computer without Singlefile and i do see the info
icon on the saved page.

Thanks

**Comment by gildas-lormeau** [comment]
Great! Thanks for the feedback.

**Comment by sj365** [comment]
Hello,

I noticed very recently SingleFile is not able to capture Facebook or
Twitter images embedded in webpages that are not Facebook or Twitter.  I
use SingleFile to save newspaper articles and it usually works well.  Today
I see that it is not able to save the images anymore.  Is there a setting
that needs to be changed or is this an issue with the application?

Thanks

Example
https://www.washingtonpost.com/nation/2020/07/27/walmart-mask-nazi-minnesota/?itid=pr_hybrid_experimentrandom_with_top_mostshared_4_na-ans_4

**Comment by gildas-lormeau** [comment]
I don't see any Facebook or Twitter block in this page. On my end, the saved page is okay. I attached it in the zip file below.

[Minnesota Walmart shoppers wearing Nazi flag masks banned from all stores after viral video - The Washington Post (2020-07-27 1_43_03 AM).zip](https://github.com/gildas-lormeau/SingleFile/files/4985185/Minnesota.Walmart.shoppers.wearing.Nazi.flag.masks.banned.from.all.stores.after.viral.video.-.The.Washington.Post.2020-07-27.1_43_03.AM.zip)

Do you confirm the option "HTML content > remove frames" is disabled in your settings?

**Comment by sj365** [comment]
Hello,

I can confirm that HTML content - remove frames is disabled.  See attached
screenshot.  Can you export your settings and forward to me?  I haven't
changed any options recently but there may still be a conflict with how my
SF is optioned.  My settings are also attached to see if my configuration
is bad.

Also, I remember seeing a post where you mentioned that SF inability to
save a page with the correct title instead of numbers/letters was a google
issue.  I discovered that for me the issue was the extension DownThemAll! 4.2.6
.  When enabled with SF enabled, it interfered with SF naming.  So I
keep DownThemAll!
disabled until i need to use it.


Thanks,

Shavar
