### ISSUE TITLE
Created file not opening with Chrome browser

### ISSUE THREAD

**Issue by Rob-the-knob** [gildas-lormeau/SingleFile#431]
The Singlefilez file created in Opera with your extension opens flawlessly with Firefox but NOT with Chrome or with Opera itself.

The error message while trying to open the file in Opera or Chrome:

_Error: Cannot open the page from the filesystem.
Chrome: Install SingleFileZ and enable the option "Allow access to file URLs" in the details page of the extension (chrome://extensions/?id=offkdfbbigofcgdokjemgjpdockaafjg). Otherwise, start the browser with the switch "--allow-file-access-from-files".
Safari: Select "Disable Local File Restrictions" in the "Develop" menu._

**Comment by gildas-lormeau** [comment]
Well, you have to follow what the error message says, i.e. install SingleFileZ or enable the option "Allow access to file URLs" in the details page of the extension (chrome://extensions/?id=offkdfbbigofcgdokjemgjpdockaafjg). This issue is due to a limitation in Chromium-based browsers.

**Comment by Rob-the-knob** [comment]
Well..., that is kind of moronic. 
I want to create a single html file which opens on any browser but then I have to install your extension on every browser first?

**Comment by gildas-lormeau** [comment]
Then use SingleFile, not SingleFileZ ;)

**Comment by gildas-lormeau** [comment]
Note that SingeFileZ produces zip files so you have also the option to unzip it in order to view it.

**Comment by Rob-the-knob** [comment]
I've already figured that out. 
To my surprise I saw you are the developer of this excellent extension also.
I use this extension for years now and it's nice.
However what is the difference between these 2?
Why develop Singlefilez when Singlefile is perfect?

**Comment by gildas-lormeau** [comment]
I developed SingleFileZ for Firefox users. When I noticed the limitation of Chrome, I didn't plan to publish the extension on it. However, some users convinced me that it was worth it.

Some recurrent complains about SingleFile were:
 - files are too big
 - it does not produce MAFF files

SingleFileZ tries to fix these 2 issues. Honestly, I also coded it because I thought it would be really cool to produce self-extracting HTML files. That was a first, as far as I know.

**Comment by Rob-the-knob** [comment]
Okay...., however Singlefilez is not a good idea because it's very buggy with a lot of issues.
By the way, I'm the person who at first gave you 1 star for Singlez and later on changed my mind and finally gave a 5 star rating.
Now I'm doubting the 5 stars because the Singlez extension is far from flawless....

**Comment by gildas-lormeau** [comment]
Your review was referring to SingleFile, not SingleFileZ. 

Anyway, feel free to give 1 star to SIngleFileZ, SingleFile and any other open-source and personal projects which are "very buggy and have a lot of issues".

**Comment by gildas-lormeau** [comment]
By the way, since it's a separated project the issue tracker of SingleFileZ is here: https://github.com/gildas-lormeau/SingleFileZ

**Comment by Rob-the-knob** [comment]
Okay...., thank you.
