### ISSUE TITLE
Cannot save pages from https://www.dailymail.co.uk/ with 'Deferred Images' checked

### ISSUE THREAD

**Issue by noto10** [gildas-lormeau/SingleFile#433]
Pages from https://www.dailymail.co.uk/ cannot be saved with 'Deferred Images' checked (for example - https://www.dailymail.co.uk/news/article-8435211/How-people-REALLY-died-Covid-19.html). Doing so will freeze Firefox with a CPU spike until the process is killed. May be related to this bug:

https://github.com/gildas-lormeau/SingleFile/issues/415

Is there any way to resolve this other than disabling 'Deferred Images' since that is useful?

Firefox 78.0 beta
Singlefile 1.17.47
Win 10 64

**Comment by gildas-lormeau** [comment]
This issue is not related to #415. This is due to the fact that if you click save the page with SingleFile without scrolling first then SingleFile has to load approximately 400 images at the same time. This is the reason why you can see a freeze or a CPU spike.

**Comment by noto10** [comment]
> 
> 
> This issue is not related to #415, which is fixed. This is due to the fact that if you click save the page with SingleFile without scrolling first then SingleFile has to load approximately 400 images at the same time. This is the reason why you can see a freeze or a CPU spike.

So the solution to saving pages with numerous images is to first scroll to the end before saving? It worked as I have just tested but would like to check with you.

**Comment by gildas-lormeau** [comment]
Yes, or just to ignore the frost and wait. In fact, manual scrolling should consume as much as computing power, but more slowly.

**Comment by abolibibelot1980** [comment]
Two years ago I solemnly vowed never to go back to dailymail.co.uk — it's toxic for the soul, seriously! I mean, even regardless of the dreadful content of the articles, just the layout with that neverending right column full of slutty pictures and clickbait links almost drove me insane each time I foolishly tried to read just that one article on dailymail.co.uk... If there's a Hell it must feel like a dailymail.co.uk webpage with infinite auto-scroll showing pictures of aging actresses' crotches swarming with cockroaches...
Sorry, I had to let it out of my system.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because it the option works as expected? It's just very demanding on CPU.
