### ISSUE TITLE
Images and status

### ISSUE THREAD

**Issue by khabib227** [gildas-lormeau/SingleFile#434]
Some pages just show the text with javascript, sometimes we want save all tabs just the html with text (loaded by JS) without images, so please add a option to ignore images, or to don't save any image in the file. And a feature to show the progress when saving multiple tabs.

thanks

**Comment by gildas-lormeau** [comment]
>  And a feature to show the progress when saving multiple tabs.

This feature exists. It's the "pending saves" view that you can open via the context menu.

**Comment by khabib227** [comment]
@gildas-lormeau  thanks for info, please think about the option to ignore all images,

**Comment by gildas-lormeau** [comment]
You're welcome. Regarding the option, it can be tracked here: https://github.com/gildas-lormeau/SingleFile/issues/418.
