### ISSUE TITLE
Function to specify storage location(future request)

### ISSUE THREAD

**Issue by TokyoSoichiro** [gildas-lormeau/SingleFile#436]
Please allow me to have future request.
I am glad if I can make some **preferences for save locations**.
Cause the addon will save automatically to Download folder, Download folder become messy with a lot of html files.  It is very convinient if I(maybe we) can make some specific folder and have preferences to save to this folders.
(eg.)Preferences for save location(like C:\2020\Singlefile_Downloaded)
Thank you and sorry for non-native English.

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. Unfortunately, that's technically impossible to choose another folder than the Downloads folder. However, you can store pages into sub folders of the Downloads folder by changing the setting "File name > template" in SingleFile. For example, if you set it to `2020/SingleFile/{page-title} ({date-iso} {time-locale}).html`, pages will be saved into the sub folder "2020/SingleFile".

**Comment by JackJohnJoe** [comment]
Hum, isn't it already possible? Options > File name > open "Save as" dialogue to confirm the file name
It seems to work for me

**Comment by gildas-lormeau** [comment]
Sure, but it cannot be automated, i.e. save files automatically outside the Downloads folder.

**Comment by TokyoSoichiro** [comment]
Thank you for comment!
I did not know that there is technical difficulties to implement this feature.

+How about setting preference on Firefox itself?
This idea might be good because dialog will be shown to select the folder path.   But I cannot save html file to specifil path automatically.
+Solution
Thank you for idea of setting like 

> "File name > template" in SingleFile. For example, if you set it to 2020/SingleFile/{page-title} ({date-iso} {time-locale}).html

This idea really WORKS!
Thank you for your help and reccomend to use this setting so that your folder won't be mess.
THANKS! I will close this issue for now.
