### ISSUE TITLE
Disable keyboard shortcut

### ISSUE THREAD

**Issue by genuinefafa** [gildas-lormeau/SingleFile#44]
Hi there! 

I'm currently having issues with the control+alt+shift+S shortcut and found no way to disable it. 
How can I?

pst: it is used by Netflix

**Comment by gildas-lormeau** [comment]
Fixed in 1.0.0

**Comment by gildas-lormeau** [comment]
You can use and configure the shortcut only in Chrome today. For this, go to chrome://extensions/shortcuts. I don't know why it does not work on Firefox. I need to investigate on this.

**Comment by gildas-lormeau** [comment]
I think I found the reason it does not work on Firefox. Ctrl-Shift-X seems to be reserved for another purpose but Ctrl+Shift+Y works. I'll change it in the next version.

**Comment by gildas-lormeau** [comment]
The new version (1.9.30) changing the default shortcut to Ctrl+Shift+Y has been released.

**Comment by cmvizitiu** [comment]
Oh... I suppose there's no way we (Firefox) users can define/reassign the shortcut? But thank you.anyway, any shortcut is better than no shortcut at all! :)

**Comment by gildas-lormeau** [comment]
I hope it will be available in Firefox 66, cf. the corresponding issue here: https://bugzilla.mozilla.org/show_bug.cgi?id=1303384.

**Comment by cmvizitiu** [comment]
Well then all my hopes and prayers are with the developers working on that bug cos' on XFCE Fedora 28 Ctrl+Shift+y in Firefox 64 opens the "Library" window. :-|

**Comment by gildas-lormeau** [comment]
@cmvizitiu FYI, https://www.reddit.com/r/firefox/comments/ag8uyv/you_can_now_manage_keyboard_shortcuts_of/
