### ISSUE TITLE
The opening <Head> tag is missing

### ISSUE THREAD

**Issue by skycommand** [gildas-lormeau/SingleFile#445]
**Describe the bug**
The opening \<head\> tag is missing from the output.

**To Reproduce**
1. Navigate to <https://www.example.com>
2. Click on 'Save page with SingleFile'
3. Open the file in a text editor
4. Observe the following:
   ````html
   <!DOCTYPE html> <html><!--
    Page saved with SingleFile 
    url: http://www.example.com/ 
    saved date: Mon Jul 13 2020 13:17:49 GMT
   --><meta charset=utf-8>
   <title>Example Domain</title>
   <meta name=viewport content="width=device-width, initial-scale=1">
   <style>body{background-color:#f0f0f2;margin:0;padding:0;font-family:-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI","Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif}div{width:600px;margin:5em auto;padding:2em;background-color:#fdfdff;border-radius:0.5em;box-shadow:2px 3px 7px 2px rgba(0,0,0,0.02)}a:link,a:visited{color:#38488f;text-decoration:none}@media (max-width:700px){div{margin:0 auto;width:auto}}</style>
   <link type=image/x-icon rel="shortcut icon" href="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="><link rel=canonical href=http://www.example.com/></head>
   <body data-gr-c-s-loaded=true>
   <div>
    <h1>Example Domain</h1>
    <p>This domain is for use in illustrative examples in documents. You may use this
    domain in literature without prior coordination or asking for permission.</p>
    <p><a href=https://www.iana.org/domains/example>More information...</a></p>
   </div>
   ````
5. Note that there is no `<head>` before `<meta charset=utf-8>`.

**Expected behavior**
Any valid HTML file must have an opening  `<head>` tag for every closing `</head>` tag.

**Screenshots**
N/A

**Environment**
 - OS: Windows 10 version 20H1 (Build 19041.329) x64
 - Browser: Firefox 78.0.2
 - Version: 1.17.53 (2020-07-11)

**Additional context**
N/A

**Comment by gildas-lormeau** [comment]
This is a feature. By default, SingleFile removes optional tags when possible. Note that the HTML is still valid though, see https://html.spec.whatwg.org/multipage/syntax.html#optional-tags for more information. To disable this feature, uncheck the setting "HTML content > compress HTML content".

**Comment by skycommand** [comment]
But the closing `</head>` tag is still there.
