### ISSUE TITLE
Manually enter annotation editor when viewing webpage already saved with SingleFile

### ISSUE THREAD

**Issue by Torenga** [gildas-lormeau/SingleFile#446]
**Is your feature request related to a problem? Please describe.**
I would like to manually select when to use the annotation editor for already saved pages instead of having to toggle it from the settings and reloading the page.

**Describe the solution you'd like**
An entry on the SingleFile icon menu and/or entry on right click menu to "Enter annotation editor".

**Describe alternatives you've considered (optional)**
"Toggle annotation mode" entry in menu.

Thank you for an extension already as essential as ad-block!

**Comment by gildas-lormeau** [comment]
The option in the settings you're referring to is "User interface > open pages saved with SingleFile in the annotation editor"?

**Comment by Torenga** [comment]
Yes, spot on.

**Comment by gildas-lormeau** [comment]
Out of curiosity, why don't you let it enabled and need to toggle it?

**Comment by Torenga** [comment]
Streamlining use and visual design.

I've already implemented it in my workflow as a replacement for Pocket/Wallabag and bring up reference pages quite a lot. Seeing the annotation editor when I just want to view the page is taking attention away from the content and seeing the annotation editor when I just want to save the page with the default settings and no annotation is an extra click.

Being "forced" to always stay in annotation mode makes this a fantastic extension instead of the perfect extension. :wink:

**Comment by gildas-lormeau** [comment]
It's almost implemented... There is a bug in Chrome where it does not seem to work without reloading the extension first. Stay tuned ;)

**Comment by gildas-lormeau** [comment]
The version 1.17.54 I just uploaded implement this new feature. When viewing a saved page, the entry "Annotate and save the page..." in the context menu will be replaced with "Annotate the page..." in order to open the saved page directly in the annotation editor. The new version will be available for download in a few days, after it has been reviewed by Mozilla , Google, and Microsoft.

**Comment by gildas-lormeau** [comment]
I just fixed a minor issue in the latest version (1.17.56) that fixes the back button with the editor. It means that if you view an archive, switch to the annotation editor and you want to view the archive again, you'll just have to press the back button.
