### ISSUE TITLE
Is it possible remove blank area in the wikipedia page?

### ISSUE THREAD

**Issue by orientune** [gildas-lormeau/SingleFile#447]
Hi, I saved selection in Wikipedia but there is blank area. Can I delete this space easily? And photos' extensions (src) are very long, can I make shorter
![Screenshot_2](https://user-images.githubusercontent.com/41265396/87925012-56de6580-ca88-11ea-9c77-8c93e7d6694a.png)

![Screenshot_1](https://user-images.githubusercontent.com/41265396/87925815-8346b180-ca89-11ea-99ae-61877787552c.png)

**Comment by gildas-lormeau** [comment]
Regarding the blank parts to remove, I would recommend to enable the setting "User interface > annotate the page before saving" in SingleFile. Then you can use the "scissors" button in the annotation editor to remove unwanted contents.

The value of the "src" attribute is the image encoded in base 64. It cannot really be shortened. Maybe [SingleFileZ](https://github.com/gildas-lormeau/SingleFileZ) would fulfill your needs.

**Comment by orientune** [comment]
Thank your very very very much. I learnt scissors with your advice,it is good feature, I will use more. But I couldnt delete left blank part, if I cut , all page disable. My goal is creating android app that you can read without internet.If you have any idea ,glad you. Already thank you very much replying me , I am not expert.
 
SingleFileZ is good extensions but its saved page cant open with html editor.But thank you very much.

**Comment by gildas-lormeau** [comment]
I cannot reproduce the blank issue. Could you please post the page you saved?

Removing links is a very specific feature but this could be done via a [userscript interacting with SingleFile](https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved). Let me know if you're interested in this solution and I'll give you the instructions to follow.

**Comment by orientune** [comment]
Thank you very much, later I can do. I must learn programming.Good luck.

**Comment by gildas-lormeau** [comment]
You're welcome :)
