### ISSUE TITLE
How to use with Selenium and Python

### ISSUE THREAD

**Issue by ScribbleGhost** [gildas-lormeau/SingleFile#448]
Hi

Thanks for making this great extension. I have used it a lot and it is super helpful!

I am trying to trigger SingleFile in Python with Selenium running Python 3.6.

This is what I have so far. It basically just runs Chromedriver, installs SingleFile and opens a webpage.

```
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By

options = Options()
options.add_extension('SingleFile.crx')
options.page_load_strategy = 'none'
driver = webdriver.Chrome(options=options, executable_path='C:/portable/chromedriver/chromedriver.exe')
driver.get("https://html5example.com")
```

I am stuck at actually triggering the SingleFile button. I know this is not an issue per se, but I thought it shouldn't hurt to ask.

Any ideas on how I can do this?

**Comment by gildas-lormeau** [comment]
I would recommend you to avoid using SingleFile as an extension since the code is designed to run directly in Selenium. To make it run with Python, you have basically to translate this code in Python: https://github.com/gildas-lormeau/SingleFile/blob/master/cli/back-ends/webdriver-gecko.js.

**Comment by ScribbleGhost** [comment]
Hmm.. I am not that js savy. Might have to find another way. Just realized I haven't read the [CLI](https://github.com/gildas-lormeau/SingleFile/blob/master/cli/README.MD) docs. Thanks for feedback, much appreciated 🙏

**Comment by gildas-lormeau** [comment]
You're welcome. I'm closing the issue because I don't plan to support other languages to control the browser right now. Feel free to comment it or reopen it if necessary though.

**Comment by hassanseoul123** [comment]
@ScribbleGhost You can use pyautogui to send ctrl+shift+y key (it is a shortcut key used to invoke SingleFile Extension)

`import pyautogui
pyautogui.hotkey('ctrl', 'shift', 'y')`

**Comment by robertog09** [comment]
> @ScribbleGhost You can use pyautogui to send ctrl+shift+y key (it is a shortcut key used to invoke SingleFile Extension)
> 
> `import pyautogui` `pyautogui.hotkey('ctrl', 'shift', 'y')`

If there is a need to rename the recently downloaded file after running

`import pyautogui`
`pyautogui.hotkey('ctrl', 'shift', 'y')`

the following code can be run:

```
# Import required packages
import glob
import os

# List of files
list_of_files = glob.glob('C:/Users/User/Downloads/*.html')

# Get most recent created .html file
latest_file = max(list_of_files, key=os.path.getctime)

# File name
file_name = 'File Name'

# Rename file
os.rename(src=latest_file, dst='C:/Users/User/Desktop/{file_name}.html'.format(file_name = file_name))
```

**Comment by codejunction** [comment]
can you trigger the extension via javascript as a selenium script rather than other methods ?

**Comment by gildas-lormeau** [comment]
Here are the generic instructions in order to use SingleFile: https://github.com/gildas-lormeau/SingleFile/wiki/How-to-integrate-SingleFile-library-code-in-%22custom%22-environments%3F
