### ISSUE TITLE
Does not work on WordPress posts

### ISSUE THREAD

**Issue by Lerie82** [gildas-lormeau/SingleFile#45]
I tried to use this on a single post on a wordpress page, it only gives the wordpress sites' 404 page as the generated HTML file

![screenshot 2018-07-04 at 9 26 04 am](https://user-images.githubusercontent.com/29735511/42287719-4d6243e6-7f6c-11e8-9c87-1a0b593d1a95.png)

**Comment by gildas-lormeau** [comment]
That's weird... Could you give me an example of URL to test?

**Comment by Lerie82** [comment]
This is the URL I tested with it first, https://lerie.us/blog/2018/06/16/coding-a-bootstrap-admin-theme-in-php-part-1-installation-overview/

**Comment by gildas-lormeau** [comment]
There is a CSS which is not found (https://lerie.us/blog/2018/07/02/wordpress-plugin-review-wp-static-html-output/loader/prettify.css). This URL should have been removed from the saved page. It is now fixed in version 1.0.7.
