### ISSUE TITLE
Add ability to specify where to save file

### ISSUE THREAD

**Issue by embash** [gildas-lormeau/SingleFile#453]
**Is your feature request related to a problem? Please describe.**
My behavior with browsers is to save each download to a location I specify rather than a default location. With SingleFile, I have to navigate to the saved location and move the file by hand to the desired location.

**Describe the solution you'd like**
It would be practical to have the option (like in the Firefox settings) to specify to ask me where to save the file.

**Describe alternatives you've considered (optional)**
No alternative or additional context considered so far.

**Comment by gildas-lormeau** [comment]
That's not technically possible today. That should be possible once this API https://caniuse.com/#feat=native-filesystem-api will exist in browsers though.

**Comment by gildas-lormeau** [comment]
Actually, I might have misunderstood the issue. Doesn't enabling the setting "File name > open the "Save as" dialog to confirm the file name" fix it?

**Comment by Torenga** [comment]
Yes. On my Ubuntu FF that would bring up the last used directory, allowing me to manually navigate to the desired directory. This is my current workflow specifically to solve the ticket issue.

**Comment by gildas-lormeau** [comment]
Please also disable `Misc > Save pages in background`.

**Comment by gildas-lormeau** [comment]
I'm closing this issue, make sure that the option `Misc > Save pages in background` is disabled and that your browser is configured to open the Save as dialog when downloading files.
