### ISSUE TITLE
search note

### ISSUE THREAD

**Issue by FreddyZeng** [gildas-lormeau/SingleFile#454]
I want a feature that is search note

**Comment by Torenga** [comment]
Content in the saved page? IMO that should be handled by the browsers built in search function (Ctrl-F on FF/Chromium IIRC).

A dedicated search function provided by SingleFile would just add another way of doing what the browser already does.

Same for saved html-pages, the OS file managers should provide the search function.

**Comment by gildas-lormeau** [comment]
@FreddyZeng Can you give more details? I agree that the built-in search could be sufficient to search a note from text. However, I could maybe add an icon in the header to navigate from notes to notes for example.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because it is too vague and I'm not really inspired. Feel free to comment it to give more details or reopen it if necessary.
