### ISSUE TITLE
No way to turn off Auto-save

### ISSUE THREAD

**Issue by sj4nes** [gildas-lormeau/SingleFile#455]
**Describe the bug**
Auto-save seems to have turned itself on. There is no way to turn it off from the Options.

**To Reproduce**
1. Go to menu for auto-save status. Claims it is not enabled.
2. Go to the extension options page. Auto-save is marked as "auto-save after page load or on page unload".
3. Try unchecking this option.
4. It turns off, but the option "auto-save after page load" flips on.
5. Click to disable auto-save after page load "off."
6. "auto-save after page load or on page unload" then flips back on.

**Expected behavior**
Some way to disable auto-save.

**Environment**
 - OS: Linux
 - Browser: Firefox
 - Version: Firefox version 77.0.1; SingleFile version 1.17.56

**Comment by sj4nes** [comment]
More information: for me, this seems to have started on July 18th when the extension auto-updated.

**Comment by gildas-lormeau** [comment]
The options page does not help to enable or disable the auto-save. To do so, you have to use the context menu of the extension (e.g. right click on a page), and select "SingleFile > Auto-save > disabled" for example.

**Comment by sj4nes** [comment]
That menu option for Auto-save was already marked as "Disabled."

I temporarily disabled the entire extension and re-enabled the extension.  So far, it hasn't been auto-saving pages. So now I cannot reproduce. :shrug: Closing.

**Comment by gildas-lormeau** [comment]
I introduced a regression in the version 1.17.56. "Autosave this tab" was broken. It's fixed with https://github.com/gildas-lormeau/SingleFile/commit/2cac06b5812950cb933b5926cf5ebbc893096435. I will publish very soon a new version with this fix.
