### ISSUE TITLE
How do you extract all the images that were downloaded when saving a page?

### ISSUE THREAD

**Issue by tarantinosaur** [gildas-lormeau/SingleFile#458]
I'm sorry if it's not allowed to ask questions like this. So anyway, there's this website I use to read manga and I want to download all the images from a page but the problem is that not all images can be detected by any image downloader extension because they're inside this blob thing. I tried using singlefile to see if it could download the whole page and retain every image and it was able to. Now, how I do extract those images from the html file? Is there like a way to extract it as if it's a zip file?

**Comment by gildas-lormeau** [comment]
I would recommend you to use SingleFileZ instead, it produces a zip file.

See https://github.com/gildas-lormeau/SingleFileZ

**Comment by gildas-lormeau** [comment]
@tarantinosaur Did you find how to download the images eventually?

**Comment by tarantinosaur** [comment]
@gildas-lormeau Yeah, by downloading them manually lol. That site is very strict about their content so some of the images are embedded to a canvas element. I don't know how they do it but there's no url link when you check those canvas elements.

**Comment by gildas-lormeau** [comment]
@tarantinosaur Thank you for the feedback and sorry for the inconvenience. Actually, SingleFileZ would not have helped you unfortunately because it also embeds canvas images as data URI. It would need some additional work to transform them as separated images in the zip.

I'm closing the issue since you found a workaround.

**Comment by tarantinosaur** [comment]
> It would need some additional work to transform them as separated images in the zip.

Will you implement this in the future? Also, sorry for not closing this.

**Comment by gildas-lormeau** [comment]
I created an issue here https://github.com/gildas-lormeau/SingleFileZ/issues/59 for this feature. I cannot promise you it will be implemented soon but it's traced.

**Comment by tarantinosaur** [comment]
Hope you also add a way to name them numerically based on the order they appear on the page. That site also likes to randomize the name of the images.

**Comment by gildas-lormeau** [comment]
Actually, that's already something SingleFileZ does ;) The URL is saved as a comment for each entry in the zip file (there is a field "comment" in a zip entry of a zip file). The comment would be empty for an image saved from a canvas.

**Comment by tarantinosaur** [comment]
Okay, got it. Thanks!

**Comment by gildas-lormeau** [comment]
@tarantinosaur I just uploaded the version 0.5.71 of SingleFileZ that should fix this issue. It's available for download on the store of Mozilla and will be available on the store of Google in the coming days.

**Comment by tarantinosaur** [comment]
So, it worked. It was able to download those pesky canvas-embedded images but they're saved at the folder 'background-images'. So now the order is messed up. I tried it first on this comic which has all the chapters of a volume in one page, it has 192 images. The whole computer slowed down and Firefox was giving me "A script in the extension 'SingeFileZ' is causing Firefox to slow down". I had to force-close Firefox lol

**Comment by gildas-lormeau** [comment]
The implementation is not perfect indeed. Regarding the "'SingeFileZ' is causing Firefox to slow down" banner, try to wait some minutes, it just means that the extension is very busy.

**Comment by tarantinosaur** [comment]
I hope it gets better over time!!

**Comment by gildas-lormeau** [comment]
I fixed the ordering issue you were referring to in the version 0.5.72 I just published.

**Comment by tarantinosaur** [comment]
What if you put an option to put all images in one folder instead? Is that possible or will that ruin how your html is setup (? sorry Idk the term lol).

**Comment by gildas-lormeau** [comment]
Indeed, I was also thinking that the "background-images" was not very relevant for end-users. It's mostly a technical detail. The version 0.5.73 I just uploaded fixes that.

**Comment by tarantinosaur** [comment]
The order is still a mess. All canvas-embedded images are placed before the regular images.

**Comment by gildas-lormeau** [comment]
Indeed, images are still ordered by type first.
