### ISSUE TITLE
Migrating from Google Chrome to MS Edge

### ISSUE THREAD

**Issue by tmyflyte** [gildas-lormeau/SingleFile#459]
Hi, the extension works just fine in GC but I noticed that the auto-save feature isn't working properly in MSE. I tried resetting options, reinstalling the extensions but no luck :(

When I save manually it works fine, it's just my auto-save profiles that doesn't seem to be triggered

Can you help? Need more info?

**Comment by gildas-lormeau** [comment]
I just did a test and it worked fine for me on MS Edge 84.0.522.49. Did you enable the auto-save feature via the context menu?

**Comment by tmyflyte** [comment]
Oh there was that. Tks it's working now!

**Comment by gildas-lormeau** [comment]
Glad to hear it :)
