### ISSUE TITLE
OTS parsing error: invalid version tag

### ISSUE THREAD

**Issue by Lerie82** [gildas-lormeau/SingleFile#46]
while trying to capture https://lerie.us/

![screenshot 2018-07-04 at 9 29 51 am](https://user-images.githubusercontent.com/29735511/42287922-5883ca50-7f6d-11e8-87c0-7dea7799188f.png)

**Comment by gildas-lormeau** [comment]
This issue is due to the fact that the page embeds the following font https://lerie.us/assets/fonts/fontawesome-webfont.eot?v=4.7.0 which returns a 404. This a also bug on our end though since the extension is trying to inline the 404 HTML page instead of ignoring the error.

**Comment by gildas-lormeau** [comment]
This is fixed in 1.0.6. Thank you!
