### ISSUE TITLE
Flat variables on filename templates

### ISSUE THREAD

**Issue by mindgs** [gildas-lormeau/SingleFile#461]
When a variable such as {url-pathname} is used, and "Save pages in background" is enabled, then it will create subfolders according to the URL path, instead of adding the pathname to the saved file's name.

Although it is a handy feature for those who want subfolders, these should be two separate options, because there are instances where a user might prefer forward slashes to be converted to _ and therefore get a filename like "**gildas-lormeau_SingleFile_issues.html**" instead of "[...]**/gildas-lormeau/SingleFile/issues.html**".

Alternatively, and perhaps a simpler and more elegant way to solve this issue would be to add new variables (as is done on other extensions such as DownThemAll) returning a "flat" variant of the same string. Therefore, **{url-pathname-flat}** would return the first example given in the previous paragraph while **{url-pathname}** would return the second one, regardless of options. The same goes for every other variable that results in forward slashes, such as **{url-href}**.

**Comment by gildas-lormeau** [comment]
Thank you very much for the suggestion. I agree that this was an issue and it will be fixed in the next version I'll publish very soon. I decided to add the variable names you proposed, i.e. `{url-pathname-flat}` and `{url-href-flat}` (and `{url-referrer-flat}`).
