### ISSUE TITLE
SingleFile & SingleFileZ

### ISSUE THREAD

**Issue by labyrinth-to-solve** [gildas-lormeau/SingleFile#462]
I have discovered that SingleFileZ provides an easy way to retrieve individual components from the saved web page. SingleFile in turn has opportunities that are lacking in SingleFileZ. Is there a table comparing the different possibilities in SingleFile and SingleFileZ?

**Comment by labyrinth-to-solve** [comment]
Forget my question. The "File format comparison" table on the first page probably gives all the answers. The big difference between the exported settings.json files is a block named "test" which is probably not significant for the actual function of add-ons.

**Comment by gildas-lormeau** [comment]
The other big difference between the two extensions is that SingleFileZ does not have an annotation editor. I am however surprised by the presence of the "test" block in the settings file because neither extension uses such a property name.

**Comment by labyrinth-to-solve** [comment]
Give me a mail address and I will send you both files.

**Comment by gildas-lormeau** [comment]
You can attach files here. Zip them in a file and drag and drop the file where you're typing the text of the comment.

**Comment by labyrinth-to-solve** [comment]
[singlefile-settings.zip](https://github.com/gildas-lormeau/SingleFile/files/5030004/singlefile-settings.zip)

**Comment by gildas-lormeau** [comment]
Thank you, I confirm it's the name of a profile you created.

**Comment by labyrinth-to-solve** [comment]
I have to ask for apology - again. I completely forgot that I created that profile. Sorry!

**Comment by gildas-lormeau** [comment]
No problem ;)
