### ISSUE TITLE
"Save page with profile" - one-off saving of pages using the selected profile's settings

### ISSUE THREAD

**Issue by redactedscribe** [gildas-lormeau/SingleFile#464]
**Is your feature request related to a problem? Please describe.**
Switching the default profile (via context menu) to save a single page using different settings (for example, to include script resources) is a bit cumbersome as you have to then remember to switch the default profile back afterwards (to avoid mistakenly saving future pages with scripts too).

**Describe the solution you'd like**
`"Save page with profile" > {list of profiles…}`. This would allow for quick-and-easy saving of pages using different profiles (incl. scripts, incl. a/v and scripts, incl. videos only, etc). I haven't used the auto-settings feature, however I believe this is mainly for regularly visited pages, but in the case of a random site's page that one wishes to archive, a simple, one-off "save with profile" option (that doesn't affect the default profile) would be ideal. The downside to this approach is if you wish the profiles to only differ to a small degree (such as including scripts), then essentially you have to maintain two profile configurations (should you make changes to what you wish your "baseline" config to be). However, once set up, this would be the fastest way to quickly save a page.

An alternate solution would be to introduce an intermediary step after pressing save (whether by button or a new `"Save page with settings…"` menu entry) which would display the default profile's options (overlayed upon the webpage), and allow for a temporary change of settings that would only affect that particular save. I can see both suggested implementations being quite useful actually, but would be happy with either as they'd both make saving with custom resources more convenient.

**Additional context (optional)**
Hopefully this would make it into SingleFileZ too, as this is what I use.

Thanks!

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. I agree an entry in the context menu would make things easier for pages that you don't regularly save.

**Comment by gildas-lormeau** [comment]
It's implemented in the version 1.18.0 I just uploaded on the stores. It will be available for dowload in the coming days, after having been reviewed. It's already available in SingleFileZ (version 0.6.0) for Firefox.
