### ISSUE TITLE
Improve auto close on save usage

### ISSUE THREAD

**Issue by clemera** [gildas-lormeau/SingleFile#468]
Thank you for this great addon!

**Is your feature request related to a problem? Please describe.**
Usually I just want to stash tabs away to archive them but sometimes I want to "bookmark" multiple pages of a website. In these cases it would be nice to have quick way to do that without having to change the default setting (which is auto close on save for me).

**Describe the solution you'd like**
One great way I can think of would be to allow to Shift+click to save the page and keep the tab open. Shift+click would mean save the page and do the opposite of the default setting. This way people which like to default to no auto close could do it with Shift+click when they want it. If that sounds to complicated maybe having shift+click always do auto close would be an alternative. Then one would always have both options and the behaviour of shift+click wouldn't depend on the setting.

**Describe alternatives you've considered (optional)**
I can open new tabs before stashing the old ones away but that would be cumbersome.

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. I understand your issue. Unfortunately, it's technically impossible to detect  if the user is pressing the Shift key when he clicks on the SingleFile button.

**Comment by clemera** [comment]
I see, thanks. What about having a "Save page (don't close)" selectable from the right click context menu?

**Comment by gildas-lormeau** [comment]
I might have another idea. Do you confirm you enabled the option Misc. > save the page of a newly created bookmark in order to save the page you bookmark?

**Comment by clemera** [comment]
> Do you confirm you enabled the option Misc. > save the page of a newly created bookmark in order to save the page you bookmark?

No, I only use bookmarks for web applications where saving the page make no sense and I just want to save the link for revisit.

> Otherwise, the "Save with profile" feature introduced in the version 1.18.0 should solve your issue.

Nice! That works for me, thanks for your help!
