### ISSUE TITLE
Support Firefox

### ISSUE THREAD

**Issue by jrmuizel** [gildas-lormeau/SingleFile#47]
It would be nice to have this available as a Firefox add-on

**Comment by gildas-lormeau** [comment]
It is supported :). 

I'll upload it on the store when it will be a little bit more stable. You should be able to install it by downloading the zip of the project and load it via this page `about:debugging#addons`.

**Comment by gildas-lormeau** [comment]
The extension has been published in the Firefox Addons Store. You can install it from https://addons.mozilla.org/en-US/firefox/addon/single-file/.
