### ISSUE TITLE
Translation of extension hotkeys

### ISSUE THREAD

**Issue by solokot** [gildas-lormeau/SingleFile#472]
Hello!

I propose a small cosmetic improvement: use interface translation in the hotkey settings section of the extension.

![ext](https://user-images.githubusercontent.com/25316928/90306562-1f23db80-ded7-11ea-9c4e-18b84ebb586d.jpg)

**Comment by gildas-lormeau** [comment]
Indeed, it should be possible to support translated labels.

**Comment by gildas-lormeau** [comment]
That's done, feel free to contribute ;)
