### ISSUE TITLE
This site to be saved into html file in which some images will have their duplicates.

### ISSUE THREAD

**Issue by nomosaic** [gildas-lormeau/SingleFile#473]
https://antv-2018.alipay.com/zh-cn/vis/chart/funnel.html
![20200817131003](https://user-images.githubusercontent.com/14254798/90359258-00664600-e08b-11ea-95c0-5a59eb1f812a.jpg)

**Comment by gildas-lormeau** [comment]
I guess you disabled `Other resources > remove scripts`. If this is the case, please enable `Misc. > save raw page`.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because I indicated how to fix it. Feel free to comment or reopen it if necessary.
