### ISSUE TITLE
CLI: pass additional options to back-ends

### ISSUE THREAD

**Issue by ylxdzsw** [gildas-lormeau/SingleFile#476]
**Is your feature request related to a problem? Please describe.**

I would like to use a socks5 proxy, which requires passing "--proxy-server=socks5://" to chromium.

**Describe the solution you'd like**

I'd like to set additional options for the backend. For example, all options after a `-` are passed to chromium.

**Describe alternatives you've considered (optional)**

Alternatively, just add an option for proxy. This will solve my particular problem. We can also unify the interface for setting proxy of different backends in this way.

**Comment by gildas-lormeau** [comment]
That should be already possible with by using something similar to this `--browser-args=["--proxy-server=socks5://"]`.

**Comment by ylxdzsw** [comment]
Oops, I did notice it. Yes, that option is what I want. Thank you.
