### ISSUE TITLE
Microsoft new edge: filename is a UUID instead of page title. 

### ISSUE THREAD

**Issue by whudwl** [gildas-lormeau/SingleFile#477]
**Describe the bug**
When using this add-on to save a page on Microsoft Edge browser, the saved file has a UUID as file name instead of the page title as filename.  

For example, I just saved google.com and the file I got was 38626dbe-f478-4ad6-816a-336a11d96359.html  

**To Reproduce**
1. Install Microsoft New Edge Browser (chromium based)
2. go to any page.  
3. save the page with this add-on (singlefile) 
4. check if the saved file is named after the page title.  

**Additional context**
I believe it only started happening a few days ago. Perhaps some Edge update is responsible for this.

**Comment by gildas-lormeau** [comment]
This is a known issue in Chromium-based browsers, see https://github.com/gildas-lormeau/SingleFile#known-issues. Nobody cares about and Google closed the issue as "won't fix". It's probably due to corrupted profile data. Let's hope Microsoft will fix it...

**Comment by whudwl** [comment]
> This is a known issue in Chromium-based browsers, see https://github.com/gildas-lormeau/SingleFile#known-issues. Nobody cares about it and Google closed the issue as "won't fix". It's probably due to corrupted profile data. Let's hope Microsoft will fix it...

Thank you.

**Comment by Unknow0059** [comment]
Wow. This is a Chromium issue? Shit...

**Comment by sergeevabc** [comment]
Year 2024, Edge 109. SingleFile worked correctly on my end for a week or so, then UUIDs instead of filenames followed. I tried to reset extension settings, but it did not help. If the extension had worked earlier, what might have happened?

**Comment by gildas-lormeau** [comment]
@sergeevabc I understand, it's happened to me in the past. The most reliable solution is to switch to Firefox. Otherwise, it's possible that reinstalling Edge will fix the problem, but I have some doubts.
