### ISSUE TITLE
parent webpage lower level tree links

### ISSUE THREAD

**Issue by gin9980** [gildas-lormeau/SingleFile#478]
Is there anyway to click a link on your offline downloaded webpage and have its links redirect to your other downloaded webpages which is 1 level down instead of redirecting to the online link?

**Comment by gin9980** [comment]
> 
> 
> Install it by following the procedure described here: https://github.com/gildas-lormeau/SingleFile/tree/master/cli#install. Update it if you already installed it.
> 
> An run the following command:
> `single-file https://www.example.com --crawl-links=true --crawl-inner-links-only=false --crawl-max-depth=1 --crawl-replace-urls=true`

not sure how to follow instructions, does the "cd SingleFile-master" and "cd cli" mean to just do "cd C:\Users\mdb\Downloads\SingleFile-master" then "npm install" in that directory? I already have node.js installed and added to the PATH but windows doesn't  recongized as a command.

**Comment by gildas-lormeau** [comment]
> not sure how to follow instructions, does the "cd SingleFile-master" and "cd cli" mean to just do "cd C:\Users\mbd\Downloads\SingleFile-master\cli" then "npm install" in that directory?
Yes, I just made the instructions compatible with Windows and Linux by avoiding using any directory separator.

> I already have node.js installed and added to the PATH but windows doesn't recongized as a command.
That's weird. If you type `node --version` on the DOS command line interface, it displays that error?

**Comment by gin9980** [comment]
> 
> 
> > not sure how to follow instructions, does the "cd SingleFile-master" and "cd cli" mean to just do "cd C:\Users\mbd\Downloads\SingleFile-master\cli" then "npm install" in that directory?
> 
> Yes, I just made the instructions compatible with Windows and Linux by avoiding using any directory separator.
> 
> > I already have node.js installed and added to the PATH but windows doesn't recongized as a command.
> 
> That's weird. If you type `node --version` on the DOS command line interface, it displays that error?
> 
> BTW, you should not install apps in your Downloads folder, this can be dangerous sometimes, cf. for example https://glyph.twistedmatrix.com/2020/08/never-run-python-in-your-downloads-folder.html,


the "npm install" into the cli folder says it doesn't contain a package.json file. Had to CD into the nodejs folder since the PATH thing in windows didn't work.

**Comment by gildas-lormeau** [comment]
Sorry for that, Did you try to run `npm install` in the SingleFile directory? I updated the instructions in the README file.

**Comment by gin9980** [comment]
> 
> 
> Sorry for that, did you try to run `npm install` in the SingleFile directory? I updated the instructions in the README file.

It works now, tried "single-file https://www.example.com --browser-executable-path=C:\Program Files\Mozilla Firefox\firefox.exe --crawl-links=true --crawl-inner-links-only=false --crawl-max-depth=1 --crawl-replace-urls=true" 
I've set the browser path option but says failed to launch browser process

**Comment by gildas-lormeau** [comment]
try `--browser-executable-path="C:\Program Files\Mozilla Firefox\firefox.exe"` (with quotes).

**Comment by gin9980** [comment]
> 
> 
> try `--browser-executable-path="C:\Program Files\Mozilla Firefox\firefox.exe"` (with quotes).

tried this but nothing happens now, no messages show up and seems to be stuck.
"single-file https://walkingdead.fandom.com/wiki/Comic_Series_Characters --browser-executable-path="C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --crawl-links=true --crawl-inner-links-only=false --crawl-max-depth=1 --crawl-replace-urls=true"

But if the website is changed to "https://en.wikipedia.org/wiki/Main_Page" it works and grabs the html pages when I look at the nodejs folder. 
Does the CLI have limitation on the websites it can grab? It works with the extension

**Comment by gildas-lormeau** [comment]
For Firefox, do you confirm you have downloaded `geckodriver.exe`?

I'll see what's wrong with https://walkingdead.fandom.com/wiki/Comic_Series_Characters.

**Comment by gin9980** [comment]
> 
> 
> For Firefox, do you confirm you have downloaded `geckodriver.exe`?
> 
> I'll see what's wrong with https://walkingdead.fandom.com/wiki/Comic_Series_Characters.

I put the geckodriver.exe in "C:\Program Files\nodejs\node_modules\single-file\cli\". But used google chrome for the CLI since I use Firefox and it seems the CLI need the browser to be closed.

**Comment by gildas-lormeau** [comment]
I did a test with https://walkingdead.fandom.com/wiki/Comic_Series_Characters with Chrome and it seems to run fine. There were more than 300 pages to capture though so I could not test if ` --crawl-replace-urls=true` works as expected. Could you add the flag `--browser-debug=true`? It will allow you to see if SingleFile can launch the browser and capture some pages.

**Comment by gin9980** [comment]
> 
> 
> I did a test with https://walkingdead.fandom.com/wiki/Comic_Series_Characters with Chrome and it seems to run fine. There were more than 300 pages to capture though so I could not test if ` --crawl-replace-urls=true` works as expected. Could you add the flag `--browser-debug=true`? It will allow you to see if SingleFile can launch the browser and capture some pages.

it works with the "--browser-debug=true" added but now it shows the "This Site Uses Cookies" popup at the bottom and scroll disabled with no way of removing it.

**Comment by gildas-lormeau** [comment]
Create a file named `accept-cookies.js` in the cli folder and copy the content below into the file
```
(() => {
	addEventListener("load", acceptCookies, false);

	function acceptCookies() {
		const okButton = document.querySelector("[data-tracking-opt-in-accept]");
		if (okButton) {
			okButton.click();
		} else {
			setTimeout(acceptCookies, 500);
		}
	}
})();
```
Then run single-file with the flag `--browser-scripts=./accept-cookies.js`. Note that this script is not generic but quite specific to this website.

**Comment by gin9980** [comment]
> 
> 
> Create a file named `accept-cookies.js` in the `cli` folder and copy the content below into the file.
> 
> ```
> (() => {
> 	addEventListener("load", acceptCookies, false);
> 
> 	function acceptCookies() {
> 		const okButton = document.querySelector("[data-tracking-opt-in-accept]");
> 		if (okButton) {
> 			okButton.click();
> 		} else {
> 			setTimeout(acceptCookies, 500);
> 		}
> 	}
> })();
> ```
> 
> Then, run `single-file` with the flag `--browser-scripts=./accept-cookies.js`. Note that this script is not generic but quite specific to this website.

left the CLI download to run but the links aren't replaced. Directed to the online links instead. Also is there a way to make it so the CLI browser is somehow minimized?

**Comment by gildas-lormeau** [comment]
> left the CLI download to run but the links aren't replaced. Directed to the online links instead. Also is there a way to make it so the CLI browser is somehow minimized?

Thank you for the feedback. I guess Chrome or puppeteer crashed. I need to code something in order to be able to continue a session when it crashes. When you remove `--browser-debug=true`, it doesn't work at all?

**Comment by gildas-lormeau** [comment]
And that's done, if you update the code of SingleFile, you will be able to use the new option `--crawl-sync-session` to save the state of the crawling session and restart where it stopped/crashed. You have to give the name of a file, e.g. `--crawl-sync-session=session-walkingdead.fandom.json`.

**Comment by gin9980** [comment]
> 
> 
> > left the CLI download to run but the links aren't replaced. Directed to the online links instead. Also is there a way to make it so the CLI browser is somehow minimized?
> 
> Thank you for the feedback. I guess Chrome or puppeteer crashed. I need to code something in order to be able to continue a session when it crashes. When you remove `--browser-debug=true`, it doesn't work at all?

when not using --browser-debug=true it doesn't work for some reason

**Comment by gildas-lormeau** [comment]
I think I should be able to add an option to start Chrome minimized, see https://github.com/puppeteer/puppeteer/issues/4513.

**Comment by gin9980** [comment]
> 
> 
> I think I should be able to add an option to start Chrome minimized, see [puppeteer/puppeteer#4513](https://github.com/puppeteer/puppeteer/issues/4513).

thanks, I'll wait for the chrome minimized option then try to see if it works then with the "--crawl-sync-session" option

**Comment by gildas-lormeau** [comment]
Can't you minimize the browser manually meanwhile?

**Comment by gin9980** [comment]
> 
> 
> Can't you minimize the browser manually meanwhile?

The google chrome browser pops up front everytime it opens the new tabs

**Comment by gildas-lormeau** [comment]
I updated the code, the new option `--browser-start-minimized` should allow you to start the browser minimized.

**Comment by gin9980** [comment]
> 
> 
> I updated the code, the new option `--browser-start-minimized` should allow you to start the browser minimized.

works, but is there an option to blacklist the ads that get downloaded with the character wiki page?

**Comment by gildas-lormeau** [comment]
I guess the option `--remove-frames` should do the job.

**Comment by gildas-lormeau** [comment]
@gin9980 any news?

**Comment by gin9980** [comment]
> 
> 
> I guess the option `--remove-frames=true` should do the job.

the --remove-frames=true doesn't seem to remove the ads on the character pages. Is there maybe some way to make ad blocker work with the downloader to remove it?

**Comment by gildas-lormeau** [comment]
You can unzip the code of uBlock Origin (see attached zip file) somewhere on your disk and run SingleFile with the option `--browser-args="["--load-extension=C:\\path\\to\\extension\\cjpalhdlnbpafiamejdnhcphjbkeiagm","--disable-extensions-except=C:\\path\\to\\extension\\cjpalhdlnbpafiamejdnhcphjbkeiagm"]"`. Replace `path\\to\\extension` with the path where you unzipped the file.

[cjpalhdlnbpafiamejdnhcphjbkeiagm.zip](https://github.com/gildas-lormeau/SingleFile/files/5151350/cjpalhdlnbpafiamejdnhcphjbkeiagm.zip)

**Comment by gin9980** [comment]
> 
> 
> You can unzip the code of uBlock Origin (see attached zip file) somewhere on your disk and run SingleFile with the option `--browser-args="["--load-extension=C:\\path\\to\\extension\\cjpalhdlnbpafiamejdnhcphjbkeiagm","--disable-extensions-except=C:\\path\\to\\extension\\cjpalhdlnbpafiamejdnhcphjbkeiagm"]"`. Replace `C:\\path\\to\\extension\\` with the path where you unzipped the file. Make sure you use `\\` and not `\` to separate the folders.
> 
> [cjpalhdlnbpafiamejdnhcphjbkeiagm.zip](https://github.com/gildas-lormeau/SingleFile/files/5151350/cjpalhdlnbpafiamejdnhcphjbkeiagm.zip)
> 
> FYI, I used CRX viewer to get the file, see https://robwu.nl/crxviewer/.

get an error saying "(node:7628) unhandledpromiserejection warning" and "(node:7628) deprecationwarning" when used the option
--browser-args="["--load-extension=C:\\cjpalhdlnbpafiamejdnhcphjbkeiagm","--disable-extensions-except=C:\\cjpalhdlnbpafiamejdnhcphjbkeiagm"]"

**Comment by gildas-lormeau** [comment]
Don't you have more information in the error message? I tested this option and it worked fine for me.

**Comment by gin9980** [comment]
> 
> 
> Don't you have more information in the error message? I tested this option and it worked fine for me.

(node:3188) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected number in JSON at position 2
    at JSON.parse (<anonymous>)
    at getBrowserOptions (C:\SingleFile-master\cli\back-ends\puppeteer.js:63:51)
    at Object.exports.initialize (C:\SingleFile-master\cli\back-ends\puppeteer.js:36:35)
    at initialize (C:\SingleFile-master\cli\single-file-cli-api.js:46:16)
    at run (C:\SingleFile-master\cli\single-file:33:59)
    at Object.<anonymous> (C:\SingleFile-master\cli\single-file:30:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
(node:5584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.or/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by gildas-lormeau** [comment]
My bad, try this:
`--browser-args="[\"--load-extension=C:\\\\cjpalhdlnbpafiamejdnhcphjbkeiagm\",\"--disable-extensions-except=C:\\\\cjpalhdlnbpafiamejdnhcphjbkeiagm\"]"`

**Comment by gin9980** [comment]
> 
> 
> My bad, try this:
> `--browser-args="[\"--load-extension=C:\\\\cjpalhdlnbpafiamejdnhcphjbkeiagm\",\"--disable-extensions-except=C:\\\\cjpalhdlnbpafiamejdnhcphjbkeiagm\"]"`

thanks, it works now

**Comment by gildas-lormeau** [comment]
Thank you, please let me know if you can save all the pages and if the links are replaced.

**Comment by gin9980** [comment]
> 
> 
> Thank you, please let me know if you can save all the pages and if the links are replaced.

yes it works, tested it out but sometimes I find that it doesn't fetch the long pages at the bottom of the page icons pictures, ends up missing half of the page. Probably due to not loading long enough?

**Comment by gildas-lormeau** [comment]
Thank you for the feedback. The issue you're describing could be related to the loading of deferred images. If you pass the option `load-deferred-images-max-idle-time=5000`, do you see any difference?

**Comment by gin9980** [comment]
> 
> 
> Thank you for the feedback. The issue you're describing could be related to the loading of deferred images. If you pass the option `load-deferred-images-max-idle-time=5000`, do you see any difference?

yup, solved the problem, fetches the images properly now
