### ISSUE TITLE
[Feature request] Ability to embed items manually

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [gildas-lormeau/SingleFile#48]
The [Save Page WE](https://addons.mozilla.org/firefox/addon/save-page-we/) extension has more flexible options to choose which items can be saved into single HTML, such as CSS images, web fonts, etc. If you get this extension, then you will see it when you open their options at add-on manager.
![1](https://i.imgur.com/HOEgK3M.png)
![2](https://i.imgur.com/XWA6fTK.png)
It would be nice if SingleFile can implement similar functionality.

**Comment by gildas-lormeau** [comment]
Why using SingleFile then? From my point of view, there are too much options in these screenshots. What options would you really like to have in SingleFile? Do you really need all of them?

**Comment by franzalex** [comment]
Much as I am in favour of customization, I have to agree with @gildas-lormeau on this.

I have been using the Save Page WE add-on and I find a lot of the settings to be superfluous. Whenever the average person is saving a web page, he/she often wants the page as is displayed, so a lot of the settings available are often left to their defaults!
