### ISSUE TITLE
Default filename template produces mismatched time/date

### ISSUE THREAD

**Issue by Illiou** [gildas-lormeau/SingleFile#480]
It seems because the default filename template uses {date-iso} together with {time-locale} it will produce files with the local time but the UTC date.
Example: I just saved a website at 1 am local time on the 25. of August and the file name showed it to be 1 am 24. of August.

I think the default should have matching date and time.

**Comment by gildas-lormeau** [comment]
I'm on UTC+2 and I cannot reproduce your issue. Here are two files I saved at 11:35 PM and 0:35 AM. Time/date are OK.

[files.zip](https://github.com/gildas-lormeau/SingleFile/files/5123756/files.zip)

**Comment by Illiou** [comment]
But you did reproduce it. The 0:35 pm should have 26. August as date. In fact, if you click the (i) on the saved website it will show you the correct date.

**Comment by gildas-lormeau** [comment]
Indeed! I was checking the infobar... I will fix that.
