### ISSUE TITLE
SingleFile not yet available in new Firefox android addon ?

### ISSUE THREAD

**Issue by doplu** [gildas-lormeau/SingleFile#481]
Hello,
Do you think SingleFile will be available in the next version of Firefox on Android in the near future ?
Since the last Android Firefox update, I am currently blocked as I can't add SingleFile addon inside it !
By luck do you know an android browser which could run Singlefile (to my knowledge Chomuim browsers have no addon in their Android version) ?
Many thanks in advance ;)

**Comment by doplu** [comment]
I'm answering myself : I have found one android browser based on Chromium that have addon supoort : "Kiwi Browser". And it works with Singlefile (go to extensions : Google Chrome Store / SingleFile). ;)

**Comment by gildas-lormeau** [comment]
Hi,

I'm glad you found how to run SingleFile on Android. 

Mozilla contacts developers when they plan to make an extension available on the new Firefox for Android. So far, I haven't been contacted by Mozilla.

I did some tests and I confirm that with the "save pages in background" option disabled, SingleFile is compatible with the newest version of Firefox for Android. Let's hope it will be available again someday.

**Comment by gildas-lormeau** [comment]
Later this month, it should be possible to use SingleFile in Firefox Nightly, see https://blog.mozilla.org/addons/2020/09/02/update-on-extension-support-in-the-new-firefox-for-android/ and https://github.com/mozilla-mobile/fenix/issues/14034.

**Comment by gildas-lormeau** [comment]
You can now install SingleFile on Firefox Nightly by following this procedure: https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/.

As I write this message,  you **must** also disable the setting `Misc. > save pages in background` in the options of SingleFile to make it work. It means the auto-save won't work. Also, a minor detail, you cannot open saved pages in Firefox on Android currently... Another browser should do the job though.

**Comment by KrasnayaPloshchad** [comment]
> Another browser should do the job though.
X-plore can open saved pages directly, even though it’s not a web browser.

**Comment by gildas-lormeau** [comment]
I debugged the save issue in the annotation editor. Unfortunately, there's nothing I can do today to circumvent it. It's probably related to the fact that the download API does not work as expected, hence the need of disabling the setting `Misc. > save pages in background`. I guess this bug will be fixed in a future version of Firefox for Android.

**Comment by gildas-lormeau** [comment]
You can follow this procedure to open files in Firefox on Android: https://github.com/mozilla-mobile/fenix/issues/7546#issuecomment-627091018.

**Comment by gildas-lormeau** [comment]
I made a change to disable by default the setting `Misc. > save pages in background` when SingleFile is installed on Firefox for Android. That's why I'm closing this issue.

**Comment by gildas-lormeau** [comment]
I stumbled upon this [issue](https://github.com/mozilla-mobile/fenix/issues/4049) which makes me think that SingleFile will never be officially supported on Firefox for Android.

**Comment by gildas-lormeau** [comment]
Actually there's some hope! This issue is not closed: https://github.com/mozilla-mobile/fenix/issues/7546. There are also maybe some interesting tips to circumvent this issue.

**Comment by KrasnayaPloshchad** [comment]
I’ve also found [CHM Reader X](https://play.google.com/store/apps/details?id=com.pdagate.chmreader) is also a good HTML reader.
