### ISSUE TITLE
"Remove HTML imports" option is removing <input> tags that are hidden

### ISSUE THREAD

**Issue by neviln** [gildas-lormeau/SingleFile#484]
I was trying to save a page that has some simple unit conversions on it, only to keep getting script errors when using the saved page. After spending some time digging into it, I found that SingleFile was removing all the hidden <input> tags that had values associated with them, even though (HTML Content > Remove Hidden Elements) was unchecked.

So then I kept unchecking options in the settings and re-saving the pages until I found what I believe is the culprit. It seems that leaving (HTML Content > Compress HTML Content) checked was causing the issue. Naturally, I would expect (HTML Content > Remove Hidden Elements) to erase these hidden tags.

I'm using Chrome Version 84.0.4147.135 (Official Build) (64-bit) on Windows 8.
The website I found this issue on is: http://www.easysurf.cc/cnver7.htm
For example, if you scroll down the page to the form for "Convert mils to inches" and inspect element, you'll see the 2 hidden <input> tags. They aren't saved if (HTML Content > Compress HTML Content) is checked in the options.

**Comment by gildas-lormeau** [comment]
Thank you for having reported this issue. I agree with you the concerned option should be HTML Content > Remove Hidden Elements. The fix will be available in the next version.
