### ISSUE TITLE
This type of hidden element not hidden? 

### ISSUE THREAD

**Issue by huhiha** [gildas-lormeau/SingleFile#486]
**Describe the bug**
I've been using SingleFile since at most verion 1.13.31 up till now. But the **remove hidden element** option seems to be not working on this page([https://linuxize.com/post/bash-heredoc/](https://linuxize.com/post/bash-heredoc/)). 

The adblocker is working, but the saved page has unexpected white space(see the screenshot below). 

Maybe this is a type of hidden element that SingleFile currently doesn't support? Or is it a bug of the new version (1.18.8) updated recently(7 Sep)?

**To Reproduce**

**Expected behavior**

**Screenshots**
![Image of Yaktocat](https://i.postimg.cc/QMyF2jNs/1.png)

**Environment**
 - OS: [e.g. Win10 Pro, Ubuntu 18.04.1, Android 7.1.2]
 - Browser: [e.g. Chrome, Firefox]
 - Version: [e.g. 64]

**Additional context**

**Comment by gildas-lormeau** [comment]
Thank you for having reported this issue. 

I was able to reproduce it. This is not a regression but a particular case that was not handled properly by SingleFile.  The fix will be available in the next version soon.
