### ISSUE TITLE
When attempting to save some pages, all that is saved is a blank page.

### ISSUE THREAD

**Issue by mtnmarty** [gildas-lormeau/SingleFile#488]
When attempting to save some pages, all that is saved is a blank page. I have been using SingleFile for about 1 year and never had a problem, not one! A great extension up until now. I hope what I have provided can somehow help.

**Steps to reproduce the behavior:
1. Go to https://abc7news.com/weather/wildfire-smoke-bay-area-sees-historic-string-of-spare-the-air-days/6418331/
2. save page with SingleFile
3. save page with WE

**Expected behavior**
open SingleFile html page all that will be visible is a blank page
WE properly saves it as SingleFile used to

**Environment**
 - macOS Catalina 10.15.6
 - Firefox 80.0.1 (64-bit)

**Screenshots**
I tried to attach the html pages produced by SinglFile and WE but this report will not allow that file type so for what it's worth I screenshot the top portion of the html pages produced by both. Yeah I know not great, but at least you can see the results I was getting.

![saved with SingleFile](https://user-images.githubusercontent.com/71133081/92926797-70998a80-f3f1-11ea-9eda-7a55b8f4b809.jpg)

![saved with WE](https://user-images.githubusercontent.com/71133081/92926840-81e29700-f3f1-11ea-8f57-92a609b8e789.jpg)

**Additional context**

**Comment by gildas-lormeau** [comment]
Thank you for reporting the issue. I was not able to reproduce it in Firefox (on Windows). On my end, the page is saved properly. I attached it to this issue (you have to zip the page to be able to attach it). Did you change any setting in SingleFile?

[Wildfire smoke_ Bay Area sees longest stretch of Spare the Air days in region's history - ABC7 San Francisco (9_11_2020 4_20_49 PM).zip](https://github.com/gildas-lormeau/SingleFile/files/5209593/Wildfire.smoke_.Bay.Area.sees.longest.stretch.of.Spare.the.Air.days.in.region.s.history.-.ABC7.San.Francisco.9_11_2020.4_20_49.PM.zip)

**Comment by gildas-lormeau** [comment]
@mtnmarty any news?

**Comment by mtnmarty** [comment]
After resetting the SingleFile extension everything works well again, and I uninstalled WE.

Thank you!

On Sep 19, 2020, at 3:41 PM, Gildas <notifications@github.com> wrote:


@mtnmarty <https://github.com/mtnmarty> any news?

**Comment by gildas-lormeau** [comment]
That was a weird issue. Feel free to reopen it if necessary.
