### ISSUE TITLE
[Feature request] Saving from Android

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [gildas-lormeau/SingleFile#49]
I have installed SingleFile in Firefox for Android just now, but it doesn't works at all when I press _Save Page_ from the menu. It would be nice if this addon allowing save single HTML from Firefox for Android.

**Comment by gildas-lormeau** [comment]
I confirm the issue. I was not able to debug the extension on Android. I'll retry later.

**Comment by gildas-lormeau** [comment]
Fixed in version 1.2.14
