### ISSUE TITLE
NPM deprecated packages

### ISSUE THREAD

**Issue by briansantich** [gildas-lormeau/SingleFile#491]
Apologies if this has already been brought up, but a quick search through previous issues (opened and closed) did not show anything related. Installing single-file using docker revealed warnings about deprecated NPM packages. The docker seems to work ok still, but it seems the recommendation is to move away from these packages: request, request-promise-native, har-validator.

Below is the warning I received, and it follows from the packages.json file.

```
Cloning into 'SingleFile'...
npm WARN deprecated request-promise-native@1.0.8: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN single-file@0.1.13 No repository field.
```

**Comment by gildas-lormeau** [comment]
Thank you for having reported the issue. I remove the dependency to `request-promise-native` in SingleFile. Note that you might still see these warnings but they come from jsdom (https://github.com/jsdom/jsdom) which can be used as an alternative to Chrome.
