### ISSUE TITLE
Cannot find module 'file-url'

### ISSUE THREAD

**Issue by Unknow0059** [gildas-lormeau/SingleFile#492]
**Describe the bug**
When I run `single-file` I get this error:

```
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'file-url'
Require stack:
- G:\Programming\Scripts\aliases\SingleFile\cli\single-file
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1025:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (G:\Programming\Scripts\aliases\SingleFile\cli\single-file:28:17)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1137:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:985:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:878:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'G:\\Programming\\Scripts\\aliases\\SingleFile\\cli\\single-file'←[39m ]
}
```

**To Reproduce**
1. Open cmd
2. Run `single-file` command

**Expected behavior**
For an error not to be thrown.

**Environment**
 - OS:  Windows 10 Pro 2004 10.0.19041.508 64-bit

**Additional context**
This morning I updated from Windows 1909 to 2004 and before the update I had no issues running `single-file`.
I tried reinstalling NodeJS to no avail.

**Comment by gildas-lormeau** [comment]
Did you run `npm install`?

**Comment by Unknow0059** [comment]
Yes, I had run it in my node install directory. If I run it again it'll tell me it's up to date.

If I run it in the single-file directory, I'll get the following error:
```
npm WARN saveError ENOENT: no such file or directory, open 'g:\Programming\Scripts\aliases\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'g:\Programming\Scripts\aliases\package.json'
npm WARN aliases No description
npm WARN aliases No repository field.
npm WARN aliases No README data
npm WARN aliases No license field.

up to date in 1.285s
found 0 vulnerabilities
```

**Comment by gildas-lormeau** [comment]
That's weird. Is `g:\Programming\Scripts\aliases` the SingleFile directory? If not, do you confirm a `package.json` file is present in the folder of SingleFile?

**Comment by Unknow0059** [comment]
There is a "package-lock.json" in that directory. There also is one in the directory of SingleFile.

**Comment by gildas-lormeau** [comment]
Please delete the `package-lock.json` file and the `node_modules` folder in `g:\Programming\Scripts\aliases`. Go into the folder of SingleFile, delete the `node_modules` folder and run `npm install`. It should reset everything.

**Comment by Unknow0059** [comment]
There was no node_modules folder in `g:\Programming\Scripts\aliases` and none in SingleFile's folder either, so I just deleted package-lock.json from the former, and ran `npm install` on the later.
I got this error:
```
G:\Programming\Scripts\aliases\SingleFile>npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! Unexpected end of JSON input while parsing near '...c1172iQe\nyGdKAuaN0OU'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aliso\AppData\Roaming\npm-cache\_logs\2020-09-24T03_10_46_292Z-debug.log
```
Log:
[2020-09-24T03_10_46_292Z-debug.log](https://github.com/gildas-lormeau/SingleFile/files/5273212/2020-09-24T03_10_46_292Z-debug.log)

**Comment by gildas-lormeau** [comment]
Open a shell as admin, run `npm cache clean --force`, close the shell. Open a shell (not admin) and run `npm install` again in the SingleFile folder.

**Comment by Unknow0059** [comment]
`npm install` worked fine this time.
But when I try to run `single-file` I get this:
`Failed to launch the browser process! spawn chrome ENOENT`
My Node.js version is v12.18.4 and my npm version is 6.14.6.
In the [troubleshooting.md](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md) file it's described that this mostly happens because of a bug from v14, but I'm not in v14, so upgrading wouldn't fix the bug I don't have.
But I'll do that anyway.
Ok, so I updated to node v14.12.0 and npm 6.14.8. The error persists.

**Comment by gildas-lormeau** [comment]
Did you try to specify the path to the executable of Chrome by using `--browser-executable-path`?

**Comment by Unknow0059** [comment]
That fixed this error.

Can I set this somewhere or do I really have to set it every time I want to use single-file?

**Comment by gildas-lormeau** [comment]
@Unknow0059 Thank you for the feedback, I'll try to implement something based on a config file I think
