### ISSUE TITLE
A useful feature suggestion to customize  <title> of HTML

### ISSUE THREAD

**Issue by dnknn** [gildas-lormeau/SingleFile#493]
![209_23022004](https://user-images.githubusercontent.com/10995302/93921620-5fcb0c00-fd43-11ea-891d-708df551ff18.png)

`<title>` of HTML is the title displayed on the browser tab , Many times  want to customize it.

- ## 💥 Current issue: Cannot modify the default `<title>` of HTML

- ## ❥ Expected behavior: Can do it.

- ## ❓ How to achieve: 

Open a prompt dialog to edit `<title>` of HTML

**Comment by gildas-lormeau** [comment]
test

**Comment by gildas-lormeau** [comment]
Thank you for the feature suggestion!

I think this could be "easily" implemented with a userscript interacting with SingleFile (see https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved).

Here is below the procedure to follow in 10 simple steps:

1. Export your settings from the options page of SingleFile by clicking on "Export"

![image](https://user-images.githubusercontent.com/396787/93933394-e53dc480-fd21-11ea-93c0-e15db9d3c083.png)

2. Edit the downloaded file in a text editor and replace `"userScriptEnabled": false` with `"userScriptEnabled": true`

![image](https://user-images.githubusercontent.com/396787/93933512-13bb9f80-fd22-11ea-8321-fcb1c621e310.png)

![image](https://user-images.githubusercontent.com/396787/93933553-20d88e80-fd22-11ea-862c-112c795c95bd.png)

3. Save the file and import it by clicking on "Import" in the options page of SingleFile

![image](https://user-images.githubusercontent.com/396787/93933684-49608880-fd22-11ea-8215-06ff28ce5d6c.png)

4. Choose and install an extension like Greasemonkey, Violentmonkey etc.. Greasemonkey is available here on Firefox: https://addons.mozilla.org/fr/firefox/addon/greasemonkey

5. Install the extension

![image](https://user-images.githubusercontent.com/396787/93933263-ad368180-fd21-11ea-99b6-650588397c23.png)

6. Click on the button of the extension

![image](https://user-images.githubusercontent.com/396787/93933784-7614a000-fd22-11ea-8724-7226fd6c8e2b.png)

7. Select "New user script..."

![image](https://user-images.githubusercontent.com/396787/93933844-8c226080-fd22-11ea-8f00-0e2e2c49b914.png)

8. This opens a new tab. Remove the existing content of the script

![image](https://user-images.githubusercontent.com/396787/93933959-bb38d200-fd22-11ea-9ad2-d597d12dbf38.png)

9. Replace it with the script below

```
// ==UserScript==
// @name     [SingleFile] Display prompt to enter the title
// @version  1
// @grant    none
// ==/UserScript==

{

    let title;

    dispatchEvent(new CustomEvent("single-file-user-script-init"));

    addEventListener("single-file-on-before-capture-request", async event => {
        title = document.title;
        const newTitle = prompt("Enter a title", title);
        if (newTitle != null) {
            document.title = newTitle;
        }
    });

    addEventListener("single-file-on-after-capture-request", () => {
        if (title != null) {
            document.title = title;
        }        
    });

}
```

![image](https://user-images.githubusercontent.com/396787/93934069-dd325480-fd22-11ea-956f-647067cce992.png)

![image](https://user-images.githubusercontent.com/396787/93934033-d4418300-fd22-11ea-8583-3e49f5c8cfb8.png)

10. Press Ctrl-S to save the changes and close the tab.

Et voilà ! From now on, when you will save a page with SingleFile, a prompt should ask you to edit the title of the page.

![image](https://user-images.githubusercontent.com/396787/93934749-e7a11e00-fd23-11ea-971b-134c62a39574.png)

**Comment by dnknn** [comment]
Thank you very much for your enthusiastic reply, 
can it be used in Chrome for 🐵Tampermonkey ? I have never used 🦊Firefox

**Comment by gildas-lormeau** [comment]
Sure!

**Comment by dnknn** [comment]
> Sure!

That's great!

**Comment by gildas-lormeau** [comment]
It should be straightforward to transpose these instructions for Chrome/TamperMonkey. Let me know if you have any issue.

**Comment by dnknn** [comment]
> It should be straightforward to transpose these instructions for Chrome/TamperMonkey. Let me know if you have any issue.

Okay, Thanks♪(･ω･)ﾉ !!   let me close this issue first.

**Comment by dnknn** [comment]
> 1. Edit the downloaded file in a text editor and replace `"userScriptEnabled": false` with `"userScriptEnabled": true`

I want to ask you,  There are 2 found  `"userScriptEnabled": false`
![209_23062025](https://user-images.githubusercontent.com/10995302/93943340-e7754280-fd64-11ea-88e8-0b8d3022e495.png)

Should I replace both of them? Or replace one of them?

**Comment by gildas-lormeau** [comment]
It means you have 2 profiles. It's up to you to decide if you want to have this feature on the profiles or not.

**Comment by dnknn** [comment]
> It means you have 2 profiles. It's up to you to decide if you want to have this feature on the 2 profiles or just one of them.

Okay, I totally understand it. I tried it with Tampermonkey just now, and it works perfectly, great!
thank you very much !!!

**Comment by gildas-lormeau** [comment]
You're welcome!

**Comment by dnknn** [comment]
> You're welcome!

Without your enthusiastic and rich illustrations, I may not be able to operate.
Thanks again ~!  sorry for my English.🤦🙈

**Comment by gildas-lormeau** [comment]
I'm glad to hear that there are enough arrows! No problem for the English, you are clear to me. I'm not a native speaker anyway ;)
