### ISSUE TITLE
Add hotkey support for SingleFile-editor removing elements !

### ISSUE THREAD

**Issue by dnknn** [gildas-lormeau/SingleFile#494]
<details>
<summary>💥 Current issue:</summary>

![209_24051750](https://user-images.githubusercontent.com/10995302/94070745-531ee480-fe25-11ea-87f1-258135b13e86.png)
- ### 💥 Current issue: 
 　　　　🛇.When selecting elements,  cannot use hotkeys to quickly select element levels.
 　　　　🛇.Cannot use Ctrl+Z/Ctrl+Shift+Z to undo/redo the last operation.

</details>

<details>
<summary>Similar/Reference extension demo</summary>

>   Similar to this extension: [Click to Remove Element](https://chrome.google.com/webstore/detail/jcgpghgjhhahcefnfpbncdmhhddedhnk)  　 (`CTRE`)
>  　  Very simple to use:  use `Q`/`W` to select element level 

<details>
<summary>🎬 Click to seeing gif demo: </summary>

![209_23041447](https://user-images.githubusercontent.com/10995302/93932831-59dd2700-fd53-11ea-82e6-e600c27ef338.png)

![123456](https://user-images.githubusercontent.com/10995302/93934708-2354db80-fd56-11ea-956a-c31ca36ac920.gif)

</details>

But `CTRE` is not enough, it will be perfect if can add the following  hotkeys 

</details>

> These hotkeys are the most basic standard universal hotkeys. 
If `SingleFile` can be supported, it will be very convenient to edit.

# 　　 ⌨⌨🖮🖮🖮⌨⌨

🖮 | action
:---: |--- |
<kbd>Tab</kbd> | select element's parent 
<kbd>Shift+Tab</kbd>  | select element's children
<kbd>Space</kbd> | confirm ✂, equivalent to <kbd>left-click</kbd> 
<kbd>Ctrl+Z</kbd> | Undo  the last ✂ 
<kbd>Ctrl+Shift+Z</kbd> | Redo the last ✂

**Comment by gildas-lormeau** [comment]
Thank you very much for the suggestion! I totally agree that it would be a nice feature to have.

**Comment by dnknn** [comment]
@gildas-lormeau  I updated this document, added that the 🖱-🎡mouse-wheel can also be used to select element levels.

**Comment by dnknn** [comment]
Hi @gildas-lormeau I updated this hotkey-document, It is very clear.

**Comment by gildas-lormeau** [comment]
@dnknn Thank you!

**Comment by gildas-lormeau** [comment]
@dnknn Your suggestions are implemented. Feel free to test the extension by extension manually to give me some feedback if necessary.

**Comment by dnknn** [comment]
Hi @gildas-lormeau  thank you very much!
> and give some feedback if necessary.

I tried it. Great, great work, already very satisfying!  report a few small problems: 

### 1. Cannot use `Ctrl+Shift+Z` to Redo.

### 2. Cannot  automatically disabled ✂ after saving a page
If you forget to close the ✂-mode, then after 📥💾, `file:/// a saved page`  will leave `.single-file-hover` CSS style.

<details>
<summary>👁 Screenshot and Gif demo description </summary>

![2010_02110922](https://user-images.githubusercontent.com/10995302/94884331-bf41be00-049f-11eb-8fe0-708cb0393316.png)

## Since it is a `hover` event, you can reproduce the problem like this: 👇
![1111](https://user-images.githubusercontent.com/10995302/94884959-80146c80-04a1-11eb-8463-1d2657606716.gif)

</details>


This question is exactly equivalent to [/issues/496#issuecomment-697252687](https://github.com/gildas-lormeau/SingleFile/issues/496#issuecomment-697252687)
So , you should be able to fully understand the meaning. support to when saving, SingleFile will disable ✂-mode on a saved page.

-----

### 3.  Bug: can not be used normally.
`Tab/Shift+Tab` is very easy to use and great! but sometimes it seems that the work cannot be very stable.

<details>
<summary>👁 Screenshot and Gif demo description </summary>

![2010_02112638](https://user-images.githubusercontent.com/10995302/94885195-2bbdbc80-04a2-11eb-8fe2-d32a78f6a26c.png)

![bug](https://user-images.githubusercontent.com/10995302/94885278-5f004b80-04a2-11eb-9555-edd7ee6c2397.gif)

</details>

I don't understand the specific reason. but this bug, I guess it is related to `Shift+Tab` ,  Because sometimes `Shift+Tab` will become the default anchor focus, Instead of ✂-mode for element parent-child select.

<details>
<summary>👁  DEMO the default anchor focus. </summary>

During normal page browsing, `Tab/Shift+Tab` can focus HTML `tabindex` attribute 👇

![2010_02115503](https://user-images.githubusercontent.com/10995302/94886569-1fd3f980-04a6-11eb-9cf7-c6460085462f.png)


![445](https://user-images.githubusercontent.com/10995302/94886268-29a92d00-04a5-11eb-8ad2-ec63236f0bd5.gif)

</details>
In other words, this bug is likely to have an incompatible conflict with the default focus anchor point, so you should add judgment processing, such as disabling the default anchor point focus.



----

### 4. Add to support: AI intelligent interactive operation:
![2010_02113600](https://user-images.githubusercontent.com/10995302/94885697-77249a80-04a3-11eb-9682-8460a9b5440f.png)
when ❷ mode is `ON` status, If you want to enter ❶ mode, just click the ❶ button, instead of first closing ❷ mode and then entering ❶ mode.

----

### 5. Add to support:  The default edit-mode after entering the `SingleFile-editor` page.

> why?   Because it is automatically in a certain default mode, you don't need to click additional button.

💥 Current issue:  🛇.when entering the SingleFile editor , by default is nothing.
&emsp;&emsp;￣￣￣￣￣￣￣

❥ **Expected behavior:** 
&emsp;&emsp;￣￣￣￣￣￣￣￣￣￣￣￣￣￣
　　　　For example: when entering the SingleFile editor , by default is in ✂-mode.

❓ How to achieve: Add a  option: 👇 or other ways.
&emsp;&emsp;￣￣￣￣￣￣￣
![2010_02121645](https://user-images.githubusercontent.com/10995302/94887534-24e67800-04a9-11eb-9438-94eac1b27f38.png)

I personally think that the default mode is ✂-mode is the best, because after you enter the editor, you can directly remove unnecessary elements.
Therefore, if you only want to support this default mode, it can be the ON/OFF option.
If you want users to choose other modes, it can be a `<select>` option.

----

### 6. Enhance the visual interaction between `.single-file-hover` elements and other elements

💥 Current issue:  The visual contrast is not strong enough
&emsp;&emsp;￣￣￣￣￣￣
　　　　- now only `.single-file-hover{outline:4px dotted #f00}`
　　　　- The background of other elements cannot be darkened a little bit.

❓ How to achieve: Add some simple CSS styles to enhance visual perception.
&emsp;&emsp;￣￣￣￣￣￣￣￣ For example:
`cursor: crosshair !important;`   👈 I think it is necessary.

Of course, I'm just an example, I don't quite understand.
```
.single-file-hover {
    outline: 4px dotted #f00 !important;
    box-shadow: 0 0 99999px #080b09f0;
    /* box-shadow: 0 0 1px 99999px #080b0947; */
    /* background: radial-gradient(#ffffff21, #0000004f ); */
    cursor: crosshair !important;
    /* background: #77f3512e; }
```

<details>
<summary>gif demo </summary>

![888](https://user-images.githubusercontent.com/10995302/94890559-1ea8c980-04b2-11eb-915e-10590d7eb572.gif)

</details>



I don't know if the way of using overlays is good or bad. 
For example, [`uBlock Origin`](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) seems to be like use this: overlays 

<details>
<summary> It seems to be ok. </summary>

![777](https://user-images.githubusercontent.com/10995302/94889697-af31da80-04af-11eb-9ffb-8ef38761f8e8.gif)

</details>

**Comment by gildas-lormeau** [comment]
Thank you for the feedback. Some of the issues you're describing seem obsolete and already fixed. Can you confirm you did your tests with an up to date version of SingleFile?

**Comment by gildas-lormeau** [comment]
Here are my comments/results with an up to date version of SingelFile:
- #1: I can't reproduce it
- #2: I can't reproduce it
- #3: I can't reproduce it
- #4: this is a separate issue from my point of view and it's not obvious to tell which choice is the best in my humble opinion
- #5: this is also a separate issue. Note the editor is called "annotation editor", not "removal editor"
- #6: this is also a separate issue and it's quite subjective

**Comment by dnknn** [comment]
I tested the latest version.   *1:  fixed.

> *2: Edit: I fixed it

No... my test is still exactly the same.


> * 3: I can't reproduce it

You can reproduce it like this, you keep pressing `Tab` , and finally it will become the default anchor focus of the focusable element on the page.



> * 4: Edit: I think I agree with you but it's maybe a separate issue that is more complex that what you described.

The main reason is that you know that there is an improved feature, and if it is not easy to implement it, please ignore it.




> * 5: this is a separate issue. Note the editor is called "annotation editor", not "removal editor"

Yes, I totally know it, 👉it is a `annotation editor`.  That’s why I said the **default-edit-mode**.


> * 6: this is also a separate issue and it's quite subjective. From my point of view, it's hard to miss the outline borders. I agree that I the cursor aspect could be different though. I'll fix that.

yes, it's quite subjective.  I'm just talking, you decide it yourself.

**Comment by gildas-lormeau** [comment]
I did some more tests and I still say that bug #2 is fixed and that I can't understand/reproduce bug #3.

**Comment by dnknn** [comment]
> I did some more tests and I still say that bug #2 is fixed and that I can't understand/reproduce bug #3.

![2010_04070352](https://user-images.githubusercontent.com/10995302/95003243-e0292100-060f-11eb-813b-0f1a103d6c6b.png)
👆 I haven't tested the latest version. After you push the new version to the store, I will test again.

**Comment by gildas-lormeau** [comment]
#4 and #5 have been implemented.

**Comment by gildas-lormeau** [comment]
I just found a way to reproduce the "tab" key issue (#3), I guess. It will be fixed in the next version.

**Comment by dnknn** [comment]
I tested, 👍 #5  Well done! 　　**But** for #4 , You don't fully understand the meaning...

For example: ❶ and ❷ 
![2010_05193357](https://user-images.githubusercontent.com/10995302/95074813-be2fbb80-0741-11eb-841b-7ad6c6c6ed18.png)
now, Although the ❶ button can be clicked, but it cannot enter ❶-mode. 
In other words, when you click the ❶ button,  cannot close ❷-mode to enter ❶-mode.

For example:  Current activation mode is ❷ , Then, first figure out one thing: 
## ❶ and ❷, the two cannot exist at the same time, right?

At this point, if you want to switch to ❶ mode, how do you do it?

The steps can only be like this:   Current activation mode is ❷ 
1st: 　 Click ❷ button to exit/disable it , (Without this step, you will never be able to enter ❶-mode)
2nd: 　Click ❶ button to enter ❶-mode

----
So my suggestion is to skip the 1st step.
Just click the ❶ button directly, It will directly enter ❶-mode ! (Of course, it will exit ❷ mode first)


----
## Switch
👆keyword:  Close/disable the current mode and switch to another mode.
If A and B are two modes that cannot exist at the same time, then click the button to switch directly.

**Comment by dnknn** [comment]
> I just found a way to reproduce the "tab" key issue (#3), I guess. It will be fixed in the next version.

In the current test, I can't reproduce "tab" key issue , although I don't have more detailed tests. But it is much better than before, it should be fixed by you.

**Comment by gildas-lormeau** [comment]
You can reproduce it here: https://news.ycombinator.com/.

**Comment by dnknn** [comment]
> You can reproduce it here: https://news.ycombinator.com/.

I still can't reproduce it. But if you can reproduce it, it means there should be some problems.


https://github.com/gildas-lormeau/SingleFile/issues/494#issuecomment-703588423
`But for #4 , You don't fully understand the meaning...`
👆 In addition, I add, maybe I am wrong,  

❶ and ❷ can coexist, but when the two modes coexist, ❶-mode cannot be edited with a mouse click.

So, I think the mode of removing elements and other modes should not coexist.
Instead, it uses a switching method. Only then will it be more in line with the user's expected behavior.

**Comment by gildas-lormeau** [comment]
I also fixed the #4 issue by never blocking the user but disabling the previous incompatible mode.

**Comment by dnknn** [comment]
> I also just fixed #4 by never blocking the user but disabling the previous incompatible mode.

I just downloaded to tested and found no changes.  

Look at these 2 comments: 
https://github.com/gildas-lormeau/SingleFile/issues/494#issuecomment-703588423
https://github.com/gildas-lormeau/SingleFile/issues/494#issuecomment-703598280

So, I think the mode of removing elements and other modes should not coexist.
Instead, it uses a switching method. Only then will it be more in line with the user's expected behavior.

**Comment by gildas-lormeau** [comment]
I considered 1 and 2 could coexist. the fix I pushed was related to highlighting functions vs cut mode. 1 and 2 could coexist but 1 is hard to use, I'll change that.

**Comment by dnknn** [comment]
> I considered 1 and 2 could coexist. the fix I pushed was related to highlighting functions vs cut mode. 1 and 2 could coexist but 1 is hard to use, I'll change that.

The problem with coexistence of 1, 2 is that it may be easy to accidentally remove elements with a mouse click.

Optimization example:
- ON/OFF Options
- Only when the removing-element mode and other modes coexist, 
can use `Esc` to close/disable the removing-element mode.

**Comment by gildas-lormeau** [comment]
The fix is already implemented and I just published the new version. "Esc" is not implemented since it's a separated issue...

**Comment by dnknn** [comment]
> The fix is already implemented and I just published the new version.

tested and very perfect! great!  and please ignore "Esc" it.
