### ISSUE TITLE
Save the CSS manually edited by the Console/DevTools on the annotation editor page

### ISSUE THREAD

**Issue by dnknn** [gildas-lormeau/SingleFile#495]
<details>
<summary>Details</summary>

`chrome-extension://mpiodijhokgodhhofbcjdecpffjipkle/extension/ui/pages/editor.html`
👆 then,  looking at a gif first 👇

![12333](https://user-images.githubusercontent.com/10995302/93938071-4e8df980-fd5b-11ea-89b8-e763cd81d1c0.gif)

----
On Chrome, the console is called `DevTools`

![209_23051416](https://user-images.githubusercontent.com/10995302/93938307-a75d9200-fd5b-11ea-8ab6-1e27bcc02950.png)

👆 `background:#00f;`  This is a manual editing operation using the DevTools console on the SingleFile-editor page, Because sometimes, you want to edit it (🅲🆂🆂) by the way, such as changing the `#abc{font-size:18px}`; , etc.

## But you definitely want it to be saved together , right ?

- ## 💥 Current issue: Inability to be saved

<s>That's right: SingleFile's style sheet setting options may save console operations, but it will also save some useless CSS at the same time, which will greatly increase the file size.

- ## ❓ So, how to achieve: 
Add a separate setting option: to solve this problem separately.</s>

</details>

🔌Extending DevTools API?
https://developer.chrome.com/extensions/devtools
https://chromedevtools.github.io/devtools-protocol/

**Comment by gildas-lormeau** [comment]
This feature is already implemented but it was only working outside the editor. In the next version SingleFile should hopefully be able to take these changes into account as well. Regarding the "useless CSS", maybe it's another issue?

**Comment by dnknn** [comment]
> This feature is already implemented but it was only working outside the editor (i.e. on a normal page).

I know this completely, so I asked the question.

**Comment by dnknn** [comment]
Hi @gildas-lormeau  !
> Regarding the "useless CSS", maybe it's another issue?

　　　No..no.. it seems to be no problem.
---

> This feature is already implemented but it was only working outside the editor (i.e. on a normal page).

　　Yes, there is no such problem outside the editor. I also know this completely, so I asked the question. 
But you may not know, I have tested and found that: 
In SingleFile-editor, it can save some edited CSS, such as `color: ;` but it cannot save the added CSS.

---
> In the next version, SingleFile should hopefully be able to take into account the CSS changes made in the editor as well.

　　Yes yes, i'm talking about this problem,  Hope it will also work in the SingleFile-editor.

**Comment by dnknn** [comment]
Hi @gildas-lormeau  !
> Regarding the "useless CSS", maybe it's another issue?

　　No..no.. it seems to be no problem.

---

> This feature is already implemented but it was only working outside the editor (i.e. on a normal page).

　　Yes, there is no such problem outside the editor. I also know this completely, so I asked the question. 
But you may not know, I have tested and found that: 
In SingleFile-editor, it can save some edited CSS, such as `color: ;` but it cannot save the added CSS.


---
> In the next version, SingleFile should hopefully be able to take into account the CSS changes made in the editor as well.

　　Yes yes, i'm talking about this problem,  
After I worked hard to edit the CSS in the DevTools of SingleFile-editor, and then saved it, I finally realized that the CSS just now was not saved.... 😭-_-😢

Hope it will also work in the SingleFile-editor.
If this problem can be directly operated in SingleFile-editor and saved at the same time, it will be more direct and convenient!

**Comment by dnknn** [comment]
@gildas-lormeau 

I specially downloaded the repo and found that there seems to be problem.

> I don't know repo very well, maybe my operation method is wrong.

`style="background:#da0;"`     👈The added inline style can be saved.
`..{background:#da0;}`　　　　👈CSS style  can  not be saved.

**Comment by gildas-lormeau** [comment]
I just did another test and it worked fine for me. I *added* a rule via the dev tools in the editor and it was present in the saved page.

When you apply the changes via the dev tools, do you see the background color changing in the page? If not, it means your rule is ignored when applying the cascade (like in your GIF demo). Suffixing the property value with "!important" might help.

**Comment by dnknn** [comment]
> Suffixing the property value with `!important` might help.

I don't understand at all except CSS, It is because of [`Stylus`](https://github.com/openstyles/stylus/) this extension that I learned CSS.
CSS Specificity, I also know it well.  Normally, it can take effect in DevTools, which means that its Specificity has priority.

And the CSS I tested is the only one, and the selector has a very high level, so there is no specificity problem.

It doesn't matter, when you release the new version, I will test it again, that is the real and reliable test.

**Comment by gildas-lormeau** [comment]
Did you find the last bug in the version you installed manually or the version from the store? I noticed it too and it's supposed to be fixed.

**Comment by dnknn** [comment]
> Did you find the last bug in the version you installed manually or the version from the store?

store version  is no problem!

👇bug in repo
![209_24014311](https://user-images.githubusercontent.com/10995302/94049277-5b682700-fe07-11ea-91fe-62896a87baa3.png)

**Comment by gildas-lormeau** [comment]
The last issue should be fixed now. Regarding the current issue, here is a GIF showing it's fixed with in the version from the repo.

![demo-css](https://user-images.githubusercontent.com/396787/94059421-aa4f9580-fde2-11ea-91fb-5f8b1798bbeb.gif)

**Comment by dnknn** [comment]
> The "blank editor" issue should be fixed now. 

💪yes, perfectly fixed !!

----

> Regarding the current issue, here is a GIF showing it's fixed in the version from the repo.
No...no... no fix

looking my gif demo 👇   

![bug](https://user-images.githubusercontent.com/10995302/94061614-3334f400-fe18-11ea-9b06-d4eebd540dfb.gif)


version  `datetime="2020-09-23T19:09:52Z" `
![image](https://user-images.githubusercontent.com/10995302/94061865-8d35b980-fe18-11ea-9530-d0c120587bad.png)

**Comment by dnknn** [comment]
<details>
<summary>json</summary>


```
{
  "profiles": {
    "1235": {
      "addProof": false,
      "applySystemTheme": true,
      "autoClose": false,
      "autoOpenEditor": false,
      "autoSaveDelay": 1,
      "autoSaveExternalSave": false,
      "autoSaveLoad": false,
      "autoSaveLoadOrUnload": true,
      "autoSaveRepeat": false,
      "autoSaveRepeatDelay": 10,
      "autoSaveUnload": false,
      "backgroundSave": true,
      "browserActionMenuEnabled": true,
      "compressCSS": true,
      "compressHTML": true,
      "confirmFilename": false,
      "confirmInfobarContent": false,
      "contextMenuEnabled": false,
      "displayInfobar": true,
      "displayStats": false,
      "extractAuthCode": true,
      "filenameConflictAction": "uniquify",
      "filenameMaxLength": "192",
      "filenameReplacedCharacters": [
        "~",
        "+",
        "\\\\",
        "?",
        "%",
        "*",
        ":",
        "|",
        "\"",
        "<",
        ">",
        "\u0000-\u001f",
        ""
      ],
      "filenameReplacementCharacter": "_",
      "filenameTemplate": "{page-title}.html",
      "forceWebAuthFlow": false,
      "groupDuplicateImages": true,
      "ignoredBookmarkFolders": [],
      "includeBOM": false,
      "includeInfobar": true,
      "infobarTemplate": "{page-title}{date-iso}",
      "loadDeferredImages": false,
      "loadDeferredImagesBlockCookies": false,
      "loadDeferredImagesBlockStorage": false,
      "loadDeferredImagesKeepZoomLevel": false,
      "loadDeferredImagesMaxIdleTime": 1500,
      "logsEnabled": true,
      "maxResourceSize": 10,
      "maxResourceSizeEnabled": false,
      "openEditor": true,
      "progressBarEnabled": true,
      "removeAlternativeFonts": true,
      "removeAlternativeImages": true,
      "removeAlternativeMedias": true,
      "removeAudioSrc": true,
      "removeFrames": false,
      "removeHiddenElements": true,
      "removeImports": true,
      "removeScripts": true,
      "removeUnusedFonts": true,
      "removeUnusedStyles": true,
      "removeVideoSrc": true,
      "replaceBookmarkURL": false,
      "resolveFragmentIdentifierURLs": false,
      "saveCreatedBookmarks": false,
      "saveFavicon": true,
      "saveRawPage": false,
      "saveToClipboard": false,
      "saveToGDrive": false,
      "shadowEnabled": true,
      "tabMenuEnabled": true,
      "userScriptEnabled": true,
      "warnUnsavedPage": true
    },
  },
  "rules": [],
  "maxParallelWorkers": 6
}

```



</details>

**Comment by gildas-lormeau** [comment]
Actually, the extension does not really use properly the devtools API. There is some work to do to fix this issue...

**Comment by gildas-lormeau** [comment]
After inspecting more closely this issue, I realize that the API (https://developer.chrome.com/extensions/devtools_inspectedWindow#method-getResources) used by SingleFile to get the changes in the inline styles does not provide enough details to implement this feature. So, I'm closing it since it can't be fixed.

**Comment by dnknn** [comment]
> So, I'm closing it since it can't be fixed.

_\-\_\- I'm sorry to hear that,  It is indeed a pity \-\_\-_ . and two suggestions: 

1. if possible, keep this issue open for a period of time, if it is still not resolved by then, close it again.

2. Of course, this may not be easy to implement, or not suitable for implementation. I will just talk about it. ▼
You can also consider providing a simple 🅲🆂🆂 edit interface for the annotation editor page.
The valid CSS styles added by the user here will be saved by SingleFile.


Examples for reference: 

[`Stylus`](https://github.com/openstyles/stylus/)　　　　I am using. It is a professional large-scale CSS style manager container.

Below are simple and lightweight CSS editors (I don't use them). Because they are **simple** and **lightweight**, they just provide a user interface for CSS editing, so if you want to do for SingleFile, you can refer to them.

- [`Live editor for CSS`](https://chrome.google.com/webstore/detail/ifhikkcafabcgolfjegfcgloomalapol)　　　　https://github.com/webextensions/live-css-editor



- [`Live CSS Tester`](https://chrome.google.com/webstore/detail/djdnjlkbgeddaglpomonofdcahkpmjaj)　　　　A CSS editor integrated into DevTools.


- [`Amino: Live CSS Editor`](https://chrome.google.com/webstore/detail/pbcpfbcibpcbfbmddogfhcijfpboeaaf)　　　　


- [`User CSS`](https://chrome.google.com/webstore/detail/okpjlejfhacmgjkmknjhadmkdbcldfcb)

----
Tip: I'm just talking about letting you know.

**Comment by gildas-lormeau** [comment]
Coding a CSS editor is too muck work for me. However, note that the only thing that you cannot do is changing existing rules. **Adding new rules or adding inline styles will work**. Moreover, I think you could open the saved page from the filesystem, use a separate editor like the ones you mentioned, and save the page with Ctrl+S. That should also work fine.

**Comment by dnknn** [comment]
> However, note that the only thing that you cannot do is changing existing rules. **Adding new rules or adding inline styles will work**.

👍OK, that's it! I fully understand now. 💪

> **Adding new rules or adding inline styles will work**.

That's enough! It's enough, it doesn't affect it at all!

Thanks♪(･ω･)ﾉ
