### ISSUE TITLE
Add an option:  ⬜ automatically remove contenteditable when saving

### ISSUE THREAD

**Issue by dnknn** [gildas-lormeau/SingleFile#496]
![209_23053357](https://user-images.githubusercontent.com/10995302/93940051-687d0b80-fd5e-11ea-8c94-88485e21ee81.png)

👆Text editing mode, very good function, but it is not smart now.

----
- ## 💥 Current issue: 
　　❶ When you turn it `ON`,  ❷then forget to turn it `OFF`, 
　　❸ After finally saving the html file, it is also in the `ON` state,  which is `contenteditable="true"`

- ## ❥ Expected behavior: 
　　automatically `OFF` (remove `contenteditable="true"`) when saving.

- ## ❓ How to achieve: 
　　Changed by default.  or Adding a  option: ⬜ automatically remove contenteditable when saving.

**Comment by gildas-lormeau** [comment]
That's a very specific need. What's the problem if you forget to turn it OFF?

**Comment by dnknn** [comment]
> What's the problem if you forget to turn it OFF?

![209_23072525](https://user-images.githubusercontent.com/10995302/93947318-f9a7ae80-fd6d-11ea-8068-d480cfe55356.png)

After you save an HTML file and open it to view it, you definitely don't want the full text to be in editable mode, right?

## Edit mode ⚔ View mode ,  These two are completely opposites.

👁 **View mode** :  🔐 It will not be accidentally edited. It is the mode of viewing.
✎**Edit mode** :  Obviously, it is not a standard way to read.

----
The most important issue is that many extension APIs/browser's own APIs specifically judge whether fields can be edited.

## If  is edit field , many actions will be completely disabled (no works)

----
Let me give you an example :
Copy better  https://chrome.google.com/webstore/detail/hpihdokfdmmghaclaojfpmbckkhjgebc

![209_23073544](https://user-images.githubusercontent.com/10995302/93947840-67a0a580-fd6f-11ea-818e-7c84bcd4333b.png)
If it is `contenteditable="true" `, the text will not be copied automatically after selection.


----
I think you should fully understand the problem now.

**Comment by dnknn** [comment]
> What's the problem if you forget to turn it OFF?

![209_23072525](https://user-images.githubusercontent.com/10995302/93947318-f9a7ae80-fd6d-11ea-8068-d480cfe55356.png)

After you save an HTML file and open it to view it, you definitely don't want the full text to be in editable mode, right?

## Edit mode ⚔ View mode ,  These two are completely opposites.

👁 **View mode** :  🔒 It will not be accidentally edited. It is the mode of viewing.
✎ **Edit mode** : &nbsp;🔓 Obviously, it is not a standard way to read.

----
The most important issue is that many extension APIs/browser's own APIs specifically judge whether fields can be edited.

## If  is edit field , many actions will be completely disabled (no works)

----
Let me give you an example :
Copy better  https://chrome.google.com/webstore/detail/hpihdokfdmmghaclaojfpmbckkhjgebc

![209_23080232](https://user-images.githubusercontent.com/10995302/93949380-29a58080-fd73-11ea-90e1-f1777a5b8319.png)

If it is `contenteditable="true" `, the text will not be copied automatically after selection.


----
I think you should fully understand the problem now.

And, just imagine, if any webpage  is in `contenteditable="true"` mode, what bad results do you think there will be ❓

So I think in the viewing mode, it is completely unnecessary to be in editable mode at the same time.

**Comment by gildas-lormeau** [comment]
Thank you, it was indeed a bug. I fixed it but note that the button won't be disabled after saving a page, as you suggested. However the saved page won't be editable.

**Comment by dnknn** [comment]
> Thank you, it was indeed a bug. I fixed it but note that the button won't be disabled after saving a page, as you suggested. However the saved page won't be editable (this was the bug).

I tested it, and it was perfect, yes, it may be that I expressed confusion. But the effect is what you did. That's right!
