### ISSUE TITLE
add to support <details> content

### ISSUE THREAD

**Issue by dnknn** [gildas-lormeau/SingleFile#498]
You can test this problem directly on this page. 
This is just an HTML attribute, is it necessary to support it?

----

## `<details>` 　　is  invalid 👇

<details>
<summary>the collapsed content cannot be captured by SingleFile</summary>

invalid

111111111111111111111
222222222222222222222
333333333333333333333

</details>

-----
## `<details open>`  is valid 👇

<details open>
<summary>This is no problem</summary>

valid
111111111111111111111
222222222222222222222
333333333333333333333

</details>

**Comment by gildas-lormeau** [comment]
Thank you! This was a bug. It's fixed now.
