### ISSUE TITLE
🗚 Can support font-size hotkeys in the contenteditable editor of SingleFile ?

### ISSUE THREAD

**Issue by dnknn** [gildas-lormeau/SingleFile#499]
![209_23053357](https://user-images.githubusercontent.com/10995302/93940051-687d0b80-fd5e-11ea-8c94-88485e21ee81.png)

Now supports 3 standard HTML editing hotkeys.  which is `Ctrl+B`   `Ctrl+I`   `Ctrl+U`

<details>
<summary>Details</summary>

![00](https://user-images.githubusercontent.com/10995302/94052447-8ce2f180-fe0b-11ea-8d7e-88a4362261bd.gif)

</details>

---
So  can also support 🗚 `font-size` hotkeys in the contenteditable editor of SingleFile ?

- ## 🗚 Function purpose: 　Quick  change/custom font-size
>  　　 　　I think this is a very useful editing function.

- ##  Implementation principle:  
  　　 　　add inline style, just like `style="font-size:18px;"`

- ## ⌨ add  hotkeys to achieve:  
  　　 　　Ctrl+1/2/3/4/5 or Alt+1/2/3/4/5 or Ctrl+[/]
`Ctrl+1` 　　`style="font-size:17px;"`
`Ctrl+2` 　　`style="font-size:19px;"`
`Ctrl+3` 　　`style="font-size:22px;"`
.....

----
Don't know if it is easy to achieve it....

**Comment by gildas-lormeau** [comment]
I think that if I start integrating such a feature, I will end up coding a WYSIWYG editor. I'm not very motivated to do that, honestly.  I'd rather integrate an existing WYSIWYG editor (open-source), if necessary.

**Comment by dnknn** [comment]
You also make sense, then I close this issue, it is not a big problem.
