### ISSUE TITLE
How can I  specify http request headers in singlefile CLI 

### ISSUE THREAD

**Issue by benfiveblocks** [gildas-lormeau/SingleFile#501]
I am using singlefile command line interface, and the web site I am hitting receives some of its parameters as http request headers. I understand in Chrome I can use Grephy's [Modify Header Value](https://chrome.google.com/webstore/detail/modify-header-value-http/cbdibdfhahmknbkkojljfncpnhmacdek/related?hl=en) extension. Is there a simpler way?

**Comment by gildas-lormeau** [comment]
I just added the option `--http-header`. Update the code of SingleFile and pass the headers like this: `--http-header=x-header-name:x-header-value --http-header=x-another-header-name:x-another-header-value `.
