### ISSUE TITLE
HTML Screenshot: Save only particular element

### ISSUE THREAD

**Issue by in4u** [gildas-lormeau/SingleFile#506]
**Is your feature request related to a problem? Please describe.**

Many times I just want to save layout preserved content while stripping off the page's header bar, top menu, left/right sidebars, thousand odd comments at the bottom, footer bar, navigation menu and what not.

This is doable currently but there are drawbacks. Sometimes the content is miles long and it's frustrating to keep dragging the selection down over dozen pages. And some sites simply disable the selection functionality so `Save selection` feature becomes useless in that case. The only other way is to use the annotation editor and tediously delete all such irrelevant elements from a page so that only the desired main element remains.

Ideally, just like the Firefox's screenshot tool allows to point and click an element to save it as image, I'd like an HTML screenshot option to save it as HTML page instead.

**Describe the solution you'd like**

In the annotation editor, there's a button with scissor icon to `enable/disable removing document's element on click`. It allows selected elements to be removed from the page. Perhaps add a new button which allows only the selected element of the page to be saved while discarding everything else.

**Additional context (optional)**

I did go through the help file but couldn't find a way to save just the selected element(s) or inverse the element selection for that matter. So, apologies if a solution already exists in some other way which I might've overlooked.

**Comment by gildas-lormeau** [comment]
Thank you for the detailed description of the issue. I think I agree a feature to remove the unselected content should exist in the annotation editor. Meanwhile, note that: 
 - selecting "Save selection" in the menu without having selected any content first might help to select large contents
 - you can select a small part of the large content at the top, release the left mouse button, scroll down, press Shift and simultaneously click with the left button. It will select the content from the beginning of the selection to where you clicked.

**Comment by in4u** [comment]
Thanks for these tips! Wasn't aware of the 1st trick at all. Maybe you should rename `Save selection` option as `Save selection or element` or something because it's not intuitive enough to suggest that it works before even starting to select. Even the help doc doesn't mention this hidden feature!

While playing around using that pre-selection trick, I randomly found it a bit buggy though. Think I switched to other tab(s) for something while `Save selection` was enabled via page's context menu on one tab but a selection wasn't yet finalized. And then don't know how but text selection just stopped working on any tab, including the original one. Things returned back to normal after restarting the browser. Another time, I used `Save selection` option via toolbar button and then somehow it became impossible to exit the selection mode using `Escape` key until and unless a selection was actually saved.

***

Some minor feedback regarding the help doc:

Don't know if it's due to my Firefox profile, settings or what but certain icons in the help file are not quite clear and very hard to identify.

<details>
<summary>See this screenshot (only colorful icons are clear, rest grey on white ones are hard, if not impossible, to recognize).</summary>

![SS](https://user-images.githubusercontent.com/43062185/95487010-67c8b400-09b1-11eb-83f2-cbba8b71049c.png)
</details>

Also, please consider hosting the help doc in this repo too, perhaps in the wiki section.

<details>
<summary>Lastly, a few typos.</summary>

https://github.com/gildas-lormeau/SingleFile/blob/2f691fddc8615fbcf44a7b4419a309ca59376a14/extension/ui/pages/help.html#L17
https://github.com/gildas-lormeau/SingleFile/blob/2f691fddc8615fbcf44a7b4419a309ca59376a14/extension/ui/pages/help.html#L178
https://github.com/gildas-lormeau/SingleFile/blob/2f691fddc8615fbcf44a7b4419a309ca59376a14/extension/ui/pages/help.html#L371
https://github.com/gildas-lormeau/SingleFile/blob/2f691fddc8615fbcf44a7b4419a309ca59376a14/extension/ui/pages/help.html#L423
https://github.com/gildas-lormeau/SingleFile/blob/2f691fddc8615fbcf44a7b4419a309ca59376a14/extension/ui/pages/help.html#L523
</details>

**Comment by gildas-lormeau** [comment]
I was not able to reproduce the issue related to saved selection. Feel free to create a new ticket if you know how to reproduce it. 

I fixed the other issues. Thank you!

**Comment by in4u** [comment]
Thanks for the quick update! The new button's functionality seems to be working great. However, while testing, I ran into a curious case which am not sure is a bug or something due to my settings. Maybe you can take a look:

URL: `https://old.reddit.com/r/firefox/`

<details>
<summary>Screenshot of element which was selected with the new button.</summary>

![E](https://user-images.githubusercontent.com/43062185/95613791-1ee13000-0a83-11eb-8142-d8a941c614ec.png)
</details>

<details>
<summary>Screenshot of saved file which doesn't match the original layout and includes other unwanted elements.</summary>

![S](https://user-images.githubusercontent.com/43062185/95613864-35878700-0a83-11eb-8ece-248091786ab9.png)
</details>

**Comment by gildas-lormeau** [comment]
Actually the element containing the image "join Firefox" is inside the left panel but it moved up with CSS. I'll try to see if I can improve the algorithm in order to take into account these cases.

**Comment by in4u** [comment]
Ah, okay. Nothing's wrong with my settings then. Regardless of whether you can manage to improve the algorithm for such edge cases or not, this problem can be easily solved by individually removing the CSS moved elements so it's no big deal.

Rest all seems fine so far. Will let you know if something else is amiss. Cheers!

**Comment by gildas-lormeau** [comment]
I improved the implementation to handle properly the example you cited. The fix will be available in the next version.

**Comment by in4u** [comment]
Alright, will look forward to it! One other thing I noticed is that despite enabling `compress HTML content` option unnecessary whitespace and empty lines still creep into the saved file.

**Comment by gildas-lormeau** [comment]
@in4u That's normal, removing all the whitespaces could break the page layout.

**Comment by in4u** [comment]
Fair enough. To get rid of empty lines and whitespaces between closed tags, etc. user can run the saved page's code through a minifier separately anyway.
