### ISSUE TITLE
The "scissors" tool does not work well.

### ISSUE THREAD

**Issue by timbalerojack** [gildas-lormeau/SingleFile#507]
Until version 1.18.10 I have been using your plug-in without any problem. Now there are webs where the scissors tool does not work as it should. I have tried SingleFile in both Edge and Firefox and the result is the same: there are parts (frames) of the page where if I try to remove some element, when I put the cursor over those parts, the content disappears and there is no way to select anything. Below, I point out the link to a website where the problem is shown clearly.
**To Reproduce**
1. Go to https://ruleteros.variousforum.com/
2. Click on menú pluging "note and save the page"
3. Put the selection cursor to delete any element from the central frame

**Expected behavior**
Select any element and be able to remove it.

**Screenshots**

**Environment**
 Windows 10
 - Browser: Edge and Mozilla FireFox
 - Version: 64 bits

**Additional context**

**Comment by timbalerojack** [comment]
Thank you for your work.

**Comment by gildas-lormeau** [comment]
Thank you for the issue, I was not sure I introduced a regression. The problem is that sometimes the outline is not visible. I implemented another technique that should be simpler and better.
