### ISSUE TITLE
[Feature Request] option to set as default "save" and "save as" format.

### ISSUE THREAD

**Issue by FredThompsonII** [gildas-lormeau/SingleFile#51]
As the title says...If so, please do so for FF 56+ builds.

**Comment by gildas-lormeau** [comment]
Hi I'm afraid this is not technically doable currently. I took a quick look at the [WebExtension API documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API) but I was not to find one that would help to implement this feature.
