### ISSUE TITLE
resizing page error

### ISSUE THREAD

**Issue by NOSEBAG** [gildas-lormeau/SingleFile#513]
Hi Gildas,

I have a problem not in saving this page, but when it comes to resizing.
Link is here;
https://www.koozai.com/tv/quick-vids/how-to-use-facebook-audience-insights-to-your-advantage/

If you try to resize the page smaller, the inserted image within the TV frame doesn't resize with the TV.

Any ideas?

Hope you can fix if this is a bug

Many thanks Gildas
Nosebag
(PS - was saved on Windows 10 64bit Pro, using Google Chrome
Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by gildas-lormeau** [comment]
This issue and #514 are related to the fact that scripts are removed from saved pages by default. You can find more info about this in the FAQ: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages.
