### ISSUE TITLE
Page saves without popup image on click

### ISSUE THREAD

**Issue by NOSEBAG** [gildas-lormeau/SingleFile#514]
Hello Gildas,
I'm on a website here;
https://technicalseo.com/tools/mobile-friendly/

If you enter any URL to analyze, (a mobile friendly testing tool) after it has all finished I want to save the page in single file.
(I can add up to 50 URLs in 1 go to save

Problem is Gildas, they have a column called 'SCREENSHOT' and when you click on it, it saves a small image of the URL webpage, which is brilliant.
Single file is not saving this. :-(

Is there any way around this please?
Or can single file be 'tweaked' so it can save this as a std file/save?

Hope you can advise

Many thanks Gildas
Still loving your addon / plugin :-)
Nosebag

**Comment by gildas-lormeau** [comment]
See #513
