### ISSUE TITLE
no more able to grap images or scripts locally present on the disk of the PC

### ISSUE THREAD

**Issue by jeanluc-grimault** [gildas-lormeau/SingleFile#517]
Hello
This bug was not present with previous Firefox releases.
With new Firefox releases, local images or local scripts are no more taken into account by SingleFile.
exemple   " img src="New-image.png"    ,    with  "New-image.png "present as a file in the same directory of the html page on the PC is not taken into account by SingleFile.
In the code of the page issued by SingleFile, the result is :   "img src=data:null;base64,"
The sole possibility to work around this is to install a small web server on the PC and in this case the image is well included in the resulting html file. But this is very cumbersome to use such a local http server.
It would be very good that local ressources could be taken into account as in the past.
Thank you in advance. Jean-Luc

**Comment by gildas-lormeau** [comment]
You're right. It's unfortunately a recent regression in Firefox due to a security issue. There is a note about this in the known issues (https://github.com/gildas-lormeau/SingleFile#known-issues):

> When processing a page from the filesystem, external resources (e.g. images, stylesheets, fonts etc.) will not be embedded into the saved page. You can find more info about this bug [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1644488). This bug has been closed by Mozilla as "WontFix".

**Comment by gildas-lormeau** [comment]
I'm closing this issue because there's nothing I can do to fix it.
