### ISSUE TITLE
Possibility to proceed closed shadowRoot in Firefox

### ISSUE THREAD

**Issue by serj-kzv** [gildas-lormeau/SingleFile#518]
As I understood there is no functionality to proceed [closed Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/mode) in the **SingleFile** addon. I went though the SingleFile code and **didn't found** how **"closed"** Shadow DOM is proceeding.

In Mozilla Firefox there is special Web Extension API to work with the closed Shadow DOM. It is [openOrClosedShadowRoot](https://developer.mozilla.org/en-US/docs/Web/API/Element/openOrClosedShadowRoot) property.
***
**Note.** That there is a mistake in the function name in the Mozilla documentation. The right variant is _openOrClose**d**ShadowRoot_ with **d** letter.
![image](https://user-images.githubusercontent.com/22834344/96234891-ba523380-0fa2-11eb-8f3f-5097de90b37e.png)
***
I wrote a small example to show how to use it. The code patches `querySelectorAll` to let it works with **closed** Shadow DOM. I don't suggest you use it, it is just an example and you can use it to check if it is work at all (I checked it).
```js
(() => {
    const patchQuerySelectorAll = instance => {
        (function (querySelectorAll) {
            // if browser is Chrome then we open Shadow DOM because there is no openOrClosedShadowRoot
            // we will set all Shadow DOMs to opened mode that is why shadowRoot will works for every Shadow DOM
            const openOrClosedShadowRoot = typeof chrome !== 'undefined' ? 'shadowRoot' : 'openOrClosedShadowRoot';

            instance.prototype.querySelectorAll = function () {
                const nodes = Array.from(querySelectorAll.apply(this, arguments));
                console.log('nodes before querySelectorAll patching', nodes);
                const selector = arguments[0];

                for (let i = 0; i < nodes.length; i++) {
                    const node = nodes[i];
                    const shadowRoot = node.openOrClosedShadowRoot || node.shadowRoot;

                    if (shadowRoot) {
                        nodes.splice(i + 1, 0, ...Array.from(shadowRoot.querySelectorAll('*')));
                    }
                }

                return nodes.filter(node => node.matches(selector));
            };
        })(instance.prototype.querySelectorAll);
    };
    [Element, Document].forEach(instance => patchQuerySelectorAll(instance));
})();
```
So what I suggest is to replace all `element.shadowRoot` by something like this
```js
// Check if it is Chrome because Chrome doesn't have the feature.
const openOrClosedShadowRoot = typeof chrome !== 'undefined' ? 'shadowRoot' : 'openOrClosedShadowRoot';
element[openOrClosedShadowRoot]; // It is like a element.shadowRoot
```

Additionally I can suggest an option to force a browser to use **opened** Shadow DOM anytime when a site try to use **closed** Shadow DOM. You can see an example of this in [shadow-dom-opener](https://github.com/serj-kzv/shadow-dom-opener) addon.
```js
// For Chrome
// You need to set all closed Shadow DOM to opened mode because if browser is Chrome then we open Shadow DOM because there is no openOrClosedShadowRoot
// inject script that opens all Shadow DOM nodes
if (typeof chrome !== 'undefined') {
	const script = document.createElement('script');
	script.async = false;
	script.src = browser.runtime.getURL('./user.js');
	(document.head || document.documentElement).appendChild(script);
	script.remove();
}

// the script that opens all Shadow DOM nodes
// user.js that contents <script> tag
(function (attachShadow) {
	Element.prototype.attachShadow = function () {
		const opened = 'open';

		if (arguments[0].mode !== opened) {
			arguments[0].mode = opened;
		}

		return attachShadow.apply(this, arguments);
	};
})(Element.prototype.attachShadow);
```

**Comment by serj-kzv** [comment]
Note that a recursion almost always is a bad idea and it you almost always can replace a recursion by `stack`+`loop` that is why you see the code in my example
```js
nodes.splice(i + 1, 0, ...Array.from(shadowRoot.querySelectorAll('*')));
```

**Comment by serj-kzv** [comment]
Also I used the way in my addon, you can see a code here https://github.com/serj-kzv/spellcheck-dictionary-configurer/blob/1e82d260d3e91321b9b0441d4300fc04e01f4e86/src/lib/web/elementMutator/proceedAllNodesFn.js

**Comment by gildas-lormeau** [comment]
Thank you very much @serj-kzv for this detailed issue! I implemented your suggestion. I wasn't aware of the existence of this property and I did not want to hook Element#attachShadow. I decided to use the statement `shadowRoot = element.openOrClosedShadowRoot || element.shadowRoot` everywhere it was needed.

**Comment by gildas-lormeau** [comment]
@serj-kzv FYI, Chrome will also expose the API `chrome.dom.openOrClosedShadowRoot(element)` (see https://chromium.googlesource.com/chromium/src/+/fe6e27d68a44c714dcce906749390378ede7d423).
