### ISSUE TITLE
Add automatically trigger "click" based on URL rules

### ISSUE THREAD

**Issue by dnknn** [gildas-lormeau/SingleFile#520]
Now, to save the page, the essential step is:  you must click (.etc) 👇
![2010_19031132](https://user-images.githubusercontent.com/10995302/96377536-d16a6e80-11b8-11eb-99f1-43400fb4759c.png)
So now, recommended to add automatically trigger "click" based on URL rules ?
Please see the explanation below: 

yes, For SingleFile itself,, it is absurd to automatically click to save.
But it is very useful in linking other tools/API/extensions to cooperate with each other, and it can achieve automation effects.

Flow example: [Stylus](https://chrome.google.com/webstore/detail/clngdbkpkpeebahjckkjfobafhncgmne) &ensp;([Repository](https://github.com/openstyles/stylus/))   is an extension of CSS style,
It can apply styles based on URL-RegExp matching rules.

<details>
<summary>Details</summary>

![2010_19032950](https://user-images.githubusercontent.com/10995302/96377916-5ce4ff00-11bb-11eb-93ea-93584617678e.png)

</details>

As long as the URL ends with `#SingleFile`, the style will be automatically applied (Specially used for SingleFile save-page style).  
`.*#SingleFile` has no effect on the URL. So can use Bookmarklet (can also be used in omnibox)

`javascript:window.open(location.href+'#SingleFile')`

<details>
<summary>Details</summary>

![2010_19033719](https://user-images.githubusercontent.com/10995302/96378094-691d8c00-11bc-11eb-88dd-47824cc320dc.png)

</details>

then after, just click Bookmarklet or use omnibox-key(sf) to automatically open a specific URL.

After opening `location.href#SingleFile`, Stylus can automatically apply styles to it, but SingleFile cannot automatically (That is the problem raised at the beginning of this issue. )

So now, recommended to add automatically trigger "click" based on URL rules ?

Yes, no one on a normal page would want it to be SingleFile automatically,  It must be a homemade URL, so URL rules matching, must support RegExp, because only RegExp can achieve accurate URL matching.

Purpose of this function: Let SingleFile and other(e.g. Stylus) be automated together.

Yes, this function, for SingleFile, only reduces the action of one click.

**Comment by gildas-lormeau** [comment]
This feature already exists but is not necessarily easy to configure. Here is the procedure to follow:
 - create a new profile in the options page and name it `Auto-save`
 - go to a website you would like to save automatically and select in the context menu `Select the profile of the current rule > Auto-save`
 - go to the options page of SingleFile and click on `Auto-settings rules`
 - check the option `Display 'Auto-save profile' column` below the table (2nd option)
 - in the table, type `*` in the URL input, set "Auto-save profile" to `Disabled`, and press the `+` button at the right
 - enable the auto-save in SingleFile by selecting `Auto-save > Auto-save all tabs`

Now SingleFile will save automatically the sites you will add by selecting in the context menu `Select the profile of the current rule > Auto-save`.

I attached an example of configuration where pages on github.com are automatically saved. Do not forget to enable the auto-save if you want to test it.
[singlefile-settings-example.zip](https://github.com/gildas-lormeau/SingleFile/files/5398159/singlefile-settings-example.zip)

**Comment by dnknn** [comment]
Wow, it looks a bit complicated (confusing). I have been researching and testing for a long time, and I probably know the meaning, but I haven't fully understood it yet. and I don’t have time to interact with `Stylus`.  

Now there are 2 questions for auto-save.
👇 ON it, but not work for autoSave.
![2010_19060619](https://user-images.githubusercontent.com/10995302/96386929-37fb8680-11d1-11eb-8071-01d42e4083a5.png)

What is the syntax format for using RegExp in the `.JSON` file?
```
  "rules": [
    {
      "url": "github.com",
......
    },
```
How do I make it as a RegExp, e.g. `^https?://.+/.*#SingleFile$`  and `/` need to be escaped into `\/` ? 


---

**Comment by gildas-lormeau** [comment]
Isn't `regexp:#SingleFile$` sufficient?

**Comment by dnknn** [comment]
> Isn't `regexp:#SingleFile$` sufficient?


I don’t understand what you said `regexp:#SingleFile$`, where to put it and how to use it.

What I mean is that in a JSON file, similar to the following syntax, how to become RegExp?
` "url": "github.com"`  become to like this👉` "url": "^https?://.+/.*#SingleFile$"`

**Comment by gildas-lormeau** [comment]
I'm referring to the syntax to use a RegExp... It's (briefly) documented BTW in the help page.

**Comment by dnknn** [comment]
` "url": "github.com"`   `github.com` not a RegExp, hot to become as `^https?://github.com/\d+`

**Comment by gildas-lormeau** [comment]
You just have to prefix your string with `regexp:`, i.e. "url": "regexp:^https?://.+/.*#SingleFile$", or more simply "url": "regexp:#SingleFile$".

**Comment by dnknn** [comment]
`"url": "github.com"` 👉 `"url": "regexp:^https?://.+/.*#SingleFile$"` right?

**Comment by dnknn** [comment]
@gildas-lormeau  Hi, can you help me?

- This is the javascript code you provided in https://github.com/gildas-lormeau/SingleFile/issues/493#issuecomment-696966162

<details>
<summary>How to add `window.open(location.href+'#SingleFile')` based on this script</summary>


```
// ==UserScript==
// @name     [SingleFile] Display prompt to enter the title
// @description  How to add `window.open(location.href+'#SingleFile')` based on this script
// @version  1
// @grant    none
// ==/UserScript==
{
    let title;

    dispatchEvent(new CustomEvent("single-file-user-script-init"));

    addEventListener("single-file-on-before-capture-request", async event => {
        title = document.title;
        const newTitle = prompt("Enter a title", title);
        if (newTitle != null) {
            document.title = newTitle;
        }
    });

    addEventListener("single-file-on-after-capture-request", () => {
        if (title != null) {
            document.title = title;
        }        
    });

}
```

</details>

---

- I want to achieve automation like this:  
Before saving SingleFile, first open `window.open(location.href+'#SingleFile') `, and then (`timeout`) run the above script code.

---

- Tampermonkey cannot use `window.open()` directly,  Tampermonkey uses its own API, i.e. [`GM_openInTab`](https://www.tampermonkey.net/documentation.php?ext=dhdg#GM_openInTab)
```
// ==UserScript==
...
// @grant		GM_openInTab

// ==/UserScript==
....
GM_openInTab(location.href + '#SingleFile' ,false);  // ,false: Do not open a new tab in the background
...

```

---
So, I want to ask you how to merge the above 2 javascript codes together, Then add a `timeout` ,
i.e.  after `GM_openInTab()`  `500ms` , then start your code.
Adding a `delay function` can ensure that the 🅲🆂🆂 styles after  `GM_openInTab()` can be injected correctly.

I don't understand javascript code and sorry for my English... can you understand the meaning to help me?    --- Sincere regards! Thanks!

**Comment by gildas-lormeau** [comment]
Use instead `history.pushState(null, null, "#SingleFile")`.

**Comment by dnknn** [comment]
hi @gildas-lormeau , Thanks, but I don't understand at all, can you help me post the code completely?

**Comment by gildas-lormeau** [comment]
I think I did not understand your question. I guess you need a `if`.
```js
if (location.hash == "#SingleFile") {


  let title;
  
  dispatchEvent(new CustomEvent("single-file-user-script-init"));
  
  addEventListener("single-file-on-before-capture-request", async event => {
      title = document.title;
      const newTitle = prompt("Enter a title", title);
      if (newTitle != null) {
          document.title = newTitle;
      }
  });
  
  addEventListener("single-file-on-after-capture-request", () => {
      if (title != null) {
          document.title = title;
      }        
  });  


} else {
  GM_openInTab(location.href + '#SingleFile' ,false);
}
```

**Comment by gildas-lormeau** [comment]
If you want a timeout before saving the page, set it in the options, there is an option for that.

**Comment by dnknn** [comment]
> I think I did not understand your question

The purpose is to make `Stylus` (a extension of CSS-style container manager) and `SingleFile` interact with each other.

> Since the two extensions cannot communicate directly (unless Stylus can develop linkage with SingleFile)

- So I can only achieve this in disguise, using a specific URL. The page style of this characteristic URL is used for the specific CSS saved by SingleFile.

![urlCSS](https://user-images.githubusercontent.com/10995302/97235335-9a7e0380-181d-11eb-8114-66e54b77d43f.gif)


👆 See this gif, you should be able to understand the specific meaning, 
All in all, it means that before saving with SingleFile, a specific CSS style is automatically applied before being saved.

- Based on the above, I want to open a specific URL before saving the SingleFile, this URL will apply a specific CSS style, and finally trigger the saving of the SingleFile.

To achieve this effect, need to add a script code that opens a specific URL in advance in the Tampermonkey script.

**Comment by dnknn** [comment]
No,   `if (location.hash == "#SingleFileSaveCss") {....}`    your code is not working at all,

**Comment by dnknn** [comment]
I use a diagram, it should be very clearer.

![2010_27064545](https://user-images.githubusercontent.com/10995302/97236416-124d2d80-1820-11eb-9ea6-9547b2570b5f.png)

**Comment by dnknn** [comment]
I use a diagram, it should be very clearer.

![2010_27065008](https://user-images.githubusercontent.com/10995302/97236730-b1722500-1820-11eb-86de-3cb86f519cc4.png)

**Comment by dnknn** [comment]
@gildas-lormeau  

> I think I did not understand your question

The purpose is to make `Stylus` (a extension of CSS-style container manager) and `SingleFile` interact with each other.


- So I can only achieve this in disguise, using a specific URL. The page style of this characteristic URL is used for the specific CSS saved by SingleFile.

specific styles for save-page
![urlCSS](https://user-images.githubusercontent.com/10995302/97235335-9a7e0380-181d-11eb-8114-66e54b77d43f.gif)

---
specific styles applied to saved-page
![urlCSS2](https://user-images.githubusercontent.com/10995302/97238211-d2884500-1823-11eb-8202-9e5151c42d96.gif)


👆 for 2 gifs above,  

   | Called  |    
 ---  |  :---:  | ---  | 
`http://foo.com/test`  |  `A`  |  (normal page)  
 `http://foo.com/test#SingleFileSaveCss`  |  `B`   | (specific page) 

-  Now, First open `B` **manually**, and then SingleFile to save `B`, right?

- Therefore, it is hoped that after running the **save command** of SingleFile, the Tampermonkey script can **automatically** open `B` and then save `B`.

- Note:  SingleFile saves  the auto-opened page, i.e. save `B`  i.e. save the `location.href+'#...'` page.

<details>
<summary>Details</summary>

you should be able to understand the specific meaning, 
All in all, it means that before saving with SingleFile, a specific CSS style is automatically applied before being saved.

- Based on the above, I want to open a specific URL before saving the SingleFile, this URL will apply a specific CSS style, and finally  save the opened  URL page (So that specific CSS can be applied).

To achieve this effect, need to add a script code that opens a specific URL in advance in the Tampermonkey script.

</details>

**Comment by dnknn** [comment]
@gildas-lormeau  

> I think I did not understand your question

The purpose is to make `Stylus` (a extension of CSS-style container manager) and `SingleFile` interact with each other.


- So I can only achieve this in disguise, using a specific URL. The page style of this characteristic URL is used for the specific CSS saved by SingleFile.

　　　　specific styles for save-page
![urlCSS](https://user-images.githubusercontent.com/10995302/97235335-9a7e0380-181d-11eb-8114-66e54b77d43f.gif)

---
　　　　specific styles applied to saved-page
![urlCSS2](https://user-images.githubusercontent.com/10995302/97238211-d2884500-1823-11eb-8202-9e5151c42d96.gif)


👆 for 2 gifs above,  

   | Called  |    
 ---  |  :---:  | ---  | 
`http://foo.com/test`  |  `A`  |  (normal page)  
 `http://foo.com/test#SingleFileSaveCss`  |  `B`   | (specific page) 

-  Now, First open `B` **manually**, and then SingleFile to save `B`, right?

- Therefore, it is hoped that after running the **save command** of SingleFile, the Tampermonkey script can **automatically** open `B` and then save `B`.

- Note:  SingleFile saves  the auto-opened page, i.e. save `B`  i.e. save the `location.href+'#...'` page.


---
I use a diagram, it should be very clearer.

Or put it this way, don’t `... newTitle = prompt("Enter a title", title) .... ` these function.
Just press `Alt+Shift+S` to  `GM_openInTab ( location.href + '#SingleFileSaveCss' ,false)` ,and then SingleFile-Save this `location.href + '#SingleFileSaveCss'` page.

![2010_27065202](https://user-images.githubusercontent.com/10995302/97236833-ef6f4900-1820-11eb-9e66-0b681494a34b.png)

---


<details>
<summary>Details</summary>

you should be able to understand the specific meaning, 
All in all, it means that before saving with SingleFile, a specific CSS style is automatically applied before being saved.

- Based on the above, I want to open a specific URL before saving the SingleFile, this URL will apply a specific CSS style, and finally  save the opened  URL page (So that specific CSS can be applied).

To achieve this effect, need to add a script code that opens a specific URL in advance in the Tampermonkey script.

</details>

**Comment by dnknn** [comment]
@gildas-lormeau  Hi~
The purpose is to make `Stylus` (a extension of CSS-style container manager) and `SingleFile` interact with each other.  So I can only achieve this in disguise, using a specific URL. 

- 　　special css styles auto applied-to for `#special` page, but definitely not for normal page.
![urlCSS](https://user-images.githubusercontent.com/10995302/97235335-9a7e0380-181d-11eb-8114-66e54b77d43f.gif)

---

- 　　The ultimate goal: SingleFile to save this `#special` page with special CSS styles applied.
![urlCSS2](https://user-images.githubusercontent.com/10995302/97238211-d2884500-1823-11eb-8202-9e5151c42d96.gif)


👆 for 2 gifs above is by manual method.

  page/URL | Called  |    
 ---  |  :---:  | ---  | 
`http://foo.com/test`  |  `A`  |  (normal page)  
 `http://foo.com/test#SingleFileSaveCss`  |  `B`   | (specific page) 

-  Now, First open `B` **manually**, and then SingleFile to save `B`, right?

- Therefore, it is hoped that **after run** the **save command** of SingleFile, the Tampermonkey script can **automatically open**  `B`  and then save `B`. (i.e. After auto-open `B`, it has nothing to do with `A`)

Note:  SingleFile saves  the auto-opened page, i.e. save `B`  i.e. save the `location.href+'#...'` page.

- One sentence: After triggering the save command of SingleFile, then auto-open `B` page `&&`  save `B` page

---
I use a diagram, it should be very clearer.

- Or put it this way, don’t `... newTitle = prompt("Enter a title", title) .... ` these function.
Just press `Alt+Shift+S` to  `GM_openInTab ( location.href + '#SingleFileSaveCss' ,false)` ,and then SingleFile-Save this `location.href + '#SingleFileSaveCss'` page.

- note:  Use `history.pushState(null, null, "#hash...")` is also better, I just found this API you mentioned, It open on the current page and can go back.

![2010_27120730](https://user-images.githubusercontent.com/10995302/97256057-0592fe80-184d-11eb-9130-1b3511d903cb.png)


---


<details>
<summary>Details</summary>

you should be able to understand the specific meaning, 
All in all, it means that before saving with SingleFile, a specific CSS style is automatically applied before being saved.

- Based on the above, I want to open a specific URL before saving the SingleFile, this URL will apply a specific CSS style, and finally  save the opened  URL page (specific CSS be applied).


</details>

**Comment by dnknn** [comment]
Hi~ @gildas-lormeau   Can you help me see it again?  now, this time it is very very simple and clear, which should make the function pretty much self-explanatory.

https://github.com/gildas-lormeau/SingleFile/issues/520#issuecomment-716974979

**Comment by gildas-lormeau** [comment]
Please follow this procedure:
1. Import the settings attached, nothing fancy, it's the same settings I suggested you in the previous issue
2. Copy the script below in TamperMonkey, it's a slightly different script that open the page with `#SingleFileSaveCss` if and only if you press Ctrl+S (without Shift)
```js
// ==UserScript==
// @name     Autosave script
// @version  0.1
// @grant     GM_openInTab
// @match    https://*/*
// @match    http://*/*
// @run-at    document-start
// ==/UserScript==

if (location.hash == "#SingleFileSaveCss") {
  let title;
  dispatchEvent(new CustomEvent("single-file-user-script-init"));
  addEventListener("single-file-on-before-capture-request", async event => {
    title = document.title;
    const newTitle = prompt("Enter a title", title);
    if (newTitle != null) {
      document.title = newTitle;
    }
  });
  addEventListener("single-file-on-after-capture-request", () => {
    if (title != null) {
      document.title = title;
    }
  });
} else {
  addEventListener("keydown", () => {
    if (event.key.toLowerCase() == "s" && event.ctrlKey) {
      event.preventDefault();
      GM_openInTab(location.href + '#SingleFileSaveCss', false);
    }
  });
}
```
3. Enable Auto save > Autosave all tabs in the context menu of SingleFile
4. Open a page in a new tab and press Ctrl+S

That's the best I can propose you.

[singlefile-settings-autosave.zip](https://github.com/gildas-lormeau/SingleFile/files/5448389/singlefile-settings-autosave.zip)

**Comment by dnknn** [comment]
@gildas-lormeau Thanks very much. The method you provided is a bit messy to me, I'll look into.
Will it automatically open the #hash page to automatically apply special CSS ,then save that page?

**Comment by gildas-lormeau** [comment]
Yes it should. You can adjust the delay in the settings, see `Auto-save > auto-save waiting delay after page load`. By default, it's 1 second.

**Comment by dnknn** [comment]
yes, I used another browser to test separately, which perfectly matches what you said.

![2010_28071224](https://user-images.githubusercontent.com/10995302/97371743-f5326080-18ec-11eb-9f5d-c74d29b0cc4c.png)

Now there is a question, can  keep the source  URL of the source page?

**Comment by gildas-lormeau** [comment]
It's not possible. You would have to code a separate script (run from the command line interface) to process your save files. However you can display the original URL in the infobar.

1. In the TamperMonkey script, replace
```js
GM_openInTab(location.href + "#SingleFileSaveCss", false);
```
with
```js
window.open(location.href + '#SingleFileSaveCss');
```
2. In the settings of SingleFile, set `User interface > template of the infobar content` to `{url-referrer}`

**Comment by dnknn** [comment]
![2010_28073614](https://user-images.githubusercontent.com/10995302/97373157-4728b580-18f0-11eb-87c2-a8f8cff7e9f0.png)
invalid.   I even removed `// @grant    GM_openInTab`  , also invalid.
`window.open(location.href + "#SingleFileSaveCss"); `  also open in the new tab.
Does it need to be replaced with:  `history.pushState(null, null, location.href+"#SingleFileSaveCss")` ?

**Comment by dnknn** [comment]
![2010_28073614](https://user-images.githubusercontent.com/10995302/97373157-4728b580-18f0-11eb-87c2-a8f8cff7e9f0.png)
invalid.   I even removed `// @grant    GM_openInTab`  , also invalid.
`window.open(location.href + "#SingleFileSaveCss"); `  also open in the new tab.
Does it need to be replaced with:  `history.pushState(null, null, location.href+"#SingleFileSaveCss");` ?

ps: I tested `history.pushState(...);`  also invalid,   It becomes unable to popup the title-edit...

**Comment by gildas-lormeau** [comment]
I'm sorry, I don't know why the procedure I described does not work for you. You don't have to use `history.pushState`, just follow the procedure. Here is the script:
```js
// ==UserScript==
// @name     Autosave script
// @version  0.1
// @grant		 GM_openInTab
// @match    https://*/*
// @match    http://*/*
// @run-at   document-start
// ==/UserScript==

if (location.hash == "#SingleFileSaveCss") {

  let title;
  dispatchEvent(new CustomEvent("single-file-user-script-init"));

  addEventListener("single-file-on-before-capture-request", async event => {
    title = document.title;
    const newTitle = prompt("Enter a title", title);
    if (newTitle != null) {
      document.title = newTitle;
    }
  });

  addEventListener("single-file-on-after-capture-request", () => {
    if (title != null) {
      document.title = title;
    }
  });


} else {
  addEventListener("keydown", () => {
    if (event.key.toLowerCase() == "s" && event.ctrlKey) {
      event.preventDefault();
      window.open(location.href + '#SingleFileSaveCss');
    }
  });
}
```

**Comment by dnknn** [comment]
sorry...sorry...!   it's my fault!  I always think of <a> ,  did not pay attention to the <span>
![2010_28082320](https://user-images.githubusercontent.com/10995302/97375864-dfc23400-18f6-11eb-8555-f91a67e35699.png)
`{url-referrer}` is not a link , right?

**Comment by dnknn** [comment]
Is the last requested improvement achievable?
Currently the script only for `Ctrl+S` `||`  `#hash` pages, right?

![image](https://user-images.githubusercontent.com/10995302/97377341-c327fb00-18fa-11eb-9765-aa92387d3d91.png) 👈 click TrayIcon  can not popup title-edit.
![2010_28085848](https://user-images.githubusercontent.com/10995302/97377818-d7202c80-18fb-11eb-9a87-e388f0276df7.png)


So, I want to achieve like:  click TrayIcon (i.e. manual save command of SingleFile) can popup title-edit.

- `Ctrl+S` : the current script and SingleFile auto-save
-  `click TrayIcon`:   only to `....const newTitle = prompt("Enter a title", title);....`  not auto open the #hash page.

In this case (which is no #hash page), it will not affect manual saving.

**Comment by dnknn** [comment]
@gildas-lormeau Thank you so much for your kind help!  

Is the last requested improvement achievable?
Currently the script only for `Ctrl+S` `||`  `#hash` pages, right?

![image](https://user-images.githubusercontent.com/10995302/97377341-c327fb00-18fa-11eb-9765-aa92387d3d91.png) 👈 click TrayIcon  can not popup title-edit.
![2010_28085848](https://user-images.githubusercontent.com/10995302/97377818-d7202c80-18fb-11eb-9a87-e388f0276df7.png)


So, I want to achieve like:  click TrayIcon (i.e. manual save command of SingleFile) can popup title-edit.

- `Ctrl+S` : the current script and SingleFile auto-save
-  `click TrayIcon`:   only to `....const newTitle = prompt("Enter a title", title);....`  not auto open the #hash page.

In this case (which is no #hash page), it will not affect manual saving.

**Comment by dnknn** [comment]
@gildas-lormeau Thank you so much for your kind help!  

Is the last requested improvement achievable?
Currently the script only for `Ctrl+S` `||`  `#hash` pages, right?

![image](https://user-images.githubusercontent.com/10995302/97377341-c327fb00-18fa-11eb-9765-aa92387d3d91.png) 👈 click TrayIcon  can not popup title-edit.
![2010_28085848](https://user-images.githubusercontent.com/10995302/97377818-d7202c80-18fb-11eb-9a87-e388f0276df7.png)


So, I want to achieve like:  click TrayIcon (i.e. manual save command of SingleFile) can popup title-edit.

- `Ctrl+S` : the current script and SingleFile auto-save
-  `click TrayIcon`:   only to `....const newTitle = prompt("Enter a title", title);....`  not auto open the #hash page.

In this case (which is no #hash page), it will not affect manual saving.

customize #hash page (write CSS styles for it) : Suitable for a little commonly used pages.
Otherwise, other random normal pages still need to be saved manually or temporarily.

**Comment by gildas-lormeau** [comment]
I'm sorry but it's not possible technically speaking.

**Comment by dnknn** [comment]
> I'm sorry but it's not possible technically speaking.

Then I will return to the traditional method of URL matching, let 2 scripts together, this seems to be possible, wdyt?


Script 1  `// @match    */*`

<details>
<summary>Script 1</summary>

```
// ==UserScript==
// @name     Autosave script
// @version  0.1
// @match    https://*/*
// @match    http://*/*
// @run-at   document-start
// ==/UserScript==
if (location.hash == "#SingleFileSaveCss") {
  let title;
  dispatchEvent(new CustomEvent("single-file-user-script-init"));
  addEventListener("single-file-on-before-capture-request", async event => {
    title = document.title;
    const newTitle = prompt("Enter a title", title);
    if (newTitle != null) {
      document.title = newTitle;
    }
  });
  addEventListener("single-file-on-after-capture-request", () => {
    if (title != null) {
      document.title = title;
    }
  });
} else {
  addEventListener("keydown", () => {
    if (event.key.toLowerCase() == "s" && event.ctrlKey) {
      event.preventDefault();
      window.open(location.href + "#SingleFileSaveCss");
    }
  });
}
```

</details>


Script 2   `// @exclude	/.*#SingleFileSaveCss$/`

<details>
<summary>Script 2</summary>

```
// ==UserScript==
// @name     [SingleFile] Display prompt to enter the title
// @version  1
// @match  */*
// @exclude	/.*#SingleFileSaveCss$/
// @grant    none
// ==/UserScript==
{
    let title;

    dispatchEvent(new CustomEvent("single-file-user-script-init"));

    addEventListener("single-file-on-before-capture-request", async event => {
        title = document.title;
        const newTitle = prompt("Enter a title", title);
        if (newTitle != null) {
            document.title = newTitle;
        }
    });

    addEventListener("single-file-on-after-capture-request", () => {
        if (title != null) {
            document.title = title;
        }        
    });

}
```

</details>
