### ISSUE TITLE
Fails to zoom back in on certain pages

### ISSUE THREAD

**Issue by fletcherhaz** [gildas-lormeau/SingleFile#525]
**Describe the bug**
`window.dispatchEvent` is not properly working on this page: [https://pubs.rsc.org/en/content/articlelanding/2020/cc/d0cc90441d#!divAbstract](url) Notably, this is an `Event` instead of a `UIEvent` as the line about it is. I'm opening an issue because I'm not sure what the reasoning behind the difference is, but on my build, switching to a UIEvent works just fine. I have not tested other browsers though nor do I know of another website that produces the same behavior.

```
Uncaught TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at dispatchEvent (content-hooks-frames-web.js:52)
    at loadDeferredImagesStart (content-hooks-frames-web.js:154)
    at content-hooks-frames-web.js:66
    at nrWrapper (d0cc90441d:13)
```

**To Reproduce**
1. Go to [https://pubs.rsc.org/en/content/articlelanding/2020/cc/d0cc90441d#!divAbstract](url)
2. Click on SingleFile to save the page with default settings (`loadDeferredImagesKeepZoomLevel` is false).
3. Open the JS console to see the error

**Expected behavior**
Should properly zoom back to normal by dispatching the event.

**Environment**
 - OS: macOS Catalina 10.15.7
 - Browser: Chrome 86.0.4240.80
 - Version: SingleFile 1.18.20

**Comment by gildas-lormeau** [comment]
Thank you for having reported this issue. Actually this page does not like fake event. It looks like it contains a library that intercept "resize" events and caused this issue. The JS error can be reproduced by running this code in the console
```js
const event = new Event("resize");
dispatchEvent(event)
```
To fix it, I added some code to catch errors when dispatching the "resize" and the "scroll" event.

**Comment by fletcherhaz** [comment]
Fantastic! Thank you!
