### ISSUE TITLE
Missing opening header tag in output

### ISSUE THREAD

**Issue by ngirard** [gildas-lormeau/SingleFile#526]
Using v1.18.23 on Firefox 82.0 /Ubuntu 20.04.

The generated output is missing an opening `<header>` tag, breaking my toolchain.

Cheers from Paris ;-)

**Comment by gildas-lormeau** [comment]
It's a feature. By default, SingleFile tries to reduce the size of the HTML page by removing quotes, unnecessary white-space characters and optional tags, as specified here: https://html.spec.whatwg.org/multipage/syntax.html#optional-tags.
You can disable this feature by unchecking the setting "HTML content > compress HTML content".

Cheers from Rennes ;-)

**Comment by gildas-lormeau** [comment]
So, I guess I can close this issue. Feel free to comment or reopen it.
