### ISSUE TITLE
Unified improvement: extension shortcut can support for multi-selected-tabs

### ISSUE THREAD

**Issue by dnknn** [gildas-lormeau/SingleFile#527]
On the tab bar of the browser, you can holding `Ctrl` / `Shift` for free multi-selected-tabs , i.e. multiple highlighted tabs. This feature is very practical.
![multi-selected-tabs](https://user-images.githubusercontent.com/10995302/97033821-82488300-1596-11eb-9d23-ce772bfccb37.gif)

----

![2010_24014852](https://user-images.githubusercontent.com/10995302/97036922-20d6e300-159b-11eb-968e-fc3c9ebb4ce8.png) or click TrayIcon ![2010_24021359](https://user-images.githubusercontent.com/10995302/97039182-998b6e80-159e-11eb-843e-1d476c3625bb.png)
.
Above is all can supported it, but  the following is very inconsistent and imperfect, i.e. ▼

### `chrome://extensions/shortcuts#:~:text=Save the current tab or the selected content`
↑ This URI link can be directly opened and jumped to highlight the destination(Chrome⁸¹ᐩ valid)

It cannot working with save `multi-selected-tabs` , so this feels like a fly in the ointment.

---
- ##  Expected behavior: / Implementation plan:
　　　　Add: can also working with multi-selected-tabs.
　　　　Change: The wording description is updated to " Save the selected tabs or the selected content "
　　　　Note: If `Save the selected tabs` and `the selected content` exist at the same time, `Save the selected tabs` has priority. The reason is simple, no people will holding `Ctrl/Shift` on the tab bar aimlessly.

Use/Purpose: Use hotkey to quickly save multiple selected tabs, and other possibilities.

----
Example demo of the extension-shortcut-hotkey of other extensions that support multi-selected-tabs.

- better-onetab
https://chrome.google.com/webstore/detail/eookhngofldnbnidjlbkeecljkfpmfpg
https://github.com/cnwangjie/better-onetab

- TabCopy
https://chrome.google.com/webstore/detail/micdllihgoppmejpecmkilggmaagfdmb

**Comment by dnknn** [comment]
the issue update complete, you should be able to understand the meaning!

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. I will eventually implement this feature once it will be available in Firefox.

**Comment by dnknn** [comment]
> I will eventually implement this feature once [Text Fragments](https://web.dev/text-fragments/#text-fragments) will be available in Firefox.

You seem to digress, right?   The question we are discussing is 👇
![2010_24042946](https://user-images.githubusercontent.com/10995302/97051336-90f06380-15b1-11eb-86e7-d1445b3ec6d6.png)
![2010_24043533](https://user-images.githubusercontent.com/10995302/97051789-5f2bcc80-15b2-11eb-9668-23691809ddf8.png)
I still don't know if you understand the specific meaning of this question?

----
I'm not talking about `scroll-to-text-fragment` . about  `scroll-to-text-fragment` that was something I mentioned accidentally, it was a digression. There are 2 more pages to view this information:

https://github.com/WICG/scroll-to-text-fragment
https://wicg.github.io/scroll-to-text-fragment

**Comment by dnknn** [comment]
> I will eventually implement this feature once [Text Fragments](https://web.dev/text-fragments/#text-fragments) will be available in Firefox.

Hi @gildas-lormeau :)
You seem to digress, right?   The question we are discussing is 👇
![2010_24042946](https://user-images.githubusercontent.com/10995302/97051336-90f06380-15b1-11eb-86e7-d1445b3ec6d6.png)
![2010_24043533](https://user-images.githubusercontent.com/10995302/97051789-5f2bcc80-15b2-11eb-9668-23691809ddf8.png)
I still don't know if you understand the specific meaning of this question?

`chrome://extensions/shortcuts#:~:text=Save the current tab or the selected content`

I just use it to get you directly to the destination. There is no problem with this URI itself. The problem is that its corresponding hotkey cannot work on multi-selected-tabs.
So I hope you can make the hotkeys also support multi-selected-tabs, Only after that optimization,, for multi-selected-tabs, the SingleFile experience is exactly the same. 
You can carefully review the problem I said.

----
I'm not talking about `scroll-to-text-fragment` . about  `scroll-to-text-fragment` that was something I mentioned accidentally, it was a digression. There are 2 more pages to view this information:

https://github.com/WICG/scroll-to-text-fragment
https://wicg.github.io/scroll-to-text-fragment

**Comment by dnknn** [comment]
> I will eventually implement this feature once [Text Fragments](https://web.dev/text-fragments/#text-fragments) will be available in Firefox.

Hi @gildas-lormeau :)  You seem to digress, right?   The question we are discussing is 👇
![2010_24042946](https://user-images.githubusercontent.com/10995302/97051336-90f06380-15b1-11eb-86e7-d1445b3ec6d6.png)
![2010_24043533](https://user-images.githubusercontent.com/10995302/97051789-5f2bcc80-15b2-11eb-9668-23691809ddf8.png)
I still don't know if you understand the specific meaning of this question?

`chrome://extensions/shortcuts#:~:text=Save the current tab or the selected content`

I just use it to get you directly to the destination. There is no problem with this URI itself. The problem is that its corresponding hotkey cannot work on multi-selected-tabs.
For example:  use `Alt+Shift+S` is unable to save multi-selected-tabs,  Currently, `Alt+Shift+S` can only be used to save only one tab page.

So I hope you can make the `Alt+Shift+S` also support multi-selected-tabs, Only after that optimization,, for multi-selected-tabs, the SingleFile experience is exactly the same. 
You can carefully review the problem I said.

----
I'm not talking about `scroll-to-text-fragment` . about  `scroll-to-text-fragment` that was something I mentioned accidentally, it was a digression. There are 2 more pages to view this information:

https://github.com/WICG/scroll-to-text-fragment
https://wicg.github.io/scroll-to-text-fragment

**Comment by gildas-lormeau** [comment]
I think I must be a little tired. I will carefully reread your messages and give you an answer.

**Comment by gildas-lormeau** [comment]
It should be implemented. 

If you open new issues, please make them as concise as possible. For example, since SingleFile is referring to selected tabs or selected content in the context menu, you can expect I know what they are and how they work. Using a URL containing a Text Fragment was also not necessary, it just makes the report harder to understand for me.

**Comment by dnknn** [comment]
Okay, sorry, thank you very much!!
