### ISSUE TITLE
Download a site that is linked to your original downloaded oage

### ISSUE THREAD

**Issue by phkc070408** [gildas-lormeau/SingleFile#532]
I don't know if this is the right term, but the ability to download one level down from the original page.

I would like to download a page, and then download some of the links that are one level down from that "top" webpage, and have the link in the homepage changed to that downloaded page that is now stored on my computer.

Example:

I download www.dogs.com to my folder C:/Home and name the page "01"
I download www.dogs.com/dogfood, also to my folder C:/Home and name the page "02A"
I can then change the link on page "01" from www.dogs.com to C:/02A.html

Therefore, when I am offline, I can click on the link in dogs.com and it will take me to the download version of www.dogs.com/dogfood, or what is really C:/02A

**Comment by gildas-lormeau** [comment]
You can do that by running SingleFile from the command line interface. I consider this is the most appropriate way to implement this kind of feature.
You should be able what you want to achieve by installing it, see https://github.com/gildas-lormeau/SingleFile/tree/master/cli, and running the following command:
```
single-file https://www.dogs.com --crawl-links --crawl-inner-links-only crawl-max-depth=1 --crawl-replace-urls
```
By default, SingleFile will use 8 navigators in parallel to crawl the website. This can create a significant workload. To reduce (or increase) this number and the workload, you can use the option `--max-parallel-workers` by adding for example `--max-parallel-workers=2`.

**Comment by gildas-lormeau** [comment]
@phkc070408 any news?

**Comment by gildas-lormeau** [comment]
@phkc070408 I'm closing the issue because I indicated you the procedure to fix it. Feel free to comment or reopen it if necessary.
