### ISSUE TITLE
CLI Download a page that requires Login

### ISSUE THREAD

**Issue by evroza** [gildas-lormeau/SingleFile#535]
We need to save a page that requires authentication. Not sure if it's possible to pass session data to the CLI so that the page at the location we need to save can open succesfully and download. The examples I have seen assume the url passed opens directly and without authentication. Or is there another way to do this?

**Comment by gildas-lormeau** [comment]
If the authentication is done in HTTP, you can use the option `--http-header` to pass HTTP headers, e.g. `--http-header="Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l"`. Otherwise, I need me more technical details on how the authentication work in the page you want to save.

**Comment by evroza** [comment]
So the idea is to be able to handle any kind of authentication since the script is to work with a multitude of sites. The scenario would be something like this, we have navigated to a page using puppeteer and already passed authentication to get to the page that needs to be saved. Now to save the page we can invoke the CLI program and pass it the link to be saved as well as the session entire session data from puppeteer so that the link opens fine.

Already explored writing a chrome extension that calls SingleFile, the problem is to run chrome extensions in puppeteer, it must be running in non-headless mode which will be a problem if we are running it on the server. So the alternative is to include the CLI and invoke it after navigating and logging in using puppeteer, to do this with the CLI means also passing cookies

**Comment by gildas-lormeau** [comment]
Right now, there are no API to do this. However, you could fork SingleFile and insert a function call that would login the user just before this line of code:
https://github.com/gildas-lormeau/SingleFile/blob/master/cli/back-ends/puppeteer.js#L44

**Comment by evroza** [comment]
Thanks @gildas-lormeau I already went with forking and fiddled with things until they worked. Solved
