### ISSUE TITLE
Can no longer save some pages

### ISSUE THREAD

**Issue by jtlpa** [gildas-lormeau/SingleFile#536]
When I try to save a page it sometimes shows a red slash circle. This has happen before, but the incidents were few and far between. Now I and getting the red slash circle a lot of the time.

The issue started after my Debian 10 system updated to Firefox 78.4.0esr (64-bit). Most of the pages that fail to save are located on support.mozilla.org, like this one.

https://support.mozilla.org/en-US/questions/1293658https://support.mozilla.org/en-US/questions/1293658ERS

This maybe a FF issue as there appears to be a host of bug in F78 ESR.

**Comment by gildas-lormeau** [comment]
This is a known issue, see here https://github.com/gildas-lormeau/SingleFile#known-issues. You can edit the list of restricted domains in `about:config` by updating they value of `extensions.webextensions.restrictedDomains`.
