### ISSUE TITLE
cannot download page contents from this page

### ISSUE THREAD

**Issue by NOSEBAG** [gildas-lormeau/SingleFile#537]
Hi there
Cannot download this webpage
https://fonts.google.com/

I scrolled to the bottome slowly, so all lazy loaded fonts would be seen.

But when I try to save, it just wont save the webpage complete with all the different font sytles

I also unchecked,
remove unused fonts, still no joy

I'm using firefox 64bit 82.0.2

Hope you can advise
Many thanks
I was just trying to download the page completely, so I have a full visual list of all google fonts, and could see all the styles etc.

**Comment by gildas-lormeau** [comment]
This website use a dynamic list to display fonts. It means that the JS makes sure that only the visible part of the list is present.

To circumvent this issue, you have to follow this procedure:
 - disable `Images > save deferred images` in SingleFile
 - in the tab displaying a page on fonts.google.com, press F12 and execute in the console the code below:
```js
// this code emulates a very large screen
window.innerHeight = document.querySelector("gf-root").getBoundingClientRect().height
dispatchEvent(new CustomEvent("resize"))
```
- press F12 again to close the developer tools
- once the fonts are loaded, save the page

**Comment by gildas-lormeau** [comment]
@NOSEBAG Do you confirm the procedure I described works for you?

**Comment by gildas-lormeau** [comment]
I'm closing the issue because I cannot do anything more than providing the procedure I described. Feel free to comment it or reopen it.
