### ISSUE TITLE
Cannot Get SingleFile to Run by Calling it With browser.runtime.sendMessage();

### ISSUE THREAD

**Issue by Dalton-Overlin** [gildas-lormeau/SingleFile#538]
Hi, @gildas-lormeau, I would like to first cite your prior advice for calling SingleFile from another extension you gave me here: [](url)https://github.com/gildas-lormeau/SingleFile/issues/515#issuecomment-709617920 

I made those edits to a forked copy of SingleFile that you advised in that above referenced comment. However, rather than calling SingleFile from a separate extension I have added my scripts directly into the forked SingleFile extension. 

The problem is that when I call single file using this command below, that I placed in a background script in the modified SingleFile extension, SingleFile doesn't start saving the current page?

var voila = browser.runtime.sendMessage("{531906d3-e22f-4a6c-a102-8057b88a1a63}", {});

I will attach a zip of the forked SingleFile extension I've been working on. Note, the browser.runtime.sendMessage() command is in the wiredIn.js script that I added as a background script to the forked SingleFile extension. That is where issues are occurring. It seems that the message is being sent, but SingleFile just doesn't do anything. If you could offer any advice on how to fix this issue I would sincerely appreciate it. 

Sincerest regards
[forked-SingleFile-Extension-Files.zip](https://github.com/gildas-lormeau/SingleFile/files/5469924/forked-SingleFile-Extension-Files.zip)

**Comment by gildas-lormeau** [comment]
Hi @Dalton-Overlin 

I you want to fork SingleFile, I recommend to call the SingleFile API directly instead of using the external message API. I attached a project containing the minimum code you need in order to call the SingleFile API *from the background page*. It also handles the download of the page.

The UI is simple, it has a browser button and the script which handles the click is `extension/ui/bg/ui-button.js`, it calls the function `singlefile.extension.core.bg.business.saveTabs()` with the array of selected tabs as parameter.

[sf-mini.zip](https://github.com/gildas-lormeau/SingleFile/files/5471887/sf-mini.zip)

**Comment by Dalton-Overlin** [comment]
Hi, @gildas-lormeau, thanks for the reply. Your code works good, but for my functionality I need there's still an issue. For example, this code below inserts a HTML button into the page that is loaded using a content script and checks every 3 seconds to see if that button was clicked (note: this is just for testing, this is not how the final version of the extension will operate). This way, a content script can initiate the page saving process by communicating with a background script.

Below is code placed in a "content script".
```
var cuizXVI = '1.0'; // Transparency.
var spanXVI = document.createElement('span');
spanXVI.innerHTML = '<button id="KTVX1997PLUSONE" style="position:absolute;bottom:0;right:0;color:black;background-color:green;opacity: ' + cuizXVI + ';z-index: 1000;">A</button>';
document.body.appendChild(spanXVI);

var buttonXVI = document.getElementById("KTVX1997PLUSONE");

buttonXVI.addEventListener("click", function () {
	if (this.innerText == "A") {
		this.innerText = "B";
	}
});
function handleResponse(message) {
  console.log(`Message from the background script:  ${message.response}`);
}
function handleError(error) {
  console.log(`Error: ${error}`);
}
var intervalXVI = setInterval(function () {
	var buttonXVITW = document.getElementById("KTVX1997PLUSONE");
	if (buttonXVITW.innerText == "B") {
		buttonXVITW.innerText = "A";
		var sending = browser.runtime.sendMessage({ greeting: "Alamo"}); /* This interracts with the background script. */
                sending.then(handleResponse, handleError);
		buttonXVITW.innerText = "A";
	}
}, 3000);
```
Next, this code below will be in a "background script" that listens for a message from the above content script. Then, once this below code gets a message from the content script it should initiate SingleFile to start saving the active tab. 

```
function handleMessage(request, sender, sendResponse) {
/*!!!   This is where code should be that can initiate SingleFile to start the page saving process.   !!!*/
sendResponse({response: "Response from background script! "});
}
browser.runtime.onMessage.addListener(handleMessage);
```
So my question, is how can I edit this code below that you pointed out that is in the ui-button.js script, and have it listen for messages from the above "content script"? This way, a content script can communicate with a background script to initiate the page saving process. This way, a content script can check a page for element changes and initiate the page saving process once a desired website element is achieved. 
```
singlefile.extension.ui.bg.button = (() => {
	browser.browserAction.onClicked.addListener(async () => {
		const bg = singlefile.extension.core.bg;
		const tabs = await bg.tabs.get({ currentWindow: true, highlighted: true });
		bg.business.saveTabs(tabs);
	});
	return {};
})();
```
Here below is an illustration of what I am trying to achieve. 
![Untitled Diagram](https://user-images.githubusercontent.com/30564402/97831827-67f56000-1c8e-11eb-8463-5e7020f7dd1a.png)

I apologize for bothering you with this, but I have not been able to figure out how to get my code to work with yours using these means I have outlined above. Since the page saving process will be initiated by a "content script" NOT a user clicking a browser toolbar button. This is why I am having difficulty getting SingleFile to run using these methods. If you could offer any insight on getting these above methods to work with the forked SingleFile you provided I would sincerely appreciate it very much.

**Comment by gildas-lormeau** [comment]
I attached the code that integrates your JS into the project "sf-mini". Globally, here is what I did:
 - I removed the code related to the existing ui
 - I added you code in the file `extension/core./content/content.js` and declared it in the `manifest.json` file as a content script that should run once the page is idle.
 - I added the message handler into `extension/core./bg/messages.js` and `extension/core./bg/business.js` in order to save the tab once the message sent from the content script is received.

[sf-mini.zip](https://github.com/gildas-lormeau/SingleFile/files/5475212/sf-mini.zip)

**Comment by Dalton-Overlin** [comment]
Hey, @gildas-lormeau, thank you so much for your help! What you've done will allow me to achieve what I need too. I have made a repository for this project here: [https://github.com/Dalton-Overlin/SingleFileSelenium](url). The code you provided is wonderful and well-written. I sincerely appreciate your help on this project, and I will make sure to give full accreditation to your help on this. Thanks again.

Sincerest regards

**Comment by gildas-lormeau** [comment]
You're welcome @Dalton-Overlin and thank you for the kind words! I'm glad to hear the code I provided will help you to develop your project. I'm closing this issue but feel free to comment it if necessary. BTW, I guess you know it but SingleFile can be run from the command line and use Selenium (it uses puppeteer by default), see https://github.com/gildas-lormeau/SingleFile/tree/master/cli.
