### ISSUE TITLE
[Feature Request] support for page source ="file:"

### ISSUE THREAD

**Issue by rdmoore6** [gildas-lormeau/SingleFile#54]
I have installed SingleFile on Macintosh Chrome. It works some of the time. Some attempts to use it result in a "download blocked" on the right-hand side of top of screen URI window. Closing the tab and starting over with a new tab seems to solve the problem.

Unfortunately SingleFile does not completely meet my needs. It has one major advantage over the browser command "Save Page As.. " raw HTML. SingleFile saves the current HTML rather than the original HTML. (Macintosh Chrome under some mysterious condition will save the current HTML rather than original). My first problem is that SingleFile only works with HTTP or HTPTPS files. When page source is "file://" SingleFile won't process the page. Perhaps documentation should mention this.

There is one aspect which I consider to be a bug.
Given a link of the form  <a href="#anchorname>text</a> , the link is modified to
<a href="sourcefile#anchorname>text</a>
However this is wrong because the anchorname might not exist in the original file.
IMHO modifying a local link is always wrong.
Macintosh Chrome version: Version 67.0.3396.99 (Official Build) (64-bit)
Cheers,
Roger D. Moore

**Comment by gildas-lormeau** [comment]
The two issues are fixed in 1.2.16. Thanks for your submission!

**Comment by rdmoore6** [comment]
Thanks for your attention. I gone another route converted the current HTML into a screen full of HTML text which can be copied to a text editor and saved there.  For my specific needs, this approach has the added advantage of allowing me to alter some of the HTML in the process such as forcing stand <head> and sometimes changing a specific "style=display:inline”  to "style=display:none”.
/Roger
