### ISSUE TITLE
Nothing happens when clicking SingleFile Addon button 

### ISSUE THREAD

**Issue by niraldmello** [gildas-lormeau/SingleFile#541]
This was working great till 2 months ago. Today when I needed it again it's not working. All my firefox addons work except SingleFile and Save Page WE. My current Firefox Version is 82.0.2 (64-bit)

Please help.

**Comment by gildas-lormeau** [comment]
This might be due to corrupted data in your profile. Did you try to create a new one and see if the problems persists? See here https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Multiple_profiles for more info.

**Comment by gildas-lormeau** [comment]
@niraldmello any news?

**Comment by gildas-lormeau** [comment]
I'm closing this issue because it is not directly related to SingleFile (since you mentioned Save Page WE stopped working too). I think it's probably related to a corrupted profile. Feel free to comment or reopen the issue if necessary.
