### ISSUE TITLE
SingleFile sets "data:null" instead of "data:image/jpg" for <img> src attributes in a certain page

### ISSUE THREAD

**Issue by lkintact** [gildas-lormeau/SingleFile#543]
**To Reproduce**
1. Create a new Firefox account, add SingleFile to it.
2. Go to https://www.culture.ru/materials/139105/zagadki-uzorov-russkikh-rospisei (that's an article about traditional Russian arts).
3. Click on the SingleFile icon in the top-right to save the page.
4. Open the saved file, `Гжель, городецкая, хохломская, жостовская, мезенская роспись, лаковая миниатюра в Федоскино и Палехе. (….html`.
5. Right-click on any of the large images (those displayed three in a row; the first row is just below the `Золотые чаши. Хохломская роспись` text), click on "View Image".
6. The image is opened in a new tab, but displayed as plain text. The image URL starts with `data:null;base64`.

**Expected behavior**
The image should be displayed as a picture. The URL should start with `data:image/jpg;base64`.

**Environment**
 - OS: Windows 10 Home 1803
 - Browser: Firefox 82.0.3 (32-bit)
 - SingleFile version: 1.18.33

**Comment by lkintact** [comment]
Sorry, I now realize the issue is probably caused by the server's not sending the "Content-type" header for the images. So, perhaps, there's nothing that can be [easily] done on the SingleFile's side to fix it.

**Comment by gildas-lormeau** [comment]
Content-types are not mandatory for images, I'll take a look at the issue.

**Comment by gildas-lormeau** [comment]
@lkintact I confirm your analysis. The content-type isn't served by the HTTP server. Maybe SingleFile should "guess" it based on the extension for example. Anyway, this does not prevent images from being displayed.

**Comment by gildas-lormeau** [comment]
For the record, The MIME sniffing is specified here: https://mimesniff.spec.whatwg.org/#matching-a-mime-type-pattern.

**Comment by lkintact** [comment]
> Anyway, this does not prevent images from being displayed.

Yes, I realize this, but the inconvenience is the images are displayed shrunk in the page, and with the current issue ("data:null") it's impossible to quickly (via the context menu) view them in browser in full size for details when the Internet connection is offline.
For example, on my display the very first (https://b1.culture.ru/c/559344.jpg) image's computed dimensions are about 325x244px, while the file itself is 1369x1027px.

Thanks for the MIME Sniffing Standard link.

**Comment by gildas-lormeau** [comment]
I'll try to implement some MIME sniffing. As you can see in the specification, it represents a certain amount of work. It also must be done properly because this could introduce vulnerabilities.

**Comment by gildas-lormeau** [comment]
This issue will be fixed in the version 1.18.40 that I just uploaded on the stores.

**Comment by lkintact** [comment]
@gildas-lormeau Thanks for the fix!

**Comment by gildas-lormeau** [comment]
You're welcome :)
