### ISSUE TITLE
Auto-saving stopped working in v1.18.37

### ISSUE THREAD

**Issue by Mzyxptlk** [gildas-lormeau/SingleFile#544]
**Describe the bug**
Since upgrading to v1.18.37 2 days ago, SingleFile no longer performs auto-saving. Manually clicking the save button still works.

**To Reproduce**
1. Enable auto-saving all tabs.
2. Open a random page that's not set to disabled in your auto-save profile.
3. Wait 10 seconds.

**Expected behavior**
The page should be saved to the appropriate file. Instead, nothing happens. The page does appear in the pending aves list, but only briefly.

**Environment**
 - OS: Windows 7
 - Browser: Firefox
 - Version: v82.0.3

**Additional context**
Looking at the browser console, the only message that seems like it might be relevant is this one:
`Error: this.processors.lazy.content.loader is undefined`
It pops up a few seconds after loading the page, which is when I'd expect auto-saving to occur.

**Comment by gildas-lormeau** [comment]
Thank you for having reported this regression. I was able to reproduce it and fix it. The fix will be available in the next version that I'll publish. Sorry for the inconvenience.

**Comment by Mzyxptlk** [comment]
Thanks! No worries, shit happens.

**Comment by gildas-lormeau** [comment]
I just uploaded the version that fixes this issue (1.18.40). Hopefully it will be available for download on Firefox tomorrow.

**Comment by Mzyxptlk** [comment]
Just got v1.18.42 and auto-saving works as before. Thanks again!

**Comment by gildas-lormeau** [comment]
@Mzyxptlk Glad to hear it :)
