### ISSUE TITLE
CLI: Redownloads already existing pages

### ISSUE THREAD

**Issue by Unknow0059** [gildas-lormeau/SingleFile#545]
**Describe the bug**
Single-File CLI redownloads pages that have already been downloaded.

**To Reproduce**
1. Use command `single-file --crawl-links --crawl-inner-links-only --crawl-max-depth 0 --crawl-replace-urls https://www.imagemagick.org/Usage/`
2. Terminate batch process
3. Reuse the command

**Expected behavior**
The existing pages to be skipped.

**Environment**
 - OS: Windows 10 Pro 2004 10.0.19041.630 64-bit
 - Browser: Chrome
 - Version: Most recent

**Comment by gildas-lormeau** [comment]
You have to use the switch `--crawl-sync-session=<filename>` to fix this issue. This allows storing the state of the crawling process.

**Comment by Unknow0059** [comment]
Thank you. I looked through the --help but I didn't see that.

**Comment by gildas-lormeau** [comment]
You're welcome. The documentation needs to be improved I think.
