### ISSUE TITLE
Saved single html file can NOT be read in Android version of Firefox, pls. fix it!

### ISSUE THREAD

**Issue by hhtmp88** [gildas-lormeau/SingleFile#547]
**Describe the bug**
Saved single html file can NOT be read in Android version of Firefox
However, that it's normal in Desktop version

**To Reproduce**
1. Simply save an webpage into a single file *.html
2. open it in Desktop version Firefox -- it can be normally displayed
3. copy this html file to an android phone, double tap on it -- Firefox (Android version) is opened, but displaying only its current page and not that html file.

**Environment**
# Desktop OS: Win10 Pro
 - Browser: Firefox 82.0.3 (64-bit)

# Android Phone: Xiao Mi Note 10
-- Android: 10
-- Browser: Firefox 82.1.3 (Build#2015774643)

**Comment by gildas-lormeau** [comment]
On my Android (11), I cannot open the page with Firefox by double-tapping on it. Firefox is not proposed in the list of browsers. AFAIK, this is a bug in Firefox. Although, I tried this workaround and it works: https://github.com/mozilla-mobile/fenix/issues/7546#issuecomment-627091018.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because it is already addressed here: https://github.com/gildas-lormeau/SingleFile/issues/481
