### ISSUE TITLE
Problem with images blocked because of CORS/CORB

### ISSUE THREAD

**Issue by k12fm** [gildas-lormeau/SingleFile#548]
When saving the following pages, the images are not saved. I attach the output html, configuration and links.
[Test files.zip](https://github.com/gildas-lormeau/SingleFile/files/5579754/Test.files.zip)

**Environment**
 - OS: Win10 Pro
 - Browser: Chrome, Firefox
 - Version: 1.18.44

**Comment by gildas-lormeau** [comment]
It's unfortunately a bug in these browsers. Here are the corresponding issues in their bug tracker:
 - Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1605197 
 - Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1131384

**Comment by k12fm** [comment]
Temporary solution (chrome), disable the following flag: "chrome://flags/#cors-for-content-scripts". Then the web pages are saved without any problem.

**Comment by gildas-lormeau** [comment]
Thank you @k12fm for the tip!

Note that you can find additional info about the issue here: https://groups.google.com/a/chromium.org/g/chromium-extensions/c/IvSsLxXajyA/m/kI_o0yayAAAJ.

**Comment by k12fm** [comment]
Yes, I check both websites, and the get request fails if the "Referrer" in the header has a wrong value, in each one it must have the main site address ex: https://loveheaven.net/ or https://manganelo.com/.

It is possible to add an option to add the url of the main site to the header. Of course this suggestion is only if it is possible and does not generate any problems, otherwise ignore the suggestion.

Thanks for the support and the great extension.

**Comment by gildas-lormeau** [comment]
@k12fm I was hesitant to implement an option for this because it requires an additional permission (`webRequestBlocking`). However, I see here https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_permissions that the permission can be optional, so I think it should be ok to implement it.

**Comment by gildas-lormeau** [comment]
I fixed this issue and added the option `Misc > pass "Referer" header after a cross-origin request error`. It's disabled by default. Enabling it allows embedding the images with hotlink protection. The feature will be available in the version 1.18.45 I'll publish soon.

**Comment by gildas-lormeau** [comment]
The version 1.18.45 is now available on Chrome.

**Comment by D0n9** [comment]
> The version 1.18.45 is now available on Chrome.

sorry, I did not find this option in the latest version (1.22.40) I downloaded from the Chrome store. What is the reason? How should I solve it?
