### ISSUE TITLE
Local hostname as "Template variable"

### ISSUE THREAD

**Issue by novoid** [gildas-lormeau/SingleFile#549]
I'm using SingleFile in auto-save mode on all of my hosts in order to log my web browsing history. My current configuration for the "template" is `webarchive/{date-iso}T{hours-locale}.{minutes-locale}.{seconds-locale} {url-hostname} - {page-title}.html` according to [my personal file name convention](https://karl-voit.at/managing-digital-photographs/).

Since I collect and synchronize all of my host web archives to one location so that [it gets visualized on my calendar](https://github.com/novoid/Memacs/blob/master/docs/memacs_filenametimestamps.org), **I would love to have an additional "template variable": `{local-hostname}`** where I get the additional context information on which of my computers did visit the URL.

------------

Alternatively, you could think of providing access to arbitrary environment variables of the local host such as `{local-env-FOOBAR}` with `FOOBAR` being mapped to the environment variable `FOOBAR`, whatever this is. Sanitizing necessary, of course. This would also open up manifold possibilities for arbitrary use-cases.

**Comment by gildas-lormeau** [comment]
Thank you for the suggestions. Unfortunately, this is impossible to implement. For security purposes, extensions cannot have access to this kind of information.

**Comment by novoid** [comment]
> Thank you for the suggestions. Unfortunately, this is impossible to implement. For security purposes, extensions cannot have access to this kind of information.

Do you mean the environment variable or the local hostname as well?

The obvious workaround is to add the hostname "hard-coded" to the filename template string.

However, this needs to be changed when the configuration file gets imported on a different host. Btw, many thanks for having the flexible filename template mechanism as well as import/export!

**Comment by gildas-lormeau** [comment]
I was meaning the environment variables an the local hostname. Regarding the hostanme, I think I might be able to get the local IP of the machine, by using this technique: https://stackoverflow.com/questions/18572365/get-local-ip-of-a-device-in-chrome-extension/29514292#29514292. Would it be ok for you?

**Comment by novoid** [comment]
In my case, the local IP wouldn't solve my problem because my business machine gets a new IP each day or so.

For now, I stick with the workaround of manually writing the hostname to the config of each host.

So when the local hostname and the environments are out of reach, you can close this issue, I guess.

PS: Meanwhile, I discovered SingleFileZ and switched to it in order to save storage space. I auto-save everything. If you need specific information on how I accomplish it to [get all visited web pages onto my calendar](https://github.com/novoid/Memacs/blob/master/docs/memacs_filenametimestamps.org), drop me a line.

**Comment by gildas-lormeau** [comment]
Indeed, the hopes to be able to get the hostname and the environment variables are very very thin, and that's understandable from a privacy/security point of view.  That's why I'm closing the issue.

PS: Thank you very much for the link. I did not know Memacs. It seems to be really interesting and mature. I'll take a closer look at it ;)

**Comment by novoid** [comment]
> I did not know Memacs. It seems to be really interesting and mature. I'll take a closer look at it ;)

It's a somewhat niche solutions since it requires basic knowledge of GNU/Emacs and org mode. Memacs is a tool to bring non-org content into org mode.
