### ISSUE TITLE
spaces between words are trimmed when creating file

### ISSUE THREAD

**Issue by genuinefafa** [gildas-lormeau/SingleFile#55]
I'm using 1.3.4 with Chrome (OSX and Windows) and when I try to "single file" a page with spaces, those are being trim to only one, that's is:

```
This  Is  A          Line
```

will become

```
This Is A Line
```

Old version did not do that, not sure how can I prevent this from happening; I can see this happening since I'm creating base on a fixed width page with spaces having meaning (to tabulate information).

If you need any other info, i'll be happy to answer any question,

Cheers and thanks for the god job

**Comment by gildas-lormeau** [comment]
What HTML tag do you use to wrap the text? You can disable this behavior by unchecking "compress HTML" option.

**Comment by genuinefafa** [comment]
```
<span class="lastStatementDetail">05/07/18 PAYU.COM                             00XXXX*       30,00              </span>
```

I did and it does work, thanks! 

but the text is not part of the HTML, but the tag content; not sure if that's the correct name for the option or behavior for the option :-/

**Comment by gildas-lormeau** [comment]
Regarding the option, maybe "compress content" would be more appropriate?

I'll try to improve the behavior of the option. It should not alter the text so I keep the bug opened.

**Comment by genuinefafa** [comment]
for me, the content of the page should not be never change; it code in the other hand, might; that's is:

```
<span>
    <ul>
        <li>item 1 with        spaces       in between</li>
    </ul>
</span>
```

might become, without any issues something like

```<span><ul><li><li>item 1 with        spaces       in between</li></ul></span>```

but should **never** be

```<span><ul><li><li>item 1 with spaces in between</li></ul></span>```

because it does _change_ the content, not only compress it.

**Comment by gildas-lormeau** [comment]
In your example, if the following rule is present in the stylesheet `span, ul, li { white-space: pre }` then the text layout will also be broken. The correct way to fix this issue IMHO is to avoid processing tags that have `white-space: pre` or similar computed style.

**Comment by gildas-lormeau** [comment]
Yep, it's done! I'm going to commit it :)

**Comment by gildas-lormeau** [comment]
The version 1.3.5 should fix this issue. It means that when "compress HTML" option is checked spaces should not be trimmed.

**Comment by genuinefafa** [comment]
i'm using 1.3.7 now... and I can confirm it works! thanks @gildas-lormeau

**Comment by gildas-lormeau** [comment]
@genuinefafa Thanks for the submission and your feedback too ;
