### ISSUE TITLE
SingleFile freezes - FF and Chrome

### ISSUE THREAD

**Issue by xam1234** [gildas-lormeau/SingleFile#553]
Hi,
Today I noticed that SingleFile stopped writing one of the pages. I have been using it for a long time in FF and Chrome without problems.
When saving the page, it hangs at step 2, nothing further happens even after a long time. It only works correctly in Edge (new version). Below is a screenshot of the suspended page.

Thanks in advance for your help.
![1](https://user-images.githubusercontent.com/32258255/100348691-8af20600-2fe7-11eb-9f8c-87b531f53720.png)

**Comment by gildas-lormeau** [comment]
That would mean that a resource cannot be downloaded. Unfortunately, I don't have an admin account for Teams. Do you know if this issue can be reproduced on a page that does not require the admin rights? Meanwhile,if you press F12 to open the developer tools console, do you see any error message (in red) when saving the page?

**Comment by gildas-lormeau** [comment]
I think i can reproduce the issue on https://admin.microsoft.com/AdminPortal/Home?#/homepage. I'm checking out what's going on.

**Comment by gildas-lormeau** [comment]
This was a regression introduced in the version 1.18.45. I just uploaded the version 1.18.46 which fixes this issue. It was working on Edge because the version 1.18.45 is not published yet. The issue is rare because it is due to a malformed CSS declaration in a stylesheet.

**Comment by xam1234** [comment]
@gildas-lormeau Thank you :)

**Comment by xam1234** [comment]
I have one more question.
When I enter the reports and indicate a conversation, a preview window pops up. Is there a way to set SingleFile to download a page with this preview window as well ?

![obraz](https://user-images.githubusercontent.com/32258255/100360068-be895c00-2ff8-11eb-8d17-61bfd6b06690.png)

**Comment by gildas-lormeau** [comment]
I guess it requires JavaScript to be displayed. You can try to follow the procedure described here https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages. I cannot guarantee it will work though.

**Comment by xam1234** [comment]
I have reinstalled the chrome add-on and it shows further version 1.18.46 but it started to work.
FF shows 1.18.45 (27.11.2020) but still it is not working.

![obraz](https://user-images.githubusercontent.com/32258255/100444581-ef769900-30ab-11eb-9919-5f879aa32bf9.png)

**Comment by gildas-lormeau** [comment]
Thank you for the feedback. You have to wait for the version 1.18.46 to be published for Firefox. It's currently being reviewed by Mozilla.
