### ISSUE TITLE
Use bookmarks hierarchy to determine save path

### ISSUE THREAD

**Issue by sdht0** [gildas-lormeau/SingleFile#555]
Hi. I just enabled the "Save new bookmarks" feature and it's pretty neat!

Is it possible to read the folder hierarchy where the bookmark was saved and use that in the save path? So a bookmark saved in the bookmarks toolbar inside ProjectNotes -> Prior Work -> Math -> bookmark will get saved to Downloads/Bookmarks/ProjectNotes/Prior Work/Math/bookmark_<template>.html

Thanks!

**Comment by gildas-lormeau** [comment]
I'm afraid this is not really possible. This problem is due to the fact that adding a bookmark and choosing its folder are in fact 2 different actions.

To expand on the details, SingleFile saves the page when you bookmark a page. Today, when you decide to choose another bookmark folder, it's too late because the page may be already saved and it's technically impossible to move it afterwards in the correct folder on the disk. The only way to fix this problem would be to wait a certain delay after you bookmark a page to see if you want to move it in a folder and then save the page. This solution is not really acceptable because you would have to move the bookmark before this delay expires. Moreover, event if you wouldn't want to move the bookmark in a folder, the delay would still be applied.

**Comment by sdht0** [comment]
I see. What if I don't use the bookmark buttom, but instead drag the tab to a particular bookmark folder? That's what I usually do.

**Comment by gildas-lormeau** [comment]
The problem is that this feature does not exist in Chrome, for example.

**Comment by sdht0** [comment]
Interesting, another reason to love Firefox! Keep this feature in mind and see if you want to do a Firefox only implementation someday.

Meanwhile, how about another feature request: adding exceptions to for certain websites that should **not** be downloaded when bookmarked, such as youtube.com (cpu intensive and is not really useful without the video anyway)  or 9gag.com (does not save gifs correctly)?

**Comment by gildas-lormeau** [comment]
I guess this would not work on Firefox for Android though. I could implement this feature but it will be quite wobbly in the end. I'm thinking of eventually implementing it but not documenting it officially.

You can solve the exception issue by creating a new profile named for example "Ignored websites" in the options page. Make sure the settings related to the bookmarks are disabled in this profile. Then, go for example on youtube.com and select in the context menu `SingleFile > Select the default profile > Ignored websites`.

**Comment by sdht0** [comment]
> I'm thinking of eventually implementing it but not documenting it officially.

Thanks. How I imagine it working: the file name template would have a "bookmark-path" variable. Then if SIngleFile is able to detect a non-root bookmark path when saving the file, the variable will get replaced with the corresponding path, otherwise it will be empty and things will work as usual.

> You can solve the exception issue by creating a new profile

Sweet! This was easy, thanks!

> I did not notice an issue related to GIFs on 9gag.

For me, on Firefox on Linux, here is what I get after the page finishes loading. I can briefly see the image while the page is loading. It works as you said on Chromium though, thanks! See if you can reproduce and hopefully fix this Firefox specific bug?

![image](https://user-images.githubusercontent.com/867424/100461209-77ea3f00-3096-11eb-9ca0-d7933813cbf2.png)

**Comment by gildas-lormeau** [comment]
I cannot reproduce the issue with Firefox on 9gag with the default settings and `Other resources > remove video sources` disabled. On my end, the page is working fine. Maybe you changed other settings?

**Comment by gildas-lormeau** [comment]
I added the variable `bookmark-path` (and `bookmark-path-flat`) as you suggested. I decided to document it actually. This feature will be available in the next version.

**Comment by sdht0** [comment]
Thanks a lot @gildas-lormeau! Looking forward to the next release.

> I cannot reproduce the issue with Firefox
You're right. I tried with a fresh profile and it worked. Turns out the adblocker extension (umatrix/ublock) is somehow interfering with the page save.

**Comment by sdht0** [comment]
Btw, I think the documentation of the 2 variable need to be swapped?

**Comment by gildas-lormeau** [comment]
I did some tests with uMatrix and Ublock Origin but I was not able to reproduce the issue.

> Btw, I think the documentation of the 2 variable need to be swapped?

Indeed! It's fixed

**Comment by sdht0** [comment]
> I was not able to reproduce the issue.

Turned out I had "Remove sources" turned off as well. It all works well now, even on Firefox. 

Thanks for all your help!

**Comment by gildas-lormeau** [comment]
You're welcome @sdht0 and thank you for the feedback!
