### ISSUE TITLE
cli: output file not saved (similar to #395)

### ISSUE THREAD

**Issue by WellRedPandit** [gildas-lormeau/SingleFile#556]
**Describe the bug**

After I cloned master (`26a5d9c7`), ran `npm i`, I then ran a command like this `single-file https://en.wikipedia.org/wiki/Main_Page wikimain.html`, but no output file was created

**To Reproduce**

1. `git clone https://github.com/gildas-lormeau/SingleFile.git`
2. `cd SingleFile/cli`
3. `./single-file https://en.wikipedia.org/wiki/Main_Page wikimain.html`
4. observe - no wikimain.html in the current directory

**Expected behavior**

wikimain.html in the current directory

**Environment**
 - OS: Mac OS Catalina 10.15.7
 - Browser: Chrome, latest
 - node: 12.8.3

**Possible fix**

I was able to produce an output file when I replaced

`const filename = getFilename(pageData.output, options);`

with

`const filename = getFilename(options.output, options);`

here https://github.com/gildas-lormeau/SingleFile/blob/master/cli/single-file-cli-api.js#L206

**Comment by gildas-lormeau** [comment]
Thank you for having reported this issue. It was indeed a carelessness on my part. It's fixed now.

**Comment by WellRedPandit** [comment]
thank you!
wonderful that you have a cli option to run your app. much appreciated.

**Comment by gildas-lormeau** [comment]
You're welcome!
