### ISSUE TITLE
Single File plugin for Obsidian.md #feature request

### ISSUE THREAD

**Issue by viaahmed** [gildas-lormeau/SingleFile#557]
Hi!
Hope you are doing well and fine.
I noticed that you like making singleFile for every possible platform.
I invite you to make a plugin for [Obsidian.md](obsidian.md) for saving a note as rendered html file. 
Obsidian is a mark-down note-making app built on electron. It supports plugin made in typescript/javascript.
Hoping a positive response from you.
[viaAhmed](https://forum.obsidian.md/u/viaahmed)
https://forum.obsidian.md/u/viaahmed
for more info check this topic:
https://forum.obsidian.md/t/how-to-get-started-with-developing-a-custom-plugin/8157

**Comment by gildas-lormeau** [comment]
Well, I do some efforts to make sure the code of SingleFile could be integrated in other products or services "easily". However, I do not really participate to the integration most of the time. In fact, it's not a problem and that's even the beauty of open-source development. 
However, I see that the HTML format is not accepted by Obsidian, see https://publish.obsidian.md/help/Accepted+file+formats. This lack is very inconvenient and technically prevents the use of a page generated by SingleFile in Obsidian.

**Comment by gildas-lormeau** [comment]
I've re-read your feature request and I realize I did not understand it. So, you would like to have a plugin to convert markdown documents from Obsidian.md into HTML?

**Comment by gildas-lormeau** [comment]
I'm going to close this issue as "out of scope" because SingleFile is specialized in transforming HTML into HTML. It would impact a lot of code to transform MD into HTML.

**Comment by viaahmed** [comment]
Ok, thanks for replying, I reached you because, after all it renders
HTML, and exports too, no problem, thanks once again.
