### ISSUE TITLE
Setting a cookie in CLI

### ISSUE THREAD

**Issue by ImportTaste** [gildas-lormeau/SingleFile#559]
What I'm trying to archive requires a cookie to get into. I tried to use --http-header with the Set-Cookie header described here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

But, I couldn't get it to ever take. Even simple cookies like `--http-header "Set-Cookie: acceptterms=1"` failed. Is there a way to do this? It would be convenient if I could just make it accept a netscape cookie file...

EDIT: I'm actually getting the feeling that puppeteer isn't even accepting it at all, it's not even trying to retrieve the page, it just fails right away. Not sure what I'm doing wrong, it works just fine without the http header (aside from not getting to the area I want to get to, of course).

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. I added the option `--browser-cookie` to pass the value of a cookie. If you run for example the following test, you should see the cookie `test=value` in the saved page.
```
single-file https://manytools.org/http-html-text/http-request-headers/ --browser-debug=true --browser-cookie=test,value,.manytools.org
```

**Comment by gildas-lormeau** [comment]
FYI, for puppeteer, it uses this API https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagesetcookiecookies.
