### ISSUE TITLE
ZipTabs

### ISSUE THREAD

**Issue by BackOrder** [gildas-lormeau/SingleFile#56]
Bonjour Gildas,

Je vois que le développement de SingleFile est en bonne forme mais Zip Tabs est disparu de Chrome Web Store. Est-ce que ça reviendra bientôt?

Merci,
Ian

**Comment by gildas-lormeau** [comment]
Bonjour Ian,

En effet, le developpement de SingleFile a repris car "SingleFile Core" a été retirée du store par Google. De ce fait, ZipTabs a aussi disparu. Cependant, vous avez presque la fonctionnalité équivalente sous Chrome aujourd'hui dans SingleFile. Vous pouvez ainsi sélectionner plusieurs onglets (avec shift+clic par exemple) et cliquer sur le bouton SingleFile pour sauvegarder plusieurs pages en un seul clic. En revanche, les pages ne sont pas stockées dans un fichier zip. Si c'était le cas, ça serait suffisant pour vous pour combler l'absence de ZipTabs ?

Gildas

**Comment by BackOrder** [comment]
Je viens d'essayer ce que vous avez suggéré et ça fonctionne très bien. C'est en fait beaucoup plus rapide que ZipTabs. Il n'y aura plus de ZipTabs dans le future? En tout cas, continuez votre excellent travail! :)

**Comment by gildas-lormeau** [comment]
Concernant ZipTabs, je ne peux pas garantir que je la ré-écrirai, c'est pour ça que je préfère savoir si la fonctionnalité actuelle basée sur la sélection multiple d'onglets est suffisante. N'hésitez pas à me faire part de vos remarques si vous trouvez que ça ne comble pas vraiment vos besoins. Merci pour les encouragements :)

**Comment by gildas-lormeau** [comment]
Je ferme le bug. N'hésitez pas à le réouvrir si vous avez un besoin que ne comblerait pas SingleFile aujourd'hui mais qui était comblé par ZipTabs.
