### ISSUE TITLE
Executing JavaScript function before save (CLI)

### ISSUE THREAD

**Issue by ImportTaste** [gildas-lormeau/SingleFile#561]
There's one last thing I'd like to ask your help with (and I feel bad doing so because you've been so helpful thus far). In order to automate saving the pages I want to save, I need to execute one of their javascript functions to load some data into fields that normally require a click to be populated.

I've already determined _which_ function to run using the chrome devtools, tested it out already. I'm just not sure how to do it with the CLI interface. I can see in --help that there's a 'user-script-enabled' boolean, but I don't see any way of actually pointing it to a script that I want it to run. Am I missing something?

If this is something that the CLI version can't do yet, an option like `--browser-console-cmd` that would be ran in the devtools console after the page finishes loading but before it saves would be wonderful. Thanks again.

**Comment by gildas-lormeau** [comment]
You have to create a file named for example `my-script.js` containing the code below and run `single-file` with the option `--browser-scripts=my-script.js`. 

```js
dispatchEvent(new CustomEvent("single-file-user-script-init"));
addEventListener("single-file-on-before-capture-request", event => {
  // call the function here
});
```
You can find more info here https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved on how to run asynchronous code if needed.

**Comment by ImportTaste** [comment]
> You have to create a file named for example `my-script.js` containing the code below and run `single-file` with the option `--browser-script=my-script.js`.
> 
> ```js
> dispatchEvent(new CustomEvent("single-file-user-script-init"));
> addEventListener("single-file-on-before-capture-request", event => {
>   // call the function here
> });
> ```
> 
> You can find more info here https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved on how to run asynchronous code if needed. There are also some examples of script.

I'm having a lot of difficulty. I was having a lot of trouble calling the page's function at first, because of sandboxing and whatnot. I came up with this, and it does technically work:

```javascript
(() => {

    dispatchEvent(new CustomEvent("single-file-user-script-init"));

    function exec(fn) {
        var script = document.createElement('script');
        script.setAttribute("type", "application/javascript");
        script.textContent = '(' + fn + ')();';
        document.body.appendChild(script);
        document.body.removeChild(script);
    }

    addEventListener("single-file-on-before-capture-request", () => {
        exec(function() {
            Web.displayImages();
        });
        console.log("The page will be saved by SingleFile");
    });

})();
```

The problem is that it receives an undefined response immediately, but it's not actually done doing what it needs to do. I can tell that it started to work, because it does add a class to one of the page's elements that indicates it's supposed to be loading elements, but SingleFile saves before that completes.

I tried this using the async method described on the page as well, but that doesn't seem to make a difference. It seems the function it needs to call isn't waiting until it's done to return its response.

My thinking is I need some way to wait a couple seconds, but upon trying to search for an equivalent to 'sleep' for javascript, I was greeted with pages of pages of people saying 'this isn't the right way to do it!' on just about every snippet of code, and I'm not sure what would be applicable to this userscript.

**Comment by ImportTaste** [comment]
Okay, I just noticed something strange when I was in debug mode. This element seems to appear when the function is called:
`<noscript><div id="JSWarning">You need to enable javascript to be able to use this website.</div></noscript>`

"The page will be saved by SingleFile" does appear in the console window though. I'm very confused by this.

**Comment by gildas-lormeau** [comment]
Note that you can add `debugger` statements to add breakoints in your script and run `single-file` with the option `--browser-debug`. This might be useful in order to understand what's happening.

**Comment by ImportTaste** [comment]
> Note that you can add `debugger` statements to add breakpoints in your script and run `single-file` with the option `--browser-debug`. This might be useful in order to understand what's happening.

That's what I've been doing, yeah.

**Comment by gildas-lormeau** [comment]
I forgot to mention that you don't need the `exec` function that you defined in the code you posted. The script is already running in the page's context.

**Comment by gildas-lormeau** [comment]
If you want to add a delay, you can run the code asynchronously like in this example below
```js
const DELAY = 5000; // time to wait in ms before calling Web.displayImages
dispatchEvent(new CustomEvent("single-file-user-script-init"));

addEventListener("single-file-on-before-capture-request", async event => {
  event.preventDefault();
  try {
    await new Promise(resolve => setTimeout(resolve, DELAY));
    Web.displayImages();
  } finally {
    dispatchEvent(new CustomEvent("single-file-on-before-capture-response"));
  }
});
```

**Comment by ImportTaste** [comment]
I actually needed to wait _after_ the call, but that was easily accomplished, I just moved the await to after the command instead of before. It's now capturing successfully now, thanks again.

**Comment by gildas-lormeau** [comment]
Glad to hear it :)
