### ISSUE TITLE
Save to place other than Downloads

### ISSUE THREAD

**Issue by notuntoward** [gildas-lormeau/SingleFile#562]
I noticed that you prefer feature requests in GitHub instead of in the reviews, so here's a copy:
> 
> If the page being annotated is already a local file, then SingleFile should save back to that file instead of making a new file in the Downloads folder.
> 
> This would be useful when re-annotating a file you've already saved.
> 
> Edit 1: There is an option "File name > filename conflict resolution" but this provides no way to save to the original file except by renavigating the whole path to the original html source file, and re-specifying the filename.
> 
> What I'm asking for is that SingleFile literally saves back to the original source html file (possibly with an overwrite warning for safety, although I would be happier without that).
> 
> Edit 2: disabling the option "File name > open the "Save as" dialog to confirm the file name" doesn't affect this problem; the file is still written to the Downloads directory instead of its original location.

You offered several suggestions (thanks, quoted below) but I can't get any of them to work, even if I stick to using the Downloads directory.

But about the impossibility of storing to a non-Downloads directory, it seems that it is somehow possible, as the Zotero Firefox and Chrome add-on, `Zotero Connector`, is [using "Single File logic" to save .html to non-Download directories](https://forums.zotero.org/discussion/85306/available-for-beta-testing-improved-webpage-snapshots).

Is their approach feasible for Single File itself?

> 
> **Developer response**
> posted 6 days ago
> There is an option for that, see "File name > filename conflict resolution".
> 
> Edit 1: I think it's possible by also disabling the option "File name > open the "Save as" dialog to confirm the file name" (this is the default state)
> 
> Edit 2: It's technically impossible for an extension to save the file in another folder than the "Downloads" folder or its subfolders.
> 
>

**Comment by gildas-lormeau** [comment]
> 
> I noticed that you prefer feature requests in GitHub instead of in the reviews, so here's a copy:

Indeed, it is more convenient for everyone. Here we can *discuss* problems and features more easily than in the "Review" section which is not intended for support anyway.

> You offered several suggestions (thanks, quoted below) but I can't get any of them to work, even if I stick to using the Downloads directory.

I agree that I was a bit vague. You can make it work but only in a predefined sub-folder or the Downloads folder itself. Here is how to configure SingleFile to overwrite files transparently in the Downloads folder:
 - reset the settings
 - change the template of the filename to `{page-title}.html`. You must change it because the default template name creates a unique filename. Alternatively, you can set it to `{url-last-segment}.html` if you want to keep the original filename. Note however that this will only work with files stored in the Downloads folder and not its sub-folders. If you need to use sub-folders, please let me know and how you organize them briefly.
 - set `File name > filename conflict resolution` to `overwrite the existing file`
With these settings, any page in the Downloads folder that you save again in SingleFile should be transparently overwritten.

> But about the impossibility of storing to a non-Downloads directory, it seems that it is somehow possible...

Yes, but it requires a third-party program. I was meaning this is not natively possible within extensions. 

> Is their approach feasible for Single File itself?

Coding such a third-party program to do so is possible bit it requires some work.

**Comment by gildas-lormeau** [comment]
It seems that no one actually wants to discuss this issue?

**Comment by notuntoward** [comment]
I'd be happy to discuss it, although I don't have the coding chops to edit
an extension.

**Comment by gildas-lormeau** [comment]
@notuntoward Did you try to create a symbolic link? If you can tell me what your OS is, I can explain you how to do so.

**Comment by loveyoucomtw** [comment]
> I noticed that you prefer feature requests in GitHub instead of in the reviews, so here's a copy:
> 
> > 
> 
> > If the page being annotated is already a local file, then SingleFile should save back to that file instead of making a new file in the Downloads folder.
> 
> > 
> 
> > This would be useful when re-annotating a file you've already saved.
> 
> > 
> 
> > Edit 1: There is an option "File name > filename conflict resolution" but this provides no way to save to the original file except by renavigating the whole path to the original html source file, and re-specifying the filename.
> 
> > 
> 
> > What I'm asking for is that SingleFile literally saves back to the original source html file (possibly with an overwrite warning for safety, although I would be happier without that).
> 
> > 
> 
> > Edit 2: disabling the option "File name > open the "Save as" dialog to confirm the file name" doesn't affect this problem; the file is still written to the Downloads directory instead of its original location.
> 
> 
> 
> You offered several suggestions (thanks, quoted below) but I can't get any of them to work, even if I stick to using the Downloads directory.
> 
> 
> 
> But about the impossibility of storing to a non-Downloads directory, it seems that it is somehow possible, as the Zotero Firefox and Chrome add-on, `Zotero Connector`, is [using "Single File logic" to save .html to non-Download directories](https://forums.zotero.org/discussion/85306/available-for-beta-testing-improved-webpage-snapshots).
> 
> 
> 
> Is their approach feasible for Single File itself?
> 
> 
> 
> > 
> 
> > **Developer response**
> 
> > posted 6 days ago
> 
> > There is an option for that, see "File name > filename conflict resolution".
> 
> > 
> 
> > Edit 1: I think it's possible by also disabling the option "File name > open the "Save as" dialog to confirm the file name" (this is the default state)
> 
> > 
> 
> > Edit 2: It's technically impossible for an extension to save the file in another folder than the "Downloads" folder or its subfolders.
> 
> > 
> 
> >
