### ISSUE TITLE
Doesn't work properly on MS Edge 

### ISSUE THREAD

**Issue by mr10008** [gildas-lormeau/SingleFile#564]
**Describe the bug**
Despite proper configuration of the template of the Infobar with {url-href} ({date-iso}) the Infobar is missing.
Extension version: 1.18.52

**To Reproduce**
1. Go to any page
2. Click on SingleFile button
3. Open the saved page
4. See that the Info bar is missing

**Expected behavior**
Info bar should be included in the saved page

**Environment**
 - OS: Win 7 Ultimate, 64 bit
 - Browser: MS Edge
 - Version:  87.0.664.57

**Comment by gildas-lormeau** [comment]
You must enable the option "Allow access to file URLs" in the extension page to display the infobar when viewing a saved page, to save or to annotate a page stored on the filesystem. See here more other known issues: https://github.com/gildas-lormeau/SingleFile#known-issues

**Comment by gildas-lormeau** [comment]
I'm closing this issue because I just did a test again and I confirm it works.
