### ISSUE TITLE
can it support exporting the page with adobe flash items?

### ISSUE THREAD

**Issue by l2tpv3** [gildas-lormeau/SingleFile#567]

**Comment by gildas-lormeau** [comment]
From a technical point of view, SingleFile could embed flash animations but the browser refuses to execute it. I saved this page http://wwwusers.di.uniroma1.it/~caminiti/personal/f8/blob.html and attached in the zip file the result When I open it in Firefox, all I see is a black screen. The browser does not even propose to run the flash animation.

[test.zip](https://github.com/gildas-lormeau/SingleFile/files/5691946/Blobs.2020-12-14.11_31_14.PM.zip)

**Comment by Unknow0059** [comment]
If you want to save Flash games I recommend BluePoint's Flashpoint.
If they don't have your flash game you can talk among their community about adding it to the library.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because this feature is impossible to implement in SingleFile. Browsers block inline flash contents.
