### ISSUE TITLE
annotated notes search problem

### ISSUE THREAD

**Issue by barrer** [gildas-lormeau/SingleFile#568]
**Describe the bug**
[DocFetcher](https://sourceforge.net/projects/docfetcher/), [pandoc](https://github.com/jgm/pandoc) and other html processing ignore this `<textarea dir=auto>note text</textarea>` HTML tag. This leaves annotated notes unsearched or unprocessed. Editing web text directly with annotate edit breaks the web structure and is not very convenient for notes.

**Expected behavior**
searchable

**Environment**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 1.18.53

**Comment by barrer** [comment]
I'm sorry, DocFetcher can search correctly, the previous test was caused by the index not updated in time.

**Comment by gildas-lormeau** [comment]
No problem ;)
