### ISSUE TITLE
new "info bar" feature does not work?

### ISSUE THREAD

**Issue by savnt** [gildas-lormeau/SingleFile#57]
At my site the info bar question mark item does not show up when I reopen a saved page in chrome (SingleFile version 1.3.14).

The option to show the info bar is checked and I granted the higher rights for the extension.

When inspecting the displayed page in chrome, no content script is assigned. I think therefore the data cannot be augmented with the info bar icon. Is this a manifest issue?

Anyway, I do not miss that feature to much. I just liked to check how its looks and if it's useful for me.

Best Regards

**Comment by gildas-lormeau** [comment]
Could you please verify the option "Allow access to file URLs" is enabled in the extension page? (chrome://extensions/?id=kdojppajkmdmiklabnjigfjjcnmaeeje)

**Comment by gildas-lormeau** [comment]
It was a regression I introduced recently if "compress HTYML" was checked. I'm sorry for that. It should be fixed in version 1.3.16 for new pages you will save. Could you please confirm?

**Comment by savnt** [comment]
Many thanks, it works now.
Best Regards

**Comment by gildas-lormeau** [comment]
You're welcome! Thanks for your submission.
