### ISSUE TITLE
Option to save directly on reader mode OR auto activate reader mode on editor

### ISSUE THREAD

**Issue by dareducky** [gildas-lormeau/SingleFile#572]
Hi, I absolutely love this extension and it has entirely replaced pocket for me. I only have one use case for it and, right now, it's a bit convoluted.

As I mentioned I use this extension as a replacement for pocket so my workflow is: 

1. Set to auto-activate editor on save on settings
2. Click on the extension button
3. Click on "Format this page for better readability"
4. Click Save

As I do this dozens of times per day its a bit annoying. So, my request is, if it's on the scope of the extension, for a setting toggle for either autosave using the "Format this page for better readability" or, if this is not possible, auto open using this mode so I only need to save it.

Ideal workflow:

1. Click on the extension button and it autosaves using better readability

Second best workflow:

1. Click on the extension button and it auto open the editor mode using better readability
2. Click save

Thank you

**Comment by gildas-lormeau** [comment]
Thank you for the kind words and the feature request. Actually, there is already an option to select the default mode of the annotation editor. I think it should be ok if you set `Annotation editor > default mode` to `format the page`.

**Comment by dareducky** [comment]
Oh my god, I actually read all the options page but didn't made the connection between format the page and format the page for reader mode. Totally my bad :(

**Comment by gildas-lormeau** [comment]
No problem ;)
