### ISSUE TITLE
request, omitting default comments

### ISSUE THREAD

**Issue by SteegHobland** [gildas-lormeau/SingleFile#573]
I would like the option to save a file omitting the default comments (url, saved date).
If such option exists, I missed it.
If there is not such an option yet, please consider this a feature request.

**Comment by gildas-lormeau** [comment]
The fact that there is no possibility to remove it is intentional actually, mainly for "marketing" purposes. Why would you want it deleted? Is there, for example, a technical reason?

**Comment by gildas-lormeau** [comment]
I'm closing the issue for the reason I mentioned. Feel free to reopen it of comment it.
