### ISSUE TITLE
CLI: Batch URL list: make items in the list use relative paths instead.

### ISSUE THREAD

**Issue by jtagcat** [gildas-lormeau/SingleFile#576]
**Is your feature request related to a problem? Please describe.**
I have a pre-scraped list of webpages. In the SingleFile, links to 'next page' go to the actual web, not local/servehost.

**Describe the solution you'd like**
I guess localization of links in the same batch list? Are there html tags for 'local fide, but if 404, then use internet file'?

**Describe alternatives you've considered (optional)**
Doing some conversion work with sed.

**Comment by gildas-lormeau** [comment]
Did you try to use the option `--crawl-replace-urls`?

**Comment by jtagcat** [comment]
No, I would've thought it replaced URLs SF discovered itself, not provided to it.

**Comment by gildas-lormeau** [comment]
I does not by default because this is done when all the pages are captured and it can take some time.
