### ISSUE TITLE
Save and arrange Html just like when we do "View Page Source"

### ISSUE THREAD

**Issue by foremtehan** [gildas-lormeau/SingleFile#581]
Hey man thanks for your extension, I just noted when we save the page, look like it re arrange the html and its different than the html when we do Ctrl+U

For example save the current issue page And also open the page source

The saved file have 2406 like of element but the page source have 4719

So i want to know is it possible to save "Untouched" file ?

**Comment by gildas-lormeau** [comment]
You should disable the options `HTML content > compress HTML content` and `HTML content > remove hidden elements`.
