### ISSUE TITLE
PDF optionnal feature

### ISSUE THREAD

**Issue by Methatronc** [gildas-lormeau/SingleFile#583]
Hello,

Could it be possible to display a choice when clicking the single-file button to either output a html or pdf file ?
By the way thanks for your work it is a very useful addon !

Have a good day

**Comment by gildas-lormeau** [comment]
Than you for the kind words! 

PDF is totally different format and SingleFile is not supposed to be a workaround for a buggy "Print as PDF" feature. Personally, I also don't want to contribute to the use of PDF to save pages, I think it's awful!

I'm sorry but I must close this issue as "out of scope". Feel free to comment it though.
