### ISSUE TITLE
An option name in SingleFile help is rendered incorrectly

### ISSUE THREAD

**Issue by lkintact** [gildas-lormeau/SingleFile#585]
**Describe the bug**
The `Option: include infobar in the saved page` text in `moz-extension://d11a382b-623a-40d7-8641-2f1936d8e4ed/extension/ui/pages/help.html` isn't inside \<span class="option"\>\[...\]\</span\>, and so is perhaps rendered not as intended. An image illustrating the issue:
![Screenshot - SingleFile help](https://user-images.githubusercontent.com/24726299/103830267-2cab4f00-508c-11eb-9e7f-e81d05d63e2c.png)

**Environment**
SingleFile version: 1.18.61

**Comment by gildas-lormeau** [comment]
Good point! It's fixed and will be available in the next version. Thank you!
