### ISSUE TITLE
Possible typos in help

### ISSUE THREAD

**Issue by lkintact** [gildas-lormeau/SingleFile#586]
In SingleFile help (`moz-extension://d11a382b-623a-40d7-8641-2f1936d8e4ed/extension/ui/pages/help.html`) the `unchecked` in both of the the phrases `frame contents may be missing (if you unchecked "remove frames")` should perhaps be `checked`.

SingleFile version: 1.18.61.

**Comment by gildas-lormeau** [comment]
Thank you again! It's fixed.
