### ISSUE TITLE
"auto-save after page load" and "auto-save on page unload" can be checked simultaneously

### ISSUE THREAD

**Issue by lkintact** [gildas-lormeau/SingleFile#587]
**Describe the bug**
Considering the description of the latter, `Check this option to auto-save pages before being unloaded instead of saving pages after being loaded [...]`, that's probably a bug or an indication of one.

**To Reproduce**
1. Create a new Firefox profile, add SingleFile to it.
2. Uncheck `auto-save after page load or on page unload` in the `Auto-save` section of SingleFile options. `auto-save after page load` gets checked.
3. Check `auto-save on page unload`. `auto-save after page load` doesn't get unchecked.

**Expected behavior**
`auto-save after page load` should perhaps get unchecked.

**Environment**
 - OS: Windows 10 Home 1803
 - Browser: Firefox 84.0.2 (32-bit)
 - SingleFile version 1.18.61

**Comment by gildas-lormeau** [comment]
This is actually a feature!

**Comment by lkintact** [comment]
Could you please explain that feature, i.e., how exactly SingleFile behaves when both preferences are checked, at what point it saves the page?

Because the way the description of `auto-save on page unload` is worded -- "Check this option to auto-save pages before being unloaded _**instead of saving pages after being loaded**_ [...]" -- suggests that if the preference is checked, `auto-save after page load` should not work at all. So it seems logical for it to get unchecked if the user checks `auto-save on page unload`, and yet it remains checked.

**Comment by gildas-lormeau** [comment]
SingleFile shoukd capture the page twice, once loaded and once unloaded.

It's poorly worded in the help page, I will fix that.

**Comment by gildas-lormeau** [comment]
I guess it's okay, I'm closing this issue.
