### ISSUE TITLE
CLI: Cannot find WebSocketTransport.js

### ISSUE THREAD

**Issue by Unknow0059** [gildas-lormeau/SingleFile#589]
**Describe the bug**
So, this started erroring and I don't know why, seeing as I did not mess with Single-File's installdir at all.

**To Reproduce**
1. Open CMD
2. Give single-file a URL
3. See error

**Expected behavior**
No error.

**Screenshots**
The cause might be that these files got renamed automatically recently:
![image](https://user-images.githubusercontent.com/25656892/103972952-0ac5d100-514d-11eb-92a8-6280e19f9581.png)
Don't know what caused it, and I'm assuming these are the same files. Maybe some Node update. I didn't even know it ran those automatically.
The highlighted file is in the `common` folder.

**Environment**
 - OS: Windows 10 Pro 2004 10.0.19041.685 64-bit
 - Browser: Chrome
 - Single-File Version: 0.2.8

**Comment by gildas-lormeau** [comment]
You might need to update puppeteer if you're using an "ever-green" Chrome browser.

**Comment by Unknow0059** [comment]
I'm sorry, but how could I do that?

**Comment by gildas-lormeau** [comment]
You have to run `npm update` in the `G:\Programing\Scripts\aliases\SingleFile` directory.

**Comment by Unknow0059** [comment]
![image](https://user-images.githubusercontent.com/25656892/104110680-c8210780-52b8-11eb-85e2-7e01975e7adb.png)
Sadly, it did nothing.

**Comment by gildas-lormeau** [comment]
Maybe something is broken in the NPM modules. I would recommend you to delete the content of the `SingleFile` folder and reinstall it.

**Comment by Unknow0059** [comment]
That did fix it. This whole NPM thing seems very unreliable.

Thank you.

**Comment by gildas-lormeau** [comment]
I guess the problem is that you're not supposed to update modules inside applications manually. I'm glad to hear it works again :)
