### ISSUE TITLE
Doesn't close the `body` tag.

### ISSUE THREAD

**Issue by twisp007** [gildas-lormeau/SingleFile#590]
**Describe the bug**
The generated HTML file contains a dangling `<body>` tag.

**To Reproduce**
1. Save a JupyterLab Notebook as HTML (`<body>` tag  is properly closed)
2. Open with firefox.
3. Use `SingleFile` to save it.
4. Use a text editor to see `<body>` is not closed by `</body>`.

**Expected behavior**
A valid HTML document is produced without any dangling HTML tags.

**Screenshots**

**Environment**
 - OS: Manjaro Linux
 - Browser: Firefox
 - Version: 83

**Additional context**
I can provide the specific JupyterLab Note HTML file. But it happens with any such file.

**Comment by gildas-lormeau** [comment]
The document *is* valid even with the omission of the `</body>` tag and some [other ones](https://www.w3.org/TR/html51/syntax.html#optional-start-and-end-tags). It's in fact a feature. You can disable it by unchecking the option `HTML content > compress HTML content`
