### ISSUE TITLE
The "default profile" value isn't kept in "singlefile-settings.json"

### ISSUE THREAD

**Issue by lkintact** [gildas-lormeau/SingleFile#593]
**To Reproduce**
1. Create a new Firefox profile, add SingleFile to it.
2. Click on "+" right to "Default settings" in the main SF options page to add a new SF profile, name it "NewProfile".
2. Scroll all the way down the options page and click on "Export", then "Save". The options are saved in a "singlefile-settings.json" file.
4. Navigate to https://example.com.
5. Right-click to open the context menu and click on "SingleFile -> Select the default profile -> NewProfile".
6. Repeat step 3 to save the options in a "singlefile-settings(1).json" file.
7. Diff-comparing "singlefile-settings.json" and "singlefile-settings(1).json" shows they are identical.

**Expected behavior**
"singlefile-settings(1).json" should have an entry for the default profile name, with the value "NewProfile".

**Environment**
 - OS: Windows 10 Home 1803,
 - Browser: Firefox version 84.0.2 (32-bit)
 - SingleFile version 1.18.62.

**Comment by gildas-lormeau** [comment]
Actually, the export saves only what you see in the options page, and there's no setting for the default profile.

**Comment by lkintact** [comment]
That's what confused me: you _can_ see the effect of setting the default profile via the context menu and that effect is persistent through browser sessions, which means the value is kept somewhere (perhaps, not in SF options?).

Steps to see what I'm trying to convey:
1. Create a new Firefox profile, add SingleFile to it (do not enable "Allow this extension to run in Private Windows" when adding SF).
2. Add a new SF profile, name it "NewProfile".
3. Navigate to https://example.com.
4. Right-click to open the context menu and click on "SingleFile -> Select the default profile -> Default settings" ("Default settings" should be already selected, but this step seems to be necessary anyway).
5. Open the `Auto-settings rules` section of SF options, you should see something like this (notice that the "Profile" value is "Default settings"):

![Capture1](https://user-images.githubusercontent.com/24726299/105495177-e29dac80-5ccc-11eb-99be-e9aa62bdc780.jpg)

6. Restart Firefox.
7. Check `Auto-settings rules` to see that "Profile" value is still "Default settings".
8. Export the options to "singlefile-settings.json".
9. Navigate to https://example.com again.
10. Right-click to open the context menu and click on "SingleFile -> Select the default profile -> NewProfile".
11. Open `Auto-settings rules` again, you should see something like this (notice that this time the "Profile" value is "NewProfile"):

![Capture2](https://user-images.githubusercontent.com/24726299/105495674-7ff8e080-5ccd-11eb-8244-dbd57e9586e2.jpg)
12. Restart Firefox.
13. Check `Auto-settings rules` to see that "Profile" value is still "NewProfile".
14. Export the options to "singlefile-settings(1).json".
15. Diff-comparing "singlefile-settings.json" and "singlefile-settings(1).json" shows they are identical.

**Environment**
Hasn't changed since the previous post.

**Comment by gildas-lormeau** [comment]
It looks like the fact that the value persists is a bug. A rule should be taken into account if and only if you specified a value for the `URL` field and clicked on the `+` button. That's why it's not exported, the rule does not exist.

**Comment by lkintact** [comment]
Perhaps, this is relevant: if you have more than one profile with at least one rule for each of them, unchecking `Options` > `Auto-settings rules` > `display all profiles` causes only the rules for the one you selected as default (steps 4 and 10 in my [previous message](https://github.com/gildas-lormeau/SingleFile/issues/593#issuecomment-765405730)) to be shown.

**Comment by lkintact** [comment]
The behavior described above is probably a bug, and unchecking `display all profiles` is actually supposed to show rules only for the currently selected profile (i.e. the one selected in the `Auto-settings rules`' "Profile" drop-down menu), not the default profile. I'm not sure, because `display all profiles` isn't mentioned in the help.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because I explained that only the options are saved (and not the actions you make via the context menu). I also think the auto-settings rules work as expected. I might be wrong on the latter point. Feel free to create a new issue if necessary.
