### ISSUE TITLE
Adding a {profile-name} template variable

### ISSUE THREAD

**Issue by lkintact** [gildas-lormeau/SingleFile#594]
**Is your feature request related to a problem? Please describe.**
It's not really a problem, but having an infobar/filename template variable holding the name of the profile that was used for saving the page would be convenient: it could give some useful information on the file, for example, whether JS or frames were removed or not, and so on.

**Describe alternatives you've considered (optional)**
Manually adding info by renaming files.

SingleFile version: 1.18.62.

**Comment by gildas-lormeau** [comment]
I agree that could be convenient :)

**Comment by gildas-lormeau** [comment]
It's implemented in the new version.
