### ISSUE TITLE
On Certain Sites Static Video Images Not Being Saved Correctly

### ISSUE THREAD

**Issue by sj365** [gildas-lormeau/SingleFile#596]
SingleFile v1.18.62
Chrome Version 88.0.4324.96 (Official Build) (64-bit)

Saved pages from certain sites do not save with static picture of video frame, only black squares

Windows 10 Education
20H2
19042.746
Windows Feature Experience Pack 120.2212.551.0

Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz 2.81 GHz
32.0 GB Ram
64-bit operating system, x64-based processor

**Page saved with static picture successfully**
https://www.nbcnews.com/politics/national-security/12-national-guard-members-removed-inauguration-duty-including-two-inappropriate-n1254772

[12 National Guard members removed from inauguration duty, including two for 'inappropriate' comments (1).zip](https://github.com/gildas-lormeau/SingleFile/files/5849760/12.National.Guard.members.removed.from.inauguration.duty.including.two.for.inappropriate.comments.1.zip)

**Page Not Saved with static video picture successfuly (black boxes)**
https://www.dailymail.co.uk/news/article-9170237/Protesters-gather-damage-Democratic-headquarters-Oregon.html

[Antifa rioters smash windows at Oregon Democratic Party headquarters in Portland _ Daily Mail Online (1).zip](https://github.com/gildas-lormeau/SingleFile/files/5849781/Antifa.rioters.smash.windows.at.Oregon.Democratic.Party.headquarters.in.Portland._.Daily.Mail.Online.1.zip)

**Comment by gildas-lormeau** [comment]
This is a known issue, see 2nd point here: https://github.com/gildas-lormeau/SingleFile#known-issues

**Comment by gildas-lormeau** [comment]
I'm closing this issue as "known issue".
