### ISSUE TITLE
How to save files in sub-folders without "save pages in background"?

### ISSUE THREAD

**Issue by zhengjiewen1999** [gildas-lormeau/SingleFile#598]
I know change the setting of "File name > template" could save files in sub-folders, but I must disable the option "Misc > save pages in background" to avoid save page like "56833935-156b-4d8c-a00f-19599c6513d3.html",  so the sub-directories in filename templates doesn't work. Is there another way?
Thank you and sorry for non-native English.

**Comment by gildas-lormeau** [comment]
Unfortunately, that's not possible. This issue is a bug in Chrome that exists for years. I would recommend you to reinstall Chrome or to switch to a browser not based on Chromium, e.g. Firefox.

**Comment by zhengjiewen1999** [comment]
Thank you for your reply. I've tried to reinstall the chrome, but it didn't work. I will consider whether to switch to another browser

**Comment by gildas-lormeau** [comment]
@zhengjiewen1999 This issue migh also be due to a "download manager" extension. If you're using one of them, make sure SingleFile is installed first.
