### ISSUE TITLE
{profile-name} always uses the name of the first profile

### ISSUE THREAD

**Issue by lkintact** [gildas-lormeau/SingleFile#600]
**Describe the bug**
Thanks for implementing #594. However, I think there's a bug:

**To Reproduce**
1. Create a new Firefox profile, add SingleFile to it (don't enable "Allow this extension to run in Private Windows" when adding SF).
2. Add two profiles to SF, `Profile1` and `Profile2`.
3. Set the filename templates for the new profiles to `{page-title} p1 {profile-name}.html` and `{page-title} p2 {profile-name}.html`, respectively.
4. Navigate to https://example.com.
5. Rightclick to open the context menu and select "SingleFile -> Save page with profile -> Profile1".
6. Repeat step 5 for "Profile2".
SF creates two files named `Example Domain p1 __Default_Settings__.html` and `Example Domain p2 __Default_Settings__.html`

**Expected behavior**
The filenames should be `Example Domain p1 Profile1` and `Example Domain p2 Profile2.html`, respectively.

**Environment**
 - OS: Windows 10 Home 1803,
 - Browser: Firefox version 84.0.2 (32-bit)
 - SingleFile version 1.18.63.

**Comment by gildas-lormeau** [comment]
Thank you, the issue is fixed in the version 1.18.66 I just uploaded.

**Comment by lkintact** [comment]
I checked with 1.18.66, works for me, thank you.  Perhaps a description of `{profile-name}` should be added to the SF help.

**Comment by gildas-lormeau** [comment]
Yeah, I totally forgot about that. Thank you for the reminder!
