### ISSUE TITLE
Problem with disqus comments

### ISSUE THREAD

**Issue by fakiyor379** [gildas-lormeau/SingleFile#602]
When saving a page with disqus comments, the console shows me the following error: "Access to fetch at 'https://c.disquscdn.com/uploads/users/8973/8058/avatar92.jpg?1423250806' from origin 'https://about.disqus.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to ' no-cors' to fetch the resource with CORS disabled. " and the saved page does not show the images correctly (attached generated file).

[Test Page.zip](https://github.com/gildas-lormeau/SingleFile/files/5888581/Test.zip)

To Reproduce
1. Save the following web page: https://about.disqus.com/disqus-demo-page

Screenshots
![image](https://user-images.githubusercontent.com/78163576/106166646-25e39980-616b-11eb-8c0b-3a6115b388a1.png)

Environment
 - OS:  Win10 Pro x64
 - Browser: Chrome  88.0.4324.104

**Comment by gildas-lormeau** [comment]
This is normal and this should not prevent the page to be captured properly. This is due to the fact that SingleFile can't download these assets from its content script. However, it can download them from the background page.

**Comment by fakiyor379** [comment]
Is it very complex to catch the CORS exception and download it in the background?

Thanks for your hard work.

**Comment by gildas-lormeau** [comment]
No it is not, that's in fact what SingleFile already does but the browser logs the error anyway.

**Comment by fakiyor379** [comment]
I have tried to see if I can help you, modify the file "\extension\lib\single-file\fetch\content\content-fetch.js", and in line number 58 add this:

```javascript
try{
  if(error == "TypeError: Failed to fetch"){
    let response = await fetch(message.url, { method: "head", mode: "no-cors" });
    if(response.type == "opaque"){
      const _r = await sendMessage({ method: "singlefile.fetch", url: message.url });
      return {
        status: _r.status,
        headers: Object.entries(_r.headers),
        array: Array.from( new Uint8Array(_r.array))
       };
    }
  }
}catch(e){}
```
And it works, but I don't know if it is the best or the correct way, since I am a javascript newbie.
This is the complete file i use: [content-fetch.zip](https://github.com/gildas-lormeau/SingleFile/files/5895946/content-fetch.zip)

**Comment by gildas-lormeau** [comment]
I agree with the principle on how to fix the issue. However, I'm wondering if it's okay to fix the issue with an additional `HEAD` request. I mean these are just logs, the CORS error is catch and handled properly by the extension. The problem I see though is that it's not clear for the user that the cause of these warnings is SingleFile and the strict policy of Chrome.

**Comment by gildas-lormeau** [comment]
This issue is somewhat fixed since Firefox does not show these messages as errors anymore.
