### ISSUE TITLE
Mind map invalid

### ISSUE THREAD

**Issue by da-gongren** [gildas-lormeau/SingleFile#604]
www.processon.com

The downloaded HTML file opens without content

![image](https://user-images.githubusercontent.com/51149477/106388604-42592d80-641a-11eb-8a6b-7c3a26824384.png)

**Comment by gildas-lormeau** [comment]
This is due to the way the site implements the scrolling area. Unfortunately, it can't work properly without JavaScript. Note that the mind map is saved but is offscreen.

**Comment by gildas-lormeau** [comment]
I'm closing the issue because, as far as I know, I cannot fix it.
