### ISSUE TITLE
Mozilla support page causes SingleFile to display "This page cannot be saved with SingleFile"

### ISSUE THREAD

**Issue by SteveS73** [gildas-lormeau/SingleFile#606]
**Describe the bug**
When I tried to save the following Mozilla Support page, the SingleFile icon displays a "stop" icon over the top of itself. Hovering the mouse over the icon displays "This page cannot be saved with SingleFile."  https://support.mozilla.org/en-US/kb/remove-other-bookmarks-folder-from-bookmarks-toolbar#firefox:win10:fx84

**To Reproduce**
1. Go to https://support.mozilla.org/en-US/kb/remove-other-bookmarks-folder-from-bookmarks-toolbar#firefox:win10:fx84
2. Click on SingleFile add-on icon

**Expected behavior**
In the past I've always been able to save such support pages. Maybe it's due to a change by Mozilla?

**Environment**
 - Win10 Pro 1909 64bit
 - Browser:  Firefox
 - Version: 84.0.2 64 bit

**Comment by gildas-lormeau** [comment]
This is a [known issue](https://github.com/gildas-lormeau/SingleFile#known-issues). Browser providers block content scripts of extensions on some domains they own. This can be fixed by removing `support.mozilla.org` from `extensions.webextensions.restrictedDomains` in the `about:config` page.

**Comment by SteveS73** [comment]
Worked, Thanks!

**Comment by bansan85** [comment]
Just to found more easily this page, please found below the default list of restricted url in Firefox:

```
accounts-static.cdn.mozilla.net
accounts.firefox.com
addons.cdn.mozilla.net
addons.mozilla.org
api.accounts.firefox.com
content.cdn.mozilla.net
discovery.addons.mozilla.org
install.mozilla.org
oauth.accounts.firefox.com
profile.accounts.firefox.com
support.mozilla.org
sync.services.mozilla.com
```
