### ISSUE TITLE
Please also create an app in play Store that has same functionality as the extension since neither Firefox not Chrome allows extension in Android.

### ISSUE THREAD

**Issue by shobhitparvan** [gildas-lormeau/SingleFile#609]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered (optional)**

**Additional context (optional)**

**Comment by gildas-lormeau** [comment]
You can actually install SingleFile on Firefox for Android Nightly by following this procedure: https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by gildas-lormeau** [comment]
I'm closing this issue since it can be fixed by using Firefox for Android Nightly.

**Comment by kenmcd** [comment]
> I'm closing this issue since it can be fixed by using Firefox for Android Nightly.

And end up with a bunch of other problems from ALPHA software.
I came here looking for a reason why the extension would not install on my android phone.
And a to find a solution to get it installed.
Using a horrible alpha version of Firefox is not a solution.
Please consider another option if possible.

**Comment by gildas-lormeau** [comment]
You can use Kiwi browser as an alternative.

**Comment by kenmcd** [comment]
> 
> 
> You can use Kiwi browser as an alternative.

That works. Thanks!

**Comment by gildas-lormeau** [comment]
You're welcome!
