### ISSUE TITLE
Suggestion - sha256 fingerprint

### ISSUE THREAD

**Issue by hpiedcoq** [gildas-lormeau/SingleFile#61]
Hi!
Thank you for this really cool extension. I love it.
Could it be possible to generate a fingerprint of the page while saving?

**Comment by gildas-lormeau** [comment]
Hi,
Thank you for your review on the Add-ons page too! Can you give me more details about your use case? Also, where should the hash be stored, in the filename or into the document itself?

**Comment by hpiedcoq** [comment]
Well, very often the pages I save can be used as proofs, or evidence.
Of course I can generate a hash after saving, but it could be useful to automatically do it as an option.
The hash could be computed on the exit file itself, so it would forbid to modify it. Or at least mitigate this risk. I don't know if the hash can be stored directly in the saved file, but yes, filename could be ok.

I don't know how relevant is this suggestion and the time/resources it would need, comparing to the benefits.

But thank you for having considered this question so far. ;)

**Comment by gildas-lormeau** [comment]
I fixed the issue in 1.6.14. You can now customize the file name of the saved page (cf. Options > File name > template) and append for example a SHA-256 hash. See the help page in the extension for more info.
