### ISSUE TITLE
do not work on palemoon browser

### ISSUE THREAD

**Issue by okpapt** [gildas-lormeau/SingleFile#611]
Hello,
Do not work on palemoon web browser based on firefox mozilla.
http://www.palemoon.org/
Thank you.

**Comment by gildas-lormeau** [comment]
It does not work because palemoon does not support Web Extensions.

**Comment by okpapt** [comment]
https://addons.palemoon.org/extensions/

Ok thank you.

I think is same problem with https://www.seamonkey-project.org/ 
https://www.seamonkey-project.org/community#addons

Have

**Comment by gildas-lormeau** [comment]
Yes, this is the same problem. Unfortunately, it represents too much work for me to make SingleFile compatible with palemoon/SeaMonkey.

**Comment by okpapt** [comment]
Work fine with torch and vivaldi, problem with brave.
https://brave.com/fr/  
I have problem to install from 
https://chrome.google.com/webstore/category/extensions

**Comment by gildas-lormeau** [comment]
What kind of problem do you have with Brave? I just did a test with the latest version of Brave and I was able to use SingleFile without any particular issue.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because porting SingleFile to Palemoon would require a significant amount of time. Feel free to keep me updated with the issue o Brave though.
