### ISSUE TITLE
This Type of Icon is Shown as A Rectangle

### ISSUE THREAD

**Issue by huhiha** [gildas-lormeau/SingleFile#613]
**Describe the bug**
Some icon/picture is shown as a rectangle.

**To Reproduce**
1. Go to [this page](https://a2zapk.com/1004482-advanced-root-checker-pro-1-4-1-paid-a2z.html)
2. Save the page using SingleFile. 

**Screenshots**
The icon at the top of the web page:
![image](https://user-images.githubusercontent.com/32677299/107947731-c3ddbd80-6fcd-11eb-9cf5-21cad5a5667c.png)
It is not correctly shown in the downloaded file:
![image](https://user-images.githubusercontent.com/32677299/107947673-ac063980-6fcd-11eb-8eae-6a668b769d78.png)

Info about the element:
![image](https://user-images.githubusercontent.com/32677299/107948075-51211200-6fce-11eb-85fc-165fdc4410e8.png)

**Comment by gildas-lormeau** [comment]
Thank you for having reported this issue. It will be fixed in the version 1.18.67 that I'm going to publish.
