### ISSUE TITLE
The default way to open the options page

### ISSUE THREAD

**Issue by dnknn** [gildas-lormeau/SingleFile#614]
1) Right-click the SingleFile trayIcon on the toolbar, 2) clicking  `Option`

- ##  **Current opening:** 
　　　`chrome://extensions/?options=mpiodijhokgodhhofbcjdecpffjipkle`

- ## **Expected opening:**
　　　`chrome-extension://mpiodijhokgodhhofbcjdecpffjipkle/extension/ui/pages/options.html`

- **Why need do this ? :** 
　　　complete in one step ^_^

- ## 💡 **How to achieve:**
　　　Changed by default, or Add an ⬜OFF/ON☑ option for this.

**Comment by gildas-lormeau** [comment]
Unfortunately, this is not technically possible to add an option for this. What's wrong with chrome://extensions/?options=mpiodijhokgodhhofbcjdecpffjipkle?

**Comment by dnknn** [comment]
> What's wrong with

- This type of page cannot be translated.  `chrome-extension://..../extension/ui/pages/options.html` can.
- 

In fact, No big problem or not problem.

**Comment by gildas-lormeau** [comment]
I think this might considered as a bug in Chrome though. Maybe you could create a ticket on crbug.com.
