### ISSUE TITLE
The right-click menu of extension toolbar not have `menuViewPendingSaves`

### ISSUE THREAD

**Issue by dnknn** [gildas-lormeau/SingleFile#615]
`menuViewPendingSaves`

There are right-click menu items on the page, but the extension toolbar does not,
can you add it ?

Because the page menu is disabled...

**Comment by gildas-lormeau** [comment]
The entry *is* present but Chrome refuses to display it. Firefox does not, see below.

![image](https://user-images.githubusercontent.com/396787/108107557-b4bf4400-708f-11eb-84c1-e6d34ae5a84c.png)

**Comment by dnknn** [comment]
OK, thank you !
