### ISSUE TITLE
Way to organise and browse downloaded HTML files

### ISSUE THREAD

**Issue by Mohan-cloud** [gildas-lormeau/SingleFile#616]
Hello. I apologize if this is not the right place for this issue. I am looking for a way (preferably a web interface) with browse, search and tagging features. How do you guys manage to do this?

**Comment by gildas-lormeau** [comment]
I would recommend to take a look at:
 - ArchiveBox: https://github.com/ArchiveBox/ArchiveBox
 - Zotero: https://www.zotero.org

Both products integrate SingleFile to save web pages as snapshots. 

The ArchiveBox project also hosts a Wiki that compiles a huge list of tools used for archiving here: https://github.com/ArchiveBox/ArchiveBox/wiki/Web-Archiving-Community

**Comment by Mohan-cloud** [comment]
Is it possible to annotate and highlight before saving to archive box just like in SingleFile?

**Comment by gildas-lormeau** [comment]
I don't think this is possible with ArchiveBox.

**Comment by gildas-lormeau** [comment]
Maybe WebScrapbook would fulfill your needs, see https://github.com/danny0838/webscrapbook.

**Comment by Mohan-cloud** [comment]
Thanks for your suggestion. Played around a little, buggy on my system but looks promising. I'll explore more.

**Comment by gildas-lormeau** [comment]
I moved this question here: https://github.com/gildas-lormeau/SingleFile/discussions/629
