### ISSUE TITLE
I must be missing something, how do I disable auto-save?

### ISSUE THREAD

**Issue by falcorr** [gildas-lormeau/SingleFile#617]

**Comment by gildas-lormeau** [comment]
The same way you enabled it, right-click on the page or the SingleFile icon, select `SingleFile > Auto-save > Disabled`

**Comment by falcorr** [comment]
The context menu on the extension icon in Chrome doesn't seem to mention auto-save. I've also tried unchecking autosave in the extension options but it merely toggles between autosaving on page load and unload.

**Comment by falcorr** [comment]
Ah, it shows on right-click on the page but not in the icon's context menu.
