### ISSUE TITLE
Download linked images

### ISSUE THREAD

**Issue by nicrame** [gildas-lormeau/SingleFile#619]
Sometimes i download websites that got some thumbnail images that i would like to see in full size when i click on them. But inside saved html file i got thumbnails only, not full size images (that are usually linked from thumbnails).
It would be cool to have option to download and put inside all linked images, so they wouldn't have to be downloaded from outside on click.

**Comment by gildas-lormeau** [comment]
I agree that it would be cool but it would also be quite complicated to develop though.

**Comment by DejayRezme** [comment]
I know this is closed / won't fix, but just to add an idea: 
There is an addon called "imagus" that enlarges images on mouse over and has "sieves" to work on many websites. This could be used to implement this functionality for singlefile.

**Comment by FLAGEL** [comment]
> I know this is closed / won't fix, but just to add an idea: There is an addon called "imagus" that enlarges images on mouse over and has "sieves" to work on many websites. This could be used to implement this functionality for singlefile.

For anyone who happens to come across this thread in the future, it is worth noting that the "Imagus" extension (at least on Chrome) does not work with all pages (i.e. it is not universal but seems to rely on per-site settings).

Further, having Imagus configured to pre-load all images at the time of loading the site will not save said pictures in a SingleFile-copy. This is the case even when SingleFile is configured to not block scripts.
