### ISSUE TITLE
Facebook comment thread didn't work

### ISSUE THREAD

**Issue by stuaxo** [gildas-lormeau/SingleFile#62]
It just displays ERR in the singlefile icon when I press it.

**Comment by stuaxo** [comment]
Well, it worked this time (browser probably had a few less tabs going this time)

Firefox did pop up the message saying a script was taking too long, but it disappeared as the script finished on time.

Last night when I tried it, it took too long and got killed by FF a couple of times.

**Comment by gildas-lormeau** [comment]
Indeed, I optimized a little bit the code related to the initialization phase yesterday. I guess (and I hope) it explains why we cannot reproduce it.
