### ISSUE TITLE
Google docs sheets gives A server error occurred.  Please press 'Reload' in your browser.

### ISSUE THREAD

**Issue by testz-99** [gildas-lormeau/SingleFile#621]
**Describe the bug**
When opening https://docs.google.com/spreadsheets/* gives server error

**To Reproduce**
opening https://docs.google.com/spreadsheets/* 

**Expected behavior**
no server error

**Environment**
 - Windows 10
 - Chrome and Firefox
 -  88.0.4324.190, 86.0

**Additional context**
If disabled it loads https://docs.google.com/spreadsheets/* correctly

**Comment by gildas-lormeau** [comment]
Thank you for having reported the issue and sorry for the inconvenience. I was able to reproduce the issue. I uploaded the new version 1.18.71, it should be available for download in the coming hours.

**Comment by gildas-lormeau** [comment]
The update is available on the store of Google.
