### ISSUE TITLE
Bug : extension hotkey doesn't work anymore...

### ISSUE THREAD

**Issue by dnknn** [gildas-lormeau/SingleFile#623]
It used to be valid before, but it became invalid after an update.

1. open this page 👇

`chrome://extensions/shortcuts#invalid:~:text=SingleFile&text=Save the selected tabs or their selected contents`

2. set a hotkey to test,

3. hotkey is not works  (Reproduce)

![image](https://user-images.githubusercontent.com/10995302/109856181-299b9c00-7c94-11eb-8087-994415097cb9.png)

**Comment by gildas-lormeau** [comment]
Thank you and sorry for the inconvenience. I made a lot of changes in the structure of the code of SingleFile and I forgot to test if the keyboard shortcut was still working. It's fixed in the version 1.18.74 I just uploaded.
