### ISSUE TITLE
Version 1.18.74: notes aren't saved

### ISSUE THREAD

**Issue by DenB10** [gildas-lormeau/SingleFile#624]
Hello,
As said in the title, the notes created with SingleFile 1.18.74 are not saved. Can you confirm this bug?
Thank you,
DenB10

**Comment by gildas-lormeau** [comment]
I confirm I was able to reproduce the issue. I'm sorry for this inconvenience. It's fixed in the version 1.18.75 I just uploaded.

**Comment by DenB10** [comment]
You don't have to be sorry!
Thank you very much for your responsiveness.
