### ISSUE TITLE
Support opened local files

### ISSUE THREAD

**Issue by brandonkal** [gildas-lormeau/SingleFile#625]
**Is your feature request related to a problem? Please describe.**

It does not function with opened files (at least on macOS and Vivaldi).

**Describe the solution you'd like**

I'd like to see support for opened files.

My use case is thus: I use Calibre to convert my eBook to HTMLZ and then extract that as a zip file. I then add some CSS of my own and then use this extension as a simple way to get the external CSS stylesheet and images embedded into a single HTML file.

**Describe alternatives you've considered (optional)**

Right now my work-around is to run a local fileserver on a folder of HTML but it would be ideal to avoid this step if possible.

**Comment by gildas-lormeau** [comment]
I moved this question here: https://github.com/gildas-lormeau/SingleFile/discussions/627
