### ISSUE TITLE
Cannot Turn SingleFile Auto-save Off After Enabling Auto-save

### ISSUE THREAD

**Issue by teachernightowl** [gildas-lormeau/SingleFile#626]
# Cannot Turn SingleFile Auto-save Off After Enabling Auto-save

### The Bug

Once SingleFile Auto-save is enabled, auto-save cannot be turned off without either disabling or uninstalling the extension. 

### To Reproduce

1. Confirm OS is Ubuntu 20.04.2 LTS
1. Confirm Firefox is 86.0
1. Create a new Firefox profile
1. Add [SingleFile](https://addons.mozilla.org/en-US/firefox/addon/single-file/?utm**source=addons.mozilla.org&utm**medium=referral&utm**content=search) to Firefox
1. Confirm auto-save is not enabled by doing some browsing in different tabs and confirming pages are NOT being saved.
1. Enable Auto-save by right clicking in an empty spot on web-page and choosing _SingleFile > Auto-save > Auto-save all tabs_
1. Do some more browsing in different tabs to confirm auto-save IS saving browsed pages.
1. Try to disable Auto-save by right clicking in an empty spot on web-page and choosing _SingleFile > Auto-save > Disabled_
1. Do some more browsing in different tabs. Auto-save should NOT be saving pages and in my case auto-save WAS saving pages.

### Expected behavior

Some way to disable SingleFile auto-save without needing to disable or uninstall the extension.

### The Environment

* OS: Linx - Ubuntu 20.04.2 LTS 
* Browser: Firefox 86.0
* Extension: SingleFile 1.18.77

### The Context

SingleFile auto-save was disabled. I enabled auto-save from the right click context menu on web page by using this sequence: _Right click > SingleFile > Auto-save > Auto-save all tabs_

Then I did the work I needed to do. 

After I was finished, I tried to disable auto-save using similar steps: _Right click > SingleFile > Auto-save > Disabled_

SingleFile kept downloading each and every page in every tab.

### Things I Have Tried

So I went to add-on preferences and tried the following...

* Uncheck _about:addons > SingleFile > Preferences > Auto-save > auto-save after page load or on page unload_ 
    - **Result:** "auto-save after page load" automatically becomes checked. If I try unchecking "auto-save after page load", "auto-save after page load or on page unload" becomes checked again and I cannot figure out a way to get both "auto-save after page load" and "auto-save after page load or on page unload" and  unchecked at the same time.
* _about:addons > SingleFile > Preferences > Reset > Reset all options_
    - **Result:** Auto-save is still enabled.
* Reduce browser to a single tab, _Right click > SingleFile > Auto-save > Disabled_ and then closed the browser. 
    - **Result:** When I open the browser again, auto-save is still working.
* Remove SingleFile Add-on, close browser, re-open browser, and reinstall SingleFile.
    - **Result:** Auto-save is disabled until I enable auto-save again. After auto-save is has been enabled, we are back to where we were earlier and are not able to disable the auto-save function.
* Disable the SingeFile extension.
    - **Result:** Auto-save is also disabled. 

### Observations

Was [Issue 455](https://github.com/gildas-lormeau/SingleFile/issues/455) a similar bug?

**Comment by gildas-lormeau** [comment]
Thank you for the detailed report and sorry for the inconvenience. I was able to reproduce and fix the issue. The fix is available in the version 1.18.78 I just uploaded. Hopefully, it will be published today (after having been reviewed).
