### ISSUE TITLE
Save to specific folder

### ISSUE THREAD

**Issue by namaljayathunga** [gildas-lormeau/SingleFile#630]
Thank you for the awesome extension. Could you please add an option to save the file to a specific folder?

    (Right Click on a Webpage) > SingleFile > Save Page to Specific Folder > (Recent Locations, Pined Locations, Browse Location)

At least Browse Location

Thanks.

**Comment by gildas-lormeau** [comment]
This is unfortunately technically impossible to implement such a feature in a web extension today. You can still make SingleFile open the "Save as" dialog by checking the option `File name > open the "Save as" dialog to confirm the file name`.

**Comment by kupietools** [comment]
This has stopped working. Until previously, when I saved a page, it opened a standard save dialog, so I could navigate to the location where I need it. Now, checking the "File name > Open Save as Dialog To Confirm" only asks me for a filename, doesn't allow me to go to the folder I need to save the page in. I tried all the other options, too, including "SingleFile Companion Lite" which does nothing that give an error. It's a real shame, this just seems to have happened in the las tfew weeks, and it's completely reduced this extension from constant use (I do a lot of research) to total unusability... if everything winds up together in one folder, and I have to go in and sort through it manually and put things where I need them, I might as well just copy and paste out of web pages.  

It would be great to get the "Save As" dialog back.

**Comment by kupietools** [comment]
If anybody winds up here looking for an answer to this like I did, the above solution doesn't work anymore (It asks for a filename, doesn't actually open the "Save As" dialog to let you pick a folder), but it's not a Firefox limitation, the extension "Save Page WE" can do it. (I'm not connected to that extension, I just found it looking for a replacement for SingleFile since I can't figure out how to make it do this anymore.)

**Comment by LinuxOnTheDesktop** [comment]
> If anybody winds up here looking for an answer to this like I did, the above solution doesn't work anymore 

Oh dear!

I could not even find documentation about where the program saves (or at least saves by default). The place seems to be: the desktop.
