### ISSUE TITLE
Images is not included for note.youdao.com

### ISSUE THREAD

**Issue by yfdyh000** [gildas-lormeau/SingleFile#633]
**Describe the bug**
The images cannot be saved for display on the note.youdao.com website.
A user asked me to report this bug, he does not speak English.

**To Reproduce**
1. Open https://note.youdao.com/ynoteshare1/index.html?id=fe24e37aeda9a6597b4dd21a3350dcb1&type=note
2. Save to an html file with the SingleFile.
3. Open and check the result.

**Expected behavior**
Save and display all the images and content in the note.

**Screenshots**
good:
![2021-03-15_155108_msedge](https://user-images.githubusercontent.com/1769875/111120437-4e521680-85a6-11eb-91ca-84baa34c1284.png)
bad:
![2021-03-15_155114_msedge](https://user-images.githubusercontent.com/1769875/111120443-4f834380-85a6-11eb-928f-76b25bcc1646.png)

**Environment**
 - OS: Win10
 - Browser: Edge
 - Version: 89. SingleFile 1.18.78.

**Additional context**
The add-on options does not seem to affect it.

**Comment by gildas-lormeau** [comment]
I confirm I was able to reproduce the issue in Chrome but not in Firefox. I will take a closer look at this problem but I guess this is probably a regression in Chrome.

**Comment by lyjhyjyes** [comment]
> **Describe the bug**
> The images cannot be saved for display on the note.youdao.com website.
> A user asked me to report this bug, he does not speak English.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Open https://note.youdao.com/ynoteshare1/index.html?id=fe24e37aeda9a6597b4dd21a3350dcb1&type=note
> 2. Save to an html file with the SingleFile.
> 3. Open and check the result.
> 
> **Expected behavior**
> Save and display all the images and content in the note.
> 
> **Screenshots**
> good:
> ![2021-03-15_155108_msedge](https://user-images.githubusercontent.com/1769875/111120437-4e521680-85a6-11eb-91ca-84baa34c1284.png)
> bad:
> ![2021-03-15_155114_msedge](https://user-images.githubusercontent.com/1769875/111120443-4f834380-85a6-11eb-928f-76b25bcc1646.png)
> 
> **Environment**
> 
> * OS: Win10
> * Browser: Edge
> * Version: 89. SingleFile 1.18.78.
> 
> **Additional context**
> The add-on options does not seem to affect it.

谢了。补充一下，我用的是chrome89，保存html后其他内容显示正确，只有图片没显示，没法抓取。配置文件默认，没调过

**Comment by gildas-lormeau** [comment]
Thank you, it was in fact a regression (I guess) in SingleFile, it's fixed in the version 1.18.79 I just uploaded.

**Comment by lyjhyjyes** [comment]
> Thank you, it was in fact a regression (I guess) in SingleFile, it's fixed in the version 1.18.79 I just uploaded.

sorry,i use chrome 89,singlefile 1.18.79,it does not work in https://note.youdao.com/ynoteshare1/index.html?id=fe24e37aeda9a6597b4dd21a3350dcb1&type=note ,picture can not be  be displayed

**Comment by gildas-lormeau** [comment]
@lyjhyjyes I did the test again and I cannot reproduce your issue. Did you change any setting in SingelFile?

**Comment by lyjhyjyes** [comment]
> @lyjhyjyes I did the test again and I cannot reproduce your issue. Did you change any setting in SingelFile?
i choose "remove frame",so it does not work.thanks
now it works

**Comment by gildas-lormeau** [comment]
Indeed this website uses frame so you have to activate the corresponding option. Thank you for the feedback.
