### ISSUE TITLE
On before capture event does not fire in the CLI.

### ISSUE THREAD

**Issue by uotsz** [gildas-lormeau/SingleFile#640]
**Describe the bug**
I am using SingleFile in CLI mode.  The normal capturing works. But when I add a script through the --browser-script parameter, the script does not have any effect. I print some log in the script and use --browser-debug to check the console output then discovered that the "single-file-on-before-capture-request" listener have never been triggered. 

**To Reproduce**
1. Run ./single-file --browser-script "replace-string-script.js"  https://example.com  output1.html
2. Run ./single-file https://example.com output2.html
3. output1.html and output2.html have the same content. 

**Expected behavior**
The script specified by --browser-script should change the content.

**Environment**
 - OS: [Ubuntu, Docker]
 - Browser: [Chrome, Chromium]

**Additional context**
Do I have a misunderstanding in the purpose of --browser-script? Is "single-file-on-before-capture-request" only triggered by clicking the extension/addon button on the browser but not in the CLI mode?

**Comment by gildas-lormeau** [comment]
It was a regression and it's fixed in the last commit. Don't forget to dispatch the event `single-file-user-script-init` when the script starts and it should work as expected.
