### ISSUE TITLE
Viewing html files after original web page has been deleted?

### ISSUE THREAD

**Issue by motreo** [gildas-lormeau/SingleFile#641]
I'm new to SingleFile and haven't encountered this scenario yet. What happens when the original web page used to create an html file is deleted? Can the html file still be viewed? For reference I've mostly been using SingleFile to capture Reddit threads.

**Comment by gildas-lormeau** [comment]
Yes, you will still able to view the saved page. Actually, you can test it by disabling your internet connection temporarily and open some pages saved with SingleFile.

**Comment by motreo** [comment]
@gildas-lormeau Great! I was hoping I could use SingleFile as an alternative to the Wayback machine, and it looks like it fits my use case perfectly :)

**Comment by gildas-lormeau** [comment]
Yes, that should do the job :)
