### ISSUE TITLE
Webpages cannot be saved with latest versions at all in Kiwi Browser

### ISSUE THREAD

**Issue by ProjectX666** [gildas-lormeau/SingleFile#643]
**Describe the bug**
Webpages cannot be saved with latest versions at all(singlefile 1.18.72+ or singlefilez 1.0.11+).

What's worse,texts in settings cannot be correctly displayed either.

**To Reproduce**
1. Before using,I have checked all permissions that my browser and this extension need are open.
2. Then I tried to save a page that singlefile 1.18.69 can save -- it did not work!
3. In the end I tried to open the settings page...Almost all texts were gone!?

**Expected behavior**
I just wanna save a page...

**Screenshots**
![Uploading IMG_20210318_153303.jpg…]()

![Uploading IMG_20210318_154300.jpg…]()

**Environment**
 - OS: [e.g. , Android 11]
 - Browser: [Kiwi Browser]
 - Version: [Git210216Gen570536402]

**Additional context**
Thanks to developers, I had a better time with my browser.

I will really appreciate you when this bug can be fixed!

(And I am sorry to bother you with machine translation

**Comment by ProjectX666** [comment]
![IMG_20210318_153303](https://user-images.githubusercontent.com/80380868/111597025-cafa1600-879b-11eb-94ae-bd9731f083bf.jpg)

**Comment by ProjectX666** [comment]
![IMG_20210318_154300](https://user-images.githubusercontent.com/80380868/111597146-e7964e00-879b-11eb-99a6-6a4bb5c27dfc.jpg)

**Comment by gildas-lormeau** [comment]
I fixed the issue. This is due to the fact that the code of Kiwi is outdated. I suspect it hasn't really been updated for at least 2 years. Thus, from a security point of view, I would not recommend using this browser. As as alternative, I highly recommend using SingleFile with Firefox Nightly for Android.

**Comment by ProjectX666** [comment]
Thanks so much!
