### ISSUE TITLE
SingleFile replaces <img> src attributes of some images in a certain page

### ISSUE THREAD

**Issue by lkintact** [gildas-lormeau/SingleFile#645]
**To Reproduce**
1. Create a new Firefox profile, add SingleFile to it (don't enable "Allow this extension to run in Private Windows" when adding SF).
2. Navigate to http://www.photographers1.com/Sailing/NauticalTerms&Nomenclature.html (that's a glossary of sailboarding and sailboating terms).
3. Save the page with SF, open the saved file.
4. Search for `YOU MUST GIVE WAY TO VESSELS IN BLACK DANGER ZONE` in the page. One match will be found with an image below - a white ship hull in a circle with black sector, titled "Bearings of Objects in Relation to Your Vessel". Right-click on the image and Ctrl-click on "View Image". An empty tab at the address `data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="1449" height="1618"><rect fill-opacity="0"/></svg>` opens.
5. Search for `Prevailing Wind - the normal wind direction for a specific area and season`. A match will be found with an image to the left - a world wind map, titled "Prevailing Winds of the World". Right-click on the image and Ctrl-click on "View Image". An empty tab opens, its address is `data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="300" height="152"><rect fill-opacity="0"/></svg>`.

**Expected behavior**
The tabs at steps 4 and 5 should contain the respective images. Their addresses should start with `data:image/gif;base64` and `data:image/png;base64`, respectively.

I compared the sources of the files created with SF and the Firefox's "Save page as..." feature, and it seems for some reason SF replaces the "src" attributes in the \<img\> tags for those two pics. Other images seem unaffected.

**Environment**
 - OS: Windows 10 Home 1803,
 - Browser: Firefox version 86.0.1 (32-bit)
 - SingleFile version 1.18.79.

**Comment by gildas-lormeau** [comment]
This is a feature. It allows SingleFile to reduce the size of pages containing multiple times the same image. Uncheck `Images > group duplicate images together` to disable it.

**Comment by lkintact** [comment]
Got it, thank you, the checkbox was indeed on.
However there are situations when an image is displayed shrunk in the page and to view it in full size for details you need the Right-click -> "View Image" functionality to work: for example, on my machine the [first image's](http://www.photographers1.com/Sailing/Bearings.gif) computed dimensions are 350x400px, which makes reading its text somewhat difficult, while the file itself is 1449x1618px.
Maybe the feature should be somehow altered to still allow opening duplicate images in separate tabs/windows for cases like that?

**Comment by gildas-lormeau** [comment]
Actually, what you described is the drawback of the technique I use. Currently, I don't know how to implement what you described without inserting a script in the saved page. I would prefer avoiding this.

**Comment by gildas-lormeau** [comment]
I fixed the issue in SingleFileZ. I prefer to keep the option enabled by default because the default settings of SingleFile are optimized to make the page as small as possible. I think that disabling it would question the usefulness of the default settings.

**Comment by lkintact** [comment]
No-no, I didn't mean to suggest that you change the defaults, I only meant that for me personally, and for that particular page using SingleFile with `group duplicate images together` disabled would be a better choice.
And thanks for fixing the issue with SingleFileZ.

**Comment by gildas-lormeau** [comment]
You could do that with an auto-setting rule actually. This is what they are intended for (e.g. applying a set of specific settings on a website).

**Comment by lkintact** [comment]
Thanks for reminding about auto-settings. I think the issue can be closed, please reopen if you disagree.
