### ISSUE TITLE
Can I do this with your repo.

### ISSUE THREAD

**Issue by zydjohnHotmail** [gildas-lormeau/SingleFile#648]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Hello:
Your repo looks good. But I want to know if I can use your repo for the following job:
If you have ever shopped in https://www.amazon.com/, you know that you can shop many items in different category, and finally, check out when you done, then pay the total bills in one place.
There is a similar web site, there are about 3 children pages, just like different categories in Amazon, I have to visit each of the 3 pages, and select one item from each page, each have about 100 items, then click a button to check out or submit the form (HTTP Post).
What I want to do is: I want to use your repo to create one total page, in which all the 3 children pages are inside this total page, also add some additional JavaScript, so I can select one item from each page, and submit the form.
In short, the only thing to do differently is: in stead of visiting one page 3 times, I want to merge all 3 pages to make one page. The advantage is: I don’t have to visit so many different pages, I can stay in the total page.
The old way of data flow is like this:
A. visit https://www.child_page1.com/, click to select item #1,
B. visit https://www.child_page2.com/, click to select item #2,
C. visit https://www.child_page3.com/, click to select item #3,
D. click a submit form button under the last item #3, then submit the form.
What I want to do now is:
A. Create a frame of a total page,
B. Load https://www.child_page1.com/ and append it as one HTML element. (I think maybe Jquery parseHTML can add an array of DOM objects inside one element, like DIV)
C. Load https://www.child_page2.com/ and append it as one HTML element. (I think maybe Jquery parseHTML can add an array of DOM objects inside one element, like DIV)
D. Load https://www.child_page3.com/ and append it as one HTML element. (I think maybe Jquery parseHTML can add an array of DOM objects inside one element, like DIV)
E. From each newly added elements, pick up one element, and finally submit the form. In other words, I want to make one big DOM includes all 3 children pages, then I can use JavaScript to select DOM nodes, like: getelementsbyclassname, and then click on the selected DOM nodes, and finally click on the submit form button.
There are a few other additional JavaScripts, work like adding items to shopping cart, and finally submit the form using HTTP Post.
I think your repo can save the current page into one file, but my request goes one step further: I need to save 3 pages within the same parent domain into one file, or better into one big DOM, so I can use the JavaScript to select some elements in each different pages, but submit the form from the only one big DOM file.
Thanks,

**Describe alternatives you've considered (optional)**

**Additional context (optional)**

**Comment by jtagcat** [comment]
Yes, terms apply. https://github.com/gildas-lormeau/SingleFile/blob/master/LICENSE

**Comment by zydjohnHotmail** [comment]
Hello:
If yes, then can you give me some basic ideas on how to do this.
Thanks,

**Comment by jtagcat** [comment]
Then start coding. /s

It seems you don't have much idea, this is probably the wrong thing for the job.

You're probably looking for browser automation. A point and click solution could be [Parsehub](https://www.parsehub.com).

**Comment by gildas-lormeau** [comment]
@zydjohnHotmail  Most of  what you described is not really related to SingleFile and I don't think SingleFile will really help you. I think the best way to achieve this would be to code a [Puppeteer](https://github.com/puppeteer/puppeteer) script, for example. But that's not necessarily easy... Maybe, Parsehub could do the job, I never used it.

**Comment by gildas-lormeau** [comment]
I'm closing this issue as out of scope.
