### ISSUE TITLE
Ability to save multiple levels

### ISSUE THREAD

**Issue by Oranko** [gildas-lormeau/SingleFile#652]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to save multiple levels from a website.
For example if i save example.com and it has links to sub web pages example.com/page1 and example.com/page2
It should download both the subpages as well such that they can be navigated to even when offline.
Like in wget we get -r -l2 
The depth can be customized to go only 1 level deep or anything else 

**Describe alternatives you've considered (optional)**

**Additional context (optional)**

**Comment by gildas-lormeau** [comment]
This can be done with the option `--crawl-max-depth` when using SingleFile from the [command line interface](https://github.com/gildas-lormeau/SingleFile/tree/master/cli).

**Comment by github-account1111** [comment]
> 
> 
> This can be done with the option `--crawl-max-depth` when using SingleFile from the [command line interface](https://github.com/gildas-lormeau/SingleFile/tree/master/cli).

That wouldn't be a wysiwyg copy though, would it?

**Comment by byzod** [comment]
> 
> 
> This can be done with the option `--crawl-max-depth` when using SingleFile from the [command line interface](https://github.com/gildas-lormeau/SingleFile/tree/master/cli).

I follow the tutorial but stuck at this step

> Make single-file executable (Linux/Unix/BSD etc.) if SingleFile is not installed globally.
> `chmod +x single-file`

`chmod` is not available on windows, what should I do next?

**Comment by gildas-lormeau** [comment]
@byzod I'm a Windows user so the instructions should work. Regarding the error in the screenshot, did you try to use `--browser-executable-path` to pass the the path to Firefox?

**Comment by byzod** [comment]
Not working

btw it broken my about:new-tab, twice

I have to reset my firefox to get it back, twice

I won't test this **** anymore, I don't have the time to reset and re-config my firefox the third time

![2](https://user-images.githubusercontent.com/848607/127638682-93c57547-ddc3-49bb-9e18-1c2b714176c1.png)

**Comment by gildas-lormeau** [comment]
@byzod Nobody forced you to test my personal project. Please write and use your own. Thanks!

**Comment by kekkc** [comment]
Many thanks gildas for the great SingleFile FF extension (that completely replaced all my MHT files).

Regarding the question from Oranko: are there any plans to include a "Ability to save multiple levels" function in the SingleFile FF extension? Would help enormously in order to save sites with images that link the original size of the image, e.g. blogspot.

Currently I have to save the original linked image, convert it to base64, edit the webpage locally to add the <img src="base64"> and then save the page via SingleFile.

**Comment by gildas-lormeau** [comment]
@kekkc Right now, the priority is to finish the work of migrating the code to the Manifest V3. Currently, maybe [SingleFileZ](https://github.com/gildas-lormeau/SingleFileZ) could help you though. It would remove the need of converting the image to base64.
