### ISSUE TITLE
Ability to exclude certain element

### ISSUE THREAD

**Issue by emil-alexandrescu** [gildas-lormeau/SingleFile#653]
**Is your feature request related to a problem? Please describe.**
Currently I am facing issues that I need to hide some elements on captured content.

**Describe the solution you'd like**
It would be great if there is option to exclude certain DOM element on the page. By ID or by classname or query selector.

**Comment by gildas-lormeau** [comment]
Today, there is no option for doing this. However, this can be achieved by running a user script before the page is saved, see https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved for more info. 
You would just have to run a script similar to this one. In this example, the script will remove all the elements having the class `ad` just before saving the page.

```js
const removedElementsSelector = ".ad";
dispatchEvent(new CustomEvent("single-file-user-script-init"));

addEventListener("single-file-on-before-capture-request", () => {
  document.querySelectorAll(removedElementsSelector).forEach(element => element.remove());
});
```

**Comment by gildas-lormeau** [comment]
I'm closing the issue because I think that's what user scripts are intended for. I know however that even though this is powerful feature, it's also not very user-friendly.

**Comment by emil-alexandrescu** [comment]
@gildas-lormeau I can't get the script running... Should it be initialized as soon as the page is loaded?

**Comment by gildas-lormeau** [comment]
@emil-alexandrescu No it does not. Can you describe how you integrate the script (e.g. what user-script extension you use)?

**Comment by emil-alexandrescu** [comment]
@gildas-lormeau Thanks for quick response. In which file I should use this header, and where to put the file?

**Comment by gildas-lormeau** [comment]
@emil-alexandrescu Follow this procedure: https://github.com/gildas-lormeau/SingleFile/issues/493

At step 9, use the following script:
```js
// ==UserScript==
// @name         Exclude elements
// @namespace    https://github.com/gildas-lormeau/SingleFile
// @version      1.0
// @description  [SingleFile] Exclude elements
// @author       Gildas Lormeau
// @match        *://*/*
// @grant        none
// ==/UserScript==

const removedElementsSelector = ".ad";
dispatchEvent(new CustomEvent("single-file-user-script-init"));
addEventListener("single-file-on-before-capture-request", () => {
  document.querySelectorAll(removedElementsSelector).forEach(element => element.remove());
});
```

**Comment by emil-alexandrescu** [comment]
Got it. Let me try it out. Thanks!
