### ISSUE TITLE
Saving to Home directory instead of Downloads directory on Linux Firefox

### ISSUE THREAD

**Issue by LinuxJoeUser** [gildas-lormeau/SingleFile#655]
First of all, thanks for your work here.  I love the simplicity of saving webpages using *Singlefile*.  

It seems *Singlefile* is supposed to --- or in fact [is only supposed to be able to](https://github.com/gildas-lormeau/SingleFile/issues/562) --- save its files into the filesystem's *Downloads* folder or a sub-folder.  If this is so, then it's not working on Firefox on Linux.

 On Firefox (87) on Linux (Linux Mint XFCE 20 and Ubuntu XFCE 20.04) saves aren't made to the *Downloads* (/home/user/Downloads) folder but instead to the user's *Home* folder (/home/user).

I have tested this on the two Linux distros mentioned above with both a *Downloads* folder and a shortcut link to a *Downloads* folder on another partition, it makes no difference.  (Actually I'd like to see a *Singlefile* sub-folder within _Downloads_, but I'll put that in as a separate issue/enhancement).

Unless this is supposed to be this way on Linux, please fix this.

Thank you.

**Comment by gildas-lormeau** [comment]
Is the `Downloads` folder configured in the options page of Firefox about:preferences#general? (cf. Files and Application > Copy) 

This is the folder that is used by extensions to save files.

**Comment by LinuxJoeUser** [comment]
> _Is the Downloads folder configured in the options page of Firefox about:preferences#general? (cf. Files and Application > Downloads)_

Yes (please see screenshot below).

> _This is the folder that is used by extensions to save files._

It may be, but _Singlefile_ is **not** using it.  _Singlefile_ makes a folder in `/home/user` and saves **there** instead, **not** in the `Downloads` folder. (please see screenshot below).

![singlefile3](https://user-images.githubusercontent.com/23580979/118137264-021f2900-b3d3-11eb-863d-241bb682c33d.png)

**Comment by LinuxJoeUser** [comment]
I sorted it, thank you.  Looks like maybe a bug in Firefox's use of links.

**Comment by gildas-lormeau** [comment]
Thanks for digging into the problem, that was my intuition too (i.e. a bug in Firefox).
