### ISSUE TITLE
[Suggestion]: Save to a "Singlefile" sub-folder by default

### ISSUE THREAD

**Issue by LinuxJoeUser** [gildas-lormeau/SingleFile#656]
I'd like to have the option to have all my *Singlefile* downloads go into their own folder, a sub-folder of whatever folder they're currently being downloaded to.  This could be set as an option in preferences (like under the "Destination" options dropdown) or just the default behaviour; both would be fine with me.

I imagine it wouldn't be hard to code into the add-on, and having a "Singlefile" destination folder would extend *Singlefile*'s role in getting and organizing webpages for offline use.

Keep up the great work!

**Comment by gildas-lormeau** [comment]
You can save files into a subfolder of the Downloads folder by editing the filename template in the options of SingleFile.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because of the reason I mentioned. Feel free to reopen it if necessary though.
