### ISSUE TITLE
Do I need to be connected to the Internet during the entire installation process?

### ISSUE THREAD

**Issue by kotoriww** [gildas-lormeau/SingleFile#658]
I installed the project in a gatewayless server. An error occurred during the installation of the unzipped file.
His error message is:
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/file-url failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by gildas-lormeau** [comment]
Indeed, SingleFile depends on modules downloaded with NPM from the internet.

**Comment by kotoriww** [comment]
ok
