### ISSUE TITLE
Firefox & Chrome extension in Win10 stuck on Wikipedia pages

### ISSUE THREAD

**Issue by beefdrifter** [gildas-lormeau/SingleFile#661]
**Describe the bug**
As the title mentions, saving a Wikipedia page using both the Firefox and Chrome extension in Win10 results in the progress being stuck on step 1/3

**To Reproduce**
1. Go to https://en.wikipedia.org/wiki/Castaway
2. Save page
3. Stuck on Step 1/3

**Expected behavior**
The page saves successfully

**Environment**
 - OS: Win10 Pro
 - Browser: Firefox 88, Chrome 90
 - Version: 1.18.82

**Comment by gildas-lormeau** [comment]
I cannot reproduce the bug. On my end, the page is properly saved in Chrome or Firefox. Did you change any setting in SingleFile?

**Comment by beefdrifter** [comment]
I have, but the extension has been working fine the day before. I might try removing then reinstalling the extension first

**Comment by beefdrifter** [comment]
So um... without me changing anything at all, the extension saves fine again, whereas it was stuck yesterday for the entire day. I guess I'll close the issue then. Thanks again for always responding so quickly.

**Comment by gildas-lormeau** [comment]
You're welcome. The issue you had is weird though.
