### ISSUE TITLE
"Refused to execute inline script" when loading unpacked

### ISSUE THREAD

**Issue by WellRedPandit** [gildas-lormeau/SingleFile#662]
**Describe the bug**

Chrome complains 
> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem:".

**To Reproduce**

1. run `./build-extension.sh` with the rollup line in dev mode, i.e. `rollup -c rollup.config.dev.js`
2. unzip `singlefile-extension-chromium.zip` into a new dir
3. use _Load unpacked_ in Chrome to load the extension from the unzipped dir
4. observe the red _Errors_ button

**Note:** the same error happens when using the prod rollup config, i.e. `rollup -c rollup.config.js` but then the line number (see the screenshot below) is not output.

**Expected behavior**

No errors

**Screenshots**

![image](https://user-images.githubusercontent.com/3659381/115824086-6868eb00-a3d5-11eb-8654-7aa3cb008979.png)

**Environment**
 - OS: Mac Big Sur
 - Browser: Chrome
 - Version:  90.0.4430.72

**Comment by WellRedPandit** [comment]
forgot to mention because it's not important to me, but thought i should mention it just in case: Chrome complains that ` "sidebar_action"` is a not valid directive in `manifest.json`. i simply remove it from the manifest before loading the extension.

**Comment by gildas-lormeau** [comment]
This is normal. This is due to the fact that Singlefile tries to inject an inline script into the page to run it synchronously. However, sometimes the page is secured by a CSP directive that blocks inline scripts.

**Comment by WellRedPandit** [comment]
understood. thank you!
