### ISSUE TITLE
Checking "compress CSS content" makes SingleFile hang at step 1/3

### ISSUE THREAD

**Issue by lkintact** [gildas-lormeau/SingleFile#663]
**To Reproduce**
1. Create a new Firefox profile, add SingleFile to it (don't enable "Allow this extension to run in Private Windows" when adding SF).
2. Check "Stylesheets -> compress CSS content" in SF options. 
3. Navigate to https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States.
4. Click on the SF toolbar icon at the top-right to save the page. 

SingleFile hangs at Step 1/3.

**Environment**
 - OS: Windows 10 Home 1803
 - Browser: Firefox 87.0 (32-bit)
 - SingleFile version: 1.18.82

**Comment by lkintact** [comment]
Looks like it's that way on any wikipedia.org page. #661 seems to have to do with the same underlying issue.

**Comment by gildas-lormeau** [comment]
Thank you for having reported this issue. It's fixed in the version 1.18.83 I just uploaded. It should be published Monday.

**Comment by lkintact** [comment]
Thanks for fixing it so quickly! Just tired https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States with SF 1.18.83, the bug is gone.

**Comment by gildas-lormeau** [comment]
@lkintact Thank you for the feedback!
