### ISSUE TITLE
Appending the current date and time to singlefile-settings.json when exporting options

### ISSUE THREAD

**Issue by lkintact** [gildas-lormeau/SingleFile#664]
**Is your feature request related to a problem? Please describe.**
This isn't quite a problem, but having the name of the options file in the form `singlefile-settings_<Date>_<Time>.json` could useful: you wouldn't have to check the modification time to make sure you're going to import the most recent options file.

**Describe the solution you'd like**
Appending a date and time to the file name so it would be something like `singlefile-settings_2021-04-23_18.49.03.json`. Perhaps the `<Time>` part should depend on the OS locale, so as not to confuse people that are used to the 12h notation.

**Describe alternatives you've considered (optional)**
Manually renaming the file.

SingleFile version: 1.18.82.

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion, it's implemented in the version 1.18.83.

**Comment by lkintact** [comment]
Thank _you_ for implementing!
