### ISSUE TITLE
Recent issue with english Wikipedia

### ISSUE THREAD

**Issue by abolibibelot1980** [gildas-lormeau/SingleFile#665]
**Describe the bug**
When attempting to save a page from english Wikipedia, SingleFile stays blocked at step 1. I didn't have issues saving pages from english Wikipedia with SingleFile up until today.

**To Reproduce**
I tried these three pages :
https://en.wikipedia.org/wiki/Not_an_Addict
https://en.wikipedia.org/wiki/Talk:Not_an_Addict
https://en.wikipedia.org/wiki/K's_Choice
There's no such issue with the dutch version of the first page above, for instance.
https://nl.wikipedia.org/wiki/Not_an_Addict

**Environment**
 - Windows 7 Pro SP1
 - Firefox 88.0 64 bits

**Comment by gildas-lormeau** [comment]
Thank you for having reported this issue. It should fixed in the version 1.18.83 I just uploaded. It should be published Monday.
