### ISSUE TITLE
API integration error

### ISSUE THREAD

**Issue by BarrBozzO** [gildas-lormeau/SingleFile#666]
**Describe the bug**
Using this guide, I've integrated SinglePage API into my extension, but getting next error trying to capture a page.
`Uncaught (in promise) TypeError: Cannot read property 'getPageData' of undefined`

**To Reproduce**
1. Use integration guide
2. Call 
`const { content, title, filename } = await extension.getPageData({
  removeHiddenElements: true,
  removeUnusedStyles: true,
  removeUnusedFonts: true,
  removeImports: true,
  removeScripts: true,
  compressHTML: true,
  removeAudioSrc: true,
  removeVideoSrc: true,
  removeAlternativeFonts: true,
  removeAlternativeMedias: true,
  removeAlternativeImages: true,
  groupDuplicateImages: true
});`
3.' See error

**Expected behavior**
Expected to get a captured page string

**Screenshots**

**Environment**
 - Browser: Chrome

**Comment by gildas-lormeau** [comment]
Thank you, I actually forgot to include `"dist/single-file.js"` as a content script. I updated the wiki. It should be ok now.

**Comment by BarrBozzO** [comment]
@gildas-lormeau Thanks

**Comment by gildas-lormeau** [comment]
@BarrBozzO you're welcome!
