### ISSUE TITLE
Website (flickr) not completely loaded

### ISSUE THREAD

**Issue by kaheischmitt** [gildas-lormeau/SingleFile#667]
Hi there. First of all I wanna thank You for Your great work! I really appreciate it.

I am using CLI version and try to grab a flickr-page into one single file. 
There is always lots of the page missing, because it uses dynamically scrolling down (dunno the exact phrase for that technique).
The code i am using is e.g. 

single-file "https://www.flickr.com/photos/spannarama/page10" output-file.html --back-end=webdriver-gecko

Is there a way to simulate scrolling down the whole web-page and grabbing everything?

I am on Win10 Pro.

Thanks in advance.
Kalle

**Comment by gildas-lormeau** [comment]
This could be done by running a user script that would scroll down into the page before the capture is done. Here is more info about how to run it: https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because I give some info on how to achieve this. Feel free to reopen it if necessary.
