### ISSUE TITLE
Suggestions - not exactly an issue

### ISSUE THREAD

**Issue by Len44** [gildas-lormeau/SingleFile#67]
Hi - 
Thank you for this add-on. You say suggestions are welcome.
I have two minor suggestions.
1. Option to append date and time, or JUST date (I don't need time).
2. In save dialog, remember last saved-to folder.
Thanks.
LB

**Comment by gildas-lormeau** [comment]
Hi,

Thanks for the suggestion. Regarding the date, I think I will implement a templating system allowing the user to customize more the filename. Regarding the second suggestion, Web Extensions cannot do that as far as I know.

**Comment by Len44** [comment]
Got it. Thanks.

LB

**Comment by gildas-lormeau** [comment]
You're right, I'll implement this soon.

**Comment by gildas-lormeau** [comment]
I looked a bit closer to the last saved-to folder issue and I can't find how go implement this. Do you know an extension that can remember it?

**Comment by Len44** [comment]
No, no. I’m just talking about the Firefox built-in main menu item under File. “Save As…” seems to remember when I use it where I last saved.

Try it out.

That’s all.

Thanks.

LB

**Comment by gildas-lormeau** [comment]
Ok, I confirm this is unfortunately not technically possible though. However I fixed the first issue in 1.6.14. You can also define a sub-folder where to save files now with the new "template" option.

**Comment by Len44** [comment]
OK, thanks.

Already have that disabled. Will play around a bit and look for it.

Thanks.

LB
