### ISSUE TITLE
Save full Website via the extension

### ISSUE THREAD

**Issue by JustACuteGirlLookingForAManToFixHerBugs** [gildas-lormeau/SingleFile#670]
Hey! I would love to see a way to save a website with all the internal links (and URLs changed to local files) via the extension. The CLI is too difficult for me to set up, and is less convinient than extension. Your extension is really the best in terms of how accurate the result is - all other website downloaders are nowhere near, especially on websites using modern technologies. 'Save selected links' is good, but it doesn't change the URLs to the local files.

**Comment by gildas-lormeau** [comment]
I agree this would be a nice feature to have. However, crawling a website *is* complicated and I don't think the extension is the best way to achieve this. I think a better approach would be to build a UI on top the CLI tool. However, note that SingleFile (the extension) is able to save multiple URLs via the context menu, see SingleFile > View pending saves ... > Add URLs.

**Comment by JustACuteGirlLookingForAManToFixHerBugs** [comment]
Yeah, a workaround I'm using (for anyone who might stumble upon this issue) is to combine this with [Linkclump](https://chrome.google.com/webstore/detail/linkclump/lfpjkncokllnfokkgpkobnkbkmelfefj) extension to select all links on a page.

**Comment by gildas-lormeau** [comment]
You should also be able do this with SingleFile by pressing `Ctrl-A` and selecting in the context menu SingleFile > Save selected links.
