### ISSUE TITLE
CLI error "javascript error: Cannot set property 'getFileContent' of undefined"

### ISSUE THREAD

**Issue by DominikM** [gildas-lormeau/SingleFile#671]
From the manually installed command line interface, certain webpages cause the following error and stack trace. I've tested this with webdriver-chromium and webdriver-gecko backends, the issue occurs in both.

> $ single-file --back-end=webdriver-chromium 'https://docs.djangoproject.com/en/3.1/ref/models/fields/'
>
> javascript error: Cannot set property 'getFileContent' of undefined
>   (Session info: headless chrome=89.0.4389.90) URL: https://docs.djangoproject.com/en/3.1/ref/models/fields/
> Stack: JavascriptError: javascript error: Cannot set property 'getFileContent' of undefined
>   (Session info: headless chrome=89.0.4389.90)
>     at Object.throwDecodedError (/opt/single-file/node_modules/selenium-webdriver/lib/error.js:550:15)
>     at parseHttpResponse (/opt/single-file/node_modules/selenium-webdriver/lib/http.js:565:13)
>     at Executor.execute (/opt/single-file/node_modules/selenium-webdriver/lib/http.js:491:26)
>     at processTicksAndRejections (node:internal/process/task_queues:94:5)
>     at async thenableWebDriverProxy.execute (/opt/single-file/node_modules/selenium-webdriver/lib/webdriver.js:700:17)
>     at async getPageData (/opt/single-file/cli/back-ends/webdriver-chromium.js:117:2)
>     at async Object.exports.getPageData (/opt/single-file/cli/back-ends/webdriver-chromium.js:37:10)
>     at async capturePage (/opt/single-file/cli/single-file-cli-api.js:246:20)
>     at async runNextTask (/opt/single-file/cli/single-file-cli-api.js:167:20)
>     at async Promise.all (index 0)

This does not occur when using jsdom. Not all websites cause this issue, although I'm unsure what the triggering factor is. Some websites that this doesn't occur are twitter.com, google.com, youtube.com. I'm running Arch Linux. I suspect the issue has something to do with the selenium-webdriver, due to jsdom working, although I'm unsure what.

Let me know if any more information is needed, thanks.

**Comment by gildas-lormeau** [comment]
I updated the version of selenium in the package.json file and it looks like this fixed the issue. Can you confirm it?

**Comment by DominikM** [comment]
It seems that this has fixed the issue when using webdriver-gecko, but the same issue remains when using webdriver-chromium for me.

**Comment by gildas-lormeau** [comment]
It should be fixed now.

**Comment by DominikM** [comment]
Thanks!
