### ISSUE TITLE
Hello sir I always use singlefile program but today I think I find bug

### ISSUE THREAD

**Issue by hugepaper** [gildas-lormeau/SingleFile#672]
Yesterday this wonderful program was fine. But today when I save the something tab
tab page name is weird.

(https://user-images.githubusercontent.com/80020752/117139773-95f76080-ade7-11eb-9bfa-32ca8ee7a550.png)

Please sir fix that problem please.

**Comment by gildas-lormeau** [comment]
Unfortunately, this is a bug in Chrome. I cannot fix this issue, see here for more info: https://github.com/gildas-lormeau/SingleFile/issues/130
