### ISSUE TITLE
Automatically saving bookmarks feature is not working

### ISSUE THREAD

**Issue by sdht0** [gildas-lormeau/SingleFile#677]
**Describe the bug**
My default profile has "save the page of a newly created bookmark" enabled. However, this does not seem to triggering a page save on creating a new bookmark anymore, either by clicking the bookmark button or dragging the tab to the bookmark toolbar.

**To Reproduce**
1. Check "save the page of a newly created bookmark" in "Default settings".
2. Open a web page, say en.wikipedia.org and ensure default profile is "Default settings".
3. Bookmark the page by dragging to the bookmarks toolbar. 
4. SingleFile is not triggered.

**Expected behavior**
SingleFile should start saving the page.

**Environment**
 - OS: ArchLinux
 - Browser: Firefox Developer Edition
 - Version: 89.0b9

**Additional context**
It did work previously, so something must have changed either in Firefox, SingleFIle, or in my local configurations.

**Comment by sdht0** [comment]
Thanks!

**Comment by gildas-lormeau** [comment]
You're welcome. The fix will be available in the version 1.18.85 which will be published on the store once reviewed by Mozilla.
