### ISSUE TITLE
Is it possible to add full URL of the source page in the saved file's metadata?

### ISSUE THREAD

**Issue by minor6th** [gildas-lormeau/SingleFile#678]
I use SinglePage to clip web pages into DEVONthink on macOS, and I noticed that the saved file has a `com.apple.metadata:kMDItemWhereFroms` metadata item which can be used by DEVONthink.

However there is a problem that it only keeps the source page's domain, it would be great if we can have the full URL of the original web page.
 
I know I could include the info bar in the saved html file, but it cannot be easily processed by productive applications like DEVONthink.

**Comment by gildas-lormeau** [comment]
Extensions cannot change these metadata. Maybe disabling the setting `Misc. > save pages in background` might help though.
