### ISSUE TITLE
How does removing `src` attribut on embed videos work ?

### ISSUE THREAD

**Issue by haoadoresorange** [gildas-lormeau/SingleFile#679]
Hi,

I'm having trouble saving a page that has embedded youtube videos, JS is already included. I already look around the issues but didn't really find an answer so I post it here.
1/ What are the options `remove video/audio sources` for ?  And why is it checked by default ? (Why I want to remove the videos)
2/ Since the embed videos are not video elements it should not affect it ?
3/ Do you have any idea why an embed video wouldn't work on saved page ? I have the `remove script` unchecked, no console error when I click on the video or whatsoever.

Thanks very much !

**Comment by gildas-lormeau** [comment]
1/ It's documented, click on the "?" icon next to the option labels. They are checked by default because otherwise they produce large files.
2/ SingleFile cannot save Youtube videos even if JavaScript files are included
3/ because the page was not designed for this.

**Comment by haoadoresorange** [comment]
Hi thanks for the comment.
1/ I know what it does, I just didn't really know why to remove it by default, videos seem an important part (but large file is indeed a problem)
2/ 3/ It wasn't to save Youtube videos, more like to play the embedded one. I inspected the content the url is not in a blob, it is just there. What is the technical limit here ? Maybe I can help ?

**Comment by gildas-lormeau** [comment]
The technical limitation is that Youtube is not designed for this use case (i..e. archives containing online videos). Although, this might be circumvented by transforming the video element with an [embedded video](https://developers.google.com/youtube/iframe_api_reference) just before saving the page thanks to a [user script](https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved).
