### ISSUE TITLE
Default Save shortcut interferes with Bitwarden

### ISSUE THREAD

**Issue by github-account1111** [gildas-lormeau/SingleFile#680]
**Is your feature request related to a problem? Please describe.**
Bitwarden is a very popular extension. It uses Ctrl+Shift+y to view and edit passwords, and it's probably my second most used shortcut. I also think it's safe to assume there's a decent overlap between Bitwarden's and SingleFile's userbase. So it would make sense to not have default shortcuts overlap with each other.

**Describe the solution you'd like**
Change default shortcut to something else.

**Describe alternatives you've considered (optional)**
Not having a default shortcut (akin to uBo where you define it yourself if needed). Less ideal, because it requires additional setup.

**Additional context (optional)**
I wipe and reinstall things fairly frequently, so it's annoying to have yet another thing to remember to change every time.

**Comment by gildas-lormeau** [comment]
Should I list all the extensions that are supposed to overlap with SingleFile in order to find a shortcut that would be okay for everyone?

**Comment by github-account1111** [comment]
No of course not, but it may be worth is to consider the most popular ones / most likely ones to overlap, like Bitwarden, Lastpass, 1Password, uBlockOrigin, tree style tab. Heck most of these don't even have default shortcuts. Almost anything but `Ctrl+Shift+y` would do.

**Comment by gildas-lormeau** [comment]
I'm sorry but I won't list "most popular ones / most likely" extensions in order to find a combination of keys that would not clash with one of them and would work on any OS.

**Comment by github-account1111** [comment]
Ctrl Shift f isn't taken and has the tactile bump which makes it easy to find. Ctrl Shift 7 is right above the U key (used to save all tabs), kinda sounds like "Save" and is also not taken.

**Comment by gildas-lormeau** [comment]
I am sorry but I am still not convinced. If I follow you, I am doomed to change the suggested SingleFile shortcut as soon as an extension becomes more popular and uses the same one.
I don't know the reason why you delete and reinstall SingleFle regularly but I think that is the cause of your problem. The fact that you can't restore the settings in the browser is also the source of the problem.

**Comment by github-account1111** [comment]
I don't delete and reinstall SingleFile specifically, just wipe OS or change the machine / VM.

>If I follow you, I am doomed to change the suggested SingleFile shortcut as soon as an extension becomes more popular and uses the same one.

That is fair, I haven't thought about it that way.
