### ISSUE TITLE
Filename garbled

### ISSUE THREAD

**Issue by Kal66** [gildas-lormeau/SingleFile#682]
Not sure if this is the right way but I wanted to ask how I can restore filenames to include the title of the web page.
Lately, the filenames are garbled like 4b6843b2-343f-4b2d-9a84-d6e275b01463.html when previously they clearly indicated title
I have reset all options

thanks

**Comment by gildas-lormeau** [comment]
It's unfortunately a bug in Chrome, see the 2nd item for "Chromium-based browsers" here: https://github.com/gildas-lormeau/SingleFile#known-issues. You can also take a look at this issue for more info: https://github.com/gildas-lormeau/SingleFile/issues/130.
