### ISSUE TITLE
SingleFileZ vs SingleFile - are there still differences?

### ISSUE THREAD

**Issue by 5TDg9** [gildas-lormeau/SingleFile#689]
According to the [comparison table](https://github.com/gildas-lormeau/SingleFile#file-format-comparison) there are some differences between SingleFile and SingleFileZ.
Although i didn't have time to check everything... after a few tests i realized that at least there seems to be no difference in this point: **_"Files can be unzipped to extract resources and view pages"_**:

All pages that i downloaded with SingleFile can also be unzipped with 7zip and and i can also find all the resources with the same folder structure.

Next i checked the file size: 
this was also the same. According to the [comparison table](https://github.com/gildas-lormeau/SingleFile#file-format-comparison) **_"Files are compressed"_** only with SingleFileZ. 

Maybe the comparison table isn't up to date anymore? 
According to the [FAQ](https://github.com/gildas-lormeau/SingleFileZ/blob/master/faq.md) SingleFileZ exist as a seperate extension because of the self-extracting ZIP feature. Maybe this ZIP-feature is the only difference?

**Comment by gildas-lormeau** [comment]
You shouldn't be able to open pages saved with SingleFile in 7zip.  Can you post an example of page that you saved with SingleFile and you can open in 7zip?

**Comment by 5TDg9** [comment]
sorry, my mistake... i don't know how i did that at first but i cannot reproduce it. So everything works like expected.

**Comment by gildas-lormeau** [comment]
no problem ;)
