### ISSUE TITLE
SingleFile (Module) as an API 

### ISSUE THREAD

**Issue by GitHubington** [gildas-lormeau/SingleFile#694]
Hello @gildas-lormeau,

I need your help.

I've been struggling for the past three days, to integrate your new **module** format into my own extension.

When I call extension.injectScript, I get the following error:

- Background Console -  `about:devtools-toolbox?id=singlefile@api&type=extension`

```
Uncaught (in promise) DOMException: The operation was aborted. extension-core.js:1:1175
    t moz-extension://7dfad001-2ef7-43fc-aa53-7f5287ac45f9/lib/single-file/dist/extension-core.js:1
    AsyncFunctionThrow self-hosted:694
    (Async: async)
    map self-hosted:221
    i moz-extension://7dfad001-2ef7-43fc-aa53-7f5287ac45f9/lib/single-file/dist/extension-core.js:1
    s moz-extension://7dfad001-2ef7-43fc-aa53-7f5287ac45f9/lib/single-file/dist/extension-core.js:1
    s moz-extension://7dfad001-2ef7-43fc-aa53-7f5287ac45f9/lib/single-file/dist/extension-core.js:1
    injectScript moz-extension://7dfad001-2ef7-43fc-aa53-7f5287ac45f9/lib/single-file/dist/extension-core.js:1
    singlefile_inject moz-extension://7dfad001-2ef7-43fc-aa53-7f5287ac45f9/js-common/common.js:25
    Initialize moz-extension://7dfad001-2ef7-43fc-aa53-7f5287ac45f9/js/background.js:41
    GetTab moz-extension://7dfad001-2ef7-43fc-aa53-7f5287ac45f9/js/Common.js:18
    apply self-hosted:2707
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:616
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:825
```

I've uploaded a small sample, [SingleFileApiTemplate.zip](https://github.com/gildas-lormeau/SingleFile/files/6587605/SingleFileApiTemplate.zip).

The three main files are:

```
extension/js/background.js
extension/js/content.js
extension/js-common/common.js
```

Please ignore the boilerplate code. I am using Bridge.NET as a C# to JavaScript compiler.

I hope it's not too much trouble.

.

_PS:_

_I did a regex search and replace on single-file files, to make relative paths correct under my `lib\` subfolder._

_Search: ((?:dist|extension)/.[^\s]*).js_
_Replace: lib/single-file/$1.js_

**Comment by GitHubington** [comment]
Hello again @gildas-lormeau,

I am simply unable to get [How to integrate the API of SingleFile into an extension](https://github.com/gildas-lormeau/SingleFile/wiki/How-to-integrate-the-API-of-SingleFile-into-an-extension) to function.

Would you provide a working sample?

**Comment by gildas-lormeau** [comment]
@GitHubington Sorry for the late answer. I followed the procedure you linked and was not able to reproduce the issue. Here is a zip containing the extension.

[singlefile-mini.zip](https://github.com/gildas-lormeau/SingleFile/files/6644796/singlefile-mini.zip)

**Comment by GitHubington** [comment]
Thanks for the reply, @gildas-lormeau,

Running your example as is, I get the following in the Browser Console...
`00:48:29.556 TypeError: window.singlefile is undefined extension-core.js:1:2903`

It seems as if, Inject, is not working.

**Comment by gildas-lormeau** [comment]
It worked in Chrome but not Firefox. It's fixed.

**Comment by GitHubington** [comment]
Awesome!

That's working wonderfully now, including the with regex search and replace.

:fist:

**Comment by anilabhadatta** [comment]
@GitHubington @gildas-lormeau how to call the extension from console. Can you provide the zip?
