### ISSUE TITLE
SF creates extra copies of the page

### ISSUE THREAD

**Issue by lkintact** [gildas-lormeau/SingleFile#696]
**Describe the bug**
SingleFile creates extra copies of the page when saving selections.

**To Reproduce**
1. Create a new Firefox profile, add SingleFile to it (don't enable "Allow this extension to run in Private Windows" when adding SF).
2. Navigate to https://example.com
3. Press Ctrl+a to select all the text on the page. Right-click to open the context menu and click on "Single File -> Save selection". SF saves the selection, creating one file.
4. Repeat step 3. Now SF creates two identical files. This number is incremented by one with each step 3 repetition.

**Environment**
 - OS: Windows 10 Home 1803
 - Browser: Firefox 88.0.1 (32-bit)
 - SingleFile version: 1.18.85

**Comment by gildas-lormeau** [comment]
Thank you for having reported this issue, it was a subtle one! It's fixed in the version 1.18.86.
