### ISSUE TITLE
SingleFiles don't show images after a while

### ISSUE THREAD

**Issue by benw-git** [gildas-lormeau/SingleFile#697]
Saving a page with SingleFile works, and views with images if I check it right away. On some files, after some time (restart?) the text and formatting is still correct, but no images. 

I've attached a sample file that has (i)info link to original page showing images, but does not show images in Firefox or Chrome on my Mac. (Had to ZIP it because GitHub doesn't upload HTML) 

Please advise. GREAT tool! Thx --Ben

[Pro(Master) tip_ Seat swap _ dieffenBIKE (2021-06-03 7_46_14 PM).html.zip](https://github.com/gildas-lormeau/SingleFile/files/6620286/Pro.Master.tip_.Seat.swap._.dieffenBIKE.2021-06-03.7_46_14.PM.html.zip)

Mac OS 10.15.7
SingleFile 1.18.85
Firefox 89.0 (64-bit)

**Comment by gildas-lormeau** [comment]
Thank you for having reported this issue, it's a regression I introduced in the version 1.18.83. I reverted the changes I did. It's fixed in the version 1.18.86.

**Comment by benw-git** [comment]
Firefox add-on page shows v 1.18.85, how do I get 1.18.86? Thx

https://addons.mozilla.org/en-US/firefox/addon/single-file/

**Comment by gildas-lormeau** [comment]
It will be available for download once the code reviewed by Mozilla.
