### ISSUE TITLE
Saving Youtube Community Page

### ISSUE THREAD

**Issue by Spicadox** [gildas-lormeau/SingleFile#698]
I am trying to archive a youtube channel's community page and the chrome extension downloads the whole page nicely, but I wanted to also be able to download the web pages of each individual post on the community page. As such, I decided to use the CLI of singlefile and using ```--crawl-max-depth``` works perfectly, except now I'm not getting the full community webpage due to "lazy loading", which I solved in the chrome extension by just manually scrolling through and loading the whole page. I've tried setting ```--load-deferred-images``` to both ```true``` and ```false``` to no avail. Is there any way to solve "lazy loading" on a youtube community page while using the CLI of this program?

Any help is much appreciated!

**Comment by gildas-lormeau** [comment]
I will do some tests to check if `--load-deferred-images` works as expected. I would say the best way to solve your issue is to emulate a very large screen with the option `--browser-height`. I did some tests (with `20000` as value) on Youtube and it seems to works fine.

**Comment by Spicadox** [comment]
The ```--browser-height``` option worked when I had it set to ```30000```. Thanks for the help!
