### ISSUE TITLE
Why not file:/// URLs?

### ISSUE THREAD

**Issue by kenahoo** [gildas-lormeau/SingleFile#7]
I see in the Known Issues for SingleFile that `file:///` URLs cannot be processed for security reasons.  I'm curious about those reasons - how would it give me access to things I wouldn't already have access to?

I was hoping to use SingleFile to make periodic local archives of some web pages created with [Org Mode](http://orgmode.org/), but they don't exist on a server anywhere.

**Comment by KrasnayaPloshchad** [comment]
@kenahoo So what happened if you set allowing to access file directory at chrome://extensions page?

**Comment by baloe** [comment]
So, the convenient workaround is:

- execute this command from within the directory holding the html file of interest:

      python -m SimpleHTTPServer 8000

- Open your web browser and go to `http://localhost:8000/` + name of your html file 
- Use SingleFile

**Comment by amirrh6** [comment]
https://github.com/gildas-lormeau/SingleFile/issues/7#issuecomment-618980153

> 
> 
> So, the convenient workaround is:
> 
>     * execute this command from within the directory holding the html file of interest:
>       ```
>       python -m SimpleHTTPServer 8000
>       ```
> 
>     * Open your web browser and go to `http://localhost:8000/` + name of your html file
> 
>     * Use SingleFile

The suggested workaround is considerably useful.
SimpleHTTPServer has been deprecated since Python 3. Consider using this command instead:

`python3 -m http.server 8000`

**Comment by Antiwhore** [comment]
This workaround is not working. My local file in turn references other local files and shitty Firefox won't let them load for "security reasons", so the page is loaded without styles and media files.

**Comment by gildas-lormeau** [comment]
@Antiwhore You need to rewrite absolute URLs found in the page into relative URLs.

**Comment by Antiwhore** [comment]
It's hard to be more obvious than that. Still it doesn't work. Even when I rewrite the paths manually in a text editor (which is a pain in the ass by the way), the assets are lost.

**Comment by baloe** [comment]
I just tried it out. Worked like a charm.

Steps:

1. Website `foo.html` with images and all relevant files in a folder `/tmp/test` (e.g. this page after Ctrl+S)
2. ```
    cd /tmp/test
    python3 -m http.server 8000
   ```
3. In Firefox browse `http://localhost:8000/foo.html` and save page with SingleFile

Firefox version 109.0.1
SingleFile version 1.21.39

**Comment by gildas-lormeau** [comment]
@Antiwhore I apologize for trying to help you and for providing you with a tool that does not suit you.

**Comment by Antiwhore** [comment]
> I just tried it out. Worked like a charm.
> 
> Steps:
> 
>     1. Website `foo.html` with images and all relevant files in a folder `/tmp/test` (e.g. this page after Ctrl+S)
> 
>     2. ```
>         cd /tmp/test
>         python3 -m http.server 8000
>        ```
> 
>     3. In Firefox browse `http://localhost:8000/foo.html` and save page with SingleFile
> 
> 
> Firefox version 109.0.1 SingleFile version 1.21.39

Yes. After devouring all memory and half of swap space and hanging the system for 15 minutes it finally outputs something similar to the source with some assets lost and bigger in size than the source by a third.
Works like a charm? Works like shit, I would say.

**Comment by baloe** [comment]
> Yes. After devouring all memory and half of swap space and hanging the system for 15 minutes it finally outputs something similar to the source with some assets lost and bigger in size than the source by a third.
> Works like a charm? Works like shit, I would say.

Come on, if you really want help be constructive and actually provide information. Just being rude won't solve your issue.

**Comment by melyux** [comment]
I don't think you can host WebArchive files on Mac with the HTTP server (they just download). What I've done is use https://github.com/gonejack/webarchive-to-html to convert them to HTML, then locally host the HTML using `http-server`, and then use SingleFile to download that. This works.

**Comment by iG8R** [comment]
Hello.
Is there some way to do the same but with mht files in Edge?
PS. I have plenty mht files and only Edge can open them so I want to save them with SingleFile.

**Comment by piknockyou** [comment]
I am using Brave browser and can save local HTML files (file:///) with SingleFile by simply enabling "Allow access to file URLs" in the extension settings (brave://extensions). No local server needed.

**Comment by iG8R** [comment]
@piknockyou 
> I am using Brave browser and can save local HTML files (file:///) with SingleFile by simply enabling "Allow access to file URLs" in the extension settings (brave://extensions). No local server needed.

Unfortunately, in my case, every mht-file hangs at step 1/3.
Could you please try the following sample file (just remove the zip extension at the end).
[Public-Mikrotik-Bandwidth-Test-Server(s) - MikroTik RouterOS - 07.09.2017.mht.zip](https://github.com/user-attachments/files/18290743/Public-Mikrotik-Bandwidth-Test-Server.s.-.MikroTik.RouterOS.-.07.09.2017.mht.zip)

**Comment by piknockyou** [comment]
Same here. Sorry about that. There may be converters out there?

**Comment by iG8R** [comment]
> Same here. Sorry about that. There may be converters out there?

Unfortunately, none of the converters I've tried work properly:
https://github.com/msindwan/mhtml2html
https://github.com/gaomeng1900/mhtml2html
https://sourceforge.net/projects/mht2htm/
https://github.com/dpellier/mht-to-html

**Comment by gildas-lormeau** [comment]
@iG8R, @piknockyou The simplest way to circumvent this limitation is to use an HTTP server as mentioned earlier in the thread. You can find a list of commands to start an HTTP server here: https://gist.github.com/willurd/5720255. Did you try this approach?

**Comment by iG8R** [comment]
@gildas-lormeau 
Thank you, yes, it works, but it is rather inconvenient to use as you need to do many excessive manual moves for each mht-file:
1. unpack (manually)
2. run the server (manually)
3. remember the name of the html-file (manually)
When using SF, you just need to open the mht file by double-clicking the left mouse button and save it with SF using the mouse as well, only with a right-click.

Could you please check, why SF hangs at step 1/3 using @piknockyou method?

**Comment by gildas-lormeau** [comment]
@iG8R Thanks for the clarification. The steps you described could done automatically by using a shell script. What OS are you using? If you're using Windows, it will probably be more complicated (for me) but it should be doable.

**Comment by iG8R** [comment]
@gildas-lormeau Thank you for trying to help. Exactly, I use Windows [Version 10.0.19045.2673].

**Comment by gildas-lormeau** [comment]
@iG8R Out of curiosity, do you (agree to) use WSL..?

**Comment by iG8R** [comment]
@gildas-lormeau It doesn't matter which method is used, the main criteria - it should work on all systems and be as native as possible.

**Comment by gildas-lormeau** [comment]
Tahnks for the feedback, I will try to provide a solution based on [single-file-cli](https://github.com/gildas-lormeau/single-file-cli) in the coming days.

**Comment by iG8R** [comment]
@gildas-lormeau It is I should be grateful that you are helping so much and paying so much attention.

**Comment by iG8R** [comment]
@gildas-lormeau With TotalCommander through the 7-Zip plug-in.

**Comment by gildas-lormeau** [comment]
@iG8R I tested [github.com/msindwan/mhtml2html](https://github.com/msindwan/mhtml2html) and it worked fine for me. What issue did you notice with this program?

**Comment by iG8R** [comment]
@gildas-lormeau It does nothing in my case.

![image](https://github.com/user-attachments/assets/ae9a58c8-68bf-47cc-8aa4-3ec5aa222049)

**Comment by gildas-lormeau** [comment]
You have to run:
```
npm install mhtml2html
npx mhtml2html 1.mht 1.html
```

**Comment by iG8R** [comment]
I remember having the same situation last time I tried to use it.

![image](https://github.com/user-attachments/assets/5c690e2c-deaf-40bf-a4b2-b7494576aa9e)

**Comment by gildas-lormeau** [comment]
@iG8R Can you do the same test in an empty folder instead of `mhtml2html-master`?

**Comment by iG8R** [comment]
@gildas-lormeau 

![image](https://github.com/user-attachments/assets/99c7bcb0-4c63-4996-a1ef-d442015f1f48)

Hmm, it looks like the error occurs if the directory is not in the root of the disk.
But still, it doesn't work, causing the error.
PS. I used the mht-file from my previous post here https://github.com/gildas-lormeau/SingleFile/issues/7#issuecomment-2567728142

![image](https://github.com/user-attachments/assets/b2eab19a-5d54-4e1c-868d-c877a281067d)

**Comment by gildas-lormeau** [comment]
It looks like it's a bug in mhtml2html. If you wish, you can post your mhtml file here so that I can debug it and possibly publish a fork with the bug(s) corrected.

**Comment by iG8R** [comment]
@gildas-lormeau Thank you so much! I've already posted the mht-file previously here https://github.com/gildas-lormeau/SingleFile/issues/7#issuecomment-2567728142 -  https://github.com/user-attachments/files/18290743/Public-Mikrotik-Bandwidth-Test-Server.s.-.MikroTik.RouterOS.-.07.09.2017.mht.zip then just I renamed it to 1.mht for convenience.

**Comment by gildas-lormeau** [comment]
@iG8R FYI, I've just published the first version of the fork. I tested it successfully with your example page. See https://github.com/gildas-lormeau/mhtml-to-html for more info.

**Comment by iG8R** [comment]
@gildas-lormeau Thank you so, so much!!! It works like a charm!
Could you please consider the possibility of processing not only a single file but the entire directory as well?
E.g. `mhtml-to-html *.mht` or `mhtml-to-html f:\_Downloads\mhtml-to-html\mhtml-to-html-main\`
PS. There is something wrong with the Deno installation on Windows.
I was forced to install it manually.

![image](https://github.com/user-attachments/assets/a9236ee2-c119-44ce-900e-8196e49214d2)

**Comment by gildas-lormeau** [comment]
@iG8R Thank you for the feedback. I updated the code in order to support wildcards, e.g. "*.mht", for the first param. In that case, the second parameter is ignored (for now).

**Comment by iG8R** [comment]
@gildas-lormeau Thank you very much!
