### ISSUE TITLE
TypeError: window.singlefile is undefined

### ISSUE THREAD

**Issue by GitHubington** [gildas-lormeau/SingleFile#701]
Hello @gildas-lormeau

Sorry to trouble you again.

When I update to your latest version, that error returns.

```
TypeError: window.singlefile is undefined
    getPageData moz-extension://7dfad001-2ef7-43fc-aa53-7f5287ac45f9/lib/single-file/dist/extension-core.js:1
```

It's probably something to do with Firefox, as you had previously mentioned.

The change you made to get the sample to work, is that something I can do myself? If so, how?

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue, it should be fixed now.
