### ISSUE TITLE
An option for more privacy

### ISSUE THREAD

**Issue by etienne-ch** [gildas-lormeau/SingleFile#702]
Hi,

I'd like to see an option to disable the log of the html address and the date/time inside the source of the page.

Why ?
– because it's a concern for privacy as it is a record of one's browsing history.
– this metadata is not strictly needed to save a page.

Of course this means that the infobar option would be disabled too (greyed out)

Thanks

**Comment by gildas-lormeau** [comment]
I am hesitant to add such an option because there has been at least 2 cases where it helped researchers to identify the source of phishing attacks. More info here:
 - https://www.trendmicro.com/en_us/research/19/d/phishing-attack-uses-browser-extension-tool-singlefile-to-obfuscate-malicious-log-in-pages.html
 - https://news-block.com/north-korean-hackers-adapt-web-skimming-to-steal-bitcoin/

So, at the moment, I'm tempted to say that it's a blessing in disguise.

**Comment by etienne-ch** [comment]
Well, remember you're working for the public, not the government .... (to paraphrase one famous whistleblower's sentence)

Anyway your add-on saves images in a way that makes it difficult to hide where they come from. From what I've read following your links, security researchers didn't really need that metadata to make up their mind as they got an accumulation of evidence.

Keep in mind who's using your add-on by a large majority, neither black hats nor the police, but ordinary people who are having a hard time protecting their privacy nowadays ... Plus remember all I'm asking is to **have a choice** in the way pages are saved. Regarding a "bad use" of your add-on, if a hacker is stupid enough to leave such crucial metadata in a phishing page then maybe he gets what he deserves ....

**Comment by gildas-lormeau** [comment]
I need some time to think about this issue. Note that the URL will be saved (by default) anyway because of this [issue](https://github.com/gildas-lormeau/SingleFile/issues/360).

I encourage everyone reading this issue to participate in the discussion on this topic here.

**Comment by etienne-ch** [comment]
Ok, good to know you're considering it.

I have enough motivation to make a commit myself if needed, though I don't know that much about javascript TBH

And I'd like to hear other opinions too

**Comment by gildas-lormeau** [comment]
The next version will allow you to set the undocumented [hidden option](https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options) `insertSingleFileComment` in order to control the insertion of the comment added by SingleFile.
