### ISSUE TITLE
Able to autosave on tab discard, then close the discarded tab, then open the file saved by singlefile

### ISSUE THREAD

**Issue by rftw** [gildas-lormeau/SingleFile#703]
**Is your feature request related to a problem? Please describe.**
Currently it is possible to autosave on tab loading or unloading. I wish to autosave on tab discarding.

**Describe the solution you'd like**
* Autosave on tab discard
* Close the discarded tab
* Open the file saved by singlefile
* Move the tab of the opened file to the same position of the closed discarded tab

Thank you!

**Comment by gildas-lormeau** [comment]
Well, this is a very specific feature request...

**Comment by rftw** [comment]
I am using Firefox. I am a heavy tab user and currently have around 300 tabs. The Auto Tab Discard extension greatly helped to reduce the cpu and ram consumption. However, a limitation of firefox tab discarding method is that whenever the discarded tab inadvertently gets focus, it is automatically reloaded. There is currently no way to prevent it which is very inconvenient. Related issue on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1505960
Also when you want to visit the discarded tabs later, their reloading takes a lot of time and resources slowing down the browser.

Previously I used chrome with "The Great Suspender" extension. The extension provides an excellent feature in that before discarding a tab, it takes a snapshot of the whole page and displays it with scrollbar. The tab is reloaded only when the user clicks on the screenshot, thus preventing accidental reloads. I wish to imitate this behavior in firefox and so requested this feature.

**Comment by gildas-lormeau** [comment]
Thank you for the additional info. The use case is clearer for me :)

In the scenario you described, the main problem is that it's impossible to open the saved file in a tab from a technical point of view. Extensions can't open tabs with `file:///` URIs.

However, I could implement the "autosave on tab discard", I think it makes sense anyway.

**Comment by rftw** [comment]
Thank you!

**Comment by rftw** [comment]
A suggestion:

Since opening local files in not possible, instead of autosaving files on tab discard, we can instead redirect the tab to the blob url created by the singlefile. I downloaded your repo and tested this approach and it worked.

[After line 276 in download.js](https://github.com/gildas-lormeau/SingleFile/blob/880c73ea612945501b6a4b84982bfed1103a505b/extension/core/bg/downloads.js#L276) file, I added the line `await browser.tabs.update({url: downloadInfo.url});` The `downloadInfo.url` contains the blob url which firefox sucessfully opened. This is much better than downloading. Therefore when implementing "Autosave on tab discard", can you please give us an option whether to download the file or just redirect to the blob url. 

Thank you!

**Comment by gildas-lormeau** [comment]
@rftw The current version on github should fix your issue.

**Comment by rftw** [comment]
> 
> 
> @rftw The current version on github should fix your issue. SingleFile will still save pages though.

Sorry for the late response. It is working as expected except that the original tab does not get closed. Screenshot of my settings:

<img width="494" alt="ss" src="https://user-images.githubusercontent.com/55868021/126381050-5d527a94-b65b-4aa4-9c7f-fc713c797a6b.png">

**Comment by gildas-lormeau** [comment]
I confirm the "remove on discard" feature does not work as expected.

**Comment by gildas-lormeau** [comment]
Everything should work fine in the version 1.18.91.

**Comment by rftw** [comment]
> 
> 
> Everything should work fine in the version 1.18.91.

Working perfect! 

A minor request: In [line 195 of autosave.js](https://github.com/gildas-lormeau/SingleFile/blob/66d619f4f9a436353e4c91ac6fadfe0ccb511cba/extension/core/bg/autosave.js#L195), can you add **windowId** property to `createTabProperties` like:
```
const createTabProperties = { active: true, url: URL.createObjectURL(blob), windowId: tab.windowId};
```
This is because the `tab.index` is for within a window. It is not unique across all windows. If windowId is not specified and if the user is using multiple windows, all tabs are created in the first window.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback and the suggestion. The fix will be available in the next version.
