### ISSUE TITLE
2 bugs in SingleFile ESR 52 v1.0.1

### ISSUE THREAD

**Issue by XX-J** [gildas-lormeau/SingleFile#714]
**1**. Not overlayed a shadow on the page when SingleFile is working. In v1.17.58 is no that bug.
____________________

 **2**. Scripts in tag `src` and base64 encode don't saved with SingleFile.

1. In Settings SingleFile uncheck: compress HTML content, remove all hidden elements and remove all scripts.
2. Save with SingleFile https://lenta.com/product/velosiped-actiwell-pro-grandtour275alyumrama24-skorkasseta-gtr275au-kitajj-529783/
3. Open saved page and save with SingleFile again.
4. Second saved page is malfunctioned (buttons for switched tabs under main picture doesn't work) and smaller megabytes, than first saved page.

 It's because scripts, like `<script defer src="data:application/javascript;base64,KHdpbmR..."></script>`, in first saved page is not saved (empty), like `<script defer></script>`, in second saved page.

 For what i resave local page?
 I edit local pages with browser DevTools (because of the visual convenience): remove garbage, ad, unused locally elements, and then resave mostly cleaned page.

**Environment**
 Win7 SP1 x64 rus; FireFox v53.0.3 x32 rus; Serpent v52.2021.06.05 x32.

**Comment by gildas-lormeau** [comment]
The first issue is a known limitation due to the fact that this version of Firefox does not support the Shadow DOM API (cf. https://caniuse.com/shadowdomv1).  I'll take a look at the second issue.

**Comment by XX-J** [comment]
> The first issue is a known limitation due to the fact that this version of Firefox...

 But in v1.17.58 overlayed shadow is show. SingleFile **ESR 52** must not use Shadow DOM API.

**Comment by gildas-lormeau** [comment]
The version 1.17.58 works because it does not rely on the Shadow DOM API. Both bugs are fixed in the version 1.0.2. Let's hope the two dozens of users will appreciate it...
