### ISSUE TITLE
Drops filename text after encountering second colon ':' in filename

### ISSUE THREAD

**Issue by JBigglesworth** [gildas-lormeau/SingleFile#722]
On saving a web page based on the page's title, if there's a second colon ':' in the string, although the colons display as underlines in the 'Save As' dialog box, the page will be saved with the correct text up to where the second colon occurs with subsequent text being dropped.

I would expect all title text that appears in the 'Save As' box (with the substituted underlines) to be included in the filename.

**Environment**
 - OS: Win10 Pro x64
 - Browser: Firefox 90.0.1 x64 US

**Comment by JBigglesworth** [comment]
An update to this is that it appears the problem wasn't the colon ':' character but the total path length.

By creating a sub directory structure having a sufficiently long path I was able to demonstrate that SingleFile was truncating the file's name at approx. 246 characters from the start of the total path.

By comparison, if I saved the same web page via FireFox's inbuilt 'Save Page As' (via right click context menu) the full file name was saved into the same sub directory.

It would appear SingleFile has some path length limit that's not imposed by FireFox of Windows dialogs.

**Comment by gildas-lormeau** [comment]
Indeed, the (relative) filename length is limited to 192 bytes. You can increase the value in the options page, see the option `File name > max length (bytes)`.

**Comment by JBigglesworth** [comment]
Thanks, it never occurred to me to check if there's an arbitrary setting to limit length. Always learning!

**Comment by gildas-lormeau** [comment]
No problem!
