### ISSUE TITLE
Publish a library support use in playwright ?

### ISSUE THREAD

**Issue by valbendan** [gildas-lormeau/SingleFile#723]
**Is your feature request related to a problem? Please describe.**
I think SingleFile(Z) is perfect use to archive web pages, but I prefer the programmable way

**Describe the solution you'd like**
It would be awesome we have a api: `SingleFile(page: Page, save_file_path: string, options: object)`

**Describe alternatives you've considered (optional)**
Use `cli` version

**Additional context (optional)**

**Comment by gildas-lormeau** [comment]
You can already do that. 

Install SingleFile from npm:
```
`npm install "gildas-lormeau/SingleFile#master"`
```
Then, you can import the JS API and use SingleFile in a Node.js script.
```js
const { initialize, capture, finish } = require("single-file");
const singlefile = await api.initialize(options);
await singlefile.capture(urls);
await singlefile.finish();
```

**Comment by valbendan** [comment]
I think I need do some interect with the page before capture.

eg:  I have to login/click some menu before capture(otherwise the content is not what I want).

**Comment by gildas-lormeau** [comment]
See here: https://github.com/gildas-lormeau/SingleFile/wiki/How-to-integrate-SingleFile-library-code-in-%22custom%22-environments%3F
