### ISSUE TITLE
Sanitize External Resources and Add Content Security Policy to block any external resources from being loaded

### ISSUE THREAD

**Issue by thebalaa** [gildas-lormeau/SingleFile#724]
Recently captured this page https://fossa.com/blog/analyzing-legal-implications-github-copilot/) with SingleFile. Viewing the resulting file I see in the Web Inspector that a Facebook tracking pixel (image) is being requested.

Is this the intended behavior? If not, it would be nice if SingleFile could "sanitize" any external resources that will cause the browser to initiate network requests AND as a fail-safe include CSPs (content security policies) to ensure no external resources will be loaded.

Adding the following meta tag into the head of the document produced by SingleFile seems to provide the desired behavior.

```html
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; font-src 'self' data:; img-src 'self' data:; style-src 'unsafe-inline';">
```

Thank you for this wonderful tool!

**Comment by gildas-lormeau** [comment]
Are you sure that your saved page triggered a request to facebook? I cannot reproduce the issue.

**Comment by gildas-lormeau** [comment]
I implemented your suggestion and added the option `HTML content > set content security policy` (enabled by default).

**Comment by gildas-lormeau** [comment]
@thebalaa I'm closing the issue but I'm still curious to know if you can reproduce the issue regarding the facebook tracker (with the new option disabled) or if you could provide me the saved page.

**Comment by thebalaa** [comment]
I am also unable to reproduce, the file was given to me by a colleague. I suspect it is an extension he may be running in his browser.

**Comment by gildas-lormeau** [comment]
Thanks for the answer. I like this new option anyway :)
