### ISSUE TITLE
Add saved pages to custom bookmarks folder

### ISSUE THREAD

**Issue by pgul** [gildas-lormeau/SingleFile#725]
It's very convenient to save pages but not very comfortable to open them from the local folder. The browser shows only list of filenames, and I can't remove these items from the browser.

It would be great if saved files will be automatically added to a custom bookmarks folder.
Or, almost the same, auto-save pages on adding to bookmarks but only to the one folder (with subfolders).
Then it will be list of saved pages with titles and favicons, and with "remove" possibility (not from local file directory, but from the list, it's enough).
May be bookmarks "ignore folders" setting can understand `*,!Saved Pages` syntax?

**Comment by gildas-lormeau** [comment]
Thank you for the issue report. I decided to add an option "allowed folders", it will be available when I'll build and publish the new version.
