### ISSUE TITLE
infobar not added anymore

### ISSUE THREAD

**Issue by AleCaste** [gildas-lormeau/SingleFile#726]
Hello, I have the setting "display an infobar when viewing a saved page" turned on, and this used to work fine.
But not anymore. Going through the generated html files I cannot find the "infobar" element anymore, no matter which webpage I save.
I am using SingleFile chrome extension version 1.18.88

**Comment by gildas-lormeau** [comment]
Is the option "Allow access to file URLs" enabled in the extension page? See chrome://extensions/?id=mpiodijhokgodhhofbcjdecpffjipkle

**Comment by AleCaste** [comment]
That was it. Now it works.

**Comment by gildas-lormeau** [comment]
Glad to hear it!
