### ISSUE TITLE
docker images per version

### ISSUE THREAD

**Issue by andreineculau** [gildas-lormeau/SingleFile#731]
**Is your feature request related to a problem? Please describe.**
I am hitting puppeteer issues when installing locally via npm, and thus I'm falling back to docker.
But I see you're only publishing "latest" https://hub.docker.com/r/capsulecode/singlefile/tags?page=1&ordering=last_updated , and while there are benefits with running bleeding edge versions, it also undermines the stability=determinism of a pipeline.

**Describe the solution you'd like**
I'd like you to consider publishing versioned tags on Docker Hub for current and future releases.

**Describe alternatives you've considered (optional)**

**Additional context (optional)**

**Comment by andreineculau** [comment]
FWIW The issue is I cannot get puppeteer to close the browser (chrome on macos). So `single-file` hangs. I have tried debugging puppeteer, I have even tried to close all pages myself as per https://github.com/puppeteer/puppeteer/issues/1245#issuecomment-620679740 , but the browser still stays open. I tried even upgrading puppeteer-core to latest, looking for better compat with newer Chrome versions. No go. I know from experience how iffy browser automation is, so for this scenario, running docker is just great! If there are versioned images :)

**Comment by gildas-lormeau** [comment]
I just created a tag for the current version. I wasn't doing this because I don't know Docker (and Docker Hub) very well, and also because Docker Hub builds the latest image automatically today. I'm wondering if it can be configured to build tagged images as well.

**Comment by andreineculau** [comment]
Thanks! As per https://docs.docker.com/docker-hub/builds/#set-up-build-rules you can have a rule for tags with a wildcard regex

**Comment by gildas-lormeau** [comment]
Thank you for the info @andreineculau. Unfortunately, this option is now disabled for non-pro users. I'll have to publish new versions manually.

**Comment by andreineculau** [comment]
Asch. Sorry to hear that.
