### ISSUE TITLE
In Chrome, scroll bar isn't displayed in extension options

### ISSUE THREAD

**Issue by rakleed** [gildas-lormeau/SingleFile#732]
**Describe the bug**
In Chrome, the scroll bar is not displayed in the extension options.

**To Reproduce**
1. Install the [SingleFile extension for Chrome](https://chrome.google.com/webstore/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle/)
2. Open extension options (`chrome-extension://mpiodijhokgodhhofbcjdecpffjipkle/extension/ui/pages/options.html` or `chrome://extensions/?options=mpiodijhokgodhhofbcjdecpffjipkle`)
3. Make sure the screen size is small enough for the scroll bar to appear

**Expected behavior**
The scroll bar is visible.

**Screenshots**
<details><summary>Screenshots</summary>

![screenshot-chrome-extensions-1627721337628](https://user-images.githubusercontent.com/19418601/127734622-96888081-a43b-4d4b-a6e3-c17ac4cc19cd.png)

![screenshot-chrome-extension-mpiodijhokgodhhofbcjdecpffjipkle-extension-ui-p-1627721524243](https://user-images.githubusercontent.com/19418601/127734645-9389cd84-9537-4242-a366-f850bb41d3a3.png)

</details>

**Environment**
 - OS: Windows 10 v. 21H1
 - Browser: Chrome 92
 - Version: 1.18.90

**Additional context**
The issue is reproducible in both light and dark browser themes.

**Comment by gildas-lormeau** [comment]
Thank you for the report. It will be fixed in the next version.
