### ISSUE TITLE
ISO date in filename template is yesterdays date

### ISSUE THREAD

**Issue by account-sxf** [gildas-lormeau/SingleFile#736]
**Describe the bug**
I'm using this template for filename: {year-locale}/{date-iso}/{page-title}.html

However, the folder name generated by date-iso is (@ 10 am my time) for the previous day, not today. E.g. today is 2021-08-04 but the folder used/generated is 2021-08-03

**Environment**
 - OS: Win 10 Version 1909 (OS Build 18363.1679) - corporate machine
 - Browser: Firefox 90.0.2 (64-bit)

**Additional context**
Tried restarting Firefox as I wondered if the date is determined at init. No luck.
Love the plugin and plan to use it all the time, superb.

**Comment by gildas-lormeau** [comment]
The ISO date is the one returned by this function: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString. The timezone is always zero UTC offset.

Why don't you use `{date-locale}` instead?

**Comment by account-sxf** [comment]
I just prefer YY-MM-DD as ordering the created folder/files by filename will yield a correct order by date, but mostly it's an aesthetic thing. Happy for you to close if you don't have plans to add any more template options. I might see how it works, perhaps it's pretty trivial to add some more and you can use merge if you like them.

**Comment by gildas-lormeau** [comment]
What about `{year-utc}-{month-utc}-{day-utc}` or `{year-locale}-{month-locale}-{day-locale}`?

**Comment by account-sxf** [comment]
Oh I didn't realize I could do that. Very flexible! Just tested it out and that's perfect. Closing my dumb query now :)

**Comment by gildas-lormeau** [comment]
Glad to hear it fulfill your needs :)
