### ISSUE TITLE
Hide tab context menu option

### ISSUE THREAD

**Issue by circcc** [gildas-lormeau/SingleFile#739]
I always use toolbar button and never webpage context menu or tab context menu. 
There is an option to hide the webpage context menu, but no menu to hide the tab context menu. 

Please make an option to hide the tab context menu.

**Comment by gildas-lormeau** [comment]
There is an hidden option for this. See https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options, you have to set `tabMenuEnabled` to `false`. The option is hidden because this feature is specific to Firefox.
