### ISSUE TITLE
Translate the option "group duplicate images together"

### ISSUE THREAD

**Issue by gildas-lormeau** [gildas-lormeau/SingleFile#74]
Hi @rstp14 @Shitennouji 

I added a new option "group duplicate images together". It allows reducing the size of the saved page when images are used multiple times in the HTML and in the CSS. When you have a little time, could you please translate the new label `optionGroupDuplicateImages`?

**Comment by Shitennouji** [comment]
optionGroupDuplicateImages
オプション重複画像のグループ化

**Comment by Shitennouji** [comment]
Hi Gildas,

The translation of the [Addon] page is completed.
I will send it by e-mail.
It becomes the file name "translation : addon page" .odt ".

**Comment by gildas-lormeau** [comment]
@Shitennouji Thank you very much!
