### ISSUE TITLE
Option: Confirm before saving

### ISSUE THREAD

**Issue by liangjiancang** [gildas-lormeau/SingleFile#742]
Considering that once turned on, it can take a lot of time, an extra layer of confirmation is necessary, especially since it cannot be stopped midway.

**Comment by gildas-lormeau** [comment]
It can be stopped midway by clicking again on the button of SingleFile.

**Comment by liangjiancang** [comment]
Got it. Then my new suggestion: a more intuitive design is to add a stop button to the `singlefile-logs` in the bottom left corner, or just add a hint "It can be stopped by ...".
