### ISSUE TITLE
Auto-Save this tab toggling off randomly

### ISSUE THREAD

**Issue by MaxSimpson** [gildas-lormeau/SingleFile#746]
I have been using the autosave to automatically save the HTML of pages after every time a specific tab refreshes 

Turn on auto-save, let it run, after 1 hour it turns off.

Keep running infinitely

![image](https://user-images.githubusercontent.com/41491414/128787672-937f9413-8dcb-4876-a87e-89cd212c4ce7.png)
![image](https://user-images.githubusercontent.com/41491414/128787685-53ff9cb4-50fa-4277-a04a-11e9703adbc6.png)
I retoggled it on but you can see my point

Windows 10, 64, Google Chrome

Is there a setting I can change to fix this or is this a bug?

**Comment by gildas-lormeau** [comment]
That's a weird issue. It might be related to discarded tabs, do you use an extension to discard tabs?

**Comment by MaxSimpson** [comment]
I don't think it is that because I was actively using chrome and the auto refresher I was using in tandem has continued to function.

**Comment by gildas-lormeau** [comment]
Thank you for the additional info. I was able to reproduce the issue by discarding the tab though (with the extension "Auto Tab Discard") and I'm pretty sure this is the cause of your issue.

**Comment by MaxSimpson** [comment]
![image](https://user-images.githubusercontent.com/41491414/128789773-74800815-247e-4232-a928-382cc45748be.png)
These are the only extensions I have.

**Comment by gildas-lormeau** [comment]
If you can, please extract and install the extension attached, it fixes the bug related to discarded tabs. You can find the instructions to install manually the extension here: https://developer.chrome.com/extensions/getstarted#manifest (omit the manifest creation). I would be curious to know if it fixes the issue.

[singlefile-extension-chromium.zip](https://github.com/gildas-lormeau/SingleFile/files/6958114/singlefile-extension-chromium.zip)

**Comment by MaxSimpson** [comment]
Alright so I ran into some issues trying to get chromium working on Windows so I found another thing that I think might work. I went into chrome://discards/ and toggled off automatic discards for my web page to see if that can fix it. Other than that, how do I run the chromium zip because I can't find anything to run in the extracted files.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback. I published the version I attached. It should be available for download from the store in the coming hours hopefully.

**Comment by gildas-lormeau** [comment]
I can't reproduce your issue. Did you change any setting in SingleFile before yesterday?

**Comment by MaxSimpson** [comment]
I may have changed them but I turned them all back to what they were previously. It works if I manually save but not when auto save. At the moment when it should save it just blinks like it is saving but nothing gets downloaded. All of my auto save settings are fine and I know that the filename and save location is not the issue.

**Comment by gildas-lormeau** [comment]
I followed these instructions:
1. reset the options in SingleFile
2. open a tab and go to https://example.com
3. enable "Auto-save this tab" via the context menu
4. refresh the tab, the page is automatically saved as expected
5. wait 1 hour
6. refresh the tab, the page is automatically saved as expected

So, I confirm I'm totally unable to reproduce your issue. Please let me know if I missed something when trying to reproduce it.

**Comment by MaxSimpson** [comment]
Alright after testing using another chrome profile and it seemed not to cause this bug. My only conclusion is that it is caused by,
a custom file location,
any of the following 9 extensions,
![image](https://user-images.githubusercontent.com/41491414/129281611-61e72fa7-bf4b-461a-ad71-c7f81dec4412.png)

Thanks for helping and sorry for wasting your time.
Also, thanks so much for this extension as it will help me so much!
-Max

**Comment by gildas-lormeau** [comment]
It wasn't a waste of time. There was really an issue related to discarded tabs in Chrome and your report helped me to identify it.

Thank you very much as well for the detailed info in your posts, it is always appreciated. I'm also glad to hear you're satisfied with SingleFile. I'll try to test SingleFile with Page Refresher installed. I highly suspect it as the one which interferes with SingleFile. Otherwise, I guess the trick is to search which one could do something particular after ~50 minutes.
