### ISSUE TITLE
"#" character present in page title prevents saved page to open from Bookmarks?

### ISSUE THREAD

**Issue by user0022** [gildas-lormeau/SingleFile#748]
I saw it first in SFZ, but I tested in SF and it is the same.
I also saved the same page the default way (means not via bookmark + auto-save that I first did), and it was the same too.
First seen and tested on a Github issue page, but also with [a StackOverflow page](https://stackoverflow.com/questions/52802403/how-can-i-use-23-instead-of-in-chrome) having a # in its title (found thanks to _intitle:"%23"_ search in Google). And the problem was still the same.

*

I bookmarked + auto-saved a page with 2 Bookmarks options checked:
_save the page of a newly created bookmark_	[x]
_link the new bookmark to the saved page_	[x]

But when trying to open it from Bookmarks, page doesn't display ("Fichier introuvable", in french).
Yet when opening it from the file manager it opens.
It seems to come from a difference I've seen in URIs.

When open from Bookmarks and not opening, The URI in address bar shows at its end (in "UTF8" writing, if it's he right name, as it displays when I copy the address in my text editor):
(...)Issue%20<ins>**#**</ins>100%20%C2%B7%20gildas-lormeau_SingleFile%20(10_10_2021%2010_10_10).html
But when open from file manager and opening:
(...)Issue%20<ins>**%23**</ins>100%20%C2%B7%20gildas-lormeau_SingleFile%20(10_10_2021%2010_10_10).html
Underlined bold characters being at the place of the # character of the page title (which is taken as first part of URI).

Yet it seems to be the contrary in the address bar, where I can read the URI without transformation in "UTF8", the non-opening page having the right writing apparently.
Open from Bookmarks, page doesn't open but in the address bar the writing is normal:
(...)· Issue #100 · gildas-lormeau_SingleFile(...)
Open from file manager, page opens but in address bar writing is odd (seems UTF8 is kept when it souldn't be kept):
(...)· Issue %23100 · gildas-lormeau_SingleFile(...)
(But probably in fact this detail is logical and it suprises me only because I don't understand the origin of the problem.)

*
The solution will be perhaps.

In the help page, you say at
6. Known issues:
"The following characters are replaced with _ in filenames: ~, +, \, ?, %, *, :, |, ", <, >"

And in **file name > Template** option:
"Invalid characters are automatically transformed and collapsed to underscores. (...) The invalid characters are: [ ~ + \ ? % * : | " < > and control characters from 0 to 31 in the ASCII table. 
(I remark that the [ character is in the line here probably by copy/paste error.)

Maybe the thing to do is to add # as invalid character?

*
I use Firefox 91, under Lubuntu 18.04 32 bits.

**Comment by gildas-lormeau** [comment]
I've skimmed the description of your report. I'll take a closer look at what's going on. In the meantime, you can add `#` to the list yourself of invalid characters by updating the `filenameReplacedCharacters` array in the [hidden settings](https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options).

**Comment by user0022** [comment]
OK thank you!
Adding manually # to the list worked fine, now pages open from Bookmarks.
I just lost 10 minutes searching in .json files of /home/<me>/.mozilla/firefox/xxxxxxxx.default-xxxxxxxxxxxxx/, before seeing export/import were in SF Prefrences, at the bottom.

**Comment by gildas-lormeau** [comment]
I'm sorry you did not know the settings should be imported/exported via the options page. I'll make the instructions clearer in the wiki page.

I fixed the issue without needing to add "#" in the list of replaced characters. The fix will be available in the version 1.18.95.
