### ISSUE TITLE
Add word-wrapping for the sticky notes annotations in SingleFile

### ISSUE THREAD

**Issue by Welding-Torch** [gildas-lormeau/SingleFile#751]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to save a page and add some personal remarks to it in the form of a sticky note, but that sticky note gets a scrollbar and I have to move it horizontally to read what I've written. It's just so cumbersome and seems like a basic issue that should be fixed.

**Describe the solution you'd like**
I'd like to see word-wrapping(which means the text will automatically go to the next line instead of developing a scroll bar) in the sticky notes in SingleFile.

**Additional context**
![image](https://user-images.githubusercontent.com/46340124/129485958-91f7af02-b80a-4f2d-839b-b69b301a59d3.png)
![image](https://user-images.githubusercontent.com/46340124/129486072-b67f8d5f-be94-46c3-b4e3-dd0c7419e436.png)

This image showcases the problem well. When I'm typing, I expect the words to remain within the boundaries of the sticky note rather than go offscreen into it.

Thank you for reading ❤

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. I agree word-wrapping is probably better. The fix will be available in the version 1.18.95.

**Comment by Welding-Torch** [comment]
You're so fast! This is I think the fastest I've ever gone from submitting an issue to seeing it fixed. Thank you! 
![image](https://user-images.githubusercontent.com/46340124/129628837-b15d998b-0b30-4ff7-a61e-4c8132c6f854.png)

**Comment by gildas-lormeau** [comment]
You're welcome!
