### ISSUE TITLE
Completely fails to encode images having a local path. Web URL images work fine.

### ISSUE THREAD

**Issue by snovotill** [gildas-lormeau/SingleFile#753]
**Describe the bug**
Completely fails to encode images having a local file path (as opposed to web URL).
This makes the extension completely unusable except on the web.

**To Reproduce**
1. Open a web page from C drive which contains images, also on C drive.
2. Save it with SingleFile.
3. The images fail to be encoded into the SingleFile documet.
4. Images having a web url do not have this problem.

**Expected behavior**
It should work. Silently discarding images having a local filesystem path is a major bug which results in loss of data if the person is not aware.

**Screenshots**
None needed. Easy to reproduce.

**Environment**
 - OS: Win10 Pro
 - Browser: Firefox
 - Version: any

**Additional context**
UnMHT with WaterFox Classic does not have this problem.
The workaround is horrific: you have to set up a web server on your local machine.

**Comment by gildas-lormeau** [comment]
This is a bug in Firefox, see https://bugzilla.mozilla.org/show_bug.cgi?id=1566051. There is nothing I can do on my end to circumvent it.

**Comment by gildas-lormeau** [comment]
@snovotill You know what I find worse? it's that SingleFile users punish me because of a bug in Firefox! It's still quite shameful...

**Comment by snovotill** [comment]
While this may be an upstream bug, the extension cannot be rate better than 3/5 because it in fact does not work well. Firefox is losing market share because of things like this, however there is also WaterFox which has been focused on giving the users a good experience. It is my hope that Firefox will die AND that a fork which respects users shall replace it. Bad leadership destroys products just like dictatorial government destroys nations.

**Comment by gildas-lormeau** [comment]
Thanks for your note, it's really nice to be sanctioned in this way without knowing exactly why ("it in fact does not work well"). It will teach me to make my work available for free. Don't be surprised if initiatives like these disappear in the future, you will have contributed to it.

**Comment by snovotill** [comment]
Absolutely wrong in this has gone on for so long because you Glidas have 
permitted it to do so. If you want your software to be useful then it 
needs to work properly. The way to accomplish this is as follows:

Every time your program fails to read a file then it MUST throw up a 
dialog explaining that this is caused by an upstream bug number XXXX in 
FireFox which has not been fixed since <insert date>.

By shaming them into fixing it like this you won't make friends but the 
truth is that you don't want those kind of people as friends. There was 
a time when software designers strived to make software which did what 
the users want, but these days there are a lot of a holes out there who 
want to protect users from their own stupidity from a security 
perspective. Those a holes need to be eradicated and there is no better 
way than for you to call them out by doing what I suggested. You are in 
a unique position to make this happen but you need to act intelligently.

**Comment by gildas-lormeau** [comment]
I recommend you to you "Save Page WE" instead of SingleFile. It should meet your requirements.

**Comment by snovotill** [comment]
I'm still using UNMHT with WaterFox Classic. As long as you are willing to take the blame for your software not being useful, then Mozilla might not fix that bug.

I've suggested a solution which will very likely solve your issue so my part here is done. If I think of anything else then I'll certainly let you know.

**Comment by gildas-lormeau** [comment]
It's because of a security issue that Mozilla decided to block extensions like SingleFile to get contents from the filesystem. This bug will never be fixed.

**Comment by snovotill** [comment]
I was suspicious that may be the case and it is absolutely tragic that 
Mozilla leadership is to inept and vicious toward their users, and 
coders who write plugins. I would highly encourage your otherwise 
excellent plug-in to pop up a notification every time Mozilla denies 
access to a file because the public needs to know that Mozilla has 
failed them. I would go so far as to reference FireFoxes' dwindling 
popularity in that dialog.

We ALREADY have a popular browser which treats it's users contemptuously 
as senile citizens who cannot look after their own security settings, so 
we certainly don't need FireFox to do the same. Firefox should be a 
choice for power users. It should allow complete bypass of SSL 
certificate checks (but with notification to user) via about:config and 
all sorts of other power-user things. This is why WaterFox came into 
existence and while I have not tried SingleFile in WaterFox yet, if it 
dosen't work then maybe Alix will fix that for you.

Outside of this, if I rate SingleFile only 3/5 then it's because it in 
fact performs to that level due to no fault of your own. I have to call 
it what it is but it is certainly not your fault. You are however in a 
unique position to make this known to the masses via a pop up whenever 
it fails.

**Comment by evroza** [comment]
I know this is probably not the place for it but I just had to. @snovotill entitled much? How about contribute to fixing this OPENSOURCE and free project yourself. Like you heard, upstream bug in firefox. You gave the project 3 stars because of a fault in the browser you're using. Ditch Firefox maybe?

**Comment by snovotill** [comment]
I report bugs once in a while (I'm a terrible programmer) and in this 
case I included a suggestion for action on your part. There is someone 
out there somewhere who is a good programmer and would be happy to fix 
this bug in FireFox, but you have not made it publicly known and so you 
won't find that person. Please add a pop-up into your SingleFile so that 
this problem gets advertised and noticed. Is this really so wrong? There 
is very little else of value I can add to this discussion and the 
decision is ultimately yours. I probably already said too much about the 
vicious authoritarian nature of many security minded people who have 
infested FireFox and dummbed it down to the point where it's useless. 
Java plugins suffered a similar fate. Please don't let this go on and 
affect your otherwise excellent plugin.

**Comment by snovotill** [comment]
I'll try calling him and Craig again tonight. Hopefully one of them 
picks up. I don't understand how they can be away from their phones so 
much. Dad won't be able to complete a service call with Shaw, so we may 
be stuck using the little cell once it's plugged back in. That little 
phone is crap. It needs to be rebooted every couple of months.

**Comment by snovotill** [comment]
Gloria went to see him and then came back and called me from her house. 
I did tell her the small phone needs to be rebooted. She said the phones 
were dead and that the cell phone was fully charged. Not helpful in any 
way. Why don't you try with Joe tonight. He is currently not picking up. 
I won't be home tonight until midnight.

**Comment by gildas-lormeau** [comment]
@snovotill I forgot to mention the existence of "SingleFile Legacy". I think it should work in Waterfox (maybe the annotation editor won't work though) and it should fix your issue.

**Comment by gildas-lormeau** [comment]
Link download SingleFile Legacy on the store: https://addons.mozilla.org/firefox/addon/singlefile-esr-52/

**Comment by snovotill** [comment]
**Please understand the purpose of this bug report.** I am not personally looking for a solution. The purpose is as follows:

Glidas, you have invested significant time into making your plugin compatible with Firefox but as you know it does not work well because of a FireFox issue. Not only have you wasted your time (the very essence of life) but you are harming your reputation because people will always blame your for the problems using the extension.

You have a simple choice: Either roll over and die (as you have already done) or program in a pop-up dialog which comes up whenever your extension fails to explain the problem. Someone who is capable of fixing the bug will eventually see this and then the Firefox bug will be fixed. Maybe it will be fixed in Waterfox and not in Firefox, but it will eventually be fixed if you advertise it in this way.

The bug affects other programs, not just yours. By taking intelligent action, or any action at all, you will do the world a flavor.

**Comment by gildas-lormeau** [comment]
Currently, there is simply no UI for displaying errors in SingleFile. It's somewhat a deliberate choice because web extensions don't really offer a way to display them. Also, using a simple `window.alert` for this is not really acceptable for this because it's not powerful enough and it could be easily faked by a "malicious" website. Moreover, errors are very common and at least 99% of the time, they can be safely ignored. Thus, it could be annoying for users to be notified about useless errors. Also, I don't want to code a specific implementation for this bug in particular. The implementation has to be generic and work for all types of error without being too cryptic for users. It's not a simple issue.

**Comment by snovotill** [comment]
That's unfortunate. I suppose it may be an option to place text into the web page being saved, in place of the missing image? I had sincerely thought that finding some way to move this along would be very worthwhile. It all seems very tragic the way this plays out.
