### ISSUE TITLE
Supports 360 secured browser | can't open the installation instructions page

### ISSUE THREAD

**Issue by Scott307** [gildas-lormeau/SingleFile#757]
Can support 360 secured browser? Some say it's Chromium + double kernel, IE the website is 86 kernel based on Chromium. Can't open the download zip in Chromium and manual installation page.

**Comment by Scott307** [comment]
My English is not good, this is a computer translation.

**Comment by gildas-lormeau** [comment]
Please follow these instructions and tell me which one is causing any issue:

1. Download this zip file: https://github.com/gildas-lormeau/SingleFile/archive/refs/heads/master.zip
2. Unzip it somewhere on your disk
3. Open se://extensions/ in 360 Secure Browser
4. Enable the checkbox "Developer Mode" at the top right of the page
5. Click on the button "Load unpacked extension..." at the top left of the page
6. Select the folder where you unzipped the zip file

se://extensions/

**Comment by Scott307** [comment]
![扩展程序](https://user-images.githubusercontent.com/89132146/130063661-2acf9a3b-268e-4a8e-b03d-9b1519459c6a.png)
![扩展程序2](https://user-images.githubusercontent.com/89132146/130063675-13b0b38a-12e3-437d-87a3-a4ccba184cfd.png)

**Comment by gildas-lormeau** [comment]
You can ignore this error, this does not prevent SingleFile from working properly.

**Comment by gildas-lormeau** [comment]
I'm closing the issue because it looks like you were able to install SingleFile.
