### ISSUE TITLE
CLI bug or bad example

### ISSUE THREAD

**Issue by JustACuteGirlLookingForAManToFixHerBugs** [gildas-lormeau/SingleFile#758]
So, I've installed the CLI version (hurray for me!)

But the command from the Readme: 

```single-file https://www.wikipedia.org --crawl-links=true --crawl-inner-links-only=true --crawl-max-depth=1 --crawl-rewrite-rule="^(.*)\\?.*$ $1" ```

Well it saves only one file! It might be that wikipedia.org doesn't have inner links, lol, but then it's a bad example for crawling links.

**Comment by gildas-lormeau** [comment]
You might consider it's a bad example since there are indeed no inner links and it's not particularly funny.

You can verify it yourself by running this script is the developer tools:

`Array.from(document.links).filter(link => link.href.startsWith("https://www.wikipedia.org/"))`

**Comment by gildas-lormeau** [comment]
Note that I cannot provide a "good example" since crawling websites is usually forbidden. The only site I know that I can use as example is example.com. Unfortunately, there are no links.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because I don't know how to fix it.
