### ISSUE TITLE
SingleFile with reader view in Firefox 62

### ISSUE THREAD

**Issue by Len44** [gildas-lormeau/SingleFile#76]
Hi - 
I think I have found an issue. 
If I tick the box beside 'open the "Save as" dialog to confirm the file name', the dialog box does not open, in Firefox _reader view_.
Firefox 62.0.2 (64-bit), Windows 10 version 1803 (OS Build 17134.285)

Also - a documentation issue: I can't seem to find what the default save folder is.
Thanks for all your help.
LB

**Comment by gildas-lormeau** [comment]
Hi,
That's weird. I thought extensions could not run in the reader view. Currently, I cannot use SingleFile at all in this mode. How did you achieve to make it run? It would help me reproducing the issue.

The default save folder is supposed to be the download folder configured in your browser, cf. about:preferences. Do you mean I should provide this link somewhere in the documentation?

**Comment by Len44** [comment]
Sorry. That’s what I meant to say – it does not work in reader view. But this is obviously not an “issue”, or at least is a known issue for addons.

 

As for the download folder, definitley yes, in answer to your question.

I have Firefox configured for the Downloads folder. BUT, I have the radio button for “Always ask you where to save files” turned on. In any event, I would like to see it explicitly stated that the default download folder for SingleFile is whatever is configured in Firefox.

With the default options set for SF, I get no dialog box at all – so it doesn’t respect my “always ask me” option. That’s okay, I just think it should be spelled out.

Thanks.

LB

**Comment by gildas-lormeau** [comment]
I updated the documentation and the descriptions in the extension stores, cf. "Additional notes".

**Comment by gildas-lormeau** [comment]
@Len44 The new version 1.17.0, currently being reviewed by Mozilla and which should be available soon for download provides a new button "Format the page for better readability" in the annotation editor. By clicking on this button, the page will be formatted in the same way as the reader view.

**Comment by Len44** [comment]
Thanks.
