### ISSUE TITLE
Clear profiles and url rules suddenly

### ISSUE THREAD

**Issue by AliM1988** [gildas-lormeau/SingleFile#766]
According my another [issue](https://github.com/gildas-lormeau/SingleFile/issues/296),   I faced with the problem again after 2 years:  The profiles that I created and their rules that I set to domains is cleared!  I saw that after updating Extension to version 1.19.

Regard

**Comment by gildas-lormeau** [comment]
Are you using a third-party program like CCleaner to "clean" your computer?

**Comment by AliM1988** [comment]
No, at all.

**Comment by gildas-lormeau** [comment]
Did you enable the "sync" feature in the SingleFile options page?

**Comment by AliM1988** [comment]
Yes

**Comment by gildas-lormeau** [comment]
As you can imagine, I have no idea of what could cause this issue. Did you do anything special like installing SingleFile in a new browser just before this bug appeared?

**Comment by AliM1988** [comment]
No, just I see the issue after new update.

**Comment by gildas-lormeau** [comment]
Did you lose your settings in all your browsers?

**Comment by AliM1988** [comment]
Yes

**Comment by gildas-lormeau** [comment]
Do you use the stable version of Chrome on both PCs?

**Comment by AliM1988** [comment]
Yes, both of them are up-to-date (automatically).

**Comment by gildas-lormeau** [comment]
I'm still not very inspired by what could cause this problem. Does this happen often?

**Comment by gildas-lormeau** [comment]
I'm closing this issue. Feel free to reopen or comment it it if the problem still happens or if you have more info.
