### ISSUE TITLE
SingleFile 1.19.0 (?) does not follow File Name Template

### ISSUE THREAD

**Issue by SomwareHR** [gildas-lormeau/SingleFile#767]
**Describe the bug**

File name template is set to this:
```{page-title} ({date-locale} {time-locale}).html```
and
```Prompt for a name```
(Img.1)

SF yet offers random filename, like:
```4d0ecbe5-18a5-40e0-9f6b-4e133e936d4c```
(even tho there is never a duplicate name in folder, and also could not be considering that there is a "time-locale" in file name template)
(Img.2)

**To Reproduce**

What I tried:
- tampering with various options in File name template .. no progress
- reset settings .. no progress
- uninstall and install extension .. no progress
- Sync = "off" + reset to avoid downloading some old misconfiguration .. no progress

**Expected behavior**

Follow the template

**Screenshots**

![Img.1](https://user-images.githubusercontent.com/45540611/131789614-4a2f6600-f70e-455d-84b2-b691118ce2bf.png)

![Img.2](https://user-images.githubusercontent.com/45540611/131789641-62efd2a8-6c9a-40e6-a65c-c15b4714547d.png)

**Environment**

+ Latest Win10 Pro
+ MS Edge Version 92.0.902.84 (Official build) (64-bit) (latest)

**Additional context**

This was working fine before in same environment. 

I am not 100% sure if this changed with 1.19.0 or with Edge updates.

**Comment by gildas-lormeau** [comment]
This is a known issue in Chrome, see https://github.com/gildas-lormeau/SingleFile#known-issues and https://bugs.chromium.org/p/chromium/issues/detail?id=892133. Maybe Google will fix it someday.

**Comment by SomwareHR** [comment]
Thanks.  SingleFile >Extension options > Misc > Disable "Save pages in background" solved the thing.

![image](https://user-images.githubusercontent.com/45540611/131885166-d5cbf9e4-9734-4158-855d-21667c97ccfd.png)
