### ISSUE TITLE
Saved page layout messed up

### ISSUE THREAD

**Issue by najloa** [gildas-lormeau/SingleFile#768]
Describe the bug
The saved layout of this page gets messed up
https://www.youtube.com/watch?v=nkcpcvxl44s

To Reproduce

Go to 'https://www.youtube.com/watch?v=nkcpcvxl44s'
Save page
Inspect saved file

Screenshots
![600](https://user-images.githubusercontent.com/15027661/131860135-653fcab3-17c1-4703-849b-91a029e0a417.png)

Environment

OS: Win10
Browser: Chrome 93.0.4577.63
Version: SingleFile 1.19.2

**Comment by gildas-lormeau** [comment]
It's a bug in the HTML of Youtube. I thought it was fixed, cf. https://github.com/gildas-lormeau/SingleFile/issues/603.

In fact, I'm not very motivated to add a specific fix for Youtube in SingleFile.

**Comment by gildas-lormeau** [comment]
Note that it can be fixed by running a userscript though. I'll try to povide the instructions on how to do this.

**Comment by gildas-lormeau** [comment]
This issue will be fixed in the version `1.19.7`.
