### ISSUE TITLE
Discuss : possibility to execute standalone (callable in devtools) process ?

### ISSUE THREAD

**Issue by fcamblor** [gildas-lormeau/SingleFile#769]
**Is your feature request related to a problem? Please describe.**
I was wondering if it was something doable to provide an importable module for `single-file`, that could make it executable programmatically from DevTools (without having to install the extension)

Something like : 
```
import SingleFile from 'https://cdn.skypack.dev/single-file-standalone'
const capturedHtml = await SingleFile()
// do something with captured html
```

(this is maybe something already existing / easily achievable, but didn't found it in the doc as the CLI is not matching my need here unfortunately, see in additional context section below)

**Describe the solution you'd like**
Publish a JS library providing API used to capture current page programmatically.

**Additional context (optional)**
The extension is fantastic, but in some cases, I would like to trigger it directly from devtools.

Typically, I need to capture HTML generated on an Android device webview (where I can't install the chrome extension, and where I can't get any URL that could be processed by the CLI).
I can remotely inspect the Android webview from my laptop, and can have access to the whole devtools context (including DOM, etc.) from it, but didn't found any way to remotely capture DOM content as single file.

With such standalone library, I assume this would become something feasible.
WDYT ?

_(not sure if this would be that easy anyway, as any extension API would have to be avoided in that case)_

**Comment by gildas-lormeau** [comment]
Hi @fcamblor, nice to hear from you (I'm the founder of seo4ajax.com) :)

You can achieve this by:
1. Injecting `https://raw.githubusercontent.com/gildas-lormeau/SingleFile/master/dist/single-file.js` in the webview, it will create a global variable named `singlefile`
2. Running for example the following code (all the options are set to `false` by default)
```js
const { content, title, filename } = await singlefile.getPageData({
  removeImports: true,
  removeScripts: true,
  removeAudioSrc: true,
  removeVideoSrc: true  
});
```

The variable `content` will contain the HTML content of the page. Frame contents won't be embedded.

Note however that you will need to disable CORS in order to be able to retrieve contents from external domains. Otherwise, it's also possible to pass a custom function used to fetch all the contents. This is how SingleFile solves this issue in the JSDOM implementation, see below
https://github.com/gildas-lormeau/SingleFile/blob/6b9b6df0223d779009cacee4915d40839c95bce8/cli/back-ends/jsdom.js#L81

https://github.com/gildas-lormeau/SingleFile/blob/6b9b6df0223d779009cacee4915d40839c95bce8/cli/back-ends/jsdom.js#L87-L107

I hope this information is useful. Feel free to ask me more questions.

**Comment by fcamblor** [comment]
Hi @gildas-lormeau (and yes, happy to see you again ;-)),

This is perfect, this whole material is very helpful (and is working like a charm, just tested it).
Thanks a lot for that, you don't know how much time you just saved me :)

**Comment by gildas-lormeau** [comment]
Great! (I edited the message because I wasn't 100% sure you were the right fcamblor ;-)). I am really glad to hear that SingleFile is useful to you.

**Comment by fcamblor** [comment]
@gildas-lormeau Hello Gildas (and sorry to bother you again ! :-) )

I'm facing an issue on `fetchResource` impl (from your jsdom example) : when one of my links targets a `svg+xml` file, this is not working.
By debugging it, I discovered that `xhrRequest.readyState` was never `DONE` when using a `xhr.responseType = "arraybuffer"` on a SVG URL.

I tried to tweak a little bit the implementation (using `xhr.responseType="text"` and `TextEncoder.encode()` on the response), but it doesn't seem to work (I continue having a `<img src="data:null;base64," />` resolved image in the DOM)

I noticed there was a [`util.parseSVGContent()` utility function](https://github.com/gildas-lormeau/SingleFile/blob/master/lib/single-file/single-file-core.js#L1920) but it seems to only be called in `xlinks`.

FYI, my altered `fetchResource` impl : 
```
async function fetchResource(resourceURL, win) { 
 	return new Promise(function (resolve, reject) { 
 		const xhrRequest = new win.XMLHttpRequest(); 
 		xhrRequest.withCredentials = true;
 		if(resourceURL.substr(resourceURL.length-".svg".length) === '.svg') {
 		    xhrRequest.responseType = "text";
 		} else {
 		    xhrRequest.responseType = "arraybuffer"; 
 		}
 		xhrRequest.onerror = function(event) { 
			console.error(`Got an error while fetching ${resourceURL}: ${JSON.stringify(event)}`);
			return reject(new Error(event.detail)); 
		};
 		xhrRequest.onreadystatechange = function() {
 			if (xhrRequest.readyState == win.XMLHttpRequest.DONE) { 
 				if(xhrRequest.responseType === "text") {
 					console.log("text response type !");
				}
				resolve({ 
					arrayBuffer: function(){
						var ui8Array;
						if(xhrRequest.responseType === 'text') {
							ui8Array = new TextEncoder().encode(xhrRequest.response);
						} else {
							ui8Array = new Uint8Array(xhrRequest.response);
						}
						return ui8Array.buffer;
					}, 
					headers: { 
						get: function(headerName) { return xhrRequest.getResponseHeader(headerName); }
					}, 
					status: xhrRequest.status 
 				}); 
			} 
 		}; 

 		console.debug(`Opening ${resourceURL}...`);
 		xhrRequest.open("GET", resourceURL, true); 
 		xhrRequest.send(); 
 	}); 
 } 
```

Would you have any piece of advice to share on this ?

**Comment by fcamblor** [comment]
Hello Gildas,

I was doubly wrong ... SVG files were properly loaded (even with `arraybuffer` responseType).

I just found the root cause of my issue : I was executing `single-file` inside a `cordova webview` where `FileReader` class was overridden ... but without `addEventLIstener()` method on it

This was resulting into a silent error [here](https://github.com/gildas-lormeau/SingleFile/blob/master/lib/single-file/single-file-util.js#L242), leading to a `data:null;base64` replacement.

Sorry for the false positive and the inconvenience / useless noise.

**Comment by gildas-lormeau** [comment]
Hello Frédéric,

No problem, I'm really glad to hear this was not in fact a weird issue and that you were able to identify and fix its root cause. A quick and dirty way to circumvent it could be to implement the missing `addEventLIstener` method, e.g. inject the code below before running SingleFile (not tested):
```js
FileReader.prototype.addEventListener = function(name, callback) { this["on" + name] = callback; }
```

BTW, if it is possible, I would be interested to know more about your use case, it sounds interesting :)

**Comment by fcamblor** [comment]
That's exactly what I did, with a little difference :-)
```
  if(!FileReader.prototype.addEventListener && eventName) {
    FileReader.prototype.addEventListener = function(eventName, callback, useCapture) {
          // Loosing useCapture flag here... not a big deal at the moment
	  this['on'+eventName.toLowerCase()] = callback;
	};
  }

```

My use case is : I'm working on a web app aimed at translating web applications.

One of the main features of this webapp is to be able to provide context to translators, and particularly "living apps" where translatable messages reside (that way, they are able to see in realtime if the translation they provided is going to break a screen or not)

https://user-images.githubusercontent.com/603815/136160419-9ebfa9d0-fbb1-48ad-b155-e3bcfea0a1b3.mov

What I call a "living app" is typically a self-sufficient single HTML page that he can upload to the translation app (the blue part in the video above) and this is where `single-file` comes in : I wrote a small js snippet aimed at capturing self-sufficient HTML page during app browsing, so that my users are able to easily contribute screens to the translation app while navigating on the apps they want to translate.

Given that we're working a lot with Cordova for our mobile apps, I need to make this work on cordova webviews as well, and this is now working since yesterday evening (or, let's say ... today early morning ;-))

**Comment by gildas-lormeau** [comment]
That's a great use-case! It also sounds like a great user experience. This is not the first time that SingleFile is used in the translation field. Funny, I didn't anticipate it. Anyway, I hope SingleFile will bring you satisfaction. Good luck and don't hesitate to ping me if you need help.
