### ISSUE TITLE
Auto-save seems not to trigger lazy load and has impact to css

### ISSUE THREAD

**Issue by maiux** [gildas-lormeau/SingleFile#770]
**Describe the bug**
I'm trying to auto-save a tab, but it does not trigger lazy load and actually the page saved has some images missing. I had the same experience with SingleFileCLI, using related parameter, but I'm referring to the extension here.

**To Reproduce**
1. Go to https://www.lg.com/it/microonde/lg-MJ3965ACS
2. Click on "Save page with SingleFile", will appear a progress box in the lower left corner, saying "Loading deferred..." and go through steps 1, 2 and 3 
3. Check the saved page
4. Enable "Auto-save all tabs"
5. Open new tab and go to same address
6. Wait to the [A] in the extension icon to become white on black background, progress box will not appear
7. Check the new saved page, background images will be missing near "3 volte più luminoso" text

**Expected behavior**
Since options aren't changed, I'd expected the same behavior of clicking on "Save page with SingleFile"

**Screenshots**
Attached files: [Archivio.zip](https://github.com/gildas-lormeau/SingleFile/files/7115906/Archivio.zip)

**Environment**
 - OS: Big Sur 11.5.2 on Intel MacBook Pro 16"
 - Browser: Chrome 
 - Version: 93.0.4577.63 (Build ufficiale) (x86_64)

**Additional context**
Since the file sizes are the same, maybe it's only a css visibility issue.

**Comment by maiux** [comment]
I confirm: loading deferred images (obtained with manual save) will remove "lazyload" class from images that will be visibile in saved files.
Instead autosaving keeps "lazyload" class that will determine hidden images in saved file. I think that scrolling will avoid the problem, IMHO.

**Comment by gildas-lormeau** [comment]
I confirm that lazy loaded contents won't be loaded when SingleFile auto-saves a page. The reason is that it's not really a transparent process for the user and it can take a significant amount of CPU/time. So, it could sometimes disrupt/break the navigation and I guess that would be very annoying.

**Comment by maiux** [comment]
So there isn't a way to trigger autosave, i.e. forcing it? Many pages have dynamic content that will not load without it.

**Comment by maiux** [comment]
In the meanwhile I got to have full page as I needed using a javascript injection via browser-script. I'm posting it, can be useful to anyone:
```javascript
// ==UserScript==
// @name         Scroll the whole page to load dynamic content and trigger javascript events
// @namespace    https://github.com/gildas-lormeau/SingleFile
// @version      1.0
// @description  Try to load whole page content and trigger JS events
// @author       Fabio Maione (maiux)
// @match        *://*/*
// @grant        none
// ==/UserScript==
(() => {
  
  // let's tell around we are starting :)
  dispatchEvent(new CustomEvent("single-file-user-script-init"));
  console.log("lazyLoadWorkAround: user-script-init");

  // let's add the code to run before capture: the full page scroll
  addEventListener("single-file-on-before-capture-request", async event => {
    // used to wait a bit while scrolling
    function sleep(ms) {
      return new Promise(resolve => setTimeout(resolve, ms));
    };

    console.log("lazyLoadWorkAround: before-capture-request, running...");
    event.preventDefault(); // since we are async here
    try {
      let scrollPoint = window.innerHeight; // scroll one screen-height a time
      let maxScrollableHeight = document.body.scrollHeight;
      while (scrollPoint < maxScrollableHeight) {
        window.scrollTo(0, scrollPoint);
        scrollPoint += window.innerHeight;
        await sleep(500); // let's wait for some scrolling effects
        maxScrollableHeight = document.body.scrollHeight; // let's update maxScrollable if we got some dynamic content
      };
    } finally {
      dispatchEvent(new CustomEvent("single-file-on-before-capture-response"));
      console.log("lazyLoadWorkAround: before-capture-request, done.");
    }
  });

  addEventListener("single-file-on-after-capture-request", () => {
    console.log("lazyLoadWorkAround: after-capture-request");
  });

})();
```
