### ISSUE TITLE
How to use SingleFile API outside of extension context?

### ISSUE THREAD

**Issue by ralphilius** [gildas-lormeau/SingleFile#773]
**Is your feature request related to a problem? Please describe.**
I'm trying to use SingleFile on my server but I can't seems to get it to work. Do you know how I could get it to work on my server? I could use puppeteer as the browser.

**Describe the solution you'd like**
Something simple like 
```js
 const { html } = await singlefile.getPageData(options);
```

**Comment by ralphilius** [comment]
> You should be able to run SingleFile on your server as a CLI tool by following the documentation here: https://github.com/gildas-lormeau/SingleFile/tree/master/cli. You could also modify the existing puppeteer code used by the CLI tool here: https://github.com/gildas-lormeau/SingleFile/blob/master/cli/back-ends/puppeteer.js. Basically the `/cli` folder is an answer to your question.
> I also described the minimum things that should be done in order to run SingleFile outside the extension context here: [#769 (comment)](https://github.com/gildas-lormeau/SingleFile/issues/769#issuecomment-913822451).

Thanks for your prompt reply. 

1. I have successfully installed and run `single-file` as command line here: https://github.com/gildas-lormeau/SingleFile/tree/master/cli. However, I want to use it inside my code. Do you know how should I achieve it?
2. I read through your comment https://github.com/gildas-lormeau/SingleFile/issues/769#issuecomment-913822451 earlier, but not sure how it could work in server environment where we don't have `window`?

**Comment by gildas-lormeau** [comment]
1. You could fork my code (cf. the `/cli` folder)
2. The code of SingleFile is run via puppeteer in Chrome so the `window` object does exist

**Comment by ababushkin** [comment]
The answer in the linked thread did the trick, thanks @gildas-lormeau, and brilliant work.

Is there a reason why certain parts of the page can't be saved as consistently in comparison to when I'm using the extension directly?

e.g. `<model-viewer>` components don't get saved property when running outside an extension context, but is saved perfectly when it is.

**Comment by gildas-lormeau** [comment]
The reason is that I provided the minimum thing to do to use SingleFile outside an extension context. In order to handle custom elements with a shadow root (e.g. `<model-viewer>`), you have to inject `dist/single-file-bootstrap.js` in the page.

**Comment by gildas-lormeau** [comment]
Some additional info about how to use SingleFile in a custom script: https://github.com/gildas-lormeau/SingleFile/wiki/How-to-integrate-SingleFile-library-code-in-%22custom%22-environments%3F
