### ISSUE TITLE
Fails to save ChemDoodle on Edx.org

### ISSUE THREAD

**Issue by daspri** [gildas-lormeau/SingleFile#774]
**Describe the bug**
Chemdoodle's are saved when on the Chemdoodle website, but not when they are integrated into the Edx.org website.

**To Reproduce**
Edx.org requires free login.

Direct URL to a web page with an integrated ChemDoodle:
https://learning.edx.org/course/course-v1:MITx+5.01x+3T2020/block-v1:MITx+5.01x+3T2020+type@sequential+block@92e665b34e114e4595f077af228ccbff/block-v1:MITx+5.01x+3T2020+type@vertical+block@a0e0290ff61c441a896dc512a1f4e0b3

Which is from this course:
https://learning.edx.org/course/course-v1:MITx+5.01x+3T2020/home
Module 5
- Lewis Structures Part I
- Part 5
- ChemDoodle Introduction:
Screenshot of the page's header:
![header](https://user-images.githubusercontent.com/4674343/132770585-93f56904-e172-46ef-ae6e-cdfdbdd39b8e.jpg)

**Expected behavior**
I expect the chemdoodle to be saved.

**Screenshots**

Top is from the ChemDoodle Demo: https://web.chemdoodle.com/demos/2d-sketcher
Left = Firefox, Right = SingleFile.   The doodle is saved properly.

Bottom is a ChemDoodle integrated on Edx.org: https://learning.edx.org/course/course-v1:MITx+5.01x+3T2020/block-v1:MITx+5.01x+3T2020+type@sequential+block@92e665b34e114e4595f077af228ccbff/block-v1:MITx+5.01x+3T2020+type@vertical+block@a0e0290ff61c441a896dc512a1f4e0b3
Left = Firefox, Right = SingleFile.  The doodle is not saved (empty white area).

![doodle](https://user-images.githubusercontent.com/4674343/132770155-1a633fb8-b1ca-42fc-8bda-b7b16110bca9.jpg)

**Environment**
Firefox 91.0.2 
SingleFile 1.19.5

**Comment by gildas-lormeau** [comment]
I was able to reproduce and fix the issue. The fix will be available in the version `1.19.8`.
