### ISSUE TITLE
Unable to load as Temporary Extension in Firefox

### ISSUE THREAD

**Issue by daspri** [gildas-lormeau/SingleFile#775]
**Describe the bug**
When loaded as a temporary extension, SingleFile fails to work.

**To Reproduce**
From the github instructions:

```
You can also download the zip file (https://github.com/gildas-lormeau/SingleFile/archive/master.zip) of the project and install it manually by unzipping it somewhere on your disk and following these instructions:
Firefox: https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/
```

I do so and get these warnings:
![text](https://user-images.githubusercontent.com/4674343/132773884-c03b6b5d-ffaa-42fd-b683-0256daadbc20.jpg)

But the extension options are empty when managing the extension:
![manage](https://user-images.githubusercontent.com/4674343/132773908-879ee3ca-9908-4df3-92b8-5493bd4b848b.jpg)

And SingleFile does not let me save a page.  Pressing "Save with Single File" tool button does not work.

**Comment by gildas-lormeau** [comment]
That's weird. Warnings are normal and don't prevent the extension to work. However the options page and the extension should work.

Maybe your profile is corrupted. Could you create a temporary profile in Firefox, install SingleFile manually and see if that changes anything?

**Comment by daspri** [comment]
This seems to be a Firefox issue.  If I unzip SingleFile to a different drive (not the RAM drive with %TEMP% on it), it works.

**Comment by gildas-lormeau** [comment]
Ok, thank you for the feedback!
