### ISSUE TITLE
Add the option --emulate-media-feature (CLI)

### ISSUE THREAD

**Issue by Spicadox** [gildas-lormeau/SingleFile#776]
**Describe the bug**
I've used both the CLI and extension to download the page and the layout still messes up. My goal is to be able to archive the page and crawl the links at least once, hence why I prefer the CLI version over the chrome extension. The command I used is 
`single-file --browser-cookies-file="I:\archive scripts\batch scripts\singlefile_script\cookie.txt" --browser-executable-path="C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --browser-wait-delay=5000 --browser-height=100000 --crawl-links=true --crawl-replace-urls=true --crawl-max-depth=1 https://www.youtube.com/channel/UC0TXe_LYZ4scaW2XMyi5_kw/community`

The layout problem I ran into using both methods was that 1) The banner image is gone 2) channel header and toolbar seems to be fixed to the middle of the webpage. 
Another problem that occurred with the CLI version was that when I supplied my cookies, instead of using my dark mode it uses the default white mode(not a big deal but just weird that the cookie works but doesn't display the correct mode). It can all be seen on my screenshots.

**To Reproduce**
1. Go to any youtube channel. I specifically used `https://www.youtube.com/channel/UC0TXe_LYZ4scaW2XMyi5_kw/community`
2. Click on the community's tab
3. Use either the chrome extension or preferably the CLI with the command I used above
4. See layout issue

**Expected behavior**
When using the CLI I expected the same result as what I would get from the chrome extension but both seems to have same issue. I used SingleFile a while back and was hoping to expect the same result(even back then it wasn't perfect, but it was bearable since the header and toolbar didn't seem to be fixed onto the middle of the screen).

**Screenshots**
The initial unscrolled page was downloaded using the CLI 
![Screenshot 2021-09-09 221700](https://user-images.githubusercontent.com/60198162/132788464-e720052e-e0f2-4298-8793-8b290cfe06d7.png)

The page after scrolling down a little
![Screenshot 2021-09-09 222256](https://user-images.githubusercontent.com/60198162/132789052-db4f746d-8159-46ee-87d9-5eca4c43cb9e.png)

For reference, this is the same page but I used the chrome extension. The layout is a little better than the CLI version since the channel header and toolbar are slightly higher up on the page and doesn't even cover the first youtube post, unlike the CLI version, but it's still fixed to the middle of the page.
![Screenshot 2021-09-09 224226](https://user-images.githubusercontent.com/60198162/132790769-63be7dde-953b-436a-b17f-43ffb92953c5.png)

**Environment**
 - OS: Win10
 - Browser: Chrome
 - Version: 64

**Additional context**
Not too sure if this is related to #768 since najloa also had issues with youtube's layout

**Comment by gildas-lormeau** [comment]
The first issue is fixed. The second issue is related to the fact that the header is positioned with JavaScript. You could maybe circumvent it by tweaking the CSS before saving the page with a user script. Regarding the theme issue, it means that this information is probably not stored in the cookie. I need to do more investigation on this, did you select "Use device theme" or "Dark theme" in the settings of Youtube?

**Comment by Spicadox** [comment]
Alright, gotcha thanks for the insight. I selected "Use device theme" instead of "Dark theme". I didn't even realize Youtube added this new feature, but after changing "Use device theme" to "Dark theme" I was able to get the page correctly in the dark theme. Thanks for the help!

**Comment by gildas-lormeau** [comment]
I think I need to check if I can configure Chrome in dark mode when running in headless mode. Thus, you wouldn't need to select explicitly "Dark theme". Note that I also fixed https://github.com/gildas-lormeau/SingleFile/issues/768 because YouTube will never fix it.

**Comment by gildas-lormeau** [comment]
For the record, here is the API that needs to be exposed to the CLI via a new option: https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pageemulatemediafeaturesfeatures.

**Comment by gildas-lormeau** [comment]
The option `--emulate-media-feature` has been implented (commit https://github.com/gildas-lormeau/SingleFile/commit/ecebe6c31ef7d28c67dd39c7a56057ebc191a0e5)
