### ISSUE TITLE
Infobar is only displayed in original browser 

### ISSUE THREAD

**Issue by Victor239** [gildas-lormeau/SingleFile#777]
**Describe the bug**
If I save a webpage in Browser 1 (eg first Firefox Desktop browser), I can see the Infobar whenever I open it again. If I try to view that same webpage in Browser 2 (eg second separate Firefox Desktop browser) or Browser 3 (Chromium browser) then it won't show the Infobar, even when "display an infobar when viewing a saved page" is enabled.

**To Reproduce**
1. Create a SingleFile
2. Open the webpage manually in the same browser, see the Infobar
3. Open the webpage manually in a different browser, don't see the Infobar

**Expected behavior**
The Infobar should be accessible regardless of the file being opened in a different browser.

**Screenshots**
N/A

**Environment**
 - Kubuntu 21.04
 - Browser: Firefox
 - Version: 92

**Comment by gildas-lormeau** [comment]
The infobar relies on JavaScript to work properly. That's why it's not included by default in saved pages. You must enable the option `HTML content > include the infobar in the saved page`.
