### ISSUE TITLE
Lazy loaded contents in iframes are not saved on Medium

### ISSUE THREAD

**Issue by mwnoo** [gildas-lormeau/SingleFile#779]
**Describe the bug**
Lazy loading elements (GitHub gists, youtube links) are not captured using docker singlefile 
In the output these elements are blank

**To Reproduce**
1. `docker run singlefile "https://towardsdatascience.com/how-to-train-a-bert-model-from-scratch-72cfce554fc6" > bert.html`
2. `docker run singlefile "https://towardsdatascience.com/how-to-train-a-bert-model-from-scratch-72cfce554fc6" > bert.html --load-deferred-images-max-idle-time 8000`

**Expected behavior**
The elements containing embedded code blocks (gists) from Github and youtube links should be visible in the output

**Environment**
 - OS: Ubuntu 20.04.3
 - singlefile docker image 

**Additional context**
Using the FireFox extension I have the same issue when I only open the page and run singlefile. When I scroll down the page and then run singlefile some of the elements are captured in the output. But this seems not possible with the docker version of singlefile.

**Comment by gildas-lormeau** [comment]
I confirm the issue and it's not specific to docker. I'll try to see what's wrong even though I'm tired of trying to understand how the lazy loading works on Medium. It's like they're trying really hard to make my life more complicated.

**Comment by mwnoo** [comment]
I understand how difficult it is to keep up with all those performance tweaks websites implement these days and I really appreciate all the time and effort you put into this amazing tool. SingleFile is a great tool!

**Comment by WellRedPandit** [comment]
> cicurmvented with a user script which would scroll to the end of the page

@gildas-lormeau , would you be kind enough to sketch out such a script? or point to a script of this kind you may know of? i'm not a front-end developer, so it's a bit hard for me to come up with one, but i would love to test it out in chrome and firefox. 

and thank you again for your great extension!
