### ISSUE TITLE
Singlefile freezes browser

### ISSUE THREAD

**Issue by janneman-1** [gildas-lormeau/SingleFile#780]
Occasionally, Singlefile will freeze the browser when saving a particular web page. The browser will be hogging one CPU and all browser tabs and windows will be unresponsive. The only way out is to kill the browser from windows task manager.

Here is one page that consistently causes this behaviour: https://www.bbc.co.uk/programmes/m000z65t.

In the case of this particular url, the problem is persistent, i.e. the same thing happens when you restart the browser and try again. This is not always the case. Sometimes the problem does not happen again after restarting the browser. The other slight variation is the point at which things freeze. Sometimes it is at "deferred images" or at step 2. With the BBC page, it's at to the Save/Save As dialog.

I've seen the problem on multiple computers with multiple browsers: Edge, Chrome and Firefox.

**Environment**
Edge 93.0.961.47 (Official build) (64-bit)
Firefox 92.0 (64-bit)
Version 93.0.4577.82 (Official Build) (64-bit)
Win10-pro-64 21H1 19043.1237

**Comment by gildas-lormeau** [comment]
Thank you very much for the detailed bug report. I was able to reproduce and fix it. The fix will be available in the version 1.19.9 which should be published early next week, after being reviewed by Mozilla and Microsoft.
