### ISSUE TITLE
hello "Auto-save" not working 

### ISSUE THREAD

**Issue by zeus6999** [gildas-lormeau/SingleFile#781]
hi.
 "**Auto-save**" not working
for what  
"**Autoclose tab after the page is saved**"  not working

regards

**Comment by gildas-lormeau** [comment]
I cannot reproduce your issue. However, I already fixed the same issue 12 days ago, see https://github.com/gildas-lormeau/SingleFile/issues/772. Make sure you're using the latest version of SingleFile.

**Comment by zeus6999** [comment]
It was my fault .
Auto-save was disabled. I didn't know you can disable from two different settings
http://prntscr.com/1t9brin
thanks, you did a fantastic extension

**Comment by zeus6999** [comment]
It was my fault .
Auto-save was disabled. I didn't know you can disable from two different settings
http://prntscr.com/1t9brin
thanks, you did a fantastic job

**Comment by gildas-lormeau** [comment]
No problem, you're welcome!
