### ISSUE TITLE
Chrome DevTools console errors with SingleFile

### ISSUE THREAD

**Issue by WhiteMac** [gildas-lormeau/SingleFile#782]
I have SingleFile (latest, 1.19.9) and Chrome (latest, 93.0.4577.82) on macOS.

For at least a few weeks now, SingleFile has been producing the following console error on every page load:

```
extension-bootstrap.js:1 Uncaught ReferenceError: browser is not defined
    at extension-bootstrap.js:1
    at extension-bootstrap.js:1
```

Disabling the extension makes the error go away (which is what I've been doing when I don't need to use SingleFile).

The issue doesn't occur with SingleFileZ.

**Comment by gildas-lormeau** [comment]
I confirm I've also seen this issue. From my point of view, it's a bug in Chrome. This error should be impossible. I also don't see any reason why SingleFileZ would not suffer from this issue. I'll try to circumvent it in the next version by injecting `chrome-browser-polyfill.js` twice (this is the scripts which defines `browser` in Chrome). Maybe, it will make things clearer.

**Comment by gildas-lormeau** [comment]
Sorry for the misunderstanding. I edited my message, I did not want to say it was specific to Windows.

FYI, Chrome already broke SingleFileZ in the past, https://bugs.chromium.org/p/chromium/issues/detail?id=1049604.

**Comment by gildas-lormeau** [comment]
This issue should be fixed now. Feel free to reopen the issue if this is not the case.
