### ISSUE TITLE
The file name is some random hash

### ISSUE THREAD

**Issue by gerroon** [gildas-lormeau/SingleFile#784]
Hi

This extension used to save files with the page name. Now it saves with some kind of hash even though I have this set in the template settings `{page-title} ({date-locale} {time-locale}).html` which is the default one.

I am using it on Chromium Ungoogled 92 on Windows.

I just tested it with this random page and it saved with hashed name

https://www.blendernation.com/2021/09/21/tutorial-blender-3-0a-how-to-create-a-flight-path-from-earth-to-the-moon/

Thanks

**Comment by gildas-lormeau** [comment]
This is a [bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=892133) and a [known issue](https://github.com/gildas-lormeau/SingleFile#known-issues). To circumvent it, disable the option `Misc. > save pages in background` in SingleFile.

**Comment by gerroon** [comment]
Thanks for the reply. The work around works.
