### ISSUE TITLE
[Firefox Fennix] Mobile Overflow Save Button

### ISSUE THREAD

**Issue by benyaminl** [gildas-lormeau/SingleFile#786]
**Is your feature request related to a problem? Please describe.**
Quite a problem and feature. I want to save the annotated page but the button is hidden below title bar of Firefox Fennix. Could you add more padding below save button so when we scroll it will show because the padding is overflow the container. 

**Describe the solution you'd like**
Adding padding bottom to save button, so when scroll the tools, we can see the save button

**Describe alternatives you've considered (optional)**
For now the work arround is chane the view to desktop view

**Additional context (optional)**
It's specific to SingleFile HTML save on Firefox Fennix Android (tested in nightly 94.0a1) and it's running flawlessly, just yeah download button is lurking below the title/url bar of fennix. Sad Fennix

Screenshoot

![210926_082033](https://user-images.githubusercontent.com/2817332/134790033-55b52e72-fac1-47eb-81d7-29822711a049.png)

**Comment by gildas-lormeau** [comment]
Thank you for the detailed issue report. I removed the scroll limitation. The fix will be available in the version 1.19.11.
