### ISSUE TITLE
"Format the page for better readability" option breaks internal links

### ISSUE THREAD

**Issue by butyoutried** [gildas-lormeau/SingleFile#787]
Here's some article, for example: https://habr.com/ru/post/465945/

Links in the TOC works only when page was saved without formatting, as is. Otherwise, every link in the table of content is unrecognized by browsers and looks like this: moz-extension://\*/extension/ui/pages/editor.html#anchor\*

Is it possible to fix that? Thank you.

**Comment by gildas-lormeau** [comment]
Thank your for the report. The bug will be fixed in the next version. However, note that unfortunately links won't work in your example because [readability](https://github.com/mozilla/readability) (the library used by SingleFile) removes `id`s from the document.
