### ISSUE TITLE
Could't save pictures on http://epaper.bjnews.com.cn

### ISSUE THREAD

**Issue by ivysrono** [gildas-lormeau/SingleFile#788]
**Describe the bug**

**To Reproduce**
1. Go to http://epaper.bjnews.com.cn/html/2021-09/30/content_809582.htm?div=0
2. Click SingleFile
3. Get page without pictures.

**Expected behavior**

**Screenshots**

**Environment**
 - OS: Win10 Pro
 - Browser: Firefox 92
 - Version: SingleFile 1.19.11

**Additional context**

**Comment by gildas-lormeau** [comment]
I cannot reproduce the issue. I attached the saved page in the zip file below.

[北京冬奥公园开园_头版_新京报电子报 (10_3_2021 9_14_09 PM).zip](https://github.com/gildas-lormeau/SingleFile/files/7274401/_._.10_3_2021.9_14_09.PM.zip)

**Comment by ivysrono** [comment]
Test again, close HTTPS Only Mode totally fix this issue.
I close HTTPS Only Mode temporary for this site so this issue happened.

**Comment by gildas-lormeau** [comment]
How can I "close HTTPS Only Mode"?

**Comment by ivysrono** [comment]
https://support.mozilla.org/en-US/kb/https-only-prefs

I'm not sure why this issue only happens while Turn Off Temporarily, not Turn Off.

**Comment by gildas-lormeau** [comment]
This website does not support HTTPS. This is not a bug in SingleFile.
