### ISSUE TITLE
Could't save all images of https://fitamin.ir/mag/how-to-lose-thigh-fat-and-tone-your-legs/

### ISSUE THREAD

**Issue by Saadi2020** [gildas-lormeau/SingleFile#790]
Hi,
SingleFile couldn't save one of images of: [https://fitamin.ir/mag/how-to-lose-thigh-fat-and-tone-your-legs/](https://fitamin.ir/mag/how-to-lose-thigh-fat-and-tone-your-legs/)
 couldn't save image under: ۵. اسکوات راه رفتنی از پهلو
![Untitled](https://user-images.githubusercontent.com/42292489/135977774-fd4e67fc-0751-4e10-9411-247cc128b1a3.png)

**Environment**
 - OS: Win10 Pro x64
 - Browser: Firefox & Edge
 - Version: Firefox 93, Edge 94

**Comment by gildas-lormeau** [comment]
Thank you very much for the report. I was able to identify and fix the bug causing this issue. It will be fixed in the version 1.19.12 which should be available for download in ~ 24/48 hours.
