### ISSUE TITLE
mathjax not saving in firefox

### ISSUE THREAD

**Issue by mak-bd** [gildas-lormeau/SingleFile#80]
i saved >>https://squircleart.github.io/animation-nodes/procedural-bookshelves-in-animation-nodes.html<< every thing saved but mathjax equations are not saving.

**Comment by gildas-lormeau** [comment]
I'm closing the issue  because I cannot reproduce it. Please re-open it if you can describe me how to reproduce it.

**Comment by KrasnayaPloshchad** [comment]
I suggest try Web ScrapBook instead if you need.

**Comment by gildas-lormeau** [comment]
@KrasnayaPloshchad Could you give me more details about this issue? I do not understand it...

**Comment by KrasnayaPloshchad** [comment]
Oh, I just found another extension that can be used to save a page, but uses another method, this extension can be available here:
https://addons.mozilla.org/en-US/firefox/addon/web-scrapbook/

**Comment by gildas-lormeau** [comment]
Okay, but how does it help to fix this issue?
