### ISSUE TITLE
Most images are not displaying in SingleFile copy of web page

### ISSUE THREAD

**Issue by russellyoung** [gildas-lormeau/SingleFile#804]
**Describe the bug**
There are 2 problems I see. One is that none of the images display. They are not being fetched, instead there are some gifs that are fetched and included inline, but even they do not show - they are set to "display: none" (I think they may be filler background while waiting for the actual photos to be received) (I decoded the inline images, and they are the background gif images, not the jpg images which should be displayed)

The second is that the text is cut off in the middle. I have tested this several times and it always ends in the same place, at the characters "...桥铁匠营，租" I believe it is connected to a problem in the web page loading, probably with the style sheets (see image 1)

I have followed your directions on unexpected problems: disabled all extensions (besides SingleFile), restart browser, run in incognito.

**To Reproduce**
    Go to https://blog.sina.cn/dpool/blog/s/blog_3baaeae90102x5dk.html
    Save page with SingleFile, open copy in browser
     None of the images are showing up, and the text is truncated. CSS styles are being displayed in the copy which are not showing up (because of errors) in the original
**Expected behavior**
I would expect the page to display just as the original page does, or at least to have the 6 images included in the display.
**Screenshots**
Screenshots of the original page and the results are included

**Environment**
 - OS: [e.g. Win10 Pro, Ubuntu 18.04.1, Android 7.1.2]
MacOS 10.14.6

 - Browser: [e.g. Chrome, Firefox]
   Chrome Version 95.0.4638.40 (Official Build) beta (x86_64)
   Brave Version 1.29.79 Chromium: 93.0.4577.63 (Official Build) (x86_64)
   Safari Version 14.1.2 (14611.3.10.1.7)

**Additional context**
The page has problems, as shown in the image below, but it seems to me it should fail more gracefully. 

Image 1: errors loading file
![image](https://user-images.githubusercontent.com/6629632/138070362-e7eae357-a0b6-4999-9b0c-9a18079ba6de.png)

image 2: web page
![image](https://user-images.githubusercontent.com/6629632/138071008-cdc60e7b-140e-452b-acab-4218d982aba2.png)

Image 3: SingleFile saved version
![image](https://user-images.githubusercontent.com/6629632/138070779-1d5d1828-48ef-443b-93c1-fdf2bd77c6fd.png)

**Comment by gildas-lormeau** [comment]
I tried to solve the problem and unfortunately, I'm afraid it's not possible to do so. This website implements a security policy that blocks SingleFile when it tries to download an image. For example, it's impossible to display one of them like http://s9.sinaimg.cn/bmiddle/0015KkEFzy76E2rwYUE18&690 in a tab.
However, I'll add the option because it might be useful. On this website, the option would make sure the CSS is not embedded in the saved page.

**Comment by gildas-lormeau** [comment]
I uploaded on the stores the version 1.19.18 with the new option "HTML content > block mixed content".
