### ISSUE TITLE
SingleFile Not Saving All Twitter/Youtube

### ISSUE THREAD

**Issue by Baofeika** [gildas-lormeau/SingleFile#807]
**Describe the bug**
Hello! I love SingeFile. Thank you for your work.
For some reason, I am having trouble saving pages that contain many Twitter/Youtube posts. This bug report is quite similar to what noto10 described in #765. 

**To Reproduce**
For example, this link.
https://www.thedrive.com/the-war-zone/42029/rc-135w-rivet-joint-spy-plane-is-flying-orbits-over-kabul

As you can see, it contains many Twitter links. I would scroll all the way down, literally expand each comment, then save using SingleFile. 

However, the saved SingleFile .html file would save the only first 5/6 Twitter/YouTube posts, then the rest would be "empty." The links, photos, etc. still take up space, but it's "empty." As in, if I open the .html file, then "Select All," I can see the image/video border, but no image/video is present.

Weirdly enough, if I try saving using SingleFile (without refreshing) a second time, ALL images/videos become empty. I can make sure of this because the resultant .html file size is noticeably smaller. I have tested this many, many times, using different settings. With VPN, without VPN, etc. Tried changing settings around, to no avail. 

**Expected behavior**
I expected all media files to be downloaded. 

**Screenshots**
<img width="1920" alt="Screen Shot 2021-10-31 at 8 54 14 PM" src="https://user-images.githubusercontent.com/59059386/139584364-fd9ca4f7-e0f3-4030-839f-5462c1d009b2.png">

**Environment**
 - OS: MacBook Pro (15-inch, 2018)
 - Browser: Vivaldi
 - Version: 4.3.2439.63

**Additional context**

**Comment by gildas-lormeau** [comment]
Thank you for the issue report. I was able to reproduce and fix the issue when you save the page the first time. This was due to timeouts used to prevent SingleFile from being blocked that were too low. I increased them significantly in the version 1.19.17 I just published on the Google Chrome store. I am also able to reproduce the second issue you described, I will try to debug it soon.

**Comment by Baofeika** [comment]
Wow, thank you for the fast response! It works now!!!
