### ISSUE TITLE
Plugin hangs

### ISSUE THREAD

**Issue by jimccann-rh** [gildas-lormeau/SingleFile#808]
**Describe the bug**
When trying to save site stops on step 1 of 3

**To Reproduce**
1. Go to 'https://cloud.ibm.com/docs/vpc?topic=vpc-bare-metal-servers-network#mapping-network-concepts'
2. Click on 'save page with singelfile'

**Expected behavior**
So save the web site to a file.

**Screenshots**
![image](https://user-images.githubusercontent.com/92321292/141021294-d374cc42-8510-42a9-802a-5e4ced37d8d3.png)

**Environment**
 - OS: [Fedora 35]
 - Browser: [Firefox]
 - Version: [94.0 64bit]

**Additional context**

**Comment by gildas-lormeau** [comment]
Thank you for the detailed info, I was able to reproduce and fix the issue. The version 1.19.21 will contain the fix. You might have to wait a little bit though because of a minor issue with the review team at Mozilla.

**Comment by gildas-lormeau** [comment]
The new version is now available for download in Firefox.
