### ISSUE TITLE
Set Firefox profile for selenium when using CLI

### ISSUE THREAD

**Issue by scruel** [gildas-lormeau/SingleFile#809]
**Is your feature request related to a problem? Please describe.**
Could not pass the profile arguments to Firefox, it still uses the default profile.
single-file https://www.wikipedia.org "wikipedia.html" --back-end=webdriver-gecko --browser-headless=false --browser-args "[\"-P C:\\Users\\scruel\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\test.default-release\"]"

**Describe the solution you'd like**
I have tried https://github.com/gildas-lormeau/SingleFile/issues/599 mentioned way to add arguments, but it still not run with profile's extensions.

**Comment by gildas-lormeau** [comment]
You must escape quotes and backslashes in the arguments string, and also separate `-P` and its value:
```
single-file 
  https://www.wikipedia.org 
  wikipedia.html 
  --back-end=webdriver-gecko 
  --browser-headless=false 
  --browser-args "[\"-P\",\"C:\\Users\\scruel\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\test.default-release\"]"
```
