### ISSUE TITLE
How to limit the max length of filename when using CLI 

### ISSUE THREAD

**Issue by scruel** [gildas-lormeau/SingleFile#810]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Provide an argument to set the max length of filename.

--------
By the way, will template accepts such format to define common property of the final filename?
{page-title:100} -> page-title max length is 100.
Or
{page-title:{max-len: 100}}

THX.

**Comment by gildas-lormeau** [comment]
Using `--filename-max-length` should work actually.

**Comment by scruel** [comment]
> 
> 
> Using `--filename-max-length` should work actually.
Tried the command:
`single-file  https://www.baidu.com --back-end=webdriver-gecko  --browser-headless=false --filename-max-length=5`
Not work as excepted, it not an option from --help command.

And sometimes I will get the error:
```
TypeError: window.singlefile is undefined URL: https://www.baidu.com
Stack: undefined
```

`single-file  https://www.baidu.com --back-end=webdriver-gecko  --browser-headless=false`
-> Got `百度一下，你就知道 (2021-11-14 上午11_22_12).html` 
`single-file  https://www.baidu.com --back-end=webdriver-gecko  --browser-headless=false --filename-max-length=5`
-> Got `….html`

**Comment by scruel** [comment]
> 
> 
> **Is your feature request related to a problem? Please describe.** Nope.
> 
> **Describe the solution you'd like** Provide an argument to set the max length of filename.
> 
> By the way, will template accepts such format to define common property of the final filename? {page-title:100} -> page-title max length is 100. Or {page-title:{max-len: 100}}
> 
> THX.

https://github.com/gildas-lormeau/SingleFile/issues/814
I've created an issue for 'By the way' part.
