### ISSUE TITLE
Provide url digest hash argument in the filename template

### ISSUE THREAD

**Issue by scruel** [gildas-lormeau/SingleFile#812]
**Describe the solution you'd like**
Implement digest hash for URL as an argument in the template, and I think SHA-1 hash algorithm would be enough, consider the max length of filename is limited.

{url-digest-sha-1}

**Comment by gildas-lormeau** [comment]
I agree SHA-1 is useful to generate "short" filenames, I merged your PR.

**Comment by scruel** [comment]
> 
> 
> I agree SHA-1 is useful to generate "short" filenames, I merged your PR.

Hah, I'd prefer use MD5 for this situation, because it is shorter.

**Comment by gildas-lormeau** [comment]
You're right, but there's no native API in the browser to compute MD5 hashes AFAIK.

**Comment by scruel** [comment]
> 
> 
> You're right, but there's no native API in the browser to compute MD5 hashes AFAIK.

Yep, I know, and SHA-1 should be enough.
