### ISSUE TITLE
Set max length of each argument separately in filename template

### ISSUE THREAD

**Issue by scruel** [gildas-lormeau/SingleFile#814]
**Is your feature request related to a problem? Please describe.**
For now, if the filename is exceeded the maximum length of filename on Windows,  the file will sometimes lose ".html" extension in filename when saving it, the global filename length property is not enough, because it may lose the important information which I want to keep in filename.
For example, if I set `{page-title} - {digest-sha-256}.html`, if the length of page title exceeded the limitation, the digest info will be truncated, the ".html" part will also not be included in the filename.

**Describe the solution you'd like**
An option which can specify the maximum length of each argument if it should be limited(e.g. page-title).

If the maximum length of page-title is 100, the syntax may:
`{page-title-\<max-length\>}`

**Comment by gildas-lormeau** [comment]
> For example, if I set `{page-title} - {digest-sha-256}.html`, if the length of page title exceeded the limitation, the digest info will be truncated, the ".html" part will also not be included in the filename.

Are you sure, I just did the test and the extension , i.e. `.html`, is not removed from the filename.

**Comment by scruel** [comment]
> 
> 
> > For example, if I set `{page-title} - {digest-sha-256}.html`, if the length of page title exceeded the limitation, the digest info will be truncated, the ".html" part will also not be included in the filename.
> 
> Are you sure? I just did the test and the extension , i.e. `.html`, is not removed from the filename.
> 
> Edit: I did the test in the extension. I'll do another test with the CLI. The CLI should behave the same, otherwise I need to fix this.

Yep, I am sure, but it hadn't happened when working with cli, but browser plugin(), sometimes the ".html" part will lose.

**Comment by gildas-lormeau** [comment]
For the record, I confirm I cannot reproduce the issue when using the CLI. The command below produces a filename with `.html` preserved.
```
single-file https://www.example.com  --filename-max-length=32 --filename-template="{page-title} - {digest-sha-256}.html"
```

**Comment by scruel** [comment]
> 
> 
> For the record, I confirm I cannot reproduce the issue when using the CLI. The command below produces a filename with `.html` preserved.
> 
> ```
> single-file https://www.example.com  --filename-max-length=32 --filename-template="{page-title} - {digest-sha-256}.html"
> ```

Ok, and I think you may design the UI like this:
![image](https://user-images.githubusercontent.com/16933298/141780200-2ec3eda2-4510-4573-9867-6e30c4bc1116.png)
It would not need to change the code logic of parsing the template variables but provide a way to set the properties of variables.

**Comment by gildas-lormeau** [comment]
Well, it would be a substantial amount of work :p. I think I would maybe prefer to implement a new syntax in the template language, e.g. `{page-title|max-length(200)}`. It would also allow to introduce other functions like `{page-title|lower-case()}`.

**Comment by gildas-lormeau** [comment]
Hmmm, this feature already exists actually. It's even documented in the help page... I totally forgot about it. Use `[` and `]`, e.g. `{page-title}[200]`

**Comment by scruel** [comment]
> 
> 
> Hmmm, this feature already exists actually. It's even already documented in the help page! I totally forgot about it... Use `[` and `]`, e.g. `{page-title}[200]`

I haven't noticed about the section ‘Template variables’ in the help page, it should be work as excepted, thanks!

**Comment by scruel** [comment]
@gildas-lormeau  I think this issue need to reopen, because its behavior is not work as we excepted.
I set the filename template as `{page-title}[120] - {url-href-digest-sha-1}.html`
For saving the web page: http://www.jasongj.com/java/multi_thread/
The filename just lost the `{url-href-digest-sha-1}` part when saving it.

The filename for saving is:
`Java多线程 sleep wait synchronized 锁 await signal 信号量 Semaphore _ 技术世界 _ java,Java,sleep wait,synchro - .html`

**Comment by gildas-lormeau** [comment]
@scruel The issue you're seeing is not related to this bug. The problem is that the SHA-1 cannot be computed on http pages, it only works with https pages unfortunately.

**Comment by scruel** [comment]
> @scruel The issue you're seeing is not related to this bug. The problem is that the SHA-1 cannot be computed on http pages, it only works with https pages unfortunately.

Got it, so could it be fixed? Should I post a new issue for this?
