### ISSUE TITLE
Call SingleFile from the JS console

### ISSUE THREAD

**Issue by DesWurstes** [gildas-lormeau/SingleFile#820]
**Is your feature request related to a problem? Please describe.**
I want to run SingleFile on multiple pages, from the console, preferably calling it via Selenium IDE. This is because the CLI is suboptimal for downloading many pages since it lacks asset caching (unsurprisingly) so I need to use the browser extension.

**Describe the solution you'd like**
Add an option to register an API on the `window` object on every webpage (like Ethereum Web3). Then I'll be able to call SingleFile from the console and from Selenium.

**Describe alternatives you've considered (optional)**
Add CLI option to download multiple pages. Bad, because browsers allow me to disable images and scripts, etc. and adding all these to CLI would be overkill.

**Additional context (optional)**

**Comment by gildas-lormeau** [comment]
You can achieve this by:
1. Injecting `/dist/single-file.js` in the page, it will create a global variable named `singlefile`
2. Running for example the following code (all the options are set to `false` by default)
```js
const { content, title, filename } = await singlefile.getPageData({
  removeImports: true,
  removeScripts: true,
  removeAudioSrc: true,
  removeVideoSrc: true  
});
```

The variable `content` will contain the HTML content of the page. Note however that you will have to implement the code to save the page on the filesystem.

**Comment by DesWurstes** [comment]
I get "ReferenceError: singlefile is not defined", `/dist/single-file.js` doesn't seem to register anything on "window".

**Comment by gildas-lormeau** [comment]
There must be something wrong on your side. If I open https://www.example.com in a browser, paste the content of `/dist/single-file.js` and execute it in the console, then I can call `singlefile.getPageData`.

**Comment by DesWurstes** [comment]
Works for me now! Thanks

**Comment by anilabhadatta** [comment]
@gildas-lormeau Hi, I am implemented your code in my script but I am facing an error "Script Timeout". I am getting the content from selenium's driver.execute_script() and I think the content isn't returned for some reason.
Can you tell me what the possible cause for this kind of error is?

**Comment by gildas-lormeau** [comment]
@anilabhadatta I would need more information about what you did to help you.

**Comment by anilabhadatta** [comment]
@gildas-lormeau In my script in am executing the JS command using selenium's driver.execute_script() and returning the page content after single file has finished processing.

![Screenshot_2022-07-25-18-16-22-492_com android chrome](https://user-images.githubusercontent.com/48487849/180780905-6ad2545d-c5f8-43f6-a33b-5bf3a5cba0b5.jpg)

This process is basically executed multiple times for various web pages and sometimes i am getting script execution timed out 
As far as i think single file is failing to get the page content and for that i guess the timeout occurs after sometime.

**Comment by anilabhadatta** [comment]
@gildas-lormeau It works most of the time. 
Only happens after scraping for a long time.
I saw in your wiki where you stated that there may be cors issue and i have to create and object etc but i don't know how to implement it.
I don't know maybe single file isn't working due to cors but i can say that the same webpage where the error occured, single file will get the page content if i restart the script again.

**Comment by anilabhadatta** [comment]
@gildas-lormeau I think I will face issues with other parts of code in Puppeteer or Playwright.

**Comment by gildas-lormeau** [comment]
@anilabhadatta Could you provide me an example of URL where you're facing this issue?

**Comment by anilabhadatta** [comment]
@gildas-lormeau 
I will ask the user who faced the issue.
You may need a subscription for this, I can send the creds to your email and once I receive the URL I will post it here.
But I think if I re-run the driver_execute command then it should get the content next time because restarting my script does get the page content of that specific url.

**Comment by anilabhadatta** [comment]
@gildas-lormeau 
![image](https://user-images.githubusercontent.com/48487849/180838348-d37a7a31-e09b-4870-a29d-ed2292534b1d.png)

I think this is what is happening, infinite stuck .

**Comment by gildas-lormeau** [comment]
I was not able to reproduce the issue. However, I guess you're facing this issue: https://github.com/gildas-lormeau/SingleFile/issues/935. You can set the option `networkTimeout` to reduce this delay.

**Comment by anilabhadatta** [comment]
@gildas-lormeau can you tell me what does network timeout actually do if i set it to 60000?

**Comment by gildas-lormeau** [comment]
@anilabhadatta  SingleFile will cancel network requests that did not return a complete response within that delay.

**Comment by anilabhadatta** [comment]
![image](https://user-images.githubusercontent.com/48487849/180950590-2afc6f98-7ab0-41ac-b399-fd00802f8c42.png)
@gildas-lormeau I will test it and will report to you if this has fixed the issue. Tested in leetcode manually using console, received the content.

**Comment by 3biubiu** [comment]
> You can achieve this by:您可以通过以下方式实现这一目标：
> 
> 1. Injecting `/dist/single-file.js` in the page, it will create a global variable named `singlefile`在页面中注入 `/dist/single-file.js` ，会创建一个名为 `singlefile` 的全局变量
> 2. Running for example the following code (all the options are set to `false` by default)例如运行以下代码（所有选项默认设置为 `false` ）
> 
> ```js
> const { content, title, filename } = await singlefile.getPageData({
>   removeImports: true,
>   removeScripts: true,
>   removeAudioSrc: true,
>   removeVideoSrc: true  
> });
> ```
> 
> The variable `content` will contain the HTML content of the page. Note however that you will have to implement the code to save the page on the filesystem.变量 `content` 将包含页面的 HTML 内容。但请注意，您必须实现代码才能将页面保存在文件系统上。
Where to get more configuration?

**Comment by anilabhadatta** [comment]
@3biubiu https://github.com/gildas-lormeau/SingleFile/wiki/How-to-integrate-SingleFile-library-code-in-%22custom%22-environments%3F
