### ISSUE TITLE
Add set default path support for saving to filesystem

### ISSUE THREAD

**Issue by scruel** [gildas-lormeau/SingleFile#823]
**Describe the solution you'd like**
Able to specify the default path for saving the pages.

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion, I agree with you. Note that you should be able to achieve this with the filename template but I can understand that it is not very practical.

**Comment by gildas-lormeau** [comment]
Again, I forgot this option already exists... The option `--output-directory` should do the job.

**Comment by scruel** [comment]
> 
> 
> Again, I forgot this option already exists... The option `--output-directory` should do the job. Regarding the extension, they cannot save pages outside the download folder.

OK, but this option is only for CLI now, but not for the browser plugin when saving in file system.
For browser plugin, I can only select one destination for saving pages now.
But sometimes I want to save to multiple destinations for backup reason(with an option "no need to show the 'save as' dialog"), so may change the radio to checkbox for destinations will be better.

**Comment by gildas-lormeau** [comment]
Extensions cannot write files outside the Downloads folder. However you can use the filename template to save pages into sub-folders. Note also that you could use profiles to define different sub-folders. For example, you could create a profile named "backup" with a filename template beginning with `backup/`.

**Comment by mjrawesome** [comment]
> For example, you could create a profile named "backup" with a filename template beginning with `backup/`.

Unfortunately, this doesn't work for me. I navigated to "Extension options" -> "File name" -> "template" and changed the default settings to "backup/{day-locale}.{month-locale}.{year-locale}.html". The slash is replaced by an underscore and it is still saved into the same, main Downloads folder.

<details>
<summary>system info</summary>

Windows 7 (64x)
Chrome v96.0.4664.110
SingleFile Extension v1.19.24
</details>

**Comment by gildas-lormeau** [comment]
Please make sure `Misc. > save pages in background` is enabled.

**Comment by mjrawesome** [comment]
> Please make sure `Misc. > save pages in background` is enabled.

Thanks for an ultra fast reply. I enabled the setting in Misc, but the file is still saved into the same directory. Except now the file name doesn't seem to follow the template at all (e.g. "786f1993-b013-45d8-a618-8476dbead036" instead of "{year-locale}.html")

**Comment by gildas-lormeau** [comment]
This is unfortunately a bug in Chrome, see https://bugs.chromium.org/p/chromium/issues/detail?id=892133. Using a separate/new profile might help. There is nothing I can do to fix it on my end. Note that this bug is specific to Chomium-based browsers.

**Comment by mjrawesome** [comment]
@gildas-lormeau 
This is very unfortunate and it will likely affect other Chromium-based browsers, like Opera (confirmed by me), Edge (not tested), Samsung Internet Browser (not tested), which only leaves Safari and Firefox of the popular ones.

I don't have the same problem with either "DownloadThemAll" or "Simple mass downloader", both of which seem to save into subdirectories just fine. Perhaps a similar solution could be implemented here.

At any rate, thank you for creating and maintaining this otherwise excellent extension.

**Comment by gildas-lormeau** [comment]
Actually "DownloadThemAll" or "Simple mass downloader" might be probably the cause of this bug. I know that there is more chances to see it when download managers are installed.

**Comment by maliayas** [comment]
You can create a symlink in your download folder to the actual target folder. Job done!

Example template: `name-of-the-symlink/{page-title}.zip.html`

**Comment by kupietools** [comment]
> Again, I forgot this option already exists... The option `--output-directory` should do the job. Regarding the extension, they cannot save pages outside the download folder.

Wait, what? I've been saving outside the download folder for ages, it asks me where it wants to save. There reason I'm here looking for help is because today it suddenly stopped asking me and started always automatically saving to the download folder. But that never happened before today, I've never saved to the Download folder before.

**Comment by GithubUser99999999** [comment]
This is terrible. It's just not plausible that there is no option to select a folder selection when saving a page. So annoying...

**Comment by gildas-lormeau** [comment]
@GithubUser99999999 This issue can easily be circumvented with Single File Lite Companion, see https://github.com/gildas-lormeau/single-file-companion-lite

**Comment by haomuch** [comment]
> You can create a symlink in your download folder to the actual target folder. Job done!
> 
> Example template: `name-of-the-symlink/{page-title}.zip.html`

That works great! I have been looking for such method to sync with OneDrive folder for a long time! Thanks very much for providing this solution!

**Comment by acahir** [comment]
I tried setting the name to a subdirectory inside Downloads folder, but no luck. Just adds sub-directory name followed by underscore to output file. 

The Misc -> save pages in background option isn't even displaying, though I can see the setting in the raw config file. Changing it to true caused an error when trying to save the page.

This was all in Safari v18.6. Will keep playing around to see if I can find a solution that works

**Comment by gildas-lormeau** [comment]
@acahir Unfortunately, I confirm that Safari does not saving pages into sub-folders. The only option is to run a WebDAV server on your machine and save pages via this server. It's integrated in macOS and quite easy to use, see this example: https://gist.github.com/namuan/484fc4557dcced73d77044423695cac5. Then, you just need to update in the options of SingleFile the "Destination" with the info of your WebDAV server.
