### ISSUE TITLE
Save webpage that only loads when scrolling down or up

### ISSUE THREAD

**Issue by ftlx** [gildas-lormeau/SingleFile#824]
Hi. Thanks for a great extention.

Im trying to save a webpage which is not fully loaded when entering the webpage. The page loads only when scrolling down or up. When I save it will thus only save the part os site which has been loaded (visible).

I have tried several ways, and also checked the settings, your guide and all issues here, but cant find any solution. Is the feature or issue Im describing possible?

Thanx

**Comment by gildas-lormeau** [comment]
If you didn't do it, enable `Images > save deferred images > zoom out the page`, scroll down to the bottom of the page and save the page. If it does not work, you can rest the options and try to zoom out the page as much as you can, e.g with Ctrl + mouse wheel, before saving it.

**Comment by ftlx** [comment]
Hi Gildas

Thanks for quick respons. I tried with these but enabled, but didnt work out.

I also tried a full zoom out, but page can not be full zoomed out. in firefox max zoom out is 30% and in chrome it is 25%.

**Comment by gildas-lormeau** [comment]
I think you could use a tool to resize the window height to the desired value (e.g. the height of the page), there are some suggestions here: https://superuser.com/questions/18215/is-there-a-way-to-resize-a-window-to-specific-sizes-eg-800x600-1024x768

**Comment by ftlx** [comment]
Hi

I tried with the sizer, but didnt work out.
I also tried with extention on chrome ZOOM which is able to zoom page to only 1 %, but even with 1 % the full page is not displayed,,,, i dont think what im trying will be possible.

Thanks for you help anyway :-)

**Comment by gildas-lormeau** [comment]
This might work by using SingleFile from the command line interface. I think this would allow you to define a large value for the window height because Chrome is run in headless mode.

**Comment by ftlx** [comment]
Sorry I didnt catch you. How can I do this. Please advise. I open chrome from cmd. But from there i dont know.

**Comment by gildas-lormeau** [comment]
In fact, you can run SingleFile from the command line interface directly, see https://github.com/gildas-lormeau/SingleFile/tree/master/cli. The option to set the height of the browser is `--browser-height`

**Comment by ftlx** [comment]
Hi Gildas

Thanks for message.
Im not that good in cmd sorry and lost in the commands :-)

**Comment by ftlx** [comment]
Great news

I am able to have it save the full page in the browser (firefox) as desired. 
I increased the max. the idle time to 2000 ms and unchecked the zoom out page.

So it looks to work very fine for the moment.

Thanks for help and a great extension :-)

**Comment by gildas-lormeau** [comment]
Great! I'm really glad to hear it :-). So I'm closing the report. Feel free to re-open it or comment on it if you wish.
