### ISSUE TITLE
Not saving pages from substack.com properly

### ISSUE THREAD

**Issue by noto10** [gildas-lormeau/SingleFile#825]
For some reason, pages from substack.com are not saved properly. 

Take for example the page at [https://maxread.substack.com/p/the-most-influential-man-on-the-internet](https://maxread.substack.com/p/the-most-influential-man-on-the-internet)

Singlefile saves the page as follows:

![sub002](https://user-images.githubusercontent.com/13828004/142488290-5dacd5b6-529b-4692-9955-265efbdafe1a.jpg)

**Comment by gildas-lormeau** [comment]
I cannot reproduce the issue, see the saved page in the attached zip file. Did you change any setting?

[The most influential man on the internet - by Max Read - Read Max (11_18_2021 10_12_48 PM).zip](https://github.com/gildas-lormeau/SingleFile/files/7566025/The.most.influential.man.on.the.internet.-.by.Max.Read.-.Read.Max.11_18_2021.10_12_48.PM.zip)

**Comment by noto10** [comment]
> I cannot reproduce the issue, see the saved page in the attached zip file. Did you change any setting?
> 
> [The most influential man on the internet - by Max Read - Read Max (11_18_2021 10_12_48 PM).zip](https://github.com/gildas-lormeau/SingleFile/files/7566025/The.most.influential.man.on.the.internet.-.by.Max.Read.-.Read.Max.11_18_2021.10_12_48.PM.zip)

Your saved file renders fine here. However mine does not. Please take a look at my saved page in the attached zip. I have changed a few settings but it's been so long that I may not be able to recall all the changes.

[The most influential man on the internet - by Max Read - Read Max (2021-11-21 1_14_15 AM).zip](https://github.com/gildas-lormeau/SingleFile/files/7576718/The.most.influential.man.on.the.internet.-.by.Max.Read.-.Read.Max.2021-11-21.1_14_15.AM.zip)

**Comment by gildas-lormeau** [comment]
Please enable the option `Other resources > remove scripts`.
