### ISSUE TITLE
Auto save not following the settings auto save rules url's

### ISSUE THREAD

**Issue by javll** [gildas-lormeau/SingleFile#827]
Auto save not following the settings auto save rules url's. Its saving every page the tab loads not filtering the url rules defined.

**Comment by gildas-lormeau** [comment]
You have to add the rule below in order to disable the auto-save by default on all domains. Make sure `display 'Auto-save profile' column` is ticked.
`URL:*, Profile: Default settings, Auto-save profile: Disabled`
