### ISSUE TITLE
it does not download <g> of html

### ISSUE THREAD

**Issue by wangxiaolei21** [gildas-lormeau/SingleFile#829]
there is a url:
https://mp.weixin.qq.com/s/gGOqopXOa8XUyvMSN312xA
in the web, all things in the page will be saved as a singlefile **without expressions.**
I am expecting your coming.

**Comment by gildas-lormeau** [comment]
I'm not able to reproduce any issue related to the images on this page, cf. the file in the attached zip file. I did this test with the default settings in Chrome and Firefox.

[正则化方法小结 (11_25_2021 2_33_28 PM).zip](https://github.com/gildas-lormeau/SingleFile/files/7603309/11_25_2021.2_33_28.PM.zip)
.

**Comment by wangxiaolei21** [comment]
I am very sorry .
what i description is wrong_
I encount a problem, which is not caused by your great tool.
please pardon me ... good night.

**Comment by gildas-lormeau** [comment]
Don't worry, I pardon you ;)
