### ISSUE TITLE
How Can I help to the development ?

### ISSUE THREAD

**Issue by musabgultekin** [gildas-lormeau/SingleFile#833]
These are my steps:

Clone the repo
Install npm packages
Make necessary changes
Ran build-extension.sh file.
Enable developer mode in chrome://extensions page.
Then drag and drop exported extension zip file to the chrome extensions page.

But I'm not sure exactly. Can you let me know which steps to take.

I'm using  MacOS Monterey (12.0.1), with Google Chrome 96.0.4664.55

**Comment by gildas-lormeau** [comment]
You don't need to generate the zip file actually. Just run `npx rollup -c rollup.config.dev.js` to build the code for debugging purposes, and install the extension in the developer mode from the folder where you cloned the project.

**Comment by musabgultekin** [comment]
Thank you!

**Comment by gildas-lormeau** [comment]
You're welcome :)

**Comment by theowenyoung** [comment]
@gildas-lormeau Hi, I tried to run `npm run dev`, and it works, but how can I run it in a watch mode?

should I run this command `npm run dev` every time when I make some changes?

**Comment by gildas-lormeau** [comment]
@theowenyoung You have to run the command **and** refresh the extension in Chrome. That's why I run it manually on my end.
