### ISSUE TITLE
Not saving correct filename

### ISSUE THREAD

**Issue by NOSEBAG** [gildas-lormeau/SingleFile#834]
Hi,
When I save a webpage, I now get names such as,
a3bb67e4-5f56-4024-880a-a20e86c99330

But in settings I have under "Filename" / Template;
{page-title} ({date-locale} {time-locale}).html

This has just been happening over the last few weeks.
this is only happening on my Google Chrome Version 96.0.4664.45 (Official Build) (64-bit)
On Firefox 94.0.2 (64-bit) it is saving fine , and settings are the same
{page-title} ({date-locale} {time-locale}).html

I think there is a bug now on Google Chrome with name saving?
please can you advise

many thanks

**Comment by NOSEBAG** [comment]
![chrome-name-saving-error-example](https://user-images.githubusercontent.com/72623810/144767940-98b80582-6f86-42c8-8ac5-a7e47ef68639.jpg)
Here's an example image of the error I face with SingleFile not saving the webpage names correctly in Google Chrome, but does this fine in Firefox

**Comment by gildas-lormeau** [comment]
This is a [bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=892133) and a [known issue](https://github.com/gildas-lormeau/SingleFile#known-issues). To circumvent it, disable the option `Misc. > save pages in background` in SingleFile.

**Comment by NOSEBAG** [comment]
Hi Gildas!
Excellent,
Many thanks for this solution,,

I've been suffering for weeks with this,, now at least there is a known workaround

Many thanks again!
Cheers

**Comment by gildas-lormeau** [comment]
you"re welcome!
