### ISSUE TITLE
Manage WebAssembly

### ISSUE THREAD

**Issue by EmilianoCostantini** [gildas-lormeau/SingleFile#835]
If feasible, it would be great to get WebAssembly code along with js, since without WASM some pages simply won't work (try for instance [this URL](https://pteo.paranoiaworks.mobi/) )

Or at least it would be useful to detect the use of WebAssembly and notifiy the user that the downloaded page might not work because of that

**Comment by gildas-lormeau** [comment]
In general, support for embedded JavaScript files is not good in SingleFile as it is a very difficult or impossible problem to solve. In the example you provided, the wasm script is loaded dynamically via a JS script. Unfortunately, SingleFile cannot detect and save dynamic scripts. The best solution for this type of use case is to save the page as a WARC or Web Bundle file (there is no implementation yet).

**Comment by EmilianoCostantini** [comment]
Got it. Too bad, but thank you very much for the explanation, and kudos for the excellent work you guys are doing!

**Comment by gildas-lormeau** [comment]
You're welcome :)
