### ISSUE TITLE
Hidden element appears again on saved Page

### ISSUE THREAD

**Issue by waleed-wwn** [gildas-lormeau/SingleFile#840]
I am using "SingleFile addon in Firefox and selected `"Remove hidden elements"` on HTML content.
I also use "uBlock Origin".

**Problem**: 
element successfully hidden in real view { Before Saved }, But after save page by using "SingleFile" the hidden element appears again on saved Page.

**To Reproduce**
on this page https://excelmacromastery.com/vba-listbox/
I added below filter on uBlock to remove an element:
`! 2021-12-14 https://excelmacromastery.com ` 
`||excelmacromastery.com/wp-content/themes/flat/assets/img/default-background.jpg`

**Expected behavior**
 the hidden element should not appears again on saved Page

**Screenshots**
![1](https://user-images.githubusercontent.com/96181055/146181025-9dd070b6-c4f4-4995-9e6b-8a4a4cf9cd90.png)
![2](https://user-images.githubusercontent.com/96181055/146181057-e2a8b375-5a53-4a26-85f2-ec5ddda57c6b.png)
![3](https://user-images.githubusercontent.com/96181055/146181068-0921d366-c10a-48c8-9855-efabb34b8052.png)

**Environment**
 - OS: Windows 11 Pro 21H2
 - Browser: Firefox 95
 - SingleFile 1.19.22

**Comment by gildas-lormeau** [comment]
Thank you. The CSS rules added by uBlock Origin cannot be directly seen by other extensions. Actually, SingleFile detects hidden elements by testing the size of the element. That's why it cannot detect the background image is not displayed. I'll try to see if I can improve the implementation to detect hidden background images.

**Comment by invobzvr** [comment]
The uBlock Origin should block the image request, so how was that resource being loaded? caches?

> Thank you. The CSS rules added by uBlock Origin cannot be directly seen by other extensions. Actually, SingleFile detects hidden elements by testing the size of the element. That's why it cannot detect the background image is not displayed. I'll try to see if I can improve the implementation to detect hidden background images.

What about using `getComputedStyle(el).display` to detect hidden element, though this may cost much...

**Comment by gildas-lormeau** [comment]
That's already what SingleFile is doing. It's also checking the size of the element. However, this technique does not always work with blocked background images because the container element is not necessarily hidden.
