### ISSUE TITLE
Move all styles to the top of <head>

### ISSUE THREAD

**Issue by ImportTaste** [gildas-lormeau/SingleFile#841]
When I save pages with SingleFile that had a dark themed applied with Stylus, I get "flashbanged" while the page is loading, since Stylus places its styles at the bottom of the page to make sure they take priority.

In other words, because of all the Base64 strings, styles that are at the bottom of the HTML file aren't loaded right away, causing the "flashbang" to occur.

What would fix this is if all the styles were placed right at the top of <head>, before any Base64 strings even occur.

And honestly, dark themes aside, it would just make the page loading look a lot smoother.

**Comment by gildas-lormeau** [comment]
I agree that could be useful. However, it could also break the page in some rare cases. For example, a learning website could have as CSS  `body style { display: block; }` in order to display/edit (with the `contenteditable` attribute) CSS examples and apply them on the page immediately. 
I might add an option for this though. Meanwhile, note that you could achieve this with a userscript executed before the page is saved, see https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved.

**Comment by ImportTaste** [comment]
> I agree that it could be useful. However, it could also break the page in some rare cases. For example, a learning website could have as CSS `body style { display: block; }` in order to display/edit (with the `contenteditable` attribute) CSS examples and apply them on the page immediately. I might add an option for this though. Meanwhile, note that you could achieve this with a userscript executed before the page is saved, see https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved.
> 
> For example, this script should do the job:
> 
> ```js
> document.querySelectorAll("body style").forEach(style => document.head.appendChild(style));
> ```

That's an interesting solution. How would I do that with the browser extension though? I don't think it's even doable through SingleFile Companion. I mean, I can just use the CLI version, it's just nowhere near as convenient when I stumble onto something...

I'd use a GreaseMonkey script, but Stylus will continuously enforce its styles at the bottom of the page.

**Comment by gildas-lormeau** [comment]
This script would run only *before* the page is saved (see the doc).

**Comment by gildas-lormeau** [comment]
Here is the complete user-script (not tested):

```js
// ==UserScript==
// @name         Move stylesheets into the HEAD element
// @namespace    https://github.com/gildas-lormeau/SingleFile
// @version      1.0
// @description  [SingleFile] Move stylesheets into the HEAD element
// @author       Gildas Lormeau
// @match        *://*/*
// @noframes
// @grant        none
// ==/UserScript==

dispatchEvent(new CustomEvent("single-file-user-script-init"));

addEventListener("single-file-on-before-capture-request", () => {
  document.querySelectorAll("body style").forEach(style => document.head.appendChild(style));
})();
````

**Comment by ImportTaste** [comment]
> This script would run (automatically) only _before_ the page is saved (see the doc).

Oh, I see, it's a hidden option. Alright then, thank you.

**Comment by ImportTaste** [comment]
> Here is the complete user-script (not tested):
> 
> ```js
> // ==UserScript==
> // @name         Move stylesheets into the HEAD element
> // @namespace    https://github.com/gildas-lormeau/SingleFile
> // @version      1.0
> // @description  [SingleFile] Move stylesheets into the HEAD element
> // @author       Gildas Lormeau
> // @match        *://*/*
> // @noframes
> // @grant        none
> // ==/UserScript==
> 
> dispatchEvent(new CustomEvent("single-file-user-script-init"));
> 
> addEventListener("single-file-on-before-capture-request", () => {
>   document.querySelectorAll("body style").forEach(style => document.head.appendChild(style));
> }, false);
> ```

Question, does this still work when using SingleFile Companion?

**Comment by gildas-lormeau** [comment]
It should work if you selected SingleFile Companion as the `Destination`.

**Comment by ImportTaste** [comment]
> It should work if you selected SingleFile Companion as the `Destination`.

I'm afraid it didn't work, Stylus still manages to keep its own styles forced to the bottom. Other styles are sent to the top just fine.

**Comment by ImportTaste** [comment]
One possible workaround might be to exclude style tags that start with the ID 'stylus' from the initial foreach check, then do another foreach check where the _contents_ of those tags are <ins>copied</ins> to a new tag that doesn't have a stylus id.

Then, in single-file-on-after-capture-request, remove the style tags with stylus IDs.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback. Here is below a script that should work. The drawback is that the style tag will appear twice in the page because it's impossible to remove the one at the bottom of the page with a user script AFAIK.

```js
// ==UserScript==
// @name         Move stylesheets into the HEAD element
// @namespace    https://github.com/gildas-lormeau/SingleFile
// @version      1.0
// @description  [SingleFile] Move stylesheets into the HEAD element
// @author       Gildas Lormeau
// @match        *://*/*
// @noframes
// @grant        none
// ==/UserScript==

dispatchEvent(new CustomEvent("single-file-user-script-init"));
document.querySelectorAll("style").forEach(style => {
  if (style.id.startsWith("stylus")) {
    style = style.cloneNode(true);
    }
  document.head.appendChild(style);
});
```
