### ISSUE TITLE
Save the origin URL for each embedded image

### ISSUE THREAD

**Issue by abolibibelot1980** [gildas-lormeau/SingleFile#842]
SingleFile should save the origin URL for each embedded image. As of now, the origin URLs do not appear anywhere in the code. This can be useful for future reference.

For instance, I've had situations where I saved a web page, and an embedded image as a separate file, then months or even years later I viewed that image again and wondered if it was (stil)l available in better quality. For instance on 2017/11/18 I saved [this article](http://www.makeuseof.com/tag/can-hard-drive-makes-unusual-noises/) as a MHT file (using at the time the now defunct Mozilla Archive Format extension), and an embedded image named “hdd-noise-670x335.jpg” ; then four years later, on 2021/10/17, I viewed that image again, and wondered if a better quality version could still be retrieved, so I opened the MHT file, found the origin URL to that image, removed the size related suffix and tried to download “hdd-noise.jpg” directly — it worked, with no need to re-load the live article to get the image's URL, and that version of the image has a much better 1680x840 resolution. Using SingleFile, re-loading the live article would be necessary to get the image's origin URL. (If I do re-load the live article today, it turns out that now [this is the image being displayed](https://static1.makeuseofimages.com/wordpress/wp-content/uploads/2015/10/hdd-noise.jpg), with a new link and a different scaling system and a dynamic conversion to WEBP format, while the lower quality JPEG versions have been removed.) It can also happen that the origin article is no longer available, but the embedded images are, in which case a web page saved with SingleFile would not allow to retrieve them at all.

**Comment by gildas-lormeau** [comment]
SingleFile relies on a library that removes comments in CSS. This is why I did not implement this feature. I simply can't add URLs in the stylesheets and I don't want to implement only half of this functionality. However, note that [SingleFileZ](https://github.com/gildas-lormeau/SingleFileZ) can save origin URLs as comments in the zip file and in a `index.json` file located in the root folder of the zip file.

**Comment by gildas-lormeau** [comment]
The new option "HTML Content > save original URLs of embedded resources" in the version 1.19.22+ allows to save the URLs of the original resources as CSS comments/HTML attributes (see the help page for more info).
