### ISSUE TITLE
Translate "template of the infobar content" and "open a prompt dialog to edit the infobar content" labels

### ISSUE THREAD

**Issue by gildas-lormeau** [gildas-lormeau/SingleFile#86]
Hi @yfdyh000, @Shitennouji, @rstp14, @xesarni, @KrasnayaPloshchad 

The [last commit](https://github.com/gildas-lormeau/SingleFile/commit/e2a470caab73823b56b004d12da347bfd89c3bda) introduces 2 additional options allowing the user to customize the infobar content. The new labels in the options page are:
* `optionInfobarTemplate`: "template of the infobar content"
* `optionConfirmInfobar`: "open a prompt dialog to edit the infobar content"

Your help in translating these labels would be welcome :)

**Comment by Shitennouji** [comment]
optionInfobarTemplate: "infobar コンテンツのテンプレート"
    optionConfirmInfobar: "infobar のコンテンツを編集するためのプロンプトダイアログを開く"

**Comment by gildas-lormeau** [comment]
Thanks @Shitennouji  :)
