### ISSUE TITLE
Add the option to save webp images to jpeg/png

### ISSUE THREAD

**Issue by KotBoyun** [gildas-lormeau/SingleFile#860]
**Is your feature request related to a problem? Please describe.**
There is still one browser that does not support webp images - Internet Explorer 11. I save HTML pages in a chrome browser. Then I use Total Commander to quickly view local files. In this case, the Internet Explorer 11 engine is used. On the saved pages of sites that uses webp (for example Aliexpress.com ), images are not shown (only a cross), because the HTML body contains data:image/webp;base64. The rest of the content is correct. It also doesn't work in Windows explorer window view panel (ALT+P).

**Describe the solution you'd like**
Check the box (save webp as jpeg or png). When saving the page, webp files were converted to jpeg/png. And encoded as data:image/jpeg;base64 or png.

**Describe alternatives you've considered (optional)**
Otherwise, I have to open every page in the Chrome browser, then until you find the right one.

**Additional context (optional)**
Thanks for the extension. This is the best there is with such features!

**Comment by gildas-lormeau** [comment]
That's an interesting feature and this could fix https://github.com/gildas-lormeau/SingleFile/issues/866. The drawback is that the time to save the page would be a bit longer because of the conversions.

**Comment by KotBoyun** [comment]
changed *.json (removed image/webp and image/avif), imported settings. It didn't help. The images are still recorded as base 64 webp. Or did I do something wrong?

**Comment by gildas-lormeau** [comment]
No, unfortunately. That's why this issue is still open ;). Here, I have to add some code to do the conversion and fix the issue.

**Comment by KotBoyun** [comment]
Hello. This issue can be closed. There are no programs left that do not work with webp. The solution to my problem was a new plugin for Total Commander (wlx-edge-viewer). Now everything is visible. Thanks for your extension. Solve more important problems.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback! I agree, let's close it and see :)
