### ISSUE TITLE
Option to Specify File Name Max Length in Characters

### ISSUE THREAD

**Issue by arandorion** [gildas-lormeau/SingleFile#862]
SingleFile lets you specify the maximum file name length in bytes. However, the max file name length on my system, macOS APFS, is specified as 255 UTF-8 characters. UTF-8 characters can range from 1 to 4 bytes. That means the file name can be up to 1,020 bytes (4 × 255) but no more than 255 characters.

If I set SingleFile's file name max length to 1,020 bytes but the filename only uses characters requiring 1 byte each, then it will erroneously think the file name can be 1,024 characters long. If I set SingleFile's file name max length to 255 bytes and the file name uses characters requiring more than 1 byte each, then the file name will be cut short of the system's 255 character maximum.

If I could specify the file name max length in characters, that would solve the problem.

Thank you

**Comment by gildas-lormeau** [comment]
Thank you, I was not aware that some FS were using characters for max filename length. I added a select input in the options page allowing you to choose the unit (`bytes` or `characters`). You can also use for example `[10ch]` after a variable name in the template to truncate the value to 10 characters. This feature will be available in the next version.
