### ISSUE TITLE
Save infinite scrolling panes, such as entire discord chat history starting at a specifc message

### ISSUE THREAD

**Issue by webhype** [gildas-lormeau/SingleFile#864]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when Discord (web version) won't scroll the chat back to the exact message that I stopped reading, but instead scrolls down to the latest messages or messages from today. 

This makes Discord unusable for busy channels because I have no idea where I left off reading 2 weeks ago. Need to scroll for a half hour to kinda sorta find the last read message. Other messengers, such as Telegram, simply reopen all chat windows _at the exact spot that the reader left off_.

The problem is well described here and in 6 years or so, Discord hasn't done anything about it: https://support.discord.com/hc/en-us/community/posts/360042591531-Option-to-Disable-Automatic-Scrolling-to-Newest-Message-on-Mobile

**Describe the solution you'd like**
I would like SingleFile to help save an entire Discord chat, ideally from a specific message on, scrolling down page by page, to "today, right now". Each specific message in Discord has a unique URL so finding a suitable starting point from the desktop app is easy (let's say, 01/01/2022). 

Then SingleFile should scroll down, page by page, which makes the Discord webpage load a few messages at a time into the scrollable pane via Ajax. SingleFile should then append these DIVs to the SingleFile output file. The end result will be the entire chat history in the channel, perhaps even neatly embedded in the Discord sidebars.

It is obvious that Discord doesn't want us to do this exact thing, but the user experience with busy channels is so horrible that only a 3rd-party tool can do anything about this.

I can envision other useful uses of "capturing (almost) infinite scrolling" on some divs, for example to capture all articles from a specific Forbes article on (Forbes links them with infinite scrolling IIRC). There are many blogging systems who do this now and saving more than the currently visible pane is a pain. 

An autoscroll feature on (almost) infinite scrolling panes would come in very handy.

**Comment by easrng** [comment]
https://github.com/Tyrrrz/DiscordChatExporter might work better for this

**Comment by falcorr** [comment]
You might also want to check out [ShareX ](https://getsharex.com/)and its scrolling screenshot feature.
