### ISSUE TITLE
Saving page with SingleFile Companion failed

### ISSUE THREAD

**Issue by Dallory** [gildas-lormeau/SingleFile#865]
Hello,
when i use the "Save with SingleFile Companion" setting and save any page I get the error "SingleFile error: browser.runtime.connectNative is not a function".
- Firefix 96.0.3
- Windows 10 Pro Version: 20H2, Build: 19042.1348
- SingleFile 1.19.24

![grafik](https://user-images.githubusercontent.com/37782111/152133536-0d9a55df-56f8-4c9a-8c5c-cbf65274b806.png)
![grafik](https://user-images.githubusercontent.com/37782111/152133883-4487bb86-c918-48cf-a554-93c18e1f726c.png)

Thanks!

**Comment by gildas-lormeau** [comment]
Thank you! I confirm I was able to reproduce the issue and fix it. The fix will be available in the next version.

**Comment by Dallory** [comment]
Thank you very much!
