### ISSUE TITLE
Pictures saved as image/avif, not viewable in Firefox after save

### ISSUE THREAD

**Issue by egor-duda** [gildas-lormeau/SingleFile#866]
When saving certain pages with SingleFile on Firefox ESR 91.5.0, included images are encoded as image/avif and browser is not able to render them afterwards

**To Reproduce**
1. Create fresh testing Firefox profile, install SingleFile extension, all SingleFile settings are left untouched
2. Go to https://www.theatlantic.com/photo/2022/02/top-shots-2021-international-landscape-photographer-year/621462/
3. Right click->SingleFile->Annotate and save the page...
4. Images in saved file are not rendered properly

**Expected behavior**
Images in saved HTML file are viewable in the browser that created it

**Screenshots**
![Screenshot from 2022-02-03 08-27-40](https://user-images.githubusercontent.com/11626825/152286648-984c8af4-08ad-4804-8096-4cc99031be91.png)

**Environment**
 - OS: Debian Linux 11.2
 - Browser: Firefox
 - Version: 91.5.0ESR

**Comment by gildas-lormeau** [comment]
On paper, I'm not against trying to fix this issue. However, I need really some time to think about it because it really does not look easy to implement.

**Comment by gildas-lormeau** [comment]
In your example, replacing `image: "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",` with `image: "image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",` manually in the settings of SingleFile might fix the issue. See here for more info about how to update this hidden setting: https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options.

**Comment by egor-duda** [comment]
> (i.e. remove `image/avif,`) in the settings of SingleFile might fix the issue though
Yes, it does indeed. Instead of avif images in saved file, webp images are being used now.
Considering that Firefox should soon support avif images out-of-the-box, that workaround seems totally adequate.
Thanks a lot!

**Comment by gildas-lormeau** [comment]
You're welcome! Note that it won't always work though. It worked in this particular example because the server ignored the requested extension (.jpg in your example).
