### ISSUE TITLE
Version mismatch between Firefox Addon store and Github

### ISSUE THREAD

**Issue by arzam16** [gildas-lormeau/SingleFile#869]
**Describe the bug**
When installed from the [Firefox Addon Store thingy](https://addons.mozilla.org/ru/firefox/addon/single-file), the browser says the latest version is 1.19.24, and [Github Releases page](https://github.com/gildas-lormeau/SingleFile/releases) says the latest version is 0.3.32.

**To Reproduce**
1. Install SinglePage from https://addons.mozilla.org/ru/firefox/addon/single-file
2. Open internal firefox addon manager
3. Click on SinglePage and scroll down a bit to see the version

**Expected behavior**
Firefox addon matching the github version

**Screenshots**
![firefox](https://user-images.githubusercontent.com/65257009/152594123-3f4cc97e-08b9-4371-ac5b-301740eb5c5e.png)
![github](https://user-images.githubusercontent.com/65257009/152594252-71354fe5-b1d2-4433-a171-46dbafc5be99.png)

**Environment**
 - OS: Solus 4.3
 - Browser: Firefox
 - Version: 93.0

**Additional context**
tbh I'm not sure it was worth reporting it. Was this versioning scheme actually intended?

**Comment by gildas-lormeau** [comment]
The version `0.3.32` is the version of SingleFile CLI (hosted on NPM). I agree it might be a bit confusing...
