### ISSUE TITLE
New permission: Exchange messages with programs other than Firefox

### ISSUE THREAD

**Issue by miku86** [gildas-lormeau/SingleFile#870]
Hi Gildas,

thank you for your great app!

I wanted to update my current version on Firefox to version`1.19.25`, but I get asked for the permission [Exchange messages with programs other than Firefox](https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions?as=u#w_exchange-messages-with-programs-other-than-firefox).

I don't know much about permissions and would love to hear why SingleFile needs this permission.

Best regards,
Michael

**Comment by gordonfreeman01** [comment]
I'm wondering the same thing, can't find any documentation about that either.

**Comment by gildas-lormeau** [comment]
This permission is needed for people that want to use the SingleFile companion, see https://github.com/gildas-lormeau/SingleFile/tree/master/companion. I just forgot to include it in the Firefox version from the beginning. In the future, I'll try to make it optional.

**Comment by xrat** [comment]
Please also consider adding an item to the FAQ.

**Comment by gildas-lormeau** [comment]
I updated the FAQ.

**Comment by gildas-lormeau** [comment]
The version 1.19.26 I just uploaded on the store makes the permission optional. It will be available for download, once reviewed by Mozilla, in the coming days.

**Comment by xrat** [comment]
Awesome!

**Comment by miku86** [comment]
Thanks for your fast response and for updating the version.
The new version is available as a Firefox extension now.

**Comment by gildas-lormeau** [comment]
You're welcome!
