### ISSUE TITLE
Woleet Library File Missing

### ISSUE THREAD

**Issue by ColdSauce** [gildas-lormeau/SingleFile#874]
**Describe the bug**
the file `lib/woleet/woleet.js`, which [`src/extension/core/bg/autosave.js`](https://github.com/gildas-lormeau/SingleFile/blob/master/src/extension/core/bg/autosave.js#L33) and [`src/extension/core/bg/downloads.js`](https://github.com/gildas-lormeau/SingleFile/blob/master/src/extension/core/bg/downloads.js#L33) reference does not exist.

**To Reproduce**
1. Go to `src/extension/core/bg/autosave.js` and `src/extension/core/bg/downloads.js`
2. See that they are referencing woleet.js from the `lib` folder
3. Go to the `lib` folder, and look for `woleet` 
4. Doesn't exist

Or run rollup
`npx rollup -c rollup.config.js`
And notice this error:
```
[!] Error: Could not resolve './../../lib/woleet/woleet.js' from src/extension/core/bg/autosave.js
Error: Could not resolve './../../lib/woleet/woleet.js' from src/extension/core/bg/autosave.js
    at error (/home/runner/work/SingleFile/SingleFile/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.handleResolveId (/home/runner/work/SingleFile/SingleFile/node_modules/rollup/dist/shared/rollup.js:22336:24)
    at /home/runner/work/SingleFile/SingleFile/node_modules/rollup/dist/shared/rollup.js:22310:26
```
 

**Expected behavior**
The `lib/woleet/woleet.js` file should exist.

**Screenshots**
N/a

**Environment**
n/a

**Additional context**
none

**Comment by gildas-lormeau** [comment]
Thank you and sorry for the inconvenience!
