### ISSUE TITLE
Memory leak followed by a crash

### ISSUE THREAD

**Issue by CodeSpartan** [gildas-lormeau/SingleFile#877]
Firefox version 97.0.1 (64-bit)
SingleFile version 1.19.29 (without permission to exchange messages with other programs and without permission to read/modify bookmarks)
Repro steps: attempt to save some livejournal page, e.g. [this one](https://sl-lopatnikov.livejournal.com/2249061.html).
It will save the page correctly, but then the CPU will go crazy, memory consumption will quickly reach multiple gigabytes in a matter of minutes, and then firefox will crash.
Environment: windows 11 Pro, high end hardware.

**Comment by gildas-lormeau** [comment]
Thank you, I confirm I can reproduce the bug. It looks like it's related to iframes, I'm investigating it. Meanwhile, you can circumvent it by enabling "HTML content > remove frames".

**Comment by gildas-lormeau** [comment]
I fixed the bug. The fix will be available in the version 1.19.31 I just submitted to the store.
