### ISSUE TITLE
Failure to reproduce content of Accordion tags <dd>..</dd>

### ISSUE THREAD

**Issue by GuyGordon1** [gildas-lormeau/SingleFile#878]
**Describe the bug**
Browse to a FAQ page displaying a list of Questions.  Each question is an accordion which you can click to read the Answer.
SingleFile reproduced only the visible text (Questions) with none of the Answers.  
The html tags are all present, but the content of the `<dd></dd>` tags (Answers) is missing.

**To Reproduce**
1. Go to ['ApacheFriendsFAQ'](https://www.apachefriends.org/faq_windows.html)
2. Every line is a question with an accordion answer.  i.e. `<dl class="accordion">::before<dt>Question</dt><dd>Answer</dd>...`
3. Save page with SingleFIle
4. Open the saved file
5. The `<dd></dd>` tags contain no text.  i.e. `<dl class="accordion">::before<dt>Question</dt><dd></dd>...`

**Expected behavior**
Expected the entire accordion, including all `<dd>`tags to be copied to the saved page, 
even though none are visible at the time of the save.

Yes, the Answer text is hidden, but just like a Link, I expected the accordion to open when clicked.

If you open one accordion on the web page and save with SingleFile, the output will contain the answer inside 
the opened `<dd>` tag ONLY.  All other accordions remain empty.  You cannot close the one open accordion or open others.
I don't see why that is so, as the accordion tags are there for that one question.

**Screenshots**
No need.  This looks pretty simple.

**Environment**
Windows 7 Pro x64, Firefox 97.0.  Examined tags using the built-in Inspector in Firefox.

I did a quick search for accordion issues with SingleFile and did not find anything.
Yet I have trouble believing this is a simple omission. 
Sorry if I'm missing something obvious.

If this *is* the intended behaviour, then it should be re-thought.  
Even if this result is following some 'rule' the result is useless, so the rule is wrong.

**Comment by gildas-lormeau** [comment]
I confirm I can reproduce the issue. It's a feature though! You have to disable the option "HTML content > remove hidden elements" :)
