### ISSUE TITLE
Web Archive page save stuck

### ISSUE THREAD

**Issue by msuom** [gildas-lormeau/SingleFile#881]
Hi, the following web archive page is getting stuck at step 1/3 during save:
https://web.archive.org/web/20210516183751/https://www.machinelearningplus.com/nlp/text-summarization-approaches-nlp-example/

Please assist.

**Environment**
 - OS: Win10 Pro
 - Browser: Firefox
 - Version: 97.0.1

**Comment by gildas-lormeau** [comment]
Thank you, I confirm I was able to reproduce the bug. The fix will be available in the next version.
