### ISSUE TITLE
images/gifs are not saved in standalone mode for some websites

### ISSUE THREAD

**Issue by dontfireme** [gildas-lormeau/SingleFile#883]
**Describe the bug**
I wanted to use SingleFile from JS console to archive some pages. I noticed that in some cases, the images and gifs are not saved when running SingleFile from console. Everything works fine when I run it from extension.

**To Reproduce**
1. Go to [latimes.com](https://www.latimes.com/)
2. Paste SingleFile into a JS console
3. Execute following code:

```
const { content, title, filename } = await window.singlefile.getPageData({
  removeImports: true,
  removeScripts: true,
  removeAudioSrc: true,
  removeVideoSrc: true  
});
```

4. Paste the `content` into a `html` file
5. Open `html` file and notice that images and gifs are broken.

**Expected behavior**
Images and gifs are displayed properly, just like when using extension

**Screenshots**
![image](https://user-images.githubusercontent.com/31350083/156385060-9b241b23-3d50-43fe-861a-5e2eaa64d659.png)

**Environment**
 - OS: macOS
 - Browser: Chrome
 - Version: 98

Does anyone know why that happens?

**Comment by gildas-lormeau** [comment]
This issue is due to the same origin policy which prevents SingleFile from reading the content of some images. You can see the issue by going to latimes.com and running the code below in the JS console.
```js
await fetch("https://www.latimes.com/subscriptions/img/logo-lat-full-black.svg");
```
You'll see that the code throws an exception. This exception could be circumvented by disabling the same origin policy, as explained here for example: https://stackoverflow.com/questions/35432749/disable-web-security-in-chrome-48. However, this could lead to security issues.

**Comment by dontfireme** [comment]
@gildas-lormeau Thank you for the response.

Why does it work in extension though?

If this is due to the CORS, can I use something like https://github.com/Rob--W/cors-anywhere to fix that?

Thanks again!

**Comment by gildas-lormeau** [comment]
@dontfireme Sorry for the late answer, The extension you mentioned should indeed allow to circumvent the CORS issue. SingleFile uses the background page to fetch contents as a workaround.

**Comment by Goldmaster** [comment]
I have a similar issue with reddit posts. if i have gif or videos that play from imgur, i only just have a single frame, rather than the whole video or gif

**Comment by gildas-lormeau** [comment]
@Goldmaster can you please post an example of URL showing this issue?

**Comment by Goldmaster** [comment]
Here's an example of a post https://www.reddit.com/r/interestingasfuck/comments/a264lv/extreme_portal_racing/

**Comment by Goldmaster** [comment]
Ah thank you. So is there a setting I have missed to include the gif in the page itself?

**Comment by gildas-lormeau** [comment]
No, SingleFile cannot include the GIF in this case.
