### ISSUE TITLE
Option-> File Name -> Extension (date)

### ISSUE THREAD

**Issue by womotroll** [gildas-lormeau/SingleFile#89]
Please add the possibility to extend the filename with datum information for better sorting.
For example:   2018-11-04_{page-title}.html

Thank's

Eberhard

**Comment by gildas-lormeau** [comment]
Isn't what `{date-iso}_{page-title}.html` would produce?

**Comment by womotroll** [comment]
That is exactly what i want!
Thank you very much, Eberhard

**Comment by gildas-lormeau** [comment]
You're welcome!
