### ISSUE TITLE
When file urls are enabled for the extension, Autodownload is active when opening the downloaded items.

### ISSUE THREAD

**Issue by unphased** [gildas-lormeau/SingleFile#891]
Well, first I was trying to test the companion script, but it doesn't work. Hoping there is an upcoming version of the plugin that makes it work, based on this: https://github.com/gildas-lormeau/SingleFile/issues/865 Anyway, 

**Describe the bug**
I found a funny behavior. I know we can turn on file url access for this extension to make the info bar work when we open the saved files. But I realized that this also makes it autodownload these when we open them. That can't be right. 

**To Reproduce**
1. enable autodownload
2. enable file url for the extension
3. load a page
4. open the downloaded SingleFile HTML made from it
5. Watch another SingleFile HTML be autodownloaded for this opened file.

**Expected behavior**
SingleFile figures out by default that it should not redownload these. 

**Environment**
 - OS: Ubuntu 20.04.3
 - Browser: Chrome

**Additional context**
I think it may be possible to set up an "auto-settings rule" that gives the desired control over file urls. However this is highly nonintuitive so maybe we can populate one by default here that just says not to download any file url?

**Comment by gildas-lormeau** [comment]
Thank you for the report. I agree with you. Having the auto-setting rule by default seems to be the best way to handle this issue.
