### ISSUE TITLE
Failed to launch the browser process! spawn chrome ENOENT

### ISSUE THREAD

**Issue by h2cone** [gildas-lormeau/SingleFile#892]
**Describe the bug**
% single-file https://www.wikipedia.org wikipedia.html
Failed to launch the browser process! spawn chrome ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

**To Reproduce**
1. Manual installation: npm install -g "gildas-lormeau/SingleFile#master"
2. Run: single-file <url> [output] [options ...]
3. See error

**Expected behavior**
Save https://www.wikipedia.org/ into wikipedia.html in the current folder.

**Environment**
 - OS: Darwin metaloop.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64
 - Browser: Google Chrome 99.0.4844.51 (arm64)
 - Node.js: v17.6.0
 - npm: 8.5.1
 - Version: 0.3.32

**Comment by gildas-lormeau** [comment]
SingleFile was not able to find the executable of Chrome. See here for more info: https://github.com/gildas-lormeau/SingleFile/issues/889
