### ISSUE TITLE
= SingleFile Disabled in Chrome/Brave? =

### ISSUE THREAD

**Issue by mettaseva** [gildas-lormeau/SingleFile#895]
**Describe the bug**
Just now discovered your indispensable plugin has been disabled in Chrome, and it has disappeared from my Brave browser! (In fact, I could not even submit a support ticket in Chrome's web store.)

Are you aware of the issue? And is there any hope of a fix in the near term?

**To Reproduce**
Shortcut to the extension is no longer visible in the Brave Browser

**Expected behavior**
Quick, 1-click access from the toolbar within the Brave Browser

**Environment**
 - OS: Windows 7
 - Browser: Brave
 - Version: 1.25.72 Chromium: 91.0.4472.101 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by gildas-lormeau** [comment]
I am not aware of such a problem. Maybe the extension icon is no longer pinned to the extension toolbar (see jigsaw piece icon) for some unknown reason?

**Comment by mettaseva** [comment]
That's not it. The extension has been *removed* from my Brave browser, and
when I went out to the Chrome web store to download and install it again,
there's a message saying the app has been disabled. Clicking on the
"enable" option does nothing.

See attached screenshot.

**Comment by mettaseva** [comment]
Strange that the screenshot didn't come through. I've attached it again
in the hope that you will receive it on the 2nd go 'round.

FWIW, I'm on a home computer, so there are no admin issues here.

**Comment by gildas-lormeau** [comment]
All I can say is that this problem is not widespread. You are the only person out of about 140k users who reported this to me. You can use an alternative extension if you want, I won't stop you...

**Comment by gildas-lormeau** [comment]
I'm closing this issue because there's nothing I can do to fix it as far as I know.

**Comment by mettaseva** [comment]
Ok, great. Glad the problem is not widespread. Just thought you would want
to know, in case it was impacting a significant percentage of your users.
