### ISSUE TITLE
connect ECONNREFUSED ::1:63657

### ISSUE THREAD

**Issue by Mennaruuk** [gildas-lormeau/SingleFile#896]
**Describe the error**
`connect ECONNREFUSED ::1:63657`

**To Reproduce**
1. Launch Command Prompt
2. Close all open Firefox instances
3. Enter the following command:
`single-file https://pdfshelter.com/ --crawl-links=true --crawl-inner-links-only=false --crawl-max-depth=10 --crawl-replace-urls=true --browser-executable-path="C:\Program Files\Mozilla Firefox\firefox.exe"`

**Expected behavior**
I followed the instructions in #478 to crawl and download site. I expected for site with its pages to be downloaded.

**Environment**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 98

**Additional context**
Thank you.

**Comment by gildas-lormeau** [comment]
It looks like you forgot to pass the `--back-end` option, e.g. `--back-end=puppeteer-gecko` (or `--back-end=webdriver-gecko` with selenium).

**Comment by Mennaruuk** [comment]
Switching to Puppeteer helped solve the problem. Thank you!

**Comment by gildas-lormeau** [comment]
You're welcome!
