### ISSUE TITLE
Safari ios not playing videos

### ISSUE THREAD

**Issue by vinxenz** [gildas-lormeau/SingleFile#897]
Hi,
in browser safari of iphone the file build by the extention 'single file' isn't able to play videos.
How can be played?

**Comment by gildas-lormeau** [comment]
SingleFile can only save "simple" videos. It cannot save videos played from streaming platforms for example. What page did you try to save?

**Comment by vinxenz** [comment]
It' s not a streaming but inline video. I see the base64 source in the html
but it's due to safari player that doesn't fully support html videos.

Il lun 21 mar 2022, 23:54 Gildas ***@***.***> ha scritto:
