### ISSUE TITLE
file name wrong

### ISSUE THREAD

**Issue by gthb1** [gildas-lormeau/SingleFile#899]
Hi,
SingleFile is a great extension.
The following seems like a easy fix, hopefully!

When saving in Chrome a page e.g. firefox.com,
it produces a file name like
41d8a087-7c2a-40c6-8852-2feed2c2c2a8.htm
instead of
Download Firefox Browser — Fast, Private & Free — from Mozilla (3_20_2022 8_11_42 PM).html

Even after trying another options profile in the extension, it does not save the file name correctly.
This does not happen in Firefox. Upon further checking, this seems due to a conflict with ChronoDownloadManager.

Thx for checking/fixing!
:)

**Comment by gildas-lormeau** [comment]
This bug in Chrome is documented here: https://github.com/gildas-lormeau/SingleFile#known-issues (see 2nd item for Chromium-based browsers). Maybe Google will fix it someday...

**Comment by gthb1** [comment]
But it does not happen without ChronoDownloadManager.
So how can a user adjust settings to avoid this problem?

**Comment by gildas-lormeau** [comment]
This is a conflict with ChronoDownloadManager, maybe installing SingleFile first and ChronoDownloadManager after might help to circumvent this bug.

**Comment by gildas-lormeau** [comment]
You're welcome :)

**Comment by KnIfER** [comment]
Ok before the "minor" bug is fixed ( 10 years or even later, lol ), the workaround should be : 



https://github.com/gildas-lormeau/SingleFile/blob/41ca36a48e6c4394f19bd7c794d0c0893929a5c8/src/extension/core/bg/download-util.js#L40


```js
	if(!downloadInfo.saveAs) {
		function downloadFile(fileName, url){
			const link = document.createElement('a');
			link.download = fileName;
			link.href = url;
			link.dispatchEvent(new MouseEvent('click'));
			URL.revokeObjectURL(link.href);
		}
		downloadFile(downloadInfo.filename, downloadInfo.url);
		return new Promise((resolve, reject) => {
			resolve({});
		});
	} 
	else { 
	…… original business logic
```



Although Extension "Double-click image downloader" can download images in background with the correct file name. Save a file like `6219ac03-ef92-45de-80e4-55d932739fa9.tmp` first, then it will be renamed to the correct file name. ( dont know how, it's not opensourced )

**Comment by gildas-lormeau** [comment]
This workaround won't work with Manifest V3 though. That's also what SingleFile does when "save in background" is disabled. The difference is that it's done in directly in the content script, see below.

https://github.com/gildas-lormeau/SingleFile/blob/b219ddec6a4dd17a6ac3603c3ac4397137c41e34/src/extension/core/common/download.js#L92-L99
