### ISSUE TITLE
file name does not display correctly

### ISSUE THREAD

**Issue by wq0372** [gildas-lormeau/SingleFile#902]
1. After downloading other browsers, the file name does not display correctly in Microsoft edge browser.

![image](https://user-images.githubusercontent.com/19257151/159883677-fbba0b44-70be-4e11-bad3-9b828b0da916.png)

2. The system is in Chinese, but the plug-in can't display Chinese in microsoft edge browser, and Firefox browser can display Chinese normally.

**Comment by gildas-lormeau** [comment]
This bug in Chrome is documented here: https://github.com/gildas-lormeau/SingleFile#known-issues (see 2nd item for Chromium-based browsers). Maybe Google will fix it someday...
