### ISSUE TITLE
A few issues with the Add Urls dialog

### ISSUE THREAD

**Issue by raelb** [gildas-lormeau/SingleFile#903]
Hi Gildas,
A few issues with the Add Urls dialog on Firefox.
1 - It start very small. Would help if bigger.
![image](https://user-images.githubusercontent.com/13108198/159907521-085059bf-c45b-49a0-a865-8ac7f0dfab33.png)

2. Can only enlarge height with size grip but not width:
![image](https://user-images.githubusercontent.com/13108198/159907730-b93d486b-d8e5-4553-9439-d814e0b13bff.png)

3. When paste in a url, it is completely invisible i.e. white. I need to select to see that it is in fact there.
![image](https://user-images.githubusercontent.com/13108198/159907976-b5ac0789-29aa-415d-a223-332719d73959.png)

**Environment**
 - OS: Win10 Pro x64
 - Browser: Firefox
 - Version: [e.g. 64]

**Comment by gildas-lormeau** [comment]
Thank you for the detailed report. #3 was fixed some days ago but I did not publish the fix. I just fixed #1 and #2, the fix will be available in the version 1.19.35. I should upload it to the stores very soon.
