### ISSUE TITLE
Feature request: Add menu item to "Batch save urls"

### ISSUE THREAD

**Issue by raelb** [gildas-lormeau/SingleFile#904]
Hi,
Feature request to add menu item to "Batch save urls".
Currently this feature is available from the view pending saves view, however, that is fairly buried from the main menu options. It took me a while to find out about it. I needed to search through some closed issues to see if such an option existed.
I suggest having it alongside the "view pending saves" item. But it could be somewhere else. My suggestion is just that this feature is more visible (especially for new users...)

**Comment by gildas-lormeau** [comment]
I didn't think of adding an entry in the menu, I agree that it would be more convenient and it would highlight the feature.

**Comment by gildas-lormeau** [comment]
It's implemented, the feature will be available in the next version. I'll fix one or two other things, wait for some translations and I'll probably publish the update in a few days.
