### ISSUE TITLE
Preview selected links

### ISSUE THREAD

**Issue by raelb** [gildas-lormeau/SingleFile#905]
I imagine this to be a lot of work, but it would be quite helpful to have a "preview selected links" dialog, that comes up when you click on the "save selected links" button. Often html selections are bringing in unwanted links, e.g. in a forum page there are the topics and then links to the author (which you don't want to download).

It would be useful to have a preview dialog that shows which links are going to be downloaded, where you can un-select some links you don't want downloaded - similar to the pending saves view.

A fancy implementation would show html titles along side the links.

**Comment by gildas-lormeau** [comment]
I think this is indeed a nice feature. I'll try to implement it.

**Comment by raelb** [comment]
Glad to hear that. And then another nice addition would be the ability to filter the list of links. (i.e. include links containing.. or exclude links containing..). The point is that selecting links is a bit of a dodgy process, so having the ability to fine tune the results would be very helpful.

**Comment by gildas-lormeau** [comment]
I reused the "Batch save URLs" to implement this feature. Right now, there is no way to filter URLs yet but I plan to implement it soon, that's why I keep the issue open.

**Comment by raelb** [comment]
Great, I'm excited to try the preview feature out, can you let me know when the new version is released

**Comment by raelb** [comment]
Thanks for that. I think I'm doing it right, but when I load the extension (about:debugging) it does not show new menu item (Batch save urls). I'm downloading zip from https://github.com/gildas-lormeau/SingleFile. Is that not correct?

**Comment by gildas-lormeau** [comment]
If you followed the instructions, you should see it (see below) in the "Debugging" page `about:debugging#/runtime/this-firefox`.

![image](https://user-images.githubusercontent.com/396787/161828273-d6209755-cb12-48ff-9a15-b658ff071420.png)

Then, the entry should also be present in the context menu

**Comment by raelb** [comment]
Yeah, I've got that, but no menu item.

![image](https://user-images.githubusercontent.com/13108198/161844732-09317532-3a01-49a2-825b-785c6c7eed97.png)

**Comment by gildas-lormeau** [comment]
My bad, I forgot that JS files in the `/lib` folder must be built. It should work now if you download the zip again.

**Comment by raelb** [comment]
ok, working now. Nicely done. I look forward to the filtering ability.

**Comment by gildas-lormeau** [comment]
There is now (in the development branch) an icon at the top right of the table allowing you to filter the URLs.

**Comment by gildas-lormeau** [comment]
FYI, I just uploaded the new version on the store. It should be available for download before the end of the week hopefully.
