### ISSUE TITLE
<noscript><meta http-equiv="refresh" causes problems when viewing a SingleFile capture with JavaScript disabled

### ISSUE THREAD

**Issue by ivan** [gildas-lormeau/SingleFile#907]
**Describe the bug**

Hi Gildas,

I used SingleFile with the default options in Chrome 99 to save https://duckduckgo.com/?q=rmt+filename+support+makes+tar+vulnerable+site%3Abugs.debian.org&ia=web

My capture is available at https://ludios.org/tmp/rmt%20filename%20support%20makes%20tar%20vulnerable%20site_bugs.debian.org%20at%20DuckDuckGo.html

When the capture is viewed in Chrome or Firefox with JavaScript disabled (e.g. using uBlock Origin's 'Click to disable JavaScript on this site'), the `<noscript><meta http-equiv="refresh"` in the saved capture is triggered and the browser redirects to a nonexistent page.

Because SingleFile advertises 'Files can be viewed without running JavaScript', I believe that SingleFile could somehow neutralize these noscript meta refresh redirects (and by default?).

All the best,

Ivan

**To Reproduce**
1. Use SingleFile to save https://duckduckgo.com/?q=rmt+filename+support+makes+tar+vulnerable+site%3Abugs.debian.org&ia=web with the default options
2. Put the capture on a web server
3. Load the capture with JavaScript disabled in the browser
4. Observe the page redirect to some other page

**Expected behavior**
Don't redirect when viewing the capture

**Environment**
 - OS: Windows 10 21H2
 - Browser: Chrome 99 and Firefox 97
 - Version: SingleFile 1.19.35

**Comment by gildas-lormeau** [comment]
Hi Ivan, thank you for the suggestion. I think I'll ad an option to remove noscript tags. It will probably be enabled by default because SingleFile does not process them yet.

**Comment by gildas-lormeau** [comment]
You're right @ivan. I did not add an option to remove `noscript` tags but implemented your suggestion instead. The fix will be available in the next version which should be published in the coming days.
