### ISSUE TITLE
Commit package-lock.json

### ISSUE THREAD

**Issue by mbrgm** [gildas-lormeau/SingleFile#910]
**Is your feature request related to a problem? Please describe.**

I tried to package SingleFile for the nix package manager. My chosen way of doing this is using the [npm2lock2nix](https://github.com/nix-community/npmlock2nix) tool, which ensures reproducability by referencing the `package-lock.json` file of a package. Not having the file inside the source repo makes this more tedious than it needs to be (patching, additional build steps etc.).

**Describe the solution you'd like**

Commit the `package-lock.json` file in source control.

**Describe alternatives you've considered (optional)**
A clear and concise description of any alternative solutions or features you've considered. This is also [recommended according to the npm documentation](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json):

> This file is intended to be committed into source repositories [...]

If you don't mind, I would create a PR for this. Alternatively, as it is not a big change, maintainers could do this without the overhead of a PR.

**Comment by gildas-lormeau** [comment]
I pinned the dependency versions, is the `package-lock.json` in that case?

**Comment by gildas-lormeau** [comment]
Thank you for the additional info. I added it on git.

**Comment by mbrgm** [comment]
Great, thank you! Now I'll be able to package this more easily. :)
