### ISSUE TITLE
Bit more padding for buttons in "Add Urls" page

### ISSUE THREAD

**Issue by raelb** [gildas-lormeau/SingleFile#919]
This is a small request.

![image](https://user-images.githubusercontent.com/13108198/161860464-c4b67b56-f22e-497f-83a2-e3a31c1fa971.png)

I think the buttons in the `Add URLs` dialog could do with some more padding, The OK button is a bit difficult to click on. Perhaps you can make it the same width as Cancel button, (more padding for both)

As I said, a small thing ☺

**Comment by gildas-lormeau** [comment]
Thank you, it's fixed :)
