### ISSUE TITLE
Can we set the path of --browser-executable-path ?

### ISSUE THREAD

**Issue by mobilelifeful** [gildas-lormeau/SingleFile#922]
**Describe the bug**
```
single-file https://www.wikipedia.org/ wikipedia.html 
spawn ENOTDIR

```
seem like single-file is not able to find the path of browser 
**To Reproduce**
1.  install single-file through NPM
2. install google chrome
3. add chrome path to .bashrc 
4. single-file https://www.wikipedia.org/ wikipedia.html

**Expected behavior**
It would just download the Wikipedia page 

**Screenshots**

**Environment**
 - OS: Ubuntu 20.04.1,
 - Browser:  Chrome,  
 - Version:
```
running  single-file -v or single-file version return:
spawn ENOTDIR

```
**Additional context**

**Comment by gildas-lormeau** [comment]
What is the name of the executable? SingleFile will try to launch `chrome` by default.
