### ISSUE TITLE
Saved pages of sspai hasn't CSS style

### ISSUE THREAD

**Issue by OvO7000** [gildas-lormeau/SingleFile#923]
**Describe the bug**
Saved pages of sspai hasn't CSS style.

**To Reproduce**
1. Go to 'https://sspai.com/post/64302'
2. Click on singlefile extension icon and save the page

**Screenshots**
![the origin web page](https://user-images.githubusercontent.com/24329456/162652813-f7b10e3f-4514-49d8-be5a-e94025b59c70.png)

![the saved page](https://user-images.githubusercontent.com/24329456/162652864-fc4d8d2b-4e1d-4258-b4e2-6deda8404da1.png)

**Environment**
 - OS: Win10 Pro
 - Browser: Chrome

**Comment by gildas-lormeau** [comment]
This issue is a bug in Chrome (and Firefox), see https://crbug.com/1131384. Unfortunately, there is nothing (reasonable) I can do on my end to circumvent it.

**Comment by xjacky8000** [comment]
me too!

**Comment by gildas-lormeau** [comment]
You should be able to circumvent this issue bu using an extensions which removes CORS headers like https://chrome.google.com/webstore/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino. However, you should not enable this extension when surfing on other sites.

**Comment by gildas-lormeau** [comment]
My bad, you can fix this issue by enabling the option `Misc > pass "Referer" header after a cross-origin request error` in SingleFile.

**Comment by hexacera** [comment]
Thanks @gildas-lormeau, that worked flawlessly! In case someone comes across this in 2024, seems like the aforementioned option has moved from "Misc" to "Network".
