### ISSUE TITLE
Selenium extension trigger for save page we

### ISSUE THREAD

**Issue by codejunction** [gildas-lormeau/SingleFile#928]
**Is your feature request related to a problem? Please describe.**
I am injecting the single file we extension crx file in my selennium grid driver object.
need a way to execute the extension from console by using a script

**Describe the solution you'd like**
a single script source that will run the plugin and return the page source rather than downloading it

**Describe alternatives you've considered (optional)**

**Additional context (optional)**

**Comment by codejunction** [comment]
cli will have to be used separately. i have a custom selenium grid on which i create browser instances and inject the extension.
i'm using selenium with Python 3.8. os after adding the extension, i need to download the page source for archieving.

**Comment by gildas-lormeau** [comment]
Here are the generic instructions in order to use SingleFile in your environment: https://github.com/gildas-lormeau/SingleFile/wiki/How-to-integrate-SingleFile-library-code-in-%22custom%22-environments%3F
