### ISSUE TITLE
Single file integrated into an extension crashes if document comment is presented.

### ISSUE THREAD

**Issue by BarrBozzO** [gildas-lormeau/SingleFile#929]
**Describe the bug**
SingleFile API integrated into extension fails when tries to parse document first comment. Integration is implemented according to this wiki: https://github.com/gildas-lormeau/SingleFile/wiki/How-to-integrate-the-API-of-SingleFile-into-an-extension.

In `single-file-core.js` file, line 482:
https://github.com/gildas-lormeau/SingleFile/blob/master/src/single-file/single-file-core.js#L482

`util.COMMENT_HEADER` and  `util.COMMENT_HEADER_LEGACY` are both empty strings, hence any text node  matches condition: `if (firstComment.nodeType == 8 && (firstComment.textContent.includes(util.COMMENT_HEADER_LEGACY) || firstComment.textContent.includes(util.COMMENT_HEADER)))`

In next few lines crash happens as random text nodedoesn't match SingleFile pattern comment pattern.
```
const info = this.doc.documentElement.firstChild.textContent.split("\n");
const [, , url, saveDate] = info;
infobarURL = url.split("url: ")[1];
```

**To Reproduce**
1. Integrate API according to wiki.
2. Try to capture any html page with a text node which is presented in a "SingleFile comment spot"
3. See error

**Expected behavior**
Expected to see correct values set `util.COMMENT_HEADER` and  `util.COMMENT_HEADER_LEGACY`, so SingleFile doesn't crash

**Screenshots**
No screenshot

**Environment**
 - OS:Linux Mint
 - Browser: Chrome
 - Version: 100

**Additional context**
I assume that for some reason `util.COMMENT_HEADER` \`util.COMMENT_HEADER_LEGACY` are not set correctly.

**Comment by gildas-lormeau** [comment]
I cannot reproduce the issue. On my end, `util.COMMENT_HEADER` and `util.COMMENT_HEADER_LEGACY` are not empty. I attached the project I used to reproduce your issue. I included the `debugger` keyword just before the code you mentioned. Open a page and the developer tools. Once loaded, you'll hit the breakpoint and see that `Bm.COMMENT_HEADER_LEGACY` and `Bm.COMMENT_HEADER` are not empty strings.
However, I agree that that the regexp could fail and lead to an error so I will add a `try/catch`.

[SingleFile-Mini.zip](https://github.com/gildas-lormeau/SingleFile/files/8586369/SingleFile-Mini.zip)
