### ISSUE TITLE
Auto-saving bookmark with allowed folder is inconsistent in Firefox

### ISSUE THREAD

**Issue by willlma** [gildas-lormeau/SingleFile#933]
**Describe the bug**
When automatically saving bookmarks saved to a specific "allowed folder", saving only works if the last bookmark was saved to the same folder. 

**To Reproduce**
1. Open Firefox and go to _about:addons_
2. Find SingleFile and click the overflow menu (...) then _preferences_
3. Open the _Bookmarks_ section, enable it, and add a folder name to the "allowed folders" section as shown in the screenshot
4. Visit any webpage and save it to your bookmarks into a different folder
5. Visit another webpage and save it to your bookmarks in the folder added to the "allowed folders" field. SingleFile does not save the page. 

**Expected behavior**
I expected SingleFile to save the page in step 5. 

**Screenshots**
<img width="634" alt="image" src="https://user-images.githubusercontent.com/4404401/164564326-21b37cd5-5f5e-4ac2-bdf6-bf4a604e47f6.png">

**Environment**
 - OS: MacOS 10.12
 - Browser: Firefox
 - Version: 99.0.1

**Additional context**
After step 5, if I then save another page to the same folder, it saves as expected. What I think is happening behind the scenes is that Firefox creates a bookmark when I click the ⭐️ button. Then when I select the right folder (_Read Later_) and click _Save_, it _moves_ the bookmark to that folder and SingleFile is probably not listening for a move event?

As a result, a secondary bug that occurs is that if I save something to my _Read Later_ folder, then save another bookmark to another folder, that second bookmark is downloaded by SingleFile even though I don't want it to be.

Love SingleFile, thanks for the hard work.

**Comment by willlma** [comment]
If my hunch is right, then you'd want to add an [onMoved](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/onMoved) listener to [bookmarks.js#L63](https://github.com/gildas-lormeau/SingleFile/blob/HEAD/src/extension/core/bg/bookmarks.js#L63). Not sure if Chrome behaves in the same way though.

**Comment by gildas-lormeau** [comment]
Thank you for the issue and the hint. I fixed it in the commit above. The fix will be available in the next version that I should publish very soon.

**Comment by willlma** [comment]
Awesome, thanks. Nice use of a `Set`.

**Comment by willlma** [comment]
Hi @gildas-lormeau, the fix is working for the scenario where I change the folder it is saved to from another folder to the target folder, but there are two situations that seem buggy to me:

1. When I bookmark a page, it starts the save process. If I click _Cancel_ in the bookmark popup the page is still downloaded.
2. When I bookmark a page, it starts the save process. But then I change the _Location_ in the bookmark popup to a different folder. The page is still downloaded even though the bookmark is in the wrong folder. 

These scenarios are less problematic than the one you fixed, as I can manually delete the file myself.

**Comment by gildas-lormeau** [comment]
@willlma I agree that there are things that could be better. I'm aware of these issues, the problem is that the bookmarks API is really not adapted to this use-case generally speaking. I'll try to fix the issues you mentioned.
