### ISSUE TITLE
Is it possible to replace spaces in the file name template?

### ISSUE THREAD

**Issue by 07416** [gildas-lormeau/SingleFile#934]
I avoid spaces in filenames and would prefer replacing all with dots, underscores or dashes.

**Comment by gildas-lormeau** [comment]
You can add the space character in the `filenameReplacedCharacters` array, see here fore more info https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options.

**Comment by 07416** [comment]
appears to work; from the edited JSON file:

```
      "filenameReplacedCharacters": [
        " ",
        "~",
        "+",
        "\\\\",
        "?",
        "%",
        "*",
        ":",
        "|",
        "\"",
        "<",
        ">",
        "\u0000-\u001f",
        "^?"
      ],

```
