### ISSUE TITLE
Stuck at step 2/3 when saving this web page.

### ISSUE THREAD

**Issue by iouzzrj** [gildas-lormeau/SingleFile#935]
**Describe the bug**
The save process is stuck at step 2/3 when saving this web page: https://www.bluehost.com/help/article/force-ssl-on-all-pages

**To Reproduce**
1. Go to https://www.bluehost.com/help/article/force-ssl-on-all-pages
2. Click on Save page with SingleFile
3. See error

**Expected behavior**
The save process should complete.

**Screenshots**

**Environment**
 - OS: Win 10
 - Browser: MS Edge

**Comment by gildas-lormeau** [comment]
It's not stuck, you just have to wait a little bit.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback @iouzzrj. It's also an issue in SingleFile actually because I refuse to implement a network timeout. However, I did not expect that this would cause such a delay. I think I'll reconsider my opinion on this.

**Comment by gildas-lormeau** [comment]
@iouzzrj The version 1.20.4 which should be available for download hopefully in the coming days (reviews are very long at Microsoft...) will include the hidden option `networkTimeout` which will allow you to circumvent this issue. If you set it for example to  `60000`, SingleFile will ignore a resource after waiting a maximum delay of 1 minute. See here for more info on how to set the hidden options: https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options.
