### ISSUE TITLE
npm package 

### ISSUE THREAD

**Issue by goyalpuneet18** [gildas-lormeau/SingleFile#936]
**Is your feature request related to a problem? Please describe.**
I have used your extension several times and it worked very well all the time, I recently worked on a project where I need to check the accessibility of the web page, and along with that, I need to save the page at the same time.  I m using a puppeteer to do that but as you might know, we can not trigger the extension using the puppeteer. 

**Describe the solution you'd like**
So I want to request is to have npm package of the SingleFile wherein we can pass the web page data and get the single file as an output.

**Comment by gildas-lormeau** [comment]
Did you have a look at SingleFile CLI? see https://github.com/gildas-lormeau/SingleFile/tree/master/cli

**Comment by goyalpuneet18** [comment]
Yes I did but my URLs have authentication as well, what I'm right now doing is using the headless puppeteer and doing the necessary authentication and saving the page.content() in an HTML file. if there is a way that I can pass that HTML file and get the SIngleFile as an output that would be amazing.

** HTML page has all the necessary JS URL and CSS URL in it 


The second option can that I should be able to call the necessary Siglefile methods when my page is open in the Puppeteer to get the SingleFile as an Output

**Comment by gildas-lormeau** [comment]
I guess your best option would be to integrate SingleFile manually as described here: https://github.com/gildas-lormeau/SingleFile/wiki/How-to-integrate-SingleFile-library-code-in-%22custom%22-environments%3F. The CLI implementations might also help : https://github.com/gildas-lormeau/SingleFile/tree/master/cli/back-ends.

**Comment by goyalpuneet18** [comment]
Thank you So much for your responses :)

**Comment by gildas-lormeau** [comment]
You're welcome! I'm closing the issue. Although feel free to comment it if needed.
