### ISSUE TITLE
Does not save colors

### ISSUE THREAD

**Issue by ShalokShalom** [gildas-lormeau/SingleFile#937]
**Describe the bug**

I have a website with colored text. SingleFile downloads it without that colors. 

**To Reproduce**
1. https://www.wfelix.org/gmg.html
2. Download
3. Open

**Expected behavior**

Green color is preserved

**Screenshots**

![Screenshot_93](https://user-images.githubusercontent.com/6344099/165811617-ce2af197-8134-4130-b109-a57ea9104db6.png)

![Screenshot_95](https://user-images.githubusercontent.com/6344099/165811843-469af811-dea6-4752-b45d-dc831fd5902e.png)

**Environment**
 - OS: [e.g. Win10 Pro, Ubuntu 18.04.1, Android 7.1.2] Linux Garuda Arch
 - Browser: [e.g. Chrome, Firefox] Firefox/Firedragon
 - Version: [e.g. 64] current

**Comment by gildas-lormeau** [comment]
I cannot reproduce the issue. I did the test with the latest version of Firefox on Win 11 Pro. I doubt the OS is responsible for this though. On my end, the page is displayed with a light theme. Do you use an extension to make the page dark?

**Comment by ShalokShalom** [comment]
Confirmed. Seems working now. 
Thanks

**Comment by gildas-lormeau** [comment]
Thank you for the feedback!
