### ISSUE TITLE
Failed to save page on certain website

### ISSUE THREAD

**Issue by dbc2rs** [gildas-lormeau/SingleFile#944]
**Describe the bug**
Failed every time on Seeking Alpha web site.

**To Reproduce**
https://seekingalpha.com/news/3834480-catalyst-watch-rivian-lockup-expires-western-digital-event-and-inflation-prints
Or any free or paid articles on the web site.

**Expected behavior**
Annotate and then save articles and comments.

**Screenshots**
![SA_2022-05-07_131859](https://user-images.githubusercontent.com/65310610/167270565-411b3f97-62a3-49c1-a9a6-268329d928ef.png)

**Environment**
 - OS: [Win7 Ultimate 64bit]
 - Browser: [Firefox PortableApps]
 - Version: [since v90 or even earlier]

**Additional context**
Save Page WE has no such problem.  Also, SingleFile works on top of Save Page WE's saved Seeking Alpha pages.

**Comment by gildas-lormeau** [comment]
I cannot reproduce your issue with the stable version of Firefox. Did you change any settings in SingleFile?

**Comment by dbc2rs** [comment]
I reset all options and profiles and it works.  Sorry I must have done something stupid with settings.  Thanks for the tip.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback. Maybe the option "remove scripts" was disabled. Unfortunately it often break saved pages because it's actually hard to save scripts reliably.
