### ISSUE TITLE
Placeholder image missing

### ISSUE THREAD

**Issue by jay1803** [gildas-lormeau/SingleFile#947]
**Describe the bug**

**To Reproduce**
1. Go to 'https://www.intercom.com/live-chat/intercom-vs-zendesk'
2. Click on the extension to download the page
3. Open the file
4. You will see some images are missing

**Expected behavior**
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/6468344/168002880-963246b6-5eca-48f3-a944-ac61d1cb84dd.png">

It's video here, but there's a placeholder image, so I think the expectation is the placeholder image displayed.

**Screenshots**
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/6468344/168002708-096cfc3d-324e-4f5e-bbf0-e4d07ac3b436.png">

**Environment**
 - OS: macOS 10.12, Vavivld
 - Browser: Vivald
 - Version: 5.2

**Comment by gildas-lormeau** [comment]
Thank you, it was a known issue but I was able to find a way to circumvent it. The fix will be available in the next version.
