### ISSUE TITLE
saving offline html pages

### ISSUE THREAD

**Issue by parhizkari** [gildas-lormeau/SingleFile#950]
Thank you for the nice add-on. It works great for the online web-pages, but I couldn't have success better than to obtain the same result as when Save-As process is triggered, for saving an offline content. Even the online content **while being offline** will not be saved as expected. Is this something about setting the add-on, or setting the browser's security options, or just not supported?
Sorry if this question is on the wrong place, I couldn't find a place for it.

**Comment by gildas-lormeau** [comment]
Unfortunately, this is a limitation due to the browser. AFAIK, there's nothing I can do in SingleFile to prevent this.
