### ISSUE TITLE
no URL decode for utf-8 character

### ISSUE THREAD

**Issue by longguzzz** [gildas-lormeau/SingleFile#957]
**Describe the bug**

Using {url-search-word} in file name will generate the url encoded alphabets which is not the wanted character.

**To Reproduce**

1. https://humanum.arts.cuhk.edu.hk/Lexis/lexi-mf/search.php?word=的
2. Use "({date-locale} {time-locale}) {url-search-word} {page-title}.html" for file name in setting
3. Save
4. Gain "_E7_9A_84" but "的" in {url-search-word}

**Expected behavior**

Decoding %E7%9A%84 to utf-8 character “的”

**Screenshots**

**Environment**
 - OS: [e.g. Win10 Pro, Ubuntu 18.04.1, Android 7.1.2]
 - Browser: [e.g. Chrome, Firefox]
 - Version: [e.g. 64]

Win10 x64, chrome 101.0.4951.67

**Additional context**

**Comment by gildas-lormeau** [comment]
Thank you, I confirm I was able to reproduce and fix the issue. The fix will be available in the version 1.21.7 which I should publish very soon.
