### ISSUE TITLE
Hangs while saving webpage using either CLI or browser extension

### ISSUE THREAD

**Issue by benyeoh** [gildas-lormeau/SingleFile#958]
**Describe the bug**
SingleFile hangs indefinitely when saving [webpage](https://my.archdaily.com/us/@dfgdgrgre) using Chrome browser, either with CLI or manually with the Chrome extension.

**To Reproduce**
1. For CLI, run: `./single-file --browser-executable-path=/usr/bin/google-chrome --browser-load-max-time 5000 https://my.archdaily.com/us/@dfgdgrgre`
2. Otherwise, navigate to URL with Chrome browser
3. With default settings, save the page using SingleFile extension

**Expected behavior**
Saves page successfully.

**Environment**
 - OS: Ubuntu 18.04.1
 - Browser: Chrome

**Comment by gildas-lormeau** [comment]
Thank you, I am not able to reproduce the issue with the extension (and the default settings) but I think I was able to reproduce and fix it with the CLI tool.
