### ISSUE TITLE
Unable to load file on Google Docs on Chrome 70/SingleFile 1.8.60

### ISSUE THREAD

**Issue by robwesterby** [gildas-lormeau/SingleFile#96]
With SingleFile enabled, when trying to load any Google Doc or Google Sheet, I always get the error:

Unable to load file / Try to load it again or send an error report.

This problem started 20/11/2018, I was already running Chrome 70, so suspect it may be related to the release of SingleFile dated 19 November 2018.

Error/Console output attached.

I've confirmed the issue affects two different Chrome profiles. I've also done a full profile reset & reinstall of Chrome (before I realised it was plugin-related!) Disabling SingleFile fixes the issue, and GDocs open normally.

---
Chrome Version 70.0.3538.110 (Official Build) (64-bit) on Windows 10 / SingleFile 1.8.60

![singlefile-bugreport1](https://user-images.githubusercontent.com/10925107/48772054-29da1e00-ecbb-11e8-974f-e02af80aece1.png)

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. It's fixed in the latest version with https://github.com/gildas-lormeau/SingleFile/commit/2f26f2b35fc4f6b0c69f2a7a04d9fdca6f7693d0.
