### ISSUE TITLE
"open saved pages in a new tab" don't get "open pages saved with SingleFile in the annotation editor" result 

### ISSUE THREAD

**Issue by dbc2rs** [gildas-lormeau/SingleFile#961]
**Describe the bug**
"open saved pages in a new tab" _don't get_ "open pages saved with SingleFile in the annotation editor" result.  
Though I am not sure this can be called a bug.  But it'll be great if I can have annotation function under settings below.  It's logical, too.  

**To Reproduce**
1. Under "*User interface*" settings, both "open saved pages in a new tab" and "auto-close the tab after the page is saved" are checked.
2. Under "*Annotation editor*" settings, "open pages saved with SingleFile in the annotation editor" is checked.
3. The resulting saved and opened page won't get annotation function.

**Expected behavior**
The resulting page should either show annotation tools, or add a line "Annotate Page" to SingleFile button right-click context menu.  
Incidentally opening saved page manually does get "Annotate the page..." in button context menu.

**Screenshots**
Upon request.

**Environment**
 - OS: Win7 Ultimate 64bit 
 - Browser: Firefox portableapps.com 64bit
 - Version: v100.0.2 

**Additional context**
You've probably heard enough of this but thank you again for the wonderful app.  Can't live without it now.  Much appreciated.

**Comment by gildas-lormeau** [comment]
Thank you for the kind words. I suppose there may be a misunderstanding somewhere in the way the options work.

 - When "open saved pages in a new tab" is enabled then every time you save a page with SingleFile, it will open the content of the saved page in a new tab
 - When "auto-close the tab after the page is saved" is enabled then every time you save a page with SingleFile, it will close the corresponding tab once the page is processed and saved by SingleFile

With these 2 options enabled, if I open a new tab, go to https://example.com/ and save the page then the page is saved, the corresponding tab is closed, and a new tab is created with the content of the saved page. That's the expected result.

- When "open pages saved with SingleFile in the annotation editor" then if I open an existing saved page from the filesystem then the page will be opened in the annotation editor.

With this option enabled, if I open a page saved with SingleFile from the filesystem (e.g. double-click from the explorer) then the saved page is opened in the annotation editor. That's the expected result.

Please let me know if there is any ambiguity or if I have missed something, do not hesitate to give me more details.

**Comment by dbc2rs** [comment]
Terribly sorry for the late response.  "For security reasons, SingleFile cannot save the page and open it (from the filesystem) in the annotation editor just after it has been saved." - This explains the behavior.  Thanks again for the patience.

**Comment by gildas-lormeau** [comment]
No problem, thank you for your answer :)
