### ISSUE TITLE
Cannot save local picture

### ISSUE THREAD

**Issue by marckruzik** [gildas-lormeau/SingleFile#963]
**Describe the bug**
I am working on Html reports generated locally, and I would like to use SingleFile to save those reports.
When pictures are included as base64 data, everything is fine.
But when pictures are from a local folder, they are not included in the SingleFile file.

**To Reproduce**

On a computer, create a local basic html file with a local picture, such as:
`<img src="pic/screenshot1.png" alt="">`
Open the local Html page on Firefox.
Try to save the Html page by using SingleFile.

The file produced by SingleFile does not display the picture.
By inspecting the code, we can see that the img contains no data:
`<img src="data:," alt="">`

**Expected behavior**
The file produced by SingleFile should contain the local picture, encoded as base64 data.

**Environment**
 - OS: Win10
 - Browser: Firefox v100.0.2 (64-bit)
 - Version: SingleFile v1.21.7

**Additional context**
Is that problem caused by a security reason, like an add-on cannot access a local file?

**Comment by gildas-lormeau** [comment]
This is a limitation of the browser. The simplest way to circumvent it is to use an HTTP server and to save pages from http://localhost. There is a list of one-liners here: https://gist.github.com/willurd/5720255

**Comment by marckruzik** [comment]
Thank you for the way to circumvent the problem!
