### ISSUE TITLE
Element's attribute remains set to the value it has when the page is saved.

### ISSUE THREAD

**Issue by metonel** [gildas-lormeau/SingleFile#964]
**Describe the bug**
On the page I spotted the issue, there is a menu (with id 'floating_menu') that has the display attribute set to 'none' and position to 'static' at first, and get set to display 'flex' and position 'fixed' after scrolling at least 90px from top, making it visible. These attributes are set via a function in a script at the bottom of the page's body.

When saving the page using SingleFile, if the position is on top and the menu isn't displayed, it won't appear on the saved file, and if the page is saved after scrolling and the menu is displayed, it will remain even when the position is at the top of the saved file.

**To Reproduce**
1. Go to '[this webpage](https://www.shopexpert.ro/)'
2. Save the page using SingleFile
3. Check the downloaded file
4. Go back to the web page and scroll at least 90px
5. Save the page using SingleFile
6. Check the downloaded file against the first saved file

**Expected behavior**
The menu on the file saved using SingleFile should have the same behaviour as the web page.

**Screenshots**
webpage without scrolling:
![image](https://user-images.githubusercontent.com/26932369/171127148-9d7c113a-e798-45d4-8aef-94bd2730bbb5.png)

webpage scrolled with the menu appeared:
![image](https://user-images.githubusercontent.com/26932369/171127508-5e99d5f6-9034-4701-b851-2273f566086a.png)

file saved while on the webpage the menu was displayed:
![image](https://user-images.githubusercontent.com/26932369/171127829-09eb6d3d-569f-4eed-be30-7c5538a687be.png)

**Environment**
 - OS: Win10 Pro
 - Browser: Chrome 101.0.4951.67
 - Version: 1.21.7

**Comment by gildas-lormeau** [comment]
The header height is changed in JavaScript when you scroll. There's nothing SingleFile can do to prevent this apart from including scripts but unfortunately this feature is not reliable.

**Comment by metonel** [comment]
I understand, thank you for your answer.
