### ISSUE TITLE
HTML is incorrectly changed when using Single File

### ISSUE THREAD

**Issue by david-littlefield** [gildas-lormeau/SingleFile#965]
Hi-there @gildas-lormeau,

When I download the YouTube Premium website, part of the html is incorrectly changed, and some of the css is lost. 

https://www.youtube.com/premium

The original html is:
```
<a id="restriction-apply-button" class="offer-details-link style-scope yt-unlimited-page-header-renderer" tabindex="0">
    <yt-formatted-string class="style-scope yt-unlimited-page-header-renderer" has-link-only_="">
        <a class="yt-simple-endpoint style-scope yt-formatted-string" spellcheck="false" dir="auto">
            Restrictions apply. Learn more here.
        </a>
    </yt-formatted-string>
</a>
```
But it gets changed to:
```
<a id="restriction-apply-button" class="offer-details-link style-scope yt-unlimited-page-header-renderer" tabindex="0">
    <yt-formatted-string class="style-scope yt-unlimited-page-header-renderer" has-link-only_="">
    </yt-formatted-string>
</a>
<a class="yt-simple-endpoint style-scope yt-formatted-string" spellcheck="false" dir="auto">
    Restrictions apply. Learn more here.
</a>
```
Or alternatively, it gets changed to:
```
<a class="yt-simple-endpoint style-scope yt-formatted-string" spellcheck="false" dir="auto">
    Restrictions apply. Learn more here.
</a>
```

I can just manually change the html and add the missing css, but I thought I'd check with you about it.

Is this a bug?

**Comment by gildas-lormeau** [comment]
Yes, it's a bug! But in YouTube... It's forbidden to include `<a>` tags into `<a>` tags (basically because it makes no sense to include links in links). I'll add a workaround to "fix" this bug (i.e. delete the inner `<a>` tag). For the record, that's the second time YouTube is reinventing HTML. They do the same with `<button>` tags. You can get more information about this kind of issue here: https://github.com/gildas-lormeau/SingleFile/issues/931#issuecomment-1110359724 (same issue but with `<p>` tags).

**Comment by david-littlefield** [comment]
Haha, good to know. You might need to transfer the classes from the inner <a> tag to the parent element. I had to do that to make everything work as expected.

Thanks, @gildas-lormeau!

**Comment by gildas-lormeau** [comment]
Indeed, that might be more complicated than expected because thumbnails at the right of the page are using the same innovative technique. If I remove the inner `<a>` tags, I also remove the thumbnails which is worse. I need to do more tests...

**Comment by david-littlefield** [comment]
@gildas-lormeau Gotcha. Ok, let me know if you need help with testing.

**Comment by david-littlefield** [comment]
Nice! Thanks, @gildas-lormeau
