### ISSUE TITLE
Problem saving images

### ISSUE THREAD

**Issue by deployx91** [gildas-lormeau/SingleFile#968]
**Describe the bug**
I have a problem when saving the page "https://ney5.xyz/manga-list.html?name=pandora", attached image, saved html, and configuration file.

**Attached**
[Page.zip](https://github.com/gildas-lormeau/SingleFile/files/8839362/Page.zip)

**Screenshots**
Original page:
![image](https://user-images.githubusercontent.com/106899543/172036125-674b3ccb-3131-4eba-bc0a-62a08fc1088e.png)

Page saved with SigleFile:
![image](https://user-images.githubusercontent.com/106899543/172036149-64eb40b6-b295-4477-afd9-b976e4948798.png)

**Environment**
 - OS: Win10 Pro
 - Browser: Chrome

**Comment by gildas-lormeau** [comment]
Thank you, I was able to reproduce the issue and fix it. The fix will be available in the version 1.21.10 which should be available for download in the coming hours. Note that you also must enable the option "Network > pass "Referer" header after a cross-origin request error" in SingleFile.
