### ISSUE TITLE
source code not in standard html format

### ISSUE THREAD

**Issue by david-littlefield** [gildas-lormeau/SingleFile#972]
There is no closing `</html>` tag in the source code, and the source code doesn't format correctly with the html formatter.

Is this intentional?

I have to open the html file in chrome, open the chrome dev tools, copy the `<html>` element, and paste it into the original file to get the standard html format.

**Comment by gildas-lormeau** [comment]
Yes, it is intentional. See https://github.com/gildas-lormeau/SingleFile/issues/967

**Comment by david-littlefield** [comment]
Awesome, thanks!
