### ISSUE TITLE
Articles from corriere.it can't be saved on Android/mobile

### ISSUE THREAD

**Issue by xandro0777** [gildas-lormeau/SingleFile#973]
Hi,

whenever I try to save an article there it will never finish :( Same article worked fine on desktop. Articles from many other sites can be saved even on mobile.

Example:
https://www.corriere.it/cronache/22_giugno_05/raduno-garda-urla-bandiere-ora-torna-l-africa-minore-molestata-ho-pianto-paura-18592042-e50d-11ec-8929-c5ad2690e50c.shtml?refresh_ce

**Comment by gildas-lormeau** [comment]
What browser are you using? I did a test with Firefox Nightly and it works fine for me.

**Comment by xandro0777** [comment]
... just as I wrote this report it worked suddenly. Have tried so many times before and it didn't work..

**Comment by gildas-lormeau** [comment]
Do you confirm you're using Firefox for Android?

**Comment by xandro0777** [comment]
I use Fennec from F-Droid, built from https://github.com/mozilla-mobile/fenix . Save pages in background is unchecked.

**Comment by gildas-lormeau** [comment]
If you can reproduce this problem easily, could you see if you can also reproduce it with Firefox for Android Nightly? At first sight, there are chances that it is a bug in the browser or maybe a conflict with another extension.

**Comment by gildas-lormeau** [comment]
Also, could you provide more details about the bug? Does it always crash at the same moment?

**Comment by xandro0777** [comment]
I am puzzled, right now everything works and I can't reproduce it.

**Comment by gildas-lormeau** [comment]
That's a bit weird indeed... This might also be related to a lack of RAM maybe? I just downloaded Firefox from F-Droid and I confirm it also works fine on my end.

**Comment by xandro0777** [comment]
The 6GB of RAM here should be enough too. Network latency seems pretty high here and when it failed earlier it would just hang in step 2.

**Comment by gildas-lormeau** [comment]
By default, there is no network timeout in SingleFile. It means that step 2/3 can take a long time in such conditions. If you're patient enough, it should work. It can take minutes though. Alternatively, you can set the "maximum download time" by enabling the option "Network  > set maximum download time" and adjusting "Network > maximum download time (s)" if necessary.

**Comment by gildas-lormeau** [comment]
I'm closing this issue. Feel free to reopen it if necessary.
