### ISSUE TITLE
Is there an option to do not save images?

### ISSUE THREAD

**Issue by gscholer** [gildas-lormeau/SingleFile#976]
Maybe it is weird, but sometimes an image is too large when is included in a html file using base64 code.

**Comment by gildas-lormeau** [comment]
You can block any type of resource via the `Network > blocked resources`, you can also decide to block a resource if it's larger than a given size, via `Network > set maximum size`. Globally speaking, if the size of saved pages are a problem for you, you can have a look at [SingelFileZ](https://github.com/gildas-lormeau/SingleFileZ).

**Comment by gscholer** [comment]
It worked as expected!
