### ISSUE TITLE
Could you support WebDAV?

### ISSUE THREAD

**Issue by WolfgangDpunkt** [gildas-lormeau/SingleFile#979]
**Describe the solution you'd like**
It would be great if this great tool could support WebDAV. This would suddenly make a much larger number of storage destinations usable. It would also be possible to use privacy-friendly self-hosted options, such as Nextcloud.

**Is your feature request related to a problem? Please describe.**
I am writing this because Google Drive works very unreliably for me (#978)

Thank you for considering this possibility.

By the way, there are browser extensions where the use of WebDAV works very well, maybe this example will help: https://github.com/floccusaddon/floccus

**Comment by gildas-lormeau** [comment]
I have to take a look on how to implement it, it might be much simpler than I initially expected. FYI, you're not the only one to request this feature (https://github.com/gildas-lormeau/SingleFileZ/issues/103).

**Comment by WolfgangDpunkt** [comment]
Wonderful! I am pleased that this could be a relevant feature for others.

I'm not a developer, but it seems to me that there are even ready-made libraries that could be used for this?

Maybe useful:

> [webdav](https://github.com/perry-mitchell/webdav-client) - WebDAV client written in JavaScript for NodeJS and the browser
[unifile](https://github.com/silexlabs/unifile) - NodeJS library to access cloud storage which supports WebDAV

([found here](https://github.com/fstanis/awesome-webdav#javascript))

**Comment by gildas-lormeau** [comment]
I'm trying to do some tests with OneDrive but I cannot get them to work for now. Do you use a browser extension uploading files to OneDrive? If not, which provider do you use?

**Comment by WolfgangDpunkt** [comment]
Thank you very much for your effort!
I have no experience with WebDAV via Onedrive, but I just tried it briefly and had no success either.

If I may make a suggestion: I would test it with Nextcloud, because most users who want to use WebDAV probably use a self-hosted cloud with Nextcloud (like me, for data protection and data sovereignty reasons).

If you're kind enough to try it out, here's an easy way:
Fortunately, there is a freely available demo version for Instant trial. I tried it successfully with the browser addon Floccus.

https://try.nextcloud.com

Automatic login data is generated that is valid for one hour.

- Note your username, password is always `demo`
- Click on "Files" in the top menu
- Now click on "Settings" in the bottom left-hand corner, the WebDAV address will be displayed.

Now you have all the necessary access data and can check via the Nextcloud interface whether the files have arrived.

**Comment by WolfgangDpunkt** [comment]
That sounds very good, I'm glad it's working out. I'm already looking forward to the new WebDAV function. Thanks a lot for your great work.

I at least use Nextcloud only as storage for syncing, so the saved web pages will end up on my mobile phone or desktop computer anyway.

**Comment by gildas-lormeau** [comment]
It's implemented in the version 1.21.17 which should be available for download on the Mozilla Store before the week-end hopefully.

**Comment by WolfgangDpunkt** [comment]
I am simply thrilled!
It works perfectly and super fast.

I would like to express my heartfelt thanks to you. Within a few days you have added this incredibly useful enhancement in a wonderful way.

And it even works to specify subdirectories, simply append the folder to the WebDAV url (.../SingleFileFolder). At least with Nextcloud, the saved articles reliably end up in the subfolder.

Once again, thank you very much.
You couldn't imagine better and faster support, even for a commercial product. You do enormously valuable work.

**Comment by gildas-lormeau** [comment]
I'm glad to hear that the feature works for you. In this respect, it's a bit of a win-win. Your help has also been invaluable, including the ability to test on NextCloud. By the way, note that you can also include directories in the template filename. For example, it is possible to group pages by day using this template `{date-locale}/{page-title} ({time-locale}).html`.

I thank you for your review and your donation. It is an effort I really appreciate.

Finally, I apologize for the poor and incomplete German translation, I'm just plain bad even though it's officially my first foreign language.

**Comment by WolfgangDpunkt** [comment]
Many thanks for the kind words and advice.
Übrigens ist die Übersetzung ziemlich gut sogar, mir ist noch kein größerer Fehler aufgefallen :-)
