### ISSUE TITLE
Feature: Support some tag in "Format the page for better readability"

### ISSUE THREAD

**Issue by MisteryMonster** [gildas-lormeau/SingleFile#988]
**Is your feature request related to a problem? Please describe.**
Current "Format the page for better readability" in Annotation do some basic job like "reader mode", but it lack of tag style "for better readability". Like `<code>` `<quote>` etc... to support some of this will be great!

**Describe the solution you'd like**
Currently I just insert an `<style>` tag to copy paste Firefox's `aboutreader.css`, in #257 it describe a user-script method I haven't test, but I think it's easer to inherit from Firefox.

**Describe alternatives you've considered (optional)**

**Additional context (optional)**

**Comment by gildas-lormeau** [comment]
Do you mean that you would like SingleFile to inject your own stylesheet into the page automatically when formatting the page?

**Comment by MisteryMonster** [comment]
I mean formatting the page could add some style to support pages with tag like `<code>` and `<quote>`, currently they doesn't have styles but Firefox Reader mode have.

![image](https://user-images.githubusercontent.com/40703811/176332883-5bf99e2d-aa2b-467a-9efe-5fee8828fea3.png)
![image](https://user-images.githubusercontent.com/40703811/176333356-51dc3de5-ca71-4931-9e3c-5cb3f51a7664.png)

**Comment by gildas-lormeau** [comment]
Thank you for the additional info. I updated the stylesheet, the fix will be available in the next version.
