### ISSUE TITLE
phpBB Forums

### ISSUE THREAD

**Issue by Matthaiks** [gildas-lormeau/SingleFile#99]
Hi!
SingleFile won't save pages on some phpBB forums. It stops at Step 2.
Examples:
https://www.vogons.org/
http://forums.mozillazine.org/

Firefox 63.0.3
SingleFile 1.8.67
Windows 10

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. It's fixed in the latest version with https://github.com/gildas-lormeau/SingleFile/commit/46087b69b3fd10380a7e58c60d320dcd690d9fe1
