### ISSUE TITLE
When SingleFile enable Code Verify add-on says Validation Failuere

### ISSUE THREAD

**Issue by MuhammetEminCakir** [gildas-lormeau/SingleFile#990]
**Describe the bug**
When SingleFile enable Code Verify add-on says Validation Failuere

**To Reproduce**
1. Download and activate the Code Verify add-on
2. Go to [WhatsApp](https://web.whatsapp.com/)

**Expected behavior**
No Validation Failure

**Screenshots**
![resim](https://user-images.githubusercontent.com/64583157/177042952-8e36a174-ca25-4de2-a075-975696d2399d.png)

**Environment**
 - OS: Windows 11 Pro
 - Browser: Firefox
 - Version: 102.0

**Additional context**
Code Verify add-on link: 
[Github (It's open-source)](https://github.com/facebookincubator/meta-code-verify)
[Firefox](https://addons.mozilla.org/firefox/addon/code-verify/)
[Chrome](https://chrome.google.com/webstore/detail/code-verify/llohflklppcaghdpehpbklhlfebooeog)
[Edge](https://microsoftedge.microsoft.com/addons/detail/code-verify/cpndjjealjjagamdecpipjfamiigaknk)

**Comment by gildas-lormeau** [comment]
From my point of view, this is a bug in the "Code Verify" add-on.

**Comment by gildas-lormeau** [comment]
I'm closing this issue but feel free to add a comment or reopen it if necessary.
