### ISSUE TITLE
Is it possible to integrate yt-dlp?

### ISSUE THREAD

**Issue by Horuyuki** [gildas-lormeau/SingleFile#992]
Is it possible to integrate yt-dlp into singlefile? So the video contents of the site can also be saved, regardless of the large size as a result. Thanks!

**Comment by gildas-lormeau** [comment]
That might be theoretically possible via the SingleFile Companion (https://github.com/gildas-lormeau/single-file-companion) but it wouldn't be easy, I guess.

**Comment by Horuyuki** [comment]
Thanks for the suggestion!

**Comment by gildas-lormeau** [comment]
Note that it's not implemented though :p
