### ISSUE TITLE
Generate unique pages with modulated code: separate html from css

### ISSUE THREAD

**Issue by rodriguezbrown** [gildas-lormeau/SingleFile#996]
**Is your feature request related to a problem? Please describe.**
1. One of the problems when the code generated... by the Single Page  extension is that the HTML becomes dense, bloated. To avoid this, it is recommended to use a modulated code.
2. This increases the code complexity in terms of project management, but on the other hand improves the readability of the generated code.

**Describe the solution you'd like**
I would like to have a modulated code at the end as: ```src/SingleFile.style.css```, ```index.html```. Sample here:

```index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Example</title>
        <link rel="stylesheet" href="src/SingleFile.style.css">
    </head>
    <body>
        <p>This is an example of a simple HTML page with one paragraph.</p>
    </body>
</html>
````

**Describe alternatives you've considered (optional)**
None.

**Additional context (optional)**
None.

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. Did you have a look at SingleFileZ, it solves this kind of issue, see https://github.com/gildas-lormeau/SingleFileZ

**Comment by rodriguezbrown** [comment]
@gildas-lormeau thank you for feedback, please close isse.

**Comment by gildas-lormeau** [comment]
You're welcome!
