### ISSUE TITLE
Single Page maybe solve this WIGC problem

### ISSUE THREAD

**Issue by rodriguezbrown** [gildas-lormeau/SingleFile#997]
**Is your feature request related to a problem? Please describe.**
> ["There should be APIs for integrating websites with the browser. For example, having a browser-powered “save” mechanism, that the browser can display however it wants to, and can in theory integrate with the OS on mobile - imagine searching for something on your phone and being shown a relevant reddit post you saved a year ago; this is currently not possible, but it could be possible if websites could integrate with the browser. A different but similar option would be to have a “save” HTML tag, making saving explicit and inherently user-initiated, but websites cannot sync these across browsers and instead you have to use the browser’s built-in sync features.
Anyway, I digress. So currently, we have “desktop notifications”. It’s a bit of a misnomer as they also work on mobile, but the idea is that they help integrate websites with the browser. Websites can also declare search engines to be used by the browser. Why not go a few steps further? 
This would significantly improve user experience for most web users. ..."](https://discourse.wicg.io/t/integrating-websites-with-the-browser/2512)

**Describe the solution you'd like**
I think if we could not integrate websites within the browser through SingleFile.

**Describe alternatives you've considered (optional)**
1. RSS - Really Simple Syndication:
2. cdn-p2p
3. IPFS
4. Twitter Bookmarks
5. Bookmarks

**Additional context (optional)**
- https://discourse.wicg.io/t/integrating-websites-with-the-browser/2512

**Comment by rodriguezbrown** [comment]
thank you for feedback, please close issue.

**Comment by gildas-lormeau** [comment]
You're welcome :)
