### ISSUE TITLE
[Feature Request] Increase Max Width of Readability Container

### ISSUE THREAD

**Issue by ragan-gum** [gildas-lormeau/SingleFile#998]
**Is your feature request related to a problem? Please describe.**
The readability function of the annotation tools provides valuable functionality. However, when I select readability mode, it appears to limit the width of the container for the content to about 500px which is frustrating.

**Describe the solution you'd like**
I would like the max-width of the .container for the readability function to be increased. Ideally to 800 or 1000 pixels.  It would be a dream if I could configure this on my own.

**Describe alternatives you've considered (optional)**
I usually handle overriding styles with violentmonkey; however, it does not work on extension pages.  I can manually change the width using dev tools but it's not usually worth the effort.

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. The width has been increased in the version `1.21.18`. I keep this issue open in order to add an option to set a custom width.

**Comment by gildas-lormeau** [comment]
@ragan-gum You're welcome, I'm glad to hear it :). 

I'm closing the issue because nobody complained about the change.
